"""ОЛМОНӢ → тоҷикӣ, «Гуфтор» A1: роҳи «Сохтмон» — вазъиятҳои 11–20 (29.09.2026).

Идомаи `_de-build-a1-packs.py` (қоидаҳо — `_de_packs_lib.py`). Транскрипсия баъд:
`node prisma/_de-fill-literal.mjs <slugs>`.

Аз ҷузвдони backend: python prisma/_de-build-a1-packs-2.py
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _de_packs_lib import *  # noqa: F401,F403

made = []
B = ["build"]
JOB_NOTE = "Касби худро гӯед — барнома онро аз ҳадафи шумо медонад."

# ═════════════════════ 11. Мушкил дар кор ═════════════════════
made.append(pack("problem_de_tg", "Probleme bei der Arbeit", "Мушкил дар кор", "⚠️", 11, B,
    "Чизе вайрон шуд, гум шуд ё шумо дер мондед. Мегӯед, ки чӣ шуд, узр мепурсед ва ба "
    "сардор занг мезанед, ки имрӯз омада наметавонед.",
    [
        ("Мушкил", [
            w("Problem", "мушкил", None),
            w("Kaputt", "вайрон", None),
            w("Strom", "барқ", None),
            w("Spät", "дер", None),
            w("Schlüssel", "калид", None),
            w("Krank", "бемор", None),
        ]),
        ("Чӣ шуд?", [
            t("Was ist los?", "Чӣ шуд?", "Бигӯ: барқ нест", "Kein Strom.", "Барқ нест.", ["Der Strom ist weg."]),
            t("Ist der Bohrer kaputt?", "Парма вайрон аст?", "Бигӯ: ҳа", "Ja.", "Ҳа.", ["Ja, er ist kaputt."]),
            t("Warum bist du zu spät?", "Чаро дер мондӣ?", "Бигӯ: автобус дер монд", "Der Bus war spät.",
              "Автобус дер монд.", ["Der Bus ist nicht gekommen."]),
        ]),
        ("Суханҳои кӯтоҳ", [
            s("Entschuldigung", "Бубахшед", None),
            s("Zu spät", "Дер", None),
            s("Verloren", "гум кардам", None),
            s("Ist kaputt", "вайрон шуд", None),
            s("Kein Wasser", "Об нест", None),
            s("Weiß nicht", "Намедонам", None),
        ]),
        ("Кулоҳ гум шуд", [
            t("Wo ist dein Helm?", "Кулоҳат куҷост?", "Бигӯ: гум кардам", "Ich habe ihn verloren.", "Гум кардам.",
              ["Verloren."]),
            t("Wie denn?", "Чӣ хел?", "Бигӯ: намедонам", "Ich weiß nicht.", "Намедонам.", ["Weiß nicht."]),
            t("Hol einen neuen aus dem Lager.", "Навашро аз анбор гир.", "Бигӯ: ташаккур, сардор", "Danke, Chef.",
              "Ташаккур, сардор.", ["Okay, Chef."]),
        ]),
        ("Чӣ вайрон шуд", [
            s("Entschuldigung, ich bin spät.", "Бубахшед, дер мондам.", None),
            s("Der Bohrer ist kaputt.", "Парма вайрон шуд.", None),
            s("Der Strom ist weg.", "Барқ рафт.", None),
            s("Das Kabel ist gerissen.", "Сим канда шуд.", None),
            s("Schlüssel ist weg.", "Калид гум шуд.", None),
            s("Was mache ich jetzt?", "Ҳоло чӣ кор кунам?", None),
        ]),
        ("Муколама: парма", [
            t("Warum arbeitest du nicht?", "Чаро кор намекунӣ?", "Бигӯ: парма вайрон шуд", "Der Bohrer ist kaputt.",
              "Парма вайрон шуд.", ["Der Bohrer geht nicht."]),
            t("Das Kabel?", "Сим?", "Бигӯ: ҳа, сим канда шуд", "Ja, das Kabel ist gerissen.",
              "Ҳа, сим канда шуд.", ["Ja."]),
            t("Okay, ich rufe den Elektriker.", "Хуб, барқчиро ҷеғ мезанам.", "Бипурс: ҳоло чӣ кор кунам?",
              "Was soll ich jetzt machen?", "Ҳоло чӣ кор кунам?", ["Was mache ich jetzt?"]),
        ]),
        ("Дер мемонам", [
            s("Ich bin heute krank.", "Ман имрӯз беморам.", None),
            s("Ich kann nicht kommen.", "Омада наметавонам.", None),
            s("Ich komme morgen.", "Фардо меоям.", None),
            s("Der Bus kam nicht.", "Автобус наомад.", None),
            s("Zwanzig Minuten später.", "Бист дақиқа дертар.", None),
            s("Tut mir leid.", "Бубахшед.", None),
        ]),
        ("Муколама: дар роҳ", [
            t("Hallo? Wo bist du?", "Алло? Куҷоӣ?", "Бигӯ: автобус наомад", "Der Bus ist nicht gekommen.",
              "Автобус наомад.", []),
            t("Wann kommst du?", "Кай меоӣ?", "Бигӯ: бист дақиқа дертар меоям", "Ich komme zwanzig Minuten später.",
              "Бист дақиқа дертар меоям.", ["In zwanzig Minuten."]),
            t("Okay, beeil dich.", "Хуб, шитоб кун.", "Бигӯ: бубахшед", "Tut mir leid.", "Бубахшед.",
              ["Entschuldigung."]),
        ]),
        ("Миссия: занг — беморам", [
            t("Hallo? Ja, bitte?", "Алло? Ҳа, марҳамат?", "Салом гӯй ва бигӯ, ки беморӣ",
              "Hallo Chef, ich bin krank.", "Салом сардор, ман беморам.", ["Chef, ich bin heute krank."]),
            t("Gute Besserung. Was hast du?", "Шифо ёбӣ. Чӣ шудааст?", "Бигӯ: таб дорам", "Ich habe Fieber.",
              "Таб дорам.", ["Hohes Fieber."]),
            t("Kannst du heute nicht kommen?", "Имрӯз омада наметавонӣ?", "Бигӯ: не, омада наметавонам",
              "Nein, ich kann nicht kommen.", "Не, омада наметавонам.", ["Nein."]),
            t("Okay, ruh dich aus. Komm morgen.", "Хуб, дам гир. Фардо биё.", "Бигӯ: хуб, фардо меоям",
              "Okay, ich komme morgen.", "Хуб, фардо меоям.", ["Danke, Chef."]),
        ]),
    ], mission_mode="call"))

# ═════════════════════ 12. Музд ва вақти кор ═════════════════════
made.append(pack("pay_de_tg", "Lohn und Arbeitszeit", "Музд ва вақти кор", "💵", 12, B,
    "Гап дар бораи пул: музд кай дода мешавад, пешпардохт, соатҳои иловагӣ (Überstunden) ва "
    "агар пул кам бошад — чӣ гуфтан лозим.",
    [
        ("Пул", [
            w("Lohn", "музд", None),
            w("Vorschuss", "пешпардохт", None),
            w("Überstunden", "соатҳои иловагӣ", None),
            w("Woche", "ҳафта", None),
            w("Monat", "моҳ", None),
            w("Konto", "ҳисоби бонкӣ", None),
        ]),
        ("Пулро гирифтӣ?", [
            t("Hast du deinen Lohn bekommen?", "Музди худро гирифтӣ?", "Бигӯ: не", "Nein.", "Не.",
              ["Nein, noch nicht."]),
            t("Brauchst du einen Vorschuss?", "Пешпардохт лозим?", "Бигӯ: ҳа, лутфан", "Ja, bitte.", "Ҳа, лутфан.",
              ["Ja."]),
            t("Hast du ein Konto?", "Ҳисоби бонкӣ дорӣ?", "Бигӯ: ҳа", "Ja.", "Ҳа.", ["Ja, ich habe ein Konto."]),
        ]),
        ("Суханҳои кӯтоҳ", [
            s("Der Zahltag", "рӯзи музд", None),
            s("Pro Stunde", "дар як соат", None),
            s("Jede Woche", "ҳар ҳафта", None),
            s("Jeden Monat", "ҳар моҳ", None),
            s("Zu wenig", "хеле кам", None),
            s("Geld fehlt", "Пул кам аст", None),
        ]),
        ("Пул кам аст", [
            t("Was ist das Problem?", "Мушкил чист?", "Бигӯ: пул кам аст", "Es fehlt Geld.", "Пул кам аст.",
              ["Mein Lohn ist zu wenig."]),
            t("Wie viel fehlt?", "Чӣ қадар кам?", "Бигӯ: дусад евро", "Zweihundert Euro.", "Дусад евро.", []),
            t("Okay, ich schaue nach.", "Хуб, месанҷам.", "Бигӯ: ташаккур", "Danke.", "Ташаккур.", []),
        ]),
        ("Саволҳо дар бораи музд", [
            s("Wann gibt es Lohn?", "Музд кай дода мешавад?", None),
            s("Mein Lohn ist falsch.", "Музди ман нодуруст аст.", None),
            s("Ich habe Überstunden gemacht.", "Ман соатҳои иловагӣ кор кардам.", None),
            s("Einen Vorschuss, bitte?", "Пешпардохт, лутфан?", None),
            s("Bitte aufs Konto.", "Лутфан, ба ҳисоби бонкӣ.", None),
            s("Ich möchte bar.", "Нақд мехоҳам.", None),
        ]),
        ("Муколама: соатҳои иловагӣ", [
            t("Hast du diesen Monat Überstunden gemacht?", "Ин моҳ соатҳои иловагӣ кор кардӣ?", "Бигӯ: ҳа, даҳ соат",
              "Ja, zehn Stunden.", "Ҳа, даҳ соат.", ["Zehn Stunden."]),
            t("Okay, zehn Stunden.", "Хуб, даҳ соат.", "Бипурс: музд кай дода мешавад?", "Wann gibt es Lohn?",
              "Музд кай дода мешавад?", ["Wann kommt der Lohn?"]),
            t("Am fünften.", "Панҷуми моҳ.", "Бигӯ: хуб, ташаккур", "Okay, danke.", "Хуб, ташаккур.", []),
        ]),
        ("Соат ва суғурта", [
            s("Wie viel pro Stunde?", "Дар як соат чанд?", None),
            s("Ich arbeite zehn Stunden.", "Ман даҳ соат кор мекунам.", None),
            s("Ist Sonntag frei?", "Якшанбе истироҳат аст?", None),
            s("Bekomme ich eine Lohnabrechnung?", "Варақаи музд мегирам?", "«Lohnabrechnung» — варақаи ҳисоби музд."),
            s("Bin ich versichert?", "Ман суғурта шудаам?", None),
            s("Bitte prüfen Sie das.", "Лутфан, инро санҷед.", None),
        ]),
        ("Муколама: соатҳо", [
            t("Wie viele Stunden arbeitest du am Tag?", "Дар як рӯз чанд соат кор мекунӣ?", "Бигӯ: даҳ соат",
              "Zehn Stunden.", "Даҳ соат.", ["Ich arbeite zehn Stunden."]),
            t("Sonntag ist frei.", "Якшанбе истироҳат.", "Бипурс: ман суғурта шудаам?", "Bin ich versichert?",
              "Ман суғурта шудаам?", []),
            t("Ja, natürlich.", "Ҳа, албатта.", "Бигӯ: хуб", "Gut.", "Хуб.", ["Okay."]),
        ]),
        ("Миссия: музд кам аст", [
            t("Ja, bitte? Was ist das Problem?", "Ҳа, марҳамат? Мушкил чист?", "Бигӯ: музди ман нодуруст аст",
              "Mein Lohn ist falsch.", "Музди ман нодуруст аст.", ["Es fehlt Geld."]),
            t("Wie viel fehlt?", "Чӣ қадар кам?", "Бигӯ: сесад евро", "Dreihundert Euro.", "Сесад евро.", []),
            t("Hast du Überstunden gemacht?", "Соатҳои иловагӣ кор кардӣ?", "Бигӯ: ҳа, понздаҳ соат",
              "Ja, fünfzehn Stunden.", "Ҳа, понздаҳ соат.", ["Ja."]),
            t("Okay, ich prüfe das.", "Хуб, инро месанҷам.", "Ташаккур гӯй", "Vielen Dank.", "Ташаккури зиёд.",
              ["Danke."]),
        ]),
    ]))

# ═════════════════════ 13. Роҳ то кор ═════════════════════
made.append(pack("commute_de_tg", "Der Weg zur Arbeit", "Роҳ то кор", "🚌", 13, B,
    "Ба кор бо автобус, метро (U-Bahn) ё мошини ширкат меравед. Мепурсед, ки кадом автобус, "
    "истгоҳ куҷост ва чипта чанд пул аст.",
    [
        ("Нақлиёт", [
            w("Bus", "автобус", None),
            w("Bahn", "қатора, метро", None),
            w("Haltestelle", "истгоҳ", None),
            w("Fahrkarte", "чипта", None),
            w("Taxi", "такси", None),
            w("Firmenwagen", "мошини ширкат", "Мошине, ки коргаронро ба объект мебарад."),
        ]),
        ("Бо чӣ меоӣ?", [
            t("Wann kommt der Firmenwagen?", "Мошини ширкат кай меояд?", "Бигӯ: соати ҳафт", "Um sieben Uhr.",
              "Соати ҳафт.", ["Um sieben."]),
            t("Kommst du mit der Bahn?", "Бо қатора меоӣ?", "Бигӯ: не, бо автобус", "Nein, mit dem Bus.",
              "Не, бо автобус.", ["Mit dem Bus."]),
            t("Hast du eine Fahrkarte?", "Чипта дорӣ?", "Бигӯ: ҳа", "Ja.", "Ҳа.", ["Ja, habe ich."]),
        ]),
        ("Суханҳои кӯтоҳ", [
            s("Welcher Bus?", "Кадом автобус?", None),
            s("Welche Haltestelle?", "Кадом истгоҳ?", None),
            s("Hier aussteigen", "Ин ҷо фуромадан", None),
            w("Umsteigen", "иваз кардан (нақлиёт)", None),
            s("Die Endstation", "истгоҳи охир", None),
            s("Sehr voll", "Хеле серодам", None),
        ]),
        ("Истгоҳ куҷост?", [
            t("Wohin fahren Sie?", "Ба куҷо меравед?", "Бигӯ: ба Берлин", "Nach Berlin.", "Ба Берлин.",
              ["Ich fahre nach Berlin."]),
            t("Die Linie zwölf.", "Хатти дувоздаҳ.", "Бипурс: истгоҳ куҷост?", "Wo ist die Haltestelle?",
              "Истгоҳ куҷост?", []),
            t("Gegenüber.", "Дар муқобил.", "Бигӯ: ташаккур", "Danke.", "Ташаккур.", []),
        ]),
        ("Дар автобус", [
            s("Fährt er zum Bahnhof?", "Ба вокзал меравад?", None),
            s("Ich habe keine Fahrkarte.", "Ман чипта надорам.", None),
            s("Ich steige hier aus.", "Ман ин ҷо мефароям.", None),
            s("Der Wagen ist weg.", "Мошин рафт.", None),
            s("Es gibt Stau.", "Роҳ банд аст.", None),
            s("Wie viele Stationen?", "Чанд истгоҳ?", None),
        ]),
        ("Муколама: автобус", [
            t("Wohin?", "Ба куҷо?", "Бипурс: автобус ба вокзал меравад?", "Fährt der Bus zum Bahnhof?",
              "Автобус ба вокзал меравад?", ["Zum Bahnhof?"]),
            t("Ja.", "Ҳа.", "Бипурс: чанд истгоҳ?", "Wie viele Stationen?", "Чанд истгоҳ?", []),
            t("Zehn Stationen.", "Даҳ истгоҳ.", "Бигӯ: ташаккур", "Danke schön.", "Ташаккур.", ["Danke."]),
        ]),
        ("Такси", [
            s("Rufst du ein Taxi?", "Такси ҷеғ мезанӣ?", None),
            s("Ich fahre zur Baustelle.", "Ман ба объект меравам.", None),
            s("Hier ist die Adresse.", "Ана суроға.", None),
            s("Bitte halten Sie hier.", "Лутфан, ин ҷо истед.", None),
            s("Was kostet die Fahrt?", "Роҳ чанд пул аст?", None),
            s("Es gab einen Unfall.", "Садама шуд.", None),
        ]),
        ("Муколама: такси", [
            t("Wohin fahren wir?", "Ба куҷо меравем?", "Бигӯ: ана суроға", "Hier ist die Adresse.", "Ана суроға.",
              ["Zu dieser Adresse."]),
            t("Okay. Wir sind da.", "Хуб. Расидем.", "Бигӯ: лутфан, ин ҷо истед", "Bitte halten Sie hier.",
              "Лутфан, ин ҷо истед.", ["Hier, bitte."]),
            t("Das macht fünfundzwanzig Euro.", "Бисту панҷ евро мешавад.", "Бигӯ: марҳамат", "Bitte schön.",
              "Марҳамат.", ["Hier, bitte."]),
        ]),
        ("Миссия: мошини ширкат рафт", [
            t("Hallo, wo bist du? Der Wagen ist weg.", "Алло, куҷоӣ? Мошин рафт.",
              "Бигӯ: мошини ширкатро аз даст додам", "Ich habe den Wagen verpasst.",
              "Мошини ширкатро аз даст додам.", []),
            t("Nimm den Bus.", "Бо автобус биё.", "Бипурс: кадом автобус?", "Welcher Bus?", "Кадом автобус?", []),
            t("Die Linie zweiundvierzig.", "Хатти чилу ду.", "Бигӯ: хуб, ҳозир меоям", "Okay, ich komme sofort.",
              "Хуб, ҳозир меоям.", ["Okay."]),
            t("Beeil dich, die Arbeit hat angefangen.", "Шитоб кун, кор сар шуд.", "Бигӯ: роҳ банд аст",
              "Es gibt Stau.", "Роҳ банд аст.", ["Viel Verkehr."]),
        ]),
    ]))

# ═════════════════════ 14. Иҷораи хона (умумӣ) ═════════════════════
made.append(pack("rent_de_tg", "Eine Wohnung mieten", "Иҷораи хона", "🏠", 14, [],
    "Хона ё ҳуҷра иҷора мегиред: нарх, гарав (Kaution), пули барқу об. Баъд — агар чизе "
    "вайрон шавад, ба соҳибхона занг мезанед.",
    [
        ("Хона", [
            w("Wohnung", "хона (квартира)", None),
            w("Zimmer", "ҳуҷра", None),
            w("Miete", "иҷорапулӣ", None),
            w("Kaution", "гарав", "Пуле, ки пеш аз даромадан медиҳед ва баъд бармегардад."),
            w("Vermieter", "соҳибхона", None),
            w("Küche", "ошхона", None),
        ]),
        ("Хона меҷӯед?", [
            t("Suchen Sie eine Wohnung?", "Хона меҷӯед?", "Бигӯ, ки ҳа", "Ja.", "Ҳа.", ["Ja, ich suche eine Wohnung."]),
            t("Wie viele Personen sind Sie?", "Чанд нафаред?", "Бигӯ: се нафар", "Drei Personen.", "Се нафар.",
              ["Wir sind drei."]),
            t("Möbliert?", "Бо мебел?", "Бигӯ: ҳа, бо мебел", "Ja, möbliert.", "Ҳа, бо мебел.", ["Ja."]),
        ]),
        ("Суханҳои кӯтоҳ", [
            s("Zwei Zimmer", "ду ҳуҷра", None),
            s("Die Miete", "иҷорапулӣ", None),
            s("Mit Nebenkosten", "бо пули барқу об", "«Nebenkosten» — пули барқ, об ва гармӣ."),
            w("Möbliert", "бо мебел", None),
            s("Zentral gelegen", "Дар марказ", None),
            s("Warmes Wasser", "оби гарм", None),
        ]),
        ("Нарх", [
            t("Die Miete ist fünfhundert Euro.", "Иҷора панҷсад евро.", "Бипурс: бо пули барқу об?",
              "Mit Nebenkosten?", "Бо пули барқу об?", ["Sind die Nebenkosten dabei?"]),
            t("Nein, ohne Nebenkosten.", "Не, бе пули барқу об.", "Бигӯ: хеле қимат", "Das ist zu teuer.",
              "Хеле қимат.", ["Zu teuer."]),
            t("Aber nah am Bahnhof.", "Вале наздики вокзал.", "Бигӯ: хуб, фикр мекунам", "Okay, ich überlege.",
              "Хуб, фикр мекунам.", ["Okay."]),
        ]),
        ("Саволҳо дар бораи хона", [
            s("Was kostet die Miete?", "Иҷора чанд аст?", None),
            s("Gibt es eine Kaution?", "Гарав ҳаст?", None),
            s("Kann ich sie sehen?", "Онро дида метавонам?", None),
            s("Wie viele Zimmer?", "Чанд ҳуҷра?", None),
            s("Gibt es warmes Wasser?", "Оби гарм ҳаст?", None),
            s("Wann kann ich einziehen?", "Кай кӯчида метавонам?", None),
        ]),
        ("Муколама: хонаро мебинем", [
            t("Möchten Sie die Wohnung sehen?", "Хонаро дидан мехоҳед?", "Бигӯ: ҳа, лутфан", "Ja, bitte.",
              "Ҳа, лутфан.", []),
            t("Hier ist die Küche und hier das Zimmer.", "Ин ошхона ва ин ҳуҷра.", "Бипурс: оби гарм ҳаст?",
              "Gibt es warmes Wasser?", "Оби гарм ҳаст?", []),
            t("Ja, natürlich.", "Ҳа, албатта.", "Бипурс: гарав ҳаст?", "Gibt es eine Kaution?", "Гарав ҳаст?", []),
        ]),
        ("Дар хона мушкил", [
            s("Der Wasserhahn tropft.", "Ҷӯмак мечакад.", None),
            s("Die Heizung geht nicht.", "Гармкунак кор намекунад.", None),
            s("Die Miete ist bezahlt.", "Иҷора пардохт шуд.", None),
            s("Ich brauche einen Vertrag.", "Ба ман шартнома лозим.", None),
            s("Wer hat den Schlüssel?", "Калид дар дасти кист?", None),
            s("Bitte den Vermieter anrufen.", "Лутфан, ба соҳибхона занг занед.", None),
        ]),
        ("Муколама: гармкунак", [
            t("Hallo, bitte?", "Алло, марҳамат?", "Бигӯ: гармкунак кор намекунад", "Die Heizung geht nicht.",
              "Гармкунак кор намекунад.", ["Die Heizung ist kaputt."]),
            t("Seit wann?", "Аз кай?", "Бигӯ: аз дирӯз", "Seit gestern.", "Аз дирӯз.", []),
            t("Okay, morgen kommt ein Handwerker.", "Хуб, фардо усто меояд.", "Бигӯ: ташаккур", "Danke.",
              "Ташаккур.", ["Vielen Dank."]),
        ]),
        ("Миссия: занг барои хона", [
            t("Hallo? Ja, bitte?", "Алло? Ҳа, марҳамат?", "Бигӯ: салом, хона меҷӯям",
              "Hallo, ich suche eine Wohnung.", "Салом, ман хона меҷӯям.", ["Ich suche eine Wohnung."]),
            t("Wir haben eine Zweizimmerwohnung.", "Хонаи дуҳуҷрагӣ дорем.", "Бипурс: иҷора чанд аст?",
              "Wie hoch ist die Miete?", "Иҷора чанд аст?", ["Was kostet die Miete?"]),
            t("Sechshundert Euro.", "Шашсад евро.", "Бипурс: хонаро дида метавонам?",
              "Kann ich die Wohnung sehen?", "Хонаро дида метавонам?", []),
            t("Ja, kommen Sie morgen Abend.", "Ҳа, фардо бегоҳ биёед.", "Бигӯ: хуб, ташаккур", "Okay, danke.",
              "Хуб, ташаккур.", ["Vielen Dank."]),
        ]),
    ], mission_mode="call"))

# ═════════════════════ 15. Занг ба бригадир ═════════════════════
made.append(pack("call_de_tg", "Den Chef anrufen", "Занг ба бригадир", "📞", 15, B,
    "Бо телефон бо сардор гап мезанед: садо намеояд, дар роҳ мондед, суроға мехоҳед ё як "
    "рӯз рухсатӣ мепурсед. Миссия — занги воқеӣ.",
    [
        ("Телефон", [
            w("Hallo", "алло", None),
            w("Handy", "телефони мобилӣ", None),
            w("Nachricht", "паём", None),
            w("Nummer", "рақам", None),
            w("Akku", "заряд (батарея)", None),
            w("Später", "баъдтар", None),
        ]),
        ("Маро мешунавӣ?", [
            t("Hallo? Wer ist da?", "Алло? Кӣ ҳаст?", "Бигӯ: коргари нав", "Der neue Arbeiter.", "Коргари нав.",
              ["Ich bin der neue Arbeiter."]),
            t("Hörst du mich?", "Маро мешунавӣ?", "Бигӯ: ҳа, мешунавам", "Ja, ich höre dich.", "Ҳа, мешунавам.",
              ["Ja."]),
            t("Ich rufe später an.", "Баъдтар занг мезанам.", "Бигӯ: хуб", "Okay.", "Хуб.", ["Okay, Chef."]),
        ]),
        ("Суханҳои телефонӣ", [
            s("Schlechte Verbindung", "Пайвасти бад", None),
            s("Bitte zurückrufen", "Лутфан, занг занед", None),
            s("Nachricht schicken", "Паём фиристодан", None),
            s("Akku leer", "Заряд тамом", None),
            s("Einen Moment", "Як лаҳза", None),
            s("Kurz Zeit?", "Як лаҳза вақт доред?", None),
        ]),
        ("Садо намеояд", [
            t("Hallo? Hallo?", "Алло? Алло?", "Бигӯ: ҳеҷ чиз намешунавам", "Ich höre nichts.",
              "Ҳеҷ чиз намешунавам.", ["Ich höre Sie nicht."]),
            t("Und jetzt?", "Ҳоло чӣ?", "Бигӯ: ҳа, ҳоло хуб", "Ja, jetzt ist es gut.", "Ҳа, ҳоло хуб.", ["Ja."]),
            t("Gut, hör zu.", "Хуб, гӯш кун.", "Бигӯ: гӯш мекунам", "Ich höre.", "Гӯш мекунам.", ["Ja, bitte."]),
        ]),
        ("Дар роҳ", [
            s("Chef, haben Sie Zeit?", "Сардор, вақт доред?", None),
            s("Ich stehe im Stau.", "Дар роҳбандӣ мондам.", None),
            s("Schicken Sie die Adresse.", "Суроғаро фиристед.", None),
            s("Das ist meine Nummer.", "Ин рақами ман.", None),
            s("Ich rufe später an.", "Баъдтар занг мезанам.", None),
            s("Der Akku ist leer.", "Заряд тамом шуд.", None),
        ]),
        ("Муколама: суроға", [
            t("Hallo, wo bist du?", "Алло, куҷоӣ?", "Бигӯ: дар роҳбандӣ мондам", "Ich stehe im Stau.",
              "Дар роҳбандӣ мондам.", ["Ich bin unterwegs."]),
            t("Kennst du die Adresse?", "Суроғаро медонӣ?", "Бигӯ: не, суроғаро фиристед",
              "Nein, schicken Sie mir die Adresse.", "Не, суроғаро фиристед.", ["Nein, bitte schicken."]),
            t("Okay, ich schicke sie jetzt.", "Хуб, ҳозир мефиристам.", "Бигӯ: ташаккур, сардор", "Danke, Chef.",
              "Ташаккур, сардор.", []),
        ]),
        ("Рухсатӣ", [
            s("Morgen komme ich nicht.", "Фардо намеоям.", None),
            s("Meine Tochter ist krank.", "Духтарам бемор аст.", None),
            s("Einen Tag frei, bitte.", "Лутфан, як рӯз рухсатӣ.", None),
            s("Ich komme am Montag.", "Душанбе меоям.", None),
            s("Ich habe Ihre Nachricht.", "Паёматонро гирифтам.", None),
            s("Okay, alles klar.", "Хуб, фаҳмо шуд.", None),
        ]),
        ("Муколама: рухсатӣ", [
            t("Hallo, ja?", "Алло, ҳа?", "Бигӯ: ба ман як рӯз рухсатӣ лозим", "Ich brauche einen Tag frei.",
              "Ба ман як рӯз рухсатӣ лозим.", ["Einen Tag frei, bitte."]),
            t("Warum?", "Чаро?", "Бигӯ: духтарам бемор аст", "Meine Tochter ist krank.", "Духтарам бемор аст.", []),
            t("Gute Besserung. Okay.", "Шифо ёбад. Хуб.", "Бигӯ: ташаккур, сардор", "Danke, Chef.",
              "Ташаккур, сардор.", ["Vielen Dank."]),
        ]),
        ("Миссия: занг ба сардор", [
            t("Hallo?", "Алло?", "Салом гӯй ва бипурс: вақт доред?", "Hallo Chef, haben Sie Zeit?",
              "Салом сардор, вақт доред?", ["Chef, haben Sie Zeit?"]),
            t("Ja, sag.", "Ҳа, гӯй.", "Бигӯ: фардо омада наметавонам", "Morgen kann ich nicht kommen.",
              "Фардо омада наметавонам.", ["Ich kann morgen nicht kommen."]),
            t("Was ist passiert?", "Чӣ шуд?", "Бигӯ: духтарам бемор аст", "Meine Tochter ist krank.",
              "Духтарам бемор аст.", []),
            t("Okay, komm am Montag.", "Хуб, душанбе биё.", "Бигӯ: хуб, душанбе меоям", "Okay, ich komme am Montag.",
              "Хуб, душанбе меоям.", ["Danke."]),
        ]),
    ], mission_mode="call"))

# ═════════════════════ 16. Ҳуҷҷатҳо ва полис (умумӣ) ═════════════════════
made.append(pack("docs_de_tg", "Papiere und Polizei", "Ҳуҷҷатҳо ва полис", "🪪", 16, [],
    "Полис ҳуҷҷат мепурсад ё шумо ба идораи хориҷиён (Ausländerbehörde) меравед. Шиноснома, "
    "иҷозати истиқомат ва иҷозати кор нишон медиҳед.",
    [
        ("Ҳуҷҷатҳо", [
            w("Pass", "шиноснома", None),
            w("Ausweis", "ҳуҷҷати шахсият", None),
            w("Aufenthaltstitel", "иҷозати истиқомат", None),
            w("Polizei", "полис", None),
            w("Adresse", "суроға", None),
            w("Formular", "форма (варақа)", None),
        ]),
        ("Ҳуҷҷататон", [
            t("Ihren Ausweis, bitte.", "Ҳуҷҷататон, лутфан.", "Бигӯ: марҳамат", "Bitte schön.", "Марҳамат.",
              ["Hier, bitte."]),
            t("Sind Sie Deutscher?", "Шумо олмонӣ ҳастед?", "Бигӯ: не, тоҷикам", "Nein, ich bin Tadschike.",
              "Не, ман тоҷикам.", ["Nein."]),
            t("Haben Sie einen Aufenthaltstitel?", "Иҷозати истиқомат доред?", "Бигӯ: ҳа", "Ja.", "Ҳа.",
              ["Ja, habe ich."]),
        ]),
        ("Суханҳои кӯтоҳ", [
            s("Mein Pass", "шиносномаи ман", None),
            s("Die Arbeitserlaubnis", "иҷозати кор", None),
            s("Meine Adresse", "суроғаи ман", None),
            s("Nicht verstanden", "Нафаҳмидам", None),
            s("Einen Dolmetscher", "тарҷумон", None),
            s("Einen Moment", "Як лаҳза", None),
        ]),
        ("Санҷиши ҳуҷҷат", [
            t("Wo ist Ihr Pass?", "Шиносномаатон куҷост?", "Бигӯ: шиносномаи ман ин ҷо", "Mein Pass ist hier.",
              "Шиносномаи ман ин ҷо.", ["Hier, bitte."]),
            t("Haben Sie eine Arbeitserlaubnis?", "Иҷозати кор доред?", "Бигӯ: ҳа", "Ja.", "Ҳа.", ["Ja, habe ich."]),
            t("Wie ist Ihre Adresse?", "Суроғаатон чист?", "Бигӯ: як лаҳза", "Einen Moment.", "Як лаҳза.",
              ["Moment, bitte."]),
        ]),
        ("Ман кистам", [
            s("Ich bin aus Tadschikistan.", "Ман аз Тоҷикистонам.", None),
            s("Ich habe einen Aufenthaltstitel.", "Ман иҷозати истиқомат дорам.", None),
            s("Der Pass ist daheim.", "Шиноснома дар хона.", None),
            s("Mein Deutsch ist schlecht.", "Олмониам бад аст.", None),
            s("Ich brauche einen Dolmetscher.", "Ба ман тарҷумон лозим.", None),
            s("Darf ich telefonieren?", "Занг зада метавонам?", None),
        ]),
        ("Муколама: полис", [
            t("Warum haben Sie keinen Ausweis?", "Чаро ҳуҷҷат надоред?", "Бигӯ: шиносномаам дар хона",
              "Mein Pass ist zu Hause.", "Шиносномаам дар хона.", ["Zu Hause."]),
            t("Wo wohnen Sie?", "Дар куҷо зиндагӣ мекунед?", "Бигӯ: дар Берлин", "In Berlin.", "Дар Берлин.",
              ["Ich wohne in Berlin."]),
            t("Verstehen Sie Deutsch?", "Олмонӣ мефаҳмед?", "Бигӯ: каме", "Ein bisschen.", "Каме.",
              ["Ein bisschen Deutsch."]),
        ]),
        ("Идораи хориҷиён", [
            s("Ich habe einen Termin.", "Ман навбат дорам.", None),
            s("Wo ist die Ausländerbehörde?", "Идораи хориҷиён куҷост?", None),
            s("Brauche ich ein Foto?", "Ба ман акс лозим?", None),
            s("Welche Papiere brauche ich?", "Кадом ҳуҷҷатҳо лозим?", None),
            s("Das Formular ist fertig.", "Форма тайёр аст.", None),
            s("Wie lange dauert das?", "Чӣ қадар вақт мегирад?", None),
        ]),
        ("Муколама: навбат", [
            t("Bitte, haben Sie einen Termin?", "Марҳамат, навбат доред?", "Бигӯ: ҳа, ман навбат дорам",
              "Ja, ich habe einen Termin.", "Ҳа, ман навбат дорам.", ["Ja."]),
            t("Haben Sie das Formular ausgefüllt?", "Формаро пур кардед?", "Бигӯ: ҳа, пур кардам",
              "Ja, ich habe es ausgefüllt.", "Ҳа, пур кардам.", ["Ja."]),
            t("Gut, wir brauchen auch zwei Fotos.", "Хуб, ду акс ҳам лозим.", "Бипурс: чӣ қадар вақт мегирад?",
              "Wie lange dauert das?", "Чӣ қадар вақт мегирад?", []),
        ]),
        ("Миссия: санҷиши полис", [
            t("Guten Tag. Ausweiskontrolle.", "Рӯз ба хайр. Санҷиши ҳуҷҷат.", "Бигӯ: марҳамат, шиноснома",
              "Bitte, mein Pass.", "Марҳамат, шиносномаи ман.", ["Bitte schön."]),
            t("Woher kommen Sie?", "Аз куҷоед?", "Бигӯ: аз Тоҷикистонам", "Aus Tadschikistan.", "Аз Тоҷикистон.",
              ["Ich komme aus Tadschikistan."]),
            t("Haben Sie einen Aufenthaltstitel?", "Иҷозати истиқомат доред?", "Бигӯ: ҳа, дорам",
              "Ja, ich habe einen.", "Ҳа, дорам.", ["Ja."]),
            t("Was machen Sie hier?", "Ин ҷо чӣ кор мекунед?", "Касби худро гӯед", "Ich bin {job}.",
              "Ман {job_tg} ҳастам.", []),
        ]),
    ]))

# ═════════════════════ 17. Вагонча ва ҳамкорон ═════════════════════
made.append(pack("crew_de_tg", "Pause im Container", "Вагонча ва ҳамкорон", "☕", 17, B,
    "Танаффус дар вагонча: чой, хӯрок ва гапи оддӣ бо ҳамкорон — оила, ватан, охири ҳафта.",
    [
        ("Танаффус", [
            w("Tee", "чой", None),
            w("Essen", "хӯрок", None),
            w("Kollege", "ҳамкор", None),
            w("Familie", "оила", None),
            w("Heimat", "ватан", None),
            w("Urlaub", "таътил", None),
        ]),
        ("Чой мехоҳӣ?", [
            t("Möchtest du Tee?", "Чой мехоҳӣ?", "Бигӯ: ҳа, лутфан", "Ja, bitte.", "Ҳа, лутфан.", ["Gerne."]),
            t("Mit Zucker?", "Бо қанд?", "Бигӯ: не, ташаккур", "Nein, danke.", "Не, ташаккур.", ["Ohne Zucker."]),
            t("Hast du Hunger?", "Гуруснаӣ?", "Бигӯ: ҳа, хеле", "Ja, sehr.", "Ҳа, хеле.", ["Ja, großen Hunger."]),
        ]),
        ("Суханҳои кӯтоҳ", [
            s("Guten Appetit", "Ош шавад", "Пеш аз хӯрок мегӯянд."),
            s("Sehr lecker", "Хеле болаззат", None),
            s("Meine Familie", "оилаи ман", None),
            s("Verheiratet?", "Оиладорӣ?", None),
            s("Gehen wir", "Равем", None),
            s("Sehr müde", "Хеле хаста", None),
        ]),
        ("Оила", [
            t("Guten Appetit!", "Ош шавад!", "Бигӯ: ташаккур", "Danke.", "Ташаккур.", ["Danke, dir auch."]),
            t("Bist du verheiratet?", "Оиладорӣ?", "Бигӯ: ҳа", "Ja.", "Ҳа.", ["Ja, ich bin verheiratet."]),
            t("Wo ist deine Familie?", "Оилаат куҷост?", "Бигӯ: оилаам дар Тоҷикистон",
              "Meine Familie ist in Tadschikistan.", "Оилаам дар Тоҷикистон.", ["In Tadschikistan."]),
        ]),
        ("Дар бораи худам", [
            s("Ich habe zwei Kinder.", "Ман ду фарзанд дорам.", None),
            s("Ich vermisse meine Heimat.", "Ватанамро соғиндам.", None),
            s("Das Essen ist lecker.", "Хӯрок болаззат аст.", None),
            s("Im Urlaub nach Hause.", "Дар таътил — ба хона.", None),
            s("Was machst du Samstag?", "Шанбе чӣ кор мекунӣ?", None),
            s("Spielst du Fußball?", "Футбол бозӣ мекунӣ?", None),
        ]),
        ("Муколама: фарзандон", [
            t("Wie viele Kinder hast du?", "Чанд фарзанд дорӣ?", "Бигӯ: ду фарзанд дорам", "Ich habe zwei Kinder.",
              "Ду фарзанд дорам.", ["Zwei."]),
            t("Vermisst du sie?", "Онҳоро соғинӣ?", "Бигӯ: ҳа, хеле", "Ja, sehr.", "Ҳа, хеле.", ["Sehr."]),
            t("Wann fährst du nach Hause?", "Кай ба хона меравӣ?", "Бигӯ: дар таътил", "Im Urlaub.", "Дар таътил.",
              ["Im Urlaub fahre ich heim."]),
        ]),
        ("Гапи оддӣ", [
            s("Heute bin ich müde.", "Имрӯз хастаам.", None),
            s("Machen wir Pause.", "Каме дам гирем.", None),
            s("Ich habe Tee gemacht.", "Чой дам кардам.", None),
            s("Wer arbeitet morgen?", "Фардо кӣ кор мекунад?", None),
            s("Woher kommst du?", "Аз куҷоӣ?", None),
            s("Dein Deutsch ist gut.", "Олмониат хуб аст.", None),
        ]),
        ("Муколама: шиносоӣ", [
            t("Woher kommst du?", "Аз куҷоӣ?", "Бигӯ: аз Тоҷикистонам", "Aus Tadschikistan.", "Аз Тоҷикистон.",
              ["Ich komme aus Tadschikistan."]),
            t("Dein Deutsch ist gut!", "Олмониат хуб аст!", "Бигӯ: ташаккур, каме медонам",
              "Danke, ein bisschen.", "Ташаккур, каме.", ["Danke."]),
            t("Was machst du am Wochenende?", "Охири ҳафта чӣ кор мекунӣ?", "Бигӯ: дам мегирам", "Ich ruhe mich aus.",
              "Дам мегирам.", ["Ich bleibe zu Hause."]),
        ]),
        ("Миссия: танаффус", [
            t("Komm, trinken wir Tee!", "Биё, чой нӯшем!", "Бигӯ: хуб, раҳмат", "Gerne, danke.", "Бо хурсандӣ, раҳмат.",
              ["Okay, danke."]),
            t("Wie geht es dir? Bist du müde?", "Чӣ хелӣ? Хастаӣ?", "Бигӯ: ҳа, хеле хастаам", "Ja, sehr müde.",
              "Ҳа, хеле хастаам.", ["Ja, ich bin müde."]),
            t("Wie geht es deiner Familie?", "Оилаат чӣ хел?", "Бигӯ: хуб, ташаккур", "Gut, danke.", "Хуб, ташаккур.",
              ["Allen geht es gut."]),
            t("So, die Pause ist vorbei.", "Хуб, танаффус тамом шуд.", "Бигӯ: равем", "Gehen wir.", "Равем.",
              ["Okay, gehen wir."]),
        ]),
    ]))

# ═════════════════════ 18. Либоси корӣ ═════════════════════
made.append(pack("gear_de_tg", "Arbeitskleidung", "Либоси корӣ", "🦺", 18, B,
    "Либос ва таҷҳизоти муҳофизатӣ: камзӯл, мӯза, айнак, ниқоб. Андозаро мегӯед, нав "
    "мехоҳед ва мефаҳмед, ки бе кулоҳ даромадан манъ аст.",
    [
        ("Либос", [
            w("Warnweste", "камзӯли инъикоскунанда", None),
            w("Arbeitsschuhe", "мӯзаи корӣ", None),
            w("Schutzbrille", "айнаки муҳофизатӣ", None),
            w("Maske", "ниқоб", None),
            w("Arbeitshose", "шими корӣ", None),
            w("Gehörschutz", "гӯшпӯшак", None),
        ]),
        ("Камзӯлат куҷост?", [
            t("Wo ist deine Warnweste?", "Камзӯлат куҷост?", "Бигӯ: дар вагонча", "Im Container.", "Дар вагонча.",
              ["Sie ist im Container."]),
            t("Setz die Schutzbrille auf!", "Айнак пӯш!", "Бигӯ: хуб", "Okay.", "Хуб.", ["Mache ich."]),
            t("Passen die Schuhe?", "Мӯзаҳо мувофиқанд?", "Бигӯ: не, калон", "Nein, zu groß.", "Не, калон.",
              ["Zu groß."]),
        ]),
        ("Суханҳои кӯтоҳ", [
            s("Neue Handschuhe", "дастпӯшаки нав", None),
            s("Eine Staubmaske", "ниқоби чанг", None),
            s("Ist kaputt", "дарида, вайрон", None),
            s("Zu klein", "хеле хурд", None),
            s("Gehörschutz aufsetzen", "гӯшпӯшак пӯшидан", None),
            s("Die Arbeitsschuhe", "мӯзаҳои корӣ", None),
        ]),
        ("Нав лозим", [
            t("Was brauchst du?", "Чӣ лозим?", "Бигӯ: дастпӯшаки нав", "Neue Handschuhe.", "Дастпӯшаки нав.",
              ["Ich brauche neue Handschuhe."]),
            t("Was ist mit den alten?", "Кӯҳнаҳо чӣ шуданд?", "Бигӯ: дарида шуданд", "Sie sind kaputt.",
              "Дарида шуданд.", ["Kaputt."]),
            t("Hier, die sind neu.", "Гир, инҳо нав.", "Бигӯ: ташаккур", "Danke.", "Ташаккур.", []),
        ]),
        ("Андоза ва вайронӣ", [
            s("Ich habe Größe zweiundvierzig.", "Андозаи ман чилу ду.", None),
            s("Die Schuhe sind klein.", "Мӯза хурд аст.", None),
            s("Ich brauche eine Staubmaske.", "Ба ман ниқоби чанг лозим.", None),
            s("Meine Weste ist kaputt.", "Камзӯлам дарида шуд.", None),
            s("Meine Brille ist kaputt.", "Айнакам шикаст.", None),
            s("Kann ich neue bekommen?", "Нав гирифта метавонам?", None),
        ]),
        ("Муколама: мӯза", [
            t("Welche Größe hast du?", "Андозаат чанд?", "Бигӯ: чилу ду", "Zweiundvierzig.", "Чилу ду.",
              ["Größe zweiundvierzig."]),
            t("Passen diese Schuhe?", "Ин мӯза мувофиқ аст?", "Бигӯ: не, хурд", "Nein, zu klein.", "Не, хурд.",
              ["Zu klein."]),
            t("Okay, hier ist dreiundvierzig.", "Хуб, ана чилу се.", "Бигӯ: хуб, ташаккур", "Gut, danke.",
              "Хуб, ташаккур.", []),
        ]),
        ("Қоидаҳо", [
            s("Hier ist es laut.", "Ин ҷо садо зиёд.", None),
            s("Ich brauche Gehörschutz.", "Ба ман гӯшпӯшак лозим.", None),
            s("Ohne Helm verboten.", "Бе кулоҳ манъ.", None),
            s("Meine Kleidung ist nass.", "Либосам тар шуд.", None),
            s("Gibt es eine Ersatzhose?", "Шими эҳтиётӣ ҳаст?", None),
            s("Zieh die Weste an.", "Камзӯлро пӯш.", None),
        ]),
        ("Муколама: гӯшпӯшак", [
            t("Warum hast du keinen Gehörschutz?", "Чаро гӯшпӯшак надорӣ?", "Бигӯ: ба ман гӯшпӯшак лозим",
              "Ich brauche Gehörschutz.", "Ба ман гӯшпӯшак лозим.", ["Ich habe keinen."]),
            t("Im Lager gibt es welchen. Hol ihn.", "Дар анбор ҳаст. Гир.", "Бипурс: шими эҳтиётӣ ҳаст?",
              "Gibt es eine Ersatzhose?", "Шими эҳтиётӣ ҳаст?", []),
            t("Warum?", "Чаро?", "Бигӯ: либосам тар шуд", "Meine Kleidung ist nass.", "Либосам тар шуд.", []),
        ]),
        ("Миссия: дар дарвоза", [
            t("Stopp! Wo ist dein Helm?", "Ист! Кулоҳат куҷост?", "Бигӯ: бубахшед, дар вагонча",
              "Entschuldigung, im Container.", "Бубахшед, дар вагонча.", ["Im Container."]),
            t("Ohne Helm ist es verboten!", "Бе кулоҳ манъ аст!", "Бигӯ: фаҳмидам, ҳозир меорам",
              "Verstanden, ich hole ihn sofort.", "Фаҳмидам, ҳозир меорам.", ["Ich hole ihn sofort."]),
            t("Und die Weste fehlt auch.", "Камзӯл ҳам нест.", "Бигӯ: камзӯлам дарида шуд", "Meine Weste ist kaputt.",
              "Камзӯлам дарида шуд.", []),
            t("Hol eine neue aus dem Lager.", "Навашро аз анбор гир.", "Бигӯ: хуб, сардор", "Okay, Chef.",
              "Хуб, сардор.", ["Danke, Chef."]),
        ]),
    ]))

# ═════════════════════ 19. Санҷиши кор ═════════════════════
made.append(pack("check_de_tg", "Arbeit prüfen", "Санҷиши кор", "✅", 19, B,
    "Сардор кори шуморо месанҷад. Мегӯед, ки тайёр аст ё каме монд, мепурсед, ки куҷо "
    "нодуруст аст, ва аз нав мекунед.",
    [
        ("Сифат", [
            w("Gerade", "рост, ҳамвор", None),
            w("Schief", "каҷ", None),
            w("Fertig", "тайёр", None),
            w("Richtig", "дуруст", None),
            w("Falsch", "нодуруст", None),
            w("Nochmal", "боз, аз нав", None),
        ]),
        ("Тайёр?", [
            t("Fertig?", "Тайёр?", "Бигӯ: ҳа, тайёр", "Ja, fertig.", "Ҳа, тайёр.", ["Fertig."]),
            t("Die Wand ist schief.", "Девор каҷ аст.", "Бигӯ: бубахшед", "Entschuldigung.", "Бубахшед.",
              ["Tut mir leid."]),
            t("Mach es nochmal.", "Аз нав кун.", "Бигӯ: хуб", "Okay.", "Хуб.", ["Okay, Chef."]),
        ]),
        ("Суханҳои кӯтоҳ", [
            s("Bitte prüfen", "Лутфан, санҷед", None),
            s("Etwas falsch?", "Чизе нодуруст?", None),
            s("Fast fertig", "Қариб тайёр", None),
            s("Jetzt gerade", "Ҳоло рост", None),
            s("Morgen fertig", "Фардо тайёр", None),
            w("Super", "офарин", None),
        ]),
        ("Кай тамом мешавад?", [
            t("Ist die Wand fertig?", "Девор тайёр аст?", "Бигӯ: қариб тайёр", "Fast fertig.", "Қариб тайёр.",
              ["Fast."]),
            t("Wann bist du fertig?", "Кай тамом мекунӣ?", "Бигӯ: фардо тайёр", "Morgen fertig.", "Фардо тайёр.",
              ["Morgen."]),
            t("Okay. Nimm die Wasserwaage.", "Хуб. Сатҳсанҷро гир.", "Бигӯ: хуб", "Okay.", "Хуб.", ["Okay, Chef."]),
        ]),
        ("Санҷед, лутфан", [
            s("Chef, schauen Sie bitte.", "Сардор, лутфан нигоҳ кунед.", None),
            s("Die Arbeit ist fertig.", "Кор тайёр аст.", None),
            s("Ist das richtig?", "Ин дуруст аст?", None),
            s("Ich mache es nochmal.", "Аз нав мекунам.", None),
            s("Jetzt ist es besser.", "Ҳоло беҳтар аст.", None),
            s("Morgen ist alles fertig.", "Фардо ҳама тайёр мешавад.", None),
        ]),
        ("Муколама: кунҷ", [
            t("Das ist schlecht gemacht.", "Ин бад сохта шудааст.", "Бипурс: чӣ нодуруст?", "Was ist falsch?",
              "Чӣ нодуруст?", ["Was ist das Problem?"]),
            t("Die Ecke ist schief.", "Кунҷ каҷ аст.", "Бигӯ: аз нав мекунам", "Ich mache es nochmal.",
              "Аз нав мекунам.", ["Okay, nochmal."]),
            t("Pass besser auf.", "Бодиққаттар бош.", "Бигӯ: хуб, сардор", "Okay, Chef.", "Хуб, сардор.", []),
        ]),
        ("Кори тайёр", [
            s("Die Fliesen sind fertig.", "Кошинҳо тайёр.", None),
            s("Ist die Farbe trocken?", "Ранг хушк шуд?", None),
            s("Zweiter Stock ist fertig.", "Ошёнаи дуюм тайёр аст.", None),
            s("Ich habe fotografiert.", "Ман акс гирифтам.", None),
            s("Ich habe aufgeräumt.", "Ман тоза кардам.", None),
            s("Gibt es noch Arbeit?", "Боз кор ҳаст?", None),
        ]),
        ("Муколама: ранг", [
            t("Wie ist die Farbe?", "Ранг чӣ хел?", "Бигӯ: ҳоло беҳтар аст", "Jetzt ist es besser.",
              "Ҳоло беҳтар аст.", ["Besser."]),
            t("Super! Hast du aufgeräumt?", "Офарин! Тоза кардӣ?", "Бигӯ: ҳа, тоза кардам", "Ja, ich habe aufgeräumt.",
              "Ҳа, тоза кардам.", ["Ja."]),
            t("Gut.", "Хуб.", "Бипурс: боз кор ҳаст?", "Gibt es noch Arbeit?", "Боз кор ҳаст?", ["Was noch?"]),
        ]),
        ("Миссия: сардор месанҷад", [
            t("Der Chef ist da. Bist du fertig?", "Сардор омад. Тамом кардӣ?", "Бигӯ: ҳа, лутфан нигоҳ кунед",
              "Ja, schauen Sie bitte.", "Ҳа, лутфан нигоҳ кунед.", ["Ja, fertig."]),
            t("Diese Ecke ist schief.", "Ин кунҷ каҷ аст.", "Бигӯ: бубахшед, аз нав мекунам",
              "Entschuldigung, ich mache es nochmal.", "Бубахшед, аз нав мекунам.", ["Ich mache es nochmal."]),
            t("Wann bist du fertig?", "Кай тамом мекунӣ?", "Бигӯ: баъд аз як соат", "In einer Stunde.",
              "Баъд аз як соат.", ["In einer Stunde fertig."]),
            t("Okay, zeig es mir dann.", "Хуб, баъд ба ман нишон деҳ.", "Бигӯ: хуб, сардор", "Okay, Chef.",
              "Хуб, сардор.", []),
        ]),
    ]))

# ═════════════════════ 20. Соатҳо ва табел ═════════════════════
made.append(pack("hours_de_tg", "Arbeitszeit und Stundenzettel", "Соатҳо ва табел", "🕗", 20, B,
    "Кай сар мекунед ва кай тамом, чанд соат кор кардед ва оё номатон дар табел "
    "(Stundenzettel) ҳаст. Инчунин рӯзи истироҳат, кори шабона ва барвақт рафтан.",
    [
        ("Вақт", [
            w("Uhr", "соат (вақт)", None),
            w("Schicht", "навбати кор", None),
            w("Stundenzettel", "табел", "Варақаи ҳисоби соатҳои кор."),
            w("Samstag", "шанбе", None),
            w("Sonntag", "якшанбе", None),
            w("Frei", "озод, истироҳат", None),
        ]),
        ("Соати чанд?", [
            t("Wann bist du gekommen?", "Кай омадӣ?", "Бигӯ: соати ҳафт", "Um sieben Uhr.", "Соати ҳафт.",
              ["Um sieben."]),
            t("Wann gehst du?", "Кай меравӣ?", "Бигӯ: соати шаш", "Um sechs Uhr.", "Соати шаш.", ["Um sechs."]),
            t("Arbeitest du am Samstag?", "Шанбе кор мекунӣ?", "Бигӯ: ҳа", "Ja.", "Ҳа.", ["Ja, am Samstag auch."]),
        ]),
        ("Суханҳои кӯтоҳ", [
            s("Um sieben", "соати ҳафт", None),
            s("Bis sechs", "то соати шаш", None),
            s("Halber Tag", "ним рӯз", None),
            s("Ganzer Tag", "рӯзи пурра", None),
            s("Hier unterschreiben", "Ин ҷо имзо кардан", None),
            s("Die Nachtschicht", "кори шабона", None),
        ]),
        ("Табел", [
            t("Unterschreib den Stundenzettel.", "Табелро имзо кун.", "Бигӯ: хуб", "Okay.", "Хуб.", ["Mache ich."]),
            t("Wie viele Stunden hast du gestern gearbeitet?", "Дирӯз чанд соат кор кардӣ?", "Бигӯ: даҳ соат",
              "Zehn Stunden.", "Даҳ соат.", ["Ich habe zehn Stunden gearbeitet."]),
            t("Einen halben Tag?", "Ним рӯз?", "Бигӯ: не, рӯзи пурра", "Nein, den ganzen Tag.", "Не, рӯзи пурра.",
              ["Den ganzen Tag."]),
        ]),
        ("Рӯзи кор", [
            s("Anfang um sieben.", "Оғоз соати ҳафт.", None),
            s("Schicht bis sechs.", "Навбат то соати шаш.", None),
            s("Gestern zehn Stunden gearbeitet.", "Дирӯз даҳ соат кор кардам.", None),
            s("Mein Name fehlt.", "Номам нест.", None),
            s("Ist Sonntag frei?", "Якшанбе истироҳат аст?", None),
            s("Eine Stunde Mittagspause.", "Як соат танаффуси нисфирӯзӣ.", None),
        ]),
        ("Муколама: номам нест", [
            t("Prüf deinen Stundenzettel.", "Табелатро сан.", "Бигӯ: номам нест", "Mein Name fehlt.", "Номам нест.",
              ["Mein Name ist nicht da."]),
            t("Welcher Tag?", "Кадом рӯз?", "Бигӯ: сешанбе", "Dienstag.", "Сешанбе.", ["Am Dienstag."]),
            t("Okay, ich trage es ein.", "Хуб, менависам.", "Бигӯ: ташаккур", "Danke.", "Ташаккур.", []),
        ]),
        ("Ҳафта ва ид", [
            s("Sechs Tage gearbeitet.", "Шаш рӯз кор кардам.", None),
            s("Samstag ein halber Tag.", "Шанбе ним рӯз.", None),
            s("Ist Feiertag frei?", "Рӯзи ид истироҳат аст?", None),
            s("Gibt es Nachtschicht?", "Кори шабона ҳаст?", None),
            s("Darf ich früher gehen?", "Барвақттар рафта метавонам?", None),
            s("Ich muss zum Arzt.", "Бояд ба духтур равам.", None),
        ]),
        ("Муколама: ҳафта", [
            t("Wie viele Tage hast du diese Woche gearbeitet?", "Ин ҳафта чанд рӯз кор кардӣ?", "Бигӯ: шаш рӯз",
              "Sechs Tage.", "Шаш рӯз.", ["Ich habe sechs Tage gearbeitet."]),
            t("Auch am Samstag?", "Шанбе ҳам?", "Бигӯ: ҳа, шанбе ним рӯз", "Ja, Samstag ein halber Tag.",
              "Ҳа, шанбе ним рӯз.", ["Ja, einen halben Tag."]),
            t("Okay, stimmt.", "Хуб, дуруст.", "Бипурс: барвақттар рафта метавонам?", "Darf ich früher gehen?",
              "Барвақттар рафта метавонам?", []),
        ]),
        ("Миссия: кори шабона", [
            t("Guten Morgen! Wann bist du gekommen?", "Субҳ ба хайр! Кай омадӣ?", "Бигӯ: соати ҳафт",
              "Um sieben Uhr.", "Соати ҳафт.", ["Um sieben."]),
            t("Heute gibt es Nachtschicht.", "Имрӯз кори шабона ҳаст.", "Бипурс: то соати чанд?", "Bis wann?",
              "То кай?", ["Bis wann arbeiten wir?"]),
            t("Bis elf Uhr.", "То соати ёздаҳ.", "Бипурс: фардо барвақттар рафта метавонам?",
              "Darf ich morgen früher gehen?", "Фардо барвақттар рафта метавонам?", ["Darf ich früher gehen?"]),
            t("Ja, nach der Mittagspause.", "Ҳа, баъд аз танаффуси нисфирӯзӣ.", "Бигӯ: ташаккур, сардор",
              "Danke, Chef.", "Ташаккур, сардор.", ["Vielen Dank."]),
        ]),
    ]))

finish(made)
