"""ОЛМОНӢ → тоҷикӣ, «Гуфтор» A1 — нишаи «Ронандагӣ» (`drive`), 04.10.2026.

14 вазъият барои ронандаи тоҷик дар Олмон (такси ва расонидани фармоиш) — ҳамон тартиби
русӣ: мошини корӣ, гирифтани мусофир, суроға ва роҳ, бағоҷ, пардохт, гап бо мусофир,
сӯзишворӣ, роҳбандӣ, расонидан, занг ба мизоҷ, полиси роҳ, мошин вайрон, садамаи хурд,
навбат ва даромад.

Роҳи `drive` = 6 вазъияти умумӣ (1, 2 «Кор ёфтан», 6, 10, 14, 16) + ин 14 → 20.

Қоидаҳо — `_de_packs_lib.py`: рақам бо ҳарф; бо мусофир, мизоҷ ва полис — «Sie»; сардор ба
ронанда — «du». Транскрипсия: `node prisma/_de-fill-literal.mjs <slugs>`.

Аз ҷузвдони backend: python prisma/_de-drive-a1-packs.py
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _de_packs_lib import *  # noqa: F401,F403

made = []
D = ["drive"]

# ═════════════════════ 3. Мошини корӣ ═════════════════════
made.append(pack("car_de_tg", "Das Firmenauto", "Мошини корӣ", "🚗", 3, D,
    "Рӯзи аввали кор: сардор ба шумо мошини кориро медиҳад. Калид ва ҳуҷҷатҳоро мегиред, "
    "мепурсед, ки бензин ё дизел аст, ва мошинро месанҷед.",
    [
        ("Мошин", [
            w("Auto", "мошин", None),
            w("Schlüssel", "калид", None),
            w("Führerschein", "шаҳодатномаи ронандагӣ", None),
            w("Benzin", "бензин", None),
            w("Diesel", "дизел", None),
            w("Reifen", "чарх (шина)", None),
        ]),
        ("Калид", [
            t("Hallo! Bist du der neue Fahrer?", "Салом! Ту ронандаи навӣ?", "Бигӯ: ҳа", "Ja.", "Ҳа.",
              ["Ja, ich bin neu.", "Ja, genau."]),
            t("Hier ist der Schlüssel.", "Мана калид.", "Ташаккур гӯй", "Danke.", "Ташаккур.", ["Danke schön."]),
            t("Hast du deinen Führerschein?", "Шаҳодатномаат ҳаст?", "Бигӯ: ҳа, мана", "Ja, hier.", "Ҳа, мана.",
              ["Ja, hier ist er.", "Ja."]),
        ]),
        ("Ибораҳо", [
            s("Welches Auto?", "Кадом мошин?", None),
            s("Weißes Auto", "Мошини сафед", None),
            s("Oder Diesel?", "Ё дизел?", None),
            s("Der Tank", "Бак", None),
            s("Alles okay", "Ҳама хуб", None),
            s("Die Papiere", "Ҳуҷҷатҳо", None),
        ]),
        ("Кадом мошин?", [
            t("Dein Auto ist draußen.", "Мошинат берун аст.", "Бипурс: кадом мошин?", "Welches Auto?", "Кадом мошин?",
              ["Welches?"]),
            t("Das weiße Auto.", "Мошини сафед.", "Бипурс: бензин ё дизел?", "Benzin oder Diesel?", "Бензин ё дизел?",
              ["Diesel?"]),
            t("Diesel.", "Дизел.", "Бигӯ: хуб, ташаккур", "Gut, danke.", "Хуб, ташаккур.", ["Okay, danke."]),
        ]),
        ("Мошинро месанҷам", [
            s("Der Tank ist voll.", "Бак пур аст.", None),
            s("Der Reifen ist kaputt.", "Чарх вайрон аст.", None),
            s("Das Licht geht nicht.", "Чароғ кор намекунад.", None),
            s("Wo sind die Papiere?", "Ҳуҷҷатҳо куҷоянд?", None),
            s("Das Auto ist schmutzig.", "Мошин чиркин аст.", None),
            s("Alles ist okay.", "Ҳама хуб аст.", None),
        ]),
        ("Санҷиш", [
            t("Ist alles okay mit dem Auto?", "Мошин ҳама хуб аст?", "Бигӯ: чарх вайрон аст", "Der Reifen ist kaputt.",
              "Чарх вайрон аст.", ["Nein, der Reifen ist kaputt."]),
            t("Oh! Nimm das blaue Auto.", "О! Мошини кабудро гир.", "Бипурс: ҳуҷҷатҳо куҷоянд?", "Wo sind die Papiere?",
              "Ҳуҷҷатҳо куҷоянд?", ["Und die Papiere?"]),
            t("Im Auto, vorne.", "Дар мошин, пеш.", "Бигӯ: хуб, ташаккур", "Gut, danke.", "Хуб, ташаккур.",
              ["Okay.", "Danke."]),
        ]),
        ("Қоидаҳо", [
            s("Fahr bitte langsam.", "Оҳиста ҳай, лутфан.", None),
            s("Kein Alkohol!", "Майзадагӣ мумкин нест!", None),
            s("Am Abend zurück.", "Бегоҳ баргард.", None),
            s("Ich fahre langsam.", "Ман оҳиста меронам.", None),
            s("Wann bringe ich es?", "Онро кай биёрам?", None),
            s("Ich tanke morgen.", "Пагоҳ бензин мерезам.", None),
        ]),
        ("Дастури сардор", [
            t("Fahr bitte langsam!", "Оҳиста ҳай, лутфан!", "Бигӯ: ман оҳиста меронам", "Ich fahre langsam.",
              "Ман оҳиста меронам.", ["Ja, langsam.", "Okay, langsam."]),
            t("Und am Abend zurück.", "Ва бегоҳ баргард.", "Бипурс: соати чанд?", "Um wie viel Uhr?", "Соати чанд?",
              ["Wann genau?"]),
            t("Um sechs Uhr.", "Соати шаш.", "Бигӯ: хуб", "Okay.", "Хуб.", ["Gut, um sechs.", "Alles klar."]),
        ]),
        ("Миссия: рӯзи аввал", [
            t("Hallo! Bist du der neue Fahrer?", "Салом! Ронандаи навӣ?", "Бигӯ: ҳа, ман ронанда ҳастам",
              "Ja, ich bin Fahrer.", "Ҳа, ман ронанда ҳастам.", ["Ja, ich bin der Fahrer.", "Ja."]),
            t("Hier ist der Schlüssel.", "Мана калид.", "Бипурс: кадом мошин?", "Welches Auto?", "Кадом мошин?",
              ["Danke. Welches Auto?"]),
            t("Das weiße Auto. Diesel.", "Мошини сафед. Дизел.", "Бигӯ: чарх вайрон аст", "Der Reifen ist kaputt.",
              "Чарх вайрон аст.", ["Der Reifen ist kaputt, leider."]),
            t("Dann nimm das blaue.", "Пас кабудро гир.", "Бигӯ: хуб, ташаккур", "Gut, danke.", "Хуб, ташаккур.",
              ["Okay, danke.", "Alles klar."]),
        ]),
    ]))

# ═════════════════════ 4. Гирифтани мусофир ═════════════════════
made.append(pack("pickup_de_tg", "Fahrgast abholen", "Гирифтани мусофир", "🙋", 4, D,
    "Шумо ронандаи такси ҳастед. Мусофирро пешвоз мегиред: салом медиҳед, номашро месанҷед, "
    "мегӯед, ки камарбандро бибандад ва мепурсед, ки ба куҷо меравад.",
    [
        ("Такси", [
            w("Fahrgast", "мусофир", None),
            w("Fahrer", "ронанда", None),
            w("Einsteigen", "савор шудан", None),
            w("Gurt", "камарбанд", None),
            w("Hinten", "дар қафо", None),
            w("Wohin", "ба куҷо", None),
        ]),
        ("Салом, мусофир", [
            t("Hallo! Sind Sie mein Taxi?", "Салом! Шумо таксии ман?", "Бигӯ: ҳа. Номатон?", "Ja. Ihr Name?",
              "Ҳа. Номатон?", ["Ja. Wie ist Ihr Name?"]),
            t("Müller.", "Мюллер.", "Бигӯ: лутфан савор шавед", "Bitte einsteigen.", "Лутфан савор шавед.",
              ["Steigen Sie ein, bitte."]),
            t("Danke.", "Ташаккур.", "Бипурс: ба куҷо?", "Wohin?", "Ба куҷо?", ["Wohin, bitte?"]),
        ]),
        ("Ибораҳо", [
            s("Ihr Name?", "Номатон?", None),
            s("Bitte einsteigen", "Лутфан савор шавед", None),
            s("Gurt, bitte", "Камарбанд, лутфан", None),
            s("Wohin, bitte?", "Ба куҷо, лутфан?", None),
            s("Zum Bahnhof", "Ба вокзал", None),
            s("Gute Fahrt", "Роҳи сафед", None),
        ]),
        ("Камарбанд", [
            t("Zum Bahnhof, bitte.", "Ба вокзал, лутфан.", "Бигӯ: камарбанд, лутфан", "Den Gurt, bitte.",
              "Камарбанд, лутфан.", ["Bitte den Gurt."]),
            t("Ach ja, sorry.", "А, ҳа, бубахшед.", "Бигӯ: мушкил нест", "Kein Problem.", "Мушкил нест.", ["Danke."]),
            t("Wie lange dauert es?", "Чӣ қадар вақт мегирад?", "Бигӯ: даҳ дақиқа", "Zehn Minuten.", "Даҳ дақиқа.",
              ["Ungefähr zehn Minuten."]),
        ]),
        ("Ман ронанда ҳастам", [
            s("Ich bin Ihr Fahrer.", "Ман ронандаи шумо ҳастам.", None),
            s("Sind Sie Herr Müller?", "Шумо ҷаноби Мюллер?", None),
            s("Bitte hinten einsteigen.", "Лутфан дар қафо шинед.", None),
            s("Haben Sie Gepäck?", "Бағоҷ доред?", None),
            s("Ist es zu kalt?", "Хеле хунук аст?", None),
            s("Wir fahren jetzt.", "Ҳоло меравем.", None),
        ]),
        ("Ҷаноби Мюллер?", [
            t("Hallo! Taxi?", "Салом! Такси?", "Бипурс: шумо ҷаноби Мюллер?", "Sind Sie Herr Müller?",
              "Шумо ҷаноби Мюллер?", ["Herr Müller?"]),
            t("Ja, das bin ich.", "Ҳа, ман ҳамонам.", "Бигӯ: ман ронандаи шумо ҳастам", "Ich bin Ihr Fahrer.",
              "Ман ронандаи шумо ҳастам.", ["Hallo, ich bin Ihr Fahrer."]),
            t("Super. Ich habe einen Koffer.", "Олӣ. Ман ҷомадон дорам.", "Бигӯ: ман ёрӣ медиҳам", "Ich helfe Ihnen.",
              "Ман ёрӣ медиҳам.", ["Kein Problem.", "Ich nehme ihn."]),
        ]),
        ("Дар роҳ", [
            s("Ist die Musik okay?", "Мусиқӣ хуб аст?", None),
            s("Zu kalt?", "Хеле хунук?", None),
            s("Ich mache es warm.", "Гарм мекунам.", None),
            s("Fenster auf?", "Тирезаро кушоям?", None),
            s("Wir sind gleich da.", "Ҳозир мерасем.", None),
            s("Hier ist Wasser.", "Мана об.", None),
        ]),
        ("Тиреза", [
            t("Es ist warm hier.", "Ин ҷо гарм аст.", "Бипурс: тирезаро кушоям?", "Fenster auf?", "Тирезаро кушоям?",
              ["Soll ich das Fenster öffnen?"]),
            t("Ja, bitte.", "Ҳа, лутфан.", "Бигӯ: хуб", "Okay.", "Хуб.", ["Gerne.", "Kein Problem."]),
            t("Wie lange noch?", "Боз чӣ қадар?", "Бигӯ: ҳозир мерасем", "Wir sind gleich da.", "Ҳозир мерасем.",
              ["Fünf Minuten.", "Gleich da."]),
        ]),
        ("Миссия: мусофири аввал", [
            t("Hallo! Taxi für Müller?", "Салом! Такси барои Мюллер?", "Бигӯ: ҳа. Лутфан савор шавед",
              "Ja. Bitte einsteigen.", "Ҳа. Лутфан савор шавед.", ["Ja, steigen Sie ein."]),
            t("Danke.", "Ташаккур.", "Бигӯ: камарбанд, лутфан", "Den Gurt, bitte.", "Камарбанд, лутфан.",
              ["Bitte den Gurt."]),
            t("Okay.", "Хуб.", "Бипурс: ба куҷо?", "Wohin, bitte?", "Ба куҷо, лутфан?", ["Wohin?"]),
            t("Zum Bahnhof.", "Ба вокзал.", "Бигӯ: хуб, ҳоло меравем", "Gut, wir fahren jetzt.", "Хуб, ҳоло меравем.",
              ["Okay, zum Bahnhof.", "Alles klar."]),
        ]),
    ]))

# ═════════════════════ 5. Суроға ва роҳ ═════════════════════
made.append(pack("route_de_tg", "Adresse und Weg", "Суроға ва роҳ", "🗺️", 5, D,
    "Мусофир суроғаро мегӯяд. Шумо мепурсед, ки кадом кӯча ва рақами хона аст, навигаторро "
    "истифода мебаред ва роҳро мепурсед: рост, чап, дар чорраҳа.",
    [
        ("Роҳ", [
            w("Links", "чап", None),
            w("Rechts", "рост", None),
            w("Geradeaus", "рост пеш", None),
            w("Ampel", "светофор", None),
            w("Kreuzung", "чорраҳа", None),
            w("Navi", "навигатор", None),
        ]),
        ("Суроға", [
            t("Zur Gartenstraße, bitte.", "Ба кӯчаи Гартен, лутфан.", "Бипурс: рақами хона?", "Welche Hausnummer?",
              "Рақами хона?", ["Welche Nummer?"]),
            t("Nummer fünf.", "Рақами панҷ.", "Бигӯ: хуб", "Okay.", "Хуб.", ["Gut.", "Gartenstraße fünf."]),
            t("Kennen Sie den Weg?", "Роҳро медонед?", "Бигӯ: навигатор дорам", "Ich habe ein Navi.",
              "Навигатор дорам.", ["Ja, mit Navi."]),
        ]),
        ("Ибораҳо", [
            s("Hier links", "Ин ҷо ба чап", None),
            s("Dann rechts", "Баъд ба рост", None),
            s("Immer geradeaus", "Ҳамеша рост", None),
            s("Ampel rechts", "Дар светофор ба рост", None),
            s("Hier halten?", "Ин ҷо истам?", None),
            s("Welche Straße?", "Кадом кӯча?", None),
        ]),
        ("Ба кадом тараф?", [
            t("Hier links, bitte.", "Ин ҷо ба чап, лутфан.", "Бигӯ: хуб, ба чап", "Okay, links.", "Хуб, ба чап.",
              ["Links, okay."]),
            t("Dann an der Ampel rechts.", "Баъд дар светофор ба рост.", "Такрор кун: дар светофор ба рост",
              "An der Ampel rechts.", "Дар светофор ба рост.", ["Rechts, okay."]),
            t("Ja, genau.", "Ҳа, дуруст.", "Бипурс: ин ҷо истам?", "Hier halten?", "Ин ҷо истам?",
              ["Soll ich hier halten?"]),
        ]),
        ("Ман роҳ мепурсам", [
            s("Wie ist die Adresse?", "Суроға чист?", None),
            s("Wo ist die Straße?", "Кӯча куҷост?", None),
            s("Links oder rechts?", "Чап ё рост?", None),
            s("Ist es weit?", "Дур аст?", None),
            s("Das Navi sagt links.", "Навигатор ба чап мегӯяд.", None),
            s("Wir sind da.", "Расидем.", None),
        ]),
        ("Кӯчаи номаълум", [
            t("Zur Lindenstraße, bitte.", "Ба кӯчаи Линден, лутфан.", "Бигӯ: кӯчаро намедонам",
              "Ich kenne die Straße nicht.", "Кӯчаро намедонам.", ["Wo ist das?", "Die kenne ich nicht."]),
            t("Beim Park.", "Назди боғ.", "Бипурс: дур аст?", "Ist es weit?", "Дур аст?", ["Weit?"]),
            t("Nein, fünf Minuten.", "Не, панҷ дақиқа.", "Бигӯ: хуб, навигатор дорам", "Gut, ich habe ein Navi.",
              "Хуб, навигатор дорам.", ["Okay, mit Navi."]),
        ]),
        ("Расидан", [
            s("Hier ist Nummer fünf.", "Ин рақами панҷ.", None),
            s("Ich halte hier.", "Ин ҷо меистам.", None),
            s("Hier halten geht nicht.", "Ин ҷо истодан намешавад.", None),
            s("Da vorne ist frei.", "Он ҷо, пеш, холӣ аст.", None),
            s("Vorsicht beim Aussteigen.", "Ҳангоми фуромадан эҳтиёт.", None),
            s("Einen schönen Tag!", "Рӯзи хуш!", None),
        ]),
        ("Ин ҷо истам?", [
            t("Hier, bitte. Halten Sie hier.", "Ин ҷо, лутфан. Ин ҷо истед.", "Бигӯ: ин ҷо истода наметавонам",
              "Ich kann hier nicht halten.", "Ин ҷо истода наметавонам.", ["Hier geht nicht."]),
            t("Wo dann?", "Пас куҷо?", "Бигӯ: он ҷо, пеш, холӣ аст", "Da vorne ist frei.", "Он ҷо, пеш, холӣ аст.",
              ["Da vorne."]),
            t("Okay, danke.", "Хуб, ташаккур.", "Бигӯ: рӯзи хуш!", "Einen schönen Tag!", "Рӯзи хуш!",
              ["Schönen Tag!", "Tschüss!"]),
        ]),
        ("Миссия: роҳи мураккаб", [
            t("Zur Gartenstraße, bitte.", "Ба кӯчаи Гартен, лутфан.", "Бипурс: рақами хона?", "Welche Hausnummer?",
              "Рақами хона?", ["Welche Nummer?"]),
            t("Nummer zwölf. Hier links!", "Рақами дувоздаҳ. Ин ҷо ба чап!", "Бигӯ: хуб, ба чап", "Okay, links.",
              "Хуб, ба чап.", ["Links, okay."]),
            t("Und dann geradeaus.", "Ва баъд рост.", "Бипурс: дур аст?", "Ist es weit?", "Дур аст?", ["Weit?"]),
            t("Nein. Da ist es!", "Не. Ана ҳамон!", "Бигӯ: расидем", "Wir sind da.", "Расидем.",
              ["So, wir sind da."]),
        ]),
    ]))

# ═════════════════════ 7. Бағоҷ ═════════════════════
made.append(pack("luggage_de_tg", "Gepäck", "Бағоҷ ва бағоҷдон", "🧳", 7, D,
    "Мусофир бағоҷ дорад: шумо ёрӣ медиҳед, ҷомадонро ба бағоҷдон мегузоред, эҳтиёт мегӯед ва "
    "дар охир фаромӯш накардани чизҳоро ёдрас мекунед.",
    [
        ("Бағоҷ", [
            w("Gepäck", "бағоҷ", None),
            w("Kofferraum", "бағоҷдон", None),
            w("Tasche", "сумка", None),
            w("Schwer", "вазнин", None),
            w("Leicht", "сабук", None),
            w("Vergessen", "фаромӯш кардан", None),
        ]),
        ("Ёрӣ медиҳам", [
            t("Ich habe zwei Koffer.", "Ман ду ҷомадон дорам.", "Бигӯ: ман ёрӣ медиҳам", "Ich helfe Ihnen.",
              "Ман ёрӣ медиҳам.", ["Kein Problem.", "Ich helfe."]),
            t("Danke! Sie sind schwer.", "Ташаккур! Вазнинанд.", "Бигӯ: мушкил нест", "Kein Problem.", "Мушкил нест.",
              ["Das geht.", "Okay."]),
            t("Und die Tasche?", "Ва сумка?", "Бигӯ: сумкаро бо худ гиред", "Die Tasche nehmen Sie mit.",
              "Сумкаро бо худ гиред.", ["Die Tasche mit nach vorne."]),
        ]),
        ("Ибораҳо", [
            s("Kofferraum auf", "Бағоҷдон кушода", None),
            s("Sehr schwer", "Хеле вазнин", None),
            s("Ganz hinten", "Дар охири қафо", None),
            s("Vorsicht, bitte", "Эҳтиёт, лутфан", None),
            s("Noch etwas?", "Боз чизе?", None),
            s("Alles drin", "Ҳама дарун", None),
        ]),
        ("Бағоҷдон", [
            t("Wo kommt der Koffer hin?", "Ҷомадон куҷо меравад?", "Бигӯ: ба бағоҷдон", "In den Kofferraum.",
              "Ба бағоҷдон.", ["Hinten, in den Kofferraum."]),
            t("Okay.", "Хуб.", "Бипурс: боз як ҷомадон?", "Noch ein Koffer?", "Боз як ҷомадон?", ["Noch etwas?"]),
            t("Nein, das ist alles.", "Не, ҳамин.", "Бигӯ: ҳама дарун", "Alles drin.", "Ҳама дарун.",
              ["Gut, alles drin."]),
        ]),
        ("Кор бо бағоҷ", [
            s("Ich nehme den Koffer.", "Ҷомадонро мегирам.", None),
            s("Der Kofferraum ist voll.", "Бағоҷдон пур аст.", None),
            s("Vorne ist Platz.", "Пеш ҷой ҳаст.", None),
            s("Ist da Glas drin?", "Дарунаш шиша ҳаст?", None),
            s("Ich mache langsam.", "Оҳиста мекунам.", None),
            s("Das ist Ihr Gepäck.", "Ин бағоҷи шумост.", None),
        ]),
        ("Эҳтиёт, шиша", [
            t("Vorsicht! Da ist Glas drin.", "Эҳтиёт! Дарунаш шиша ҳаст.", "Бигӯ: оҳиста мекунам", "Ich mache langsam.",
              "Оҳиста мекунам.", ["Okay, langsam."]),
            t("Danke.", "Ташаккур.", "Бигӯ: бағоҷдон пур аст", "Der Kofferraum ist voll.", "Бағоҷдон пур аст.",
              ["Leider ist der Kofferraum voll."]),
            t("Und die kleine Tasche?", "Ва сумкаи хурд?", "Бигӯ: пеш ҷой ҳаст", "Vorne ist Platz.",
              "Пеш ҷой ҳаст.", ["Vorne geht."]),
        ]),
        ("Дар охир", [
            s("Wir sind da.", "Расидем.", None),
            s("Ich hole Ihr Gepäck.", "Бағоҷатонро меорам.", None),
            s("Haben Sie alles?", "Ҳама чизатон ҳаст?", None),
            s("Ihr Handy!", "Телефонатон!", None),
            s("Nichts vergessen?", "Чизе фаромӯш накардед?", None),
            s("Gute Reise!", "Сафари хуш!", None),
        ]),
        ("Чизе фаромӯш накардед?", [
            t("So, danke!", "Хуб, ташаккур!", "Бипурс: ҳама чизатон ҳаст?", "Haben Sie alles?", "Ҳама чизатон ҳаст?",
              ["Nichts vergessen?"]),
            t("Ja, ich glaube.", "Ҳа, фикр мекунам.", "Бигӯ: телефонатон!", "Ihr Handy!", "Телефонатон!",
              ["Hier, Ihr Handy!"]),
            t("Oh, danke schön!", "О, ташаккури зиёд!", "Бигӯ: сафари хуш!", "Gute Reise!", "Сафари хуш!",
              ["Gerne, gute Reise!"]),
        ]),
        ("Миссия: фурудгоҳ", [
            t("Hallo! Ich habe drei Koffer.", "Салом! Ман се ҷомадон дорам.", "Бигӯ: ман ёрӣ медиҳам",
              "Ich helfe Ihnen.", "Ман ёрӣ медиҳам.", ["Kein Problem, ich helfe."]),
            t("Danke. Einer ist sehr schwer.", "Ташаккур. Яке хеле вазнин аст.", "Бигӯ: мушкил нест", "Kein Problem.",
              "Мушкил нест.", ["Das geht.", "Okay."]),
            t("Wir sind da. Danke!", "Расидем. Ташаккур!", "Бипурс: ҳама чизатон ҳаст?", "Haben Sie alles?",
              "Ҳама чизатон ҳаст?", ["Nichts vergessen?"]),
            t("Ja, alles.", "Ҳа, ҳама.", "Бигӯ: сафари хуш!", "Gute Reise!", "Сафари хуш!", ["Tschüss, gute Reise!"]),
        ]),
    ]))

# ═════════════════════ 8. Пардохти пули роҳ ═════════════════════
made.append(pack("fare_de_tg", "Bezahlen", "Пардохти пули роҳ", "💵", 8, D,
    "Сафар тамом шуд: шумо нархро мегӯед, мепурсед, ки нақд ё бо корт, бақия медиҳед, чек "
    "пешниҳод мекунед ва ташаккур мегӯед.",
    [
        ("Пул", [
            w("Fahrpreis", "пули роҳ", None),
            w("Bar", "нақд", None),
            w("Quittung", "квитансия", None),
            w("Wechselgeld", "бақия", None),
            w("Euro", "евро", None),
            w("Trinkgeld", "чойпулӣ", None),
        ]),
        ("Чанд пул?", [
            t("Was kostet die Fahrt?", "Сафар чанд пул?", "Бигӯ: понздаҳ евро", "Fünfzehn Euro.", "Понздаҳ евро.",
              ["Das macht fünfzehn Euro."]),
            t("Mit Karte, bitte.", "Бо корт, лутфан.", "Бигӯ: хуб", "Okay.", "Хуб.", ["Gerne.", "Kein Problem."]),
            t("Danke!", "Ташаккур!", "Бигӯ: рӯзи хуш!", "Schönen Tag!", "Рӯзи хуш!", ["Tschüss!"]),
        ]),
        ("Ибораҳо", [
            s("Mit Karte?", "Бо корт?", None),
            s("Fünfzehn Euro", "Понздаҳ евро", None),
            s("Ihre Quittung", "Квитансияатон", None),
            s("Stimmt so", "Бақия лозим нест", None),
            s("Ihr Wechselgeld", "Бақияатон", None),
            s("Vielen Dank", "Ташаккури зиёд", None),
        ]),
        ("Нақд", [
            t("Ich zahle bar.", "Нақд медиҳам.", "Бигӯ: понздаҳ евро", "Fünfzehn Euro.", "Понздаҳ евро.",
              ["Das macht fünfzehn Euro."]),
            t("Hier sind zwanzig.", "Мана бист.", "Бигӯ: мана бақияатон", "Hier ist Ihr Wechselgeld.",
              "Мана бақияатон.", ["Fünf Euro zurück."]),
            t("Stimmt so.", "Бақия лозим нест.", "Ташаккури зиёд гӯй", "Vielen Dank!", "Ташаккури зиёд!",
              ["Danke schön!"]),
        ]),
        ("Пардохт", [
            s("Das macht zwanzig Euro.", "Бист евро мешавад.", None),
            s("Möchten Sie eine Quittung?", "Квитансия мехоҳед?", None),
            s("Die Karte geht nicht.", "Корт кор намекунад.", None),
            s("Haben Sie es kleiner?", "Пули майдатар доред?", None),
            s("Ich habe kein Wechselgeld.", "Бақия надорам.", None),
            s("Danke für das Trinkgeld!", "Барои чойпулӣ ташаккур!", None),
        ]),
        ("Пули калон", [
            t("Ich habe nur hundert Euro.", "Ман танҳо сад евро дорам.", "Бигӯ: бақия надорам",
              "Ich habe kein Wechselgeld.", "Бақия надорам.", ["Leider kein Wechselgeld."]),
            t("Oh. Mit Karte geht?", "О. Бо корт мешавад?", "Бигӯ: ҳа, албатта", "Ja, natürlich.", "Ҳа, албатта.",
              ["Ja, kein Problem.", "Ja."]),
            t("Gut, mit Karte.", "Хуб, бо корт.", "Бипурс: квитансия мехоҳед?", "Möchten Sie eine Quittung?",
              "Квитансия мехоҳед?", ["Eine Quittung?"]),
        ]),
        ("Квитансия", [
            s("Für die Firma?", "Барои ширкат?", None),
            s("Hier ist die Quittung.", "Мана квитансия.", None),
            s("Mit Datum und Preis.", "Бо сана ва нарх.", None),
            s("Einen Moment, bitte.", "Як лаҳза, лутфан.", None),
            s("Die Fahrt war kurz.", "Сафар кӯтоҳ буд.", None),
            s("Bis zum nächsten Mal!", "То дафъаи дигар!", None),
        ]),
        ("Квитансия барои ширкат", [
            t("Ich brauche eine Quittung.", "Ба ман квитансия лозим.", "Бигӯ: як лаҳза, лутфан", "Einen Moment, bitte.",
              "Як лаҳза, лутфан.", ["Moment."]),
            t("Für die Firma.", "Барои ширкат.", "Бигӯ: мана квитансия", "Hier ist die Quittung.", "Мана квитансия.",
              ["Bitte schön, die Quittung."]),
            t("Danke! Tschüss!", "Ташаккур! Хайр!", "Бигӯ: то дафъаи дигар!", "Bis zum nächsten Mal!",
              "То дафъаи дигар!", ["Tschüss!", "Schönen Tag!"]),
        ]),
        ("Миссия: охири сафар", [
            t("Wir sind da? Was kostet das?", "Расидем? Чанд пул?", "Бигӯ: бист евро мешавад", "Das macht zwanzig Euro.",
              "Бист евро мешавад.", ["Zwanzig Euro."]),
            t("Mit Karte, bitte.", "Бо корт, лутфан.", "Бигӯ: хуб", "Okay.", "Хуб.", ["Gerne.", "Kein Problem."]),
            t("Ich brauche eine Quittung.", "Квитансия лозим.", "Бигӯ: мана квитансия", "Hier ist die Quittung.",
              "Мана квитансия.", ["Bitte schön."]),
            t("Danke schön!", "Ташаккури зиёд!", "Бигӯ: рӯзи хуш!", "Einen schönen Tag!", "Рӯзи хуш!",
              ["Schönen Tag!", "Tschüss!"]),
        ]),
    ]))

# ═════════════════════ 9. Гап бо мусофир ═════════════════════
made.append(pack("smalltalk_de_tg", "Gespräch mit Fahrgast", "Гап бо мусофир", "💬", 9, D,
    "Мусофир бо шумо гап мезанад: аз куҷоед, чанд вақт дар Олмон ҳастед, оила доред, ҳаво чӣ хел. "
    "Шумо кӯтоҳ ва хушмуомила ҷавоб медиҳед.",
    [
        ("Гап", [
            w("Wetter", "ҳаво", None),
            w("Familie", "оила", None),
            w("Kinder", "фарзандон", None),
            w("Jahre", "сол", None),
            w("Schön", "зебо, хуб", None),
            w("Regen", "борон", None),
        ]),
        ("Аз куҷоед?", [
            t("Woher kommen Sie?", "Аз куҷоед?", "Бигӯ: аз Тоҷикистон", "Aus Tadschikistan.", "Аз Тоҷикистон.",
              ["Ich komme aus Tadschikistan."]),
            t("Oh, interessant!", "О, ҷолиб!", "Бигӯ: ҳа, хеле зебо", "Ja, sehr schön.", "Ҳа, хеле зебо.",
              ["Ja, es ist schön dort."]),
            t("Wie lange sind Sie hier?", "Чанд вақт ин ҷоед?", "Бигӯ: ду сол", "Zwei Jahre.", "Ду сол.",
              ["Seit zwei Jahren."]),
        ]),
        ("Ибораҳо", [
            s("Zwei Jahre", "Ду сол", None),
            s("Sehr schön", "Хеле зебо", None),
            s("Viel Regen", "Борони зиёд", None),
            s("Zwei Kinder", "Ду фарзанд", None),
            s("Und Sie?", "Ва шумо?", None),
            s("Ein bisschen", "Каме", None),
        ]),
        ("Ҳаво", [
            t("Heute regnet es viel.", "Имрӯз бисёр борон меборад.", "Бигӯ: ҳа, борони зиёд", "Ja, viel Regen.",
              "Ҳа, борони зиёд.", ["Ja, leider."]),
            t("In Tadschikistan auch?", "Дар Тоҷикистон ҳам?", "Бигӯ: не, он ҷо офтобӣ", "Nein, dort ist viel Sonne.",
              "Не, он ҷо офтоб бисёр.", ["Nein, mehr Sonne."]),
            t("Schön!", "Хуб!", "Бигӯ: ҳа", "Ja.", "Ҳа.", ["Ja, sehr schön."]),
        ]),
        ("Дар бораи ман", [
            s("Seit zwei Jahren hier.", "Ду сол боз ин ҷо.", None),
            s("Meine Familie ist dort.", "Оилаам он ҷост.", None),
            s("Ich habe zwei Kinder.", "Ман ду фарзанд дорам.", None),
            s("Ich lerne Deutsch.", "Ман олмонӣ меомӯзам.", None),
            own("Ich wohne in ___.", "Ман дар ___ зиндагӣ мекунам.", "Шаҳри худро гӯед.",
                "Wo wohnen Sie?", "Дар куҷо зиндагӣ мекунед?", "Шаҳри худро гӯед"),
            s("Ich arbeite jeden Tag.", "Ман ҳар рӯз кор мекунам.", None),
        ]),
        ("Оила", [
            t("Haben Sie Familie?", "Оила доред?", "Бигӯ: ҳа, ду фарзанд дорам", "Ja, ich habe zwei Kinder.",
              "Ҳа, ду фарзанд дорам.", ["Ja, zwei Kinder."]),
            t("Sind sie hier?", "Онҳо ин ҷоянд?", "Бигӯ: не, оилаам он ҷост", "Nein, meine Familie ist dort.",
              "Не, оилаам он ҷост.", ["Nein, in Tadschikistan."]),
            t("Ihr Deutsch ist gut!", "Олмониатон хуб аст!", "Бигӯ: ташаккур, ман меомӯзам", "Danke, ich lerne.",
              "Ташаккур, ман меомӯзам.", ["Danke! Ich lerne Deutsch."]),
        ]),
        ("Хушмуомила", [
            s("Das freut mich.", "Аз ин шодам.", None),
            s("Ich verstehe nicht ganz.", "Пурра намефаҳмам.", None),
            s("Bitte langsam.", "Оҳиста, лутфан.", None),
            s("Und Sie, woher?", "Ва шумо аз куҷо?", None),
            s("Waren Sie schon dort?", "Он ҷо будед?", None),
            s("Kommen Sie mal!", "Як бор биёед!", None),
        ]),
        ("Савол ба мусофир", [
            t("Ich bin aus München.", "Ман аз Мюнхен ҳастам.", "Бигӯ: аз ин шодам", "Das freut mich.", "Аз ин шодам.",
              ["Schön!"]),
            t("Ich reise gern.", "Ман сафарро дӯст медорам.", "Бипурс: он ҷо будед?", "Waren Sie schon dort?",
              "Он ҷо будед?", ["Waren Sie in Tadschikistan?"]),
            t("Nein, noch nicht.", "Не, ҳанӯз не.", "Бигӯ: як бор биёед!", "Kommen Sie mal!", "Як бор биёед!",
              ["Kommen Sie! Es ist schön."]),
        ]),
        ("Миссия: сафари дароз", [
            t("Woher kommen Sie?", "Аз куҷоед?", "Бигӯ: аз Тоҷикистон", "Aus Tadschikistan.", "Аз Тоҷикистон.",
              ["Ich komme aus Tadschikistan."]),
            t("Wie lange sind Sie in Deutschland?", "Чанд вақт дар Олмонед?", "Бигӯ: ду сол", "Zwei Jahre.", "Ду сол.",
              ["Seit zwei Jahren."]),
            t("Und Ihre Familie?", "Ва оилаатон?", "Бигӯ: оилаам он ҷост", "Meine Familie ist dort.",
              "Оилаам он ҷост.", ["In Tadschikistan."]),
            t("Ihr Deutsch ist super!", "Олмониатон олӣ!", "Ташаккур гӯй", "Danke schön!", "Ташаккури зиёд!",
              ["Danke, ich lerne.", "Vielen Dank!"]),
        ]),
    ]))

# ═════════════════════ 11. Нуқтаи сӯзишворӣ ═════════════════════
made.append(pack("fuel_de_tg", "An der Tankstelle", "Нуқтаи сӯзишворӣ", "⛽", 11, D,
    "Бензин тамом мешавад. Шумо ба нуқтаи сӯзишворӣ меравед: сутуни бензинро мегӯед, пардохт "
    "мекунед, ҳавои чарх ва обро мепурсед.",
    [
        ("Тапка", [
            w("Tankstelle", "нуқтаи сӯзишворӣ", None),
            w("Tanken", "бензин рехтан", None),
            w("Säule", "сутун (колонка)", None),
            w("Waschanlage", "мошиншӯйхона", None),
            w("Luft", "ҳаво", None),
            w("Öl", "равған", None),
        ]),
        ("Дар касса", [
            t("Hallo! Welche Säule?", "Салом! Кадом сутун?", "Бигӯ: сутуни се", "Säule drei.", "Сутуни се.",
              ["Nummer drei.", "Drei."]),
            t("Sechzig Euro.", "Шаст евро.", "Бигӯ: бо корт, лутфан", "Mit Karte, bitte.", "Бо корт, лутфан.",
              ["Karte, bitte."]),
            t("Danke. Quittung?", "Ташаккур. Квитансия?", "Бигӯ: ҳа, лутфан", "Ja, bitte.", "Ҳа, лутфан.", ["Ja."]),
        ]),
        ("Ибораҳо", [
            s("Säule drei", "Сутуни се", None),
            s("Voll tanken", "Пур кардан", None),
            s("Dreißig Euro", "Сӣ евро", None),
            s("Luft prüfen", "Ҳаворо санҷидан", None),
            s("Wasser, bitte", "Об, лутфан", None),
            s("Diesel, bitte", "Дизел, лутфан", None),
        ]),
        ("Ҳаво дар чарх", [
            t("Kann ich helfen?", "Ёрӣ диҳам?", "Бипурс: ҳаво куҷост?", "Wo ist die Luft?", "Ҳаво куҷост?",
              ["Wo kann ich Luft prüfen?"]),
            t("Da hinten, rechts.", "Он ҷо, дар қафо, рост.", "Бипурс: ройгон аст?", "Ist das gratis?", "Ройгон аст?",
              ["Kostet das Geld?"]),
            t("Ja, gratis.", "Ҳа, ройгон.", "Бигӯ: олӣ, ташаккур", "Super, danke.", "Олӣ, ташаккур.", ["Danke!"]),
        ]),
        ("Ман бензин мерезам", [
            s("Ich tanke voll.", "Пур мекунам.", None),
            s("Der Tank ist leer.", "Бак холӣ аст.", None),
            s("Die Säule geht nicht.", "Сутун кор намекунад.", None),
            s("Ich zahle drinnen.", "Дарун пардохт мекунам.", None),
            s("Wo ist die Toilette?", "Ҳоҷатхона куҷост?", None),
            s("Einen Kaffee, bitte.", "Як қаҳва, лутфан.", None),
        ]),
        ("Сутун кор намекунад", [
            t("Ja, bitte?", "Ҳа, лутфан?", "Бигӯ: сутуни ду кор намекунад", "Säule zwei geht nicht.",
              "Сутуни ду кор намекунад.", ["Die Säule geht nicht."]),
            t("Moment, jetzt geht es.", "Як лаҳза, ҳоло кор мекунад.", "Ташаккур гӯй", "Danke!", "Ташаккур!",
              ["Danke schön."]),
            t("Bitte. Noch etwas?", "Марҳамат. Боз чизе?", "Бипурс: ҳоҷатхона куҷост?", "Wo ist die Toilette?",
              "Ҳоҷатхона куҷост?", ["Die Toilette, bitte?"]),
        ]),
        ("Мошинро тоза мекунам", [
            s("Ich wasche das Auto.", "Мошинро мешӯям.", None),
            s("Die Waschanlage, bitte.", "Мошиншӯйхона, лутфан.", None),
            s("Was kostet das?", "Ин чанд пул?", None),
            s("Brauche ich eine Karte?", "Ба ман корт лозим?", None),
            s("Das Öl ist alt.", "Равған кӯҳна аст.", None),
            s("Bitte prüfen Sie das.", "Лутфан инро санҷед.", None),
        ]),
        ("Мошиншӯйхона", [
            t("Noch etwas?", "Боз чизе?", "Бигӯ: мошиншӯйхона, лутфан", "Die Waschanlage, bitte.",
              "Мошиншӯйхона, лутфан.", ["Einmal Waschanlage."]),
            t("Das kostet zehn Euro.", "Даҳ евро мешавад.", "Бигӯ: хуб", "Okay.", "Хуб.", ["Gut.", "Gerne."]),
            t("Hier ist der Code.", "Мана рамз.", "Ташаккур гӯй", "Danke schön!", "Ташаккури зиёд!", ["Danke!"]),
        ]),
        ("Миссия: бак холӣ", [
            t("Hallo! Welche Säule?", "Салом! Кадом сутун?", "Бигӯ: сутуни чор", "Säule vier.", "Сутуни чор.",
              ["Nummer vier.", "Vier."]),
            t("Siebzig Euro, bitte.", "Ҳафтод евро, лутфан.", "Бигӯ: бо корт, лутфан", "Mit Karte, bitte.",
              "Бо корт, лутфан.", ["Karte, bitte."]),
            t("Noch etwas?", "Боз чизе?", "Бипурс: ҳаво куҷост?", "Wo ist die Luft?", "Ҳаво куҷост?",
              ["Wo kann ich Luft prüfen?"]),
            t("Da hinten. Gute Fahrt!", "Он ҷо, дар қафо. Роҳи сафед!", "Ташаккур гӯй", "Danke! Tschüss!",
              "Ташаккур! Хайр!", ["Vielen Dank!"]),
        ]),
    ]))

# ═════════════════════ 12. Роҳбандӣ ва дер мондан ═════════════════════
made.append(pack("traffic_de_tg", "Stau und Verspätung", "Роҳбандӣ ва дер мондан", "🚦", 12, D,
    "Дар роҳ роҳбандӣ (Stau) аст. Шумо ба мусофир ё мизоҷ мегӯед, ки дер мемонед, мепурсед, ки "
    "роҳи дигар ҳаст ё не, ва бубахшед мегӯед.",
    [
        ("Роҳбандӣ", [
            w("Stau", "роҳбандӣ", None),
            w("Verspätung", "дер мондан", None),
            w("Unfall", "садама", None),
            w("Baustelle", "корҳои сохтмонӣ", None),
            w("Umweg", "роҳи давр", None),
            w("Minuten", "дақиқа", None),
        ]),
        ("Роҳбандӣ!", [
            t("Warum fahren wir nicht?", "Чаро намеравем?", "Бигӯ: роҳбандӣ аст", "Stau.", "Роҳбандӣ.",
              ["Es gibt Stau.", "Da ist Stau."]),
            t("Wie lange?", "Чӣ қадар?", "Бигӯ: даҳ дақиқа", "Zehn Minuten.", "Даҳ дақиқа.", ["Ungefähr zehn Minuten."]),
            t("Ich habe einen Termin!", "Ман вохӯрӣ дорам!", "Бигӯ: бубахшед", "Entschuldigung.", "Бубахшед.",
              ["Es tut mir leid."]),
        ]),
        ("Ибораҳо", [
            s("Viel Stau", "Роҳбандии зиёд", None),
            s("Ein Unfall", "Як садама", None),
            s("Etwas später", "Каме дертар", None),
            s("Ein Umweg", "Роҳи давр", None),
            s("Bitte warten", "Лутфан интизор шавед", None),
            s("Gleich weiter", "Ҳозир давом медиҳем", None),
        ]),
        ("Роҳи дигар", [
            t("Gibt es einen Umweg?", "Роҳи дигар ҳаст?", "Бигӯ: ҳа, роҳи давр", "Ja, einen Umweg.", "Ҳа, роҳи давр.",
              ["Ja, über die Stadt."]),
            t("Ist er schneller?", "Тезтар аст?", "Бигӯ: ҳа, каме", "Ja, ein bisschen.", "Ҳа, каме.",
              ["Ja, etwas schneller."]),
            t("Gut, fahren Sie!", "Хуб, ҳайдед!", "Бигӯ: хуб", "Okay.", "Хуб.", ["Alles klar."]),
        ]),
        ("Ман дер мемонам", [
            s("Wir haben Verspätung.", "Мо дер мемонем.", None),
            s("Vorne ist ein Unfall.", "Пеш садама шудааст.", None),
            s("Ich fahre einen Umweg.", "Аз роҳи давр меравам.", None),
            s("Das kostet nicht mehr.", "Ин зиёд пул намешавад.", None),
            s("Zehn Minuten später.", "Даҳ дақиқа дертар.", None),
            s("Es tut mir leid.", "Бубахшед.", None),
        ]),
        ("Пули зиёд?", [
            t("Der Umweg kostet mehr, oder?", "Роҳи давр бештар пул мешавад, ҳа?", "Бигӯ: не, зиёд пул намешавад",
              "Nein, das kostet nicht mehr.", "Не, зиёд пул намешавад.", ["Nein, gleicher Preis."]),
            t("Gut. Wie lange noch?", "Хуб. Боз чӣ қадар?", "Бигӯ: понздаҳ дақиқа", "Fünfzehn Minuten.",
              "Понздаҳ дақиқа.", ["Noch fünfzehn Minuten."]),
            t("Okay, danke.", "Хуб, ташаккур.", "Бигӯ: бубахшед барои дер мондан", "Entschuldigung für die Verspätung.",
              "Барои дер мондан бубахшед.", ["Es tut mir leid."]),
        ]),
        ("Ба мизоҷ хабар додан", [
            s("Ich bin im Stau.", "Ман дар роҳбандӣ ҳастам.", None),
            s("Ich komme später.", "Дертар меоям.", None),
            s("Noch zwanzig Minuten.", "Боз бист дақиқа.", None),
            s("Ist das okay?", "Ин хуб аст?", None),
            s("Ich rufe wieder an.", "Боз занг мезанам.", None),
            s("Danke fürs Warten.", "Барои интизорӣ ташаккур.", None),
        ]),
        ("Занг: дер мемонам", [
            t("Hallo? Wo sind Sie?", "Ало? Шумо куҷоед?", "Бигӯ: дар роҳбандӣ ҳастам", "Ich bin im Stau.",
              "Ман дар роҳбандӣ ҳастам.", ["Im Stau, leider."]),
            t("Wann kommen Sie?", "Кай меоед?", "Бигӯ: боз бист дақиқа", "Noch zwanzig Minuten.",
              "Боз бист дақиқа.", ["In zwanzig Minuten."]),
            t("Okay, ich warte.", "Хуб, интизор мешавам.", "Бигӯ: барои интизорӣ ташаккур", "Danke fürs Warten.",
              "Барои интизорӣ ташаккур.", ["Vielen Dank!"]),
        ]),
        ("Миссия: садама дар роҳ", [
            t("Warum stehen wir?", "Чаро истодаем?", "Бигӯ: он ҷо, пеш, садама", "Da vorne ist ein Unfall.",
              "Он ҷо, пеш, садама.", ["Ein Unfall.", "Es gibt einen Unfall."]),
            t("Oh nein! Ich habe einen Termin.", "Эҳ! Ман вохӯрӣ дорам.", "Бигӯ: аз роҳи давр меравам",
              "Ich fahre einen Umweg.", "Аз роҳи давр меравам.", ["Ich nehme einen Umweg."]),
            t("Kostet das mehr?", "Бештар пул мешавад?", "Бигӯ: не, зиёд пул намешавад", "Nein, das kostet nicht mehr.",
              "Не, зиёд пул намешавад.", ["Nein."]),
            t("Danke!", "Ташаккур!", "Бигӯ: бо хурсандӣ", "Gerne.", "Бо хурсандӣ.", ["Kein Problem."]),
        ]),
    ]))

# ═════════════════════ 13. Расонидани фармоиш ═════════════════════
made.append(pack("delivery_de_tg", "Lieferung", "Расонидани фармоиш", "📦", 13, D,
    "Шумо бастаҳо ва хӯрок мерасонед: дари хонаро мезанед, номро месанҷед, имзо мегиред, агар "
    "касе набошад, бастаро ба ҳамсоя медиҳед.",
    [
        ("Расонидан", [
            w("Paket", "баста, посилка", None),
            w("Klingeln", "занги дарро задан", None),
            w("Nachbar", "ҳамсоя", None),
            w("Unterschrift", "имзо", None),
            w("Haustür", "дари даромад", None),
            w("Stock", "ошёна", None),
        ]),
        ("Баста омад", [
            t("Ja, bitte?", "Ҳа, лутфан?", "Бигӯ: баста барои Шмидт", "Ein Paket für Schmidt.", "Баста барои Шмидт.",
              ["Paket für Schmidt.", "Lieferung für Schmidt."]),
            t("Das bin ich.", "Ман ҳамонам.", "Бигӯ: имзо, лутфан", "Eine Unterschrift, bitte.", "Имзо, лутфан.",
              ["Bitte hier unterschreiben."]),
            t("Hier. Danke!", "Ин ҷо. Ташаккур!", "Бигӯ: рӯзи хуш!", "Schönen Tag!", "Рӯзи хуш!", ["Tschüss!"]),
        ]),
        ("Ибораҳо", [
            s("Ein Paket", "Як баста", None),
            s("Für Schmidt", "Барои Шмидт", None),
            s("Hier unterschreiben", "Ин ҷо имзо кунед", None),
            s("Welcher Stock?", "Кадом ошёна?", None),
            s("Beim Nachbarn", "Назди ҳамсоя", None),
            s("Ihr Essen", "Хӯроки шумо", None),
        ]),
        ("Кадом ошёна?", [
            t("Hallo? Wer ist da?", "Ало? Кӣ ҳаст?", "Бигӯ: расонидан, барои Шмидт", "Lieferung für Schmidt.",
              "Расонидан, барои Шмидт.", ["Ein Paket für Schmidt."]),
            t("Kommen Sie hoch.", "Боло биёед.", "Бипурс: кадом ошёна?", "Welcher Stock?", "Кадом ошёна?",
              ["Welche Etage?"]),
            t("Dritter Stock.", "Ошёнаи сеюм.", "Бигӯ: хуб", "Okay.", "Хуб.", ["Gut, ich komme."]),
        ]),
        ("Ман мерасонам", [
            s("Ich habe ein Paket.", "Ман як баста дорам.", None),
            s("Sind Sie Herr Schmidt?", "Шумо ҷаноби Шмидт?", None),
            s("Niemand ist zu Hause.", "Дар хона ҳеҷ кас нест.", None),
            s("Ich klingle beim Nachbarn.", "Занги ҳамсояро мезанам.", None),
            s("Ihr Essen ist da.", "Хӯроки шумо омад.", None),
            s("Guten Appetit!", "Ош шавад!", None),
        ]),
        ("Касе нест", [
            t("Ja? Ich bin der Nachbar.", "Ҳа? Ман ҳамсоя.", "Бигӯ: баста барои Шмидт", "Ein Paket für Schmidt.",
              "Баста барои Шмидт.", ["Ich habe ein Paket für Schmidt."]),
            t("Er ist nicht da.", "Ӯ нест.", "Бипурс: шумо онро мегиред?", "Nehmen Sie es?", "Шумо онро мегиред?",
              ["Können Sie es nehmen?"]),
            t("Ja, kein Problem.", "Ҳа, мушкил нест.", "Бигӯ: ин ҷо имзо кунед", "Bitte hier unterschreiben.",
              "Лутфан ин ҷо имзо кунед.", ["Eine Unterschrift, bitte."]),
        ]),
        ("Хӯрок мерасонам", [
            s("Ihre Pizza ist da.", "Питсаатон омад.", None),
            s("Schon bezahlt.", "Аллакай пардохт шуда.", None),
            s("Bar, bitte.", "Нақд, лутфан.", None),
            s("Noch heiß!", "Ҳанӯз гарм!", None),
            s("Die Cola fehlt?", "Кола нест?", None),
            s("Ich frage das Restaurant.", "Аз тарабхона мепурсам.", None),
        ]),
        ("Кола нест", [
            t("Danke! Aber die Cola fehlt.", "Ташаккур! Аммо кола нест.", "Бигӯ: бубахшед", "Entschuldigung!",
              "Бубахшед!", ["Oh, das tut mir leid."]),
            t("Was machen wir jetzt?", "Ҳоло чӣ кунем?", "Бигӯ: аз тарабхона мепурсам", "Ich frage das Restaurant.",
              "Аз тарабхона мепурсам.", ["Ich rufe das Restaurant an."]),
            t("Okay, danke.", "Хуб, ташаккур.", "Бигӯ: ош шавад!", "Guten Appetit!", "Ош шавад!", ["Gerne."]),
        ]),
        ("Миссия: рӯзи бастаҳо", [
            t("Hallo? Wer ist da?", "Ало? Кӣ ҳаст?", "Бигӯ: баста барои Шмидт", "Ein Paket für Schmidt.",
              "Баста барои Шмидт.", ["Lieferung für Schmidt."]),
            t("Kommen Sie hoch. Vierter Stock.", "Боло биёед. Ошёнаи чорум.", "Бигӯ: хуб", "Okay.", "Хуб.",
              ["Gut, ich komme."]),
            t("Hallo! Das ist für mich.", "Салом! Ин барои ман.", "Бигӯ: имзо, лутфан", "Eine Unterschrift, bitte.",
              "Имзо, лутфан.", ["Bitte hier unterschreiben."]),
            t("So, fertig. Danke!", "Хуб, тамом. Ташаккур!", "Бигӯ: рӯзи хуш!", "Schönen Tag!", "Рӯзи хуш!",
              ["Tschüss!", "Einen schönen Tag!"]),
        ]),
    ]))

# ═════════════════════ 15. Занг ба мизоҷ ═════════════════════
made.append(pack("customer_call_de_tg", "Kunden anrufen", "Занг ба мизоҷ", "📱", 15, D,
    "Шумо суроғаро намеёбед ва ба мизоҷ занг мезанед: худро муаррифӣ мекунед, мепурсед, ки даромадгоҳ "
    "куҷост, мегӯед, ки дар назди хона ҳастед.",
    [
        ("Телефон", [
            w("Anrufen", "занг задан", None),
            w("Eingang", "даромадгоҳ", None),
            w("Hof", "ҳавлӣ", None),
            w("Draußen", "берун", None),
            w("Unten", "поён", None),
            w("Finden", "ёфтан", None),
        ]),
        ("Ало, ман ронанда", [
            t("Hallo?", "Ало?", "Бигӯ: салом, ман ронанда", "Hallo, ich bin der Fahrer.", "Салом, ман ронанда.",
              ["Hallo, hier ist der Fahrer."]),
            t("Ah, gut! Wo sind Sie?", "А, хуб! Куҷоед?", "Бигӯ: назди хона", "Vor dem Haus.", "Назди хона.",
              ["Ich bin vor dem Haus."]),
            t("Ich komme runter.", "Поён меоям.", "Бигӯ: хуб, ман интизорам", "Gut, ich warte.", "Хуб, интизорам.",
              ["Okay, ich warte."]),
        ]),
        ("Ибораҳо", [
            s("Der Fahrer", "Ронанда", None),
            s("Vorm Haus", "Назди хона", None),
            s("Welcher Eingang?", "Кадом даромадгоҳ?", None),
            s("Im Hof", "Дар ҳавлӣ", None),
            s("Unten warten", "Поён интизор шудан", None),
            s("Nicht gefunden", "Наёфтам", None),
        ]),
        ("Даромадгоҳ", [
            t("Ich bin da, aber wo?", "Ман омадам, аммо куҷо?", "Бипурс: кадом даромадгоҳ?", "Welcher Eingang?",
              "Кадом даромадгоҳ?", ["Wo ist der Eingang?"]),
            t("Im Hof, links.", "Дар ҳавлӣ, тарафи чап.", "Бигӯ: хуб, ташаккур", "Gut, danke.", "Хуб, ташаккур.",
              ["Okay, danke."]),
            t("Bis gleich!", "То дидан!", "Бигӯ: то дидан", "Bis gleich!", "То дидан!", ["Tschüss!"]),
        ]),
        ("Ман занг мезанам", [
            s("Wo ist die Adresse?", "Суроға куҷост?", None),
            s("Bei Nummer zehn.", "Назди рақами даҳ.", None),
            s("Wo ist Ihr Eingang?", "Даромадгоҳатон куҷост?", None),
            s("Kommen Sie bitte runter?", "Поён меоед?", None),
            s("In fünf Minuten da.", "Баъди панҷ дақиқа мерасам.", None),
            s("Ich warte draußen.", "Берун интизорам.", None),
        ]),
        ("Суроғаро намеёбам", [
            t("Hallo, Schmidt?", "Ало, Шмидт?", "Бигӯ: салом, суроғаро намеёбам", "Hallo, ich finde die Adresse nicht.",
              "Салом, суроғаро намеёбам.", ["Ich finde Sie nicht."]),
            t("Wo sind Sie jetzt?", "Ҳоло куҷоед?", "Бигӯ: назди рақами даҳ", "Vor Nummer zehn.", "Назди рақами даҳ.",
              ["Ich bin vor Nummer zehn."]),
            t("Wir sind Nummer zwölf, im Hof.", "Мо рақами дувоздаҳ, дар ҳавлӣ.", "Бигӯ: хуб, ташаккур",
              "Gut, danke.", "Хуб, ташаккур.", ["Okay, ich komme."]),
        ]),
        ("Ҷавоб нест", [
            s("Niemand geht ran.", "Касе ҷавоб намедиҳад.", None),
            s("Ich schreibe eine Nachricht.", "Паём менависам.", None),
            s("Ich warte fünf Minuten.", "Панҷ дақиқа интизор мешавам.", None),
            s("Dann fahre ich.", "Баъд меравам.", None),
            s("Bitte rufen Sie zurück.", "Лутфан баргашта занг занед.", None),
            s("Mein Chef sagt das.", "Сардорам ҳамин мегӯяд.", None),
        ]),
        ("Ба сардор", [
            t("Ja? Was ist los?", "Ҳа? Чӣ гап?", "Бигӯ: касе ҷавоб намедиҳад", "Niemand geht ran.",
              "Касе ҷавоб намедиҳад.", ["Der Kunde geht nicht ran."]),
            t("Warte fünf Minuten.", "Панҷ дақиқа интизор шав.", "Бигӯ: хуб, ман паём менависам",
              "Gut, ich schreibe eine Nachricht.", "Хуб, паём менависам.", ["Okay."]),
            t("Und dann fahr weiter.", "Баъд давом деҳ.", "Бигӯ: фаҳмидам", "Verstanden.", "Фаҳмидам.",
              ["Okay, verstanden."]),
        ]),
        ("Миссия: занги мизоҷ", [
            t("Hallo?", "Ало?", "Бигӯ: салом, ман ронанда", "Hallo, ich bin der Fahrer.", "Салом, ман ронанда.",
              ["Hier ist der Fahrer."]),
            t("Ah! Wo sind Sie?", "А! Куҷоед?", "Бигӯ: суроғаро намеёбам", "Ich finde die Adresse nicht.",
              "Суроғаро намеёбам.", ["Ich finde Sie nicht."]),
            t("Wir sind im Hof, links.", "Мо дар ҳавлӣ, тарафи чап.", "Бигӯ: баъди панҷ дақиқа мерасам",
              "Ich bin in fünf Minuten da.", "Баъди панҷ дақиқа мерасам.", ["Fünf Minuten."]),
            t("Gut, bis gleich!", "Хуб, то дидан!", "Бигӯ: то дидан", "Bis gleich!", "То дидан!", ["Tschüss!"]),
        ]),
    ], mission_mode="call"))

# ═════════════════════ 17. Полиси роҳ ═════════════════════
made.append(pack("traffic_stop_de_tg", "Polizeikontrolle", "Полиси роҳ", "👮", 17, D,
    "Полис шуморо нигоҳ медорад. Шумо ором салом медиҳед, шаҳодатнома ва ҳуҷҷатҳои мошинро "
    "медиҳед, саволҳоро мефаҳмед ва бо эҳтиром ҷавоб медиҳед.",
    [
        ("Полис", [
            w("Polizei", "полис", None),
            w("Kontrolle", "санҷиш", None),
            w("Fahrzeugschein", "ҳуҷҷати мошин", None),
            w("Schnell", "тез", None),
            w("Strafe", "ҷарима", None),
            w("Ausweis", "шаҳодатнома (ID)", None),
        ]),
        ("Санҷиш", [
            t("Guten Tag. Polizei. Kontrolle.", "Рӯз ба хайр. Полис. Санҷиш.", "Салом гӯй", "Guten Tag.", "Рӯз ба хайр.",
              ["Hallo.", "Guten Tag!"]),
            t("Ihren Führerschein, bitte.", "Шаҳодатномаатон, лутфан.", "Бигӯ: мана", "Hier, bitte.", "Мана, марҳамат.",
              ["Bitte schön."]),
            t("Und den Fahrzeugschein.", "Ва ҳуҷҷати мошин.", "Бигӯ: як лаҳза", "Einen Moment.", "Як лаҳза.",
              ["Moment, bitte."]),
        ]),
        ("Ибораҳо", [
            s("Hier, bitte", "Мана, марҳамат", None),
            s("Einen Moment", "Як лаҳза", None),
            s("Mein Ausweis", "Шаҳодатномаи ман", None),
            s("Zu schnell", "Хеле тез", None),
            s("Ich verstehe", "Мефаҳмам", None),
            s("Nicht verstanden", "Нафаҳмидам", None),
        ]),
        ("Хеле тез", [
            t("Sie waren zu schnell.", "Шумо хеле тез ҳайдед.", "Бигӯ: бубахшед", "Entschuldigung.", "Бубахшед.",
              ["Es tut mir leid."]),
            t("Das kostet dreißig Euro.", "Ин сӣ евро ҷарима аст.", "Бигӯ: мефаҳмам", "Ich verstehe.", "Мефаҳмам.",
              ["Okay, ich verstehe."]),
            t("Zahlen Sie mit Karte?", "Бо корт пардохт мекунед?", "Бигӯ: ҳа", "Ja.", "Ҳа.", ["Ja, mit Karte."]),
        ]),
        ("Ҷавобҳо ба полис", [
            s("Ich bin Fahrer.", "Ман ронанда ҳастам.", None),
            s("Das ist ein Firmenauto.", "Ин мошини ширкат аст.", None),
            s("Die Papiere sind hier.", "Ҳуҷҷатҳо ин ҷоянд.", None),
            s("Bitte langsam sprechen.", "Лутфан оҳиста гап занед.", None),
            s("Ich habe nicht getrunken.", "Ман нанӯшидаам.", None),
            s("Darf ich jetzt fahren?", "Ҳоло равам мешавад?", None),
        ]),
        ("Мошини кӣ?", [
            t("Ist das Ihr Auto?", "Ин мошини шумост?", "Бигӯ: не, ин мошини ширкат аст", "Nein, das ist ein Firmenauto.",
              "Не, ин мошини ширкат аст.", ["Nein, von der Firma."]),
            t("Haben Sie Alkohol getrunken?", "Майзадагӣ кардед?", "Бигӯ: не, ман нанӯшидаам",
              "Nein, ich habe nicht getrunken.", "Не, ман нанӯшидаам.", ["Nein.", "Nein, nie."]),
            t("Gut.", "Хуб.", "Бипурс: ҳоло равам мешавад?", "Darf ich jetzt fahren?", "Ҳоло равам мешавад?",
              ["Kann ich fahren?"]),
        ]),
        ("Огоҳӣ", [
            s("Das Licht ist kaputt.", "Чароғ вайрон аст.", None),
            s("Das geht so nicht.", "Ин тавр намешавад.", None),
            s("Ich mache das morgen.", "Фардо мекунам.", None),
            s("Danke für die Info.", "Барои огоҳӣ ташаккур.", None),
            s("Gute Fahrt!", "Роҳи сафед!", None),
            s("Auf Wiedersehen!", "Хайр!", None),
        ]),
        ("Чароғ вайрон", [
            t("Ihr Licht hinten ist kaputt.", "Чароғи қафоатон вайрон аст.", "Бигӯ: фардо мекунам", "Ich mache das morgen.",
              "Фардо мекунам.", ["Ich repariere das morgen."]),
            t("Gut. Heute keine Strafe.", "Хуб. Имрӯз ҷарима нест.", "Бигӯ: барои огоҳӣ ташаккур",
              "Danke für die Info.", "Барои огоҳӣ ташаккур.", ["Vielen Dank!"]),
            t("Gute Fahrt!", "Роҳи сафед!", "Бигӯ: хайр!", "Auf Wiedersehen!", "Хайр!", ["Danke, tschüss!"]),
        ]),
        ("Миссия: санҷиши шабона", [
            t("Guten Abend. Polizei. Ihren Führerschein, bitte.", "Шом ба хайр. Полис. Шаҳодатнома, лутфан.",
              "Бигӯ: мана", "Hier, bitte.", "Мана, марҳамат.", ["Bitte schön."]),
            t("Ist das Ihr Auto?", "Ин мошини шумост?", "Бигӯ: не, ин мошини ширкат аст", "Nein, das ist ein Firmenauto.",
              "Не, ин мошини ширкат аст.", ["Nein, von der Firma."]),
            t("Haben Sie Alkohol getrunken?", "Майзадагӣ кардед?", "Бигӯ: не, ман нанӯшидаам",
              "Nein, ich habe nicht getrunken.", "Не, ман нанӯшидаам.", ["Nein."]),
            t("Alles gut. Gute Fahrt!", "Ҳама хуб. Роҳи сафед!", "Ташаккур гӯй ва хайр", "Danke! Auf Wiedersehen!",
              "Ташаккур! Хайр!", ["Danke, tschüss!"]),
        ]),
    ]))

# ═════════════════════ 18. Мошин вайрон шуд ═════════════════════
made.append(pack("repair_de_tg", "Das Auto ist kaputt", "Мошин вайрон шуд", "🔧", 18, D,
    "Мошин дар роҳ вайрон шуд. Шумо ба сардор ва ба устохона занг мезанед: мегӯед, ки чӣ "
    "кор намекунад, ки куҷоед, ва мепурсед, ки кай тайёр мешавад.",
    [
        ("Устохона", [
            w("Werkstatt", "устохона", None),
            w("Motor", "мотор", None),
            w("Batterie", "аккумулятор", None),
            w("Bremse", "тормоз", None),
            w("Reparieren", "таъмир кардан", None),
            w("Abschleppen", "бо мошини ёрӣ кашидан", None),
        ]),
        ("Мошин намеравад", [
            t("Was ist los?", "Чӣ шуд?", "Бигӯ: мошин намеравад", "Das Auto fährt nicht.", "Мошин намеравад.",
              ["Das Auto ist kaputt."]),
            t("Wo bist du?", "Ту куҷоӣ?", "Бигӯ: дар кӯчаи Ҳаупт", "In der Hauptstraße.", "Дар кӯчаи Ҳаупт.",
              ["Hauptstraße."]),
            t("Ich rufe die Werkstatt.", "Ба устохона занг мезанам.", "Бигӯ: хуб, ташаккур", "Gut, danke.",
              "Хуб, ташаккур.", ["Okay, danke."]),
        ]),
        ("Ибораҳо", [
            s("Der Motor", "Мотор", None),
            s("Die Batterie", "Аккумулятор", None),
            s("Geht nicht", "Кор намекунад", None),
            s("Komisches Geräusch", "Садои аҷиб", None),
            s("Wann fertig?", "Кай тайёр?", None),
            s("Wie teuer?", "Чӣ қадар гарон?", None),
        ]),
        ("Чӣ вайрон?", [
            t("Was ist kaputt?", "Чӣ вайрон аст?", "Бигӯ: аккумулятор, фикр мекунам", "Die Batterie, glaube ich.",
              "Аккумулятор, фикр мекунам.", ["Ich glaube, die Batterie."]),
            t("Gibt es ein Geräusch?", "Садо ҳаст?", "Бигӯ: ҳа, садои аҷиб", "Ja, ein komisches Geräusch.",
              "Ҳа, садои аҷиб.", ["Ja."]),
            t("Okay, wir kommen.", "Хуб, меоем.", "Бипурс: кай?", "Wann?", "Кай?", ["Wann kommen Sie?"]),
        ]),
        ("Ман мушкилро мегӯям", [
            s("Das Auto fährt nicht.", "Мошин намеравад.", None),
            s("Die Bremse ist schlecht.", "Тормоз бад аст.", None),
            s("Das Licht ist an.", "Чароғ даргирифт.", "Чароғи огоҳӣ дар панел."),
            s("Ich stehe rechts.", "Тарафи рост истодаам.", None),
            s("Bitte schnell kommen.", "Лутфан зуд биёед.", None),
            s("Wie lange dauert es?", "Чӣ қадар вақт мегирад?", None),
        ]),
        ("Занг ба устохона", [
            t("Werkstatt Becker, hallo?", "Устохонаи Беккер, ало?", "Бигӯ: салом, мошин намеравад",
              "Hallo, das Auto fährt nicht.", "Салом, мошин намеравад.", ["Hallo, mein Auto ist kaputt."]),
            t("Wo sind Sie?", "Куҷоед?", "Бигӯ: тарафи рост, кӯчаи Ҳаупт", "Rechts, Hauptstraße.",
              "Тарафи рост, кӯчаи Ҳаупт.", ["Ich stehe rechts."]),
            t("Wir kommen in dreißig Minuten.", "Баъди сӣ дақиқа меоем.", "Бигӯ: хуб, ташаккур", "Gut, danke.",
              "Хуб, ташаккур.", ["Okay, ich warte."]),
        ]),
        ("Таъмир", [
            s("Wann ist es fertig?", "Кай тайёр мешавад?", None),
            s("Was kostet das?", "Ин чанд пул?", None),
            s("Die Firma zahlt.", "Ширкат пардохт мекунад.", None),
            s("Ich brauche das Auto.", "Ба ман мошин лозим.", None),
            s("Morgen früh?", "Фардо саҳар?", None),
            s("Rufen Sie mich an.", "Ба ман занг занед.", None),
        ]),
        ("Кай тайёр?", [
            t("Die Batterie ist kaputt.", "Аккумулятор вайрон аст.", "Бипурс: кай тайёр мешавад?", "Wann ist es fertig?",
              "Кай тайёр мешавад?", ["Wann ist das Auto fertig?"]),
            t("Morgen früh.", "Фардо саҳар.", "Бипурс: чанд пул?", "Was kostet das?", "Чанд пул?",
              ["Wie teuer ist das?"]),
            t("Hundert Euro.", "Сад евро.", "Бигӯ: ширкат пардохт мекунад", "Die Firma zahlt.", "Ширкат пардохт мекунад.",
              ["Okay, die Firma zahlt."]),
        ]),
        ("Миссия: дар роҳ монд", [
            t("Werkstatt, hallo?", "Устохона, ало?", "Бигӯ: салом, мошин намеравад", "Hallo, das Auto fährt nicht.",
              "Салом, мошин намеравад.", ["Mein Auto ist kaputt."]),
            t("Was ist das Problem?", "Мушкил чист?", "Бигӯ: аккумулятор, фикр мекунам", "Die Batterie, glaube ich.",
              "Аккумулятор, фикр мекунам.", ["Ich glaube, die Batterie."]),
            t("Wo sind Sie?", "Куҷоед?", "Бигӯ: дар кӯчаи Ҳаупт", "In der Hauptstraße.", "Дар кӯчаи Ҳаупт.",
              ["Hauptstraße, rechts."]),
            t("Wir kommen bald.", "Ба наздикӣ меоем.", "Бигӯ: хуб, ман интизорам", "Gut, ich warte.", "Хуб, интизорам.",
              ["Danke, ich warte."]),
        ]),
    ], mission_mode="call"))

# ═════════════════════ 19. Садамаи хурд ═════════════════════
made.append(pack("accident_de_tg", "Ein kleiner Unfall", "Садамаи хурд", "💥", 19, D,
    "Садамаи хурд: ягон кас захмӣ нашуд, аммо мошинҳо осеб диданд. Шумо мепурсед, ки ҳама "
    "хубанд, ба полис занг мезанед ва бо ронандаи дигар маълумот иваз мекунед.",
    [
        ("Садама", [
            w("Unfall", "садама", None),
            w("Verletzt", "захмӣ", None),
            w("Polizei", "полис", None),
            w("Versicherung", "суғурта", None),
            w("Schaden", "зарар", None),
            w("Foto", "акс", None),
        ]),
        ("Ҳама хуб?", [
            t("Oh nein! Ein Unfall!", "Эҳ! Садама!", "Бипурс: шумо хубед?", "Sind Sie okay?", "Шумо хубед?",
              ["Alles okay?", "Sind Sie verletzt?"]),
            t("Ja, ich bin okay. Und Sie?", "Ҳа, хубам. Ва шумо?", "Бигӯ: ман ҳам хубам", "Ich bin auch okay.",
              "Ман ҳам хубам.", ["Mir geht es gut."]),
            t("Gut. Rufen wir die Polizei?", "Хуб. Ба полис занг занем?", "Бигӯ: ҳа", "Ja.", "Ҳа.",
              ["Ja, bitte.", "Ja, ich rufe an."]),
        ]),
        ("Ибораҳо", [
            s("Alles okay?", "Ҳама хуб?", None),
            s("Niemand verletzt", "Касе захмӣ нашуд", None),
            s("Ihre Versicherung?", "Суғуртаатон?", None),
            s("Ein Foto", "Як акс", None),
            s("Ihr Name?", "Номатон?", None),
            s("Ihre Nummer", "Рақаматон", None),
        ]),
        ("Суғурта", [
            t("Haben Sie eine Versicherung?", "Суғурта доред?", "Бигӯ: ҳа, мана", "Ja, hier.", "Ҳа, мана.",
              ["Ja, hier ist die Versicherung."]),
            t("Danke. Mein Name ist Weber.", "Ташаккур. Номи ман Вебер.", "Бипурс: рақаматон?", "Ihre Nummer?",
              "Рақаматон?", ["Ihre Telefonnummer, bitte?"]),
            t("Null eins sieben…", "Сифр як ҳафт…", "Бигӯ: оҳиста, лутфан", "Bitte langsam.", "Оҳиста, лутфан.",
              ["Langsam, bitte."]),
        ]),
        ("Ман мегӯям", [
            s("Niemand ist verletzt.", "Касе захмӣ нашуд.", None),
            s("Ich mache ein Foto.", "Акс мегирам.", None),
            s("Das ist ein Firmenauto.", "Ин мошини ширкат аст.", None),
            s("Ich rufe die Polizei.", "Ба полис занг мезанам.", None),
            s("Ich rufe meinen Chef.", "Ба сардорам занг мезанам.", None),
            s("Hier ist meine Versicherung.", "Мана суғуртаи ман.", None),
        ]),
        ("Занг ба полис", [
            t("Polizei, hallo?", "Полис, ало?", "Бигӯ: салом, садамаи хурд", "Hallo, ein kleiner Unfall.",
              "Салом, садамаи хурд.", ["Hallo, ich hatte einen Unfall."]),
            t("Ist jemand verletzt?", "Касе захмӣ шуд?", "Бигӯ: не, касе захмӣ нашуд", "Nein, niemand ist verletzt.",
              "Не, касе захмӣ нашуд.", ["Nein, niemand."]),
            t("Wo sind Sie?", "Куҷоед?", "Бигӯ: дар кӯчаи Ҳаупт", "In der Hauptstraße.", "Дар кӯчаи Ҳаупт.",
              ["Hauptstraße."]),
        ]),
        ("Ба сардор", [
            s("Ich hatte einen Unfall.", "Ман садама кардам.", None),
            s("Nur ein kleiner Schaden.", "Танҳо зарари хурд.", None),
            s("Die Polizei ist hier.", "Полис ин ҷост.", None),
            s("Ich habe Fotos.", "Ман акс дорам.", None),
            s("Was mache ich jetzt?", "Ҳоло чӣ кор кунам?", None),
            s("Es tut mir leid.", "Бубахшед.", None),
        ]),
        ("Занг ба сардор", [
            t("Hallo? Was ist los?", "Ало? Чӣ гап?", "Бигӯ: ман садама кардам", "Ich hatte einen Unfall.",
              "Ман садама кардам.", ["Ein kleiner Unfall."]),
            t("Bist du okay?", "Ту хубӣ?", "Бигӯ: ҳа, танҳо зарари хурд", "Ja, nur ein kleiner Schaden.",
              "Ҳа, танҳо зарари хурд.", ["Ja, ich bin okay."]),
            t("Gut. Mach Fotos.", "Хуб. Акс гир.", "Бигӯ: ман акс дорам", "Ich habe Fotos.", "Ман акс дорам.",
              ["Ja, ich habe Fotos."]),
        ]),
        ("Миссия: зарбаи хурд", [
            t("Oh! Sind Sie okay?", "О! Шумо хубед?", "Бигӯ: ҳа, ман хубам. Ва шумо?", "Ja, ich bin okay. Und Sie?",
              "Ҳа, хубам. Ва шумо?", ["Ja. Und Sie?"]),
            t("Auch okay. Ihre Versicherung, bitte.", "Ман ҳам. Суғуртаатон, лутфан.", "Бигӯ: мана суғуртаи ман",
              "Hier ist meine Versicherung.", "Мана суғуртаи ман.", ["Hier, bitte."]),
            t("Danke. Machen wir Fotos?", "Ташаккур. Акс гирем?", "Бигӯ: ҳа, ман акс мегирам", "Ja, ich mache Fotos.",
              "Ҳа, акс мегирам.", ["Ja, gute Idee."]),
            t("Gut. Und die Polizei?", "Хуб. Ва полис?", "Бигӯ: ман ба полис занг мезанам", "Ich rufe die Polizei.",
              "Ба полис занг мезанам.", ["Ich rufe an."]),
        ]),
    ]))

# ═════════════════════ 20. Навбати корӣ ва даромад ═════════════════════
made.append(pack("shift_de_tg", "Schicht und Verdienst", "Навбати корӣ ва даромад", "💰", 20, D,
    "Шумо бо сардор дар бораи навбат ва пул гап мезанед: чанд соат кор кардед, чанд сафар, кай "
    "маош меояд ва рӯзи истироҳат кай аст.",
    [
        ("Кор ва пул", [
            w("Schicht", "навбат (смена)", None),
            w("Fahrten", "сафарҳо", None),
            w("Stunden", "соатҳо", None),
            w("Lohn", "маош", None),
            w("Pause", "танаффус", None),
            w("Überstunden", "соатҳои иловагӣ", None),
        ]),
        ("Охири навбат", [
            t("Wie war die Schicht?", "Навбат чӣ хел гузашт?", "Бигӯ: хуб, бисёр сафар", "Gut, viele Fahrten.",
              "Хуб, сафарҳои зиёд.", ["Gut.", "Viel Arbeit."]),
            t("Wie viele Fahrten?", "Чанд сафар?", "Бигӯ: понздаҳ", "Fünfzehn.", "Понздаҳ.",
              ["Fünfzehn Fahrten."]),
            t("Super!", "Олӣ!", "Бигӯ: ташаккур", "Danke.", "Ташаккур.", ["Danke schön."]),
        ]),
        ("Ибораҳо", [
            s("Zehn Stunden", "Даҳ соат", None),
            s("Viele Fahrten", "Сафарҳои зиёд", None),
            s("Keine Pause", "Танаффус нест", None),
            s("Mein Lohn", "Маоши ман", None),
            s("Am Freitag", "Рӯзи ҷумъа", None),
            s("Nächste Woche", "Ҳафтаи оянда", None),
        ]),
        ("Танаффус", [
            t("Hattest du Pause?", "Танаффус доштӣ?", "Бигӯ: не, танаффус набуд", "Nein, keine Pause.",
              "Не, танаффус набуд.", ["Nein."]),
            t("Das ist nicht gut.", "Ин хуб нест.", "Бигӯ: даҳ соат кор кардам", "Ich habe zehn Stunden gearbeitet.",
              "Даҳ соат кор кардам.", ["Zehn Stunden, ohne Pause."]),
            t("Morgen machst du Pause.", "Фардо танаффус мекунӣ.", "Бигӯ: хуб, ташаккур", "Gut, danke.",
              "Хуб, ташаккур.", ["Okay, danke."]),
        ]),
        ("Ман дар бораи кор мегӯям", [
            s("Ich arbeite zehn Stunden.", "Даҳ соат кор мекунам.", None),
            s("Ich bin sehr müde.", "Ман хеле хастаам.", None),
            s("Wann kommt der Lohn?", "Маош кай меояд?", None),
            s("Bekomme ich Überstunden?", "Соатҳои иловагӣ мегирам?", None),
            s("Ich brauche frei.", "Ба ман истироҳат лозим.", None),
            s("Am Sonntag arbeite ich.", "Якшанбе кор мекунам.", None),
        ]),
        ("Маош", [
            t("Hast du Fragen?", "Савол дорӣ?", "Бипурс: маош кай меояд?", "Wann kommt der Lohn?", "Маош кай меояд?",
              ["Wann bekomme ich Geld?"]),
            t("Am Ende vom Monat.", "Дар охири моҳ.", "Бипурс: соатҳои иловагӣ мегирам?", "Bekomme ich Überstunden?",
              "Соатҳои иловагӣ мегирам?", ["Und die Überstunden?"]),
            t("Ja, natürlich.", "Ҳа, албатта.", "Бигӯ: олӣ, ташаккур", "Super, danke.", "Олӣ, ташаккур.",
              ["Gut, danke."]),
        ]),
        ("Рӯзи истироҳат", [
            s("Ich möchte Montag frei.", "Душанбе истироҳат мехоҳам.", None),
            s("Mein Kind ist krank.", "Фарзандам бемор аст.", None),
            s("Ich arbeite am Samstag.", "Шанбе кор мекунам.", None),
            s("Geht das?", "Мешавад?", None),
            s("Vielen Dank, Chef.", "Ташаккури зиёд, сардор.", None),
            s("Bis Dienstag!", "То сешанбе!", None),
        ]),
        ("Як рӯз истироҳат", [
            t("Ja, was ist?", "Ҳа, чӣ гап?", "Бигӯ: душанбе истироҳат мехоҳам", "Ich möchte Montag frei.",
              "Душанбе истироҳат мехоҳам.", ["Kann ich Montag frei haben?"]),
            t("Warum?", "Чаро?", "Бигӯ: фарзандам бемор аст", "Mein Kind ist krank.", "Фарзандам бемор аст.",
              ["Mein Sohn ist krank."]),
            t("Okay, kein Problem.", "Хуб, мушкил нест.", "Бигӯ: ташаккури зиёд, сардор", "Vielen Dank, Chef.",
              "Ташаккури зиёд, сардор.", ["Danke schön!"]),
        ]),
        ("Миссия: гап бо сардор", [
            t("Hallo! Wie war die Woche?", "Салом! Ҳафта чӣ хел гузашт?", "Бигӯ: хуб, сафарҳои зиёд",
              "Gut, viele Fahrten.", "Хуб, сафарҳои зиёд.", ["Gut, viel Arbeit."]),
            t("Super! Noch Fragen?", "Олӣ! Боз савол?", "Бипурс: маош кай меояд?", "Wann kommt der Lohn?",
              "Маош кай меояд?", ["Wann bekomme ich Geld?"]),
            t("Am Freitag.", "Рӯзи ҷумъа.", "Бигӯ: душанбе истироҳат мехоҳам", "Ich möchte Montag frei.",
              "Душанбе истироҳат мехоҳам.", ["Kann ich Montag frei haben?"]),
            t("Ja, das geht.", "Ҳа, мешавад.", "Бигӯ: ташаккури зиёд, сардор", "Vielen Dank, Chef.",
              "Ташаккури зиёд, сардор.", ["Danke schön!"]),
        ]),
    ]))

finish(made)
