"""ОЛМОНӢ → тоҷикӣ, «Гуфтор» A1 — нишаи «Ҳаёти рӯзмарра» (`life`), 04.10.2026.

14 вазъият барои тоҷике, ки дар Олмон зиндагӣ мекунад — ҳамон тартиби русӣ: фурудгоҳ,
меҳмонхона, автобус ва метро, қаҳвахона, супермаркет, телефон ва интернет, пул фиристодан,
дорухона, почта, ҳамсояҳо, гум шудан, вақти холӣ, занги фаврӣ (112), сартарошхона.

Роҳи `life` = 6 вазъияти умумӣ (1, 2 «Кор ёфтан», 6, 10, 14, 16) + ин 14 → 20.

Қоидаҳо — `_de_packs_lib.py`: рақам бо ҳарф; бо бегонаҳо ва кормандон — «Sie», бо ҳамсояи
наздик ва дӯст — «du». chunks ≤ 2 калима, sentences ≤ 4.
Транскрипсия: `node prisma/_de-fill-literal.mjs <slugs>`.

Аз ҷузвдони backend: python prisma/_de-life-a1-packs.py
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _de_packs_lib import *  # noqa: F401,F403

made = []
L = ["life"]

# ═════════════════════ 3. Дар фурудгоҳ ═════════════════════
made.append(pack("airport_de_tg", "Am Flughafen", "Дар фурудгоҳ", "🛫", 3, L,
    "Шумо ба Олмон парвоз мекунед ё бармегардед: дар қайди парвоз бағоҷро медиҳед, гейтро "
    "мепурсед ва агар ҷомадон наояд, хабар медиҳед.",
    [
        ("Фурудгоҳ", [
            w("Flughafen", "фурудгоҳ", None),
            w("Flug", "парвоз", None),
            w("Ticket", "чипта", None),
            w("Gate", "гейт (дари баромад)", None),
            w("Gepäck", "бағоҷ", None),
            w("Ankunft", "омадан, фуруд", None),
        ]),
        ("Қайди парвоз", [
            t("Guten Tag! Wohin fliegen Sie?", "Рӯз ба хайр! Ба куҷо парвоз мекунед?", "Бигӯ: ба Душанбе",
              "Nach Duschanbe.", "Ба Душанбе.", ["Ich fliege nach Duschanbe."]),
            t("Ihren Pass, bitte.", "Шиносномаатон, лутфан.", "Бигӯ: мана", "Hier, bitte.", "Мана, марҳамат.",
              ["Bitte schön."]),
            t("Ein Koffer?", "Як ҷомадон?", "Бигӯ: ҳа, як ҷомадон", "Ja, ein Koffer.", "Ҳа, як ҷомадон.", ["Ja."]),
        ]),
        ("Ибораҳо", [
            s("Welches Gate?", "Кадом гейт?", None),
            s("Mein Ticket", "Чиптаи ман", None),
            s("Ein Koffer", "Як ҷомадон", None),
            s("Am Fenster", "Назди тиреза", None),
            w("Pünktlich", "сари вақт", None),
            s("Gute Reise!", "Сафари хуш!", None),
        ]),
        ("Ҷой ва гейт", [
            t("Fenster oder Gang?", "Назди тиреза ё гузаргоҳ?", "Бигӯ: назди тиреза, лутфан", "Am Fenster, bitte.",
              "Назди тиреза, лутфан.", ["Fenster, bitte."]),
            t("Hier ist Ihr Ticket.", "Мана чиптаатон.", "Бипурс: кадом гейт?", "Welches Gate?", "Кадом гейт?",
              ["Wo ist mein Gate?"]),
            t("Gate zwölf.", "Гейти дувоздаҳ.", "Бигӯ: хуб, ташаккур", "Gut, danke.", "Хуб, ташаккур.", ["Danke schön."]),
        ]),
        ("Дар фурудгоҳ", [
            s("Wo ist Gate zwölf?", "Гейти дувоздаҳ куҷост?", None),
            s("Ist der Flug pünktlich?", "Парвоз сари вақт аст?", None),
            s("Mein Flug ist spät.", "Парвози ман дер аст.", None),
            s("Ich fliege nach Hause.", "Ба хона парвоз мекунам.", None),
            s("Wo ist der Ausgang?", "Баромадгоҳ куҷост?", None),
            s("Ich suche mein Gepäck.", "Бағоҷамро меҷӯям.", None),
        ]),
        ("Парвоз дер мешавад", [
            t("Kann ich helfen?", "Ёрӣ диҳам?", "Бипурс: парвоз сари вақт аст?", "Ist der Flug pünktlich?",
              "Парвоз сари вақт аст?", ["Ist mein Flug pünktlich?"]),
            t("Nein, eine Stunde später.", "Не, як соат дертар.", "Бигӯ: эҳ, хуб", "Oh, okay.", "Эҳ, хуб.",
              ["Schade.", "Okay, danke."]),
            t("Das Gate ist dort.", "Гейт он ҷост.", "Ташаккур гӯй", "Danke!", "Ташаккур!", ["Vielen Dank!"]),
        ]),
        ("Ҷомадон наомад", [
            s("Mein Koffer ist weg.", "Ҷомадонам гум шуд.", None),
            s("Er ist schwarz.", "Он сиёҳ аст.", None),
            s("Ich komme aus Istanbul.", "Аз Истамбул омадам.", None),
            s("Hier ist mein Ticket.", "Мана чиптаам.", None),
            s("Wann kommt er?", "Кай меояд?", None),
            s("Bringen Sie ihn?", "Онро меоред?", None),
        ]),
        ("Ҷомадони гумшуда", [
            t("Ja, bitte?", "Ҳа, лутфан?", "Бигӯ: ҷомадонам гум шуд", "Mein Koffer ist weg.", "Ҷомадонам гум шуд.",
              ["Mein Koffer ist nicht da."]),
            t("Welche Farbe?", "Чӣ ранг?", "Бигӯ: сиёҳ", "Schwarz.", "Сиёҳ.", ["Er ist schwarz."]),
            t("Wir bringen ihn morgen.", "Фардо меорем.", "Бигӯ: хуб, ташаккур", "Gut, danke.", "Хуб, ташаккур.",
              ["Okay, danke schön."]),
        ]),
        ("Миссия: парвоз ба хона", [
            t("Guten Tag! Wohin fliegen Sie?", "Рӯз ба хайр! Ба куҷо?", "Бигӯ: ба Душанбе", "Nach Duschanbe.",
              "Ба Душанбе.", ["Ich fliege nach Duschanbe."]),
            t("Fenster oder Gang?", "Тиреза ё гузаргоҳ?", "Бигӯ: назди тиреза, лутфан", "Am Fenster, bitte.",
              "Назди тиреза, лутфан.", ["Fenster, bitte."]),
            t("Hier ist Ihr Ticket.", "Мана чиптаатон.", "Бипурс: кадом гейт?", "Welches Gate?", "Кадом гейт?",
              ["Wo ist mein Gate?"]),
            t("Gate fünf. Gute Reise!", "Гейти панҷ. Сафари хуш!", "Ташаккур гӯй", "Vielen Dank!", "Ташаккури зиёд!",
              ["Danke schön!"]),
        ]),
    ]))

# ═════════════════════ 4. Қабул дар меҳмонхона ═════════════════════
made.append(pack("hotel_stay_de_tg", "Im Hotel", "Қабул дар меҳмонхона", "🏨", 4, L,
    "Шумо ба меҳмонхона меоед: номатонро мегӯед, ҳуҷра мегиред, мепурсед, ки ноништа соати чанд "
    "аст ва Wi-Fi ҳаст, ва агар чизе кор накунад, хабар медиҳед.",
    [
        ("Меҳмонхона", [
            w("Hotel", "меҳмонхона", None),
            w("Zimmer", "ҳуҷра", None),
            w("Nacht", "шаб", None),
            w("Frühstück", "ноништа", None),
            w("Aufzug", "лифт", None),
            w("Reservierung", "фармоиш (броня)", None),
        ]),
        ("Қабул", [
            t("Guten Abend! Haben Sie eine Reservierung?", "Шом ба хайр! Фармоиш доред?", "Бигӯ: ҳа",
              "Ja.", "Ҳа.", ["Ja, ich habe eine Reservierung."]),
            t("Wie ist Ihr Name?", "Номатон?", "Бигӯ: Каримов", "Karimov.", "Каримов.", ["Mein Name ist Karimov."]),
            t("Zwei Nächte?", "Ду шаб?", "Бигӯ: ҳа, ду шаб", "Ja, zwei Nächte.", "Ҳа, ду шаб.", ["Ja."]),
        ]),
        ("Ибораҳо", [
            s("Zwei Nächte", "Ду шаб", None),
            s("Ein Zimmer", "Як ҳуҷра", None),
            s("Welcher Stock?", "Кадом ошёна?", None),
            s("Wann Frühstück?", "Ноништа кай?", None),
            s("Das Passwort?", "Рамз?", None),
            s("Der Aufzug", "Лифт", None),
        ]),
        ("Калид", [
            t("Hier ist Ihr Schlüssel.", "Мана калидатон.", "Бипурс: кадом ошёна?", "Welcher Stock?", "Кадом ошёна?",
              ["In welchem Stock?"]),
            t("Dritter Stock.", "Ошёнаи сеюм.", "Бипурс: ноништа кай?", "Wann ist Frühstück?", "Ноништа кай аст?",
              ["Frühstück wann?"]),
            t("Von sieben bis zehn.", "Аз ҳафт то даҳ.", "Ташаккур гӯй", "Danke!", "Ташаккур!", ["Danke schön."]),
        ]),
        ("Саволҳо", [
            s("Ich habe reserviert.", "Ман фармоиш додаам.", None),
            s("Gibt es WLAN?", "Wi-Fi ҳаст?", None),
            s("Wo ist der Aufzug?", "Лифт куҷост?", None),
            s("Mit Frühstück?", "Бо ноништа?", None),
            s("Wann muss ich gehen?", "Кай бояд равам?", None),
            s("Ein ruhiges Zimmer, bitte.", "Ҳуҷраи ором, лутфан.", None),
        ]),
        ("Wi-Fi ва ноништа", [
            t("Noch Fragen?", "Боз савол?", "Бипурс: Wi-Fi ҳаст?", "Gibt es WLAN?", "Wi-Fi ҳаст?",
              ["Haben Sie WLAN?"]),
            t("Ja, das Passwort ist hier.", "Ҳа, рамз ин ҷо.", "Бипурс: бо ноништа?", "Mit Frühstück?",
              "Бо ноништа?", ["Ist Frühstück dabei?"]),
            t("Ja, mit Frühstück.", "Ҳа, бо ноништа.", "Бигӯ: олӣ, ташаккур", "Super, danke.", "Олӣ, ташаккур.",
              ["Danke schön."]),
        ]),
        ("Мушкил дар ҳуҷра", [
            s("Die Heizung geht nicht.", "Гармкунак кор намекунад.", None),
            s("Kein warmes Wasser.", "Оби гарм нест.", None),
            s("Das Zimmer ist laut.", "Ҳуҷра пурсадо аст.", None),
            s("Ein anderes Zimmer?", "Ҳуҷраи дигар?", None),
            s("Bitte neue Handtücher.", "Лутфан сачоқҳои нав.", None),
            s("Danke für die Hilfe.", "Барои ёрӣ ташаккур.", None),
        ]),
        ("Ба қабулгоҳ", [
            t("Rezeption, hallo?", "Қабулгоҳ, ало?", "Бигӯ: оби гарм нест", "Kein warmes Wasser.", "Оби гарм нест.",
              ["Es gibt kein warmes Wasser."]),
            t("Welches Zimmer?", "Кадом ҳуҷра?", "Бигӯ: ҳуҷраи сесаду ду", "Zimmer dreihundertzwei.",
              "Ҳуҷраи сесаду ду.", ["Dreihundertzwei."]),
            t("Wir kommen sofort.", "Ҳозир меоем.", "Бигӯ: барои ёрӣ ташаккур", "Danke für die Hilfe.",
              "Барои ёрӣ ташаккур.", ["Danke!"]),
        ]),
        ("Миссия: шаби аввал", [
            t("Guten Abend! Ihr Name, bitte?", "Шом ба хайр! Номатон?", "Бигӯ: Каримов, ман фармоиш додаам",
              "Karimov. Ich habe reserviert.", "Каримов. Фармоиш додаам.", ["Karimov."]),
            t("Ja, zwei Nächte. Hier ist der Schlüssel.", "Ҳа, ду шаб. Мана калид.", "Бипурс: Wi-Fi ҳаст?",
              "Gibt es WLAN?", "Wi-Fi ҳаст?", ["Haben Sie WLAN?"]),
            t("Ja, gratis.", "Ҳа, ройгон.", "Бипурс: ноништа кай?", "Wann ist Frühstück?", "Ноништа кай аст?",
              ["Und das Frühstück?"]),
            t("Ab sieben Uhr.", "Аз соати ҳафт.", "Ташаккур гӯй", "Vielen Dank!", "Ташаккури зиёд!", ["Danke!"]),
        ]),
    ]))

# ═════════════════════ 5. Автобус ва метро ═════════════════════
made.append(pack("transit_de_tg", "Bus und Bahn", "Автобус ва метро", "🚇", 5, L,
    "Шумо бо автобус ва метро (U-Bahn) мегардед: чипта мехаред, мепурсед, ки кадом хат ба куҷо "
    "меравад, дар куҷо фуромадан лозим ва аз ронанда ёрӣ мехоҳед.",
    [
        ("Нақлиёт", [
            w("Bus", "автобус", None),
            w("Bahn", "қатора, метро", "«U-Bahn» — метро, «S-Bahn» — қатораи шаҳрӣ."),
            w("Fahrkarte", "чипта", None),
            w("Haltestelle", "истгоҳ", None),
            w("Linie", "хат, рақами автобус", None),
            w("Aussteigen", "фуромадан", None),
        ]),
        ("Чипта", [
            t("Hallo! Was möchten Sie?", "Салом! Чӣ мехоҳед?", "Бигӯ: як чипта, лутфан", "Eine Fahrkarte, bitte.",
              "Як чипта, лутфан.", ["Ein Ticket, bitte."]),
            t("Wohin?", "Ба куҷо?", "Бигӯ: ба маркази шаҳр", "Ins Zentrum.", "Ба маркази шаҳр.", ["Zum Zentrum."]),
            t("Drei Euro.", "Се евро.", "Бигӯ: мана", "Hier, bitte.", "Мана, марҳамат.", ["Bitte schön."]),
        ]),
        ("Ибораҳо", [
            s("Welche Linie?", "Кадом хат?", None),
            s("Ins Zentrum", "Ба марказ", None),
            s("Nächste Haltestelle", "Истгоҳи навбатӣ", None),
            s("Hier aussteigen", "Ин ҷо фуромадан", None),
            s("Wie lange?", "Чӣ қадар?", None),
            s("Einmal, bitte", "Як бор, лутфан", None),
        ]),
        ("Кадом автобус?", [
            t("Kann ich helfen?", "Ёрӣ диҳам?", "Бипурс: кадом хат ба вокзал?", "Welche Linie zum Bahnhof?",
              "Кадом хат ба вокзал?", ["Welcher Bus fährt zum Bahnhof?"]),
            t("Die Linie fünf.", "Хати панҷ.", "Бипурс: истгоҳ куҷост?", "Wo ist die Haltestelle?",
              "Истгоҳ куҷост?", ["Wo hält der Bus?"]),
            t("Da drüben.", "Он тараф.", "Ташаккур гӯй", "Danke!", "Ташаккур!", ["Vielen Dank!"]),
        ]),
        ("Дар роҳ", [
            s("Zum Bahnhof, bitte?", "Ба вокзал, лутфан?", None),
            s("Wo muss ich aussteigen?", "Куҷо фуроям?", None),
            s("Ist das hier frei?", "Ин ҷо холист?", None),
            s("Ich steige hier aus.", "Ман ин ҷо мефуроям.", None),
            s("Die Bahn ist voll.", "Метро пур аст.", None),
            s("Ich habe eine Monatskarte.", "Ман чиптаи моҳона дорам.", None),
        ]),
        ("Аз ронанда мепурсам", [
            t("Ja?", "Ҳа?", "Бипурс: ба вокзал меравед?", "Fahren Sie zum Bahnhof?", "Ба вокзал меравед?",
              ["Fährt der Bus zum Bahnhof?"]),
            t("Ja, steigen Sie ein.", "Ҳа, савор шавед.", "Бипурс: куҷо фуроям?", "Wo muss ich aussteigen?",
              "Куҷо фуроям?", ["Wann steige ich aus?"]),
            t("Ich sage es Ihnen.", "Ба шумо мегӯям.", "Ташаккур гӯй", "Danke schön!", "Ташаккури зиёд!", ["Danke!"]),
        ]),
        ("Назорати чипта", [
            s("Fahrkarten, bitte!", "Чиптаҳо, лутфан!", "Назоратчӣ мегӯяд."),
            s("Hier ist meine Karte.", "Мана чиптаи ман.", None),
            s("Ich habe kein Ticket.", "Чипта надорам.", None),
            s("Der Automat geht nicht.", "Автомат кор намекунад.", None),
            s("Wo kaufe ich das?", "Инро куҷо харам?", None),
            s("In der App.", "Дар барнома.", None),
        ]),
        ("Назоратчӣ", [
            t("Fahrkarte, bitte!", "Чипта, лутфан!", "Бигӯ: мана чиптаи ман", "Hier ist meine Karte.",
              "Мана чиптаи ман.", ["Hier, bitte."]),
            t("Danke. Alles gut.", "Ташаккур. Ҳама хуб.", "Бипурс: истгоҳи навбатӣ вокзал аст?",
              "Ist der Bahnhof die nächste?", "Истгоҳи навбатӣ вокзал аст?", ["Ist die nächste der Bahnhof?"]),
            t("Ja, steigen Sie dort aus.", "Ҳа, он ҷо фуроед.", "Бигӯ: хуб, ташаккур", "Gut, danke.", "Хуб, ташаккур.",
              ["Danke!"]),
        ]),
        ("Миссия: ба вокзал", [
            t("Hallo! Was möchten Sie?", "Салом! Чӣ мехоҳед?", "Бигӯ: як чипта ба вокзал", "Eine Fahrkarte zum Bahnhof.",
              "Як чипта ба вокзал.", ["Ein Ticket zum Bahnhof, bitte."]),
            t("Drei Euro, bitte.", "Се евро, лутфан.", "Бипурс: кадом хат?", "Welche Linie?", "Кадом хат?",
              ["Welcher Bus?"]),
            t("Die U-Bahn, Linie zwei.", "Метро, хати ду.", "Бипурс: чӣ қадар?", "Wie lange dauert das?",
              "Чӣ қадар вақт мегирад?", ["Wie lange?"]),
            t("Zehn Minuten.", "Даҳ дақиқа.", "Ташаккур гӯй", "Danke schön!", "Ташаккури зиёд!", ["Vielen Dank!"]),
        ]),
    ]))

# ═════════════════════ 7. Дар қаҳвахона ═════════════════════
made.append(pack("coffee_shop_de_tg", "Im Café", "Қаҳвахонаи шаҳр", "☕", 7, L,
    "Шумо ба қаҳвахона меравед: нӯшокӣ ва ширинӣ фармоиш медиҳед, мегӯед, ки шакар лозим аст ё "
    "не, ин ҷо менӯшед ё мебаред, ва пардохт мекунед.",
    [
        ("Қаҳвахона", [
            w("Kaffee", "қаҳва", None),
            w("Tee", "чой", None),
            w("Kuchen", "пирожни, торт", None),
            w("Zucker", "шакар", None),
            w("Milch", "шир", None),
            w("Groß", "калон", None),
        ]),
        ("Фармоиш", [
            t("Hallo! Was darf es sein?", "Салом! Чӣ мехоҳед?", "Бигӯ: як қаҳва, лутфан", "Einen Kaffee, bitte.",
              "Як қаҳва, лутфан.", ["Ein Kaffee, bitte."]),
            t("Groß oder klein?", "Калон ё хурд?", "Бигӯ: хурд", "Klein.", "Хурд.", ["Klein, bitte."]),
            t("Mit Milch?", "Бо шир?", "Бигӯ: ҳа, лутфан", "Ja, bitte.", "Ҳа, лутфан.", ["Ja.", "Nein, danke."]),
        ]),
        ("Ибораҳо", [
            s("Einen Tee", "Як чой", None),
            s("Ohne Zucker", "Бе шакар", None),
            s("Mit Milch", "Бо шир", None),
            s("Zum Mitnehmen", "Барои бурдан", None),
            s("Hier trinken", "Ин ҷо нӯшидан", None),
            s("Ein Stück", "Як порча", None),
        ]),
        ("Барои бурдан?", [
            t("Hier oder zum Mitnehmen?", "Ин ҷо ё барои бурдан?", "Бигӯ: барои бурдан", "Zum Mitnehmen.",
              "Барои бурдан.", ["Mitnehmen, bitte."]),
            t("Mit Zucker?", "Бо шакар?", "Бигӯ: бе шакар", "Ohne Zucker.", "Бе шакар.", ["Ohne, bitte."]),
            t("Noch etwas?", "Боз чизе?", "Бигӯ: як порча торт", "Ein Stück Kuchen.", "Як порча торт.",
              ["Ein Stück Kuchen, bitte."]),
        ]),
        ("Ман фармоиш медиҳам", [
            s("Ich nehme einen Tee.", "Ман як чой мегирам.", None),
            s("Was kostet der Kuchen?", "Торт чанд пул?", None),
            s("Ist hier frei?", "Ин ҷо холист?", None),
            s("Noch einen Kaffee, bitte.", "Боз як қаҳва, лутфан.", None),
            s("Das schmeckt sehr gut.", "Хеле бомаза аст.", None),
            s("Wo ist die Toilette?", "Ҳоҷатхона куҷост?", None),
        ]),
        ("Ҷой ва нарх", [
            t("Hallo!", "Салом!", "Бипурс: ин ҷо холист?", "Ist hier frei?", "Ин ҷо холист?",
              ["Ist der Platz frei?"]),
            t("Ja, bitte.", "Ҳа, марҳамат.", "Бипурс: торт чанд пул?", "Was kostet der Kuchen?", "Торт чанд пул?",
              ["Wie viel kostet der Kuchen?"]),
            t("Drei Euro.", "Се евро.", "Бигӯ: хуб, як порча, лутфан", "Gut, ein Stück, bitte.", "Хуб, як порча, лутфан.",
              ["Einen, bitte."]),
        ]),
        ("Пардохт", [
            s("Zahlen, bitte.", "Ҳисоб, лутфан.", None),
            s("Mit Karte geht?", "Бо корт мешавад?", None),
            s("Das macht sechs Euro.", "Шаш евро мешавад.", None),
            s("Stimmt so.", "Бақия лозим нест.", None),
            s("Schönen Tag noch!", "Рӯзи хуш!", None),
            s("Bis bald!", "То дидан!", None),
        ]),
        ("Ҳисоб", [
            t("Ja, bitte?", "Ҳа, лутфан?", "Бигӯ: ҳисоб, лутфан", "Zahlen, bitte.", "Ҳисоб, лутфан.",
              ["Die Rechnung, bitte."]),
            t("Das macht sechs Euro.", "Шаш евро мешавад.", "Бипурс: бо корт мешавад?", "Mit Karte geht?",
              "Бо корт мешавад?", ["Kann ich mit Karte zahlen?"]),
            t("Ja, natürlich.", "Ҳа, албатта.", "Ташаккур гӯй", "Danke!", "Ташаккур!", ["Danke schön."]),
        ]),
        ("Миссия: қаҳваи субҳ", [
            t("Guten Morgen! Was darf es sein?", "Субҳ ба хайр! Чӣ мехоҳед?", "Бигӯ: як чой, лутфан",
              "Einen Tee, bitte.", "Як чой, лутфан.", ["Ein Tee, bitte."]),
            t("Mit Zucker?", "Бо шакар?", "Бигӯ: бе шакар", "Ohne Zucker.", "Бе шакар.", ["Nein, ohne."]),
            t("Hier oder zum Mitnehmen?", "Ин ҷо ё барои бурдан?", "Бигӯ: ин ҷо", "Hier, bitte.", "Ин ҷо, лутфан.",
              ["Hier."]),
            t("Zwei Euro fünfzig.", "Ду евро панҷоҳ.", "Бигӯ: бо корт, лутфан", "Mit Karte, bitte.", "Бо корт, лутфан.",
              ["Karte, bitte."]),
        ]),
    ]))

# ═════════════════════ 8. Дар супермаркет ═════════════════════
made.append(pack("supermarket_de_tg", "Einkaufen im Laden", "Дар супермаркет", "🛒", 8, L,
    "Шумо харид мекунед: мепурсед, ки нон ва гӯшт дар куҷост, гӯшти халол меҷӯед, нархро "
    "мепурсед ва дар касса халта мегиред.",
    [
        ("Харид", [
            w("Brot", "нон", None),
            w("Fleisch", "гӯшт", None),
            w("Obst", "мева", None),
            w("Gemüse", "сабзавот", None),
            w("Kilo", "кило", None),
            w("Halal", "халол", None),
        ]),
        ("Куҷост?", [
            t("Kann ich helfen?", "Ёрӣ диҳам?", "Бипурс: нон куҷост?", "Wo ist das Brot?", "Нон куҷост?",
              ["Wo gibt es Brot?"]),
            t("Da vorne, links.", "Пеш, тарафи чап.", "Бипурс: ва гӯшт?", "Und das Fleisch?", "Ва гӯшт?",
              ["Wo ist das Fleisch?"]),
            t("Hinten rechts.", "Дар қафо, рост.", "Ташаккур гӯй", "Danke!", "Ташаккур!", ["Danke schön."]),
        ]),
        ("Ибораҳо", [
            s("Ein Kilo", "Як кило", None),
            s("Halal Fleisch", "Гӯшти халол", None),
            s("Wie viel?", "Чанд?", None),
            s("Eine Tüte", "Як халта", None),
            s("Sehr frisch", "Хеле тоза", None),
            s("Im Angebot", "Бо тахфиф", None),
        ]),
        ("Гӯшти халол", [
            t("Was suchen Sie?", "Чӣ меҷӯед?", "Бигӯ: гӯшти халол", "Halal Fleisch.", "Гӯшти халол.",
              ["Ich suche Halal Fleisch."]),
            t("Leider nicht hier.", "Мутаассифона ин ҷо нест.", "Бипурс: дар куҷо?", "Wo dann?", "Пас дар куҷо?",
              ["Wo gibt es das?"]),
            t("Im türkischen Laden.", "Дар мағозаи туркӣ.", "Ташаккур гӯй", "Danke für die Info!", "Барои маълумот ташаккур!",
              ["Danke!"]),
        ]),
        ("Дар бахши мева", [
            s("Ein Kilo Äpfel, bitte.", "Як кило себ, лутфан.", None),
            s("Was kostet das?", "Ин чанд пул?", None),
            s("Ist das frisch?", "Ин тоза аст?", None),
            s("Das ist zu teuer.", "Ин хеле гарон аст.", None),
            s("Ich nehme das.", "Инро мегирам.", None),
            s("Das ist alles.", "Ҳамин.", None),
        ]),
        ("Себ ва нарх", [
            t("Was möchten Sie?", "Чӣ мехоҳед?", "Бигӯ: як кило себ, лутфан", "Ein Kilo Äpfel, bitte.",
              "Як кило себ, лутфан.", ["Äpfel, bitte."]),
            t("Noch etwas?", "Боз чизе?", "Бипурс: ин чанд пул?", "Was kostet das?", "Ин чанд пул?",
              ["Wie viel kostet das?"]),
            t("Drei Euro.", "Се евро.", "Бигӯ: инро мегирам", "Ich nehme das.", "Инро мегирам.", ["Gut, danke."]),
        ]),
        ("Дар касса", [
            s("Brauchen Sie eine Tüte?", "Халта лозим?", None),
            s("Ja, eine Tüte.", "Ҳа, як халта.", None),
            s("Ich habe eine Tasche.", "Ман сумка дорам.", None),
            s("Mit Karte, bitte.", "Бо корт, лутфан.", None),
            s("Den Bon, bitte.", "Чек, лутфан.", None),
            s("Schönen Tag!", "Рӯзи хуш!", None),
        ]),
        ("Касса", [
            t("Brauchen Sie eine Tüte?", "Халта лозим?", "Бигӯ: не, сумка дорам", "Nein, ich habe eine Tasche.",
              "Не, сумка дорам.", ["Nein, danke."]),
            t("Zwölf Euro, bitte.", "Дувоздаҳ евро, лутфан.", "Бигӯ: бо корт, лутфан", "Mit Karte, bitte.",
              "Бо корт, лутфан.", ["Karte, bitte."]),
            t("Danke. Den Bon?", "Ташаккур. Чек?", "Бигӯ: не, ташаккур", "Nein, danke.", "Не, ташаккур.", ["Ja, bitte."]),
        ]),
        ("Миссия: хариди ҳафта", [
            t("Kann ich helfen?", "Ёрӣ диҳам?", "Бипурс: нон куҷост?", "Wo ist das Brot?", "Нон куҷост?",
              ["Wo gibt es Brot?"]),
            t("Da vorne. Noch etwas?", "Пеш. Боз чизе?", "Бипурс: гӯшти халол ҳаст?", "Gibt es Halal Fleisch?",
              "Гӯшти халол ҳаст?", ["Haben Sie Halal Fleisch?"]),
            t("Ja, hinten rechts.", "Ҳа, дар қафо, рост.", "Ташаккур гӯй", "Danke!", "Ташаккур!", ["Super, danke!"]),
            t("Brauchen Sie eine Tüte?", "Халта лозим?", "Бигӯ: ҳа, як халта", "Ja, eine Tüte.", "Ҳа, як халта.",
              ["Ja, bitte."]),
        ]),
    ]))

# ═════════════════════ 9. Телефон ва интернет ═════════════════════
made.append(pack("phone_plan_de_tg", "Handy und Internet", "Телефон ва интернет", "📶", 9, L,
    "Шумо SIM-корт ва интернет мехаред: тарифро мепурсед, чанд гигабайт ва чанд пул, рақами "
    "нав мегиред ва мегӯед, ки интернет кор намекунад.",
    [
        ("Телефон", [
            w("Handy", "телефони мобилӣ", None),
            w("SIM-Karte", "SIM-корт", None),
            w("Tarif", "тариф", None),
            w("Guthaben", "баланс (пул дар телефон)", None),
            w("Netz", "шабака", None),
            w("Aufladen", "пур кардан (пул)", None),
        ]),
        ("SIM-корт", [
            t("Hallo! Was suchen Sie?", "Салом! Чӣ меҷӯед?", "Бигӯ: SIM-корт", "Eine SIM-Karte.", "SIM-корт.",
              ["Ich brauche eine SIM-Karte."]),
            t("Mit Vertrag?", "Бо шартнома?", "Бигӯ: не, бе шартнома", "Nein, ohne Vertrag.", "Не, бе шартнома.",
              ["Ohne Vertrag, bitte."]),
            t("Ihren Pass, bitte.", "Шиносномаатон, лутфан.", "Бигӯ: мана", "Hier, bitte.", "Мана, марҳамат.",
              ["Bitte schön."]),
        ]),
        ("Ибораҳо", [
            s("Ohne Vertrag", "Бе шартнома", None),
            s("Zehn Gigabyte", "Даҳ гигабайт", None),
            s("Pro Monat", "Дар як моҳ", None),
            s("Kein Netz", "Шабака нест", None),
            s("Zwanzig Euro", "Бист евро", None),
            s("Neue Nummer", "Рақами нав", None),
        ]),
        ("Тариф", [
            t("Dieser Tarif ist gut.", "Ин тариф хуб аст.", "Бипурс: чанд пул?", "Was kostet das?", "Чанд пул?",
              ["Wie viel kostet der Tarif?"]),
            t("Zehn Euro pro Monat.", "Даҳ евро дар як моҳ.", "Бипурс: чанд гигабайт?", "Wie viele Gigabyte?",
              "Чанд гигабайт?", ["Wie viel Internet?"]),
            t("Zwanzig Gigabyte.", "Бист гигабайт.", "Бигӯ: хуб, инро мегирам", "Gut, das nehme ich.",
              "Хуб, инро мегирам.", ["Okay, ich nehme das."]),
        ]),
        ("Ман мепурсам", [
            s("Ich brauche Internet.", "Ба ман интернет лозим.", None),
            s("Anrufe nach Tadschikistan?", "Занг ба Тоҷикистон?", None),
            s("Ich möchte aufladen.", "Пул гузоштан мехоҳам.", None),
            s("Mein Internet geht nicht.", "Интернетам кор намекунад.", None),
            s("Wie ist meine Nummer?", "Рақами ман чӣ?", None),
            s("Ich habe kein Netz.", "Шабака надорам.", None),
        ]),
        ("Занг ба хона", [
            t("Noch Fragen?", "Боз савол?", "Бипурс: ба Тоҷикистон занг зада метавонам?",
              "Kann ich nach Tadschikistan anrufen?", "Ба Тоҷикистон занг зада метавонам?", ["Auch nach Tadschikistan?"]),
            t("Ja, aber das kostet extra.", "Ҳа, аммо алоҳида пул аст.", "Бипурс: чанд пул?", "Wie viel?", "Чанд?",
              ["Was kostet das?"]),
            t("Zehn Cent pro Minute.", "Даҳ сент дар як дақиқа.", "Бигӯ: хуб, ташаккур", "Gut, danke.",
              "Хуб, ташаккур.", ["Okay."]),
        ]),
        ("Интернет кор намекунад", [
            s("Das Internet ist langsam.", "Интернет суст аст.", None),
            s("Ich habe Guthaben.", "Ман баланс дорам.", None),
            s("Bitte prüfen Sie das.", "Лутфан инро санҷед.", None),
            s("Handy neu starten?", "Телефонро аз нав фурӯзонам?", None),
            s("Jetzt geht es.", "Ҳоло кор мекунад.", None),
            s("Vielen Dank!", "Ташаккури зиёд!", None),
        ]),
        ("Мушкил", [
            t("Was ist das Problem?", "Мушкил чист?", "Бигӯ: интернетам кор намекунад", "Mein Internet geht nicht.",
              "Интернетам кор намекунад.", ["Kein Internet."]),
            t("Haben Sie Guthaben?", "Баланс доред?", "Бигӯ: ҳа, баланс дорам", "Ja, ich habe Guthaben.",
              "Ҳа, баланс дорам.", ["Ja."]),
            t("Starten Sie das Handy neu.", "Телефонро аз нав фурӯзон кунед.", "Бигӯ: ҳоло кор мекунад, ташаккур!",
              "Jetzt geht es, danke!", "Ҳоло кор мекунад, ташаккур!", ["Danke, jetzt geht es."]),
        ]),
        ("Миссия: SIM-корти нав", [
            t("Hallo! Kann ich helfen?", "Салом! Ёрӣ диҳам?", "Бигӯ: ба ман SIM-корт лозим",
              "Ich brauche eine SIM-Karte.", "Ба ман SIM-корт лозим.", ["Eine SIM-Karte, bitte."]),
            t("Mit Vertrag oder ohne?", "Бо шартнома ё бе?", "Бигӯ: бе шартнома", "Ohne Vertrag.", "Бе шартнома.",
              ["Ohne, bitte."]),
            t("Zehn Euro, zwanzig Gigabyte.", "Даҳ евро, бист гигабайт.", "Бигӯ: хуб, инро мегирам",
              "Gut, das nehme ich.", "Хуб, инро мегирам.", ["Okay, ich nehme das."]),
            t("Ihren Pass, bitte.", "Шиносномаатон, лутфан.", "Бигӯ: мана", "Hier, bitte.", "Мана, марҳамат.",
              ["Bitte schön."]),
        ]),
    ]))

# ═════════════════════ 11. Пул ва фиристодан ба хона ═════════════════════
made.append(pack("money_de_tg", "Geld schicken", "Пул ва фиристодан ба хона", "💱", 11, L,
    "Шумо ба оила пул мефиристед: ба нуқтаи интиқоли пул меравед, мегӯед чанд пул ва ба кӣ, "
    "қурбро мепурсед ва рамзи интиқолро мегиред.",
    [
        ("Пул", [
            w("Geld", "пул", None),
            w("Schicken", "фиристодан", None),
            w("Empfänger", "гиранда", None),
            w("Gebühr", "ҳаққи хизмат", None),
            w("Kurs", "қурб", None),
            w("Code", "рамз", None),
        ]),
        ("Пул мефиристам", [
            t("Hallo! Was möchten Sie?", "Салом! Чӣ мехоҳед?", "Бигӯ: пул фиристодан мехоҳам",
              "Ich möchte Geld schicken.", "Пул фиристодан мехоҳам.", ["Geld schicken, bitte."]),
            t("Wohin?", "Ба куҷо?", "Бигӯ: ба Тоҷикистон", "Nach Tadschikistan.", "Ба Тоҷикистон.",
              ["Tadschikistan."]),
            t("Wie viel?", "Чанд?", "Бигӯ: дусад евро", "Zweihundert Euro.", "Дусад евро.", ["Zweihundert."]),
        ]),
        ("Ибораҳо", [
            s("Zweihundert Euro", "Дусад евро", None),
            s("Die Gebühr?", "Ҳаққи хизмат?", None),
            s("Der Kurs?", "Қурб?", None),
            s("Meine Mutter", "Модарам", None),
            s("Ihr Name?", "Номи ӯ?", None),
            s("Der Code", "Рамз", None),
        ]),
        ("Ҳаққи хизмат", [
            t("Zweihundert Euro nach Tadschikistan.", "Дусад евро ба Тоҷикистон.", "Бипурс: ҳаққи хизмат чанд?",
              "Wie hoch ist die Gebühr?", "Ҳаққи хизмат чанд?", ["Was kostet das?"]),
            t("Fünf Euro.", "Панҷ евро.", "Бипурс: қурб чанд?", "Wie ist der Kurs?", "Қурб чанд?",
              ["Und der Kurs?"]),
            t("Der Kurs ist gut heute.", "Имрӯз қурб хуб аст.", "Бигӯ: хуб", "Gut.", "Хуб.", ["Okay, danke."]),
        ]),
        ("Маълумоти гиранда", [
            s("Das ist für Mama.", "Ин барои модарам.", None),
            s("Ihr Name ist Zarina.", "Номи ӯ Зарина.", None),
            s("Sie wohnt in Duschanbe.", "Ӯ дар Душанбе зиндагӣ мекунад.", None),
            s("Wann kommt das Geld?", "Пул кай мерасад?", None),
            s("Hier ist mein Pass.", "Мана шиносномаам.", None),
            s("Bitte den Code.", "Рамз, лутфан.", None),
        ]),
        ("Ба кӣ?", [
            t("Wer ist der Empfänger?", "Гиранда кист?", "Бигӯ: модарам", "Meine Mutter.", "Модарам.",
              ["Das Geld ist für meine Mutter."]),
            t("Wie heißt sie?", "Номаш чист?", "Бигӯ: Зарина Каримова", "Zarina Karimova.", "Зарина Каримова.",
              ["Ihr Name ist Zarina Karimova."]),
            t("In welcher Stadt?", "Дар кадом шаҳр?", "Бигӯ: Душанбе", "Duschanbe.", "Душанбе.",
              ["In Duschanbe."]),
        ]),
        ("Рамз ва вақт", [
            s("Wann kommt es an?", "Кай мерасад?", None),
            s("In zehn Minuten.", "Баъди даҳ дақиқа.", None),
            s("Hier ist der Code.", "Мана рамз.", None),
            s("Ich schicke den Code.", "Рамзро мефиристам.", None),
            s("Ist das sicher?", "Ин бехатар аст?", None),
            s("Bis nächsten Monat!", "То моҳи оянда!", None),
        ]),
        ("Рамз", [
            t("Fertig. Hier ist der Code.", "Тайёр. Мана рамз.", "Бипурс: пул кай мерасад?", "Wann kommt das Geld?",
              "Пул кай мерасад?", ["Wann kommt es an?"]),
            t("In zehn Minuten.", "Баъди даҳ дақиқа.", "Бипурс: ин бехатар аст?", "Ist das sicher?", "Ин бехатар аст?",
              ["Sicher?"]),
            t("Ja, sehr sicher.", "Ҳа, хеле бехатар.", "Ташаккур гӯй", "Vielen Dank!", "Ташаккури зиёд!", ["Danke!"]),
        ]),
        ("Миссия: пул ба модар", [
            t("Hallo! Was möchten Sie?", "Салом! Чӣ мехоҳед?", "Бигӯ: пул ба Тоҷикистон фиристодан мехоҳам",
              "Ich möchte Geld nach Tadschikistan schicken.", "Ба Тоҷикистон пул фиристодан мехоҳам.",
              ["Geld schicken, bitte."]),
            t("Wie viel?", "Чанд?", "Бигӯ: дусад евро", "Zweihundert Euro.", "Дусад евро.", ["Zweihundert."]),
            t("Für wen?", "Барои кӣ?", "Бигӯ: барои модарам", "Für meine Mutter.", "Барои модарам.",
              ["Meine Mutter."]),
            t("Gut. Hier ist der Code.", "Хуб. Мана рамз.", "Бипурс: пул кай мерасад?", "Wann kommt das Geld?",
              "Пул кай мерасад?", ["Wann kommt es an?"]),
        ]),
    ]))

# ═════════════════════ 12. Дар дорухона ═════════════════════
made.append(pack("pharmacy_de_tg", "In der Apotheke", "Дар дорухона", "💊", 12, L,
    "Шумо бемор ҳастед ва ба дорухона (Apotheke) меравед: мегӯед, ки чӣ дард мекунад, дору "
    "мепурсед ва мефаҳмед, ки онро чӣ тавр бояд хӯрд.",
    [
        ("Дорухона", [
            w("Apotheke", "дорухона", None),
            w("Tabletten", "ҳаб (таблетка)", None),
            w("Kopfschmerzen", "дарди сар", None),
            w("Fieber", "табларза", None),
            w("Husten", "сулфа", None),
            w("Rezept", "рецепт (дастури духтур)", None),
        ]),
        ("Чӣ дард мекунад?", [
            t("Hallo! Was fehlt Ihnen?", "Салом! Чӣ шудааст?", "Бигӯ: дарди сар дорам", "Ich habe Kopfschmerzen.",
              "Дарди сар дорам.", ["Kopfschmerzen."]),
            t("Haben Sie Fieber?", "Табларза доред?", "Бигӯ: не", "Nein.", "Не.", ["Nein, kein Fieber."]),
            t("Diese Tabletten sind gut.", "Ин ҳабҳо хубанд.", "Бипурс: чанд пул?", "Was kosten sie?", "Чанд пул?",
              ["Wie viel kosten die?"]),
        ]),
        ("Ибораҳо", [
            s("Gegen Husten", "Барои сулфа", None),
            s("Ohne Rezept?", "Бе рецепт?", None),
            s("Wie oft?", "Чанд бор?", None),
            s("Nach Essen", "Баъди хӯрок", None),
            s("Dreimal täglich", "Се бор дар рӯз", None),
            s("Gute Besserung!", "Шифо ёбед!", None),
        ]),
        ("Бе рецепт?", [
            t("Ich habe Husten.", "Ман сулфа дорам.", "Бипурс: бе рецепт мешавад?", "Geht das ohne Rezept?",
              "Бе рецепт мешавад?", ["Ohne Rezept?"]),
            t("Ja, das geht.", "Ҳа, мешавад.", "Бипурс: чанд бор?", "Wie oft?", "Чанд бор?",
              ["Wie oft nehme ich das?"]),
            t("Dreimal täglich.", "Се бор дар рӯз.", "Бигӯ: хуб, ташаккур", "Gut, danke.", "Хуб, ташаккур.",
              ["Okay, danke."]),
        ]),
        ("Ман бемор ҳастам", [
            s("Ich bin krank.", "Ман бемор ҳастам.", None),
            s("Mein Hals tut weh.", "Гулӯям дард мекунад.", None),
            s("Ich habe Fieber.", "Ман табларза дорам.", None),
            s("Etwas gegen Husten?", "Чизе барои сулфа?", None),
            s("Hier ist mein Rezept.", "Мана рецептам.", None),
            s("Für mein Kind.", "Барои фарзандам.", None),
        ]),
        ("Дору барои кӯдак", [
            t("Ja, bitte?", "Ҳа, лутфан?", "Бигӯ: фарзандам табларза дорад", "Mein Kind hat Fieber.",
              "Фарзандам табларза дорад.", ["Für mein Kind, Fieber."]),
            t("Wie alt ist das Kind?", "Кӯдак чандсола аст?", "Бигӯ: панҷсола", "Fünf Jahre.", "Панҷсола.",
              ["Es ist fünf."]),
            t("Dieser Saft ist gut.", "Ин шарбат хуб аст.", "Бипурс: чанд бор?", "Wie oft?", "Чанд бор?",
              ["Wie viel?"]),
        ]),
        ("Чӣ тавр хӯрдан?", [
            s("Wie nehme ich das?", "Инро чӣ тавр хӯрам?", None),
            s("Mit Wasser.", "Бо об.", None),
            s("Vor dem Essen?", "Пеш аз хӯрок?", None),
            s("Nicht mit Alkohol.", "Бо майзадагӣ не.", None),
            s("Drei Tage lang.", "Се рӯз.", None),
            s("Ich verstehe, danke.", "Фаҳмидам, ташаккур.", None),
        ]),
        ("Дастур", [
            t("Hier sind die Tabletten.", "Мана ҳабҳо.", "Бипурс: инро чӣ тавр хӯрам?", "Wie nehme ich das?",
              "Инро чӣ тавр хӯрам?", ["Wie oft?"]),
            t("Eine Tablette nach dem Essen.", "Як ҳаб баъди хӯрок.", "Бипурс: чанд рӯз?", "Wie lange?", "Чанд рӯз?",
              ["Wie viele Tage?"]),
            t("Drei Tage. Gute Besserung!", "Се рӯз. Шифо ёбед!", "Бигӯ: фаҳмидам, ташаккур", "Ich verstehe, danke.",
              "Фаҳмидам, ташаккур.", ["Danke schön!"]),
        ]),
        ("Миссия: шаби бемор", [
            t("Guten Abend! Was fehlt Ihnen?", "Шом ба хайр! Чӣ шудааст?", "Бигӯ: гулӯям дард мекунад",
              "Mein Hals tut weh.", "Гулӯям дард мекунад.", ["Halsschmerzen."]),
            t("Haben Sie Fieber?", "Табларза доред?", "Бигӯ: ҳа, каме", "Ja, ein bisschen.", "Ҳа, каме.",
              ["Ja.", "Ein bisschen Fieber."]),
            t("Nehmen Sie diese Tabletten.", "Ин ҳабҳоро гиред.", "Бипурс: чанд бор?", "Wie oft?", "Чанд бор?",
              ["Wie oft nehme ich das?"]),
            t("Dreimal täglich. Gute Besserung!", "Се бор дар рӯз. Шифо ёбед!", "Ташаккур гӯй", "Vielen Dank!",
              "Ташаккури зиёд!", ["Danke schön!"]),
        ]),
    ]))

# ═════════════════════ 13. Дар почта ═════════════════════
made.append(pack("post_de_tg", "Bei der Post", "Дар почта", "📮", 13, L,
    "Шумо ба почта меравед: баста ба Тоҷикистон мефиристед, мепурсед, ки чанд пул ва чанд рӯз, "
    "марка мехаред ва бастаи худро мегиред.",
    [
        ("Почта", [
            w("Post", "почта", None),
            w("Paket", "баста", None),
            w("Brief", "мактуб", None),
            w("Briefmarke", "марка", None),
            w("Schicken", "фиристодан", None),
            w("Abholen", "гирифтан (омада)", None),
        ]),
        ("Баста мефиристам", [
            t("Hallo! Was möchten Sie?", "Салом! Чӣ мехоҳед?", "Бигӯ: ин бастаро фиристодан мехоҳам",
              "Ich möchte das Paket schicken.", "Ин бастаро фиристодан мехоҳам.", ["Ein Paket schicken, bitte."]),
            t("Wohin?", "Ба куҷо?", "Бигӯ: ба Тоҷикистон", "Nach Tadschikistan.", "Ба Тоҷикистон.",
              ["Tadschikistan."]),
            t("Das kostet dreißig Euro.", "Сӣ евро мешавад.", "Бигӯ: хуб", "Okay.", "Хуб.", ["Gut, danke."]),
        ]),
        ("Ибораҳо", [
            s("Ein Paket", "Як баста", None),
            s("Eine Briefmarke", "Як марка", None),
            s("Wie lange?", "Чӣ қадар?", None),
            s("Zwei Wochen", "Ду ҳафта", None),
            s("Mein Paket", "Бастаи ман", None),
            s("Hier unterschreiben", "Ин ҷо имзо кунед", None),
        ]),
        ("Чанд рӯз?", [
            t("Fertig. Noch Fragen?", "Тайёр. Боз савол?", "Бипурс: чӣ қадар вақт мегирад?", "Wie lange dauert das?",
              "Чӣ қадар вақт мегирад?", ["Wie lange?"]),
            t("Zwei Wochen.", "Ду ҳафта.", "Бигӯ: хуб, ташаккур", "Gut, danke.", "Хуб, ташаккур.", ["Okay."]),
            t("Hier unterschreiben, bitte.", "Ин ҷо имзо кунед, лутфан.", "Бигӯ: хуб", "Okay.", "Хуб.", ["Hier?"]),
        ]),
        ("Дар почта", [
            s("Was kostet ein Brief?", "Мактуб чанд пул?", None),
            s("Eine Briefmarke, bitte.", "Як марка, лутфан.", None),
            s("Ich hole ein Paket.", "Бастаеро мегирам.", None),
            s("Hier ist der Zettel.", "Мана коғаз.", None),
            s("Was ist im Paket?", "Дар баста чӣ ҳаст?", None),
            s("Kleidung und Geschenke.", "Либос ва тӯҳфаҳо.", None),
        ]),
        ("Дар баста чӣ?", [
            t("Was ist im Paket?", "Дар баста чӣ ҳаст?", "Бигӯ: либос ва тӯҳфаҳо", "Kleidung und Geschenke.",
              "Либос ва тӯҳфаҳо.", ["Kleidung."]),
            t("Ist das schwer?", "Вазнин аст?", "Бигӯ: панҷ кило", "Fünf Kilo.", "Панҷ кило.", ["Ungefähr fünf Kilo."]),
            t("Gut. Noch etwas?", "Хуб. Боз чизе?", "Бигӯ: як марка, лутфан", "Eine Briefmarke, bitte.",
              "Як марка, лутфан.", ["Nein, danke."]),
        ]),
        ("Баста гирифтан", [
            s("Ich war nicht da.", "Ман набудам.", None),
            s("Hier ist mein Ausweis.", "Мана ҳуҷҷатам.", None),
            s("Das ist für mich.", "Ин барои ман.", None),
            s("Wo ist mein Paket?", "Бастаи ман куҷост?", None),
            s("Einen Moment, bitte.", "Як лаҳза, лутфан.", None),
            s("Danke, schönen Tag!", "Ташаккур, рӯзи хуш!", None),
        ]),
        ("Коғази почта", [
            t("Ja, bitte?", "Ҳа, лутфан?", "Бигӯ: бастаеро мегирам", "Ich hole ein Paket.", "Бастаеро мегирам.",
              ["Ich möchte ein Paket abholen."]),
            t("Haben Sie den Zettel?", "Коғаз доред?", "Бигӯ: ҳа, мана коғаз", "Ja, hier ist der Zettel.",
              "Ҳа, мана коғаз.", ["Ja, hier."]),
            t("Und Ihren Ausweis?", "Ва ҳуҷҷататон?", "Бигӯ: мана ҳуҷҷатам", "Hier ist mein Ausweis.",
              "Мана ҳуҷҷатам.", ["Hier, bitte."]),
        ]),
        ("Миссия: тӯҳфа ба хона", [
            t("Hallo! Was möchten Sie?", "Салом! Чӣ мехоҳед?", "Бигӯ: ин бастаро ба Тоҷикистон",
              "Das Paket nach Tadschikistan.", "Ин баста ба Тоҷикистон.", ["Ein Paket nach Tadschikistan, bitte."]),
            t("Was ist drin?", "Дарунаш чӣ?", "Бигӯ: либос ва тӯҳфаҳо", "Kleidung und Geschenke.",
              "Либос ва тӯҳфаҳо.", ["Kleidung."]),
            t("Dreißig Euro, bitte.", "Сӣ евро, лутфан.", "Бипурс: чӣ қадар вақт мегирад?", "Wie lange dauert das?",
              "Чӣ қадар вақт мегирад?", ["Wie lange?"]),
            t("Zwei Wochen.", "Ду ҳафта.", "Бигӯ: хуб, ташаккур", "Gut, danke.", "Хуб, ташаккур.", ["Danke schön!"]),
        ]),
    ]))

# ═════════════════════ 15. Ҳамсояҳо ═════════════════════
made.append(pack("neighbors_de_tg", "Die Nachbarn", "Ҳамсояҳо", "🏠", 15, L,
    "Шумо бо ҳамсояҳо шинос мешавед: салом медиҳед, худро муаррифӣ мекунед, барои садо бубахшед "
    "мегӯед, ёрӣ мепурсед ва ба меҳмонӣ даъват мекунед.",
    [
        ("Ҳамсоя", [
            w("Nachbar", "ҳамсоя", "Зан: «Nachbarin»."),
            w("Wohnung", "хона (квартира)", None),
            w("Laut", "баланд, пурсадо", None),
            w("Leise", "оҳиста, ором", None),
            w("Treppe", "зинапоя", None),
            w("Einladen", "даъват кардан", None),
        ]),
        ("Ҳамсояи нав", [
            t("Hallo! Sind Sie neu hier?", "Салом! Шумо ин ҷо навед?", "Бигӯ: ҳа, ман нав ҳастам", "Ja, ich bin neu.",
              "Ҳа, ман нав ҳастам.", ["Ja.", "Ja, ich wohne jetzt hier."]),
            t("Ich bin Frau Becker.", "Ман хонум Беккер.", "Бигӯ: шодам", "Freut mich.", "Шодам.",
              ["Freut mich sehr."]),
            t("Welche Wohnung?", "Кадом хона?", "Бигӯ: ошёнаи дуюм", "Zweiter Stock.", "Ошёнаи дуюм.",
              ["Im zweiten Stock."]),
        ]),
        ("Ибораҳо", [
            s("Wohne hier", "Ин ҷо зиндагӣ мекунам", "Кӯтоҳ аз «Ich wohne hier»."),
            s("Zweiter Stock", "Ошёнаи дуюм", None),
            s("Zu laut", "Хеле баланд", None),
            s("Kein Problem", "Мушкил нест", None),
            s("Kommen Sie!", "Биёед!", None),
            w("Gern", "бо хурсандӣ", None),
        ]),
        ("Садо", [
            t("Entschuldigung, es ist zu laut.", "Бубахшед, хеле баланд аст.", "Бигӯ: бубахшед", "Entschuldigung!",
              "Бубахшед!", ["Oh, das tut mir leid."]),
            t("Mein Baby schläft.", "Кӯдакам хоб аст.", "Бигӯ: мо ором мешавем", "Wir sind leise.", "Мо ором мешавем.",
              ["Okay, wir sind jetzt leise."]),
            t("Danke!", "Ташаккур!", "Бигӯ: мушкил нест", "Kein Problem.", "Мушкил нест.", ["Gerne."]),
        ]),
        ("Бо ҳамсоя", [
            s("Ich bin Ihr Nachbar.", "Ман ҳамсояи шумо ҳастам.", None),
            s("Haben Sie ein Werkzeug?", "Асбоб доред?", None),
            s("Ich brauche Hilfe.", "Ба ман ёрӣ лозим.", None),
            s("Ich habe Ihr Paket.", "Бастаи шуморо дорам.", None),
            s("Kommen Sie zum Tee!", "Ба чой биёед!", None),
            s("Das ist sehr nett.", "Ин хеле хуб аст.", None),
        ]),
        ("Бастаи ҳамсоя", [
            t("Hallo! Ja, bitte?", "Салом! Ҳа, лутфан?", "Бигӯ: бастаатон назди ман аст", "Ihr Paket ist bei mir.",
              "Бастаатон назди ман аст.", ["Ich habe Ihr Paket."]),
            t("Oh, danke! Das ist nett.", "О, ташаккур! Хеле хуб.", "Бигӯ: мушкил нест", "Kein Problem.", "Мушкил нест.",
              ["Gerne."]),
            t("Möchten Sie einen Tee?", "Чой мехоҳед?", "Бигӯ: бо хурсандӣ", "Gerne!", "Бо хурсандӣ!",
              ["Ja, gerne!", "Danke, gerne."]),
        ]),
        ("Даъват", [
            s("Wir haben ein Fest.", "Мо ҷашн дорем.", None),
            s("Am Samstag um sechs.", "Шанбе соати шаш.", None),
            s("Kommen Sie zum Essen!", "Ба хӯрок биёед!", None),
            s("Ich koche Plov.", "Ман палав мепазам.", None),
            s("Bringen Sie nichts mit.", "Чизе наоред.", None),
            s("Wir freuen uns!", "Мо шод мешавем!", None),
        ]),
        ("Ба палав биёед!", [
            t("Hallo! Wie geht's?", "Салом! Чӣ хел?", "Бигӯ: шанбе ҷашн дорем", "Am Samstag haben wir ein Fest.",
              "Шанбе ҷашн дорем.", ["Wir haben ein Fest."]),
            t("Oh, schön!", "О, хуб!", "Бигӯ: ба хӯрок биёед!", "Kommen Sie zum Essen!", "Ба хӯрок биёед!",
              ["Kommen Sie!"]),
            t("Gerne! Um wie viel Uhr?", "Бо хурсандӣ! Соати чанд?", "Бигӯ: соати шаш", "Um sechs Uhr.", "Соати шаш.",
              ["Um sechs."]),
        ]),
        ("Миссия: шиносоӣ бо ҳамсоя", [
            t("Hallo! Sind Sie neu?", "Салом! Навед?", "Бигӯ: ҳа, ман ҳамсояи шумо ҳастам", "Ja, ich bin Ihr Nachbar.",
              "Ҳа, ман ҳамсояи шумо ҳастам.", ["Ja, ich bin neu."]),
            t("Ich bin Frau Becker. Freut mich!", "Ман хонум Беккер. Шодам!", "Бигӯ: ман ҳам шодам", "Freut mich auch.",
              "Ман ҳам шодам.", ["Mich auch."]),
            t("Brauchen Sie Hilfe?", "Ёрӣ лозим?", "Бигӯ: не, ташаккур", "Nein, danke.", "Не, ташаккур.",
              ["Jetzt nicht, danke."]),
            t("Gut. Schönen Tag!", "Хуб. Рӯзи хуш!", "Бигӯ: ба шумо ҳам", "Ihnen auch!", "Ба шумо ҳам!",
              ["Danke, Ihnen auch!"]),
        ]),
    ]))

# ═════════════════════ 17. Гум шудам ═════════════════════
made.append(pack("lost_de_tg", "Ich habe mich verlaufen", "Гум шудам", "🧭", 17, L,
    "Шумо дар шаҳр гум шудед: аз роҳгузар роҳ мепурсед, суроғаро нишон медиҳед, мефаҳмед, ки "
    "дур аст ё наздик, ва ташаккур мегӯед.",
    [
        ("Шаҳр", [
            w("Weg", "роҳ", None),
            w("Weit", "дур", None),
            w("Nah", "наздик", None),
            w("Ecke", "кунҷ", None),
            w("Platz", "майдон", None),
            w("Karte", "харита", None),
        ]),
        ("Роҳ мепурсам", [
            t("Ja, bitte?", "Ҳа, лутфан?", "Бигӯ: бубахшед, вокзал куҷост?", "Entschuldigung, wo ist der Bahnhof?",
              "Бубахшед, вокзал куҷост?", ["Wo ist der Bahnhof?"]),
            t("Geradeaus und dann links.", "Рост ва баъд ба чап.", "Бипурс: дур аст?", "Ist es weit?", "Дур аст?",
              ["Weit?"]),
            t("Nein, fünf Minuten.", "Не, панҷ дақиқа.", "Ташаккур гӯй", "Danke!", "Ташаккур!", ["Vielen Dank!"]),
        ]),
        ("Ибораҳо", [
            s("Ganz nah", "Хеле наздик", None),
            s("Zu Fuß", "Пиёда", None),
            s("Gleich dort", "Ҳамон ҷо", None),
            s("Diese Adresse", "Ин суроға", None),
            s("Noch einmal?", "Боз як бор?", None),
            s("Welche Richtung?", "Кадом тараф?", None),
        ]),
        ("Пиёда?", [
            t("Kann ich helfen?", "Ёрӣ диҳам?", "Бигӯ: ҳа, ман гум шудам", "Ja, ich bin verloren.", "Ҳа, ман гум шудам.",
              ["Ja, bitte."]),
            t("Wohin möchten Sie?", "Ба куҷо мехоҳед?", "Бигӯ: ба ин суроға", "Zu dieser Adresse.", "Ба ин суроға.",
              ["Hier, diese Adresse."]),
            t("Ah, um die Ecke!", "А, аз кунҷ гузашта!", "Бипурс: пиёда?", "Zu Fuß?", "Пиёда?",
              ["Kann ich zu Fuß gehen?"]),
        ]),
        ("Саволҳо", [
            s("Wo bin ich hier?", "Ман ин ҷо куҷоям?", None),
            s("Ich suche diese Straße.", "Ман ин кӯчаро меҷӯям.", None),
            s("Wie komme ich dorthin?", "Чӣ тавр он ҷо равам?", None),
            s("Bitte zeigen Sie mir.", "Лутфан нишон диҳед.", None),
            s("Gibt es einen Bus?", "Автобус ҳаст?", None),
            s("Ich verstehe nicht ganz.", "Пурра намефаҳмам.", None),
        ]),
        ("Харита", [
            t("Ja, bitte?", "Ҳа, лутфан?", "Бигӯ: ман ин кӯчаро меҷӯям", "Ich suche diese Straße.",
              "Ман ин кӯчаро меҷӯям.", ["Wo ist diese Straße?"]),
            t("Hmm, das ist weit.", "Ҳм, ин дур аст.", "Бипурс: автобус ҳаст?", "Gibt es einen Bus?", "Автобус ҳаст?",
              ["Fährt ein Bus?"]),
            t("Ja, der Bus zehn.", "Ҳа, автобуси даҳ.", "Бигӯ: лутфан дар харита нишон диҳед", "Bitte zeigen Sie mir.",
              "Лутфан нишон диҳед.", ["Auf der Karte, bitte."]),
        ]),
        ("Ташаккур", [
            s("Jetzt verstehe ich.", "Ҳоло мефаҳмам.", None),
            s("Sie sind sehr nett.", "Шумо хеле меҳрубонед.", None),
            s("Danke für die Hilfe.", "Барои ёрӣ ташаккур.", None),
            s("Schönen Tag noch!", "Рӯзи хуш!", None),
            s("Ich finde es.", "Ёфта метавонам.", None),
            s("Alles klar!", "Ҳама фаҳмо!", None),
        ]),
        ("Ҳоло фаҳмидам", [
            t("Hier links, dann geradeaus.", "Ин ҷо ба чап, баъд рост.", "Бигӯ: ҳоло мефаҳмам", "Jetzt verstehe ich.",
              "Ҳоло мефаҳмам.", ["Alles klar!"]),
            t("Und dann sehen Sie es.", "Ва баъд онро мебинед.", "Бигӯ: барои ёрӣ ташаккур", "Danke für die Hilfe.",
              "Барои ёрӣ ташаккур.", ["Vielen Dank!"]),
            t("Gern geschehen!", "Арзише надорад!", "Бигӯ: рӯзи хуш!", "Schönen Tag noch!", "Рӯзи хуш!",
              ["Tschüss!"]),
        ]),
        ("Миссия: шаҳри нав", [
            t("Kann ich helfen?", "Ёрӣ диҳам?", "Бигӯ: ҳа, ман гум шудам", "Ja, ich bin verloren.", "Ҳа, ман гум шудам.",
              ["Ja, bitte."]),
            t("Wohin möchten Sie?", "Ба куҷо мехоҳед?", "Бигӯ: ба вокзал", "Zum Bahnhof.", "Ба вокзал.",
              ["Ich suche den Bahnhof."]),
            t("Geradeaus und um die Ecke.", "Рост ва аз кунҷ гузашта.", "Бипурс: дур аст?", "Ist es weit?", "Дур аст?",
              ["Weit?"]),
            t("Nein, ganz nah.", "Не, хеле наздик.", "Бигӯ: барои ёрӣ ташаккур", "Danke für die Hilfe.",
              "Барои ёрӣ ташаккур.", ["Vielen Dank!"]),
        ]),
    ]))

# ═════════════════════ 18. Вақти холӣ ═════════════════════
made.append(pack("free_time_de_tg", "Am Wochenende", "Вақти холӣ", "🎉", 18, L,
    "Охири ҳафта: бо дӯстон нақша мекашед — ба боғ, футбол ё кино меравед, мепурсед, ки кай ва "
    "дар куҷо вомехӯред, ва дар бораи шавқҳоятон гап мезанед.",
    [
        ("Истироҳат", [
            w("Wochenende", "охири ҳафта", None),
            w("Park", "боғ", None),
            w("Fußball", "футбол", None),
            w("Kino", "кино", None),
            w("Spazieren", "сайр кардан", None),
            w("Treffen", "вохӯрдан", None),
        ]),
        ("Нақша", [
            t("Was machst du am Wochenende?", "Охири ҳафта чӣ мекунӣ?", "Бигӯ: ҳеҷ чиз", "Nichts.", "Ҳеҷ чиз.",
              ["Ich weiß nicht.", "Noch nichts."]),
            t("Spielen wir Fußball?", "Футбол бозӣ кунем?", "Бигӯ: бо хурсандӣ!", "Gerne!", "Бо хурсандӣ!",
              ["Ja, gerne!", "Gute Idee!"]),
            t("Am Samstag?", "Шанбе?", "Бигӯ: ҳа, шанбе хуб", "Ja, Samstag ist gut.", "Ҳа, шанбе хуб.",
              ["Ja, Samstag."]),
        ]),
        ("Ибораҳо", [
            s("Am Samstag", "Шанбе", None),
            s("Im Park", "Дар боғ", None),
            s("Gute Idee!", "Фикри хуб!", None),
            s("Um drei", "Соати се", None),
            s("Ich komme", "Меоям", None),
            s("Leider nicht", "Мутаассифона, не", None),
        ]),
        ("Кай ва куҷо?", [
            t("Wann treffen wir uns?", "Кай вомехӯрем?", "Бигӯ: соати се", "Um drei.", "Соати се.",
              ["Um drei Uhr."]),
            t("Und wo?", "Ва куҷо?", "Бигӯ: дар боғ", "Im Park.", "Дар боғ.", ["Im Park, beim Eingang."]),
            t("Super, bis Samstag!", "Олӣ, то шанбе!", "Бигӯ: то шанбе", "Bis Samstag!", "То шанбе!", ["Tschüss!"]),
        ]),
        ("Шавқҳои ман", [
            s("Ich spiele gern Fußball.", "Футболро дӯст медорам.", None),
            s("Ich gehe gern spazieren.", "Сайрро дӯст медорам.", None),
            s("Ich koche gern.", "Пухтанро дӯст медорам.", None),
            own("Am Wochenende ___ ich.", "Охири ҳафта ман ___.", "Кори дӯстдоштаатонро гӯед: «schlafe», «koche»…",
                "Was machst du am Wochenende?", "Охири ҳафта чӣ мекунӣ?", "Кори дӯстдоштаатонро гӯед"),
            s("Hast du Zeit?", "Вақт дорӣ?", None),
            s("Kommst du mit?", "Бо мо меоӣ?", None),
        ]),
        ("Кино?", [
            t("Gehen wir ins Kino?", "Ба кино равем?", "Бигӯ: мутаассифона, не", "Leider nicht.", "Мутаассифона, не.",
              ["Heute nicht."]),
            t("Warum?", "Чаро?", "Бигӯ: ман кор мекунам", "Ich arbeite.", "Ман кор мекунам.", ["Ich muss arbeiten."]),
            t("Schade! Und Sonntag?", "Афсӯс! Ва якшанбе?", "Бигӯ: якшанбе вақт дорам", "Sonntag habe ich Zeit.",
              "Якшанбе вақт дорам.", ["Sonntag geht.", "Ja, Sonntag!"]),
        ]),
        ("Баъди истироҳат", [
            s("Wie war das Wochenende?", "Охири ҳафта чӣ хел гузашт?", None),
            s("Es war sehr schön.", "Хеле хуб буд.", None),
            s("Ich war im Park.", "Ман дар боғ будам.", None),
            s("Wir haben gekocht.", "Мо хӯрок пухтем.", None),
            s("Ich war müde.", "Ман хаста будам.", None),
            s("Und du?", "Ва ту?", None),
        ]),
        ("Душанбе", [
            t("Hallo! Wie war das Wochenende?", "Салом! Охири ҳафта чӣ хел?", "Бигӯ: хеле хуб буд",
              "Es war sehr schön.", "Хеле хуб буд.", ["Sehr schön!", "Gut, danke."]),
            t("Was hast du gemacht?", "Чӣ кор кардӣ?", "Бигӯ: дар боғ будам", "Ich war im Park.", "Дар боғ будам.",
              ["Fußball im Park."]),
            t("Toll!", "Олӣ!", "Бипурс: ва ту?", "Und du?", "Ва ту?", ["Und dein Wochenende?"]),
        ]),
        ("Миссия: шанбеи футбол", [
            t("Hallo! Hast du am Samstag Zeit?", "Салом! Шанбе вақт дорӣ?", "Бигӯ: ҳа, вақт дорам", "Ja, ich habe Zeit.",
              "Ҳа, вақт дорам.", ["Ja!"]),
            t("Spielen wir Fußball?", "Футбол бозӣ кунем?", "Бигӯ: фикри хуб!", "Gute Idee!", "Фикри хуб!",
              ["Ja, gerne!"]),
            t("Um drei im Park?", "Соати се дар боғ?", "Бигӯ: хуб, меоям", "Gut, ich komme.", "Хуб, меоям.",
              ["Okay!", "Ja, ich komme."]),
            t("Super! Bis Samstag!", "Олӣ! То шанбе!", "Бигӯ: то шанбе", "Bis Samstag!", "То шанбе!", ["Tschüss!"]),
        ]),
    ]))

# ═════════════════════ 19. Занги фаврӣ (112) ═════════════════════
made.append(pack("emergency_de_tg", "Notruf hundertzwölf", "Занги фаврӣ", "🚨", 19, L,
    "Ҳолати фаврӣ: касе бемор шуд ё сӯхтор аст. Шумо ба 112 занг мезанед, ором мегӯед, ки чӣ "
    "шуд ва куҷо, ва саволҳои оддиро ҷавоб медиҳед.",
    [
        ("Фаврӣ", [
            w("Notruf", "занги фаврӣ", "Дар Олмон: 112."),
            w("Krankenwagen", "мошини ёрии таъҷилӣ", None),
            w("Feuer", "сӯхтор", None),
            w("Hilfe", "ёрӣ", None),
            w("Schnell", "тез", None),
            w("Adresse", "суроға", None),
        ]),
        ("112", [
            t("Notruf. Was ist passiert?", "Занги фаврӣ. Чӣ шуд?", "Бигӯ: мард бемор аст", "Ein Mann ist krank.",
              "Мард бемор аст.", ["Ein Mann ist umgefallen."]),
            t("Wo sind Sie?", "Куҷоед?", "Бигӯ: дар кӯчаи Гартен, даҳ", "Gartenstraße zehn.", "Кӯчаи Гартен, даҳ.",
              ["In der Gartenstraße zehn."]),
            t("Der Krankenwagen kommt.", "Ёрии таъҷилӣ меояд.", "Бигӯ: тез, лутфан!", "Bitte schnell!", "Тез, лутфан!",
              ["Danke, schnell bitte!"]),
        ]),
        ("Ибораҳо", [
            s("Hilfe, bitte!", "Ёрӣ, лутфан!", None),
            s("Schnell, bitte!", "Тез, лутфан!", None),
            s("Ein Unfall", "Садама", None),
            s("Es brennt!", "Сӯхтор!", None),
            s("Er atmet", "Ӯ нафас мегирад", None),
            s("Meine Adresse", "Суроғаи ман", None),
        ]),
        ("Ӯ нафас мегирад?", [
            t("Atmet er?", "Ӯ нафас мегирад?", "Бигӯ: ҳа, нафас мегирад", "Ja, er atmet.", "Ҳа, нафас мегирад.",
              ["Ja."]),
            t("Ist er wach?", "Ҳушёр аст?", "Бигӯ: не", "Nein.", "Не.", ["Nein, er ist nicht wach."]),
            t("Bleiben Sie bei ihm.", "Назди ӯ монед.", "Бигӯ: хуб", "Okay.", "Хуб.", ["Ja, ich bleibe."]),
        ]),
        ("Ман хабар медиҳам", [
            s("Es gibt einen Unfall.", "Садама шуд.", None),
            s("Ein Kind ist verletzt.", "Кӯдак захмӣ шуд.", None),
            s("Die Küche brennt.", "Ошхона месӯзад.", None),
            s("Bitte kommen Sie schnell.", "Лутфан тез биёед.", None),
            s("Ich spreche wenig Deutsch.", "Ман каме олмонӣ медонам.", None),
            s("Ich warte draußen.", "Берун интизорам.", None),
        ]),
        ("Сӯхтор", [
            t("Notruf. Was ist los?", "Занги фаврӣ. Чӣ гап?", "Бигӯ: дар ошхона сӯхтор аст", "In der Küche brennt es.",
              "Дар ошхона сӯхтор аст.", ["Es brennt!", "Feuer!"]),
            t("Ist jemand im Haus?", "Касе дар хона ҳаст?", "Бигӯ: не, ҳама берун", "Nein, alle sind draußen.",
              "Не, ҳама берун.", ["Nein."]),
            t("Die Feuerwehr kommt.", "Сӯхторнишонҳо меоянд.", "Бигӯ: берун интизорам", "Ich warte draußen.",
              "Берун интизорам.", ["Danke!"]),
        ]),
        ("Ором бош", [
            s("Bitte langsam.", "Оҳиста, лутфан.", None),
            s("Noch einmal, bitte.", "Боз як бор, лутфан.", None),
            s("Mein Name ist Ali.", "Номи ман Алӣ.", None),
            s("Meine Nummer ist hier.", "Рақамам ин ҷо.", None),
            s("Ja, ich verstehe.", "Ҳа, мефаҳмам.", None),
            s("Danke für die Hilfe.", "Барои ёрӣ ташаккур.", None),
        ]),
        ("Саволҳои 112", [
            t("Wie ist Ihr Name?", "Номатон чист?", "Бигӯ: номи ман Алӣ", "Mein Name ist Ali.", "Номи ман Алӣ.",
              ["Ali."]),
            t("Bleiben Sie am Telefon, bitte.", "Дар телефон монед, лутфан.", "Бигӯ: оҳиста, лутфан", "Bitte langsam.",
              "Оҳиста, лутфан.", ["Ich spreche wenig Deutsch."]),
            t("Bleiben… Sie… hier.", "Ин… ҷо… монед.", "Бигӯ: ҳа, мефаҳмам", "Ja, ich verstehe.", "Ҳа, мефаҳмам.",
              ["Okay."]),
        ]),
        ("Миссия: занг ба 112", [
            t("Notruf. Was ist passiert?", "Занги фаврӣ. Чӣ шуд?", "Бигӯ: садама шуд", "Es gibt einen Unfall.",
              "Садама шуд.", ["Ein Unfall!"]),
            t("Ist jemand verletzt?", "Касе захмӣ шуд?", "Бигӯ: ҳа, кӯдак захмӣ шуд", "Ja, ein Kind ist verletzt.",
              "Ҳа, кӯдак захмӣ шуд.", ["Ja, ein Kind."]),
            t("Wo sind Sie?", "Куҷоед?", "Бигӯ: дар кӯчаи Гартен, даҳ", "Gartenstraße zehn.", "Кӯчаи Гартен, даҳ.",
              ["In der Gartenstraße zehn."]),
            t("Der Krankenwagen kommt.", "Ёрии таъҷилӣ меояд.", "Бигӯ: лутфан тез биёед", "Bitte kommen Sie schnell.",
              "Лутфан тез биёед.", ["Bitte schnell!"]),
        ]),
    ], mission_mode="call"))

# ═════════════════════ 20. Дар сартарошхона ═════════════════════
made.append(pack("barber_de_tg", "Beim Friseur", "Дар сартарошхона", "💈", 20, L,
    "Шумо ба сартарошхона меравед: вақт мегиред, мегӯед, ки чӣ тавр буред — кӯтоҳ ё каме, риш, "
    "мепурсед, ки чанд пул аст ва ташаккур мегӯед.",
    [
        ("Сартарош", [
            w("Friseur", "сартарош", None),
            w("Haare", "мӯй", None),
            w("Kurz", "кӯтоҳ", None),
            w("Bart", "риш", None),
            w("Schneiden", "буридан", None),
            w("Termin", "вақти қабул", None),
        ]),
        ("Вақт ҳаст?", [
            t("Hallo! Haben Sie einen Termin?", "Салом! Вақти қабул доред?", "Бигӯ: не", "Nein.", "Не.",
              ["Nein, ohne Termin."]),
            t("Kein Problem. Zehn Minuten warten?", "Мушкил нест. Даҳ дақиқа интизор?", "Бигӯ: хуб", "Okay.", "Хуб.",
              ["Ja, ich warte.", "Gut."]),
            t("Bitte setzen Sie sich.", "Лутфан шинед.", "Ташаккур гӯй", "Danke.", "Ташаккур.", ["Danke schön."]),
        ]),
        ("Ибораҳо", [
            s("Kurz, bitte", "Кӯтоҳ, лутфан", None),
            s("Ein bisschen", "Каме", None),
            s("Den Bart", "Ришро", None),
            s("Mit Wasser", "Бо об", None),
            s("Sehr gut", "Хеле хуб", None),
            s("Wie viel?", "Чанд пул?", None),
        ]),
        ("Чӣ тавр?", [
            t("Wie möchten Sie die Haare?", "Мӯйро чӣ тавр мехоҳед?", "Бигӯ: кӯтоҳ, лутфан", "Kurz, bitte.",
              "Кӯтоҳ, лутфан.", ["Kurz."]),
            t("Und oben?", "Ва боло?", "Бигӯ: танҳо каме", "Nur ein bisschen.", "Танҳо каме.", ["Ein bisschen."]),
            t("Den Bart auch?", "Ришро ҳам?", "Бигӯ: ҳа, лутфан", "Ja, bitte.", "Ҳа, лутфан.", ["Nein, danke."]),
        ]),
        ("Ман мегӯям", [
            s("Ich möchte Haare schneiden.", "Мӯй гирифтан мехоҳам.", None),
            s("Bitte nicht zu kurz.", "Лутфан на хеле кӯтоҳ.", None),
            s("Oben länger, bitte.", "Боло дарозтар, лутфан.", None),
            s("Das ist gut so.", "Ҳамин хуб аст.", None),
            s("Was kostet das?", "Ин чанд пул?", None),
            s("Haben Sie morgen Zeit?", "Фардо вақт доред?", None),
        ]),
        ("Вақт фардо", [
            t("Friseur Schmidt, hallo?", "Сартарошхонаи Шмидт, ало?", "Бигӯ: фардо вақт доред?",
              "Haben Sie morgen Zeit?", "Фардо вақт доред?", ["Morgen einen Termin, bitte."]),
            t("Ja, um zehn Uhr.", "Ҳа, соати даҳ.", "Бигӯ: хуб, соати даҳ", "Gut, um zehn.", "Хуб, соати даҳ.",
              ["Zehn Uhr ist gut."]),
            t("Ihr Name?", "Номатон?", "Бигӯ: Алӣ", "Ali.", "Алӣ.", ["Mein Name ist Ali."]),
        ]),
        ("Тамом", [
            s("Gefällt es Ihnen?", "Маъқул аст?", None),
            s("Ja, sehr gut!", "Ҳа, хеле хуб!", None),
            s("Das macht fünfzehn Euro.", "Понздаҳ евро мешавад.", None),
            s("Mit Karte?", "Бо корт?", None),
            s("Danke, bis bald!", "Ташаккур, то дидан!", None),
            s("Bis zum nächsten Mal!", "То дафъаи дигар!", None),
        ]),
        ("Маъқул аст?", [
            t("So, fertig! Gefällt es Ihnen?", "Тамом! Маъқул аст?", "Бигӯ: ҳа, хеле хуб!", "Ja, sehr gut!",
              "Ҳа, хеле хуб!", ["Super, danke!"]),
            t("Das macht fünfzehn Euro.", "Понздаҳ евро мешавад.", "Бипурс: бо корт мешавад?", "Mit Karte?",
              "Бо корт мешавад?", ["Kann ich mit Karte zahlen?"]),
            t("Ja, natürlich.", "Ҳа, албатта.", "Бигӯ: ташаккур, то дидан!", "Danke, bis bald!", "Ташаккур, то дидан!",
              ["Danke, tschüss!"]),
        ]),
        ("Миссия: мӯйи нав", [
            t("Hallo! Was möchten Sie?", "Салом! Чӣ мехоҳед?", "Бигӯ: мӯй гирифтан мехоҳам",
              "Ich möchte Haare schneiden.", "Мӯй гирифтан мехоҳам.", ["Haare schneiden, bitte."]),
            t("Wie möchten Sie es?", "Чӣ тавр мехоҳед?", "Бигӯ: кӯтоҳ, аммо на хеле кӯтоҳ",
              "Kurz, aber nicht zu kurz.", "Кӯтоҳ, аммо на хеле кӯтоҳ.", ["Kurz, bitte."]),
            t("Und den Bart?", "Ва риш?", "Бигӯ: танҳо каме", "Nur ein bisschen.", "Танҳо каме.", ["Ein bisschen."]),
            t("Fertig! Gefällt es Ihnen?", "Тамом! Маъқул аст?", "Бигӯ: ҳа, хеле хуб!", "Ja, sehr gut!",
              "Ҳа, хеле хуб!", ["Super, danke!"]),
        ]),
    ]))

finish(made)
