"""ОЛМОНӢ → тоҷикӣ, «Гуфтор» A1 — нишаи «Хизматрасонӣ» (`service`), 04.10.2026.

14 вазъият барои коргари тоҷик дар тарабхона, қаҳвахона ва мағозаи Олмон — ҳамон тартиби
русӣ: ошхона, пешвози меҳмон, фармоиш, овардани хӯрок, ҳисоб, шикоят, касса, мол дар рафҳо,
ёрӣ ба харидор, фармоиш бо телефон, тозакунӣ, хӯрок ва аллергия, рӯзи серкор, ҷадвали кор.

Роҳи `service` = 6 вазъияти умумӣ (1, 2 «Кор ёфтан», 6, 10, 14, 16) + ин 14 → 20.

Қоидаҳо — `_de_packs_lib.py`: рақам бо ҳарф; Chef ба коргар — «du», коргар ба Chef — «Sie»;
бо меҳмон ва харидор ҳамеша «Sie». Транскрипсия: `node prisma/_de-fill-literal.mjs <slugs>`.

Аз ҷузвдони backend: python prisma/_de-service-a1-packs.py
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _de_packs_lib import *  # noqa: F401,F403

made = []
SV = ["service"]

# ═════════════════════ 3. Рӯзи аввал дар ошхона ═════════════════════
made.append(pack("kitchen_de_tg", "Erster Tag in der Küche", "Рӯзи аввал дар ошхона", "👨‍🍳", 3, SV,
    "Рӯзи аввали кор дар тарабхона. Chef ба шумо ошхона, яхдон ва ҷои либосро нишон медиҳад. "
    "Шумо мепурсед, ки чӣ кор кунед, ва дастурҳои оддиро иҷро мекунед.",
    [
        ("Ошхона", [
            w("Küche", "ошхона", None),
            w("Kühlschrank", "яхдон", None),
            w("Teller", "тақсимча", None),
            w("Messer", "корд", None),
            w("Schürze", "пешдоман", None),
            w("Spülen", "шустан (зарф)", None),
        ]),
        ("Салом, Chef", [
            t("Hallo! Bist du der Neue?", "Салом! Ту навӣ?", "Бигӯ: ҳа", "Ja.", "Ҳа.", ["Ja, ich bin neu."]),
            t("Ich bin Klaus, der Chef.", "Ман Клаус, сардор.", "Бигӯ: шодам", "Freut mich.", "Шодам.",
              ["Freut mich sehr.", "Hallo!"]),
            t("Hier ist deine Schürze.", "Мана пешдоманат.", "Ташаккур гӯй", "Danke.", "Ташаккур.", ["Danke schön."]),
        ]),
        ("Дастурҳо", [
            s("Hier spülen", "Ин ҷо бишӯй", None),
            s("Die Teller", "Тақсимчаҳо", None),
            w("Sofort", "ҳозир", None),
            s("Was jetzt?", "Ҳоло чӣ?", None),
            s("Im Kühlschrank", "Дар яхдон", None),
            w("Fertig", "тайёр, тамом", None),
        ]),
        ("Чӣ кор кунам?", [
            t("Spül bitte die Teller.", "Тақсимчаҳоро бишӯй, лутфан.", "Бигӯ: ҳозир", "Sofort!", "Ҳозир!",
              ["Ja, sofort.", "Okay!"]),
            t("Bist du fertig?", "Тамом кардӣ?", "Бигӯ: ҳа, тамом", "Ja, fertig.", "Ҳа, тамом.", ["Ja.", "Fertig!"]),
            t("Gut gemacht!", "Офарин!", "Бипурс: ҳоло чӣ?", "Was jetzt?", "Ҳоло чӣ?",
              ["Was mache ich jetzt?", "Und jetzt?"]),
        ]),
        ("Ман нав ҳастам", [
            s("Ich bin neu hier.", "Ман ин ҷо нав ҳастам.", None),
            s("Was mache ich jetzt?", "Ҳоло чӣ кор кунам?", None),
            s("Wo sind die Teller?", "Тақсимчаҳо куҷоянд?", None),
            s("Wo ist der Kühlschrank?", "Яхдон куҷост?", None),
            s("Zeigen Sie mir, bitte.", "Нишон диҳед, лутфан.", None),
            s("Ich verstehe.", "Мефаҳмам.", None),
        ]),
        ("Ошхона нишон медиҳад", [
            t("Das ist die Küche.", "Ин ошхона.", "Бипурс: яхдон куҷост?", "Wo ist der Kühlschrank?",
              "Яхдон куҷост?", ["Und der Kühlschrank?"]),
            t("Da links.", "Он ҷо, тарафи чап.", "Бипурс: тақсимчаҳо куҷоянд?", "Wo sind die Teller?",
              "Тақсимчаҳо куҷоянд?", ["Und die Teller?"]),
            t("Hier oben.", "Ин ҷо, дар боло.", "Бигӯ: мефаҳмам, ташаккур", "Ich verstehe, danke.",
              "Мефаҳмам, ташаккур.", ["Okay, danke.", "Danke."]),
        ]),
        ("Тоза ва бехатар", [
            s("Hände waschen", "Дастҳоро бишӯй", None),
            s("Das Messer ist scharf.", "Корд тез аст.", None),
            s("Vorsicht, heiß!", "Эҳтиёт, гарм!", None),
            s("Der Boden ist nass.", "Фарш тар аст.", None),
            s("Wo ist der Müll?", "Партов куҷост?", None),
            s("Ich wasche die Hände.", "Ман дастҳоро мешӯям.", None),
        ]),
        ("Эҳтиёт!", [
            t("Vorsicht! Das ist heiß!", "Эҳтиёт! Ин гарм аст!", "Бигӯ: хуб, ташаккур", "Okay, danke!", "Хуб, ташаккур!",
              ["Danke!", "Ah, danke."]),
            t("Wasch zuerst die Hände.", "Аввал дастҳоро бишӯй.", "Бигӯ: хуб, ҳозир", "Okay, sofort.", "Хуб, ҳозир.",
              ["Ja, sofort.", "Gut."]),
            t("Der Müll ist draußen.", "Партов берун аст.", "Бигӯ: фаҳмидам", "Verstanden.", "Фаҳмидам.",
              ["Okay, verstanden.", "Ich verstehe."]),
        ]),
        ("Миссия: рӯзи аввал", [
            t("Hallo! Bist du neu?", "Салом! Навӣ?", "Бигӯ: ҳа, ман нав ҳастам", "Ja, ich bin neu hier.",
              "Ҳа, ман ин ҷо нав ҳастам.", ["Ja.", "Ja, ich bin neu."]),
            t("Gut. Hier ist deine Schürze.", "Хуб. Мана пешдоманат.", "Бипурс: ҳоло чӣ кор кунам?",
              "Was mache ich jetzt?", "Ҳоло чӣ кор кунам?", ["Was jetzt?", "Danke. Was mache ich?"]),
            t("Spül die Teller, bitte.", "Тақсимчаҳоро бишӯй.", "Бипурс: тақсимчаҳо куҷоянд?", "Wo sind die Teller?",
              "Тақсимчаҳо куҷоянд?", ["Wo sind sie?"]),
            t("Da links. Danke!", "Он ҷо, тарафи чап. Ташаккур!", "Бигӯ: ҳозир", "Sofort!", "Ҳозир!",
              ["Okay, sofort.", "Gerne."]),
        ]),
    ]))

# ═════════════════════ 4. Пешвоз гирифтани меҳмон ═════════════════════
made.append(pack("host_de_tg", "Gäste begrüßen", "Пешвоз гирифтани меҳмон", "🙋", 4, SV,
    "Шумо дар дари тарабхона меҳмононро пешвоз мегиред: салом медиҳед, мепурсед, ки чанд нафаранд, "
    "мизро нишон медиҳед ва менюро медиҳед.",
    [
        ("Тарабхона", [
            w("Gast", "меҳмон", "Ҷамъ: «Gäste»."),
            w("Tisch", "миз", None),
            w("Personen", "нафар", None),
            w("Speisekarte", "меню", None),
            w("Reserviert", "банд (фармоишшуда)", None),
            w("Draußen", "берун", None),
        ]),
        ("Хуш омадед!", [
            t("Guten Abend!", "Шом ба хайр!", "Салом гӯй ва бигӯ: хуш омадед", "Guten Abend! Willkommen!",
              "Шом ба хайр! Хуш омадед!", ["Willkommen!", "Guten Abend!"]),
            t("Einen Tisch, bitte.", "Як миз, лутфан.", "Бипурс: барои чанд нафар?", "Für wie viele Personen?",
              "Барои чанд нафар?", ["Wie viele Personen?", "Für wie viele?"]),
            t("Für zwei.", "Барои ду нафар.", "Бигӯ: лутфан, аз ин ҷо", "Bitte kommen Sie.", "Лутфан, биёед.",
              ["Hier, bitte.", "Bitte, hier."]),
        ]),
        ("Ибораҳо", [
            s("Herzlich willkommen", "Хуш омадед", None),
            s("Wie viele?", "Чанд нафар?", None),
            s("Dieser Tisch", "Ин миз", None),
            s("Bitte warten", "Лутфан интизор шавед", None),
            s("Die Speisekarte", "Меню", None),
            s("Oder draußen?", "Ё берун?", None),
        ]),
        ("Дарун ё берун?", [
            t("Wir sind drei.", "Мо се нафарем.", "Бипурс: дарун ё берун?", "Drinnen oder draußen?",
              "Дарун ё берун?", ["Möchten Sie draußen sitzen?"]),
            t("Draußen, bitte.", "Берун, лутфан.", "Бигӯ: ин миз, лутфан", "Dieser Tisch, bitte.", "Ин миз, лутфан.",
              ["Hier, bitte.", "Bitte schön."]),
            t("Danke!", "Ташаккур!", "Бигӯ: мана меню", "Hier ist die Speisekarte.", "Мана меню.",
              ["Die Speisekarte, bitte.", "Bitte schön."]),
        ]),
        ("Ҷумлаҳои пешвоз", [
            s("Haben Sie reserviert?", "Ҷой фармоиш додаед?", None),
            s("Bitte setzen Sie sich.", "Лутфан шинед.", None),
            s("Der Tisch ist frei.", "Миз холӣ аст.", None),
            s("Alles ist voll.", "Ҳама ҷо пур аст.", None),
            s("Zehn Minuten, bitte.", "Даҳ дақиқа, лутфан.", None),
            s("Ich bringe die Speisekarte.", "Менюро меорам.", None),
        ]),
        ("Ҷой фармоиш дода?", [
            t("Hallo, wir sind vier.", "Салом, мо чор нафарем.", "Бипурс: ҷой фармоиш додаед?", "Haben Sie reserviert?",
              "Ҷой фармоиш додаед?", ["Reserviert?", "Haben Sie eine Reservierung?"]),
            t("Nein, leider nicht.", "Не, мутаассифона.", "Бигӯ: як миз холӣ аст", "Ein Tisch ist frei.",
              "Як миз холӣ аст.", ["Der Tisch ist frei.", "Kein Problem."]),
            t("Super, danke!", "Олӣ, ташаккур!", "Бигӯ: лутфан шинед", "Bitte setzen Sie sich.", "Лутфан шинед.",
              ["Bitte schön.", "Bitte hier."]),
        ]),
        ("Ҷой нест", [
            s("Leider ist alles voll.", "Мутаассифона ҳама ҷо пур.", None),
            s("Können Sie warten?", "Интизор шуда метавонед?", None),
            s("Gleich ist frei.", "Ҳозир холӣ мешавад.", None),
            s("Ihr Name, bitte?", "Номатон, лутфан?", None),
            s("Bitte kommen Sie.", "Лутфан биёед.", None),
            s("Entschuldigung, einen Moment.", "Бубахшед, як лаҳза.", None),
        ]),
        ("Интизорӣ", [
            t("Einen Tisch für zwei, bitte.", "Миз барои ду нафар, лутфан.", "Бигӯ: мутаассифона ҳама ҷо пур",
              "Leider ist alles voll.", "Мутаассифона ҳама ҷо пур.", ["Alles ist voll, leider."]),
            t("Wie lange?", "Чӣ қадар?", "Бигӯ: даҳ дақиқа", "Zehn Minuten.", "Даҳ дақиқа.", ["Ungefähr zehn Minuten."]),
            t("Okay, wir warten.", "Хуб, интизор мешавем.", "Бипурс: номатон, лутфан?", "Ihr Name, bitte?",
              "Номатон, лутфан?", ["Wie ist Ihr Name?"]),
        ]),
        ("Миссия: шоми серкор", [
            t("Guten Abend!", "Шом ба хайр!", "Салом гӯй ва бигӯ: хуш омадед", "Guten Abend! Willkommen!",
              "Шом ба хайр! Хуш омадед!", ["Herzlich willkommen!"]),
            t("Einen Tisch für zwei, bitte.", "Миз барои ду нафар.", "Бипурс: дарун ё берун?", "Drinnen oder draußen?",
              "Дарун ё берун?", ["Möchten Sie drinnen sitzen?"]),
            t("Drinnen, bitte.", "Дарун, лутфан.", "Бигӯ: ин миз, лутфан", "Dieser Tisch, bitte.", "Ин миз, лутфан.",
              ["Bitte hier.", "Bitte setzen Sie sich."]),
            t("Danke schön!", "Ташаккури зиёд!", "Бигӯ: мана меню", "Hier ist die Speisekarte.", "Мана меню.",
              ["Die Speisekarte, bitte schön."]),
        ]),
    ]))

# ═════════════════════ 5. Қабули фармоиш ═════════════════════
made.append(pack("take_order_de_tg", "Bestellung aufnehmen", "Қабули фармоиш", "📝", 5, SV,
    "Шумо фармоиши меҳмонро мегиред: мепурсед, ки чӣ менӯшанд ва чӣ мехӯранд, такрор мекунед ва "
    "мегӯед, ки хӯрок кай тайёр мешавад.",
    [
        ("Меню", [
            w("Bestellen", "фармоиш додан", None),
            w("Getränk", "нӯшокӣ", None),
            w("Wasser", "об", None),
            w("Tee", "чой", None),
            w("Salat", "салат", None),
            w("Pizza", "питса", None),
        ]),
        ("Нӯшокӣ", [
            t("Hallo! Wir möchten bestellen.", "Салом! Мо фармоиш додан мехоҳем.", "Бипурс: чӣ менӯшед?",
              "Was möchten Sie trinken?", "Чӣ менӯшед?", ["Was trinken Sie?", "Getränke?"]),
            t("Zwei Wasser, bitte.", "Ду об, лутфан.", "Бигӯ: хуб", "Gerne.", "Бо хурсандӣ.", ["Okay.", "Sehr gut."]),
            t("Und einen Tee.", "Ва як чой.", "Бигӯ: як чой, хуб", "Ein Tee, gut.", "Як чой, хуб.", ["Gerne.", "Okay."]),
        ]),
        ("Саволҳо", [
            s("Ihre Bestellung?", "Фармоишатон?", None),
            s("Zu trinken?", "Барои нӯшидан?", None),
            s("Zu essen?", "Барои хӯрдан?", None),
            s("Noch etwas?", "Боз чизе?", None),
            w("Sofort", "ҳозир", None),
            s("Gute Wahl", "Интихоби хуб", None),
        ]),
        ("Хӯрок", [
            t("Ich nehme eine Pizza.", "Ман питса мегирам.", "Бигӯ: интихоби хуб", "Gute Wahl.", "Интихоби хуб.",
              ["Sehr gut.", "Gerne."]),
            t("Und einen Salat.", "Ва як салат.", "Бипурс: боз чизе?", "Noch etwas?", "Боз чизе?",
              ["Sonst noch etwas?"]),
            t("Nein, danke.", "Не, ташаккур.", "Бигӯ: хуб, ҳозир", "Gut, sofort.", "Хуб, ҳозир.", ["Okay, danke."]),
        ]),
        ("Фармоиш мегирам", [
            s("Was möchten Sie trinken?", "Чӣ нӯшидан мехоҳед?", None),
            s("Möchten Sie bestellen?", "Фармоиш медиҳед?", None),
            s("Eine Pizza, ein Salat.", "Як питса, як салат.", None),
            s("Das dauert zehn Minuten.", "Ин даҳ дақиқа мегирад.", None),
            s("Mit oder ohne Eis?", "Бо ях ё бе ях?", None),
            s("Ich bringe es sofort.", "Ҳозир меорам.", None),
        ]),
        ("Такрори фармоиш", [
            t("Eine Pizza und ein Wasser.", "Як питса ва як об.", "Такрор кун: як питса, як об",
              "Eine Pizza, ein Wasser.", "Як питса, як об.", ["Also, eine Pizza und ein Wasser."]),
            t("Ja, genau.", "Ҳа, дуруст.", "Бигӯ: ин даҳ дақиқа мегирад", "Das dauert zehn Minuten.",
              "Ин даҳ дақиқа мегирад.", ["Zehn Minuten, bitte."]),
            t("Kein Problem.", "Мушкил нест.", "Ташаккур гӯй", "Danke!", "Ташаккур!", ["Danke schön."]),
        ]),
        ("Саволи меҳмон", [
            s("Was ist das?", "Ин чист?", None),
            s("Das ist Hähnchen.", "Ин мурғ аст.", None),
            s("Ist das scharf?", "Ин тунд аст?", None),
            s("Nein, nicht scharf.", "Не, тунд нест.", None),
            s("Das ist sehr gut.", "Ин хеле хуб аст.", None),
            s("Ich frage den Koch.", "Аз ошпаз мепурсам.", None),
        ]),
        ("Ин чист?", [
            t("Was ist das hier?", "Ин чист?", "Бигӯ: ин мурғ аст", "Das ist Hähnchen.", "Ин мурғ аст.",
              ["Hähnchen mit Reis.", "Das ist Hähnchen mit Reis."]),
            t("Ist das scharf?", "Тунд аст?", "Бигӯ: не, тунд нест", "Nein, nicht scharf.", "Не, тунд нест.",
              ["Nein.", "Ein bisschen."]),
            t("Gut, das nehme ich.", "Хуб, инро мегирам.", "Бигӯ: интихоби хуб", "Gute Wahl!", "Интихоби хуб!",
              ["Sehr gut!", "Gerne!"]),
        ]),
        ("Миссия: мизи панҷ", [
            t("Hallo! Wir möchten bestellen.", "Салом! Фармоиш медиҳем.", "Бипурс: чӣ менӯшед?",
              "Was möchten Sie trinken?", "Чӣ менӯшед?", ["Was trinken Sie?"]),
            t("Ein Wasser und einen Tee.", "Як об ва як чой.", "Бипурс: ва барои хӯрдан?", "Und zu essen?",
              "Ва барои хӯрдан?", ["Was möchten Sie essen?"]),
            t("Zwei Pizza, bitte.", "Ду питса, лутфан.", "Бипурс: боз чизе?", "Noch etwas?", "Боз чизе?",
              ["Sonst noch etwas?"]),
            t("Nein, das ist alles.", "Не, ҳамин.", "Бигӯ: хуб, даҳ дақиқа", "Gut, zehn Minuten.", "Хуб, даҳ дақиқа.",
              ["Das dauert zehn Minuten.", "Okay, sofort."]),
        ]),
    ]))

# ═════════════════════ 7. Овардани хӯрок ═════════════════════
made.append(pack("serving_de_tg", "Essen servieren", "Овардани хӯрок", "🍽️", 7, SV,
    "Шумо хӯрокро ба миз меоред: мегӯед, ки кадом хӯрок аз кист, ош шавад мегӯед, мепурсед, ки "
    "хӯрок маъқул аст ва зарфҳои холиро мебаред.",
    [
        ("Миз", [
            w("Gabel", "чангча", None),
            w("Löffel", "қошуқ", None),
            w("Glas", "стакан", None),
            w("Serviette", "дастмолча", None),
            w("Heiß", "гарм", None),
            w("Leer", "холӣ", None),
        ]),
        ("Хӯрок омад", [
            t("Ist das unsere Pizza?", "Ин питсаи мост?", "Бигӯ: ҳа, ош шавад", "Ja. Guten Appetit!", "Ҳа. Ош шавад!",
              ["Ja, bitte schön.", "Guten Appetit!"]),
            t("Und der Salat?", "Ва салат?", "Бигӯ: ҳозир меорам", "Ich bringe ihn sofort.", "Ҳозир меорам.",
              ["Sofort!", "Kommt sofort."]),
            t("Danke!", "Ташаккур!", "Бигӯ: бо хурсандӣ", "Gerne.", "Бо хурсандӣ.", ["Bitte schön."]),
        ]),
        ("Ибораҳо", [
            s("Für wen?", "Барои кӣ?", None),
            s("Guten Appetit!", "Ош шавад!", None),
            s("Vorsicht, heiß", "Эҳтиёт, гарм", None),
            s("Noch Brot?", "Боз нон?", None),
            s("Schmeckt es?", "Маъқул аст?", None),
            s("Bitte schön", "Марҳамат", None),
        ]),
        ("Барои кӣ?", [
            t("Hier, eine Pizza.", "Мана, як питса.", "Бипурс: барои кӣ?", "Für wen?", "Барои кӣ?",
              ["Wer bekommt die Pizza?"]),
            t("Für mich, danke.", "Барои ман, ташаккур.", "Бигӯ: эҳтиёт, гарм", "Vorsicht, heiß!", "Эҳтиёт, гарм!",
              ["Vorsicht, der Teller ist heiß."]),
            t("Danke für die Info.", "Барои огоҳӣ ташаккур.", "Бигӯ: ош шавад", "Guten Appetit!", "Ош шавад!",
              ["Bitte schön, guten Appetit."]),
        ]),
        ("Дар сари миз", [
            s("Brauchen Sie noch etwas?", "Боз чизе лозим?", None),
            s("Ich bringe eine Gabel.", "Як чангча меорам.", None),
            s("Ist alles gut?", "Ҳама хуб аст?", None),
            s("Darf ich das nehmen?", "Инро бардорам?", None),
            s("Der Teller ist leer.", "Тақсимча холӣ аст.", None),
            s("Noch ein Glas Wasser?", "Боз як стакан об?", None),
        ]),
        ("Ҳама хуб?", [
            t("Entschuldigung!", "Бубахшед!", "Бипурс: боз чизе лозим?", "Brauchen Sie noch etwas?",
              "Боз чизе лозим?", ["Ja, bitte?", "Kann ich helfen?"]),
            t("Ja, eine Gabel, bitte.", "Ҳа, як чангча, лутфан.", "Бигӯ: ҳозир меорам", "Ich bringe sie sofort.",
              "Ҳозир меорам.", ["Sofort!", "Kommt sofort."]),
            t("Und noch Brot, bitte.", "Ва боз нон, лутфан.", "Бигӯ: бо хурсандӣ", "Gerne.", "Бо хурсандӣ.",
              ["Natürlich.", "Okay."]),
        ]),
        ("Баъди хӯрок", [
            s("Hat es geschmeckt?", "Маъқул буд?", None),
            s("Möchten Sie Nachtisch?", "Ширинӣ мехоҳед?", None),
            s("Einen Kaffee vielleicht?", "Шояд як қаҳва?", None),
            s("Ich putze den Tisch.", "Мизро тоза мекунам.", None),
            s("Das freut mich.", "Аз ин шодам.", None),
            s("Noch etwas?", "Боз чизе?", None),
        ]),
        ("Ширинӣ?", [
            t("Fertig, danke.", "Тамом, ташаккур.", "Бипурс: маъқул буд?", "Hat es geschmeckt?", "Маъқул буд?",
              ["Schmeckt es?", "War alles gut?"]),
            t("Ja, sehr gut!", "Ҳа, хеле хуб!", "Бигӯ: аз ин шодам", "Das freut mich.", "Аз ин шодам.",
              ["Super!", "Schön!"]),
            t("Ja.", "Ҳа.", "Бипурс: ширинӣ мехоҳед?", "Möchten Sie Nachtisch?", "Ширинӣ мехоҳед?",
              ["Nachtisch?", "Einen Kaffee vielleicht?"]),
        ]),
        ("Миссия: мизи серкор", [
            t("Ist das mein Salat?", "Ин салати ман аст?", "Бигӯ: ҳа, марҳамат", "Ja, bitte schön.", "Ҳа, марҳамат.",
              ["Ja. Guten Appetit!"]),
            t("Danke! Noch eine Gabel, bitte.", "Ташаккур! Боз як чангча.", "Бигӯ: ҳозир меорам",
              "Ich bringe sie sofort.", "Ҳозир меорам.", ["Sofort!"]),
            t("Danke. Es schmeckt gut.", "Ташаккур. Бомаза аст.", "Бигӯ: аз ин шодам", "Das freut mich.",
              "Аз ин шодам.", ["Schön!", "Super!"]),
            t("Wir sind fertig.", "Мо тамом кардем.", "Бипурс: ширинӣ мехоҳед?", "Möchten Sie Nachtisch?",
              "Ширинӣ мехоҳед?", ["Einen Kaffee vielleicht?", "Noch etwas?"]),
        ]),
    ]))

# ═════════════════════ 8. Ҳисоб дар тарабхона ═════════════════════
made.append(pack("bill_de_tg", "Die Rechnung", "Ҳисоб дар тарабхона", "🧾", 8, SV,
    "Меҳмон ҳисобро мехоҳад: шумо ҳисобро меоред, нархро мегӯед, мепурсед, ки бо корт ё нақд "
    "пардохт мекунад, бақияро медиҳед ва ташаккур мегӯед.",
    [
        ("Ҳисоб", [
            w("Rechnung", "ҳисоб, чек", None),
            w("Bar", "нақд", None),
            w("Karte", "корт", None),
            w("Zusammen", "якҷоя", None),
            w("Getrennt", "алоҳида", None),
            w("Trinkgeld", "чойпулӣ", None),
        ]),
        ("Ҳисоб, лутфан", [
            t("Die Rechnung, bitte.", "Ҳисоб, лутфан.", "Бигӯ: ҳозир", "Sofort.", "Ҳозир.", ["Gerne.", "Ja, sofort."]),
            t("Wie viel ist es?", "Чанд шуд?", "Бигӯ: бист евро", "Zwanzig Euro.", "Бист евро.",
              ["Das macht zwanzig Euro."]),
            t("Mit Karte, bitte.", "Бо корт, лутфан.", "Бигӯ: хуб", "Gerne.", "Бо хурсандӣ.", ["Okay.", "Kein Problem."]),
        ]),
        ("Пардохт", [
            s("Oder getrennt?", "Ё алоҳида?", None),
            s("Mit Karte?", "Бо корт?", None),
            s("Zehn Euro", "Даҳ евро", None),
            s("Stimmt so", "Бақия лозим нест", "Меҳмон мегӯяд — бақия чойпулӣ."),
            s("Ihr Wechselgeld", "Бақияатон", None),
            s("Vielen Dank", "Ташаккури зиёд", None),
        ]),
        ("Якҷоя ё алоҳида?", [
            t("Wir möchten zahlen.", "Мо пардохт кардан мехоҳем.", "Бипурс: якҷоя ё алоҳида?",
              "Zusammen oder getrennt?", "Якҷоя ё алоҳида?", ["Zusammen?"]),
            t("Getrennt, bitte.", "Алоҳида, лутфан.", "Бипурс: нақд ё корт?", "Bar oder Karte?", "Нақд ё корт?",
              ["Zahlen Sie bar?"]),
            t("Bar.", "Нақд.", "Бигӯ: хуб", "Okay.", "Хуб.", ["Gut.", "Gerne."]),
        ]),
        ("Ман ҳисоб меорам", [
            s("Ich bringe die Rechnung.", "Ҳисобро меорам.", None),
            s("Das macht fünfzehn Euro.", "Понздаҳ евро мешавад.", None),
            s("Hier ist Ihr Wechselgeld.", "Мана бақияатон.", None),
            s("Die Karte, bitte.", "Корт, лутфан.", None),
            s("Danke für das Trinkgeld.", "Барои чойпулӣ ташаккур.", None),
            s("Einen schönen Abend!", "Шоми хуш!", None),
        ]),
        ("Бақия", [
            t("Hier sind zwanzig Euro.", "Мана бист евро.", "Бигӯ: мана бақияатон", "Hier ist Ihr Wechselgeld.",
              "Мана бақияатон.", ["Ihr Wechselgeld, bitte.", "Fünf Euro zurück."]),
            t("Stimmt so.", "Бақия лозим нест.", "Барои чойпулӣ ташаккур гӯй", "Danke für das Trinkgeld!",
              "Барои чойпулӣ ташаккур!", ["Vielen Dank!", "Danke schön!"]),
            t("Tschüss!", "Хайр!", "Бигӯ: шоми хуш!", "Einen schönen Abend!", "Шоми хуш!",
              ["Tschüss, schönen Abend!", "Auf Wiedersehen!"]),
        ]),
        ("Мушкили пардохт", [
            s("Die Karte geht nicht.", "Корт кор намекунад.", None),
            s("Noch einmal, bitte.", "Боз як бор, лутфан.", None),
            s("Haben Sie Bargeld?", "Пули нақд доред?", None),
            s("Die PIN, bitte.", "Рамзи корт, лутфан.", None),
            s("Jetzt geht es.", "Ҳоло шуд.", None),
            s("Kein Problem.", "Мушкил нест.", None),
        ]),
        ("Корт кор намекунад", [
            t("Hier ist meine Karte.", "Мана корти ман.", "Бигӯ: рамзи корт, лутфан", "Die PIN, bitte.",
              "Рамзи корт, лутфан.", ["Bitte die PIN.", "Ihre PIN, bitte."]),
            t("So, fertig?", "Хуб, тамом?", "Бигӯ: корт кор намекунад", "Die Karte geht nicht.", "Корт кор намекунад.",
              ["Leider geht die Karte nicht.", "Noch einmal, bitte."]),
            t("Oh! Ich zahle bar.", "О! Нақд медиҳам.", "Бигӯ: мушкил нест", "Kein Problem.", "Мушкил нест.",
              ["Okay, kein Problem.", "Gut."]),
        ]),
        ("Миссия: ҳисоби мизи ду", [
            t("Die Rechnung, bitte.", "Ҳисоб, лутфан.", "Бипурс: якҷоя ё алоҳида?", "Zusammen oder getrennt?",
              "Якҷоя ё алоҳида?", ["Zusammen?"]),
            t("Zusammen.", "Якҷоя.", "Бигӯ: сӣ евро мешавад", "Das macht dreißig Euro.", "Сӣ евро мешавад.",
              ["Dreißig Euro, bitte."]),
            t("Mit Karte, bitte.", "Бо корт, лутфан.", "Бигӯ: рамзи корт, лутфан", "Die PIN, bitte.",
              "Рамзи корт, лутфан.", ["Bitte die PIN."]),
            t("Danke! Tschüss!", "Ташаккур! Хайр!", "Бигӯ: шоми хуш!", "Einen schönen Abend!", "Шоми хуш!",
              ["Danke, schönen Abend!", "Auf Wiedersehen!"]),
        ]),
    ]))

# ═════════════════════ 9. Шикояти меҳмон ═════════════════════
made.append(pack("complaint_de_tg", "Ein unzufriedener Gast", "Шикояти меҳмон", "😟", 9, SV,
    "Меҳмон норозӣ аст: хӯрок хунук ё нодуруст аст, ё дер омад. Шумо бубахшед мегӯед, мегӯед, "
    "ки онро иваз мекунед ва ба сардор хабар медиҳед.",
    [
        ("Мушкил", [
            w("Kalt", "хунук", None),
            w("Falsch", "нодуруст", None),
            w("Spät", "дер", None),
            w("Schmutzig", "чиркин", None),
            w("Entschuldigung", "бубахшед", None),
            w("Neu", "нав", None),
        ]),
        ("Хӯрок хунук аст", [
            t("Entschuldigung! Die Suppe ist kalt.", "Бубахшед! Шӯрбо хунук аст.", "Бигӯ: бубахшед",
              "Entschuldigung!", "Бубахшед!", ["Oh, Entschuldigung.", "Das tut mir leid."]),
            t("Ich möchte eine neue.", "Навашро мехоҳам.", "Бигӯ: ҳозир", "Sofort.", "Ҳозир.",
              ["Ja, sofort.", "Natürlich, sofort."]),
            t("Danke.", "Ташаккур.", "Бигӯ: бо хурсандӣ", "Gerne.", "Бо хурсандӣ.", ["Bitte."]),
        ]),
        ("Ибораҳо", [
            s("Mein Fehler", "Хатои ман", None),
            s("Neues Essen", "Хӯроки нав", None),
            s("Einen Moment", "Як лаҳза", None),
            s("Kalte Suppe", "Шӯрбои хунук", None),
            s("Der Chef", "Сардор", None),
            w("Natürlich", "албатта", None),
        ]),
        ("Хӯроки нодуруст", [
            t("Das ist falsch. Ich habe Hähnchen bestellt.", "Ин нодуруст. Ман мурғ фармудам.", "Бигӯ: мебахшед, хатои ман",
              "Entschuldigung, mein Fehler.", "Бубахшед, хатои ман.", ["Das tut mir leid.", "Oh, Entschuldigung."]),
            t("Bitte schnell.", "Лутфан тезтар.", "Бигӯ: инро иваз мекунам", "Ich wechsle das.", "Инро иваз мекунам.",
              ["Sofort.", "Ich wechsle das sofort."]),
            t("Okay.", "Хуб.", "Бигӯ: як лаҳза", "Einen Moment, bitte.", "Як лаҳза, лутфан.", ["Einen Moment."]),
        ]),
        ("Ҷавоб ба шикоят", [
            s("Es tut mir leid.", "Афсӯс мехӯрам.", None),
            s("Ich bringe eine neue.", "Навашро меорам.", None),
            s("Das geht schnell.", "Ин зуд мешавад.", None),
            s("Ich rufe den Chef.", "Сардорро даъват мекунам.", None),
            s("Das Glas ist schmutzig.", "Стакан чиркин аст.", None),
            s("Ist jetzt alles gut?", "Ҳоло ҳама хуб?", None),
        ]),
        ("Стакани чиркин", [
            t("Das Glas ist schmutzig!", "Стакан чиркин аст!", "Бигӯ: хеле афсӯс мехӯрам", "Das tut mir sehr leid.",
              "Хеле афсӯс мехӯрам.", ["Entschuldigung!", "Oh, das tut mir leid."]),
            t("Ein neues, bitte.", "Нав, лутфан.", "Бигӯ: ҳозир меорам", "Ich bringe sofort ein neues.",
              "Ҳозир навашро меорам.", ["Sofort!", "Natürlich."]),
            t("Danke.", "Ташаккур.", "Бипурс: ҳоло ҳама хуб?", "Ist jetzt alles gut?", "Ҳоло ҳама хуб?",
              ["Alles gut?"]),
        ]),
        ("Хеле дер", [
            s("Wir warten schon lange.", "Мо кайҳо интизорем.", None),
            s("Es dauert noch kurz.", "Боз каме вақт мегирад.", None),
            s("Die Küche ist voll.", "Ошхона серкор аст.", None),
            s("Ein Getränk gratis?", "Як нӯшокӣ ройгон?", None),
            s("Danke fürs Warten.", "Барои интизорӣ ташаккур.", None),
            s("Ich frage den Koch.", "Аз ошпаз мепурсам.", None),
        ]),
        ("Интизории дароз", [
            t("Wir warten schon lange!", "Мо кайҳо интизорем!", "Бигӯ: бубахшед, ошхона серкор аст",
              "Entschuldigung, die Küche ist voll.", "Бубахшед, ошхона серкор аст.", ["Das tut mir leid."]),
            t("Wie lange noch?", "Боз чӣ қадар?", "Бигӯ: аз ошпаз мепурсам", "Ich frage den Koch.",
              "Аз ошпаз мепурсам.", ["Einen Moment, ich frage."]),
            t("Okay, danke.", "Хуб, ташаккур.", "Бигӯ: барои интизорӣ ташаккур", "Danke fürs Warten.",
              "Барои интизорӣ ташаккур.", ["Vielen Dank.", "Danke."]),
        ]),
        ("Миссия: меҳмони норозӣ", [
            t("Entschuldigung! Das ist falsch!", "Бубахшед! Ин нодуруст аст!", "Бигӯ: хеле афсӯс мехӯрам",
              "Das tut mir sehr leid.", "Хеле афсӯс мехӯрам.", ["Entschuldigung!", "Oh, das tut mir leid."]),
            t("Und die Suppe ist kalt.", "Ва шӯрбо хунук аст.", "Бигӯ: навашро меорам", "Ich bringe eine neue.",
              "Навашро меорам.", ["Ich wechsle das sofort."]),
            t("Ich möchte den Chef sprechen.", "Бо сардор гап задан мехоҳам.", "Бигӯ: сардорро даъват мекунам",
              "Ich rufe den Chef.", "Сардорро даъват мекунам.", ["Einen Moment, ich rufe den Chef."]),
            t("Danke.", "Ташаккур.", "Бигӯ: барои интизорӣ ташаккур", "Danke fürs Warten.",
              "Барои интизорӣ ташаккур.", ["Gerne.", "Vielen Dank."]),
        ]),
    ]))

# ═════════════════════ 11. Дар касса ═════════════════════
made.append(pack("cashier_de_tg", "An der Kasse", "Дар касса", "💳", 11, SV,
    "Шумо дар кассаи мағоза кор мекунед: салом медиҳед, нархро мегӯед, халта пешниҳод мекунед, "
    "пулро мегиред ва чек медиҳед.",
    [
        ("Касса", [
            w("Kasse", "касса", None),
            w("Tüte", "халта", None),
            w("Kassenbon", "чек", None),
            w("Preis", "нарх", None),
            w("Kleingeld", "пули майда", None),
            w("Angebot", "тахфиф, пешниҳоди махсус", None),
        ]),
        ("Салом дар касса", [
            t("Hallo!", "Салом!", "Салом гӯй", "Hallo! Guten Tag!", "Салом! Рӯз ба хайр!", ["Guten Tag!"]),
            t("Das hier, bitte.", "Ин, лутфан.", "Бипурс: халта мехоҳед?", "Brauchen Sie eine Tüte?", "Халта мехоҳед?",
              ["Eine Tüte?"]),
            t("Ja, bitte.", "Ҳа, лутфан.", "Бигӯ: даҳ евро мешавад", "Das macht zehn Euro.", "Даҳ евро мешавад.",
              ["Zehn Euro, bitte."]),
        ]),
        ("Ибораҳо", [
            s("Eine Tüte?", "Халта?", None),
            s("Den Bon?", "Чек?", None),
            s("Mit Karte?", "Бо корт?", None),
            s("Hier, bitte", "Мана, марҳамат", None),
            s("Schönen Tag!", "Рӯзи хуш!", None),
            s("Der Nächste", "Навбатӣ", None),
        ]),
        ("Чек мехоҳед?", [
            t("Ich zahle mit Karte.", "Бо корт пардохт мекунам.", "Бигӯ: хуб, марҳамат", "Gut, bitte.", "Хуб, марҳамат.",
              ["Okay.", "Gerne."]),
            t("Fertig?", "Тамом?", "Бипурс: чек мехоҳед?", "Möchten Sie den Bon?", "Чек мехоҳед?", ["Den Bon?"]),
            t("Nein, danke.", "Не, ташаккур.", "Бигӯ: рӯзи хуш!", "Schönen Tag!", "Рӯзи хуш!",
              ["Einen schönen Tag!", "Tschüss!"]),
        ]),
        ("Ман дар касса", [
            s("Das macht acht Euro.", "Ҳашт евро мешавад.", None),
            s("Haben Sie Kleingeld?", "Пули майда доред?", None),
            s("Hier ist Ihr Bon.", "Мана чекатон.", None),
            s("Die Tüte kostet extra.", "Халта алоҳида пул аст.", None),
            s("Das ist im Angebot.", "Ин бо тахфиф аст.", None),
            s("Brauchen Sie eine Tüte?", "Халта лозим?", None),
        ]),
        ("Пули майда", [
            t("Hier sind fünfzig Euro.", "Мана панҷоҳ евро.", "Бипурс: пули майда доред?", "Haben Sie Kleingeld?",
              "Пули майда доред?", ["Kleingeld, bitte?"]),
            t("Nein, leider nicht.", "Не, мутаассифона.", "Бигӯ: мушкил нест", "Kein Problem.", "Мушкил нест.",
              ["Okay.", "Kein Problem, hier."]),
            t("Danke.", "Ташаккур.", "Бигӯ: мана чекатон", "Hier ist Ihr Bon.", "Мана чекатон.",
              ["Ihr Bon, bitte."]),
        ]),
        ("Нарх", [
            s("Was kostet das?", "Ин чанд пул?", None),
            s("Der Preis ist falsch.", "Нарх нодуруст аст.", None),
            s("Ich frage die Chefin.", "Аз сардор мепурсам.", None),
            s("Einen Moment, bitte.", "Як лаҳза, лутфан.", None),
            s("Ja, das stimmt.", "Ҳа, дуруст аст.", None),
            s("Jetzt stimmt es.", "Ҳоло дуруст аст.", None),
        ]),
        ("Нарх нодуруст?", [
            t("Der Preis ist falsch! Das ist im Angebot.", "Нарх нодуруст! Ин бо тахфиф аст.",
              "Бигӯ: як лаҳза, лутфан", "Einen Moment, bitte.", "Як лаҳза, лутфан.", ["Moment, bitte."]),
            t("Zwei Euro, nicht drei!", "Ду евро, на се!", "Бигӯ: ҳа, дуруст аст", "Ja, das stimmt.",
              "Ҳа, дуруст аст.", ["Das stimmt.", "Entschuldigung, das stimmt."]),
            t("Danke!", "Ташаккур!", "Бигӯ: ҳоло дуруст аст", "Jetzt stimmt es.", "Ҳоло дуруст аст.",
              ["So, jetzt stimmt es."]),
        ]),
        ("Миссия: навбат дар касса", [
            t("Guten Tag!", "Рӯз ба хайр!", "Салом гӯй ва бипурс: халта мехоҳед?", "Hallo! Brauchen Sie eine Tüte?",
              "Салом! Халта мехоҳед?", ["Guten Tag! Eine Tüte?"]),
            t("Nein, danke. Was kostet das?", "Не, ташаккур. Чанд пул?", "Бигӯ: дувоздаҳ евро", "Zwölf Euro.",
              "Дувоздаҳ евро.", ["Das macht zwölf Euro."]),
            t("Mit Karte, bitte.", "Бо корт, лутфан.", "Бигӯ: хуб, марҳамат", "Gut, bitte.", "Хуб, марҳамат.",
              ["Okay, bitte."]),
            t("Danke! Tschüss!", "Ташаккур! Хайр!", "Бигӯ: рӯзи хуш!", "Schönen Tag!", "Рӯзи хуш!",
              ["Einen schönen Tag!", "Tschüss!"]),
        ]),
    ]))

# ═════════════════════ 12. Мол дар рафҳо ═════════════════════
made.append(pack("shelves_de_tg", "Ware einräumen", "Мол дар рафҳо", "📦", 12, SV,
    "Шумо дар анбор ва толори мағоза кор мекунед: қуттиҳоро мекушоед, молро ба раф мегузоред, "
    "нарх мечаспонед ва мепурсед, ки чиз куҷо меравад.",
    [
        ("Анбор", [
            w("Regal", "раф", None),
            w("Karton", "қуттӣ", None),
            w("Lager", "анбор", None),
            w("Ware", "мол", None),
            w("Oben", "боло", None),
            w("Unten", "поён", None),
        ]),
        ("Кор дар анбор", [
            t("Die Ware ist da.", "Мол омад.", "Бипурс: ба куҷо?", "Wohin?", "Ба куҷо?", ["Wohin damit?"]),
            t("Ins Regal, bitte.", "Ба раф, лутфан.", "Бипурс: боло ё поён?", "Oben oder unten?", "Боло ё поён?",
              ["Oben?"]),
            t("Unten.", "Поён.", "Бигӯ: хуб", "Okay.", "Хуб.", ["Gut.", "Mache ich."]),
        ]),
        ("Ибораҳо", [
            s("Ins Regal", "Ба раф", None),
            s("Den Karton", "Қуттиро", None),
            s("Ganz oben", "Дар болои боло", None),
            s("Im Lager", "Дар анбор", None),
            s("Mache ich", "Мекунам", None),
            s("Schon fertig", "Аллакай тамом", None),
        ]),
        ("Қуттӣ вазнин аст", [
            t("Nimm den Karton, bitte.", "Қуттиро бигир, лутфан.", "Бигӯ: он вазнин аст", "Er ist schwer.",
              "Он вазнин аст.", ["Der Karton ist schwer."]),
            t("Ich helfe dir.", "Ба ту ёрӣ медиҳам.", "Ташаккур гӯй", "Danke!", "Ташаккур!", ["Danke schön."]),
            t("Bring ihn ins Lager.", "Онро ба анбор бубар.", "Бигӯ: мекунам", "Mache ich.", "Мекунам.",
              ["Okay.", "Sofort."]),
        ]),
        ("Кор бо мол", [
            s("Wohin kommt das?", "Ин ба куҷо меравад?", None),
            s("Das Regal ist leer.", "Раф холӣ аст.", None),
            s("Ich hole mehr Ware.", "Боз мол меорам.", None),
            s("Der Preis fehlt.", "Нарх нест.", None),
            s("Ich mache die Preise.", "Нархҳоро мечаспонам.", None),
            s("Das ist kaputt.", "Ин вайрон аст.", None),
        ]),
        ("Раф холӣ", [
            t("Das Regal ist leer!", "Раф холӣ аст!", "Бигӯ: боз мол меорам", "Ich hole mehr Ware.", "Боз мол меорам.",
              ["Ich hole Ware.", "Sofort."]),
            t("Gut. Und die Preise?", "Хуб. Ва нархҳо?", "Бигӯ: нархҳоро мечаспонам", "Ich mache die Preise.",
              "Нархҳоро мечаспонам.", ["Mache ich auch."]),
            t("Danke!", "Ташаккур!", "Бигӯ: бо хурсандӣ", "Gerne.", "Бо хурсандӣ.", ["Kein Problem."]),
        ]),
        ("Мушкил дар анбор", [
            s("Ein Glas ist kaputt.", "Як шиша шикаст.", None),
            s("Das Datum ist alt.", "Мӯҳлат гузаштааст.", None),
            s("Wir haben keine Milch.", "Мо шир надорем.", None),
            s("Was mache ich damit?", "Бо ин чӣ кунам?", None),
            s("Weg damit!", "Онро парто!", None),
            s("Ich sage es Ihnen.", "Ба шумо мегӯям.", None),
        ]),
        ("Мӯҳлат гузашт", [
            t("Was ist los?", "Чӣ шуд?", "Бигӯ: мӯҳлат гузаштааст", "Das Datum ist alt.", "Мӯҳлат гузаштааст.",
              ["Das ist alt.", "Das Datum ist vorbei."]),
            t("Oh! Wie viele?", "О! Чандто?", "Бигӯ: се", "Drei.", "Се.", ["Drei Stück."]),
            t("Weg damit, bitte.", "Онҳоро парто, лутфан.", "Бигӯ: мекунам", "Mache ich.", "Мекунам.", ["Okay."]),
        ]),
        ("Миссия: мол омад", [
            t("Hallo! Die Ware ist da.", "Салом! Мол омад.", "Бипурс: ба куҷо?", "Wohin kommt das?",
              "Ин ба куҷо меравад?", ["Wohin?"]),
            t("Ins Regal, ganz oben.", "Ба раф, дар болои боло.", "Бигӯ: мекунам", "Mache ich.", "Мекунам.",
              ["Okay.", "Sofort."]),
            t("Ist alles gut?", "Ҳама хуб аст?", "Бигӯ: як шиша шикаст", "Ein Glas ist kaputt.", "Як шиша шикаст.",
              ["Nein, ein Glas ist kaputt."]),
            t("Kein Problem. Weg damit.", "Мушкил нест. Партоб.", "Бигӯ: хуб", "Okay.", "Хуб.", ["Mache ich."]),
        ]),
    ]))

# ═════════════════════ 13. Ёрӣ ба харидор ═════════════════════
made.append(pack("shop_help_de_tg", "Kunden helfen", "Ёрӣ ба харидор", "🛒", 13, SV,
    "Харидор чизе меҷӯяд: шумо мегӯед, ки он дар кадом раф аст, андоза ё ранги дигарро мепурсед "
    "ва агар набошад, мегӯед, ки кай меояд.",
    [
        ("Мағоза", [
            w("Kunde", "харидор", None),
            w("Größe", "андоза", None),
            w("Farbe", "ранг", None),
            w("Billig", "арзон", None),
            w("Teuer", "гарон", None),
            w("Hinten", "дар қафо", None),
        ]),
        ("Ёрӣ диҳам?", [
            t("Entschuldigung!", "Бубахшед!", "Бипурс: ёрӣ диҳам?", "Kann ich helfen?", "Ёрӣ диҳам?",
              ["Ja, bitte?", "Kann ich Ihnen helfen?"]),
            t("Wo ist der Reis?", "Биринҷ куҷост?", "Бигӯ: дар қафо, тарафи чап", "Hinten links.", "Дар қафо, тарафи чап.",
              ["Da hinten.", "Hinten, links."]),
            t("Danke!", "Ташаккур!", "Бигӯ: бо хурсандӣ", "Gerne.", "Бо хурсандӣ.", ["Bitte."]),
        ]),
        ("Ибораҳо", [
            s("Hilfe nötig?", "Ёрӣ лозим?", None),
            s("Da hinten", "Он ҷо, дар қафо", None),
            s("Welche Größe?", "Кадом андоза?", None),
            s("Welche Farbe?", "Кадом ранг?", None),
            s("Leider nicht", "Мутаассифона, не", None),
            s("Mitkommen, bitte", "Бо ман биёед", None),
        ]),
        ("Андоза", [
            t("Haben Sie das in Größe M?", "Инро андозаи M доред?", "Бигӯ: як лаҳза", "Einen Moment.", "Як лаҳза.",
              ["Moment, bitte."]),
            t("Und in Blau?", "Ва кабуд?", "Бигӯ: мутаассифона, не", "Leider nicht.", "Мутаассифона, не.",
              ["Nein, leider nicht.", "Nur in Rot."]),
            t("Schade.", "Афсӯс.", "Бигӯ: бубахшед", "Entschuldigung.", "Бубахшед.", ["Das tut mir leid."]),
        ]),
        ("Ёрӣ ба харидор", [
            s("Was suchen Sie?", "Чӣ меҷӯед?", None),
            s("Das ist im Regal.", "Ин дар раф аст.", None),
            s("Kommen Sie mit, bitte.", "Бо ман биёед, лутфан.", None),
            s("Das ist billiger.", "Ин арзонтар аст.", None),
            s("Das gibt es nicht.", "Ин нест.", None),
            s("Morgen kommt neue Ware.", "Фардо моли нав меояд.", None),
        ]),
        ("Ман меҷӯям…", [
            t("Hallo! Ich suche Milch.", "Салом! Ман шир меҷӯям.", "Бигӯ: бо ман биёед, лутфан",
              "Kommen Sie mit, bitte.", "Бо ман биёед, лутфан.", ["Kommen Sie mit."]),
            t("Danke. Ist das billig?", "Ташаккур. Ин арзон аст?", "Бигӯ: ин арзонтар аст", "Das ist billiger.",
              "Ин арзонтар аст.", ["Die hier ist billiger."]),
            t("Super, danke!", "Олӣ, ташаккур!", "Бигӯ: бо хурсандӣ", "Gerne.", "Бо хурсандӣ.", ["Bitte schön."]),
        ]),
        ("Мол нест", [
            s("Das ist leider aus.", "Мутаассифона тамом шуд.", None),
            s("Morgen wieder da.", "Фардо боз ҳаст.", None),
            s("Ich frage im Lager.", "Аз анбор мепурсам.", None),
            s("Das hier ist gut.", "Ин хуб аст.", None),
            s("Nehmen Sie das.", "Инро гиред.", None),
            s("Gern geschehen.", "Арзише надорад.", None),
        ]),
        ("Тамом шуд", [
            t("Wo ist das Brot?", "Нон куҷост?", "Бигӯ: мутаассифона тамом шуд", "Das ist leider aus.",
              "Мутаассифона тамом шуд.", ["Leider kein Brot mehr."]),
            t("Und morgen?", "Ва фардо?", "Бигӯ: фардо боз ҳаст", "Morgen wieder da.", "Фардо боз ҳаст.",
              ["Morgen kommt neues Brot."]),
            t("Gut, danke!", "Хуб, ташаккур!", "Бигӯ: арзише надорад", "Gern geschehen.", "Арзише надорад.",
              ["Gerne.", "Bitte."]),
        ]),
        ("Миссия: харидори саросема", [
            t("Entschuldigung! Ich suche Reis.", "Бубахшед! Биринҷ меҷӯям.", "Бигӯ: дар қафо, тарафи чап", "Hinten links.",
              "Дар қафо, тарафи чап.", ["Da hinten links.", "Kommen Sie mit."]),
            t("Ist das der billige Reis?", "Ин биринҷи арзон аст?", "Бигӯ: ҳа, ин арзонтар аст", "Ja, das ist billiger.",
              "Ҳа, ин арзонтар аст.", ["Ja."]),
            t("Und haben Sie Brot?", "Ва нон доред?", "Бигӯ: мутаассифона тамом шуд", "Das ist leider aus.",
              "Мутаассифона тамом шуд.", ["Leider nicht.", "Morgen wieder da."]),
            t("Okay, danke!", "Хуб, ташаккур!", "Бигӯ: арзише надорад", "Gern geschehen.", "Арзише надорад.",
              ["Gerne.", "Schönen Tag!"]),
        ]),
    ]))

# ═════════════════════ 15. Фармоиш бо телефон ═════════════════════
made.append(pack("phone_order_de_tg", "Bestellung am Telefon", "Фармоиш бо телефон", "📞", 15, SV,
    "Тарабхона хӯрок ба хона мефиристад. Шумо занг қабул мекунед: фармоишро менависед, суроға ва "
    "рақами телефонро мепурсед ва мегӯед, ки хӯрок кай мерасад.",
    [
        ("Телефон", [
            w("Telefon", "телефон", None),
            w("Adresse", "суроға", None),
            w("Straße", "кӯча", None),
            w("Hausnummer", "рақами хона", None),
            w("Lieferung", "расонидан", None),
            w("Abholen", "омада гирифтан", None),
        ]),
        ("Ало!", [
            t("Hallo? Ich möchte bestellen.", "Ало? Фармоиш додан мехоҳам.", "Бигӯ: бо хурсандӣ. Чӣ мехоҳед?",
              "Gerne. Was möchten Sie?", "Бо хурсандӣ. Чӣ мехоҳед?", ["Was möchten Sie?"]),
            t("Zwei Pizza, bitte.", "Ду питса, лутфан.", "Бипурс: расонидан ё омада гирифтан?",
              "Lieferung oder abholen?", "Расонем ё омада мегиред?", ["Liefern wir?"]),
            t("Lieferung, bitte.", "Расонед, лутфан.", "Бигӯ: хуб", "Okay.", "Хуб.", ["Gut.", "Gerne."]),
        ]),
        ("Ибораҳо", [
            s("Ihre Adresse?", "Суроғаатон?", None),
            s("Welche Straße?", "Кадом кӯча?", None),
            s("Ihre Nummer?", "Рақаматон?", None),
            s("Noch einmal", "Боз як бор", None),
            s("Dreißig Minuten", "Сӣ дақиқа", None),
            s("Bis gleich", "То дидан", None),
        ]),
        ("Суроға", [
            t("Ich wohne in der Gartenstraße.", "Дар кӯчаи Гартен зиндагӣ мекунам.", "Бипурс: рақами хона?",
              "Welche Hausnummer?", "Рақами хона?", ["Und die Hausnummer?"]),
            t("Nummer zwölf.", "Рақами дувоздаҳ.", "Бипурс: рақами телефонатон?", "Ihre Telefonnummer?",
              "Рақами телефонатон?", ["Ihre Nummer, bitte?"]),
            t("Null eins fünf eins…", "Сифр як панҷ як…", "Бигӯ: боз як бор, лутфан", "Noch einmal, bitte.",
              "Боз як бор, лутфан.", ["Bitte langsam.", "Langsam, bitte."]),
        ]),
        ("Фармоиш мегирам", [
            s("Wie ist Ihre Adresse?", "Суроғаатон чист?", None),
            s("Bitte langsam.", "Оҳиста, лутфан.", None),
            s("Das dauert dreißig Minuten.", "Сӣ дақиқа мегирад.", None),
            s("Zahlen Sie bar?", "Нақд пардохт мекунед?", None),
            s("Ich wiederhole die Bestellung.", "Фармоишро такрор мекунам.", None),
            s("Danke für die Bestellung.", "Барои фармоиш ташаккур.", None),
        ]),
        ("Такрор", [
            t("Also, zwei Pizza?", "Пас, ду питса?", "Бигӯ: фармоишро такрор мекунам", "Ich wiederhole die Bestellung.",
              "Фармоишро такрор мекунам.", ["Ja, ich wiederhole."]),
            t("Ja, und eine Cola.", "Ҳа, ва як кола.", "Бигӯ: ду питса, як кола", "Zwei Pizza, eine Cola.",
              "Ду питса, як кола.", ["Okay, zwei Pizza und eine Cola."]),
            t("Richtig!", "Дуруст!", "Бигӯ: сӣ дақиқа мегирад", "Das dauert dreißig Minuten.", "Сӣ дақиқа мегирад.",
              ["Dreißig Minuten."]),
        ]),
        ("Савол аз мизоҷ", [
            s("Wie lange dauert das?", "Чӣ қадар вақт мегирад?", None),
            s("Haben Sie Halal?", "Халол доред?", None),
            s("Ist das mit Fleisch?", "Ин бо гӯшт аст?", None),
            s("Ich frage kurz.", "Зуд мепурсам.", None),
            s("Ja, das haben wir.", "Ҳа, инро дорем.", None),
            s("Leider nicht heute.", "Имрӯз мутаассифона не.", None),
        ]),
        ("Халол?", [
            t("Haben Sie Halal?", "Халол доред?", "Бигӯ: зуд мепурсам", "Ich frage kurz.", "Зуд мепурсам.",
              ["Einen Moment, ich frage."]),
            t("Und?", "Хӯш?", "Бигӯ: ҳа, мурғи халол дорем", "Ja, das haben wir.", "Ҳа, инро дорем.",
              ["Ja, Halal-Hähnchen haben wir."]),
            t("Super! Wie lange dauert das?", "Олӣ! Чӣ қадар мегирад?", "Бигӯ: сӣ дақиқа", "Dreißig Minuten.",
              "Сӣ дақиқа.", ["Das dauert dreißig Minuten."]),
        ]),
        ("Миссия: занги фармоиш", [
            t("Hallo? Ich möchte bestellen.", "Ало? Фармоиш медиҳам.", "Бигӯ: бо хурсандӣ. Чӣ мехоҳед?",
              "Gerne. Was möchten Sie?", "Бо хурсандӣ. Чӣ мехоҳед?", ["Was möchten Sie?"]),
            t("Eine Pizza mit Hähnchen.", "Як питса бо мурғ.", "Бипурс: суроғаатон чист?", "Wie ist Ihre Adresse?",
              "Суроғаатон чист?", ["Ihre Adresse, bitte?"]),
            t("Gartenstraße zwölf.", "Кӯчаи Гартен, дувоздаҳ.", "Бипурс: нақд пардохт мекунед?", "Zahlen Sie bar?",
              "Нақд пардохт мекунед?", ["Bar oder Karte?"]),
            t("Ja, bar.", "Ҳа, нақд.", "Бигӯ: сӣ дақиқа мегирад, ташаккур", "Dreißig Minuten. Danke!",
              "Сӣ дақиқа. Ташаккур!", ["Das dauert dreißig Minuten.", "Danke für die Bestellung."]),
        ]),
    ], mission_mode="call"))

# ═════════════════════ 17. Тозакунӣ ва бастан ═════════════════════
made.append(pack("closing_de_tg", "Putzen und schließen", "Тозакунӣ ва бастан", "🧹", 17, SV,
    "Охири рӯз: мизҳоро тоза мекунед, фаршро мешӯед, партовро мебаред, чароғҳоро хомӯш мекунед "
    "ва ба сардор мегӯед, ки ҳама тайёр аст.",
    [
        ("Тозакунӣ", [
            w("Putzen", "тоза кардан", None),
            w("Boden", "фарш", None),
            w("Müll", "партов", None),
            w("Licht", "чароғ", None),
            w("Tür", "дар", None),
            w("Schließen", "бастан", None),
        ]),
        ("Вақти бастан", [
            t("Wir schließen bald.", "Ба наздикӣ мебандем.", "Бипурс: чӣ кор кунам?", "Was mache ich?", "Чӣ кор кунам?",
              ["Was soll ich machen?"]),
            t("Putz bitte die Tische.", "Мизҳоро тоза кун.", "Бигӯ: хуб", "Okay.", "Хуб.", ["Mache ich.", "Gut."]),
            t("Und dann den Boden.", "Баъд фаршро.", "Бигӯ: мекунам", "Mache ich.", "Мекунам.", ["Okay.", "Gut."]),
        ]),
        ("Ибораҳо", [
            s("Die Tische", "Мизҳо", None),
            s("Den Boden", "Фаршро", None),
            s("Licht aus", "Чароғ хомӯш", None),
            s("Tür zu", "Дар баста", None),
            s("Alles sauber", "Ҳама тоза", None),
            s("Bis morgen", "То фардо", None),
        ]),
        ("Ҳама тоза?", [
            t("Sind die Tische sauber?", "Мизҳо тозаанд?", "Бигӯ: ҳа, ҳама тоза", "Ja, alles sauber.",
              "Ҳа, ҳама тоза.", ["Ja.", "Ja, fertig."]),
            t("Und der Müll?", "Ва партов?", "Бигӯ: ҳозир", "Sofort.", "Ҳозир.", ["Mache ich jetzt."]),
            t("Danke!", "Ташаккур!", "Бигӯ: бо хурсандӣ", "Gerne.", "Бо хурсандӣ.", ["Kein Problem."]),
        ]),
        ("Кор дар охири рӯз", [
            s("Ich putze die Küche.", "Ошхонаро тоза мекунам.", None),
            s("Ich bringe den Müll.", "Партовро мебарам.", None),
            s("Der Boden ist nass.", "Фарш тар аст.", None),
            s("Wo ist der Schlüssel?", "Калид куҷост?", None),
            s("Ich mache aus.", "Хомӯш мекунам.", None),
            s("Alles ist fertig.", "Ҳама тайёр аст.", None),
        ]),
        ("Калид", [
            t("Bist du fertig?", "Тамом кардӣ?", "Бигӯ: ҳа, ҳама тайёр аст", "Ja, alles ist fertig.",
              "Ҳа, ҳама тайёр аст.", ["Ja, fertig."]),
            t("Gut. Schließ bitte die Tür.", "Хуб. Дарро бибанд.", "Бипурс: калид куҷост?", "Wo ist der Schlüssel?",
              "Калид куҷост?", ["Der Schlüssel?"]),
            t("Hier.", "Ин ҷо.", "Ташаккур гӯй", "Danke.", "Ташаккур.", ["Danke schön."]),
        ]),
        ("Хайрухуш", [
            s("Darf ich jetzt gehen?", "Ҳоло рафта метавонам?", None),
            s("Bis morgen um acht.", "То фардо соати ҳашт.", None),
            s("Schönen Abend!", "Шоми хуш!", None),
            s("Ich bin müde.", "Ман хаста ҳастам.", None),
            s("Heute war viel los.", "Имрӯз серкор буд.", None),
            s("Gute Nacht!", "Шаб ба хайр!", None),
        ]),
        ("Рафтан мумкин?", [
            t("Gute Arbeit heute!", "Имрӯз хуб кор кардӣ!", "Бипурс: ҳоло рафта метавонам?", "Darf ich jetzt gehen?",
              "Ҳоло рафта метавонам?", ["Kann ich gehen?"]),
            t("Ja, natürlich.", "Ҳа, албатта.", "Бигӯ: то фардо", "Bis morgen!", "То фардо!", ["Tschüss!"]),
            t("Bis morgen um acht.", "То фардо соати ҳашт.", "Бигӯ: шоми хуш!", "Schönen Abend!", "Шоми хуш!",
              ["Gute Nacht!", "Tschüss, schönen Abend!"]),
        ]),
        ("Миссия: охири навбат", [
            t("Wir schließen. Hilfst du?", "Мебандем. Ёрӣ медиҳӣ?", "Бигӯ: ҳа, чӣ кор кунам?", "Ja, was mache ich?",
              "Ҳа, чӣ кор кунам?", ["Ja, natürlich."]),
            t("Putz die Küche und den Boden.", "Ошхона ва фаршро тоза кун.", "Бигӯ: мекунам", "Mache ich.", "Мекунам.",
              ["Okay.", "Sofort."]),
            t("Fertig?", "Тамом?", "Бигӯ: ҳа, ҳама тайёр аст", "Ja, alles ist fertig.", "Ҳа, ҳама тайёр аст.",
              ["Ja, alles sauber."]),
            t("Danke! Bis morgen!", "Ташаккур! То фардо!", "Бигӯ: шоми хуш!", "Schönen Abend!", "Шоми хуш!",
              ["Bis morgen!", "Gute Nacht!"]),
        ]),
    ]))

# ═════════════════════ 18. Хӯрок ва аллергия ═════════════════════
made.append(pack("allergy_de_tg", "Halal und Allergien", "Хӯрок ва аллергия", "🥜", 18, SV,
    "Меҳмон мепурсад, ки дар хӯрок чӣ ҳаст: гӯшти хук, чормағз, шир. Шумо аз ошпаз мепурсед ва "
    "дақиқ ҷавоб медиҳед, то меҳмон бемор нашавад.",
    [
        ("Таркиб", [
            w("Nüsse", "чормағз", None),
            w("Milch", "шир", None),
            w("Ei", "тухм", None),
            w("Allergie", "аллергия", None),
            w("Fleisch", "гӯшт", None),
            w("Vegetarisch", "бе гӯшт", None),
        ]),
        ("Аллергия дорам", [
            t("Ich habe eine Allergie.", "Ман аллергия дорам.", "Бипурс: ба чӣ?", "Gegen was?", "Ба чӣ?",
              ["Was für eine Allergie?"]),
            t("Gegen Nüsse.", "Ба чормағз.", "Бигӯ: аз ошпаз мепурсам", "Ich frage den Koch.", "Аз ошпаз мепурсам.",
              ["Einen Moment, ich frage."]),
            t("Danke.", "Ташаккур.", "Бигӯ: як лаҳза", "Einen Moment.", "Як лаҳза.", ["Moment, bitte."]),
        ]),
        ("Ибораҳо", [
            s("Ohne Nüsse", "Бе чормағз", None),
            s("Mit Milch", "Бо шир", None),
            s("Kein Schwein", "Гӯшти хук нест", None),
            s("Nur Gemüse", "Танҳо сабзавот", None),
            s("Ganz sicher", "Комилан дуруст", None),
            s("Kein Ei", "Тухм нест", None),
        ]),
        ("Гӯшти хук?", [
            t("Ist da Schwein drin?", "Дар ин гӯшти хук ҳаст?", "Бигӯ: не, гӯшти хук нест", "Nein, kein Schwein.",
              "Не, гӯшти хук нест.", ["Nein, das ist Hähnchen."]),
            t("Sind Sie sicher?", "Боварӣ доред?", "Бигӯ: ҳа, комилан дуруст", "Ja, ganz sicher.", "Ҳа, комилан дуруст.",
              ["Ja, sicher.", "Ja, der Koch sagt das."]),
            t("Gut, danke.", "Хуб, ташаккур.", "Бигӯ: бо хурсандӣ", "Gerne.", "Бо хурсандӣ.", ["Bitte."]),
        ]),
        ("Ман аз ошпаз мепурсам", [
            s("Ist das ohne Nüsse?", "Ин бе чормағз аст?", None),
            s("Das hat Milch.", "Ин шир дорад.", None),
            s("Das ist vegetarisch.", "Ин бе гӯшт аст.", None),
            s("Das ist Rindfleisch.", "Ин гӯшти гов аст.", None),
            s("Ich frage noch einmal.", "Боз як бор мепурсам.", None),
            s("Das ist nicht gut.", "Ин хуб нест.", None),
        ]),
        ("Ба ошпаз", [
            t("Ja? Was ist?", "Ҳа? Чӣ гап?", "Бипурс: ин бе чормағз аст?", "Ist das ohne Nüsse?", "Ин бе чормағз аст?",
              ["Sind da Nüsse drin?"]),
            t("Nein, da sind Nüsse drin.", "Не, дар он чормағз ҳаст.", "Бигӯ: меҳмон аллергия дорад",
              "Der Gast hat eine Allergie.", "Меҳмон аллергия дорад.", ["Der Gast hat Allergie."]),
            t("Dann nimm den Salat.", "Пас салатро бигир.", "Бигӯ: хуб, ташаккур", "Gut, danke.", "Хуб, ташаккур.",
              ["Okay."]),
        ]),
        ("Ҷавоб ба меҳмон", [
            s("Das hat leider Nüsse.", "Мутаассифона чормағз дорад.", None),
            s("Der Salat ist gut.", "Салат хуб аст.", None),
            s("Ohne Milch geht.", "Бе шир мешавад.", None),
            s("Das ist Halal.", "Ин халол аст.", None),
            s("Ich bringe die Liste.", "Рӯйхатро меорам.", None),
            s("Guten Appetit!", "Ош шавад!", None),
        ]),
        ("Бехатар", [
            t("Und der Kuchen?", "Ва пирожни?", "Бигӯ: мутаассифона чормағз дорад", "Das hat leider Nüsse.",
              "Мутаассифона чормағз дорад.", ["Leider mit Nüssen."]),
            t("Was ist ohne Nüsse?", "Чӣ бе чормағз аст?", "Бигӯ: салат хуб аст", "Der Salat ist gut.", "Салат хуб аст.",
              ["Der Salat, ohne Nüsse."]),
            t("Gut, einen Salat.", "Хуб, як салат.", "Бигӯ: ош шавад!", "Guten Appetit!", "Ош шавад!",
              ["Gerne, sofort."]),
        ]),
        ("Миссия: меҳмони эҳтиёткор", [
            t("Hallo! Ist das Halal?", "Салом! Ин халол аст?", "Бигӯ: ҳа, ин халол аст", "Ja, das ist Halal.",
              "Ҳа, ин халол аст.", ["Ja, Halal-Hähnchen."]),
            t("Ich habe eine Allergie gegen Milch.", "Ман ба шир аллергия дорам.", "Бигӯ: аз ошпаз мепурсам",
              "Ich frage den Koch.", "Аз ошпаз мепурсам.", ["Einen Moment, ich frage."]),
            t("Und?", "Хӯш?", "Бигӯ: бе шир мешавад", "Ohne Milch geht.", "Бе шир мешавад.",
              ["Ja, ohne Milch geht das."]),
            t("Super, danke!", "Олӣ, ташаккур!", "Бигӯ: бо хурсандӣ", "Gerne.", "Бо хурсандӣ.", ["Guten Appetit!"]),
        ]),
    ]))

# ═════════════════════ 19. Рӯзи серкор ═════════════════════
made.append(pack("rush_de_tg", "Viel los im Café", "Рӯзи серкор", "⏱️", 19, SV,
    "Дар қаҳвахона навбати дароз аст: шумо тез кор мекунед, ба меҳмонон мегӯед, ки интизор шаванд, "
    "аз ҳамкор ёрӣ мехоҳед ва ба сардор мегӯед, ки чизе тамом шуд.",
    [
        ("Серкор", [
            w("Schnell", "тез", None),
            w("Warten", "интизор шудан", None),
            w("Kollege", "ҳамкор", "Зан: «Kollegin»."),
            w("Voll", "пур", None),
            w("Becher", "истакони қоғазӣ", None),
            w("Gleich", "ҳозир", None),
        ]),
        ("Навбат дароз", [
            t("Hallo, ein Kaffee!", "Салом, як қаҳва!", "Бигӯ: як лаҳза, лутфан", "Einen Moment, bitte.",
              "Як лаҳза, лутфан.", ["Moment, bitte."]),
            t("Bitte schnell!", "Лутфан тез!", "Бигӯ: ҳозир", "Gleich!", "Ҳозир!", ["Sofort!", "Kommt gleich."]),
            t("Danke.", "Ташаккур.", "Бигӯ: мана, марҳамат", "Bitte schön.", "Марҳамат.", ["Hier, bitte."]),
        ]),
        ("Ибораҳо", [
            s("Bitte warten", "Лутфан интизор шавед", None),
            s("Kommt gleich", "Ҳозир меояд", None),
            s("Zum Mitnehmen?", "Барои бурдан?", None),
            s("Hier trinken?", "Ин ҷо менӯшед?", None),
            s("Der Nächste", "Навбатӣ", None),
            s("Hilf mir!", "Ёрӣ деҳ!", None),
        ]),
        ("Барои бурдан?", [
            t("Einen Tee, bitte.", "Як чой, лутфан.", "Бипурс: барои бурдан?", "Zum Mitnehmen?", "Барои бурдан?",
              ["Hier oder zum Mitnehmen?"]),
            t("Ja, zum Mitnehmen.", "Ҳа, барои бурдан.", "Бигӯ: ҳозир меояд", "Kommt gleich.", "Ҳозир меояд.",
              ["Gleich!", "Sofort."]),
            t("Danke!", "Ташаккур!", "Бигӯ: навбатӣ, лутфан", "Der Nächste, bitte!", "Навбатӣ, лутфан!",
              ["Wer ist der Nächste?"]),
        ]),
        ("Тез кор мекунам", [
            s("Heute ist viel los.", "Имрӯз серкор аст.", None),
            s("Bitte warten Sie kurz.", "Лутфан каме интизор шавед.", None),
            s("Kannst du mir helfen?", "Ба ман ёрӣ медиҳӣ?", "Ба ҳамкор («du»)."),
            s("Die Becher sind alle.", "Истаконҳо тамом шуданд.", None),
            s("Ich mache den Kaffee.", "Ман қаҳва тайёр мекунам.", None),
            s("Du machst die Kasse.", "Ту дар касса бош.", None),
        ]),
        ("Бо ҳамкор", [
            t("Viel los heute!", "Имрӯз серкор!", "Бипурс: ба ман ёрӣ медиҳӣ?", "Kannst du mir helfen?",
              "Ба ман ёрӣ медиҳӣ?", ["Hilf mir, bitte!"]),
            t("Ja, klar! Was mache ich?", "Ҳа, албатта! Чӣ кунам?", "Бигӯ: ту дар касса бош", "Du machst die Kasse.",
              "Ту дар касса бош.", ["Mach du die Kasse."]),
            t("Und du?", "Ва ту?", "Бигӯ: ман қаҳва тайёр мекунам", "Ich mache den Kaffee.", "Ман қаҳва тайёр мекунам.",
              ["Ich mache Kaffee."]),
        ]),
        ("Чизе тамом шуд", [
            s("Die Milch ist alle.", "Шир тамом шуд.", None),
            s("Wir brauchen Becher.", "Ба мо истакон лозим.", None),
            s("Ich hole sie schnell.", "Зуд меорам.", None),
            s("Das dauert fünf Minuten.", "Ин панҷ дақиқа мегирад.", None),
            s("Danke fürs Warten.", "Барои интизорӣ ташаккур.", None),
            s("Der Nächste, bitte!", "Навбатӣ, лутфан!", None),
        ]),
        ("Ба сардор", [
            t("Was ist los?", "Чӣ шуд?", "Бигӯ: шир тамом шуд", "Die Milch ist alle.", "Шир тамом шуд.",
              ["Wir haben keine Milch."]),
            t("Im Lager ist mehr.", "Дар анбор боз ҳаст.", "Бигӯ: зуд меорам", "Ich hole sie schnell.", "Зуд меорам.",
              ["Ich hole Milch."]),
            t("Danke, gut gemacht!", "Ташаккур, офарин!", "Бигӯ: бо хурсандӣ", "Gerne!", "Бо хурсандӣ!",
              ["Kein Problem."]),
        ]),
        ("Миссия: соати серкор", [
            t("Zwei Kaffee, bitte!", "Ду қаҳва, лутфан!", "Бипурс: барои бурдан?", "Zum Mitnehmen?", "Барои бурдан?",
              ["Hier oder zum Mitnehmen?"]),
            t("Ja. Schnell, bitte!", "Ҳа. Тез, лутфан!", "Бигӯ: лутфан каме интизор шавед", "Bitte warten Sie kurz.",
              "Лутфан каме интизор шавед.", ["Einen Moment, bitte."]),
            t("Wie lange?", "Чӣ қадар?", "Бигӯ: панҷ дақиқа", "Fünf Minuten.", "Панҷ дақиқа.",
              ["Das dauert fünf Minuten."]),
            t("Okay.", "Хуб.", "Бигӯ: барои интизорӣ ташаккур", "Danke fürs Warten.", "Барои интизорӣ ташаккур.",
              ["Danke!", "Kommt gleich!"]),
        ]),
    ]))

# ═════════════════════ 20. Ҷадвали кор ═════════════════════
made.append(pack("schedule_de_tg", "Der Dienstplan", "Ҷадвали кор", "🗓️", 20, SV,
    "Шумо ҷадвали корро бо сардор муҳокима мекунед: кадом рӯзҳо ва соатҳо кор мекунед, рӯзи "
    "истироҳат мепурсед ва навбатро бо ҳамкор иваз мекунед.",
    [
        ("Ҷадвал", [
            w("Dienstplan", "ҷадвали кор", None),
            w("Schicht", "навбат (смена)", None),
            w("Frei", "озод, рӯзи истироҳат", None),
            w("Woche", "ҳафта", None),
            w("Wochenende", "рӯзҳои истироҳат", None),
            w("Tauschen", "иваз кардан", None),
        ]),
        ("Кай кор мекунам?", [
            t("Hier ist der Dienstplan.", "Мана ҷадвали кор.", "Бипурс: ман кай кор мекунам?", "Wann arbeite ich?",
              "Ман кай кор мекунам?", ["Wann bin ich dran?"]),
            t("Montag und Dienstag.", "Душанбе ва сешанбе.", "Бипурс: соати чанд?", "Um wie viel Uhr?", "Соати чанд?",
              ["Wann genau?"]),
            t("Von acht bis vier.", "Аз ҳашт то чор.", "Бигӯ: хуб, ташаккур", "Gut, danke.", "Хуб, ташаккур.",
              ["Okay, danke."]),
        ]),
        ("Ибораҳо", [
            s("Von acht", "Аз ҳашт", None),
            s("Bis vier", "То чор", None),
            s("Am Wochenende", "Дар охири ҳафта", None),
            w("Frühschicht", "навбати субҳ", None),
            w("Spätschicht", "навбати шом", None),
            s("Nächste Woche", "Ҳафтаи оянда", None),
        ]),
        ("Рӯзи истироҳат", [
            t("Arbeitest du am Samstag?", "Шанбе кор мекунӣ?", "Бигӯ: не, озодам", "Nein, ich bin frei.",
              "Не, озодам.", ["Nein, frei.", "Nein."]),
            t("Und am Sonntag?", "Ва якшанбе?", "Бигӯ: ҳа, навбати шом", "Ja, Spätschicht.", "Ҳа, навбати шом.",
              ["Ja, ich arbeite.", "Ja."]),
            t("Okay, danke.", "Хуб, ташаккур.", "Бигӯ: бо хурсандӣ", "Gerne.", "Бо хурсандӣ.", ["Bitte."]),
        ]),
        ("Ҷадвали ман", [
            s("Ich arbeite am Montag.", "Ман душанбе кор мекунам.", None),
            s("Ich habe Frühschicht.", "Ман навбати субҳ дорам.", None),
            s("Freitags kann ich nicht.", "Ҷумъаҳо наметавонам.", None),
            own("Ich bin am ___ frei.", "Ман рӯзи ___ озодам.", "Рӯзи истироҳати худро гӯед.",
                "Wann bist du frei?", "Кай озодӣ?", "Рӯзи озоди худро гӯед"),
            s("Kann ich tauschen?", "Иваз карда метавонам?", None),
            s("Wie viele Stunden?", "Чанд соат?", None),
        ]),
        ("Ҷумъа наметавонам", [
            t("Du arbeitest am Freitag.", "Ту ҷумъа кор мекунӣ.", "Бигӯ: ҷумъа наметавонам",
              "Am Freitag kann ich nicht.", "Ҷумъа наметавонам.", ["Freitag geht leider nicht."]),
            t("Warum nicht?", "Чаро?", "Бигӯ: ман ба масҷид меравам", "Ich gehe in die Moschee.",
              "Ман ба масҷид меравам.", ["Ich habe einen Termin."]),
            t("Okay. Dann Samstag?", "Хуб. Пас шанбе?", "Бигӯ: ҳа, шанбе мешавад", "Ja, Samstag geht.",
              "Ҳа, шанбе мешавад.", ["Ja, gerne.", "Samstag ist gut."]),
        ]),
        ("Иваз бо ҳамкор", [
            s("Tauschst du mit mir?", "Бо ман иваз мекунӣ?", None),
            s("Du hast Montag frei.", "Ту душанбе озодӣ.", None),
            s("Ich arbeite für dich.", "Ман ба ҷои ту кор мекунам.", None),
            s("Ich frage den Chef.", "Аз сардор мепурсам.", None),
            s("Das ist okay.", "Ин хуб аст.", None),
            s("Danke, Kollege!", "Ташаккур, ҳамкор!", None),
        ]),
        ("Навбатро иваз кунем?", [
            t("Was ist los?", "Чӣ гап?", "Бипурс: бо ман иваз мекунӣ?", "Tauschst du mit mir?",
              "Бо ман иваз мекунӣ?", ["Können wir tauschen?"]),
            t("Wann?", "Кай?", "Бигӯ: ҷумъа", "Am Freitag.", "Ҷумъа.", ["Freitag."]),
            t("Ja, das geht.", "Ҳа, мешавад.", "Бигӯ: ташаккур, ҳамкор!", "Danke, Kollege!", "Ташаккур, ҳамкор!",
              ["Super, danke!", "Danke dir!"]),
        ]),
        ("Миссия: ҷадвали ҳафта", [
            t("Hallo! Hier ist der neue Dienstplan.", "Салом! Мана ҷадвали нав.", "Бипурс: ман кай кор мекунам?",
              "Wann arbeite ich?", "Ман кай кор мекунам?", ["Wann bin ich dran?"]),
            t("Freitag und Samstag, Spätschicht.", "Ҷумъа ва шанбе, навбати шом.", "Бигӯ: ҷумъа наметавонам",
              "Am Freitag kann ich nicht.", "Ҷумъа наметавонам.", ["Freitag geht leider nicht."]),
            t("Hmm. Und am Montag?", "Ҳм. Ва душанбе?", "Бигӯ: ҳа, душанбе мешавад", "Ja, Montag geht.",
              "Ҳа, душанбе мешавад.", ["Ja, Montag ist gut."]),
            t("Gut, dann Montag.", "Хуб, пас душанбе.", "Ташаккур гӯй", "Vielen Dank!", "Ташаккури зиёд!",
              ["Danke schön!", "Super, danke!"]),
        ]),
    ]))

finish(made)
