"""АНГЛИСӢ → тоҷикӣ, «Гуфтор» A1 — ИЛОВА (28.09.2026).

1. «Сохтмон»: 3 вазъияти охир (18–20) — либоси корӣ, санҷиши кор, соатҳо ва табел.
   Роҳи сохтмон: 17 → 20 вазъият.
2. Нишаи «Таҳсил» (`study`): 11 вазъият. Бо 5 вазъияти умумӣ — роҳи 16 вазъият.
   Тартиб байни вазъиятҳои умумӣ (1 салом, 6 духтур, 10 бозор, 14 иҷора, 16 ҳуҷҷат).
   Касб («{job}») барои `study` — «a student».

Ҳамон қоидаҳо (`_en_packs_lib.py`): транскрипсия ҳатмӣ, зина ≤2/≤2/≤4/≤8 калима.
Аз ҷузвдони backend: python prisma/_en-a1-more-packs.py
"""
from _en_packs_lib import *  # noqa: F401,F403

EXTRA.update({
    # сохтмон
    'gloves': 'гловз', 'goggles': 'гогэлз', 'vest': 'вест', 'vests': 'вестс', 'boots': 'бутс',
    'mask': 'маск', 'size': 'сайз', 'wear': 'веэр', 'safety': 'сейфтӣ', 'dusty': 'дастӣ',
    'loud': 'лауд', 'earplugs': 'ирплагз', 'these': 'ҙиз', 'big': 'биг', 'forty': 'фортӣ',
    'check': 'чек', 'wrong': 'ронг', 'finished': 'финишт', 'perfect': 'пёрфект', 'like': 'лайк',
    'show': 'шоу', 'looks': 'лукс', 'redo': 'ридӯ', 'mistake': 'мистейк', 'minutes': 'минитс',
    'ready': 'редӣ', 'timesheet': 'таймшит', 'sign': 'сайн', 'finish': 'финиш', 'started': 'стартид',
    'worked': 'вёркт', 'forgot': 'фэргот', 'also': 'олсоу', 'had': 'ҳэд', 'thirty': 'ҫёртӣ',
    'checking': 'чекинг', 'out': 'аут', 'put': 'пут', 'one': 'ван', 'more': 'мор', 'showing': 'шоуинг',
    # таҳсил
    'student': 'стюдэнт', 'university': 'юнивёрситӣ', 'suitcase': 'сюткейс', 'study': 'стадӣ',
    'studying': 'стадиинг', 'clothes': 'клоуз', 'welcome': 'велкам', 'taxi': 'тэксӣ', 'city': 'ситӣ',
    'missing': 'мисинг', 'state': 'стейт', 'office': 'офис', 'form': 'форм', 'photo': 'фоутоу',
    'photos': 'фоутоуз', 'copy': 'копӣ', 'course': 'корс', 'surname': 'сёрнейм', 'english': 'инглиш',
    'free': 'фрӣ', 'room': 'рум', 'twelve': 'твелв', 'dorm': 'дорм', 'roommate': 'руммейт',
    'bed': 'бед', 'quiet': 'квайэт', 'hot': 'ҳот', 'lost': 'лост', 'close': 'клоуз', 'use': 'юз',
    'laundry': 'лондрӣ', 'cook': 'кук', 'teacher': 'тичэр', 'book': 'бук', 'books': 'букс',
    'page': 'пейдж', 'question': 'квесчэн', 'homework': 'ҳоумвёрк', 'mean': 'мин', 'spell': 'спел',
    'know': 'ноу', 'difficult': 'дификэлт', 'easy': 'изӣ', 'tuesday': 'тюздей', 'wednesday': 'вензей',
    'thursday': 'ҫёрздей', 'class': 'клэс', 'cancelled': 'кэнсэлд', 'library': 'лайбрэрӣ',
    'borrow': 'бороу', 'return': 'ритёрн', 'computer': 'кэмпютэр', 'printer': 'принтэр',
    'print': 'принт', 'due': 'дю', 'open': 'оупэн', 'doesn\'t': 'дазнт', 'only': 'оунлӣ',
    'classmate': 'клэсмейт', 'country': 'кантрӣ', 'language': 'лэнгвидж', 'coffee': 'кофӣ',
    'idea': 'айдиэ', 'after': 'эфтэр', 'tajik': 'таҷик', 'russian': 'рашэн', 'business': 'бизнис',
    'medicine': 'медсин', 'seat': 'сит', 'sit': 'сит', 'phone': 'фоун', 'email': 'имейл',
    'explain': 'иксплейн', 'clear': 'клир', 'was': 'воз', 'missed': 'мист', 'time': 'тайм',
    'exam': 'игзэм', 'test': 'тест', 'grade': 'грейд', 'pass': 'пэс', 'passed': 'пэст', 'pen': 'пен',
    'luck': 'лак', 'paper': 'пейпэр', 'correct': 'кэрект', 'best': 'бест', 'try': 'трай',
    'sandwich': 'сэндвич', 'soup': 'суп', 'juice': 'джус', 'menu': 'меню', 'hungry': 'ҳангрӣ',
    'chicken': 'чикин', 'sugar': 'шугэр', 'meat': 'мит', 'pork': 'порк', 'discount': 'дискаунт',
    "i'd": 'айд', 'cold': 'коулд', 'napkins': 'нэпкинз', 'bank': 'бэнк', 'account': 'экаунт',
    'internet': 'интэрнет', 'sim': 'сим', 'atm': 'эй ти эм', 'pin': 'пин', 'plan': 'плэн',
    'large': 'лардж', 'go': 'гоу', 'hours': 'ауэрз', 'meet': 'мит', 'monday': 'мандей', 'miss': 'мис', 'weeks': 'викс',
    'moment': 'моумэнт', "wasn't": 'вознт',
})

made = []
B = ["build"]
S = ["study"]

# ═════════════════════ 18. Либоси корӣ (сохтмон) ═════════════════════
made.append(pack("gear_en_tg", "Work gear", "Либоси корӣ", "🦺", 18, B,
    "Дар объект бе либоси муҳофизатӣ кор кардан мумкин нест: каска, дастпӯшак, айнак, "
    "жилет, мӯза. Шумо мепурсед, андоза мегӯед ва чизи лозимиро мегиред.",
    [
        ("Либоси муҳофизатӣ", [
            w("Gloves", "дастпӯшак", None),
            w("Goggles", "айнаки муҳофизатӣ", None),
            w("Vest", "жилет", "Жилети дурахшон — барои он ки шуморо бубинанд."),
            w("Boots", "мӯзаи корӣ", None),
            w("Mask", "ниқоб", None),
            w("Helmet", "каска", None),
        ]),
        ("Чӣ лозим?", [
            t("What do you need for your hands?", "Барои дастҳо чӣ лозим?", "Бигӯ: дастпӯшак",
              "Gloves.", "Дастпӯшак.", ["Some gloves.", "I need gloves."], "Кӯтоҳ ҷавоб диҳед."),
            t("What goes on your head?", "Ба сар чӣ мепӯшанд?", "Бигӯ: каска", "A helmet.", "Каска.",
              ["Helmet.", "The helmet."]),
            t("It's dusty. What do you need?", "Чанг аст. Чӣ лозим?", "Бигӯ: ниқоб", "A mask.", "Ниқоб.",
              ["Mask.", "I need a mask."]),
        ]),
        ("Андоза", [
            s("My gloves", "Дастпӯшаки ман", None),
            s("Your helmet", "Каскаи ту", None),
            w("Size", "андоза", None),
            s("What size?", "Чӣ андоза?", None),
            w("Big", "калон", None),
            s("Safety first", "Аввал бехатарӣ", None),
        ]),
        ("Каскаатро пӯш!", [
            t("Where are your gloves?", "Дастпӯшакҳоят куҷо?", "Бигӯ: дастпӯшаки ман ин ҷо",
              "My gloves are here.", "Дастпӯшаки ман ин ҷо.", ["Here.", "They're here."]),
            t("Put on your helmet!", "Каскаатро пӯш!", "Бигӯ: хуб, албатта", "Okay, sure.", "Хуб, албатта.",
              ["Sure.", "Okay."]),
            t("New boots? What size?", "Мӯзаи нав? Чӣ андоза?", "Бигӯ: чил", "Forty.", "Чил.",
              ["Size forty.", "40."]),
        ]),
        ("Ман мепурсам", [
            s("I don't have gloves.", "Ман дастпӯшак надорам.", None,
              swaps=["gloves|дастпӯшак", "boots|мӯза", "goggles|айнак"]),
            s("Where are the vests?", "Жилетҳо куҷоянд?", None),
            s("These are too big.", "Инҳо хеле калонанд.", None),
            s("A mask, please.", "Ниқоб, лутфан.", None),
            s("Size forty, please.", "Андозаи чил, лутфан.", None),
            w("Wear", "пӯшидан", None),
        ]),
        ("Жилет куҷост?", [
            t("Hey! Where is your vest?", "Эй! Жилетат куҷост?", "Бигӯ: жилет надорам",
              "I don't have a vest.", "Ман жилет надорам.", ["No vest.", "I don't have one."]),
            t("Go get one. Take the orange one.", "Рав як дона гир. Норанҷиашро гир.",
              "Бипурс: жилетҳо куҷоянд?", "Where are the vests?", "Жилетҳо куҷоянд?", ["Where?", "The vests?"]),
            t("In the trailer.", "Дар вагонча.", "Бигӯ: фаҳмидам, ташаккур", "Got it, thanks.",
              "Фаҳмидам, ташаккур.", ["Thanks.", "Okay, thank you."]),
        ]),
        ("Чанг ва садо", [
            w("Dusty", "чангнок", None),
            s("It's very dusty.", "Хеле чанг аст.", None),
            w("Loud", "баланд (пурсадо)", None),
            s("It's too loud.", "Садо хеле баланд аст.", None),
            w("Earplugs", "гӯшпӯшак", None),
            s("I need earplugs.", "Ба ман гӯшпӯшак лозим.", None),
        ]),
        ("Имрӯз бетон мебурем", [
            t("We're cutting concrete today.", "Имрӯз бетон мебурем.", "Бигӯ: хеле чанг, ба ман ниқоб лозим",
              "It's very dusty. I need a mask.", "Хеле чанг. Ба ман ниқоб лозим.", ["I need a mask.", "Dusty. A mask, please."]),
            t("Here's a mask. Anything else?", "Ана ниқоб. Боз чизе?", "Бигӯ: садо баланд, гӯшпӯшак лозим",
              "It's too loud. I need earplugs.", "Садо баланд. Ба ман гӯшпӯшак лозим.", ["I need earplugs.", "Earplugs, please."]),
            t("Good. Safety first!", "Хуб. Аввал бехатарӣ!", "Бигӯ: ҳа, аввал бехатарӣ",
              "Yes, safety first!", "Ҳа, аввал бехатарӣ!", ["Safety first!", "Yes."]),
        ]),
        ("Миссия: санҷиши бехатарӣ", [
            t("Stop! Where is your helmet?", "Ист! Каскаат куҷост?", "Бигӯ: бубахшед. ҳозир",
              "Sorry. Right now.", "Бубахшед. Ҳозир.", ["Sorry, I'll put it on.", "One moment, please."]),
            t("And your gloves?", "Дастпӯшакат чӣ?", "Бигӯ: дастпӯшак надорам",
              "I don't have gloves.", "Ман дастпӯшак надорам.", ["No gloves.", "I don't have any."]),
            t("Take these. Are they okay?", "Инҳоро гир. Мувофиқанд?", "Бигӯ: хеле калонанд",
              "These are too big.", "Инҳо хеле калонанд.", ["Too big.", "They're too big."]),
            t("Try the small ones.", "Хурдашро пӯш.", "Бигӯ: хуб, ташаккур", "Okay, thank you.", "Хуб, ташаккур.",
              ["Thanks.", "Okay, thanks."]),
        ]),
    ]))

# ═════════════════════ 19. Санҷиши кор (сохтмон) ═════════════════════
made.append(pack("check_en_tg", "Checking the work", "Санҷиши кор", "✅", 19, B,
    "Бригадир кори шуморо месанҷад: рост аст ё не, аз нав кардан лозим аст ё тайёр. Шумо "
    "мепурсед «ҳамин хел?», хоҳиш мекунед нишон диҳад ва хатоятонро ислоҳ мекунед.",
    [
        ("Санҷиш", [
            w("Check", "санҷидан", None),
            w("Wrong", "нодуруст", None),
            w("Straight", "рост (ҳамвор)", None),
            w("Again", "боз", None),
            w("Finished", "тамом", None),
            w("Perfect", "олӣ", None),
        ]),
        ("Тайёр?", [
            t("Is the wall finished?", "Девор тамом шуд?", "Бигӯ: тамом", "Finished.", "Тамом.",
              ["Yes, finished.", "Yes, it's finished."], "Кӯтоҳ ҷавоб диҳед."),
            t("Is it straight?", "Рост аст?", "Бигӯ: ҳа, рост", "Yes, straight.", "Ҳа, рост.",
              ["Yes.", "Yes, it's straight."]),
            t("This is wrong. Do it again.", "Ин нодуруст. Боз кун.", "Бипурс: боз?", "Again?", "Боз?",
              ["Again? Okay.", "One more time?"]),
        ]),
        ("Ҳамин хел?", [
            s("Like this?", "Ҳамин хел?", None),
            s("Show me", "Нишон деҳ", None),
            s("Check it", "Санҷ", None),
            s("Looks good", "Хуб менамояд", None),
            s("Not straight", "Рост нест", None),
            s("Redo it", "Аз нав кун", None),
        ]),
        ("Бригадир нишон медиҳад", [
            t("Put the tiles in a line.", "Кошинҳоро дар як қатор гузор.", "Бипурс: ҳамин хел?",
              "Like this?", "Ҳамин хел?", ["Like this? Okay?", "This way?"]),
            t("No. Look, I'll show you.", "Не. Бин, нишон медиҳам.", "Бигӯ: лутфан, нишон деҳ",
              "Show me, please.", "Лутфан, нишон деҳ.", ["Please show me.", "Okay, show me."]),
            t("See? Now you try.", "Дидӣ? Акнун ту кӯшиш кун.", "Бипурс: хуб менамояд?",
              "Looks good?", "Хуб менамояд?", ["Is it good?", "Like this?"]),
        ]),
        ("Ман мепурсам", [
            s("Can you check it?", "Санҷида метавонед?", None),
            s("Is this okay?", "Ин хуб аст?", None),
            s("It's not straight.", "Рост нест.", None),
            s("I can redo it.", "Аз нав карда метавонам.", None),
            s("How is it?", "Чӣ хел аст?", None),
            s("Thanks, I understand.", "Ташаккур, фаҳмидам.", None),
        ]),
        ("Девор", [
            t("Are you done with the wall?", "Деворро тамом кардӣ?", "Бигӯ: ҳа, санҷида метавонед?",
              "Yes. Can you check it?", "Ҳа. Санҷида метавонед?", ["Yes, can you check it?", "Yes. Check it, please."]),
            t("Hmm. This part is not straight.", "Ҳм. Ин қисм рост нест.", "Бигӯ: аз нав карда метавонам",
              "I can redo it.", "Аз нав карда метавонам.", ["Okay, I'll redo it.", "Sorry, I'll do it again."]),
            t("Good. Be careful this time.", "Хуб. Ин дафъа эҳтиёт бош.", "Бигӯ: хуб, фаҳмидам",
              "Okay, I understand.", "Хуб, фаҳмидам.", ["Got it.", "Okay."]),
        ]),
        ("Хатои ман", [
            w("Mistake", "хато", None),
            s("Sorry, my mistake.", "Бубахшед, хатои ман.", None),
            w("Minutes", "дақиқаҳо", None),
            s("Ten more minutes.", "Боз даҳ дақиқа.", None),
            s("It's ready now.", "Акнун тайёр.", None),
            s("Is it good now?", "Акнун хуб аст?", None),
        ]),
        ("Кай тайёр?", [
            t("Why is this wrong?", "Чаро ин нодуруст?", "Бигӯ: бубахшед, хатои ман",
              "Sorry, my mistake.", "Бубахшед, хатои ман.", ["My mistake.", "Sorry."]),
            t("When will it be ready?", "Кай тайёр мешавад?", "Бигӯ: боз даҳ дақиқа",
              "Ten more minutes.", "Боз даҳ дақиқа.", ["Ten minutes.", "In ten minutes."]),
            t("Okay. Let me see.", "Хуб. Бигзор бубинам.", "Бипурс: акнун хуб аст?",
              "Is it good now?", "Акнун хуб аст?", ["Is it okay now?", "Good now?"]),
            t("Yes, perfect. Good job!", "Ҳа, олӣ. Офарин!", "Ташаккур гӯй", "Thank you!", "Ташаккур!",
              ["Thanks!", "Thank you, boss."]),
        ]),
        ("Миссия: кори ман", [
            t("Show me your work.", "Кори худро нишон деҳ.", "Бигӯ: ана, хуб аст?",
              "Here. Is this okay?", "Ана. Ин хуб аст?", ["Is this okay?", "Here it is."]),
            t("This line is not straight.", "Ин хат рост нест.", "Бигӯ: бубахшед, аз нав карда метавонам",
              "Sorry. I can redo it.", "Бубахшед. Аз нав карда метавонам.", ["I'll do it again.", "Sorry, I'll redo it."]),
            t("Okay. Use the level.", "Хуб. Аз нивелир истифода бар.", "Бипурс: ҳамин хел?",
              "Like this?", "Ҳамин хел?", ["This way?", "Like this? Okay?"]),
            t("Yes, now it's perfect.", "Ҳа, акнун олӣ.", "Ташаккур гӯй ва бигӯ, ки фаҳмидӣ",
              "Thanks, I understand.", "Ташаккур, фаҳмидам.", ["Thank you.", "Got it, thanks."]),
        ]),
    ]))

# ═════════════════════ 20. Соатҳо ва табел (сохтмон) ═════════════════════
made.append(pack("hours_en_tg", "Hours and timesheet", "Соатҳо ва табел", "🕗", 20, B,
    "Дар Амрико ва Англия ҳар рӯз омадан ва рафтанро дар табел сабт мекунанд — аз он музд "
    "ҳисоб мешавад. Шумо имзо мегузоред, соатҳоятонро мегӯед ва хаторо нишон медиҳед.",
    [
        ("Табел", [
            w("Timesheet", "табел", None),
            w("Sign", "имзо кардан", None),
            w("Start", "сар кардан", None),
            w("Finish", "тамом кардан", None),
            w("Break", "танаффус", None),
            w("Minutes", "дақиқаҳо", None),
        ]),
        ("Имзо гузоштӣ?", [
            t("Did you sign in?", "Имзо гузоштӣ?", "Бигӯ, ки ҳа", "Yes.", "Ҳа.", ["Yes, I did."],
              "Кӯтоҳ ҷавоб диҳед."),
            t("When did you start? Seven or eight?", "Кай сар кардӣ? Ҳафт ё ҳашт?", "Бигӯ: ҳафт",
              "Seven.", "Ҳафт.", ["At seven.", "7."]),
            t("How long was your break?", "Танаффусат чанд буд?", "Бигӯ: сӣ дақиқа",
              "Thirty minutes.", "Сӣ дақиқа.", ["30 minutes.", "Thirty."]),
        ]),
        ("Имзо", [
            s("Sign here", "Ин ҷо имзо кун", None),
            s("Sign in", "Омаданро сабт кун", "«Sign in» — омадан, «sign out» — рафтан."),
            s("Sign out", "Рафтанро сабт кун", None),
            s("Eight hours", "Ҳашт соат", None),
            s("Thirty minutes", "Сӣ дақиқа", None),
            s("My hours", "Соатҳои ман", None),
        ]),
        ("Саҳар", [
            t("Morning! Sign here.", "Субҳ ба хайр! Ин ҷо имзо кун.", "Бипурс: ин ҷо?",
              "Here?", "Ин ҷо?", ["Sign here?", "Right here?"]),
            t("Yes. And sign out at five.", "Ҳа. Соати панҷ рафтанро ҳам сабт кун.", "Бигӯ: хуб, соати панҷ",
              "Okay, at five.", "Хуб, соати панҷ.", ["Okay.", "Sure, at five."]),
            t("How many hours today?", "Имрӯз чанд соат?", "Бигӯ: ҳашт соат",
              "Eight hours.", "Ҳашт соат.", ["Eight.", "8 hours."]),
        ]),
        ("Соатҳои ман", [
            s("I start at seven.", "Ман соати ҳафт сар мекунам.", None, swaps=["seven|ҳафт", "eight|ҳашт"]),
            s("I finish at five.", "Ман соати панҷ тамом мекунам.", None, swaps=["five|панҷ", "six|шаш"]),
            s("My hours are wrong.", "Соатҳои ман нодурустанд.", None),
            s("Where do I sign?", "Куҷо имзо кунам?", None),
            s("I work eight hours.", "Ман ҳашт соат кор мекунам.", None),
            s("I can sign now.", "Ҳозир имзо мекунам.", None),
        ]),
        ("Хато дар табел", [
            t("Your timesheet says six hours.", "Дар табелат шаш соат.", "Бигӯ: соатҳои ман нодурустанд",
              "My hours are wrong.", "Соатҳои ман нодурустанд.", ["That's wrong.", "It's wrong."]),
            t("Why? When do you start?", "Чаро? Кай сар мекунӣ?", "Бигӯ: соати ҳафт сар мекунам",
              "I start at seven.", "Ман соати ҳафт сар мекунам.", ["At seven.", "I started at seven."]),
            t("And when do you finish?", "Ва кай тамом мекунӣ?", "Бигӯ: соати панҷ тамом мекунам",
              "I finish at five.", "Ман соати панҷ тамом мекунам.", ["At five.", "I finished at five."]),
        ]),
        ("Шанбе ва танаффус", [
            s("I work on Saturday.", "Ман шанбе кор мекунам.", None),
            s("No break today.", "Имрӯз танаффус набуд.", None),
            s("Please check again.", "Лутфан, боз санҷед.", None),
            w("Saturday", "шанбе", None),
            s("Thanks for checking.", "Ташаккур барои санҷиш.", None),
            s("Can you fix it?", "Ислоҳ карда метавонед?", None),
        ]),
        ("Ислоҳи табел", [
            t("Okay, I see. I'll fix it.", "Хуб, фаҳмидам. Ислоҳ мекунам.", "Бигӯ: ман шанбе ҳам кор мекунам",
              "I work on Saturday too.", "Ман шанбе ҳам кор мекунам.", ["And Saturday.", "I also worked on Saturday."]),
            t("Saturday? How many hours?", "Шанбе? Чанд соат?", "Бигӯ: шаш соат", "Six hours.", "Шаш соат.",
              ["Six.", "6 hours."]),
            t("And your break?", "Танаффусат чӣ?", "Бигӯ: имрӯз танаффус набуд", "No break today.", "Имрӯз танаффус набуд.",
              ["No break.", "I had no break."]),
        ]),
        ("Миссия: саҳари кор", [
            t("Hi. Did you sign in today?", "Салом. Имрӯз имзо гузоштӣ?", "Бигӯ: не. ҳозир имзо мекунам",
              "No. I can sign now.", "Не. Ҳозир имзо мекунам.", ["No, I forgot.", "Sorry, I forgot."]),
            t("Okay. What time do you start?", "Хуб. Соати чанд сар мекунӣ?", "Бигӯ: соати ҳафт сар мекунам",
              "I start at seven.", "Ман соати ҳафт сар мекунам.", ["At seven.", "I started at seven."]),
            t("And when will you finish?", "Кай тамом мекунӣ?", "Бигӯ: соати панҷ", "At five.", "Соати панҷ.",
              ["Five.", "At five o'clock."]),
            t("Good. Sign here, please.", "Хуб. Лутфан, ин ҷо имзо кун.", "Бигӯ: хуб, ташаккур",
              "Okay, thank you.", "Хуб, ташаккур.", ["Thanks.", "Okay."]),
        ]),
    ]))

# ═════════════════════ ТАҲСИЛ ═════════════════════
made.append(pack("arrive_en_tg", "Arriving to study", "Омадан барои таҳсил", "✈️", 2, S,
    "Шумо барои таҳсил ба хориҷ омадед. Дар фурудгоҳ мегӯед, ки донишҷӯед ва барои чӣ "
    "омадед, визаро нишон медиҳед ва бо такси ба донишгоҳ меравед.",
    [
        ("Фурудгоҳ", [
            w("Student", "донишҷӯ", None),
            w("University", "донишгоҳ", None),
            w("Passport", "шиноснома", None),
            w("Suitcase", "ҷомадон", None),
            w("Study", "таҳсил кардан", None),
            w("Visa", "виза", None),
        ]),
        ("Назорати шиноснома", [
            t("Why are you here? Work or study?", "Чаро омадед? Кор ё таҳсил?", "Бигӯ: таҳсил",
              "Study.", "Таҳсил.", ["To study.", "I'm here to study."], "Кӯтоҳ ҷавоб диҳед."),
            t("Are you a student?", "Шумо донишҷӯед?", "Бигӯ, ки ҳа", "Yes.", "Ҳа.", ["Yes, I am."]),
            t("What is in your suitcase? Food?", "Дар ҷомадонатон чист? Хӯрок?", "Бигӯ: либос",
              "Clothes.", "Либос.", ["My clothes.", "Just clothes."]),
        ]),
        ("Виза", [
            s("My visa", "Визаи ман", None),
            s("Student visa", "Визаи донишҷӯӣ", None),
            w("Welcome", "хуш омадед", None),
            s("One year", "Як сол", None),
            s("Which university?", "Кадом донишгоҳ?", None),
            w("Taxi", "такси", None),
        ]),
        ("Виза, лутфан", [
            t("Your visa, please.", "Визаатон, лутфан.", "Бигӯ: ана визаи ман", "My visa.", "Визаи ман.",
              ["Here, my visa.", "Here you go."]),
            t("A student visa. How long will you stay?", "Визаи донишҷӯӣ. Чанд вақт мемонед?",
              "Бигӯ: як сол", "One year.", "Як сол.", ["For one year.", "A year."]),
            t("Welcome! Next, please.", "Хуш омадед! Навбатӣ.", "Ташаккур гӯй", "Thank you.", "Ташаккур.",
              ["Thanks.", "Thank you very much."]),
        ]),
        ("Ман донишҷӯям", [
            s("I am {job}.", "Ман {job_tg} ҳастам.", "Касби худро гӯед.",
              cue="What do you do?", cue_tr="Шумо чӣ кор мекунед?"),
            s("I'm here to study.", "Ман барои таҳсил омадам.", None),
            own("I study at ___.", "Ман дар ___ таҳсил мекунам.", "Номи донишгоҳи худро гӯед.",
                "Where do you study?", "Шумо дар куҷо таҳсил мекунед?", "Номи донишгоҳро гӯед"),
            s("Where is the exit?", "Баромадгоҳ куҷост?", None),
            s("I need a taxi.", "Ба ман такси лозим.", None),
            s("Is this my suitcase?", "Ин ҷомадони ман аст?", None),
        ]),
        ("Сабаби сафар", [
            t("Hello. What's the reason for your visit?", "Салом. Сабаби сафаратон чист?",
              "Бигӯ: барои таҳсил омадам", "I'm here to study.", "Барои таҳсил омадам.",
              ["To study.", "I'm a student."]),
            t("Where will you study?", "Дар куҷо таҳсил мекунед?", "Бигӯ: дар донишгоҳ",
              "At the university.", "Дар донишгоҳ.", ["At a university.", "University."]),
            t("Okay. Welcome!", "Хуб. Хуш омадед!", "Ташаккур гӯй", "Thank you!", "Ташаккур!",
              ["Thanks!", "Thank you very much."]),
        ]),
        ("Такси", [
            s("Where is the taxi?", "Такси куҷост?", None),
            s("To the university, please.", "Ба донишгоҳ, лутфан.", None),
            s("How much is it?", "Чанд пул аст?", None),
            w("Missing", "гум (нест)", None),
            s("My suitcase is missing.", "Ҷомадонам гум шуд.", None),
            s("Can you help me?", "Ба ман ёрӣ дода метавонед?", None),
        ]),
        ("Ба донишгоҳ", [
            t("Taxi? Where to?", "Такси? Ба куҷо?", "Бигӯ: ба донишгоҳ, лутфан",
              "To the university, please.", "Ба донишгоҳ, лутфан.", ["The university.", "University, please."]),
            t("Okay. Get in.", "Хуб. Шинед.", "Бипурс: чанд пул аст?", "How much is it?", "Чанд пул аст?",
              ["How much?", "How much to the university?"]),
            t("Forty dollars.", "Чил доллар.", "Бигӯ: хуб, ташаккур", "Okay, thank you.", "Хуб, ташаккур.",
              ["Okay.", "Thanks."]),
        ]),
        ("Миссия: фурудгоҳ", [
            t("Passport, please. Why are you here?", "Шиноснома, лутфан. Чаро омадед?",
              "Бигӯ: барои таҳсил", "I'm here to study.", "Барои таҳсил омадам.", ["To study.", "I'm a student."]),
            t("Which university?", "Кадом донишгоҳ?", "Бигӯ: Донишгоҳи давлатӣ",
              "The State University.", "Донишгоҳи давлатӣ.", ["State University.", "The state university."]),
            t("Do you have a student visa?", "Визаи донишҷӯӣ доред?", "Бигӯ: ҳа, ана визаи ман",
              "Yes, here is my visa.", "Ҳа, ана визаи ман.", ["Yes, I do.", "Yes, here it is."]),
            t("Everything is fine. Welcome!", "Ҳама чиз дуруст. Хуш омадед!", "Ташаккур гӯй",
              "Thank you very much!", "Ташаккури зиёд!", ["Thank you!", "Thanks!"]),
        ]),
    ]))

made.append(pack("register_en_tg", "Registration office", "Дафтари қабул", "🏫", 3, S,
    "Рӯзи аввал дар донишгоҳ: дафтари қабул. Шумо мегӯед, ки донишҷӯи навед, варақа пур "
    "мекунед, сурат ва нусхаи шиноснома медиҳед ва корти донишҷӯӣ мегиред.",
    [
        ("Ҳуҷҷатҳо", [
            w("Office", "идора (дафтар)", None),
            w("Form", "варақа", None),
            w("Photo", "сурат", None),
            w("Copy", "нусха", None),
            w("Course", "курс", None),
            w("Card", "корт", None),
        ]),
        ("Донишҷӯи нав", [
            t("Hello! New student?", "Салом! Донишҷӯи нав?", "Бигӯ, ки ҳа", "Yes.", "Ҳа.",
              ["Yes, I am.", "Yes, I'm new."], "Кӯтоҳ ҷавоб диҳед."),
            t("Passport or a copy?", "Шиноснома ё нусха?", "Бигӯ: нусха", "A copy.", "Нусха.",
              ["Copy.", "The copy."]),
            t("What course? English?", "Кадом курс? Англисӣ?", "Бигӯ: англисӣ", "English.", "Англисӣ.",
              ["English course.", "Yes, English."]),
        ]),
        ("Варақа", [
            s("This form", "Ин варақа", None),
            s("Two photos", "Ду сурат", None),
            s("Sign here", "Ин ҷо имзо кунед", None),
            s("My course", "Курси ман", None),
            s("Student card", "Корти донишҷӯӣ", None),
            w("Surname", "насаб", None),
        ]),
        ("Қабул", [
            t("Fill in this form, please.", "Лутфан, ин варақаро пур кунед.", "Бигӯ: хуб", "Okay.", "Хуб.",
              ["Okay, sure.", "Sure."]),
            t("And we need two photos.", "Ду сурат ҳам лозим.", "Бигӯ: ду сурат? хуб",
              "Two photos? Okay.", "Ду сурат? Хуб.", ["Okay.", "Two photos."]),
            t("Your student card is ready on Monday.", "Корти донишҷӯиатон душанбе тайёр.",
              "Бипурс: корти донишҷӯӣ?", "Student card?", "Корти донишҷӯӣ?", ["My student card?", "Monday?"]),
        ]),
        ("Ман мегӯям", [
            s("I'm a new student.", "Ман донишҷӯи навам.", None),
            own("My surname is ___.", "Насаби ман ___.", "Насаби худро гӯед.",
                "What is your surname?", "Насабатон чист?", "Насаби худро гӯед"),
            s("Where do I sign?", "Куҷо имзо кунам?", None),
            s("I have my passport.", "Шиносномаам бо ман аст.", None),
            s("Here are my photos.", "Ана суратҳои ман.", None),
            s("When is it ready?", "Кай тайёр мешавад?", None),
        ]),
        ("Дар дафтар", [
            t("Hello. How can I help?", "Салом. Чӣ ёрӣ диҳам?", "Бигӯ: ман донишҷӯи навам",
              "I'm a new student.", "Ман донишҷӯи навам.", ["I'm new here.", "New student."]),
            t("Welcome! Do you have your passport?", "Хуш омадед! Шиносномаатон ҳаст?",
              "Бигӯ: ҳа, шиносномаам бо ман", "Yes, I have my passport.", "Ҳа, шиносномаам бо ман.",
              ["Yes, here it is.", "Yes."]),
            t("Good. Sign this form.", "Хуб. Ин варақаро имзо кунед.", "Бипурс: куҷо имзо кунам?",
              "Where do I sign?", "Куҷо имзо кунам?", ["Where?", "Sign where?"]),
        ]),
        ("Ҳуҷра ва пул", [
            w("Free", "ройгон", None),
            s("Is it free?", "Ройгон аст?", None),
            s("Do I pay?", "Пул медиҳам?", None),
            s("Which room?", "Кадом ҳуҷра?", None),
            s("Room twelve.", "Ҳуҷраи дувоздаҳ.", None, swaps=["twelve|дувоздаҳ", "ten|даҳ"]),
            s("Thanks for your help.", "Ташаккур барои ёрӣ.", None),
        ]),
        ("Корт тайёр", [
            t("Your student card is ready.", "Корти донишҷӯиатон тайёр.", "Бипурс: пул медиҳам?",
              "Do I pay?", "Пул медиҳам?", ["Is it free?", "How much?"]),
            t("No, it's free.", "Не, ройгон.", "Бипурс: кадом ҳуҷра?", "Which room?", "Кадом ҳуҷра?",
              ["Which room is my class?", "What room?"]),
            t("Room twelve, second floor.", "Ҳуҷраи дувоздаҳ, ошёнаи дуюм.", "Ташаккур гӯй барои ёрӣ",
              "Thanks for your help.", "Ташаккур барои ёрӣ.", ["Thank you.", "Thanks a lot."]),
        ]),
        ("Миссия: қабул ба донишгоҳ", [
            t("Hi! Can I help you?", "Салом! Ёрӣ диҳам?", "Бигӯ: ман донишҷӯи навам",
              "I'm a new student.", "Ман донишҷӯи навам.", ["I'm new here.", "Hi, I'm a new student."]),
            t("Do you have your documents?", "Ҳуҷҷатҳоятон ҳаст?", "Бигӯ: ҳа, шиноснома ва суратҳо",
              "Yes, my passport and photos.", "Ҳа, шиноснома ва суратҳо.", ["Yes, here they are.", "Yes."]),
            t("Great. Sign here, please.", "Олӣ. Лутфан, ин ҷо имзо кунед.", "Бипурс: корт кай тайёр?",
              "When is my card ready?", "Корти ман кай тайёр?", ["When is it ready?", "When can I get my card?"]),
            t("On Monday. Welcome!", "Рӯзи душанбе. Хуш омадед!", "Ташаккур гӯй барои ёрӣ",
              "Thanks for your help.", "Ташаккур барои ёрӣ.", ["Thank you.", "Thanks!"]),
        ]),
    ]))

made.append(pack("dorm_en_tg", "The dorm", "Хобгоҳ", "🛏️", 4, S,
    "Хобгоҳи донишҷӯён: ҳуҷра, калид, ҳамҳуҷра, душ ва ошхона. Шумо ҷой мепурсед, бо "
    "ҳамҳуҷра шинос мешавед ва қоидаҳоро мефаҳмед.",
    [
        ("Хобгоҳ", [
            w("Dorm", "хобгоҳ", None),
            w("Room", "ҳуҷра", None),
            w("Key", "калид", None),
            w("Roommate", "ҳамҳуҷра", None),
            w("Bed", "кат", None),
            w("Quiet", "ором", None),
        ]),
        ("Ҳуҷраи ман", [
            t("Are you in the dorm?", "Шумо дар хобгоҳед?", "Бигӯ, ки ҳа", "Yes.", "Ҳа.", ["Yes, I am."],
              "Кӯтоҳ ҷавоб диҳед."),
            t("What do you need? Your key?", "Чӣ лозим? Калидатон?", "Бигӯ: калид", "The key.", "Калид.",
              ["My key.", "Yes, the key."]),
            t("Where do you sleep? Here?", "Куҷо мехобӣ? Ин ҷо?", "Бигӯ: он кат", "That bed.", "Он кат.",
              ["There.", "That one."]),
        ]),
        ("Ҳуҷра", [
            s("Room five", "Ҳуҷраи панҷ", None),
            s("My key", "Калиди ман", None),
            s("My roommate", "Ҳамҳуҷраи ман", None),
            s("Quiet, please", "Ором, лутфан", None),
            w("Shower", "душ", None),
            s("Hot water", "Оби гарм", None),
        ]),
        ("Қабул дар хобгоҳ", [
            t("Your room is number five.", "Ҳуҷраи шумо рақами панҷ.", "Бигӯ: ҳуҷраи панҷ? хуб",
              "Room five? Okay.", "Ҳуҷраи панҷ? Хуб.", ["Okay.", "Room five."]),
            t("Here is your key.", "Ана калидатон.", "Ташаккур гӯй", "Thank you.", "Ташаккур.",
              ["Thanks.", "Thank you very much."]),
            t("Hi! I'm your roommate, Ali.", "Салом! Ман ҳамҳуҷраи ту, Алӣ.", "Салом гӯй ва бигӯ, ки аз шиносоӣ шодӣ",
              "Hi! Nice to meet you.", "Салом! Аз шиносоӣ шодам.", ["Nice to meet you.", "Hello! Nice to meet you."]),
        ]),
        ("Ман мепурсам", [
            s("Where is the shower?", "Душ куҷост?", None,
              swaps=["shower|душ", "kitchen|ошхона", "laundry|ҷомашӯйхона"]),
            s("Is there hot water?", "Оби гарм ҳаст?", None),
            s("Where is my key?", "Калидам куҷост?", None),
            s("Please be quiet.", "Лутфан, ором бошед.", None),
            s("When does it close?", "Кай баста мешавад?", None),
            s("Can I use this?", "Инро истифода бурда метавонам?", None),
        ]),
        ("Душ куҷост?", [
            t("Hi! Do you need anything?", "Салом! Ягон чиз лозим?", "Бипурс: душ куҷост?",
              "Where is the shower?", "Душ куҷост?", ["Where's the shower?", "The shower?"]),
            t("At the end of the hall.", "Дар охири долон.", "Бипурс: оби гарм ҳаст?",
              "Is there hot water?", "Оби гарм ҳаст?", ["Hot water?", "Is the water hot?"]),
            t("Yes, all day.", "Ҳа, тамоми рӯз.", "Ташаккур гӯй", "Thank you.", "Ташаккур.", ["Thanks.", "Great, thanks."]),
        ]),
        ("Шом дар хобгоҳ", [
            w("Studying", "дарс хондан", None),
            s("I'm studying.", "Ман дарс мехонам.", None),
            w("Cook", "пухтан", None),
            s("Let's cook together.", "Биё якҷоя хӯрок пазем.", None),
            s("It's late.", "Дер шуд.", None),
            s("Good night!", "Шаб ба хайр!", None),
        ]),
        ("Ҳамҳуҷра", [
            t("Let's listen to music!", "Биё мусиқӣ гӯш кунем!", "Бигӯ: бубахшед, ман дарс мехонам",
              "Sorry, I'm studying.", "Бубахшед, ман дарс мехонам.", ["I'm studying.", "Sorry, not now."]),
            t("Oh, sorry! I'm hungry. Are you?", "Оҳ, бубахшед! Гуруснаам. Ту чӣ?",
              "Бигӯ: ҳа, биё якҷоя пазем", "Yes. Let's cook together.", "Ҳа. Биё якҷоя пазем.",
              ["Let's cook together.", "Yes, let's cook."]),
            t("Great! What do we cook?", "Олӣ! Чӣ мепазем?", "Бигӯ: палав", "Plov!", "Палав!",
              ["Let's make plov.", "Plov."]),
        ]),
        ("Миссия: рӯзи аввал дар хобгоҳ", [
            t("Welcome to the dorm! Are you a new student?", "Хуш омадед ба хобгоҳ! Донишҷӯи навед?",
              "Бигӯ: ҳа, донишҷӯи навам", "Yes, I'm a new student.", "Ҳа, ман донишҷӯи навам.", ["Yes, I'm new.", "Yes."]),
            t("Your room is number five. Here's the key.", "Ҳуҷраатон рақами панҷ. Ана калид.",
              "Бипурс: душ куҷост?", "Where is the shower?", "Душ куҷост?", ["Where's the shower?", "The shower?"]),
            t("On the first floor. Anything else?", "Дар ошёнаи якум. Боз чизе?", "Бипурс: хобгоҳ кай баста мешавад?",
              "When does it close?", "Кай баста мешавад?", ["When is it closed?", "What time does it close?"]),
            t("At eleven. Good night!", "Соати ёздаҳ. Шаб ба хайр!", "Ташаккур гӯй ва шаби хуш гӯй",
              "Thank you. Good night!", "Ташаккур. Шаб ба хайр!", ["Thanks, good night!", "Good night!"]),
        ]),
    ]))

made.append(pack("class_en_tg", "In class", "Дар дарс", "📚", 5, S,
    "Дар дарс муаллим мегӯяд, ки китобро кушоед, саволҳо медиҳад ва вазифа месупорад. Шумо "
    "савол медиҳед, хоҳиш мекунед такрор кунад ва мегӯед, ки чиро намефаҳмед.",
    [
        ("Дарс", [
            w("Teacher", "муаллим", None),
            w("Book", "китоб", None),
            w("Page", "саҳифа", None),
            w("Question", "савол", None),
            w("Late", "дер", None),
            w("Repeat", "такрор кардан", None),
        ]),
        ("Муаллим мепурсад", [
            t("What do you need? A pen?", "Чӣ лозим? Қалам?", "Бигӯ: китоб", "A book.", "Китоб.",
              ["Book.", "My book."], "Кӯтоҳ ҷавоб диҳед."),
            t("Do you have a question?", "Савол доред?", "Бигӯ, ки ҳа", "Yes.", "Ҳа.", ["Yes, I do.", "Yes, one question."]),
            t("Page ten or twelve?", "Саҳифаи даҳ ё дувоздаҳ?", "Бигӯ: дувоздаҳ", "Twelve.", "Дувоздаҳ.",
              ["Page twelve.", "12."]),
        ]),
        ("Дар синф", [
            s("Sorry, teacher", "Бубахшед, муаллим", None),
            s("One question", "Як савол", None),
            s("Page twelve", "Саҳифаи дувоздаҳ", None),
            s("Good morning", "Субҳ ба хайр", None),
            s("I'm late", "Дер кардам", None),
            w("Homework", "вазифаи хонагӣ", None),
        ]),
        ("Оғози дарс", [
            t("Good morning, class!", "Субҳ ба хайр, синф!", "Салом гӯй", "Good morning!", "Субҳ ба хайр!",
              ["Good morning, teacher.", "Morning!"]),
            t("You're late!", "Дер кардӣ!", "Бигӯ: бубахшед, муаллим", "Sorry, teacher.", "Бубахшед, муаллим.",
              ["Sorry, I'm late.", "Sorry."]),
            t("Open your books to page twelve.", "Китобҳоро дар саҳифаи дувоздаҳ кушоед.", "Бипурс: саҳифаи дувоздаҳ?",
              "Page twelve?", "Саҳифаи дувоздаҳ?", ["Twelve?", "Which page?"]),
        ]),
        ("Ман мепурсам", [
            s("I have a question.", "Ман савол дорам.", None),
            s("Can you repeat, please?", "Лутфан, такрор карда метавонед?", None),
            s("What does it mean?", "Ин чӣ маъно дорад?", None),
            s("Spell it, please?", "Ҳарф ба ҳарф гӯед, лутфан?", None),
            s("I don't know.", "Намедонам.", None),
            s("Sorry, no book.", "Бубахшед, китоб надорам.", None),
        ]),
        ("Савол", [
            t("Any questions?", "Савол ҳаст?", "Бигӯ: савол дорам", "I have a question.", "Ман савол дорам.",
              ["Yes, one question.", "Yes, I have a question."]),
            t("Yes? Go ahead.", "Ҳа? Бипурсед.", "Бипурс: «homework» чӣ маъно дорад?",
              "What does homework mean?", "«Homework» чӣ маъно дорад?", ["What does it mean?", "What is homework?"]),
            t("Homework is work at home.", "«Homework» — кор дар хона.", "Бигӯ: фаҳмидам, ташаккур",
              "Got it, thanks.", "Фаҳмидам, ташаккур.", ["Thank you.", "I understand, thanks."]),
        ]),
        ("Вазифа", [
            s("For tomorrow?", "Барои фардо?", None),
            s("It's ready.", "Тайёр аст.", None),
            w("Difficult", "душвор", None),
            s("It's difficult.", "Душвор аст.", None),
            w("Easy", "осон", None),
            s("It's easy.", "Осон аст.", None),
        ]),
        ("Вазифаи хонагӣ", [
            t("Your homework is page twenty.", "Вазифаатон саҳифаи бист.", "Бипурс: барои фардо?",
              "For tomorrow?", "Барои фардо?", ["Is it for tomorrow?", "Tomorrow?"]),
            t("Yes. Is it easy?", "Ҳа. Осон аст?", "Бигӯ: не, душвор", "No, it's difficult.", "Не, душвор аст.",
              ["It's difficult.", "No, difficult."]),
            t("Don't worry, I'll help you.", "Хавотир нашав, ёрӣ медиҳам.", "Ба муаллим ташаккур гӯй",
              "Thank you, teacher.", "Ташаккур, муаллим.", ["Thank you!", "Thanks."]),
        ]),
        ("Миссия: дарси англисӣ", [
            t("You're late again!", "Боз дер кардӣ!", "Бигӯ: бубахшед, муаллим", "Sorry, teacher.",
              "Бубахшед, муаллим.", ["Sorry, I'm late.", "Sorry."]),
            t("Where is your book?", "Китобат куҷост?", "Бигӯ: бубахшед, китоб надорам",
              "Sorry, no book.", "Бубахшед, китоб надорам.", ["I forgot my book.", "Sorry, I don't have it."]),
            t("Okay. Look at page twelve. Questions?", "Хуб. Ба саҳифаи дувоздаҳ нигоҳ кун. Савол?",
              "Бигӯ: савол дорам ва хоҳиш кун такрор кунад", "I have a question. Can you repeat, please?",
              "Савол дорам. Такрор карда метавонед?", ["Can you repeat, please?", "Please repeat."]),
            t("Of course. Page twelve, exercise three.", "Албатта. Саҳифаи дувоздаҳ, машқи се.",
              "Бигӯ: фаҳмидам, ташаккур", "Got it, thank you.", "Фаҳмидам, ташаккур.", ["Thank you.", "Got it."]),
        ]),
    ]))

made.append(pack("timetable_en_tg", "Timetable", "Ҷадвали дарсҳо", "🗓️", 7, S,
    "Ҷадвали дарсҳо: кадом рӯз, соати чанд, дар кадом ҳуҷра. Шумо мепурсед ва мефаҳмед, ки "
    "дарс кай аст, бекор шуд ё не, ва бо ҳамсинф вохӯриро муайян мекунед.",
    [
        ("Рӯзҳо", [
            w("Monday", "душанбе", None),
            w("Tuesday", "сешанбе", None),
            w("Wednesday", "чоршанбе", "Хонда мешавад: «вензей» — «d» шунида намешавад."),
            w("Class", "дарс", None),
            w("Room", "ҳуҷра", None),
            w("Time", "вақт", None),
        ]),
        ("Кадом рӯз?", [
            t("Is the class on Monday or Tuesday?", "Дарс душанбе аст ё сешанбе?", "Бигӯ: душанбе",
              "Monday.", "Душанбе.", ["On Monday."], "Кӯтоҳ ҷавоб диҳед."),
            t("What day is today? Wednesday?", "Имрӯз чӣ рӯз? Чоршанбе?", "Бигӯ: сешанбе",
              "Tuesday.", "Сешанбе.", ["It's Tuesday.", "No, Tuesday."]),
            t("What do you have now? Lunch?", "Ҳозир чӣ дорӣ? Хӯроки пешин?", "Бигӯ: дарс",
              "Class.", "Дарс.", ["A class.", "I have class."]),
        ]),
        ("Вақт", [
            s("On Monday", "Рӯзи душанбе", None),
            s("At nine", "Соати нӯҳ", None),
            s("Room ten", "Ҳуҷраи даҳ", None),
            s("Every Tuesday", "Ҳар сешанбе", None),
            w("Thursday", "панҷшанбе", None),
            s("Next week", "Ҳафтаи оянда", None),
        ]),
        ("Дарси англисӣ кай?", [
            t("When is English class?", "Дарси англисӣ кай?", "Бигӯ: рӯзи душанбе", "On Monday.", "Рӯзи душанбе.",
              ["Monday.", "It's on Monday."]),
            t("What time?", "Соати чанд?", "Бигӯ: соати нӯҳ", "At nine.", "Соати нӯҳ.", ["Nine.", "At 9."]),
            t("Which room?", "Кадом ҳуҷра?", "Бигӯ: ҳуҷраи даҳ", "Room ten.", "Ҳуҷраи даҳ.", ["Ten.", "Room 10."]),
        ]),
        ("Ман мепурсам", [
            s("When is the class?", "Дарс кай?", None),
            s("What time is class?", "Дарс соати чанд?", None),
            s("Where is room ten?", "Ҳуҷраи даҳ куҷост?", None),
            s("I have class today.", "Имрӯз дарс дорам.", None),
            s("Is there class tomorrow?", "Фардо дарс ҳаст?", None),
            s("No class today.", "Имрӯз дарс нест.", None),
        ]),
        ("Бо ҳамсинф", [
            t("Hi! Do you have class today?", "Салом! Имрӯз дарс дорӣ?", "Бигӯ: ҳа, имрӯз дарс дорам",
              "Yes, I have class today.", "Ҳа, имрӯз дарс дорам.", ["Yes, I do.", "Yes."]),
            t("What time?", "Соати чанд?", "Бигӯ: соати даҳ", "At ten.", "Соати даҳ.", ["Ten.", "At 10."]),
            t("Me too! Which room?", "Ман ҳам! Кадом ҳуҷра?", "Бигӯ: ҳуҷраи дувоздаҳ", "Room twelve.",
              "Ҳуҷраи дувоздаҳ.", ["Twelve.", "Room 12."]),
        ]),
        ("Ҳафта", [
            s("See you on Friday.", "То ҷумъа.", None),
            s("Is it every week?", "Ҳар ҳафта аст?", None),
            s("Class is at eight.", "Дарс соати ҳашт.", None),
            s("No class on Sunday.", "Якшанбе дарс нест.", None),
            w("Cancelled", "бекор шуд", None),
            s("Next week, Monday.", "Ҳафтаи оянда, душанбе.", None),
        ]),
        ("Дарс бекор шуд", [
            t("The Tuesday class is cancelled.", "Дарси сешанбе бекор шуд.", "Бипурс: фардо дарс ҳаст?",
              "Is there class tomorrow?", "Фардо дарс ҳаст?", ["Class tomorrow?", "And tomorrow?"]),
            t("Yes, on Wednesday at nine.", "Ҳа, чоршанбе соати нӯҳ.", "Бипурс: ҳар ҳафта?",
              "Is it every week?", "Ҳар ҳафта аст?", ["Every week?", "Is it every Wednesday?"]),
            t("Yes, every Wednesday.", "Ҳа, ҳар чоршанбе.", "Бигӯ: хуб, то чоршанбе",
              "Okay. See you on Wednesday.", "Хуб. То чоршанбе.", ["See you on Wednesday.", "Okay, thanks."]),
        ]),
        ("Миссия: ҷадвал", [
            t("Hi! Are you in my English class?", "Салом! Ту дар синфи англисии манӣ?",
              "Бигӯ: ҳа ва бипурс дарс кай", "Yes. When is the class?", "Ҳа. Дарс кай?", ["Yes. When is it?", "Yes."]),
            t("On Monday and Thursday.", "Рӯзҳои душанбе ва панҷшанбе.", "Бипурс: дарс соати чанд?",
              "What time is class?", "Дарс соати чанд?", ["What time?", "At what time?"]),
            t("At nine, room twelve.", "Соати нӯҳ, ҳуҷраи дувоздаҳ.", "Такрор кун ва ташаккур гӯй",
              "At nine, room twelve. Thanks.", "Соати нӯҳ, ҳуҷраи дувоздаҳ. Ташаккур.", ["Thanks!", "Nine, room twelve. Thank you."]),
            t("See you on Monday!", "То душанбе!", "Бигӯ: то душанбе", "See you on Monday!", "То душанбе!",
              ["See you!", "Bye, see you Monday!"]),
        ]),
    ]))

made.append(pack("library_en_tg", "At the library", "Дар китобхона", "📖", 8, S,
    "Китобхонаи донишгоҳ: китоб гирифтан, баргардондан, компютер ва принтер. Шумо корти "
    "китобхона мегиред ва мепурсед, ки китобро то кай гирифтан мумкин.",
    [
        ("Китобхона", [
            w("Library", "китобхона", None),
            w("Book", "китоб", None),
            w("Borrow", "қарз гирифтан", "Китобро муваққатан гирифтан."),
            w("Return", "баргардондан", None),
            w("Card", "корт", None),
            w("Computer", "компютер", None),
        ]),
        ("Чӣ лозим?", [
            t("What do you want? A book?", "Чӣ мехоҳед? Китоб?", "Бигӯ, ки ҳа, китоб", "A book.", "Китоб.",
              ["Yes, a book.", "Book."], "Кӯтоҳ ҷавоб диҳед."),
            t("Do you have a library card?", "Корти китобхона доред?", "Бигӯ, ки не", "No.", "Не.",
              ["No, I don't."]),
            t("Book or computer?", "Китоб ё компютер?", "Бигӯ: компютер", "Computer.", "Компютер.",
              ["A computer.", "The computer."]),
        ]),
        ("Корт", [
            s("This book", "Ин китоб", None),
            s("Two weeks", "Ду ҳафта", None),
            s("My card", "Корти ман", None),
            s("Library card", "Корти китобхона", None),
            s("Quiet, please", "Ором, лутфан", None),
            w("Printer", "принтер", None),
        ]),
        ("Корти китобхона", [
            t("You need a library card.", "Ба шумо корти китобхона лозим.", "Бипурс: корти китобхона?",
              "Library card?", "Корти китобхона?", ["A library card?", "A card?"]),
            t("Yes. It's free.", "Ҳа. Ройгон.", "Бигӯ: хуб, ташаккур", "Okay, thanks.", "Хуб, ташаккур.",
              ["Great, thanks.", "Thank you."]),
            t("You can borrow books for two weeks.", "Китобҳоро барои ду ҳафта гирифта метавонед.",
              "Бигӯ: ду ҳафта? хуб", "Two weeks? Okay.", "Ду ҳафта? Хуб.", ["Okay.", "Two weeks."]),
        ]),
        ("Ман мепурсам", [
            s("Can I borrow this?", "Инро гирифта метавонам?", None),
            s("Until when?", "То кай?", "Мӯҳлати баргардондани китобро мепурсад."),
            s("Where is the printer?", "Принтер куҷост?", None),
            s("I need a computer.", "Ба ман компютер лозим.", None),
            s("Can I use it?", "Истифода бурда метавонам?", None),
            s("Here is my card.", "Ана корти ман.", None),
        ]),
        ("Китоб мегирам", [
            t("Hello. Can I help you?", "Салом. Ёрӣ диҳам?", "Бипурс: инро гирифта метавонам?",
              "Can I borrow this?", "Инро гирифта метавонам?", ["Can I take this book?", "This book, please."]),
            t("Yes. Your card, please.", "Ҳа. Кортатон, лутфан.", "Бигӯ: ана корти ман", "Here is my card.",
              "Ана корти ман.", ["Here.", "Here you go."]),
            t("Okay. Return it in two weeks.", "Хуб. Баъди ду ҳафта баргардонед.", "Бигӯ: ду ҳафта, хуб, ташаккур",
              "Two weeks. Okay, thanks.", "Ду ҳафта. Хуб, ташаккур.", ["Okay, thanks.", "Thank you."]),
        ]),
        ("Кушода аст?", [
            s("The computer doesn't work.", "Компютер кор намекунад.", None),
            s("Where is it?", "Куҷост?", None),
            w("Open", "кушода", None),
            s("Is it open today?", "Имрӯз кушода аст?", None),
            s("Open on Sunday?", "Якшанбе кушода?", None),
            s("I need this book.", "Ба ман ин китоб лозим.", None),
        ]),
        ("Компютер", [
            t("Can I help you?", "Ёрӣ диҳам?", "Бигӯ: компютер кор намекунад", "The computer doesn't work.",
              "Компютер кор намекунад.", ["It doesn't work.", "This computer doesn't work."]),
            t("Try this one.", "Инашро санҷед.", "Бипурс: принтер куҷост?", "Where is the printer?",
              "Принтер куҷост?", ["The printer?", "Where's the printer?"]),
            t("Over there. It's ten cents a page.", "Он ҷо. Саҳифае даҳ сент.", "Ташаккур гӯй", "Thank you.", "Ташаккур.",
              ["Thanks.", "Okay, thanks."]),
        ]),
        ("Миссия: дар китобхона", [
            t("Hi! What do you need?", "Салом! Чӣ лозим?", "Бигӯ: ба ман ин китоб лозим", "I need this book.",
              "Ба ман ин китоб лозим.", ["This book, please.", "Can I borrow this book?"]),
            t("Do you have a library card?", "Корти китобхона доред?", "Бигӯ: ҳа, ана корти ман",
              "Yes, here is my card.", "Ҳа, ана корти ман.", ["Yes, here.", "Yes, I do."]),
            t("Good. Return it in two weeks.", "Хуб. Баъди ду ҳафта баргардонед.", "Бипурс: якшанбе кушода аст?",
              "Open on Sunday?", "Якшанбе кушода?", ["Is it open on Sunday?", "And on Sunday?"]),
            t("No, only Monday to Saturday.", "Не, танҳо аз душанбе то шанбе.", "Бигӯ: фаҳмидам, ташаккур",
              "Okay, got it. Thanks.", "Хуб, фаҳмидам. Ташаккур.", ["Got it, thanks.", "Thank you."]),
        ]),
    ]))

made.append(pack("classmates_en_tg", "Classmates", "Ҳамсинфон", "👫", 9, S,
    "Ҳамсинфон аз кишварҳои гуногун: шиносоӣ, чӣ мехонед, кадом забонҳоро медонед. Шумо "
    "ҷой мепурсед, рақами телефон мегиред ва якҷоя дарс хонданро пешниҳод мекунед.",
    [
        ("Ҳамсинфон", [
            w("Classmate", "ҳамсинф", None),
            w("Study", "хондан (омӯхтан)", None),
            w("Together", "якҷоя", None),
            w("Country", "кишвар", None),
            w("Language", "забон", None),
            w("Coffee", "қаҳва", None),
        ]),
        ("Шиносоӣ", [
            t("Are you a new classmate?", "Ту ҳамсинфи навӣ?", "Бигӯ, ки ҳа", "Yes.", "Ҳа.", ["Yes, I am.", "Yes, I'm new."],
              "Кӯтоҳ ҷавоб диҳед."),
            t("What do you study? Math?", "Чӣ мехонӣ? Математика?", "Бигӯ: англисӣ", "English.", "Англисӣ.",
              ["I study English.", "No, English."]),
            t("Tea or coffee?", "Чой ё қаҳва?", "Бигӯ: қаҳва", "Coffee.", "Қаҳва.", ["Coffee, please."]),
        ]),
        ("Якҷоя", [
            s("Me too", "Ман ҳам", None),
            s("Study together", "Якҷоя дарс хондан", None),
            s("Which country?", "Кадом кишвар?", None),
            s("Good idea", "Фикри хуб", None),
            s("After class", "Баъди дарс", None),
            s("Your language", "Забони ту", None),
        ]),
        ("Аз куҷоӣ?", [
            t("Where are you from? Which country?", "Аз куҷоӣ? Кадом кишвар?", "Бигӯ: Тоҷикистон",
              "Tajikistan.", "Тоҷикистон.", ["I'm from Tajikistan.", "From Tajikistan."]),
            t("Let's study together after class.", "Биё баъди дарс якҷоя дарс хонем.", "Бигӯ: фикри хуб",
              "Good idea!", "Фикри хуб!", ["Okay, good idea.", "Sure!"]),
            t("What languages do you speak?", "Бо кадом забонҳо гап мезанӣ?", "Бигӯ: тоҷикӣ ва русӣ",
              "Tajik and Russian.", "Тоҷикӣ ва русӣ.", ["Tajik, Russian.", "I speak Tajik and Russian."]),
        ]),
        ("Дар бораи худам", [
            s("What do you study?", "Чӣ мехонӣ?", None),
            s("I study English.", "Ман англисӣ мехонам.", None,
              swaps=["English|англисӣ", "business|тиҷорат", "medicine|тиб"]),
            s("Let's study together.", "Биё якҷоя дарс хонем.", None),
            s("Do you want coffee?", "Қаҳва мехоҳӣ?", None),
            s("I speak Tajik.", "Ман тоҷикӣ гап мезанам.", None, swaps=["Tajik|тоҷикӣ", "Russian|русӣ"]),
            s("And you?", "Ту-чӣ?", None),
        ]),
        ("Қаҳва баъди дарс", [
            t("Hi! I'm Maria. What do you study?", "Салом! Ман Мария. Чӣ мехонӣ?", "Бигӯ: англисӣ. Ту-чӣ?",
              "I study English. And you?", "Ман англисӣ мехонам. Ту-чӣ?", ["English. And you?", "I study English."]),
            t("Medicine. Do you want coffee?", "Тиб. Қаҳва мехоҳӣ?", "Бигӯ: ҳа, ташаккур",
              "Yes, thank you.", "Ҳа, ташаккур.", ["Sure.", "Yes, please."]),
            t("Let's go after class.", "Баъди дарс меравем.", "Бигӯ: хуб, фикри хуб",
              "Okay, good idea.", "Хуб, фикри хуб.", ["Good idea!", "Okay!"]),
        ]),
        ("Рақами телефон", [
            s("What's your phone number?", "Рақами телефонат чанд?", None),
            own("My number is ___.", "Рақами ман ___.", "Рақами телефони худро гӯед.",
                "What's your number?", "Рақамат чанд?", "Рақами худро гӯед"),
            s("Let's meet tomorrow.", "Фардо вомехӯрем.", None),
            s("See you in class.", "То дидор дар дарс.", None),
            s("Can I sit here?", "Ин ҷо нишаста метавонам?", None),
            s("Sit with me.", "Бо ман шин.", None),
        ]),
        ("Ҷои холӣ", [
            t("Hi!", "Салом!", "Бипурс: ин ҷо нишаста метавонам?", "Can I sit here?", "Ин ҷо нишаста метавонам?",
              ["Is this seat free?", "Can I sit here, please?"]),
            t("Yes, sit down.", "Ҳа, шинед.", "Ташаккур гӯй ва пешниҳод кун якҷоя дарс хонед",
              "Thanks. Let's study together.", "Ташаккур. Биё якҷоя дарс хонем.", ["Thanks!", "Let's study together."]),
            t("Sure! Let's meet tomorrow.", "Албатта! Фардо вомехӯрем.", "Бигӯ: хуб, то фардо",
              "Okay. See you tomorrow.", "Хуб. То фардо.", ["See you tomorrow!", "Okay!"]),
        ]),
        ("Миссия: ҳамсинфи нав", [
            t("Hi! Are you new? Which country are you from?", "Салом! Навӣ? Аз кадом кишварӣ?",
              "Бигӯ: Тоҷикистон ва бипурс: ту-чӣ?", "Tajikistan. And you?", "Тоҷикистон. Ту-чӣ?",
              ["I'm from Tajikistan. And you?", "From Tajikistan."]),
            t("Brazil! What do you study?", "Бразилия! Чӣ мехонӣ?", "Бигӯ: англисӣ мехонам",
              "I study English.", "Ман англисӣ мехонам.", ["English.", "English. And you?"]),
            t("Me too! Let's study together?", "Ман ҳам! Якҷоя дарс хонем?", "Бигӯ: фикри хуб!",
              "Good idea!", "Фикри хуб!", ["Sure!", "Okay, good idea."]),
            t("Great. See you in class!", "Олӣ. То дидор дар дарс!", "Бигӯ: то дидор дар дарс",
              "See you in class!", "То дидор дар дарс!", ["See you!", "Bye, see you in class!"]),
        ]),
    ]))

made.append(pack("help_en_tg", "Asking for help", "Ёрӣ пурсидан", "🙋", 11, S,
    "Чизеро нафаҳмидед ё дарсро аз даст додед — ба назди муаллим меравед. Шумо мегӯед, ки "
    "чиро намефаҳмед, хоҳиш мекунед фаҳмонад ва вақти бештар мепурсед.",
    [
        ("Ёрӣ", [
            w("Help", "ёрӣ", None),
            w("Problem", "мушкил", None),
            w("Homework", "вазифаи хонагӣ", None),
            w("Email", "почтаи электронӣ", None),
            w("Office", "ҳуҷраи корӣ (кабинет)", None),
            w("Understand", "фаҳмидан", None),
        ]),
        ("Ёрӣ лозим?", [
            t("Do you need help?", "Ёрӣ лозим?", "Бигӯ, ки ҳа", "Yes.", "Ҳа.", ["Yes, please.", "Yes, I do."],
              "Кӯтоҳ ҷавоб диҳед."),
            t("Is it the homework or the exam?", "Вазифаи хонагӣ ё имтиҳон?", "Бигӯ: вазифаи хонагӣ",
              "The homework.", "Вазифаи хонагӣ.", ["Homework.", "It's the homework."]),
            t("Do you understand?", "Мефаҳмед?", "Бигӯ, ки не", "No.", "Не.", ["No, I don't.", "Not really."]),
        ]),
        ("Фаҳмо нест", [
            s("Help me", "Ёрӣ деҳ", None),
            s("This question", "Ин савол", None),
            s("Your email", "Почтаи шумо", None),
            s("Office hours", "Соатҳои қабул", "Вақте ки муаллим донишҷӯёнро қабул мекунад."),
            s("Not clear", "Фаҳмо нест", None),
            w("Explain", "фаҳмондан", None),
        ]),
        ("Дар кабинети муаллим", [
            t("Hello! Come in.", "Салом! Дароед.", "Бигӯ: ба ман ёрӣ лозим", "I need help.", "Ба ман ёрӣ лозим.",
              ["Can you help me?", "Hello, I need help."]),
            t("With what?", "Бо чӣ?", "Бигӯ: ин савол", "This question.", "Ин савол.", ["This one.", "This question here."]),
            t("Okay. What is not clear?", "Хуб. Чӣ фаҳмо нест?", "Бигӯ: вазифаи хонагӣ", "The homework.",
              "Вазифаи хонагӣ.", ["The homework is not clear.", "Homework."]),
        ]),
        ("Ман мепурсам", [
            s("Can you explain this?", "Инро фаҳмонда метавонед?", None),
            s("I don't understand this.", "Инро намефаҳмам.", None),
            s("Can I email you?", "Ба шумо почта фиристода метавонам?", None),
            s("When are office hours?", "Соатҳои қабул кай?", None),
            s("Thanks for your time.", "Ташаккур барои вақтатон.", None),
            s("I need more time.", "Ба ман вақти бештар лозим.", None),
        ]),
        ("Фаҳмонед, лутфан", [
            t("Hi. Can I help you?", "Салом. Ёрӣ диҳам?", "Бигӯ: инро намефаҳмам", "I don't understand this.",
              "Инро намефаҳмам.", ["I don't understand.", "This is not clear."]),
            t("Which part?", "Кадом қисм?", "Бипурс: инро фаҳмонда метавонед?", "Can you explain this?",
              "Инро фаҳмонда метавонед?", ["This part. Can you explain?", "Can you explain it?"]),
            t("Sure. Look...", "Албатта. Бинед...", "Ташаккур гӯй барои вақт", "Thanks for your time.",
              "Ташаккур барои вақтатон.", ["Thank you.", "Thanks a lot."]),
        ]),
        ("Дарсро аз даст додам", [
            s("I was sick.", "Бемор будам.", None),
            w("Yesterday", "дирӯз", None),
            s("I wasn't in class.", "Дар дарс набудам.", None),
            s("What's the homework?", "Вазифа чист?", None),
            s("Is Friday okay?", "Ҷумъа мешавад?", None),
            s("I understand now.", "Акнун фаҳмидам.", None),
        ]),
        ("Баъди беморӣ", [
            t("You weren't in class yesterday.", "Дирӯз дар дарс набудӣ.", "Бигӯ: бемор будам", "I was sick.",
              "Бемор будам.", ["Sorry, I was sick.", "I was sick, sorry."]),
            t("I see. Are you better now?", "Фаҳмо. Акнун беҳтарӣ?", "Бигӯ: ҳа ва бипурс: вазифа чист?",
              "Yes. What's the homework?", "Ҳа. Вазифа чист?", ["Yes, thanks. What did I miss?", "What did I miss?"]),
            t("Page thirty. The homework is for tomorrow.", "Саҳифаи сӣ. Вазифа барои фардо.",
              "Бигӯ: ба ман вақти бештар лозим", "I need more time.", "Ба ман вақти бештар лозим.",
              ["Can I have more time?", "More time, please."]),
            t("Okay. Friday is fine.", "Хуб. Ҷумъа мешавад.", "Ташаккур гӯй", "Thank you!", "Ташаккур!",
              ["Thanks!", "Thank you very much."]),
        ]),
        ("Миссия: назди муаллим", [
            t("Hello! Come in. How can I help?", "Салом! Дароед. Чӣ ёрӣ диҳам?",
              "Бигӯ: дар дарс набудам, бемор будам", "I wasn't in class. I was sick.",
              "Дар дарс набудам. Бемор будам.", ["I was sick. I missed the class.", "I missed the class."]),
            t("Sorry to hear that. What do you need?", "Афсӯс. Чӣ лозим?", "Бипурс: инро фаҳмонда метавонед?",
              "Can you explain this?", "Инро фаҳмонда метавонед?", ["Can you explain it?", "Please explain this."]),
            t("Of course. Is it clear now?", "Албатта. Акнун фаҳмо?", "Бигӯ: ҳа, акнун фаҳмидам",
              "Yes, I understand now.", "Ҳа, акнун фаҳмидам.", ["Yes, I understand.", "Yes, thank you."]),
            t("Good. Any more questions?", "Хуб. Боз савол ҳаст?", "Бигӯ: не, ташаккур барои вақтатон",
              "No. Thanks for your time.", "Не. Ташаккур барои вақтатон.", ["No, thank you.", "Thanks for your time."]),
        ]),
    ]))

made.append(pack("exams_en_tg", "Homework and exams", "Вазифа ва имтиҳон", "📝", 12, S,
    "Имтиҳон наздик: кай, чанд вақт, чӣ лозим. Шумо мепурсед, мегӯед, ки тайёред ё не, "
    "вақти бештар мехоҳед ва баҳои худро мепурсед.",
    [
        ("Имтиҳон", [
            w("Exam", "имтиҳон", None),
            w("Test", "санҷиш", None),
            w("Grade", "баҳо", None),
            w("Pass", "гузаштан", "«I passed» — гузаштам."),
            w("Ready", "тайёр", None),
            w("Pen", "қалам", None),
        ]),
        ("Кай?", [
            t("Is the exam today or tomorrow?", "Имтиҳон имрӯз аст ё фардо?", "Бигӯ: фардо", "Tomorrow.", "Фардо.",
              ["It's tomorrow."], "Кӯтоҳ ҷавоб диҳед."),
            t("Are you ready?", "Тайёрӣ?", "Бигӯ, ки ҳа", "Yes.", "Ҳа.", ["Yes, I am.", "I think so."]),
            t("Do you have a pen?", "Қалам дорӣ?", "Бигӯ, ки не", "No.", "Не.", ["No, I don't."]),
        ]),
        ("Барори кор!", [
            s("Next Friday", "Ҷумъаи оянда", None),
            s("Good luck", "Барори кор", None),
            s("I passed", "Гузаштам", None),
            s("My grade", "Баҳои ман", None),
            s("Not ready", "Тайёр нестам", None),
            w("Paper", "коғаз", None),
        ]),
        ("Имтиҳони ҷумъа", [
            t("The exam is next Friday.", "Имтиҳон ҷумъаи оянда.", "Бигӯ: ҷумъаи оянда? хуб",
              "Next Friday? Okay.", "Ҷумъаи оянда? Хуб.", ["Okay.", "Next Friday."]),
            t("Good luck!", "Барори кор!", "Ташаккур гӯй", "Thank you!", "Ташаккур!", ["Thanks!"]),
            t("How was the exam?", "Имтиҳон чӣ хел гузашт?", "Бигӯ: гузаштам!", "I passed!", "Гузаштам!",
              ["I passed it!", "Good, I passed."]),
        ]),
        ("Ман мепурсам", [
            s("When is the exam?", "Имтиҳон кай?", None),
            s("How long is it?", "Чанд вақт давом мекунад?", None),
            s("A pen, please.", "Қалам, лутфан.", None),
            s("I'm done.", "Ман тамом кардам.", None),
            s("What is my grade?", "Баҳои ман чанд?", None),
            s("I'm not ready.", "Ман тайёр нестам.", None),
        ]),
        ("Фардо санҷиш", [
            t("Tomorrow we have a test.", "Фардо санҷиш дорем.", "Бипурс: чанд вақт давом мекунад?",
              "How long is it?", "Чанд вақт давом мекунад?", ["How long?", "Is it long?"]),
            t("One hour.", "Як соат.", "Бигӯ: ман тайёр нестам", "I'm not ready.", "Ман тайёр нестам.",
              ["Not ready.", "Oh no, I'm not ready."]),
            t("Study tonight. You can do it!", "Бегоҳ тайёрӣ бин. Ту метавонӣ!", "Ташаккур гӯй", "Thank you!",
              "Ташаккур!", ["Thanks!", "Thank you, I will."]),
        ]),
        ("Вақт тамом!", [
            s("Is this correct?", "Ин дуруст аст?", None),
            w("Correct", "дуруст", None),
            s("It was difficult.", "Душвор буд.", None),
            s("Can I try again?", "Боз кӯшиш карда метавонам?", None),
            s("I need more time.", "Ба ман вақти бештар лозим.", None),
            s("Can I go now?", "Ҳозир рафта метавонам?", None),
        ]),
        ("Баъди имтиҳон", [
            t("Time's up! Finish, please.", "Вақт тамом! Лутфан, тамом кунед.", "Бигӯ: ба ман вақти бештар лозим",
              "I need more time.", "Ба ман вақти бештар лозим.", ["One more minute, please.", "More time, please."]),
            t("One more minute.", "Боз як дақиқа.", "Бигӯ: тамом кардам", "I'm done.",
              "Ман тамом кардам.", ["I finished.", "I finished the test."]),
            t("Your grade is C.", "Баҳои шумо C.", "Бипурс: боз кӯшиш карда метавонам?", "Can I try again?",
              "Боз кӯшиш карда метавонам?", ["Can I try again, please?", "Again?"]),
        ]),
        ("Миссия: рӯзи имтиҳон", [
            t("The exam starts now. Are you ready?", "Имтиҳон ҳозир сар мешавад. Тайёрӣ?",
              "Бигӯ: ҳа ва қалам пурс", "Yes. A pen, please.", "Ҳа. Қалам, лутфан.", ["Yes. Do you have a pen?", "Yes."]),
            t("Here. You have one hour.", "Ана. Як соат вақт доред.", "Бигӯ: хуб, ташаккур", "Okay, thank you.",
              "Хуб, ташаккур.", ["Thanks.", "Okay."]),
            t("Time's up! Did you finish?", "Вақт тамом! Тамом кардед?", "Бигӯ: ҳа, тамом кардам",
              "Yes, I'm done.", "Ҳа, тамом кардам.", ["Yes, I finished.", "Yes."]),
            t("Good. Grades on Monday.", "Хуб. Баҳоҳо рӯзи душанбе.", "Бигӯ: хуб, душвор буд",
              "Okay. It was difficult.", "Хуб. Душвор буд.", ["It was difficult.", "Okay, thanks."]),
        ]),
    ]))

made.append(pack("cafe_en_tg", "Campus café", "Ошхонаи донишгоҳ", "🥪", 13, S,
    "Ошхона ва қаҳвахонаи донишгоҳ: шӯрбо, сандвич, нӯшокӣ. Шумо фармоиш медиҳед, мегӯед, "
    "ки гӯшти хук намехӯред ва тахфифи донишҷӯӣ мепурсед.",
    [
        ("Меню", [
            w("Sandwich", "сандвич", None),
            w("Soup", "шӯрбо", None),
            w("Coffee", "қаҳва", None),
            w("Juice", "шарбат", None),
            w("Pork", "гӯшти хук", "Агар гӯшти хук намехӯред — инро донед."),
            w("Menu", "меню", None),
            w("Hungry", "гурусна", None),
        ]),
        ("Фармоиш", [
            t("What would you like? Soup?", "Чӣ мехоҳед? Шӯрбо?", "Бигӯ: сандвич", "A sandwich.", "Сандвич.",
              ["Sandwich.", "A sandwich, please."], "Кӯтоҳ ҷавоб диҳед."),
            t("Coffee or juice?", "Қаҳва ё шарбат?", "Бигӯ: шарбат", "Juice.", "Шарбат.", ["Juice, please."]),
            t("Are you hungry?", "Гуруснаӣ?", "Бигӯ, ки ҳа", "Yes.", "Ҳа.", ["Yes, very.", "Yes, I am."]),
        ]),
        ("Бурдан ё дар ин ҷо", [
            s("Chicken soup", "Шӯрбои мурғ", None),
            s("To go", "Барои бурдан", None),
            s("For here", "Дар ин ҷо", None),
            s("No sugar", "Бе шакар", None),
            w("Sugar", "шакар", None),
            s("Large coffee", "Қаҳваи калон", None),
        ]),
        ("Дар пешхон", [
            t("Hi! What can I get you?", "Салом! Ба шумо чӣ диҳам?", "Бигӯ: шӯрбои мурғ", "Chicken soup.",
              "Шӯрбои мурғ.", ["Chicken soup, please.", "The chicken soup."]),
            t("For here or to go?", "Дар ин ҷо ё барои бурдан?", "Бигӯ: барои бурдан", "To go.", "Барои бурдан.",
              ["To go, please.", "Take away."]),
            t("Anything to drink?", "Нӯшокӣ?", "Бигӯ: қаҳва, бе шакар", "Coffee, no sugar.", "Қаҳва, бе шакар.",
              ["Coffee, please. No sugar.", "Coffee."]),
        ]),
        ("Ман мегӯям", [
            s("The menu, please.", "Меню, лутфан.", None),
            s("I'd like a sandwich.", "Сандвич мехоҳам.", None, swaps=["sandwich|сандвич", "soup|шӯрбо", "coffee|қаҳва"]),
            s("Is there meat?", "Гӯшт дорад?", None),
            s("I don't eat pork.", "Ман гӯшти хук намехӯрам.", None),
            w("Discount", "тахфиф", None),
            s("Student discount?", "Тахфифи донишҷӯӣ?", None),
        ]),
        ("Мурғ ё ветчина?", [
            t("What would you like?", "Чӣ мехоҳед?", "Бигӯ: сандвич мехоҳам", "I'd like a sandwich.", "Сандвич мехоҳам.",
              ["A sandwich, please.", "Sandwich."]),
            t("Chicken or ham?", "Мурғ ё ветчина?", "Бигӯ: мурғ, гӯшти хук намехӯрам",
              "Chicken. I don't eat pork.", "Мурғ. Гӯшти хук намехӯрам.", ["Chicken, please.", "Chicken. No pork."]),
            t("Okay. Six dollars.", "Хуб. Шаш доллар.", "Бипурс: тахфифи донишҷӯӣ?", "Student discount?",
              "Тахфифи донишҷӯӣ?", ["Is there a student discount?", "Discount for students?"]),
        ]),
        ("Хӯрок чӣ хел?", [
            s("The soup is cold.", "Шӯрбо хунук аст.", None),
            w("Cold", "хунук", None),
            s("One more coffee.", "Боз як қаҳва.", None),
            s("Where is the water?", "Об куҷост?", None),
            s("It's very good.", "Хеле бомаза.", None),
            s("Can I sit here?", "Ин ҷо нишаста метавонам?", None),
        ]),
        ("Шӯрбо хунук", [
            t("How is the food?", "Хӯрок чӣ хел?", "Бигӯ: шӯрбо хунук аст", "The soup is cold.", "Шӯрбо хунук аст.",
              ["It's cold.", "The soup is cold, sorry."]),
            t("Oh, sorry! I'll change it.", "Оҳ, бубахшед! Иваз мекунам.", "Ташаккур гӯй", "Thank you.", "Ташаккур.",
              ["Thanks.", "Thank you very much."]),
            t("Anything else?", "Боз чизе?", "Бигӯ: боз як қаҳва", "One more coffee.", "Боз як қаҳва.",
              ["One more coffee, please.", "Another coffee."]),
        ]),
        ("Миссия: хӯроки пешин", [
            t("Hi! Are you ready to order?", "Салом! Фармоиш медиҳед?", "Бигӯ: ҳа, шӯрбои мурғ, лутфан",
              "Yes. Chicken soup, please.", "Ҳа. Шӯрбои мурғ, лутфан.", ["Chicken soup, please.", "Yes, chicken soup."]),
            t("Anything else?", "Боз чизе?", "Бигӯ: сандвич, бе гӯшти хук", "A sandwich, please. No pork.",
              "Сандвич, лутфан. Бе гӯшти хук.", ["A sandwich, no pork.", "I'd like a sandwich. No pork."]),
            t("Okay, chicken sandwich. Eight dollars.", "Хуб, сандвичи мурғ. Ҳашт доллар.",
              "Бипурс: тахфифи донишҷӯӣ ҳаст?", "Is there a student discount?", "Тахфифи донишҷӯӣ ҳаст?",
              ["Student discount?", "Discount for students?"]),
            t("Yes, ten percent. Seven twenty.", "Ҳа, даҳ фоиз. Ҳафт доллару бист.", "Ташаккур гӯй",
              "Great, thank you!", "Олӣ, ташаккур!", ["Thank you!", "Thanks!"]),
        ]),
    ]))

made.append(pack("bank_en_tg", "Bank and phone", "Бонк ва телефон", "🏦", 15, S,
    "Донишҷӯ дар хориҷ ҳисоби бонкӣ ва SIM-корт лозим дорад. Шумо ҳисоб мекушоед, тарифи "
    "телефонро мепурсед ва агар корт кор накунад — ёрӣ мепурсед.",
    [
        ("Бонк", [
            w("Bank", "бонк", None),
            w("Account", "ҳисоб", None),
            w("Card", "корт", None),
            w("SIM", "SIM-корт", "Корти хурди рақами телефон."),
            w("Money", "пул", None),
            w("PIN", "рамзи корт", "PIN — рамзи чаҳоррақамаи корт."),
            w("Internet", "интернет", None),
        ]),
        ("Чӣ лозим?", [
            t("Do you need a bank account?", "Ҳисоби бонкӣ лозим?", "Бигӯ, ки ҳа", "Yes.", "Ҳа.",
              ["Yes, please.", "Yes, I do."], "Кӯтоҳ ҷавоб диҳед."),
            t("A new phone or a SIM card?", "Телефони нав ё SIM-корт?", "Бигӯ: SIM-корт", "A SIM card.", "SIM-корт.",
              ["SIM card.", "Just a SIM card."]),
            t("Cash or card?", "Нақд ё корт?", "Бигӯ: корт", "Card.", "Корт.", ["By card.", "Card, please."]),
        ]),
        ("Ҳисоб", [
            s("Bank account", "Ҳисоби бонкӣ", None),
            s("SIM card", "SIM-корт", None),
            s("Every month", "Ҳар моҳ", None),
            s("More internet", "Интернети бештар", None),
            s("Student account", "Ҳисоби донишҷӯӣ", None),
            w("Plan", "тариф", None),
        ]),
        ("Дар бонк", [
            t("Hello! How can I help?", "Салом! Чӣ ёрӣ диҳам?", "Бигӯ: ҳисоби бонкӣ", "A bank account.", "Ҳисоби бонкӣ.",
              ["I need a bank account.", "Bank account, please."]),
            t("Okay. A student account?", "Хуб. Ҳисоби донишҷӯӣ?", "Бигӯ: ҳа, ҳисоби донишҷӯӣ",
              "Yes, a student account.", "Ҳа, ҳисоби донишҷӯӣ.", ["Yes.", "Yes, please."]),
            t("It's free for students.", "Барои донишҷӯён ройгон.", "Бигӯ: олӣ, ташаккур", "Great, thank you.",
              "Олӣ, ташаккур.", ["Great!", "Thanks."]),
        ]),
        ("Ман мепурсам", [
            s("I need an account.", "Ба ман ҳисоб лозим.", None),
            s("A SIM card, please.", "SIM-корт, лутфан.", None),
            s("How much a month?", "Дар як моҳ чанд?", None),
            s("How much internet?", "Интернет чанд?", None),
            s("Here is my passport.", "Ана шиносномаи ман.", None),
            s("Is it free?", "Ройгон аст?", None),
        ]),
        ("Мағозаи телефон", [
            t("Hi! What do you need?", "Салом! Чӣ лозим?", "Бигӯ: SIM-корт, лутфан", "A SIM card, please.",
              "SIM-корт, лутфан.", ["A SIM card.", "I need a SIM card."]),
            t("Okay. This plan is twenty dollars.", "Хуб. Ин тариф бист доллар.", "Бипурс: интернет чанд?",
              "How much internet?", "Интернет чанд?", ["How much data?", "And internet?"]),
            t("Ten gigabytes per month.", "Моҳе даҳ гигабайт.", "Бигӯ: хуб, инро мехоҳам", "Okay, I want it.",
              "Хуб, инро мехоҳам.", ["I'll take it.", "Okay."]),
        ]),
        ("Корт кор намекунад", [
            w("ATM", "банкомат", None),
            s("Where is an ATM?", "Банкомат куҷост?", None),
            s("My card doesn't work.", "Корти ман кор намекунад.", None),
            s("My PIN doesn't work.", "Рамзам кор намекунад.", "PIN — рамзи корт."),
            s("Pay by phone?", "Бо телефон пардохт?", None),
            s("Please help me.", "Лутфан, ёрӣ диҳед.", None),
        ]),
        ("Дар бонк", [
            t("Next! How can I help?", "Навбатӣ! Чӣ ёрӣ диҳам?", "Бигӯ: корти ман кор намекунад",
              "My card doesn't work.", "Корти ман кор намекунад.", ["My card is not working.", "The card doesn't work."]),
            t("Did you enter the right PIN?", "Рамзи дурустро ворид кардед?", "Бигӯ: рамзам кор намекунад",
              "My PIN doesn't work.", "Рамзам кор намекунад.", ["I forgot my PIN.", "It doesn't work."]),
            t("No problem. We can make a new one.", "Мушкил нест. Навашро месозем.", "Ташаккур гӯй",
              "Thank you very much.", "Ташаккури зиёд.", ["Thank you!", "Thanks a lot."]),
        ]),
        ("Миссия: ҳисоби бонкӣ", [
            t("Welcome! How can I help you?", "Хуш омадед! Чӣ ёрӣ диҳам?", "Бигӯ: ба ман ҳисоб лозим",
              "I need an account.", "Ба ман ҳисоб лозим.", ["I need a bank account.", "A bank account, please."]),
            t("Okay. Your passport, please.", "Хуб. Шиносномаатон, лутфан.", "Бигӯ: ана шиносномаи ман",
              "Here is my passport.", "Ана шиносномаи ман.", ["Here you go.", "Here."]),
            t("Thanks. Do you want a card too?", "Ташаккур. Корт ҳам мехоҳед?", "Бигӯ: ҳа ва бипурс дар як моҳ чанд",
              "Yes. How much a month?", "Ҳа. Дар як моҳ чанд?", ["Yes, please. How much?", "How much per month?"]),
            t("It's free for students.", "Барои донишҷӯён ройгон.", "Бигӯ: олӣ, ташаккур", "Great, thank you!",
              "Олӣ, ташаккур!", ["Great!", "Thank you!"]),
        ]),
    ]))

if MISSING:
    raise SystemExit('⛔ транскрипсия нест: ' + ', '.join(sorted(MISSING)))
print(' '.join(made))
