"""АНГЛИСӢ → тоҷикӣ, «Гуфтор» A1: нишаи «Хизматрасонӣ» (`service`) — 02.10.2026.

Коргари тоҷик дар мағоза, супермаркет ва қаҳвахона: рафҳо, касса, харидор,
тозакунӣ, мол, навбатҳо. 14 вазъияти махсус + «Кор ёфтан» (муштарак) + 5
вазъияти умумӣ = роҳи 20 вазъият (ҳамон тартиби «Сохтмон»: 1 салом, 2 кор
ёфтан, 6 духтур, 10 бозор, 14 иҷора, 16 ҳуҷҷат — умумӣ). Касб («{job}») —
«a salesperson».

Қоидаҳои A1 (аудити 02.10.2026, `prisma/_en-a1-strict-fix.py`):
  • гуфтори хонанда — замони ҳозира, фармон, can; гузашта танҳо «Got it»;
  • ҳар калимаи нав аввал дар дарси «Калимаҳо» ё «Ибораҳо»-и ҳамон вазъият
    (ё вазъияти пештараи роҳ) меояд, баъд дар ҷумла;
  • ҷумлаҳои ҳамсуҳбат кӯтоҳ, бе Present Perfect ва идиома.
Ҳамон қоидаҳои зина (`_en_packs_lib.py`): ≤2/≤2/≤4/≤8 калима, транскрипсия ҳатмӣ.
Номи мудир — Anna (дар ҳамаи вазъиятҳо як нафар).

Аз ҷузвдони backend: python prisma/_en-service-a1-packs.py
"""
from _en_packs_lib import *  # noqa: F401,F403

EXTRA.update({
    'manager': 'мэниҷэр', 'customer': 'кастэмэр', 'shelf': 'шелф', 'shelves': 'шелвз',
    'box': 'бокс', 'boxes': 'боксиз', 'shop': 'шоп', 'rice': 'райс', 'oil': 'ойл', 'eggs': 'егз',
    'top': 'топ', 'bottom': 'ботэм', 'clean': 'клин', 'close': 'клоуз', 'count': 'каунт',
    'moment': 'моумэнт', 'of': 'ов', 'course': 'корс', 'table': 'тейбэл', 'show': 'шоу',
    'aisle': 'айл', 'fruit': 'фрут', 'drinks': 'дринкс', 'follow': 'фолоу', 'ask': 'аск',
    'anything': 'енӣҫинг', 'else': 'елс', 'have': 'ҳэв', 'nice': 'найс', 'know': 'ноу',
    'change': 'чейндж', 'receipt': 'рисит', 'total': 'тоутэл', 'try': 'трай', 'cents': 'сентс',
    'half': 'ҳаф', 'sale': 'сейл', 'eleven': 'илевэн', 'nine': 'найн', 'cup': 'кап',
    'small': 'смол', 'large': 'лардж', 'sugar': 'шугэр', 'milk': 'милк', 'name': 'нейм',
    'enjoy': 'инджой', 'mop': 'моп', 'trash': 'трэш', 'wet': 'вет', 'dirty': 'дёртӣ',
    'toilets': 'тойлэтс', 'full': 'фул', 'delivery': 'диливэрӣ', 'list': 'лист',
    'nineteen': 'найнтин', 'driver': 'драйвэр', 'shirt': 'шёрт', 'apron': 'ейпрэн', 'cap': 'кэп',
    'shoes': 'шуз', 'badge': 'бэдж', 'medium': 'мидиэм', 'black': 'блэк', 'aprons': 'ейпрэнз',
    'return': 'ритёрн', 'old': 'оулд', 'back': 'бэк', 'fresh': 'фреш', 'shift': 'шифт',
    'shifts': 'шифтс', 'schedule': 'скеджул', 'anna': 'эннэ', 'tea': 'тӣ', 'coffee': 'кофӣ',
    'ready': 'редӣ', 'hot': 'ҳот', 'kilo': 'килоу', 'kilos': 'килоуз', 'about': 'эбаут',
    'three': 'ҫрӣ', 'twenty': 'твентӣ', 'four': 'фор', 'eight': 'эйт', 'lift': 'лифт',
    'size': 'сайз', 'wear': 'веэр', 'gloves': 'гловз', 'sick': 'сик', 'fever': 'фивэр',
    'hear': 'ҳир', 'home': 'ҳоум', 'very': 'верӣ', 'free': 'фрӣ', 'busy': 'бизӣ',
    "doesn't": 'дазнт', 'dollar': 'долар', 'finish': 'финиш', 'open': 'оупэн', 'sign': 'сайн', 'they': 'ҙей',
})

made = []
S = ["service"]

# ═════════════════════ 3. Рӯзи аввал дар мағоза ═════════════════════
made.append(pack("shop_en_tg", "First day at the shop", "Рӯзи аввал дар мағоза", "🏪", 3, S,
    "Рӯзи аввали кор дар мағоза. Мудир (Anna) вазифа медиҳад: қуттиҳоро ба раф гузоштан, "
    "халтаҳоро ҷо ба ҷо кардан. Шумо мефаҳмед, мепурсед ва ҷавоб медиҳед.",
    [
        ("Мағоза", [
            w("Shop", "мағоза", None),
            w("Manager", "мудир", "Сардори мағоза ё қаҳвахона."),
            w("Customer", "харидор", None),
            w("Shelf", "раф", None),
            w("Box", "қуттӣ", None),
            w("Bag", "халта", None),
        ]),
        ("Рӯзи аввал", [
            t("Are you the new worker?", "Ту коргари навӣ?", "Бигӯ, ки ҳа", "Yes.", "Ҳа.",
              ["Yes, I am.", "Yes, I'm new."], "Як калима кофист."),
            t("Do you see the manager?", "Мудирро мебинӣ?", "Бигӯ, ки не", "No.", "Не.",
              ["No, I don't.", "No, sorry."]),
            t("Is the box here?", "Қуттӣ ин ҷост?", "Бигӯ: ҳа, ин ҷо", "Yes, here.", "Ҳа, ин ҷо.",
              ["Here.", "It's here."]),
        ]),
        ("Ибораҳои рӯзи аввал", [
            s("New worker", "Коргари нав", None),
            s("First day", "Рӯзи аввал", None),
            w("Today", "имрӯз", None),
            w("Put", "гузоштан", None),
            s("Got it", "Фаҳмидам", "Ҷавоби маъмул дар кор."),
            s("Say again?", "Боз гӯед?", "Вақте нашунидед ё нафаҳмидед."),
        ]),
        ("Шинос бо мудир", [
            t("Hi! Is it your first day?", "Салом! Рӯзи аввали туст?", "Бигӯ: ҳа, рӯзи аввал",
              "Yes, first day.", "Ҳа, рӯзи аввал.", ["Yes, it's my first day.", "Yes."]),
            t("I'm Anna, the manager.", "Ман Анна, мудир.", "Салом гӯй: салом, Анна",
              "Hello, Anna.", "Салом, Анна.", ["Hi, Anna.", "Nice to meet you."]),
            t("Put the boxes on the shelf.", "Қуттиҳоро ба раф гузор.", "Бипурс: боз гӯед?",
              "Say again?", "Боз гӯед?", ["Sorry?", "Can you say that again?"]),
        ]),
        ("Ман мепурсам", [
            s("What do I do?", "Ман чӣ кор кунам?", "Саволи асосии рӯзи аввал."),
            s("Where is the manager?", "Мудир куҷост?", None,
              swaps=["manager|мудир", "box|қуттӣ", "bag|халта"]),
            s("I don't understand.", "Ман намефаҳмам.", "Беҳтар аст бигӯед, ки нафаҳмидед, аз он ки хато кунед."),
            s("Please say it again.", "Лутфан, боз гӯед.", None),
            s("Put it here?", "Ин ҷо гузорам?", None),
            w("Please", "лутфан", None),
        ]),
        ("Вазифаи аввал", [
            t("Good morning! Ready?", "Субҳ ба хайр! Тайёрӣ?", "Бигӯ, ки ҳа ва бипурс, ки чӣ кор кунӣ",
              "Yes. What do I do?", "Ҳа. Ман чӣ кор кунам?", ["What do I do?", "Yes, I'm ready. What do I do?"]),
            t("Put the bags on the shelf.", "Халтаҳоро ба раф гузор.", "Бипурс: ин ҷо гузорам?",
              "Put it here?", "Ин ҷо гузорам?", ["Here?", "On this shelf?"]),
            t("Yes, there. Thank you!", "Ҳа, он ҷо. Ташаккур!", "Бипурс: мудир куҷост?",
              "Where is the manager?", "Мудир куҷост?", ["Where's the manager?", "And the manager?"]),
        ]),
        ("Танаффус ва ёрӣ", [
            w("Break", "танаффус", None),
            s("What time is break?", "Танаффус соати чанд?", None),
            s("Where is the toilet?", "Ҳоҷатхона куҷост?", None),
            s("Can I have water?", "Об гирифта метавонам?", "Хушмуомила об хостан."),
            s("It's done.", "Тайёр шуд.", "Вақте кор тамом шуд."),
            w("Water", "об", None),
        ]),
        ("Танаффус кай?", [
            t("We work until one.", "То соати як кор мекунем.", "Бипурс: танаффус соати чанд?",
              "What time is break?", "Танаффус соати чанд?", ["When is break?", "Break at what time?"]),
            t("At one. Then lunch.", "Соати як. Баъд хӯроки пешин.", "Бипурс: ҳоҷатхона куҷост?",
              "Where is the toilet?", "Ҳоҷатхона куҷост?", ["Where's the toilet?", "Where is the bathroom?"]),
            t("Over there, on the left.", "Он ҷо, аз чап.", "Бигӯ: фаҳмидам, ташаккур",
              "Got it, thanks.", "Фаҳмидам, ташаккур.", ["Thank you.", "Okay, thanks."]),
        ]),
        ("Миссия: рӯзи аввал", [
            t("Hi! You're the new worker?", "Салом! Ту коргари навӣ?", "Бигӯ, ки ҳа ва бипурс, ки чӣ кор кунӣ",
              "Yes. What do I do?", "Ҳа. Ман чӣ кор кунам?", ["Yes. What should I do?", "Hi! What do I do?"]),
            t("Put the boxes on the shelf.", "Қуттиҳоро ба раф гузор.", "Бигӯ, ки намефаҳмӣ",
              "Sorry, I don't understand.", "Бубахшед, ман намефаҳмам.", ["I don't understand.", "Say again?"]),
            t("Boxes. Shelf. Okay?", "Қуттиҳо. Раф. Хуб?", "Бигӯ: фаҳмидам, ташаккур",
              "Got it. Thank you.", "Фаҳмидам. Ташаккур.", ["Okay, got it.", "Got it."]),
            t("Any questions?", "Савол ҳаст?", "Бипурс: танаффус соати чанд?",
              "What time is break?", "Танаффус соати чанд?", ["When is break?", "Yes. What time is break?"]),
        ]),
    ]))

# ═════════════════════ 4. Рафҳо ва мол ═════════════════════
made.append(pack("shelves_en_tg", "Shelves and products", "Рафҳо ва мол", "📦", 4, S,
    "Шумо молро ба рафҳо мегузоред: шир, нон, биринҷ, равған, тухм. Мегӯед, ки чӣ дар "
    "куҷост, раф холӣ шуд ё не, ва нархро ба харидор мегӯед.",
    [
        ("Мол", [
            w("Milk", "шир", None),
            w("Bread", "нон", None),
            w("Rice", "биринҷ", None),
            w("Oil", "равған", None),
            w("Eggs", "тухм", None),
            w("Price", "нарх", None),
        ]),
        ("Ин чист?", [
            t("Where is the milk?", "Шир куҷост?", "Бигӯ: ин ҷо", "Here.", "Ин ҷо.",
              ["It's here.", "Right here."], "Як калима кофист."),
            t("Is this rice?", "Ин биринҷ аст?", "Бигӯ, ки ҳа", "Yes.", "Ҳа.", ["Yes, it is.", "Yes, rice."]),
            t("Do we have eggs?", "Тухм дорем?", "Бигӯ, ки не", "No.", "Не.", ["No, we don't.", "No eggs."]),
        ]),
        ("Боло ва поён", [
            w("Top", "боло", None),
            s("Top shelf", "Рафи боло", None),
            w("Bottom", "поён", None),
            s("Bottom shelf", "Рафи поён", None),
            s("Two boxes", "Ду қуттӣ", None),
            s("More milk", "Шири бештар", None),
        ]),
        ("Куҷо гузорам?", [
            t("Where do the eggs go?", "Тухм ба куҷо меравад?", "Бигӯ: рафи боло", "Top shelf.", "Рафи боло.",
              ["On the top shelf.", "The top shelf."]),
            t("And the rice?", "Биринҷ чӣ?", "Бигӯ: рафи поён", "Bottom shelf.", "Рафи поён.",
              ["On the bottom shelf.", "The bottom shelf."]),
            t("How many boxes of oil?", "Чанд қуттӣ равған?", "Бигӯ: ду қуттӣ", "Two boxes.", "Ду қуттӣ.",
              ["Two.", "Two boxes of oil."]),
        ]),
        ("Ман мегӯям", [
            s("Where does it go?", "Ин ба куҷо меравад?", None),
            s("The milk is here.", "Шир ин ҷост.", None, swaps=["milk|шир", "bread|нон", "rice|биринҷ"]),
            s("We need more milk.", "Ба мо шири бештар лозим.", None),
            s("On the top shelf.", "Дар рафи боло.", None),
            w("Empty", "холӣ", None),
            s("The shelf is empty.", "Раф холист.", None),
        ]),
        ("Раф холист", [
            t("Take this box.", "Ин қуттиро гир.", "Бипурс: ин ба куҷо меравад?", "Where does it go?",
              "Ин ба куҷо меравад?", ["Where?", "Where do I put it?"]),
            t("Milk. Look at the shelf.", "Шир. Ба раф нигоҳ кун.", "Бигӯ: раф холист",
              "The shelf is empty.", "Раф холист.", ["It's empty.", "The shelf is empty!"]),
            t("Oh! What do we need?", "Оҳ! Ба мо чӣ лозим?", "Бигӯ: ба мо шири бештар лозим",
              "We need more milk.", "Ба мо шири бештар лозим.", ["More milk.", "We need milk."]),
        ]),
        ("Нарх", [
            s("What's the price?", "Нархаш чанд?", None),
            w("Cheap", "арзон", None),
            s("Is it cheap?", "Арзон аст?", None),
            w("Expensive", "қимат", None),
            s("It's very expensive.", "Хеле қимат аст.", None),
            s("Two dollars.", "Ду доллар.", None, swaps=["two|ду", "five|панҷ", "ten|даҳ"]),
        ]),
        ("Харидор мепурсад", [
            t("Excuse me, where is the bread?", "Бубахшед, нон куҷост?", "Бигӯ: дар рафи боло",
              "On the top shelf.", "Дар рафи боло.", ["Top shelf.", "It's on the top shelf."]),
            t("Thank you. What's the price?", "Ташаккур. Нархаш чанд?", "Бигӯ: ду доллар",
              "Two dollars.", "Ду доллар.", ["It's two dollars.", "Two."]),
            t("Oh, it's cheap!", "Оҳ, арзон!", "Бигӯ: ҳа, арзон", "Yes, it's cheap.", "Ҳа, арзон.",
              ["Yes.", "Yes, very cheap."]),
        ]),
        ("Миссия: раф холӣ", [
            t("Hi. Can you help? The shelf is empty.", "Салом. Ёрӣ медиҳӣ? Раф холист.",
              "Бипурс: ба мо чӣ лозим?", "What do we need?", "Ба мо чӣ лозим?",
              ["What do you need?", "Okay. What do we need?"]),
            t("Milk and eggs.", "Шир ва тухм.", "Бигӯ: фаҳмидам. ду қуттӣ?", "Got it. Two boxes?",
              "Фаҳмидам. Ду қуттӣ?", ["Two boxes?", "Okay. Two boxes?"]),
            t("Yes. Eggs on the top shelf.", "Ҳа. Тухм дар рафи боло.", "Бигӯ: фаҳмидам, рафи боло",
              "Got it. Top shelf.", "Фаҳмидам. Рафи боло.", ["Okay, top shelf.", "Top shelf. Okay."]),
            t("And the milk is two dollars.", "Ва шир ду доллар.", "Бигӯ: хуб, ду доллар",
              "Okay, two dollars.", "Хуб, ду доллар.", ["Two dollars. Okay.", "Okay."]),
        ]),
    ]))

# ═════════════════════ 5. Мудир мегӯяд ═════════════════════
made.append(pack("mgr_en_tg", "Manager's orders", "Мудир мегӯяд", "🧑‍💼", 5, S,
    "Мудир фармон медиҳад: тоза кун, кушо, пӯш, шумор, интизор шав. Баъзан зуд ва "
    "кӯтоҳ мегӯяд. Шумо ҷавоб медиҳед, мепурсед ва хоҳиш мекунед, ки нишон диҳад.",
    [
        ("Фармонҳо", [
            w("Clean", "тоза кардан", None),
            w("Open", "кушодан", None),
            w("Close", "пӯшидан (бастан)", None),
            w("Count", "шумурдан", None),
            w("Help", "ёрӣ додан", None),
            w("Wait", "интизор шудан", None),
        ]),
        ("Ёрӣ медиҳӣ?", [
            t("Can you help me?", "Ёрӣ дода метавонӣ?", "Бигӯ, ки ҳа", "Yes.", "Ҳа.",
              ["Yes, sure.", "Sure."], "Як калима кофист."),
            t("Is the door open?", "Дар кушода аст?", "Бигӯ, ки не", "No.", "Не.",
              ["No, it's closed.", "Not open."]),
            t("Wait here, okay?", "Ин ҷо интизор шав, хуб?", "Бигӯ: хуб", "Okay.", "Хуб.",
              ["Okay, I can wait.", "Sure."]),
        ]),
        ("Зуд!", [
            s("Right now", "Ҳозир", None),
            w("Quickly", "зуд", None),
            s("Come here", "Ин ҷо биё", None),
            s("One moment", "Як лаҳза", None),
            s("No problem", "Мушкил нест", None),
            s("Of course", "Албатта", None),
        ]),
        ("Мудир даъват мекунад", [
            t("Come here, please.", "Лутфан, ин ҷо биё.", "Бигӯ: як лаҳза", "One moment.", "Як лаҳза.",
              ["Coming!", "One moment, please."]),
            t("Clean this table, please.", "Лутфан, ин мизро тоза кун.", "Бигӯ: мушкил нест",
              "No problem.", "Мушкил нест.", ["Okay.", "Of course."]),
            t("Right now, please. Quickly!", "Ҳозир, лутфан. Зуд!", "Бигӯ: албатта", "Of course.", "Албатта.",
              ["Okay.", "Sure."]),
        ]),
        ("Ман мегӯям", [
            w("Table", "миз", None),
            s("I clean the table.", "Ман мизро тоза мекунам.", None),
            s("Open the door?", "Дарро кушоям?", None),
            s("I count the money.", "Ман пулро мешуморам.", None),
            s("I can help.", "Ман ёрӣ дода метавонам.", None),
            s("Right now?", "Ҳозир?", None),
        ]),
        ("Кор зиёд", [
            t("Can you help me now?", "Ҳозир ёрӣ дода метавонӣ?", "Бигӯ: ҳа, ман ёрӣ дода метавонам",
              "Yes, I can help.", "Ҳа, ман ёрӣ дода метавонам.", ["Yes, I can.", "Sure, I can help."]),
            t("Good. Clean the tables.", "Хуб. Мизҳоро тоза кун.", "Бипурс: ҳозир?", "Right now?", "Ҳозир?",
              ["Now?", "Okay. Right now?"]),
            t("Yes, now. Then count the money.", "Ҳа, ҳозир. Баъд пулро шумор.", "Бигӯ: мушкил нест",
              "No problem.", "Мушкил нест.", ["Okay.", "Of course."]),
        ]),
        ("Нишон диҳед", [
            w("Show", "нишон додан", None),
            s("Show me, please.", "Лутфан, нишон диҳед.", None),
            s("Like this?", "Ин хел?", None),
            s("Is it okay?", "Хуб аст?", None),
            s("I'm sorry.", "Бубахшед.", None),
            s("Wait one moment.", "Як лаҳза сабр кунед.", None),
        ]),
        ("Ин хел не", [
            t("No, no. Not like that.", "Не, не. Ин хел не.", "Бигӯ: бубахшед. лутфан, нишон диҳед",
              "Sorry. Show me, please.", "Бубахшед. Лутфан, нишон диҳед.", ["Show me, please.", "I'm sorry. Show me."]),
            t("Look. Clean it like this.", "Бин. Ин хел тоза кун.", "Бипурс: ин хел?", "Like this?", "Ин хел?",
              ["Like this? Okay.", "Is it okay?"]),
            t("Yes! Good job.", "Ҳа! Офарин.", "Ташаккур гӯй", "Thank you.", "Ташаккур.",
              ["Thanks!", "Thank you very much."]),
        ]),
        ("Миссия: фармони мудир", [
            t("Hey! Can you help me?", "Эй! Ёрӣ дода метавонӣ?", "Бигӯ: ҳа, ман ёрӣ дода метавонам",
              "Yes, I can help.", "Ҳа, ман ёрӣ дода метавонам.", ["Yes, I can.", "Sure."]),
            t("Clean the table. Quickly!", "Мизро тоза кун. Зуд!", "Бигӯ: албатта, ҳозир",
              "Of course. Right now.", "Албатта. Ҳозир.", ["Right now.", "Okay, right now."]),
            t("Not like that!", "Ин хел не!", "Бигӯ: бубахшед. лутфан, нишон диҳед",
              "Sorry. Show me, please.", "Бубахшед. Лутфан, нишон диҳед.", ["Show me, please.", "Sorry. Like this?"]),
            t("Like this. Okay?", "Ин хел. Хуб?", "Бигӯ: фаҳмидам, ташаккур", "Got it. Thank you.",
              "Фаҳмидам. Ташаккур.", ["Okay, thanks.", "Got it."]),
        ]),
    ]))

# ═════════════════════ 7. Харидор меҷӯяд ═════════════════════
made.append(pack("aisle_en_tg", "Helping customers", "Харидор меҷӯяд", "🔎", 7, S,
    "Харидор мепурсад, ки мол дар куҷост. Шумо қатор (aisle) ва тарафро мегӯед, роҳро "
    "нишон медиҳед ё мегӯед, ки ин мол нест — ва хушмуомила хайрухуш мекунед.",
    [
        ("Дар мағоза", [
            w("Aisle", "қатор (байни рафҳо)", "Талаффуз: «айл», ҳарфи s хонда намешавад."),
            w("Left", "чап", None),
            w("Right", "рост", None),
            w("Fruit", "мева", None),
            w("Meat", "гӯшт", None),
            w("Drinks", "нӯшокӣ", None),
        ]),
        ("Куҷост?", [
            t("Excuse me, fruit?", "Бубахшед, мева?", "Бигӯ: аз чап", "Left.", "Аз чап.",
              ["On the left.", "It's on the left."], "Як калима кофист."),
            t("And meat?", "Гӯшт чӣ?", "Бигӯ: аз рост", "Right.", "Аз рост.",
              ["On the right.", "It's on the right."]),
            t("Do you have drinks?", "Нӯшокӣ доред?", "Бигӯ, ки ҳа", "Yes.", "Ҳа.",
              ["Yes, we do.", "Yes, here."]),
        ]),
        ("Қатор ва роҳ", [
            s("Aisle five", "Қатори панҷ", None),
            s("Aisle two", "Қатори ду", None),
            s("This way", "Ин тараф", None),
            s("Follow me", "Аз паи ман биёед", None),
            s("Over there", "Он ҷо", None),
            w("Sorry", "бубахшед", None),
        ]),
        ("Роҳ нишон медиҳам", [
            t("Where is the rice?", "Биринҷ куҷост?", "Бигӯ: қатори панҷ", "Aisle five.", "Қатори панҷ.",
              ["In aisle five.", "It's in aisle five."]),
            t("Sorry, where?", "Бубахшед, куҷо?", "Бигӯ: аз паи ман биёед", "Follow me.", "Аз паи ман биёед.",
              ["Come with me.", "This way."]),
            t("Thank you so much!", "Ташаккури зиёд!", "Бигӯ: мушкил нест", "No problem.", "Мушкил нест.",
              ["You're welcome.", "Okay."]),
        ]),
        ("Ман мегӯям", [
            s("Can I help you?", "Ёрӣ диҳам?", "Аввалин саволи фурӯшанда."),
            s("It's in aisle five.", "Дар қатори панҷ.", None, swaps=["five|панҷ", "two|ду", "three|се"]),
            s("This way, please.", "Ин тараф, лутфан.", None),
            s("It's over there.", "Он ҷост.", None),
            s("We don't have it.", "Мо инро надорем.", None),
            s("Sorry, I don't know.", "Бубахшед, намедонам.", None),
        ]),
        ("Тухм куҷост?", [
            t("Hi! I need eggs.", "Салом! Ба ман тухм лозим.", "Бигӯ: дар қатори ду", "It's in aisle two.",
              "Дар қатори ду.", ["Aisle two.", "In aisle two."]),
            t("Aisle two? Where is it?", "Қатори ду? Куҷост?", "Бигӯ: ин тараф, лутфан", "This way, please.",
              "Ин тараф, лутфан.", ["Follow me.", "Over there."]),
            t("Do you have coffee?", "Қаҳва доред?", "Бигӯ: бубахшед, мо инро надорем",
              "Sorry, we don't have it.", "Бубахшед, мо инро надорем.", ["Sorry, no.", "We don't have it."]),
        ]),
        ("Хушмуомила", [
            s("What do you need?", "Ба шумо чӣ лозим?", None),
            s("Anything else?", "Боз чизе?", None),
            w("Ask", "пурсидан", None),
            s("I can ask.", "Ман пурсида метавонам.", None),
            s("One moment, please.", "Як лаҳза, лутфан.", None),
            s("Have a nice day!", "Рӯзи хуш!", None),
        ]),
        ("Ман намедонам", [
            t("Excuse me! Help, please.", "Бубахшед! Ёрӣ, лутфан.", "Бипурс: ба шумо чӣ лозим?",
              "What do you need?", "Ба шумо чӣ лозим?", ["Can I help you?", "Yes? What do you need?"]),
            t("Do you have green tea?", "Чойи кабуд доред?", "Бигӯ: бубахшед, намедонам. ман пурсида метавонам",
              "Sorry, I don't know. I can ask.", "Бубахшед, намедонам. Пурсида метавонам.",
              ["I don't know. One moment, please.", "Sorry. I can ask."]),
            t("Thanks. That's all.", "Ташаккур. Ҳамааш.", "Бигӯ: рӯзи хуш!", "Have a nice day!", "Рӯзи хуш!",
              ["Have a good day!", "Bye!"]),
        ]),
        ("Миссия: ёрӣ ба харидор", [
            t("Excuse me!", "Бубахшед!", "Бипурс: ёрӣ диҳам?", "Can I help you?", "Ёрӣ диҳам?",
              ["Yes? Can I help you?", "What do you need?"]),
            t("Where is the milk?", "Шир куҷост?", "Бигӯ: дар қатори панҷ", "It's in aisle five.",
              "Дар қатори панҷ.", ["Aisle five.", "In aisle five."]),
            t("Sorry, where is aisle five?", "Бубахшед, қатори панҷ куҷост?", "Бигӯ: лутфан, аз паи ман биёед",
              "Follow me, please.", "Лутфан, аз паи ман биёед.", ["This way, please.", "Follow me."]),
            t("Thank you!", "Ташаккур!", "Бипурс: боз чизе?", "Anything else?", "Боз чизе?",
              ["Anything else? No?", "You're welcome. Anything else?"]),
        ]),
    ]))

# ═════════════════════ 8. Дар касса ═════════════════════
made.append(pack("till_en_tg", "At the till", "Дар касса", "💳", 8, S,
    "Шумо дар касса кор мекунед: нархро мегӯед, мепурсед нақд ё корт, бақия ва чекро "
    "медиҳед. Агар корт кор накунад — оромона мегӯед, ки боз кӯшиш кунад.",
    [
        ("Касса", [
            w("Cash", "пули нақд", None),
            w("Card", "корт", None),
            w("Change", "бақия (пули гардон)", None),
            w("Receipt", "чек", "Талаффуз: «рисит», ҳарфи p хонда намешавад."),
            w("Total", "ҳамагӣ", None),
            w("Next", "навбатӣ", None),
        ]),
        ("Нақд ё корт?", [
            t("Cash or card?", "Нақд ё корт?", "Бигӯ: корт", "Card.", "Корт.",
              ["By card.", "Card, please."], "Як калима кофист."),
            t("Do you need a bag?", "Халта лозим?", "Бигӯ, ки не", "No.", "Не.", ["No, thanks.", "No bag."]),
            t("Receipt?", "Чек?", "Бигӯ, ки ҳа", "Yes.", "Ҳа.", ["Yes, please.", "Yes, thanks."]),
        ]),
        ("Ибораҳои касса", [
            s("By card", "Бо корт", None),
            s("In cash", "Нақд", None),
            s("Your change", "Бақияатон", None),
            s("Your receipt", "Чекатон", None),
            s("Ten dollars", "Даҳ доллар", None),
            s("Next, please", "Навбатӣ, лутфан", None),
        ]),
        ("Харидори аввал", [
            t("Hello! Can I pay here?", "Салом! Ин ҷо пардохт кардан мумкин?", "Бигӯ: ҳа. навбатӣ, лутфан",
              "Yes. Next, please.", "Ҳа. Навбатӣ, лутфан.", ["Next, please.", "Yes, please."]),
            t("How much is it?", "Чанд пул?", "Бигӯ: даҳ доллар", "Ten dollars.", "Даҳ доллар.",
              ["It's ten dollars.", "Ten."]),
            t("Here. In cash.", "Ана. Нақд.", "Бигӯ: бақияатон", "Your change.", "Бақияатон.",
              ["Here's your change.", "Your change, please."]),
        ]),
        ("Ман мегӯям", [
            s("Cash or card?", "Нақд ё корт?", None),
            s("That's ten dollars.", "Даҳ доллар мешавад.", None, swaps=["ten|даҳ", "five|панҷ", "twenty|бист"]),
            s("Here's your change.", "Ана бақияатон.", None),
            s("Here's your receipt.", "Ана чекатон.", None),
            s("Need a bag?", "Халта лозим?", None),
            s("Put your card here.", "Кортатонро ин ҷо гузоред.", None),
        ]),
        ("Пардохт бо корт", [
            t("Hi! Just this water.", "Салом! Танҳо ҳамин об.", "Бигӯ: як доллар. нақд ё корт?",
              "One dollar. Cash or card?", "Як доллар. Нақд ё корт?", ["Cash or card?", "One dollar, please."]),
            t("Card, please.", "Корт, лутфан.", "Бигӯ: кортатонро ин ҷо гузоред", "Put your card here.",
              "Кортатонро ин ҷо гузоред.", ["Your card here, please.", "Here, please."]),
            t("Okay. Done?", "Хуб. Шуд?", "Бигӯ: ҳа. ана чекатон", "Yes. Here's your receipt.",
              "Ҳа. Ана чекатон.", ["Here's your receipt.", "Yes, thank you."]),
        ]),
        ("Корт кор намекунад", [
            w("Try", "кӯшиш кардан", None),
            s("The card doesn't work.", "Корт кор намекунад.", None),
            s("Try again, please.", "Лутфан, боз кӯшиш кунед.", None),
            s("It's okay now.", "Ҳоло хуб аст.", None),
            s("Thank you. Bye!", "Ташаккур. Хайр!", None),
            s("One more time.", "Боз як бор.", None),
        ]),
        ("Боз кӯшиш кунед", [
            t("Card, please. Oh no!", "Корт, лутфан. Оҳ не!", "Бигӯ: корт кор намекунад",
              "The card doesn't work.", "Корт кор намекунад.", ["It doesn't work.", "Sorry, the card doesn't work."]),
            t("Oh. What do I do?", "Оҳ. Чӣ кор кунам?", "Бигӯ: лутфан, боз кӯшиш кунед",
              "Try again, please.", "Лутфан, боз кӯшиш кунед.", ["One more time, please.", "Please try again."]),
            t("Is it okay now?", "Ҳоло хуб аст?", "Бигӯ: ҳа, ҳоло хуб аст. ташаккур",
              "Yes, it's okay now. Thank you.", "Ҳа, ҳоло хуб аст. Ташаккур.", ["It's okay now.", "Yes. Thank you."]),
        ]),
        ("Миссия: дар касса", [
            t("Hello! Can I pay here?", "Салом! Ин ҷо пардохт кардан мумкин?", "Бигӯ: ҳа. нақд ё корт?",
              "Yes. Cash or card?", "Ҳа. Нақд ё корт?", ["Cash or card?", "Yes, please. Cash or card?"]),
            t("Cash. How much?", "Нақд. Чанд?", "Бигӯ: даҳ доллар мешавад", "That's ten dollars.",
              "Даҳ доллар мешавад.", ["Ten dollars.", "It's ten dollars."]),
            t("Here's twenty.", "Ана бист.", "Бигӯ: ана бақияатон. халта лозим?",
              "Here's your change. Need a bag?", "Ана бақияатон. Халта лозим?", ["Your change. A bag?", "Here's your change."]),
            t("No, thanks.", "Не, ташаккур.", "Бигӯ: ана чекатон. хайр!", "Here's your receipt. Bye!",
              "Ана чекатон. Хайр!", ["Your receipt. Have a nice day!", "Thank you. Bye!"]),
        ]),
    ]))

# ═════════════════════ 9. Нарх ва шумора ═════════════════════
made.append(pack("prices_en_tg", "Prices and numbers", "Нарх ва шумора", "🏷️", 9, S,
    "Харидор нарх мепурсад: доллар ва сент, тахфиф, нисфи нарх, кило. Шумо рақамро "
    "дуруст ва равшан мегӯед ва ҳамагиро ҳисоб мекунед.",
    [
        ("Пул ва нарх", [
            w("Dollars", "доллар", None),
            w("Cents", "сент", "Як доллар — сад сент."),
            w("Half", "нисф", None),
            w("Sale", "тахфиф", "«On sale» — бо тахфиф, арзонтар аз нархи муқаррарӣ."),
            w("Free", "ройгон", None),
            w("Kilo", "кило", None),
        ]),
        ("Ин чанд?", [
            t("How much is this?", "Ин чанд пул?", "Бигӯ: панҷ доллар", "Five dollars.", "Панҷ доллар.",
              ["It's five dollars.", "Five."], "Кӯтоҳ ҷавоб диҳед."),
            t("Is it on sale?", "Тахфиф дорад?", "Бигӯ, ки ҳа", "Yes.", "Ҳа.", ["Yes, it is.", "Yes, on sale."]),
            t("Is the bag free?", "Халта ройгон аст?", "Бигӯ, ки не", "No.", "Не.", ["No, it's not.", "No, sorry."]),
        ]),
        ("Рақамҳо", [
            s("Fifty cents", "Панҷоҳ сент", None),
            s("Half price", "Нисфи нарх", None),
            s("On sale", "Бо тахфиф", None),
            s("Five dollars", "Панҷ доллар", None),
            s("Very cheap", "Хеле арзон", None),
            s("Per kilo", "Барои як кило", None),
        ]),
        ("Арзон аст?", [
            t("Is this cheap?", "Ин арзон аст?", "Бигӯ: нисфи нарх", "Half price.", "Нисфи нарх.",
              ["Yes, half price.", "It's half price."]),
            t("And the bread?", "Нон чӣ?", "Бигӯ: панҷоҳ сент", "Fifty cents.", "Панҷоҳ сент.",
              ["It's fifty cents.", "Fifty."]),
            t("Are the apples on sale?", "Себҳо тахфиф доранд?", "Бигӯ: ҳа, бо тахфиф", "Yes, on sale.",
              "Ҳа, бо тахфиф.", ["On sale.", "Yes, they are."]),
        ]),
        ("Ман мегӯям", [
            s("It's on sale.", "Бо тахфиф аст.", None),
            s("It's half price.", "Нисфи нарх аст.", None),
            s("Nine dollars, please.", "Нӯҳ доллар, лутфан.", None, swaps=["nine|нӯҳ", "six|шаш", "twelve|дувоздаҳ"]),
            s("Apples are two dollars.", "Себ ду доллар.", None),
            s("Three dollars a kilo.", "Килояш се доллар.", None),
            w("Apples", "себ", None),
        ]),
        ("Себ ва шир", [
            t("How much are the apples?", "Себҳо чанд пул?", "Бигӯ: килояш се доллар",
              "Three dollars a kilo.", "Килояш се доллар.", ["Three dollars.", "Three a kilo."]),
            t("Is the milk on sale?", "Шир тахфиф дорад?", "Бигӯ: ҳа, нисфи нарх аст", "Yes, it's half price.",
              "Ҳа, нисфи нарх аст.", ["Half price.", "Yes, on sale."]),
            t("Great! How much in total?", "Олӣ! Ҳамагӣ чанд?", "Бигӯ: нӯҳ доллар, лутфан",
              "Nine dollars, please.", "Нӯҳ доллар, лутфан.", ["Nine dollars.", "It's nine dollars."]),
        ]),
        ("Чанд то?", [
            s("How many?", "Чанд то?", None),
            s("One or two?", "Як ё ду?", None),
            s("It's free.", "Ройгон аст.", None),
            w("Hundred", "сад", None),
            s("One hundred dollars.", "Сад доллар.", None),
            s("Sorry, it's not free.", "Бубахшед, ройгон нест.", None),
        ]),
        ("Халта ройгон?", [
            t("I need some bags.", "Ба ман якчанд халта лозим.", "Бипурс: чанд то?", "How many?", "Чанд то?",
              ["How many bags?", "One or two?"]),
            t("Three. Are they free?", "Се то. Ройгон?", "Бигӯ: бубахшед, ройгон нест",
              "Sorry, it's not free.", "Бубахшед, ройгон нест.", ["No, sorry.", "They're not free."]),
            t("How much?", "Чанд?", "Бигӯ: панҷоҳ сент", "Fifty cents.", "Панҷоҳ сент.",
              ["Fifty cents each.", "It's fifty cents."]),
        ]),
        ("Миссия: нарх мепурсанд", [
            t("Hi! How much is this oil?", "Салом! Ин равған чанд пул?", "Бигӯ: панҷ доллар. бо тахфиф аст",
              "Five dollars. It's on sale.", "Панҷ доллар. Бо тахфиф аст.", ["Five dollars.", "It's on sale. Five dollars."]),
            t("Good! And the apples?", "Хуб! Себҳо чӣ?", "Бигӯ: килояш се доллар", "Three dollars a kilo.",
              "Килояш се доллар.", ["Three dollars.", "Three a kilo."]),
            t("Two kilos, please. Total?", "Ду кило, лутфан. Ҳамагӣ?", "Бигӯ: ёздаҳ доллар, лутфан",
              "Eleven dollars, please.", "Ёздаҳ доллар, лутфан.", ["Eleven dollars.", "It's eleven dollars."]),
            t("Here you are.", "Марҳамат.", "Бигӯ: ташаккур. рӯзи хуш!", "Thank you. Have a nice day!",
              "Ташаккур. Рӯзи хуш!", ["Thanks! Have a nice day!", "Thank you!"]),
        ]),
    ]))

# ═════════════════════ 11. Дар қаҳвахона ═════════════════════
made.append(pack("counter_en_tg", "At the café counter", "Дар қаҳвахона", "☕", 11, S,
    "Шумо дар пештахтаи қаҳвахона кор мекунед: фармоиш мегиред, мепурсед хурд ё калон, "
    "бо шир ё бе шакар, барои ин ҷо ё барои бурдан — ва нӯшокиро медиҳед.",
    [
        ("Пештахта", [
            w("Cup", "пиёла", None),
            w("Small", "хурд", None),
            w("Large", "калон", None),
            w("Tea", "чой", None),
            w("Coffee", "қаҳва", None),
            w("Sugar", "шакар", None),
        ]),
        ("Фармоиши кӯтоҳ", [
            t("Small or large?", "Хурд ё калон?", "Бигӯ: калон", "Large.", "Калон.",
              ["Large, please.", "A large one."], "Як калима кофист."),
            t("Tea or coffee?", "Чой ё қаҳва?", "Бигӯ: чой", "Tea.", "Чой.", ["Tea, please.", "Tea for me."]),
            t("With sugar?", "Бо шакар?", "Бигӯ, ки не", "No.", "Не.", ["No sugar.", "No, thanks."]),
        ]),
        ("Ибораҳо", [
            s("To go", "Барои бурдан", None),
            s("For here", "Барои ин ҷо", None),
            s("No sugar", "Бе шакар", None),
            s("With milk", "Бо шир", None),
            s("Large coffee", "Қаҳваи калон", None),
            s("Your name?", "Номатон?", "Дар қаҳвахона номро ба пиёла менависанд."),
        ]),
        ("Фармоиш мегирам", [
            t("A coffee, please.", "Як қаҳва, лутфан.", "Бипурс: хурд ё калон?", "Small or large?",
              "Хурд ё калон?", ["Small or large coffee?", "What size?"]),
            t("Large, please.", "Калон, лутфан.", "Бипурс: барои ин ҷо ё барои бурдан?",
              "For here or to go?", "Барои ин ҷо ё барои бурдан?", ["To go?", "For here?"]),
            t("To go.", "Барои бурдан.", "Бипурс: номатон?", "Your name?", "Номатон?",
              ["What's your name?", "And your name?"]),
        ]),
        ("Ман мегӯям", [
            s("Coffee with milk?", "Қаҳва бо шир?", None),
            s("For here?", "Барои ин ҷо?", None),
            s("Your coffee is ready.", "Қаҳваатон тайёр.", None, swaps=["coffee|қаҳва", "tea|чой"]),
            s("That's four dollars.", "Чор доллар мешавад.", None),
            w("Ready", "тайёр", None),
            s("One moment, please.", "Як лаҳза, лутфан.", None),
        ]),
        ("Чой бо шир?", [
            t("Can I have a tea?", "Як чой гирифта метавонам?", "Бипурс: бо шир?", "With milk?", "Бо шир?",
              ["Tea with milk?", "Milk?"]),
            t("No milk. How much?", "Бе шир. Чанд пул?", "Бигӯ: чор доллар мешавад", "That's four dollars.",
              "Чор доллар мешавад.", ["Four dollars.", "It's four dollars."]),
            t("Here you are.", "Марҳамат.", "Бигӯ: ташаккур. як лаҳза, лутфан", "Thank you. One moment, please.",
              "Ташаккур. Як лаҳза, лутфан.", ["One moment, please.", "Thanks."]),
        ]),
        ("Нӯшокӣ тайёр", [
            w("Hot", "гарм", None),
            s("It's very hot.", "Хеле гарм аст.", None),
            s("Here's your tea.", "Ана чойатон.", None),
            s("Sugar is here.", "Шакар ин ҷост.", None),
            s("Sorry, no milk.", "Бубахшед, шир нест.", None),
            s("Enjoy your coffee!", "Қаҳваи гуворо!", "Вақте нӯшокиро медиҳед."),
        ]),
        ("Қаҳвааш гарм", [
            t("Is my coffee ready?", "Қаҳваи ман тайёр?", "Бигӯ: ҳа. ана қаҳваатон", "Yes. Here's your coffee.",
              "Ҳа. Ана қаҳваатон.", ["Here's your coffee.", "Yes, it's ready."]),
            t("Thanks! Is it hot?", "Ташаккур! Гарм аст?", "Бигӯ: ҳа, хеле гарм аст", "Yes, it's very hot.",
              "Ҳа, хеле гарм аст.", ["Very hot.", "Yes, it's hot."]),
            t("Where is the sugar?", "Шакар куҷост?", "Бигӯ: шакар ин ҷост", "Sugar is here.", "Шакар ин ҷост.",
              ["It's here.", "Here."]),
        ]),
        ("Миссия: фармоиши қаҳва", [
            t("Hi! A coffee, please.", "Салом! Як қаҳва, лутфан.", "Бипурс: хурд ё калон?", "Small or large?",
              "Хурд ё калон?", ["What size?", "Small or large coffee?"]),
            t("Small. With milk.", "Хурд. Бо шир.", "Бипурс: барои ин ҷо ё барои бурдан?", "For here or to go?",
              "Барои ин ҷо ё барои бурдан?", ["To go?", "For here?"]),
            t("To go. How much?", "Барои бурдан. Чанд пул?", "Бигӯ: се доллар мешавад", "That's three dollars.",
              "Се доллар мешавад.", ["Three dollars.", "It's three dollars."]),
            t("Thank you!", "Ташаккур!", "Бигӯ: ана қаҳваатон. қаҳваи гуворо!", "Here's your coffee. Enjoy!",
              "Ана қаҳваатон. Гуворо бошад!", ["Here's your coffee.", "Enjoy your coffee!"]),
        ]),
    ]))

# ═════════════════════ 12. Тозакунӣ ═════════════════════
made.append(pack("cleaning_en_tg", "Cleaning", "Тозакунӣ", "🧽", 12, S,
    "Пас аз кор ё дар миёнаи рӯз тоза мекунед: фарш, ошхона, ҳоҷатхона, партов. Шумо "
    "асбоб мепурсед, мегӯед, ки фарш тар аст, ва хабар медиҳед, ки ҳама тоза шуд.",
    [
        ("Тозагӣ", [
            w("Mop", "швабра", None),
            w("Trash", "партов", None),
            w("Floor", "фарш", None),
            w("Dirty", "чиркин", None),
            w("Wet", "тар", None),
            w("Gloves", "дастпӯшак", None),
        ]),
        ("Чӣ хел аст?", [
            t("Is the floor wet?", "Фарш тар аст?", "Бигӯ, ки ҳа", "Yes.", "Ҳа.",
              ["Yes, it's wet.", "Yes, careful."], "Як калима кофист."),
            t("Is this table dirty?", "Ин миз чиркин аст?", "Бигӯ, ки не", "No.", "Не.",
              ["No, it's clean.", "No, it's okay."]),
            t("Where is the mop?", "Швабра куҷост?", "Бигӯ: ин ҷо", "Here.", "Ин ҷо.", ["It's here.", "Right here."]),
        ]),
        ("Ибораҳо", [
            s("Wet floor", "Фарши тар", None),
            s("Take out", "Берун бурдан", None),
            s("The trash", "Партов", None),
            s("Very dirty", "Хеле чиркин", None),
            s("All clean", "Ҳама тоза", None),
            s("Be careful", "Эҳтиёт бошед", None),
        ]),
        ("Фарш тар", [
            t("Careful! What's that?", "Эҳтиёт! Ин чист?", "Бигӯ: фарши тар", "Wet floor.", "Фарши тар.",
              ["The floor is wet.", "It's wet."]),
            t("Is the kitchen dirty?", "Ошхона чиркин аст?", "Бигӯ: хеле чиркин", "Very dirty.", "Хеле чиркин.",
              ["Yes, very dirty.", "Yes."]),
            t("And now?", "Ҳоло чӣ?", "Бигӯ: ҳама тоза", "All clean.", "Ҳама тоза.", ["It's all clean.", "Clean now."]),
        ]),
        ("Ман мегӯям", [
            s("I clean the floor.", "Ман фаршро тоза мекунам.", None, swaps=["floor|фарш", "kitchen|ошхона"]),
            s("The floor is wet.", "Фарш тар аст.", None),
            s("Be careful, please.", "Лутфан, эҳтиёт бошед.", None),
            s("Where is the trash?", "Партов куҷост?", None),
            s("Take out the trash?", "Партовро барорам?", None),
            s("I need gloves.", "Ба ман дастпӯшак лозим.", None),
        ]),
        ("Ошхонаро тоза кун", [
            t("Please clean the kitchen.", "Лутфан, ошхонаро тоза кун.", "Бигӯ: ба ман дастпӯшак лозим",
              "I need gloves.", "Ба ман дастпӯшак лозим.", ["Gloves, please.", "Okay. I need gloves."]),
            t("Here. Then the floor, please.", "Ана. Баъд фарш, лутфан.", "Бипурс: швабра куҷост?",
              "Where is the mop?", "Швабра куҷост?", ["The mop?", "Where's the mop?"]),
            t("Behind the door.", "Паси дар.", "Бипурс: партовро барорам?", "Take out the trash?",
              "Партовро барорам?", ["And the trash?", "The trash too?"]),
        ]),
        ("Тамом?", [
            s("It's all clean.", "Ҳама тоза аст.", None),
            s("Is it okay now?", "Ҳоло хуб аст?", None),
            w("Full", "пур", None),
            s("The trash is full.", "Партов пур аст.", None),
            s("I clean the toilets.", "Ман ҳоҷатхонаҳоро тоза мекунам.", None),
            s("Five minutes, please.", "Панҷ дақиқа, лутфан.", None),
        ]),
        ("Тамом кардӣ?", [
            t("Are you done?", "Тамом кардӣ?", "Бигӯ: панҷ дақиқа, лутфан", "Five minutes, please.",
              "Панҷ дақиқа, лутфан.", ["Not yet. Five minutes.", "Five minutes."]),
            t("Okay. And the toilets?", "Хуб. Ҳоҷатхонаҳо чӣ?", "Бигӯ: ҳама тоза аст", "It's all clean.",
              "Ҳама тоза аст.", ["All clean.", "They're clean."]),
            t("Good! Anything else?", "Хуб! Боз чизе?", "Бигӯ: партов пур аст", "The trash is full.",
              "Партов пур аст.", ["Trash is full.", "Yes, the trash is full."]),
        ]),
        ("Миссия: тозакунии ошхона", [
            t("Hi! The kitchen is very dirty.", "Салом! Ошхона хеле чиркин.", "Бигӯ: хуб. ба ман дастпӯшак лозим",
              "Okay. I need gloves.", "Хуб. Ба ман дастпӯшак лозим.", ["I need gloves.", "Okay, gloves, please."]),
            t("Here. Clean the floor first.", "Ана. Аввал фаршро тоза кун.", "Бипурс: швабра куҷост?",
              "Where is the mop?", "Швабра куҷост?", ["The mop?", "Okay. Where's the mop?"]),
            t("Behind the door. Is it wet?", "Паси дар. Тар аст?", "Бигӯ: ҳа. лутфан, эҳтиёт бошед",
              "Yes. Be careful, please.", "Ҳа. Лутфан, эҳтиёт бошед.", ["Be careful, it's wet.", "Yes, careful."]),
            t("Thanks. Are you done?", "Ташаккур. Тамом кардӣ?", "Бигӯ: ҳа, ҳама тоза аст", "Yes, it's all clean.",
              "Ҳа, ҳама тоза аст.", ["All clean.", "Yes, all clean."]),
        ]),
    ]))

# ═════════════════════ 13. Мол омад ═════════════════════
made.append(pack("delivery_en_tg", "Delivery day", "Мол омад", "🚚", 13, S,
    "Мошини мол омад: қуттиҳоро мегиред, ба анбор мебаред, мешуморед ва имзо мекунед. "
    "Агар қуттӣ шикаста ё кам бошад — мегӯед ва мудирро ҷеғ мезанед.",
    [
        ("Мол", [
            w("Delivery", "мол (расонидан)", None),
            w("Truck", "мошини боркаш", None),
            w("Warehouse", "анбор", None),
            w("Heavy", "вазнин", None),
            w("List", "рӯйхат", None),
            w("Sign", "имзо кардан", None),
        ]),
        ("Мошин омад", [
            t("Is the truck here?", "Мошин омад?", "Бигӯ, ки ҳа", "Yes.", "Ҳа.",
              ["Yes, it's here.", "Yes, the truck is here."], "Кӯтоҳ ҷавоб диҳед."),
            t("Is the box heavy?", "Қуттӣ вазнин аст?", "Бигӯ: хеле вазнин", "Very heavy.", "Хеле вазнин.",
              ["Yes, very heavy.", "Heavy."]),
            t("Do you have the list?", "Рӯйхат дорӣ?", "Бигӯ, ки не", "No.", "Не.", ["No, I don't.", "No list."]),
        ]),
        ("Ибораҳо", [
            s("Twenty boxes", "Бист қуттӣ", None),
            s("Sign here", "Ин ҷо имзо кунед", None),
            s("Help me", "Ёрӣ деҳ", None),
            s("Too heavy", "Хеле вазнин", None),
            s("The list", "Рӯйхат", None),
            s("Lift together", "Якҷоя бардоштан", None),
        ]),
        ("Қуттиҳо", [
            t("Delivery! How many boxes?", "Мол! Чанд қуттӣ?", "Бигӯ: бист қуттӣ", "Twenty boxes.", "Бист қуттӣ.",
              ["Twenty.", "We have twenty boxes."]),
            t("This box is big.", "Ин қуттӣ калон.", "Бигӯ: хеле вазнин. ёрӣ деҳ", "Too heavy. Help me.",
              "Хеле вазнин. Ёрӣ деҳ.", ["Help me, please.", "It's too heavy."]),
            t("Okay. Then sign here.", "Хуб. Баъд ин ҷо имзо кун.", "Бипурс: ин ҷо?", "Here?", "Ин ҷо?",
              ["Sign here?", "Right here?"]),
        ]),
        ("Ман мегӯям", [
            s("Where do they go?", "Онҳо ба куҷо мераванд?", None),
            s("To the warehouse?", "Ба анбор?", None),
            s("I count the boxes.", "Ман қуттиҳоро мешуморам.", None),
            s("We have nineteen.", "Мо нуздаҳ дорем.", None),
            s("Let's lift together.", "Биё якҷоя бардорем.", None),
            s("Where do I sign?", "Куҷо имзо кунам?", None),
        ]),
        ("Ба анбор", [
            t("Take the boxes in.", "Қуттиҳоро дарун бар.", "Бипурс: ба анбор?", "To the warehouse?", "Ба анбор?",
              ["The warehouse?", "Where do they go?"]),
            t("Yes. Count them, please.", "Ҳа. Лутфан, онҳоро шумор.", "Бигӯ: мо нуздаҳ дорем",
              "We have nineteen.", "Мо нуздаҳ дорем.", ["Nineteen.", "Nineteen boxes."]),
            t("Nineteen? The list says twenty.", "Нуздаҳ? Дар рӯйхат бист.", "Бигӯ: бубахшед. як лаҳза, лутфан",
              "Sorry. One moment, please.", "Бубахшед. Як лаҳза, лутфан.", ["One moment.", "Sorry, one moment."]),
        ]),
        ("Қуттии шикаста", [
            s("Here is the list.", "Ана рӯйхат.", None),
            s("Everything is here.", "Ҳама чиз ҳаст.", None),
            w("Broken", "шикаста", None),
            s("This box is broken.", "Ин қуттӣ шикастааст.", None),
            s("Call the manager?", "Мудирро ҷеғ занам?", None),
            s("Thank you, driver.", "Ташаккур, ронанда.", None),
        ]),
        ("Ҳама хуб?", [
            t("Delivery for you!", "Мол барои шумо!", "Бипурс: куҷо имзо кунам?", "Where do I sign?",
              "Куҷо имзо кунам?", ["Sign where?", "Where?"]),
            t("Here. Is everything okay?", "Ин ҷо. Ҳама хуб?", "Бигӯ: не. ин қуттӣ шикастааст",
              "No. This box is broken.", "Не. Ин қуттӣ шикастааст.", ["This box is broken.", "One box is broken."]),
            t("Oh, sorry!", "Оҳ, бубахшед!", "Бипурс: мудирро ҷеғ занам?", "Call the manager?",
              "Мудирро ҷеғ занам?", ["The manager?", "Can I call the manager?"]),
        ]),
        ("Миссия: рӯзи мол", [
            t("Hi! Delivery. Twenty boxes.", "Салом! Мол. Бист қуттӣ.", "Бипурс: ба анбор?", "To the warehouse?",
              "Ба анбор?", ["The warehouse?", "Where do they go?"]),
            t("Yes. This one is heavy.", "Ҳа. Инаш вазнин.", "Бигӯ: биё якҷоя бардорем", "Let's lift together.",
              "Биё якҷоя бардорем.", ["Together, please.", "Help me, please."]),
            t("Okay. Count them, please.", "Хуб. Лутфан, онҳоро шумор.", "Бигӯ: ҳама чиз ҳаст. бист қуттӣ",
              "Everything is here. Twenty boxes.", "Ҳама чиз ҳаст. Бист қуттӣ.", ["Twenty boxes.", "Everything is here."]),
            t("Good. Sign here, please.", "Хуб. Лутфан, ин ҷо имзо кунед.", "Бигӯ: хуб. ташаккур, ронанда",
              "Okay. Thank you, driver.", "Хуб. Ташаккур, ронанда.", ["Thank you.", "Okay, thanks."]),
        ]),
    ]))

# ═════════════════════ 15. Занг ба мудир ═════════════════════
made.append(pack("callmgr_en_tg", "Calling the manager", "Занг ба мудир", "📞", 15, S,
    "Дер мемонед, бемор шудед ё имрӯз намеоед — бояд ба мудир занг занед. Дар телефон "
    "рӯй намебинед, садо бад аст. Шумо кӯтоҳ ва фаҳмо мегӯед, ки чӣ шуд ва кай меоед.",
    [
        ("Телефон", [
            w("Late", "дер", None),
            w("Sick", "бемор", None),
            w("Sorry", "бубахшед", None),
            w("Today", "имрӯз", None),
            w("Come", "омадан", None),
            w("Call", "занг задан", None),
        ]),
        ("Ту куҷоӣ?", [
            t("Hello?", "Алло?", "Салом гӯй", "Hello!", "Салом!", ["Hi!", "Hello, it's me."], "Кӯтоҳ ҷавоб диҳед."),
            t("Where are you? Are you late?", "Ту куҷоӣ? Дер мемонӣ?", "Бигӯ: ҳа, дер", "Yes, late.", "Ҳа, дер.",
              ["Yes, I'm late.", "Yes."]),
            t("Why aren't you at work? Are you sick?", "Чаро дар кор нестӣ? Беморӣ?", "Бигӯ: ҳа, беморам",
              "Yes, sick.", "Ҳа, беморам.", ["Yes, I'm sick.", "I'm sick."]),
        ]),
        ("Кӯтоҳ мегӯям", [
            s("I'm late", "Ман дер мондам", None),
            s("I'm sick", "Ман беморам", None),
            s("Not coming", "Намеоям", None),
            s("One hour", "Як соат", None),
            s("Very sorry", "Хеле бубахшед", None),
            s("Tomorrow morning", "Фардо саҳар", None),
        ]),
        ("Дер мемонам", [
            t("Hello, Anna speaking.", "Алло, Анна гап мезанад.", "Бигӯ: бубахшед, дер мондам",
              "Sorry, I'm late.", "Бубахшед, дер мондам.", ["I'm late, sorry.", "Very sorry. I'm late."]),
            t("When do you come?", "Кай меоӣ?", "Бигӯ: баъди як соат", "In one hour.", "Баъди як соат.",
              ["One hour.", "In an hour."]),
            t("Okay, I'm waiting.", "Хуб, интизорам.", "Ташаккур гӯй", "Thank you.", "Ташаккур.",
              ["Thanks.", "Thank you, see you."]),
        ]),
        ("Сабаб", [
            own("This is ___.", "Ин ___ (ҳастам).", "Ба ҷои «___» номи ХУДАТОНРО гӯед.",
                "Hello, who is this?", "Алло, ин кӣ?", "Номи худатонро гӯед"),
            s("I can't come today.", "Имрӯз омада наметавонам.", None),
            s("I have a fever.", "Ман таб дорам.", None),
            s("The bus is late.", "Автобус дер кард.", None),
            s("I'm at home.", "Ман дар хонаам.", None),
            s("Can I come tomorrow?", "Фардо омада метавонам?", None),
        ]),
        ("Беморам", [
            t("Hello! Why aren't you at work?", "Алло! Чаро дар кор нестӣ?", "Бигӯ: беморам, таб дорам",
              "I'm sick. I have a fever.", "Беморам. Таб дорам.", ["I'm sick.", "I have a fever."]),
            t("I see. And tomorrow?", "Фаҳмо. Фардо чӣ?", "Бипурс: фардо омада метавонам?",
              "Can I come tomorrow?", "Фардо омада метавонам?", ["Tomorrow?", "Yes. Can I come tomorrow?"]),
            t("Yes, of course. Get well!", "Ҳа, албатта. Шифо ёбӣ!", "Ташаккур гӯй", "Thank you!", "Ташаккур!",
              ["Thanks!", "Thank you, Anna."]),
        ]),
        ("Садо бад аст", [
            w("Hear", "шунидан", None),
            s("I can't hear you.", "Шуморо намешунавам.", "Дар телефон ибораи зарурӣ."),
            s("Call me back, please.", "Лутфан, боз занг занед.", None),
            s("I'm coming.", "Ҳозир меоям.", None),
            s("Sorry, I'm late.", "Бубахшед, дер мондам.", None),
            s("I can call tonight.", "Бегоҳ занг зада метавонам.", None),
        ]),
        ("Алоқа бад", [
            t("Hello! Where are you? We...", "Алло! Ту куҷоӣ? Мо...", "Бигӯ: шуморо намешунавам",
              "I can't hear you.", "Шуморо намешунавам.", ["Sorry, I can't hear you.", "Hello? I can't hear."]),
            t("Where are you, I said?", "Мегӯям, ту куҷоӣ?", "Бигӯ: ҳозир меоям, автобус дер кард",
              "I'm coming. The bus is late.", "Ҳозир меоям. Автобус дер кард.",
              ["The bus is late. I'm coming.", "I'm on my way. The bus is late."]),
            t("Okay. Call me back, please.", "Хуб. Лутфан, боз занг зан.", "Бигӯ: хуб, бегоҳ занг зада метавонам",
              "Okay, I can call tonight.", "Хуб, бегоҳ занг зада метавонам.", ["I'll call tonight.", "Okay."]),
        ]),
        ("Миссия: занг ба мудир", [
            t("Hello, Anna speaking.", "Алло, Анна гап мезанад.", "Салом гӯй ва бубахшед",
              "Hello, Anna! Sorry.", "Салом, Анна! Бубахшед.", ["Hi, Anna. Sorry.", "Hello, sorry."]),
            t("What happened?", "Чӣ шуд?", "Бигӯ: беморам, имрӯз омада наметавонам",
              "I'm sick. I can't come today.", "Беморам. Имрӯз омада наметавонам.",
              ["I'm sick, I can't come.", "I can't come today. I'm sick."]),
            t("I see. Do you have a fever?", "Фаҳмо. Таб дорӣ?", "Бигӯ: ҳа, таб дорам",
              "Yes, I have a fever.", "Ҳа, таб дорам.", ["Yes.", "Yes, a fever."]),
            t("Okay, rest. Call me tonight.", "Хуб, дам гир. Бегоҳ занг зан.", "Бигӯ: хуб, бегоҳ занг зада метавонам",
              "Okay, I can call tonight.", "Хуб, бегоҳ занг зада метавонам.", ["I'll call tonight.", "Okay, thank you."]),
        ]),
    ], mission_mode="call"))

# ═════════════════════ 17. Танаффус бо ҳамкорон ═════════════════════
made.append(pack("staff_en_tg", "Break with coworkers", "Танаффус бо ҳамкорон", "🍵", 17, S,
    "Танаффус дар ҳуҷраи кормандон бо ҳамкорон аз кишварҳои гуногун: чой, хӯрок ва "
    "суҳбат. Шумо мегӯед, ки аз куҷоед, дар куҷо зиндагӣ мекунед ва бо ҳам дам мегиред.",
    [
        ("Танаффус", [
            w("Break", "танаффус", None),
            w("Tired", "монда", None),
            w("Together", "якҷоя", None),
            w("Tea", "чой", None),
            w("Friend", "дӯст", None),
            w("Lunch", "хӯроки пешин", None),
        ]),
        ("Дам мегирем", [
            t("Are we working or taking a break?", "Кор мекунем ё танаффус?", "Бигӯ: танаффус", "Break.",
              "Танаффус.", ["A break.", "Break time."], "Кӯтоҳ ҷавоб диҳед."),
            t("Are you tired?", "Монда шудӣ?", "Бигӯ: ҳа, монда", "Tired.", "Монда.", ["Yes, tired.", "Yes, I'm tired."]),
            t("Lunch alone or together?", "Хӯрок танҳо ё якҷоя?", "Бигӯ: якҷоя", "Together.", "Якҷоя.",
              ["Together, please."]),
        ]),
        ("Биё!", [
            s("Let's go", "Биё равем", None),
            s("Let's rest", "Биё дам гирем", None),
            s("Let's eat", "Биё хӯрем", None),
            s("Me too", "Ман ҳам", None),
            s("Good job", "Офарин", None),
            w("Delicious", "бомаза", None),
        ]),
        ("Шиносоӣ", [
            t("Hey, where are you from?", "Эй, аз куҷоӣ?", "Бигӯ: аз Тоҷикистон ва бипурс: ту аз куҷоӣ?",
              "Tajikistan. And you?", "Тоҷикистон. Ту-чӣ?", ["I'm from Tajikistan. And you?", "From Tajikistan."]),
            t("I'm from Mexico. I'm tired today!", "Ман аз Мексика. Имрӯз монда шудам!",
              "Бигӯ: ман ҳам. биё дам гирем", "Me too. Let's rest.", "Ман ҳам. Биё дам гирем.", ["Let's rest.", "Me too."]),
            t("Okay. Want some tea?", "Хуб. Чой мехоҳӣ?", "Бигӯ: ҳа, биё равем", "Yes, let's go.", "Ҳа, биё равем.",
              ["Sure, let's go.", "Yes, please."]),
        ]),
        ("Дар бораи худам", [
            s("What's your name?", "Номат чист?", None),
            own("My name is ___.", "Номи ман ___.", "Ба ҷои «___» номи ХУДАТОНРО гӯед.",
                "And what's your name?", "Номи ту чист?", "Номи худатонро гӯед"),
            s("Are you new here?", "Ту ин ҷо навӣ?", None),
            s("No, I'm not new.", "Не, ман нав нестам.", None),
            s("Where do you live?", "Дар куҷо зиндагӣ мекунӣ?", None),
            s("I live near here.", "Ман наздики ин ҷо зиндагӣ мекунам.", None),
        ]),
        ("Суҳбат", [
            t("Are you new here?", "Ту ин ҷо навӣ?", "Бигӯ: не, ман нав нестам", "No, I'm not new.",
              "Не, ман нав нестам.", ["No.", "No, one year here."]),
            t("And where do you live?", "Дар куҷо зиндагӣ мекунӣ?", "Бигӯ: наздики ин ҷо", "I live near here.",
              "Наздики ин ҷо зиндагӣ мекунам.", ["Near here.", "Close to here."]),
            t("Me too! Let's go home together?", "Ман ҳам! Якҷоя ба хона равем?", "Бигӯ: ҳа, биё равем",
              "Yes, let's go.", "Ҳа, биё равем.", ["Sure.", "Yes, together."]),
        ]),
        ("Сари дастурхон", [
            s("Help me, please.", "Лутфан, ёрӣ деҳ.", None),
            s("Thanks, my friend.", "Ташаккур, дӯстам.", None),
            s("It's very good.", "Хеле бомаза.", None),
            s("Do you want tea?", "Чой мехоҳӣ?", None),
            s("Enjoy your meal.", "Иштиҳои хуш.", "Пеш аз хӯрок мегӯянд."),
            w("Plov", "палав", None),
        ]),
        ("Хӯроки пешин", [
            t("Sit down, eat with us.", "Шин, бо мо хӯрок хӯр.", "Бигӯ: ташаккур, дӯстам", "Thanks, my friend.",
              "Ташаккур, дӯстам.", ["Thank you.", "Thanks a lot, my friend."]),
            t("This is plov. Do you like it?", "Ин палав. Маъқул аст?", "Бигӯ: хеле бомаза", "It's very good!",
              "Хеле бомаза!", ["Delicious!", "Very good, thank you."]),
            t("Do you want more tea?", "Боз чой мехоҳӣ?", "Бигӯ: ҳа, лутфан", "Yes, please.", "Ҳа, лутфан.",
              ["Yes, thanks.", "Sure."]),
        ]),
        ("Миссия: ҳамкори нав", [
            t("Hi! Are you new? Where are you from?", "Салом! Навӣ? Аз куҷоӣ?",
              "Бигӯ: аз Тоҷикистон ва бипурс: ту аз куҷоӣ?", "Tajikistan. And you?", "Тоҷикистон. Ту-чӣ?",
              ["I'm from Tajikistan. And you?", "From Tajikistan."]),
            t("I'm from Poland. Are you new here?", "Ман аз Лаҳистон. Ту ин ҷо навӣ?",
              "Бигӯ: не, ман нав нестам", "No, I'm not new.", "Не, ман нав нестам.", ["No.", "No, one year here."]),
            t("Nice! Are you tired today?", "Офарин! Имрӯз монда шудӣ?", "Бигӯ: ҳа, монда. биё дам гирем",
              "Yes, I'm tired. Let's rest.", "Ҳа, монда шудам. Биё дам гирем.", ["Tired. Let's rest.", "Yes, let's rest."]),
            t("Okay. Want some tea?", "Хуб. Чой мехоҳӣ?", "Бигӯ: ҳа, ташаккур, дӯстам",
              "Yes, thanks, my friend.", "Ҳа, ташаккур, дӯстам.", ["Thanks, my friend.", "Yes, please."]),
        ]),
    ]))

# ═════════════════════ 18. Либоси корӣ ва бейҷ ═════════════════════
made.append(pack("uniform_en_tg", "Uniform and badge", "Либоси корӣ ва бейҷ", "👕", 18, S,
    "Дар мағоза ва қаҳвахона либоси корӣ мепӯшанд: курта, пешдоман, кепка, пойафзоли "
    "сиёҳ ва бейҷ бо ном. Шумо андоза мегӯед ва чизи лозимиро мепурсед.",
    [
        ("Либос", [
            w("Shirt", "курта", None),
            w("Apron", "пешдоман", None),
            w("Cap", "кепка", None),
            w("Shoes", "пойафзол", None),
            w("Badge", "бейҷ (нишони ном)", None),
            w("Size", "андоза", None),
        ]),
        ("Чӣ мепӯшӣ?", [
            t("What do you wear on your head?", "Ба сар чӣ мепӯшӣ?", "Бигӯ: кепка", "A cap.", "Кепка.",
              ["Cap.", "My cap."], "Кӯтоҳ ҷавоб диҳед."),
            t("Is this your apron?", "Ин пешдомани туст?", "Бигӯ, ки ҳа", "Yes.", "Ҳа.", ["Yes, it is.", "Yes, my apron."]),
            t("Do you have a badge?", "Бейҷ дорӣ?", "Бигӯ, ки не", "No.", "Не.", ["No, I don't.", "No badge."]),
        ]),
        ("Андоза", [
            s("My shirt", "Куртаи ман", None),
            s("Your badge", "Бейҷи ту", None),
            s("What size?", "Чӣ андоза?", None),
            w("Small", "хурд", None),
            w("Medium", "миёна", None),
            s("Too small", "Хеле хурд", None),
        ]),
        ("Курта мувофиқ аст?", [
            t("Here's your shirt. What size?", "Ана куртаат. Чӣ андоза?", "Бигӯ: миёна", "Medium.", "Миёна.",
              ["Medium, please.", "Size medium."]),
            t("Is it okay?", "Мувофиқ аст?", "Бигӯ: хеле хурд", "Too small.", "Хеле хурд.",
              ["It's too small.", "No, too small."]),
            t("And where is your badge?", "Бейҷат куҷост?", "Бигӯ: бейҷи ман ин ҷо", "My badge is here.",
              "Бейҷи ман ин ҷо.", ["Here.", "It's here."]),
        ]),
        ("Ман мепурсам", [
            s("I need a shirt.", "Ба ман курта лозим.", None, swaps=["shirt|курта", "apron|пешдоман", "cap|кепка"]),
            s("This is too small.", "Ин хеле хурд аст.", None),
            s("Medium, please.", "Миёна, лутфан.", None),
            s("Where are the aprons?", "Пешдоманҳо куҷоянд?", None),
            w("Wear", "пӯшидан", None),
            s("Do I wear this?", "Инро пӯшам?", None),
        ]),
        ("Либоси корӣ", [
            t("Hi! Do you have a shirt?", "Салом! Курта дорӣ?", "Бигӯ: не. ба ман курта лозим",
              "No. I need a shirt.", "Не. Ба ман курта лозим.", ["I need a shirt.", "No, I don't."]),
            t("Try this one.", "Инашро пӯш.", "Бигӯ: ин хеле хурд аст", "This is too small.", "Ин хеле хурд аст.",
              ["Too small.", "It's too small."]),
            t("What size do you need?", "Чӣ андоза лозим?", "Бигӯ: миёна, лутфан", "Medium, please.", "Миёна, лутфан.",
              ["Medium.", "Size medium, please."]),
        ]),
        ("Тоза ва сиёҳ", [
            s("My shirt is dirty.", "Куртаи ман чиркин аст.", None),
            s("Can I have another?", "Дигарашро гирифта метавонам?", None),
            w("Black", "сиёҳ", None),
            s("Black shoes, please.", "Пойафзоли сиёҳ, лутфан.", None),
            s("Is this okay?", "Ин хуб аст?", None),
            w("Clean", "тоза", None),
        ]),
        ("Курта чиркин", [
            t("Your shirt! What's wrong?", "Куртаат! Чӣ шуд?", "Бигӯ: куртаи ман чиркин аст", "My shirt is dirty.",
              "Куртаи ман чиркин аст.", ["It's dirty.", "Sorry, it's dirty."]),
            t("Take a clean one.", "Тозаашро гир.", "Бигӯ: ташаккур. ин хуб аст?", "Thanks. Is this okay?",
              "Ташаккур. Ин хуб аст?", ["Is this okay?", "Thank you."]),
            t("Yes. And wear black shoes.", "Ҳа. Ва пойафзоли сиёҳ пӯш.", "Бигӯ: хуб, фаҳмидам", "Okay, got it.",
              "Хуб, фаҳмидам.", ["Got it.", "Okay, black shoes."]),
        ]),
        ("Миссия: пеш аз кор", [
            t("Stop! Where is your badge?", "Ист! Бейҷат куҷост?", "Бигӯ: бубахшед, бейҷ надорам",
              "Sorry. I don't have a badge.", "Бубахшед. Бейҷ надорам.", ["I don't have a badge.", "Sorry, no badge."]),
            t("Okay, take this one. And your apron?", "Хуб, инашро гир. Пешдоманат чӣ?",
              "Бипурс: пешдоманҳо куҷоянд?", "Where are the aprons?", "Пешдоманҳо куҷоянд?", ["The aprons?", "Where?"]),
            t("Behind the door. Is it okay?", "Паси дар. Мувофиқ аст?", "Бигӯ: хеле хурд. миёна, лутфан",
              "Too small. Medium, please.", "Хеле хурд. Миёна, лутфан.", ["Too small.", "Medium, please."]),
            t("Here. Have a good day!", "Ана. Рӯзи хуш!", "Бигӯ: ташаккури зиёд!", "Thank you very much!",
              "Ташаккури зиёд!", ["Thanks!", "Thank you!"]),
        ]),
    ]))

# ═════════════════════ 19. Харидори норозӣ ═════════════════════
made.append(pack("complaint_en_tg", "An unhappy customer", "Харидори норозӣ", "😟", 19, S,
    "Харидор норозӣ аст: мол шикаста, кӯҳна ё андозааш нодуруст. Шумо оромона узр "
    "мепурсед, чекро мепурсед, молро иваз мекунед ё мудирро ҷеғ мезанед.",
    [
        ("Мушкил", [
            w("Problem", "мушкил", None),
            w("Return", "баргардондан", None),
            w("Broken", "шикаста", None),
            w("Wrong", "нодуруст", None),
            w("Old", "кӯҳна", None),
            w("Change", "иваз кардан", None),
        ]),
        ("Ин шикаста!", [
            t("Are you the manager?", "Шумо мудиред?", "Бигӯ, ки не", "No.", "Не.",
              ["No, sorry.", "No, I'm not."], "Кӯтоҳ ҷавоб диҳед."),
            t("This is broken!", "Ин шикаста!", "Бигӯ: бубахшед", "Sorry.", "Бубахшед.", ["I'm sorry.", "Oh, sorry."]),
            t("Can I return it?", "Баргардонда метавонам?", "Бигӯ, ки ҳа", "Yes.", "Ҳа.", ["Yes, you can.", "Yes, of course."]),
        ]),
        ("Ибораҳо", [
            s("Money back", "Пулро баргардондан", None),
            s("Your receipt?", "Чекатон?", None),
            s("No problem", "Мушкил нест", None),
            s("I'm sorry", "Бубахшед", None),
            s("Not fresh", "Тоза нест (кӯҳна)", None),
            s("Wrong size", "Андозаи нодуруст", None),
        ]),
        ("Пуламро баргардонед", [
            t("I want my money back.", "Пуламро баргардонед.", "Бипурс: чекатон?", "Your receipt?", "Чекатон?",
              ["Do you have the receipt?", "Receipt, please?"]),
            t("Here it is.", "Ана.", "Бигӯ: ташаккур. мушкил нест", "Thank you. No problem.", "Ташаккур. Мушкил нест.",
              ["No problem.", "Thanks."]),
            t("And this milk is old!", "Ин шир кӯҳна!", "Бигӯ: бубахшед", "I'm sorry.", "Бубахшед.",
              ["Oh, I'm sorry.", "Sorry."]),
        ]),
        ("Ман мегӯям", [
            s("What's the problem?", "Чӣ мушкил?", None),
            s("I'm very sorry.", "Хеле бубахшед.", None),
            s("Receipt, please.", "Чек, лутфан.", None),
            s("It's not fresh.", "Тоза нест.", None),
            s("Here is new milk.", "Ана шири нав.", None),
            s("Please wait here.", "Лутфан, ин ҷо интизор шавед.", None),
        ]),
        ("Нон тоза нест", [
            t("Excuse me! This is wrong!", "Бубахшед! Ин нодуруст!", "Бипурс: чӣ мушкил?", "What's the problem?",
              "Чӣ мушкил?", ["What's wrong?", "Is there a problem?"]),
            t("The bread is not fresh.", "Нон тоза нест.", "Бигӯ: хеле бубахшед", "I'm very sorry.", "Хеле бубахшед.",
              ["Sorry.", "I'm so sorry."]),
            t("I want new bread.", "Нони нав мехоҳам.", "Бигӯ: як лаҳза, лутфан", "One moment, please.",
              "Як лаҳза, лутфан.", ["One moment.", "Okay, one moment."]),
        ]),
        ("Иваз мекунам", [
            s("I can change it.", "Ман онро иваз карда метавонам.", None),
            s("Here is your money.", "Ана пулатон.", None),
            s("Wrong size?", "Андоза нодуруст?", None),
            s("Sorry about that.", "Барои ин бубахшед.", None),
            s("The manager is coming.", "Мудир ҳозир меояд.", None),
            w("Manager", "мудир", None),
        ]),
        ("Пойафзол калон", [
            t("These shoes are too big.", "Ин пойафзол хеле калон.", "Бипурс: андоза нодуруст?", "Wrong size?",
              "Андоза нодуруст?", ["The wrong size?", "Too big?"]),
            t("Yes. Can I change them?", "Ҳа. Иваз карда метавонам?", "Бигӯ: ҳа. ман онро иваз карда метавонам",
              "Yes. I can change it.", "Ҳа. Ман онро иваз карда метавонам.", ["Yes, of course.", "Yes, no problem."]),
            t("Thank you so much.", "Ташаккури зиёд.", "Бигӯ: барои ин бубахшед", "Sorry about that.",
              "Барои ин бубахшед.", ["No problem.", "I'm sorry about that."]),
        ]),
        ("Миссия: телефони шикаста", [
            t("Excuse me! I have a problem.", "Бубахшед! Ман мушкил дорам.", "Бипурс: чӣ мушкил?",
              "What's the problem?", "Чӣ мушкил?", ["Yes? What's the problem?", "What's wrong?"]),
            t("This phone is broken.", "Ин телефон шикаста.", "Бигӯ: хеле бубахшед. чек, лутфан",
              "I'm very sorry. Receipt, please.", "Хеле бубахшед. Чек, лутфан.", ["Sorry. Receipt, please.", "Do you have the receipt?"]),
            t("Here. I want my money back.", "Ана. Пуламро баргардонед.", "Бигӯ: лутфан, интизор шавед. мудир ҳозир меояд",
              "Please wait. The manager is coming.", "Лутфан, интизор шавед. Мудир ҳозир меояд.",
              ["One moment, please.", "Please wait. I'll call the manager."]),
            t("Okay. Thank you.", "Хуб. Ташаккур.", "Бигӯ: барои ин бубахшед", "Sorry about that.",
              "Барои ин бубахшед.", ["I'm sorry.", "Sorry about that. One moment."]),
        ]),
    ]))

# ═════════════════════ 20. Навбат ва соатҳо ═════════════════════
made.append(pack("shifts_en_tg", "Shifts and hours", "Навбат ва соатҳо", "🗓️", 20, S,
    "Дар мағоза навбатҳо (shift) ҳастанд: саҳар, бегоҳ, охири ҳафта. Шумо ҷадвалро "
    "мепурсед, мегӯед кай кор карда метавонед ва навбатро иваз мекунед.",
    [
        ("Навбат", [
            w("Shift", "навбат (смена)", None),
            w("Morning", "саҳар", None),
            w("Evening", "бегоҳ", None),
            w("Weekend", "охири ҳафта", None),
            w("Schedule", "ҷадвал", "Талаффуз: «скеджул»."),
            w("Hours", "соатҳо", None),
        ]),
        ("Кадом навбат?", [
            t("Morning or evening shift?", "Навбати саҳар ё бегоҳ?", "Бигӯ: саҳар", "Morning.", "Саҳар.",
              ["Morning, please.", "The morning shift."], "Як калима кофист."),
            t("Can you work on the weekend?", "Охири ҳафта кор карда метавонӣ?", "Бигӯ, ки ҳа", "Yes.", "Ҳа.",
              ["Yes, I can.", "Sure."]),
            t("Is eight hours okay?", "Ҳашт соат хуб?", "Бигӯ: ҳа, хуб", "Yes, okay.", "Ҳа, хуб.",
              ["Okay.", "Yes, eight hours."]),
        ]),
        ("Ибораҳо", [
            s("Morning shift", "Навбати саҳар", None),
            s("Evening shift", "Навбати бегоҳ", None),
            s("Day off", "Рӯзи истироҳат", None),
            s("Next week", "Ҳафтаи оянда", None),
            s("My schedule", "Ҷадвали ман", None),
            s("Eight hours", "Ҳашт соат", None),
        ]),
        ("Ҷадвали ҳафта", [
            t("Which shift do you want?", "Кадом навбатро мехоҳӣ?", "Бигӯ: навбати саҳар", "Morning shift.",
              "Навбати саҳар.", ["The morning shift.", "Morning, please."]),
            t("When is your day off?", "Рӯзи истироҳатат кай?", "Бигӯ: якшанбе", "Sunday.", "Якшанбе.",
              ["On Sunday.", "My day off is Sunday."]),
            t("Do you have your schedule?", "Ҷадвалатро дорӣ?", "Бигӯ: ҷадвали ман? не", "My schedule? No.",
              "Ҷадвали ман? Не.", ["No, I don't.", "No."]),
        ]),
        ("Ман мепурсам", [
            s("When is my shift?", "Навбати ман кай?", None),
            s("I start at seven.", "Ман соати ҳафт сар мекунам.", None, swaps=["seven|ҳафт", "eight|ҳашт"]),
            s("I finish at three.", "Ман соати се тамом мекунам.", None),
            s("Where is the schedule?", "Ҷадвал куҷост?", None),
            s("I'm free on Monday.", "Душанбе ман холӣ ҳастам.", None),
            w("Free", "холӣ (бекор)", None),
        ]),
        ("Навбати ман", [
            t("Hi! Do you know your shifts?", "Салом! Навбатҳоятро медонӣ?", "Бигӯ: не. ҷадвал куҷост?",
              "No. Where is the schedule?", "Не. Ҷадвал куҷост?", ["Where is the schedule?", "No. When is my shift?"]),
            t("On the wall. You start at seven.", "Дар девор. Соати ҳафт сар мекунӣ.", "Бипурс: кай тамом мекунам?",
              "When do I finish?", "Кай тамом мекунам?", ["And I finish at?", "What time do I finish?"]),
            t("At three.", "Соати се.", "Бигӯ: хуб, ташаккур", "Okay, thank you.", "Хуб, ташаккур.",
              ["Thanks.", "Okay, thanks."]),
        ]),
        ("Иваз кардан", [
            s("Can I change shifts?", "Навбатро иваз карда метавонам?", None),
            s("I can't on Friday.", "Ҷумъа наметавонам.", None),
            s("A day off, please?", "Рӯзи истироҳат, лутфан?", None),
            s("My hours are wrong.", "Соатҳои ман нодурустанд.", None),
            w("Overtime", "кори иловагӣ", None),
            s("Is it overtime?", "Ин кори иловагӣ аст?", None),
        ]),
        ("Ҷумъа наметавонам", [
            t("You work on Friday evening.", "Ҷумъа бегоҳ кор мекунӣ.", "Бигӯ: ҷумъа наметавонам",
              "I can't on Friday.", "Ҷумъа наметавонам.", ["Sorry, I can't on Friday.", "Not Friday, sorry."]),
            t("Why? What's the problem?", "Чаро? Чӣ мушкил?", "Бипурс: навбатро иваз карда метавонам?",
              "Can I change shifts?", "Навбатро иваз карда метавонам?", ["Can I change?", "Can I work on Saturday?"]),
            t("Okay. Saturday, ten hours.", "Хуб. Шанбе, даҳ соат.", "Бипурс: ин кори иловагӣ аст?",
              "Is it overtime?", "Ин кори иловагӣ аст?", ["Overtime?", "Is that overtime?"]),
        ]),
        ("Миссия: ҷадвали нав", [
            t("Hi! Here's your schedule.", "Салом! Ана ҷадвалат.", "Бипурс: навбати ман кай?", "When is my shift?",
              "Навбати ман кай?", ["My shift?", "When do I work?"]),
            t("Monday, morning shift.", "Душанбе, навбати саҳар.", "Бипурс: соати ҳафт сар мекунам?",
              "Okay. I start at seven?", "Хуб. Соати ҳафт сар мекунам?", ["At seven?", "What time do I start?"]),
            t("Yes, at seven. Any questions?", "Ҳа, соати ҳафт. Савол ҳаст?", "Бипурс: рӯзи истироҳатам кай?",
              "Yes. When is my day off?", "Ҳа. Рӯзи истироҳатам кай?", ["When is my day off?", "My day off?"]),
            t("Sunday. Have a good week!", "Якшанбе. Ҳафтаи хуш!", "Бигӯ: ташаккур, ба шумо ҳам",
              "Thank you, you too.", "Ташаккур, ба шумо ҳам.", ["Thanks!", "Thank you!"]),
        ]),
    ]))

if MISSING:
    raise SystemExit('⛔ транскрипсия нест: ' + ', '.join(sorted(MISSING)))
print(' '.join(made))
