"""АНГЛИСӢ → тоҷикӣ, «Гуфтор» A1 — нишаи «Ронандагӣ ва таксӣ» (`drive`), 30.09.2026.

14 вазъият аз нигоҳи РОНАНДА (такси, расонидан): мошини корӣ, мусофир, суроға,
бағоҷ, пардохт, гап дар роҳ, сӯзишворӣ, роҳбандӣ, расонидан, занг ба мизоҷ,
полиси роҳ, вайронӣ, садама, навбати корӣ.

Роҳи `drive` = 5 вазъияти умумӣ (1 салом, 6 духтур, 10 бозор, 14 иҷора,
16 ҳуҷҷат) + «Кор ёфтан» (2, умумӣ барои build/service/drive/life) + ин 14 →
20 вазъият. `order`-ҳо ҳамон ҷойҳои холии роҳи сохтмонанд: 3–5, 7–9, 11–13,
15, 17–20.

Ҳамон қоидаҳо (`_en_packs_lib.py`): транскрипсия ҳатмӣ, зина ≤2/≤2/≤4/≤8 калима.
Аз ҷузвдони backend: python prisma/_en-drive-a1-packs.py

02.10.2026: аз шохаи `claude/nifty-albattani-6uijek` (0194dcb) гирифта шуд ва бо
`prisma/_en-a1-path-audit.mjs drive` ба A1-и қатъӣ расонида шуд. Slug-и «Расонидани
фармоиш» — `dropoff_en_tg` (`delivery_en_tg` дар main аллакай «Мол омад»-и Хизматрасонӣ аст).
"""
from _en_packs_lib import *  # noqa: F401,F403

EXTRA.update({
    'let': 'лет', 'needs': 'нидз',
    # мошин
    'car': 'кар', 'keys': 'киз', 'gas': 'гэс', 'tire': 'тайэр', 'lights': 'лайтс', 'seat': 'сит',
    'white': 'вайт', 'full': 'фул', 'tank': 'тэнк', 'papers': 'пейпэрз', 'front': 'франт',
    'clean': 'клин', 'low': 'лоу', 'dirty': 'дёртӣ', 'automatic': 'отэмэтик', 'mirrors': 'мирэрз',
    'park': 'парк', 'garage': 'гэраж', 'driver': 'драйвэр', 'drive': 'драйв', 'driving': 'драйвинг',
    'tonight': 'тунайт',
    # мусофир
    'passenger': 'пэсинджэр', 'name': 'нейм', 'seatbelt': 'ситбелт', 'door': 'дор', 'anna': 'энэ',
    "what's": 'вотс', 'going': 'гоуинг', 'bag': 'бэг', 'comfortable': 'камфэртэбэл', 'music': 'мюзик',
    'cold': 'коулд', 'window': 'виндоу', 'nice': 'найс', 'bye': 'бай', 'morning': 'морнинг',
    'close': 'клоуз', 'fasten': 'фэсэн', 'sit': 'сит', 'place': 'плейс',
    # суроға
    'address': 'эдрес', 'straight': 'стрейт', 'corner': 'корнэр', 'turn': 'тёрн', 'airport': 'еэрпорт',
    'terminal': 'тёрминэл', 'gps': 'ҷи пи эс', 'show': 'шоу', 'building': 'билдинг',
    'entrance': 'ентрэнс', 'almost': 'олмоуст', 'parking': 'паркинг', 'wrong': 'ронг', 'close': 'клоуз',
    'gate': 'гейт', 'then': 'ҙен', 'big': 'биг',
    # бағоҷ
    'trunk': 'транк', 'suitcase': 'сюткейс', 'small': 'смол', 'careful': 'кеэрфул', 'fit': 'фит',
    'doesn\'t': 'дазнт', 'forget': 'фэргет', 'phone': 'фоун', 'things': 'ҫингз', 'anything': 'энӣҫинг',
    'else': 'елс', 'last': 'ласт', 'open': 'оупэн',
    # пардохт
    'change': 'чейндж', 'receipt': 'рисит', 'tip': 'тип', 'fifteen': 'фифтин', 'tap': 'тэп',
    'keep': 'кип', 'twenty': 'твентӣ', 'already': 'олредӣ', 'paid': 'пейд', 'smaller': 'смолэр',
    'bill': 'бил', 'app': 'эп', 'only': 'оунлӣ', 'kind': 'кайнд', 'fifty': 'фифтӣ',
    # гап дар роҳ
    'weather': 'веҙэр', 'rain': 'рейн', 'hot': 'ҳот', 'quiet': 'квайэт', 'loud': 'лауд',
    'city': 'ситӣ', 'kids': 'кидз', 'family': 'фэмилӣ', 'welcome': 'велкам', 'trip': 'трип',
    'cool': 'кул', 'better': 'бетэр', 'little': 'литэл', 'tajikistan': 'тоҷикистон',
    # сӯзишворӣ
    'pump': 'памп', 'diesel': 'дизэл', 'air': 'еэр', 'oil': 'ойл', 'wash': 'вош', 'regular': 'регюлэр',
    'restroom': 'реструм', 'coffee': 'кофӣ', 'four': 'фор', 'forty': 'фортӣ', 'try': 'трай',
    'wait': 'вейт', 'free': 'фрӣ',
    # роҳбандӣ
    'traffic': 'трэфик', 'hurry': 'ҳарӣ', 'road': 'роуд', 'bridge': 'бриҷ', 'minutes': 'минитс',
    'bad': 'бэд', 'closed': 'клоузд', 'around': 'эраунд', 'rush': 'раш', 'hour': 'ауэр',
    'safe': 'сейф', 'worry': 'ворӣ', 'stopping': 'стопинг', 'happened': 'ҳэпэнд', 'flight': 'флайт',
    'slow': 'слоу', 'lots': 'лотс', 'faster': 'фестэр', 'way': 'вей', 'let\'s': 'летс',
    # расонидан
    'order': 'ордэр', 'package': 'пэкиҷ', 'apartment': 'эпартмэнт', 'sign': 'сайн', 'delivery': 'диливэрӣ',
    'boxes': 'боксиз', 'box': 'бокс', 'floor': 'флор', 'third': 'ҫёрд', 'leave': 'лив', 'nobody': 'ноубадӣ',
    'send': 'сенд', 'photo': 'фоутоу', 'photos': 'фоутоуз', 'broken': 'броукэн', 'item': 'айтэм',
    'store': 'стор', 'check': 'чек', 'drink': 'дринк', 'rest': 'рест', 'food': 'фуд', 'twelve': 'твелв',
    'up': 'ап', 'who': 'ҳу',
    # занг
    'outside': 'аутсайд', 'black': 'блэк', 'exactly': 'игзэктлӣ', 'toyota': 'тойоутэ', 'find': 'файнд',
    'text': 'текст', 'line': 'лайн', 'away': 'эвей', 'jacket': 'ҷэкит', 'red': 'ред', 'hotel': 'ҳоутел',
    'hear': 'ҳир',
    # полис
    'license': 'лайсэнс', 'officer': 'офисэр', 'speed': 'спид', 'ticket': 'тикит', 'insurance': 'иншуэрэнс',
    'stay': 'стей', 'sir': 'сёр', 'limit': 'лимит', 'seventy': 'севэнтӣ', 'didn\'t': 'диднт',
    'know': 'ноу', 'warning': 'ворнинг', 'school': 'скул', 'evening': 'ивнинг', 'one': 'ван',
    'new': 'ню', 'were': 'вёр', 'understand': 'андэрстэнд', 'mine': 'майн',
    # вайронӣ
    'engine': 'енҷин', 'brakes': 'брейкс', 'mechanic': 'мэкэник', 'flat': 'флэт', 'battery': 'бэтэрӣ',
    'noise': 'нойз', 'strange': 'стрейнҷ', 'dead': 'дед', 'won\'t': 'воунт', 'expensive': 'икспенсив',
    'later': 'лейтэр', 'works': 'вёркс', 'service': 'сёрвис', 'maybe': 'мейбӣ', 'any': 'енӣ',
    'need': 'нид', 'hundred': 'ҳандрэд',
    # садама
    'accident': 'эксидэнт', 'damage': 'дэмидж', 'bumper': 'бампэр', 'fault': 'фолт', 'hurt': 'ҳёрт',
    'look': 'лук', 'stopped': 'стопт', 'light': 'лайт', 'was': 'воз', 'hit': 'ҳит', 'report': 'рипорт',
    'neck': 'нек', 'hurts': 'ҳёртс', 'anyone': 'енӣван', 'should': 'шуд', 'number': 'намбэр',
    'quickly': 'квиклӣ',
    # навбати корӣ
    'shift': 'шифт', 'rating': 'рейтинг', 'night': 'найт', 'starts': 'стартс', 'end': 'енд',
    'does': 'даз', 'stars': 'старз', 'weekly': 'виклӣ', 'six': 'сикс', 'get': 'гет', 'hours': 'ауэрз',
    'friday': 'фрайдей', 'sunday': 'сандей', 'saturday': 'сэтэрдей', 'monday': 'мандей',
    'dispatch': 'диспэч', 'again': 'эген', 'boss': 'бос', 'payday': 'пейдей', 'questions': 'квесчэнз',
    'next': 'некст', 'eight': 'эйт', 'week': 'вик', 'off': 'оф', 'job': 'ҷоб',
    'about': 'эбаут', 'fast': 'фэст', 'minute': 'минит', 'waiting': 'вейтинг', "you'll": 'юл',
})

made = []
D = ["drive"]

# ═════════════════════ 3. Мошини корӣ ═════════════════════
made.append(pack("car_en_tg", "The work car", "Мошини корӣ", "🚗", 3, D,
    "Рӯзи аввал дар ширкати такси. Шумо калидро мегиред ва мошинро месанҷед: бензин, "
    "чароғҳо, чархҳо. Мепурсед, ки ҳуҷҷатҳо куҷоянд ва мошинро куҷо гузоред.",
    [
        ("Мошин ва калид", [
            w("Car", "мошин", None),
            w("Keys", "калидҳо", None),
            w("Gas", "бензин", "Дар Амрико «gas», дар Англия «petrol»."),
            w("Tire", "чарх", None),
            w("Lights", "чароғҳо", None),
            w("Seat", "курсӣ", None),
        ]),
        ("Калид, лутфан", [
            t("Hi! Are you the new driver?", "Салом! Шумо ронандаи нав ҳастед?", "Бигӯ: ҳа, ман",
              "Yes, I am.", "Ҳа, ман.", ["Yes.", "Yes, that's me."]),
            t("Here are the keys.", "Ана калидҳо.", "Ташаккур гӯй", "Thank you.", "Ташаккур.",
              ["Thanks.", "Thank you very much."]),
            t("Your car is the white one.", "Мошини шумо — сафедаш.", "Бипурс: сафедаш?",
              "The white one?", "Сафедаш?", ["White?", "This white car?"]),
        ]),
        ("Мошини сафед", [
            s("White car", "Мошини сафед", None),
            s("Full tank", "Баки пур", None),
            w("Empty", "холӣ", None),
            s("Car papers", "Ҳуҷҷатҳои мошин", None),
            s("Front seat", "Курсии пеш", None),
            w("Clean", "тоза", None),
        ]),
        ("Бензин ҳаст?", [
            t("Check the car first.", "Аввал мошинро санҷед.", "Бигӯ: хуб", "Okay.", "Хуб.",
              ["Okay, sure.", "Sure."]),
            t("Is the tank full?", "Бак пур аст?", "Бигӯ: не, холӣ аст", "No, it's empty.", "Не, холӣ аст.",
              ["No. Empty.", "It's empty."]),
            t("Okay. Get gas first.", "Хуб. Аввал бензин гиред.", "Бигӯ: фаҳмидам", "Got it.", "Фаҳмидам.",
              ["Okay.", "Okay, got it."]),
        ]),
        ("Мошинро месанҷам", [
            s("The lights work.", "Чароғҳо кор мекунанд.", None),
            s("Check this tire.", "Ин чархро санҷед.", None),
            s("Where are the papers?", "Ҳуҷҷатҳо куҷоянд?", None),
            s("The car is dirty.", "Мошин чиркин аст.", None),
            s("I need gas.", "Ба ман бензин лозим.", None),
            s("Where are the keys?", "Калидҳо куҷоянд?", None),
        ]),
        ("Санҷиш", [
            t("Everything okay with the car?", "Бо мошин ҳама хуб?", "Бигӯ: ин чарх паст аст",
              "Check this tire.", "Ин чархро санҷед.", ["This tire is low.", "The tire is bad."]),
            t("Okay, I'll fix it.", "Хуб, дуруст мекунам.", "Бипурс: ҳуҷҷатҳо куҷоянд?",
              "Where are the papers?", "Ҳуҷҷатҳо куҷоянд?", ["Where are the car papers?", "The papers?"]),
            t("In the glove box.", "Дар қуттии пеши мошин.", "Ташаккур гӯй", "Thank you.", "Ташаккур.",
              ["Thanks.", "Okay, thanks."]),
        ]),
        ("Пеш аз роҳ", [
            s("The mirrors are good.", "Оинаҳо хубанд.", None),
            s("The papers are here.", "Ҳуҷҷатҳо ин ҷоянд.", None),
            s("The car is clean.", "Мошин тоза аст.", None),
            s("I'm ready to go.", "Ман ба роҳ тайёрам.", None),
            s("Where do I park?", "Мошинро куҷо гузорам?", None),
            s("See you tonight.", "То бегоҳ.", None),
        ]),
        ("Тайёр ҳастед?", [
            t("Are you ready to go?", "Ба роҳ тайёред?", "Бигӯ: ҳа, тайёрам", "Yes, I'm ready.",
              "Ҳа, тайёрам.", ["Ready.", "Yes, I'm ready to go."]),
            t("Bring the car back at ten.", "Мошинро соати даҳ баргардонед.", "Бипурс: мошинро куҷо гузорам?",
              "Where do I park?", "Мошинро куҷо гузорам?", ["Where do I park it?", "Where do I leave it?"]),
            t("Right here, by the office.", "Ҳамин ҷо, назди идора.", "Бигӯ: хуб, то бегоҳ",
              "Okay. See you tonight.", "Хуб. То бегоҳ.", ["See you tonight.", "Okay, see you."]),
        ]),
        ("Миссия: мошини корӣ", [
            t("Hi! You're the new driver, right?", "Салом! Шумо ронандаи нав, дуруст?", "Бигӯ: ҳа, ман",
              "Yes, I am.", "Ҳа, ман.", ["Yes.", "Yes, that's me."]),
            t("Here are the keys. It's the white car.", "Ана калидҳо. Мошини сафед.",
              "Ташаккур гӯй ва бипурс: бензин ҳаст?", "Thank you. Is there gas?", "Ташаккур. Бензин ҳаст?",
              ["Thanks. Is the tank full?", "Is there gas?"]),
            t("Yes, the tank is full.", "Ҳа, бак пур аст.", "Бигӯ: ин чархро санҷед", "Check this tire.",
              "Ин чархро санҷед.", ["This tire is low.", "The tire is bad."]),
            t("Oh! Take it to the garage.", "О! Ба гараж баред.", "Бигӯ: хуб, фаҳмидам", "Okay, got it.",
              "Хуб, фаҳмидам.", ["Okay.", "Got it."]),
        ]),
    ]))

# ═════════════════════ 4. Гирифтани мусофир ═════════════════════
made.append(pack("pickup_en_tg", "Picking up a passenger", "Гирифтани мусофир", "🙋", 4, D,
    "Шумо мусофирро аз суроға мегиред: номашро мепурсед, салом медиҳед, мегӯед, ки "
    "камарбандро бандад ва мепурсед, ки ба куҷо меравад.",
    [
        ("Мусофир", [
            w("Passenger", "мусофир", None),
            w("Driver", "ронанда", None),
            w("Name", "ном", None),
            w("Seatbelt", "камарбанд", None),
            w("Door", "дар", None),
            w("Back seat", "курсии қафо", None),
        ]),
        ("Шумо Анна ҳастед?", [
            t("Hi! Are you my driver?", "Салом! Шумо ронандаи ман ҳастед?", "Бигӯ: ҳа. Шумо Анна ҳастед?",
              "Yes. Are you Anna?", "Ҳа. Шумо Анна ҳастед?", ["Yes. Anna?", "Yes, I am. Anna?"],
              "Номи мусофирро пурсед — ин мусофири шумост?"),
            t("Yes, I'm Anna.", "Ҳа, ман Анна.", "Бигӯ: салом! Шинед, лутфан", "Hello! Get in, please.",
              "Салом! Шинед, лутфан.", ["Hi! Get in.", "Please get in."]),
            t("Thanks. Can I sit in front?", "Ташаккур. Дар пеш шинам?", "Бигӯ: албатта", "Sure.",
              "Албатта.", ["Of course.", "Yes, sure."]),
        ]),
        ("Шинед", [
            s("Get in", "Шинед", "Яъне «ба мошин дароед»."),
            s("Good morning", "Субҳ ба хайр", None),
            s("Your name?", "Номатон?", None),
            s("Seatbelt, please", "Камарбанд, лутфан", None),
            s("Let's go", "Рафтем", None),
            s("Ten minutes", "Даҳ дақиқа", None),
        ]),
        ("Камарбанд", [
            t("Okay, I'm in.", "Хуб, шиштам.", "Бигӯ: камарбанд, лутфан", "Seatbelt, please.",
              "Камарбанд, лутфан.", ["Your seatbelt, please.", "Please, the seatbelt."]),
            t("Oh, sorry. Done.", "О, бубахшед. Тайёр.", "Бигӯ: ташаккур. Рафтем", "Thank you. Let's go.",
              "Ташаккур. Рафтем.", ["Thanks. Let's go.", "Let's go."]),
            t("How long is the ride?", "Роҳ чанд вақт?", "Бигӯ: даҳ дақиқа", "Ten minutes.", "Даҳ дақиқа.",
              ["About ten minutes.", "Ten minutes, maybe."]),
        ]),
        ("Ман ронандаи шумо", [
            s("I'm your driver.", "Ман ронандаи шумоям.", None),
            s("Please close the door.", "Лутфан, дарро пӯшед.", None),
            s("Where are you going?", "Ба куҷо меравед?", None),
            s("Is this your bag?", "Ин сумкаи шумост?", None),
            own("My name is ___.", "Номи ман ___.", "Номи худро гӯед.",
                "What's your name?", "Номатон чист?", "Номи худро гӯед"),
            s("Are you comfortable?", "Бароҳатед?", None),
        ]),
        ("Ба куҷо?", [
            t("Hello! Is this my taxi?", "Салом! Ин таксии ман аст?", "Бигӯ: ҳа, ман ронандаи шумо",
              "Yes, I'm your driver.", "Ҳа, ман ронандаи шумоям.", ["Yes. I'm your driver.", "Yes, it is."]),
            t("Can I put my bag here?", "Сумкаамро ин ҷо гузорам?", "Бигӯ: ҳа, албатта", "Yes, of course.",
              "Ҳа, албатта.", ["Sure.", "Yes."]),
            t("Thanks. I'm ready.", "Ташаккур. Тайёрам.", "Бипурс: ба куҷо меравед?", "Where are you going?",
              "Ба куҷо меравед?", ["Where to?", "Where are we going?"]),
        ]),
        ("Дар роҳ", [
            s("Is the music okay?", "Мусиқӣ хуб аст?", None),
            s("Is it too cold?", "Хеле хунук аст?", None),
            s("Open the window?", "Тирезаро кушоям?", None),
            w("Window", "тиреза", None),
            s("We are here.", "Расидем.", None),
            s("Have a nice day!", "Рӯзи хуш!", None),
        ]),
        ("Расидем", [
            t("Is this the place?", "Ҳамин ҷост?", "Бигӯ: ҳа, расидем", "Yes, we are here.", "Ҳа, расидем.",
              ["Yes. We're here.", "We are here."]),
            t("Great! Thank you!", "Олӣ! Ташаккур!", "Бигӯ: рӯзи хуш", "Have a nice day!", "Рӯзи хуш!",
              ["Have a good day!", "Bye! Have a nice day."]),
            t("You too! Bye!", "Ба шумо ҳам! Хайр!", "Бигӯ: хайр", "Bye!", "Хайр!", ["Goodbye!", "Bye-bye!"]),
        ]),
        ("Миссия: мусофири аввал", [
            t("Hi! Are you my driver?", "Салом! Шумо ронандаи ман ҳастед?", "Бигӯ: ҳа. Шумо Анна ҳастед?",
              "Yes. Are you Anna?", "Ҳа. Шумо Анна ҳастед?", ["Yes. Anna?", "Yes, I am. Anna?"]),
            t("Yes! Can I sit in the back?", "Ҳа! Дар қафо шинам?", "Бигӯ: ҳа, албатта", "Yes, of course.",
              "Ҳа, албатта.", ["Sure.", "Of course."]),
            t("Okay, I'm in.", "Хуб, шиштам.", "Бигӯ: камарбанд, лутфан", "Seatbelt, please.",
              "Камарбанд, лутфан.", ["Your seatbelt, please.", "Please, the seatbelt."]),
            t("Sure. Done.", "Албатта. Тайёр.", "Бипурс: ба куҷо меравед?", "Where are you going?",
              "Ба куҷо меравед?", ["Where to?", "Where are we going?"]),
        ]),
    ]))

# ═════════════════════ 5. Суроға ва роҳ ═════════════════════
made.append(pack("route_en_tg", "Addresses and directions", "Суроға ва роҳ", "🗺️", 5, D,
    "Мусофир мегӯяд, ки ба куҷо меравад. Шумо суроғаро такрор мекунед, мепурсед "
    "«чап ё рост?», мегӯед, ки GPS доред ва ҷои дурустро меёбед.",
    [
        ("Чап ва рост", [
            w("Address", "суроға", None),
            w("Left", "чап", None),
            w("Right", "рост", None),
            w("Straight", "рост ба пеш", None),
            w("Corner", "кунҷ", None),
            w("Airport", "фурудгоҳ", None),
        ]),
        ("Ба фурудгоҳ", [
            t("To the airport, please.", "Ба фурудгоҳ, лутфан.", "Бипурс: ба фурудгоҳ?", "To the airport?",
              "Ба фурудгоҳ?", ["The airport?", "Airport?"], "Суроғаро такрор кунед — хато намешавад."),
            t("Yes. Terminal two.", "Ҳа. Терминали ду.", "Бигӯ: хуб, рақами ду", "Okay, number two.",
              "Хуб, рақами ду.", ["Terminal two. Okay.", "Okay."]),
            t("How long is the drive?", "Роҳ чанд вақт?", "Бигӯ: бист дақиқа", "Twenty minutes.",
              "Бист дақиқа.", ["About twenty minutes.", "Twenty minutes, maybe."]),
        ]),
        ("Гардед", [
            s("Turn left", "Ба чап гардед", None),
            s("Turn right", "Ба рост гардед", None),
            s("Go straight", "Рост равед", None),
            s("This street?", "Ҳамин кӯча?", None),
            s("Next corner", "Кунҷи навбатӣ", None),
            s("Right here", "Ҳамин ҷо", None),
        ]),
        ("Чап ё рост?", [
            t("Turn here, please.", "Ин ҷо гардед, лутфан.", "Бипурс: чап ё рост?", "Left or right?",
              "Чап ё рост?", ["Left?", "Right or left?"]),
            t("Left. Then go straight.", "Ба чап. Баъд рост равед.", "Бигӯ: хуб, фаҳмидам", "Okay, got it.",
              "Хуб, фаҳмидам.", ["Okay.", "Got it."]),
            t("Stop at the next corner.", "Дар кунҷи навбатӣ истед.", "Бипурс: ҳамин ҷо?", "Right here?",
              "Ҳамин ҷо?", ["Here?", "This corner?"]),
        ]),
        ("Суроға чист?", [
            s("What's the address?", "Суроға чист?", None),
            s("I have GPS.", "Ман GPS дорам.", None),
            s("Show me, please.", "Нишон диҳед, лутфан.", None),
            s("Is this the building?", "Ҳамин бино аст?", None),
            s("Which entrance?", "Кадом даромадгоҳ?", None),
            s("Is it far?", "Дур аст?", None),
        ]),
        ("Бинои сафед", [
            t("Hi! Can you take me home?", "Салом! Маро ба хона мебаред?", "Бипурс: суроға чист?",
              "What's the address?", "Суроға чист?", ["Your address?", "What is the address?"]),
            t("Here, on my phone.", "Ана, дар телефонам.", "Бигӯ: хуб. Ман GPS дорам", "Okay. I have GPS.",
              "Хуб. Ман GPS дорам.", ["I have GPS.", "Okay, thanks."]),
            t("It's a big white building.", "Бинои калони сафед.", "Бипурс: кадом даромадгоҳ?",
              "Which entrance?", "Кадом даромадгоҳ?", ["Which door?", "What entrance?"]),
        ]),
        ("Қариб расидем", [
            s("Two more minutes.", "Боз ду дақиқа.", None),
            s("Can I stop here?", "Ин ҷо истам?", None),
            s("There's no parking.", "Ҷои истодан нест.", None),
            s("One more minute.", "Боз як дақиқа.", None),
            s("Sorry, wrong street.", "Бубахшед, кӯча нодуруст.", None),
            w("Parking", "ҷои мошин гузоштан", None),
        ]),
        ("Ҷои истодан нест", [
            t("Are we close?", "Наздик шудем?", "Бигӯ: боз ду дақиқа", "Two more minutes.", "Боз ду дақиқа.",
              ["Almost there.", "One more minute."]),
            t("Can you stop at the gate?", "Назди дарвоза меистед?", "Бигӯ: ҷои истодан нест",
              "There's no parking.", "Ҷои истодан нест.", ["No parking here.", "Sorry, no parking."]),
            t("Okay. Stop at the corner.", "Хуб. Дар кунҷ истед.", "Бигӯ: хуб", "Okay.", "Хуб.",
              ["Okay, sure.", "Sure."]),
        ]),
        ("Миссия: ба фурудгоҳ", [
            t("Hi! To the airport, please.", "Салом! Ба фурудгоҳ, лутфан.", "Бипурс: ба фурудгоҳ?",
              "To the airport?", "Ба фурудгоҳ?", ["The airport?", "Airport?"]),
            t("Yes. Is it far?", "Ҳа. Дур аст?", "Бигӯ: бист дақиқа", "Twenty minutes.", "Бист дақиқа.",
              ["About twenty minutes.", "No, twenty minutes."]),
            t("Good. Turn left here, it's faster.", "Хуб. Ин ҷо ба чап гардед, тезтар аст.",
              "Бипурс: ба чап? Хуб", "Left? Okay.", "Ба чап? Хуб.", ["Left?", "Turn left? Okay."]),
            t("Stop at terminal two, please.", "Дар терминали ду истед, лутфан.", "Бигӯ: хуб, рақами ду",
              "Okay, number two.", "Хуб, рақами ду.", ["Terminal two. Okay.", "Okay."]),
        ]),
    ]))

# ═════════════════════ 7. Бағоҷ ва бағоҷдон ═════════════════════
made.append(pack("luggage_en_tg", "Bags and the trunk", "Бағоҷ ва бағоҷдон", "🧳", 7, D,
    "Мусофир ҷомадонҳои калон дорад. Шумо бағоҷдонро мекушоед, ёрӣ медиҳед, мепурсед, "
    "ки чанд сумка ҳаст, ва дар охир мегӯед, ки ҳеҷ чизро дар мошин фаромӯш накунад.",
    [
        ("Сумкаҳо", [
            w("Trunk", "бағоҷдон", None),
            w("Bag", "сумка", None),
            w("Suitcase", "ҷомадон", None),
            w("Heavy", "вазнин", None),
            w("Big", "калон", None),
            w("Small", "хурд", None),
        ]),
        ("Ёрӣ медиҳам", [
            t("I have two big bags.", "Ман ду сумкаи калон дорам.", "Бигӯ: ман ёрӣ медиҳам", "I can help.",
              "Ман ёрӣ медиҳам.", ["I can help.", "I'll help you."]),
            t("Thank you! They are heavy.", "Ташаккур! Вазнинанд.", "Бигӯ: мушкил нест", "No problem.",
              "Мушкил нест.", ["It's okay.", "No problem at all."]),
            t("Where do I put this?", "Инро куҷо гузорам?", "Бигӯ: дар бағоҷдон", "In the trunk.",
              "Дар бағоҷдон.", ["The trunk.", "Put it in the trunk."]),
        ]),
        ("Ду сумка", [
            s("Two bags", "Ду сумка", None),
            s("Very heavy", "Хеле вазнин", None),
            s("One more?", "Боз як?", None),
            s("Be careful", "Эҳтиёт шавед", None),
            s("Your bags", "Бағоҷатон", None),
            s("All done", "Ҳама тайёр", None),
        ]),
        ("Чанд сумка?", [
            t("I have bags.", "Ман сумкаҳо дорам.", "Бипурс: чанд сумка?", "How many bags?", "Чанд сумка?",
              ["How many?", "How many bags do you have?"]),
            t("Three. One is very heavy.", "Се. Яктош хеле вазнин.", "Бигӯ: мушкил нест, ман ёрӣ медиҳам",
              "No problem. Let me help.", "Мушкил нест. Ман ёрӣ медиҳам.", ["Let me help.", "No problem."]),
            t("This small one stays with me.", "Ин хурдашро бо худ мегирам.", "Бигӯ: хуб", "Okay.", "Хуб.",
              ["Okay, sure.", "Sure."]),
        ]),
        ("Бағоҷдон", [
            s("Open the trunk?", "Бағоҷдонро кушоям?", None),
            s("Is that all?", "Ҳамаш ҳамин?", None),
            s("It's too big.", "Хеле калон аст.", None),
            s("Put it in front.", "Дар пеш гузоред.", None),
            s("Be careful, please.", "Эҳтиёт шавед, лутфан.", None),
            s("The trunk is full.", "Бағоҷдон пур аст.", None),
        ]),
        ("Ҷой намешавад", [
            t("Can you open the trunk?", "Бағоҷдонро кушода метавонед?", "Бигӯ: ҳа, мекушоям",
              "Yes, I can open it.", "Ҳа, кушода метавонам.", ["Sure.", "Yes, one second."]),
            t("Here is the last bag.", "Ана сумкаи охирин.", "Бигӯ: бағоҷдон пур аст", "The trunk is full.",
              "Бағоҷдон пур аст.", ["It doesn't fit.", "Sorry, it's full."]),
            t("Oh no! What now?", "Вой! Акнун чӣ?", "Бигӯ: дар пеш гузоред", "Put it in front.",
              "Дар пеш гузоред.", ["In the front seat.", "Put it here, in front."]),
        ]),
        ("Фаромӯш накунед", [
            s("Don't forget your bag.", "Сумкаатонро фаромӯш накунед.", None),
            s("Is this your phone?", "Ин телефони шумост?", None),
            s("Take your things.", "Чизҳоятонро гиред.", None),
            s("Here you go.", "Марҳамат.", None),
            s("I can close it.", "Пӯшида метавонам.", None),
            s("Anything else?", "Боз чизе?", None),
        ]),
        ("Телефони шумо", [
            t("Thank you for the ride!", "Барои роҳ ташаккур!", "Бигӯ: сумкаатонро фаромӯш накунед",
              "Don't forget your bag.", "Сумкаатонро фаромӯш накунед.", ["Your bag!", "Take your bag, please."]),
            t("Oh, yes! Thanks.", "О, ҳа! Ташаккур.", "Бипурс: ин телефони шумост?", "Is this your phone?",
              "Ин телефони шумост?", ["Your phone?", "Is this phone yours?"]),
            t("Yes! Thank you so much!", "Ҳа! Ташаккури зиёд!", "Бигӯ: марҳамат", "Here you go.", "Марҳамат.",
              ["You're welcome.", "Here."]),
        ]),
        ("Миссия: бағоҷи калон", [
            t("Hi! I have three bags.", "Салом! Ман се сумка дорам.", "Бигӯ: ман ёрӣ медиҳам", "I can help.",
              "Ман ёрӣ медиҳам.", ["I'll help you.", "I can help."]),
            t("Thanks! This one is very heavy.", "Ташаккур! Ин хеле вазнин.",
              "Бигӯ: мушкил нест, кушода метавонам", "No problem. I can open it.",
              "Мушкил нест. Кушода метавонам.", ["No problem.", "I'll open the trunk."]),
            t("Can the small bag go in front?", "Сумкаи хурд дар пеш меравад?", "Бигӯ: ҳа, албатта",
              "Yes, of course.", "Ҳа, албатта.", ["Sure.", "Yes."]),
            t("We're here. Thank you!", "Расидем. Ташаккур!", "Бигӯ: сумкаатонро фаромӯш накунед",
              "Don't forget your bag.", "Сумкаатонро фаромӯш накунед.", ["Your bags, please.", "Take your bags."]),
        ]),
    ]))

# ═════════════════════ 8. Пардохти пули роҳ ═════════════════════
made.append(pack("fare_en_tg", "Paying the fare", "Пардохти пули роҳ", "💵", 8, D,
    "Мусофир мепурсад, ки чанд пул аст. Шумо нархро мегӯед, мепурсед нақд ё корт, "
    "бақия медиҳед, чек пешниҳод мекунед ва барои чойпулӣ ташаккур мегӯед.",
    [
        ("Пул", [
            w("Cash", "пули нақд", None),
            w("Card", "корт", None),
            w("Change", "бақия", "Пули боқимонда, ки ба мусофир бармегардонед."),
            w("Receipt", "чек", None),
            w("Tip", "чойпулӣ", None),
            w("Dollars", "доллар", None),
        ]),
        ("Чанд пул?", [
            t("How much is it?", "Чанд пул аст?", "Бигӯ: понздаҳ доллар", "Fifteen dollars.",
              "Понздаҳ доллар.", ["It's fifteen dollars.", "Fifteen."]),
            t("Can I pay by card?", "Бо корт пардохт карда метавонам?", "Бигӯ: ҳа, албатта", "Yes, of course.",
              "Ҳа, албатта.", ["Sure.", "Yes, card is fine."]),
            t("Here's my card.", "Ана корти ман.", "Ташаккур гӯй", "Thank you.", "Ташаккур.",
              ["Thanks.", "Thank you very much."]),
        ]),
        ("Бо корт", [
            s("By card", "Бо корт", None),
            s("In cash", "Нақд", None),
            s("Your change", "Бақияатон", None),
            s("Fifteen dollars", "Понздаҳ доллар", None),
            s("Tap here", "Ин ҷо расонед", "Кортро ба дастгоҳ расонед."),
            s("Twenty dollars", "Бист доллар", None),
        ]),
        ("Нақд ё корт?", [
            t("We're here? How much?", "Расидем? Чанд?", "Бигӯ: понздаҳ доллар", "Fifteen dollars.",
              "Понздаҳ доллар.", ["It's fifteen.", "Fifteen dollars, please."]),
            t("Okay.", "Хуб.", "Бипурс: нақд ё корт?", "Cash or card?", "Нақд ё корт?",
              ["Card or cash?", "Cash or card, please?"]),
            t("Card, please.", "Корт, лутфан.", "Бигӯ: ин ҷо расонед", "Tap here.", "Ин ҷо расонед.",
              ["Tap here, please.", "Please tap here."]),
        ]),
        ("Бақия", [
            s("Cash or card?", "Нақд ё корт?", None),
            s("Here is your change.", "Ана бақияатон.", None),
            s("Need a receipt?", "Чек лозим?", None),
            s("The card doesn't work.", "Корт кор намекунад.", None),
            s("Try again, please.", "Боз кӯшиш кунед, лутфан.", None),
            s("It's twenty dollars.", "Бист доллар мешавад.", None),
        ]),
        ("Чек лозим?", [
            t("Twenty dollars? Here, fifty.", "Бист доллар? Ана, панҷоҳ.", "Бигӯ: ана бақияатон",
              "Here is your change.", "Ана бақияатон.", ["Your change.", "Here's your change."]),
            t("Thanks.", "Ташаккур.", "Бипурс: чек лозим?", "Need a receipt?", "Чек лозим?",
              ["Do you need a receipt?", "Receipt?"]),
            t("Yes, please.", "Ҳа, лутфан.", "Бигӯ: марҳамат", "Here you go.", "Марҳамат.",
              ["Here.", "Here is your receipt."]),
        ]),
        ("Чойпулӣ", [
            s("Thanks for the tip!", "Барои чойпулӣ ташаккур!", None),
            s("That's very kind.", "Хеле меҳрубонед.", None),
            s("I don't have change.", "Ман бақия надорам.", None),
            s("Ten dollars, please.", "Даҳ доллар, лутфан.", None),
            s("Pay by card?", "Бо корт пардохт?", None),
            s("No change? Okay.", "Бақия нест? Хуб.", None),
        ]),
        ("Бақия надорам", [
            t("I only have a hundred.", "Ман танҳо сад дорам.", "Бигӯ: ман бақия надорам",
              "I don't have change.", "Ман бақия надорам.", ["Sorry, no change.", "I have no change."]),
            t("Oh. Can I pay by card?", "О. Бо корт шавад?", "Бигӯ: ҳа, ин ҷо расонед", "Yes, tap here.",
              "Ҳа, ин ҷо расонед.", ["Sure. Tap here.", "Yes, of course."]),
            t("Done. And five dollars for you.", "Тайёр. Ва панҷ доллар барои шумо.",
              "Барои чойпулӣ ташаккур гӯй", "Thanks for the tip!", "Барои чойпулӣ ташаккур!",
              ["Thank you so much!", "That's very kind. Thanks!"]),
        ]),
        ("Миссия: пардохт", [
            t("Great ride! How much is it?", "Роҳи хуб! Чанд пул аст?", "Бигӯ: понздаҳ доллар",
              "Fifteen dollars.", "Понздаҳ доллар.", ["It's fifteen dollars.", "Fifteen."]),
            t("Here's twenty.", "Ана бист.", "Бигӯ: ана бақияатон", "Here is your change.", "Ана бақияатон.",
              ["Your change.", "Here's your change."]),
            t("Thanks. Can I get a receipt?", "Ташаккур. Чек мегирам?", "Бигӯ: ҳа, марҳамат",
              "Yes, here you go.", "Ҳа, марҳамат.", ["Sure, here.", "Yes, of course."]),
            t("And this is for you.", "Ва ин барои шумо.", "Барои чойпулӣ ташаккур гӯй", "Thanks for the tip!",
              "Барои чойпулӣ ташаккур!", ["Thank you so much!", "Thank you! Have a nice day!"]),
        ]),
    ]))

# ═════════════════════ 9. Гап бо мусофир ═════════════════════
made.append(pack("smalltalk_en_tg", "Talking with passengers", "Гап бо мусофир", "💬", 9, D,
    "Дар роҳ мусофир гап мезанад: аз куҷо ҳастед, оила доред, ҳаво чӣ хел аст. Шумо кӯтоҳ "
    "ҷавоб медиҳед, дар бораи мусиқӣ ва гармию хунукӣ мепурсед.",
    [
        ("Ҳаво ва мусиқӣ", [
            w("Music", "мусиқӣ", None),
            w("Weather", "ҳаво", None),
            w("Rain", "борон", None),
            w("Hot", "гарм", None),
            w("Cold", "хунук", None),
            w("Quiet", "ором", None),
        ]),
        ("Аз куҷо ҳастед?", [
            t("Where are you from?", "Шумо аз куҷо ҳастед?", "Бигӯ: аз Тоҷикистон", "From Tajikistan.",
              "Аз Тоҷикистон.", ["I'm from Tajikistan.", "Tajikistan."]),
            t("Oh, nice! Do you like it here?", "О, хуб! Ин ҷо ба шумо писанд аст?", "Бигӯ: ҳа, хеле",
              "Yes, very much.", "Ҳа, хеле.", ["Yes, I like it.", "Yes, it's nice."]),
            t("Is this job hard?", "Ин кор душвор аст?", "Бигӯ: не, ба ман писанд аст", "No, I like it.",
              "Не, ба ман писанд аст.", ["No. It's okay.", "Not really. I like it."]),
        ]),
        ("Мусиқӣ хуб?", [
            s("Music okay?", "Мусиқӣ хуб?", None),
            s("Too loud?", "Хеле баланд?", None),
            s("Nice weather", "Ҳавои хуб", None),
            s("Very hot", "Хеле гарм", None),
            s("Heavy rain", "Борони сахт", None),
            s("Me too", "Ман ҳам", None),
        ]),
        ("Суруди хуб", [
            t("Can you turn on the radio?", "Радиоро мемонед?", "Бигӯ: ҳа, албатта", "Yes, of course.",
              "Ҳа, албатта.", ["Sure.", "Yes."]),
            t("Thanks. I like this song.", "Ташаккур. Ин суруд ба ман писанд.", "Бигӯ: ман ҳам", "Me too.",
              "Ман ҳам.", ["I like it too.", "Me too! Nice song."]),
            t("It's a little loud.", "Каме баланд аст.", "Бигӯ: бубахшед. Ҳоло беҳтар?", "Sorry. Better now?",
              "Бубахшед. Ҳоло беҳтар?", ["Sorry! Is it okay now?", "Sorry. Better?"]),
        ]),
        ("Ман аз Тоҷикистон", [
            own("I'm from ___.", "Ман аз ___ ҳастам.", "Шаҳр ё кишвари худро гӯед.",
                "Where are you from?", "Шумо аз куҷо ҳастед?", "Ҷои худро гӯед"),
            s("I like this city.", "Ин шаҳр ба ман писанд.", None),
            s("Are you from here?", "Шумо аз ҳамин ҷоед?", None),
            s("Is it too hot?", "Хеле гарм аст?", None),
            s("It's going to rain.", "Борон меборад.", None),
            s("Nice weather today.", "Имрӯз ҳаво хуб.", None),
        ]),
        ("Хеле гарм", [
            t("Wow, it's so hot today!", "Во, имрӯз хеле гарм!", "Бипурс: хеле гарм аст?", "Is it too hot?",
              "Хеле гарм аст?", ["Too hot?", "Is it too hot in here?"]),
            t("Yes, a little.", "Ҳа, каме.", "Бигӯ: як сония", "One second.", "Як сония.",
              ["Just a second.", "Okay, one second."]),
            t("Thanks! Much better.", "Ташаккур! Хеле беҳтар.", "Бигӯ: олӣ", "Great!", "Олӣ!",
              ["Good.", "Great, no problem."]),
        ]),
        ("Оила", [
            s("I have two kids.", "Ман ду фарзанд дорам.", None),
            s("My family is there.", "Оилаам он ҷост.", None),
            s("I work every day.", "Ман ҳар рӯз кор мекунам.", None),
            s("Here for work?", "Барои кор омадед?", None),
            s("Welcome to the city!", "Ба шаҳр хуш омадед!", None),
            s("Have a good trip!", "Сафари хуш!", None),
        ]),
        ("Оила доред?", [
            t("Do you have a family?", "Шумо оила доред?", "Бигӯ: ҳа, ман ду фарзанд дорам",
              "Yes, I have two kids.", "Ҳа, ман ду фарзанд дорам.", ["Yes. Two kids.", "I have two kids."]),
            t("Are they here?", "Онҳо ин ҷоянд?", "Бигӯ: не, оилаам он ҷост", "No, my family is there.",
              "Не, оилаам он ҷост.", ["No. In Tajikistan.", "No, they are at home."]),
            t("I'm here for work too.", "Ман ҳам барои кор омадам.", "Бигӯ: ба шаҳр хуш омадед",
              "Welcome to the city!", "Ба шаҳр хуш омадед!", ["Welcome!", "Oh, welcome!"]),
        ]),
        ("Миссия: сӯҳбат дар роҳ", [
            t("Hi! Nice weather today, right?", "Салом! Имрӯз ҳаво хуб, ҳа?", "Бигӯ: ҳа, хеле хуб",
              "Yes, very nice.", "Ҳа, хеле хуб.", ["Yes, nice weather.", "Yes, it's nice."]),
            t("Where are you from?", "Шумо аз куҷо ҳастед?", "Бигӯ: аз Тоҷикистон", "From Tajikistan.",
              "Аз Тоҷикистон.", ["I'm from Tajikistan.", "Tajikistan."]),
            t("Cool! Do you like it here?", "Ҷолиб! Ин ҷо ба шумо писанд аст?",
              "Бигӯ: ҳа, ин шаҳр ба ман писанд", "Yes, I like this city.", "Ҳа, ин шаҳр ба ман писанд.",
              ["Yes, very much.", "Yes, I like it."]),
            t("Can you turn on some music?", "Мусиқӣ мемонед?", "Бигӯ: ҳа, албатта", "Yes, of course.",
              "Ҳа, албатта.", ["Sure.", "Sure, one second."]),
        ]),
    ]))

# ═════════════════════ 11. Нуқтаи сӯзишворӣ ═════════════════════
made.append(pack("fuel_en_tg", "At the gas station", "Нуқтаи сӯзишворӣ", "⛽", 11, D,
    "Бензин кам аст. Шумо ба нуқтаи сӯзишворӣ меравед, рақами колонкаро мегӯед, пул "
    "медиҳед, бод ба чарх медиҳед ва мошинро мешӯед.",
    [
        ("Колонка", [
            w("Pump", "колонка", None),
            w("Diesel", "дизел", None),
            w("Air", "бод", "Бод барои чарх."),
            w("Oil", "равған", None),
            w("Wash", "шустан", None),
            w("Full", "пур", None),
        ]),
        ("Колонкаи чор", [
            t("Hi! Which pump?", "Салом! Кадом колонка?", "Бигӯ: рақами чор", "Number four.", "Рақами чор.",
              ["Pump four.", "Four, please."]),
            t("How much gas?", "Чанд бензин?", "Бигӯ: пур, лутфан", "Full, please.", "Пур, лутфан.",
              ["Fill it up, please.", "A full tank, please."]),
            t("Okay. Cash or card?", "Хуб. Нақд ё корт?", "Бигӯ: корт", "Card.", "Корт.",
              ["By card.", "Card, please."]),
        ]),
        ("Бензини оддӣ", [
            s("Pump four", "Колонкаи чор", None),
            s("Full tank", "Баки пур", None),
            s("Forty dollars", "Чил доллар", None),
            s("Regular gas", "Бензини оддӣ", None),
            s("Car wash", "Мошиншӯӣ", None),
            s("Oil change", "Иваз кардани равған", None),
        ]),
        ("Оддӣ ё дизел?", [
            t("Regular or diesel?", "Оддӣ ё дизел?", "Бигӯ: оддӣ", "Regular.", "Оддӣ.",
              ["Regular, please.", "Regular gas."]),
            t("How much?", "Чанд?", "Бигӯ: чил доллар", "Forty dollars.", "Чил доллар.",
              ["Forty, please.", "Forty dollars, please."]),
            t("Okay, pump four is ready.", "Хуб, колонкаи чор тайёр.", "Ташаккур гӯй", "Thank you.",
              "Ташаккур.", ["Thanks.", "Great, thanks."]),
        ]),
        ("Бод ва равған", [
            s("Where is the air?", "Бод куҷост?", None),
            s("My tire needs air.", "Чархам бод мехоҳад.", None),
            s("I need oil.", "Ба ман равған лозим.", None),
            s("The pump doesn't work.", "Колонка кор намекунад.", None),
            s("Where is the toilet?", "Ҳоҷатхона куҷост?", None),
            s("A coffee, please.", "Як қаҳва, лутфан.", None),
        ]),
        ("Колонка кор намекунад", [
            t("Hi. Can I help you?", "Салом. Ёрӣ диҳам?", "Бигӯ: колонка кор намекунад",
              "The pump doesn't work.", "Колонка кор намекунад.",
              ["Pump four doesn't work.", "The pump is not working."]),
            t("Try pump five, please.", "Колонкаи панҷро санҷед, лутфан.", "Бигӯ: хуб, ташаккур",
              "Okay, thank you.", "Хуб, ташаккур.", ["Okay.", "Thanks."]),
            t("Anything else?", "Боз чизе?", "Бигӯ: як қаҳва, лутфан", "A coffee, please.",
              "Як қаҳва, лутфан.", ["One coffee, please.", "Coffee, please."]),
        ]),
        ("Мошиншӯӣ", [
            s("A car wash, please.", "Мошиншӯӣ, лутфан.", None),
            s("How much is it?", "Чанд пул аст?", None),
            s("It's free today.", "Имрӯз ройгон аст.", None),
            s("Wait five minutes.", "Панҷ дақиқа сабр кунед.", None),
            s("Is it open now?", "Ҳозир кушода аст?", None),
            s("The car is clean!", "Мошин тоза шуд!", None),
        ]),
        ("Мошин тоза шуд", [
            t("Do you want a car wash?", "Мошиншӯӣ мехоҳед?", "Бигӯ: ҳа. Чанд пул аст?",
              "Yes. How much is it?", "Ҳа. Чанд пул аст?", ["Yes. How much?", "How much is it?"]),
            t("It's free today with gas.", "Имрӯз бо бензин ройгон.", "Бигӯ: олӣ! Ташаккур",
              "Great! Thank you.", "Олӣ! Ташаккур.", ["Great!", "Oh, great. Thanks!"]),
            t("Wait five minutes, please.", "Панҷ дақиқа сабр кунед, лутфан.", "Бигӯ: хуб", "Okay.", "Хуб.",
              ["Okay, no problem.", "Sure."]),
        ]),
        ("Миссия: баки пур", [
            t("Hi! Which pump?", "Салом! Кадом колонка?", "Бигӯ: рақами чор", "Number four.", "Рақами чор.",
              ["Pump four.", "Four."]),
            t("Regular or diesel?", "Оддӣ ё дизел?", "Бигӯ: оддӣ, баки пур", "Regular, full tank.",
              "Оддӣ, баки пур.", ["Regular. Full, please.", "Regular, please."]),
            t("That's forty dollars.", "Чил доллар мешавад.", "Бигӯ: корт, лутфан", "Card, please.",
              "Корт, лутфан.", ["By card.", "Here's my card."]),
            t("Done. Anything else?", "Тайёр. Боз чизе?", "Бипурс: бод куҷост?", "Where is the air?",
              "Бод куҷост?", ["Where can I get air?", "Air for my tire?"]),
        ]),
    ]))

# ═════════════════════ 12. Роҳбандӣ ва дер мондан ═════════════════════
made.append(pack("traffic_en_tg", "Traffic and delays", "Роҳбандӣ ва дер мондан", "🚦", 12, D,
    "Роҳ банд аст ва мусофир шитоб дорад. Шумо мегӯед, ки роҳбандӣ аст, чанд дақиқа "
    "мемонад, роҳи дигарро пешниҳод мекунед ва ором мегӯед, ки тезтар рондан бехатар нест.",
    [
        ("Роҳ", [
            w("Traffic", "роҳбандӣ", "Мошинҳои зиёд дар роҳ."),
            w("Late", "дер", None),
            w("Hurry", "шитоб", None),
            w("Road", "роҳ", None),
            w("Bridge", "пул (кӯпрук)", None),
            w("Minutes", "дақиқаҳо", None),
        ]),
        ("Роҳбандӣ", [
            t("Why are we so slow?", "Чаро ин қадар оҳиста?", "Бигӯ: роҳбандӣ зиёд", "Lots of traffic.",
              "Роҳбандӣ зиёд.", ["There's a lot of traffic.", "Traffic, sorry."]),
            t("I'm late for work!", "Ба кор дер мемонам!", "Бигӯ: бубахшед", "I'm sorry.", "Бубахшед.",
              ["Sorry.", "I'm very sorry."]),
            t("How many minutes?", "Чанд дақиқа?", "Бигӯ: даҳ дақиқа", "Ten minutes.", "Даҳ дақиқа.",
              ["About ten minutes.", "Maybe ten minutes."]),
        ]),
        ("Роҳи дигар", [
            s("Bad traffic", "Роҳбандии сахт", None),
            s("Ten minutes", "Даҳ дақиқа", None),
            s("Another road", "Роҳи дигар", None),
            s("I'm sorry", "Бубахшед", None),
            s("Road closed", "Роҳ баста", None),
            s("Almost there", "Қариб расидем", None),
        ]),
        ("Тезтар аст?", [
            t("Is there another road?", "Роҳи дигар ҳаст?", "Бигӯ: ҳа, роҳи дигар", "Yes, another road.",
              "Ҳа, роҳи дигар.", ["Yes, there is.", "Yes. Another road."]),
            t("Is it faster?", "Тезтар аст?", "Бигӯ: ҳа, тез аст", "Yes, it's fast.", "Ҳа, тез аст.",
              ["Yes, it's faster.", "A little faster."]),
            t("Okay, let's go that way.", "Хуб, аз он роҳ равем.", "Бигӯ: хуб", "Okay.", "Хуб.",
              ["Okay, sure.", "Sure."]),
        ]),
        ("Роҳ баста", [
            s("The road is closed.", "Роҳ баста аст.", None),
            s("There's an accident.", "Садама шудааст.", None),
            s("We can go around.", "Давр зада меравем.", None),
            s("Traffic is bad.", "Роҳ сахт банд аст.", None),
            s("Sorry for the wait.", "Барои интизорӣ бубахшед.", None),
            s("We're not late.", "Мо дер намемонем.", None),
        ]),
        ("Чӣ шуд?", [
            t("Why are we stopping?", "Чаро истодем?", "Бигӯ: роҳ баста аст", "The road is closed.",
              "Роҳ баста аст.", ["Road closed.", "The road is closed, sorry."]),
            t("Oh no! What happened?", "Вой! Чӣ шуд?", "Бигӯ: садама шудааст", "There's an accident.",
              "Садама шудааст.", ["An accident.", "There's an accident there."]),
            t("What can we do?", "Чӣ кор кунем?", "Бигӯ: давр зада меравем", "We can go around.",
              "Давр зада меравем.", ["Another road.", "Let's go around."]),
        ]),
        ("Бехатар нест", [
            s("I can't go fast.", "Тез рафта наметавонам.", None),
            s("It's not safe.", "Ин бехатар нест.", None),
            s("Five more minutes.", "Боз панҷ дақиқа.", None),
            s("Call your friend?", "Ба дӯстатон занг мезанед?", None),
            s("It's okay.", "Ҳамааш хуб.", None),
            s("We're here now.", "Ҳоло расидем.", None),
        ]),
        ("Тезтар!", [
            t("Faster, please! I'm very late!", "Тезтар, лутфан! Хеле дер мондам!",
              "Бигӯ: тез рафта наметавонам", "I can't go fast.", "Тез рафта наметавонам.",
              ["Sorry, I can't.", "I can't go faster."]),
            t("Why not?", "Чаро не?", "Бигӯ: ин бехатар нест", "It's not safe.", "Ин бехатар нест.",
              ["It's dangerous.", "Not safe, sorry."]),
            t("Okay, okay. How long?", "Хуб, хуб. Чанд вақт?", "Бигӯ: боз панҷ дақиқа. ҳамааш хуб",
              "Five more minutes. It's okay.", "Боз панҷ дақиқа. Ҳамааш хуб.",
              ["Five more minutes.", "Don't worry. Five minutes."]),
        ]),
        ("Миссия: роҳбандӣ", [
            t("Why is it so slow?", "Чаро ин қадар оҳиста?", "Бигӯ: роҳбандӣ зиёд", "Lots of traffic.",
              "Роҳбандӣ зиёд.", ["Bad traffic.", "There's a lot of traffic."]),
            t("I have a flight at six!", "Соати шаш парвоз дорам!", "Бигӯ: ҳамааш хуб", "It's okay.",
              "Ҳамааш хуб.", ["No problem.", "Don't worry, please."]),
            t("Is there another road?", "Роҳи дигар ҳаст?", "Бигӯ: ҳа, давр зада меравем",
              "Yes, we can go around.", "Ҳа, давр зада меравем.", ["Yes, another road.", "Yes. Let's go around."]),
            t("Thank you! Are we close?", "Ташаккур! Наздик шудем?", "Бигӯ: қариб расидем", "Almost there.",
              "Қариб расидем.", ["We're almost there.", "Five more minutes."]),
        ]),
    ]))

# ═════════════════════ 13. Расонидани фармоиш ═════════════════════
made.append(pack("dropoff_en_tg", "Delivering orders", "Расонидани фармоиш", "📦", 13, D,
    "Шумо хӯрок ва бастаҳо мерасонед: мегӯед, ки фармоиш омад, ошёнаро мепурсед, имзо "
    "мегиред ё бастаро назди дар мегузоред ва акс мефиристед.",
    [
        ("Фармоиш", [
            w("Order", "фармоиш", None),
            w("Package", "баста", None),
            w("Broken", "шикаста", None),
            w("Apartment", "хона (квартира)", None),
            w("Sign", "имзо кардан", None),
            w("Delivery", "расонидан", None),
        ]),
        ("Фармоиши шумо", [
            t("Hello?", "Салом?", "Бигӯ: фармоиши шумо", "Your order.", "Фармоиши шумо.",
              ["Delivery!", "Here is your order."]),
            t("Oh, great! Thank you.", "О, олӣ! Ташаккур.", "Бигӯ: лутфан, ин ҷо имзо кунед",
              "Sign here, please.", "Лутфан, ин ҷо имзо кунед.", ["Please sign here.", "Sign here."]),
            t("Here you go.", "Марҳамат.", "Бигӯ: ташаккур. Рӯзи хуш", "Thanks. Have a nice day!",
              "Ташаккур. Рӯзи хуш!", ["Thank you!", "Have a good day!"]),
        ]),
        ("Ин ҷо имзо кунед", [
            s("Your order", "Фармоиши шумо", None),
            s("Sign here", "Ин ҷо имзо кунед", None),
            s("Which floor?", "Кадом ошёна?", None),
            s("Front door", "Дари даромад", None),
            s("Hot food", "Хӯроки гарм", None),
            s("Two boxes", "Ду қуттӣ", None),
        ]),
        ("Кадом ошёна?", [
            t("Hi! Come in. Apartment twelve.", "Салом! Дароед. Хонаи дувоздаҳ.", "Бипурс: кадом ошёна?",
              "Which floor?", "Кадом ошёна?", ["What floor?", "Which floor, please?"]),
            t("The third floor.", "Ошёнаи сеюм.", "Бигӯ: хуб, меоям", "Okay, coming.", "Хуб, меоям.",
              ["Okay.", "I'm coming."]),
            t("Is it hot food?", "Хӯрок гарм аст?", "Бигӯ: ҳа, хӯроки гарм", "Yes, hot food.",
              "Ҳа, хӯроки гарм.", ["Yes, it's hot.", "Yes."]),
        ]),
        ("Назди дар", [
            s("I'm at the door.", "Ман назди дар ҳастам.", None),
            s("Leave it here?", "Ин ҷо гузорам?", None),
            s("Is this apartment twelve?", "Ин хонаи дувоздаҳ аст?", None),
            s("No one is home.", "Касе дар хона нест.", None),
            s("At the door?", "Назди дар?", None),
            s("A photo, okay?", "Акс, хуб?", None),
        ]),
        ("Касе нест", [
            t("Hello? Who is this?", "Алло? Кӣ?", "Бигӯ: расонидан. Ман назди дар ҳастам",
              "Delivery. I'm at the door.", "Расонидан. Ман назди дар ҳастам.",
              ["I'm at the door.", "Delivery! I'm here."]),
            t("Sorry, I'm not home.", "Бубахшед, ман дар хона нестам.", "Бипурс: ин ҷо гузорам?",
              "Leave it here?", "Ин ҷо гузорам?", ["Can I leave it here?", "At the door?"]),
            t("Yes, at the door, please.", "Ҳа, назди дар, лутфан.", "Бигӯ: хуб. Акс мефиристам",
              "Okay. I can send a photo.", "Хуб. Акс фиристода метавонам.", ["Okay.", "Okay, I'll leave it here."]),
        ]),
        ("Чизе нест", [
            s("This box is broken.", "Ин қуттӣ шикастааст.", None),
            s("Only two boxes?", "Танҳо ду қуттӣ?", None),
            s("Call the store?", "Ба мағоза занг занам?", None),
            s("Sorry about that.", "Барои ин бубахшед.", None),
            s("Is everything there?", "Ҳама чиз ҳаст?", None),
            s("Please check it.", "Лутфан, санҷед.", None),
        ]),
        ("Нӯшокӣ нест", [
            t("Wait, my drink is missing.", "Истед, нӯшокиам нест.", "Бигӯ: бубахшед. Ба мағоза занг мезанам",
              "Sorry. I can call the store.", "Бубахшед. Ба мағоза занг зада метавонам.",
              ["I'm sorry. I'll call them.", "Sorry about that."]),
            t("Okay, thanks.", "Хуб, ташаккур.", "Бипурс: дигар ҳама чиз ҳаст?", "Is everything else there?",
              "Дигар ҳама чиз ҳаст?", ["Everything else okay?", "Is the rest okay?"]),
            t("Yes, the rest is fine.", "Ҳа, боқимонда хуб аст.", "Бигӯ: хуб. Рӯзи хуш",
              "Okay. Have a nice day!", "Хуб. Рӯзи хуш!", ["Have a good day!", "Okay, bye!"]),
        ]),
        ("Миссия: расонидан", [
            t("Hello? Who is it?", "Салом? Кӣ?", "Бигӯ: расонидан. Фармоиши шумо", "Delivery. Your order.",
              "Расонидан. Фармоиши шумо.", ["Delivery!", "Your order is here."]),
            t("Great! Come up, third floor.", "Олӣ! Бароед, ошёнаи сеюм.", "Бигӯ: хуб, меоям",
              "Okay, coming.", "Хуб, меоям.", ["Okay.", "I'm coming."]),
            t("Hi! Is it all there?", "Салом! Ҳамааш ҳаст?", "Бигӯ: ҳа. Лутфан, ин ҷо имзо кунед",
              "Yes. Sign here, please.", "Ҳа. Лутфан, ин ҷо имзо кунед.", ["Yes. Please sign here.", "Yes, everything."]),
            t("Done. Thank you!", "Тайёр. Ташаккур!", "Бигӯ: рӯзи хуш", "Have a nice day!", "Рӯзи хуш!",
              ["Have a good day!", "You're welcome. Bye!"]),
        ]),
    ]))

# ═════════════════════ 15. Занг ба мизоҷ ═════════════════════
made.append(pack("customer_call_en_tg", "Calling the customer", "Занг ба мизоҷ", "📱", 15, D,
    "Шумо ба суроға расидед, вале мизоҷ нест. Бо телефон занг мезанед: мегӯед, ки "
    "расидед, мепурсед ӯ куҷост, мошинатонро мегӯед ва агар алоқа бад бошад — боз мепурсед.",
    [
        ("Телефон", [
            w("Phone", "телефон", None),
            w("Call", "занг", None),
            w("Outside", "берун", None),
            w("Wait", "интизор шудан", None),
            w("Black", "сиёҳ", None),
            w("Gate", "дарвоза", None),
        ]),
        ("Ман расидам", [
            t("Hello?", "Алло?", "Бигӯ: салом, ман ронандаи шумо", "Hi, I'm your driver.",
              "Салом, ман ронандаи шумоям.", ["Hello, this is your driver.", "Hi! Your driver."]),
            t("Oh, hi! Are you here?", "О, салом! Расидед?", "Бигӯ: ҳа, ман берун ҳастам", "Yes, I'm outside.",
              "Ҳа, ман берунам.", ["Yes, I'm here.", "I'm outside."]),
            t("Okay, one minute.", "Хуб, як дақиқа.", "Бигӯ: хуб, интизор мешавам", "Okay, I can wait.",
              "Хуб, интизор шуда метавонам.", ["No problem.", "Okay, I'm waiting."]),
        ]),
        ("Мошини сиёҳ", [
            s("I'm outside", "Ман берунам", None),
            s("Black car", "Мошини сиёҳ", None),
            s("One minute", "Як дақиқа", None),
            s("Where exactly?", "Дақиқан куҷо?", None),
            s("Big gate", "Дарвозаи калон", None),
            s("Call me", "Ба ман занг занед", None),
        ]),
        ("Шумо куҷоед?", [
            t("I'm outside too. Where are you?", "Ман ҳам берунам. Шумо куҷоед?",
              "Бигӯ: назди дарвозаи калон", "At the big gate.", "Назди дарвозаи калон.",
              ["By the big gate.", "Near the big gate."]),
            t("What car is it?", "Кадом мошин?", "Бигӯ: Тойотаи сиёҳ", "A black Toyota.", "Тойотаи сиёҳ.",
              ["Black Toyota.", "A black car, Toyota."]),
            t("I see you! Coming.", "Шуморо мебинам! Меоям.", "Бигӯ: хуб", "Okay!", "Хуб!",
              ["Great!", "Okay, see you."]),
        ]),
        ("Шуморо намеёбам", [
            s("Where are you now?", "Ҳозир куҷоед?", None),
            s("I can't find you.", "Шуморо ёфта наметавонам.", None),
            s("I'm in front.", "Ман дар пеш ҳастам.", None),
            s("Please come outside.", "Лутфан, берун бароед.", None),
            s("I can wait.", "Интизор шуда метавонам.", None),
            s("Sorry, I can't hear.", "Бубахшед, намешунавам.", None),
        ]),
        ("Куртаи сурх", [
            t("Hi, I'm at the door.", "Салом, ман назди дар.", "Бигӯ: шуморо ёфта наметавонам",
              "I can't find you.", "Шуморо ёфта наметавонам.", ["I don't see you.", "Sorry, I can't find you."]),
            t("I'm at the hotel door. Red jacket.", "Ман назди дари меҳмонхона. Куртаи сурх.",
              "Бигӯ: хуб! Ман дар пеш ҳастам", "Okay! I'm in front.", "Хуб! Ман дар пеш ҳастам.",
              ["I'm in front.", "Okay, I'm coming."]),
            t("Ah, I see you now!", "А, ҳоло шуморо мебинам!", "Бигӯ: олӣ", "Great!", "Олӣ!",
              ["Good!", "Okay, great!"]),
        ]),
        ("Алоқа бад аст", [
            s("I'm five minutes away.", "Панҷ дақиқа роҳ мондааст.", None),
            s("I'm coming now.", "Ҳозир меоям.", None),
            s("Please wait for me.", "Лутфан, маро интизор шавед.", None),
            s("Can you text me?", "Паём навишта метавонед?", None),
            s("The line is bad.", "Алоқа бад аст.", None),
            s("Can you hear me?", "Маро мешунавед?", None),
        ]),
        ("Намешунавам", [
            t("Hello? Where... you... now?", "Алло? Шумо... ҳозир... куҷо?", "Бигӯ: бубахшед, намешунавам",
              "Sorry, I can't hear.", "Бубахшед, намешунавам.", ["Sorry, the line is bad.", "I can't hear you."]),
            t("Hello? Can you hear me now?", "Алло? Ҳозир мешунавед?", "Бигӯ: ҳа. Панҷ дақиқа роҳ мондааст",
              "Yes. I'm five minutes away.", "Ҳа. Панҷ дақиқа роҳ мондааст.",
              ["Yes. Five minutes.", "Yes, five minutes away."]),
            t("Okay, I'll wait at the gate.", "Хуб, назди дарвоза интизор мешавам.", "Бигӯ: хуб, ҳозир меоям",
              "Okay, I'm coming now.", "Хуб, ҳозир меоям.", ["Okay, coming.", "Okay."]),
        ]),
        ("Миссия: занг ба мизоҷ", [
            t("Hello?", "Алло?", "Бигӯ: салом, ман ронандаи шумо. Ман берунам", "Hi, I'm your driver. I'm outside.",
              "Салом, ман ронандаи шумоям. Ман берунам.", ["Hi! I'm outside.", "Your driver. I'm outside."]),
            t("Great! Where exactly?", "Олӣ! Дақиқан куҷо?", "Бигӯ: назди дарвозаи калон", "At the big gate.",
              "Назди дарвозаи калон.", ["By the big gate.", "Near the gate."]),
            t("What car?", "Кадом мошин?", "Бигӯ: Тойотаи сиёҳ", "A black Toyota.", "Тойотаи сиёҳ.",
              ["Black Toyota.", "A black car."]),
            t("Okay, I'm coming in two minutes.", "Хуб, пас аз ду дақиқа меоям.", "Бигӯ: хуб, интизор мешавам",
              "Okay, I can wait.", "Хуб, интизор шуда метавонам.", ["No problem.", "Okay, I'm waiting."]),
        ]),
    ], mission_mode="call"))

# ═════════════════════ 17. Полиси роҳ ═════════════════════
made.append(pack("traffic_stop_en_tg", "Police stop", "Полиси роҳ", "👮", 17, D,
    "Полис мошинро нигоҳ медорад. Шумо ором ҳастед, шаҳодатнома ва суғуртаро медиҳед, "
    "ба саволҳо кӯтоҳ ҷавоб медиҳед ва агар нафаҳмед — хоҳиш мекунед, ки оҳиста гӯяд.",
    [
        ("Ҳуҷҷатҳои ронанда", [
            w("Police", "полис", None),
            w("License", "шаҳодатномаи ронандагӣ", "Дар Англия — «driving licence»."),
            w("Officer", "афсар", "Ба полис «officer» мегӯянд."),
            w("Speed", "суръат", None),
            w("Ticket", "ҷарима", "Коғази ҷарима."),
            w("Insurance", "суғурта", None),
        ]),
        ("Шаҳодатнома, лутфан", [
            t("Hello. License, please.", "Салом. Шаҳодатнома, лутфан.", "Бигӯ: ҳа, марҳамат", "Yes, here you go.",
              "Ҳа, марҳамат.", ["Here it is.", "Yes, officer."]),
            t("And the insurance.", "Ва суғурта.", "Бигӯ: як сония", "One second.", "Як сония.",
              ["Just a second.", "Here it is."]),
            t("Thank you. Stay in the car.", "Ташаккур. Дар мошин монед.", "Бигӯ: хуб", "Okay.", "Хуб.",
              ["Okay, officer.", "Yes, sir."]),
        ]),
        ("Хеле тез", [
            s("Yes, officer", "Ҳа, афсар", None),
            s("My license", "Шаҳодатномаи ман", None),
            s("Car papers", "Ҳуҷҷатҳои мошин", None),
            s("Too fast", "Хеле тез", None),
            s("Speed limit", "Ҳадди суръат", None),
            s("One second", "Як сония", None),
        ]),
        ("Суръататонро медонед?", [
            t("Do you know your speed?", "Суръататонро медонед?", "Бигӯ: не, бубахшед", "No, sorry.",
              "Не, бубахшед.", ["No, officer.", "Sorry, I don't know."]),
            t("You were too fast. Seventy.", "Шумо хеле тез будед. Ҳафтод.", "Бигӯ: бубахшед, афсар",
              "I'm sorry, officer.", "Бубахшед, афсар.", ["Sorry.", "I'm very sorry."]),
            t("The limit here is fifty.", "Ҳадди ин ҷо панҷоҳ.", "Бигӯ: фаҳмидам", "I understand.",
              "Фаҳмидам.", ["Got it.", "Okay, I understand."]),
        ]),
        ("Оҳиста, лутфан", [
            s("Here is my license.", "Ана шаҳодатномаи ман.", None),
            s("I'm very sorry.", "Хеле бубахшед.", None),
            s("Please speak slowly.", "Лутфан, оҳиста гап занед.", None),
            s("Can you repeat?", "Такрор карда метавонед?", None),
            s("Is it a ticket?", "Ин ҷарима аст?", None),
            s("Where do I pay?", "Куҷо пардохт кунам?", None),
        ]),
        ("Суғуртаи кӯҳна", [
            t("Your insurance card is old.", "Корти суғуртаи шумо кӯҳна аст.", "Бигӯ: лутфан, оҳиста гап занед",
              "Please speak slowly.", "Лутфан, оҳиста гап занед.", ["Slowly, please.", "Sorry, slowly please."]),
            t("Your insurance. It's old.", "Суғуртаатон. Кӯҳна.", "Бигӯ: ана навашро", "Here is the new one.",
              "Ана навашро.", ["This is the new one.", "Here, the new one."]),
            t("Okay, thank you.", "Хуб, ташаккур.", "Бипурс: ин ҷарима аст?", "Is it a ticket?",
              "Ин ҷарима аст?", ["A ticket?", "Do I get a ticket?"]),
        ]),
        ("Эҳтиёт мешавам", [
            s("Thank you, officer.", "Ташаккур, афсар.", None),
            s("Can I go now?", "Ҳозир равам?", None),
            s("Okay, I understand.", "Хуб, фаҳмидам.", None),
            s("I'm a taxi driver.", "Ман ронандаи такси ҳастам.", None),
            s("My passenger is waiting.", "Мусофирам интизор аст.", None),
            s("Is everything okay?", "Ҳама чиз хуб?", None),
        ]),
        ("Танҳо огоҳӣ", [
            t("This time, only a warning.", "Ин дафъа танҳо огоҳӣ.", "Бигӯ: ташаккур, афсар",
              "Thank you, officer.", "Ташаккур, афсар.", ["Thanks, officer.", "Thank you very much."]),
            t("Drive slowly, okay?", "Оҳиста ронед, хуб?", "Бигӯ: ҳа, фаҳмидам", "Yes, I understand.",
              "Ҳа, фаҳмидам.", ["Yes, officer.", "I'll be careful."]),
            t("Okay. Here are your papers.", "Хуб. Ана ҳуҷҷатҳоятон.", "Ташаккур гӯй ва бипурс: ҳозир равам?",
              "Thanks. Can I go now?", "Ташаккур. Ҳозир равам?", ["Can I go now?", "Thank you. Can I go?"]),
        ]),
        ("Миссия: полиси роҳ", [
            t("Good evening. License and insurance, please.", "Шоми хуш. Шаҳодатнома ва суғурта, лутфан.",
              "Бигӯ: ҳа, марҳамат", "Yes, here you go.", "Ҳа, марҳамат.", ["Here they are.", "Yes, officer."]),
            t("You were too fast.", "Шумо хеле тез рондед.", "Бигӯ: бубахшед, ҷаноби афсар",
              "Sorry, officer.", "Бубахшед, ҷаноби афсар.", ["I'm sorry, officer.", "Sorry. I didn't know."]),
            t("Here is a school. The limit is twenty.", "Ин ҷо мактаб аст. Ҳадди суръат бист.",
              "Бигӯ: фаҳмидам. бубахшед, ҷаноби афсар", "I understand. Sorry, officer.", "Фаҳмидам. Бубахшед, ҷаноби афсар.",
              ["I understand.", "Okay. I'll be careful."]),
            t("Okay. Only a warning today.", "Хуб. Имрӯз танҳо огоҳӣ.", "Ташаккур гӯй", "Thank you, officer.",
              "Ташаккур, афсар.", ["Thank you very much.", "Thanks, officer."]),
        ]),
    ]))

# ═════════════════════ 18. Мошин вайрон шуд ═════════════════════
made.append(pack("repair_en_tg", "Car trouble", "Мошин вайрон шуд", "🔧", 18, D,
    "Мошин вайрон шуд: чарх пора шуд ё чароғи мотор даргирифт. Шумо ба устохона меравед, "
    "мушкилро кӯтоҳ мегӯед, нарх ва вақтро мепурсед ва чек мегиред.",
    [
        ("Устохона", [
            w("Engine", "мотор", None),
            w("Brakes", "тормоз", None),
            w("Mechanic", "усто", None),
            w("Flat tire", "чархи пора", None),
            w("Battery", "аккумулятор", None),
            w("Noise", "садо", None),
        ]),
        ("Чархи пора", [
            t("Hi! What's the problem?", "Салом! Мушкил чист?", "Бигӯ: чархам пора шуд", "I have a flat tire.",
              "Чархам пора шуд.", ["A flat tire.", "My tire is flat."]),
            t("Okay. Which one?", "Хуб. Кадомаш?", "Бигӯ: қафо, чап", "Back left.", "Қафо, чап.",
              ["The back left.", "Left, in back."]),
            t("No problem. I can fix it.", "Мушкил нест. Дуруст мекунам.", "Бипурс: чанд пул?", "How much?",
              "Чанд пул?", ["How much is it?", "How much for the tire?"]),
        ]),
        ("Чароғи мотор", [
            s("Flat tire", "Чархи пора", None),
            s("Engine light", "Чароғи мотор", None),
            s("Strange noise", "Садои аҷиб", None),
            s("Dead battery", "Аккумулятори холӣ", None),
            s("How long?", "Чанд вақт?", None),
            s("By tonight?", "То бегоҳ?", None),
        ]),
        ("Садои аҷиб", [
            t("What's wrong with the car?", "Мошин чӣ шуд?", "Бигӯ: чароғи мотор даргирифт",
              "The engine light is on.", "Чароғи мотор даргирифт.", ["Engine light.", "The engine light."]),
            t("Any noise?", "Ягон садо ҳаст?", "Бигӯ: ҳа, садои аҷиб", "Yes, a strange noise.",
              "Ҳа, садои аҷиб.", ["Yes, a noise.", "Yes. Strange noise."]),
            t("Okay. I need to check it.", "Хуб. Бояд санҷам.", "Бипурс: чанд вақт?", "How long?",
              "Чанд вақт?", ["How long will it take?", "How long is it?"]),
        ]),
        ("Мошин ба роҳ намеафтад", [
            s("The brakes are bad.", "Тормоз бад аст.", None),
            s("The car doesn't start.", "Мошин ба роҳ намеафтад.", None),
            s("I need it today.", "Имрӯз лозим аст.", None),
            s("It's my taxi.", "Ин таксии ман аст.", None),
            s("Is it expensive?", "Қимат аст?", None),
            s("Can you call me?", "Ба ман занг мезанед?", None),
        ]),
        ("Хизматрасонии мошин", [
            t("Hello, car service.", "Салом, хизматрасонии мошин.", "Бигӯ: мошин ба роҳ намеафтад",
              "The car doesn't start.", "Мошин ба роҳ намеафтад.", ["My car won't start.", "It doesn't start."]),
            t("Maybe the battery. Where are you?", "Шояд аккумулятор. Шумо куҷоед?", "Бигӯ: дар кӯчаи Мейн",
              "On Main Street.", "Дар кӯчаи Мейн.", ["Main Street.", "I'm on Main Street."]),
            t("We can come in one hour.", "Пас аз як соат омада метавонем.", "Бигӯ: хуб, ташаккур",
              "Okay, thank you.", "Хуб, ташаккур.", ["Okay, thanks.", "Great, thank you."]),
        ]),
        ("Тайёр аст?", [
            s("Is it ready?", "Тайёр аст?", None),
            s("What was wrong?", "Чӣ вайрон буд?", None),
            s("Can I pay later?", "Баъдтар пардохт кунам?", None),
            s("That's too expensive.", "Ин хеле қимат аст.", None),
            s("I need a receipt.", "Ба ман чек лозим.", None),
            s("It works now!", "Ҳоло кор мекунад!", None),
        ]),
        ("Аккумулятори нав", [
            t("Hi! Your car is ready.", "Салом! Мошинатон тайёр.", "Бипурс: чӣ вайрон буд?", "What was wrong?",
              "Чӣ вайрон буд?", ["What was it?", "What was the problem?"]),
            t("The battery. The new one is in.", "Аккумулятор. Навашро гузоштем.", "Бипурс: чанд пул аст?",
              "How much is it?", "Чанд пул аст?", ["How much?", "How much do I pay?"]),
            t("One hundred and twenty dollars.", "Саду бист доллар.", "Бигӯ: хуб. Ба ман чек лозим",
              "Okay. I need a receipt.", "Хуб. Ба ман чек лозим.", ["Okay. Receipt, please.", "Okay. A receipt, please."]),
        ]),
        ("Миссия: устохона", [
            t("Hi! How can I help?", "Салом! Чӣ ёрӣ диҳам?", "Бигӯ: чароғи мотор даргирифт",
              "The engine light is on.", "Чароғи мотор даргирифт.", ["Engine light is on.", "My engine light."]),
            t("Okay. Any strange noise?", "Хуб. Ягон садои аҷиб?", "Бигӯ: ҳа. Ва тормоз бад аст",
              "Yes. And the brakes are bad.", "Ҳа. Ва тормоз бад аст.", ["Yes, a noise.", "Yes. Bad brakes too."]),
            t("I need two hours.", "Ба ман ду соат лозим.", "Бигӯ: ин таксии ман. Имрӯз лозим",
              "It's my taxi. I need it today.", "Ин таксии ман. Имрӯз лозим.",
              ["I need it today.", "Today, please. It's for work."]),
            t("Okay, it's ready at five.", "Хуб, соати панҷ тайёр.", "Бигӯ: олӣ, ташаккур", "Great, thank you.",
              "Олӣ, ташаккур.", ["Thank you!", "Okay, thanks."]),
        ]),
    ]))

# ═════════════════════ 19. Садамаи хурд ═════════════════════
made.append(pack("accident_en_tg", "A small accident", "Садамаи хурд", "💥", 19, D,
    "Мошини дигар ба мошини шумо зад. Шумо мепурсед, ки ҳама солим аст, акс мегиред, "
    "суғуртаро иваз мекунед ва ба полис занг мезанед.",
    [
        ("Садама", [
            w("Accident", "садама", None),
            w("Hurt", "захмӣ", None),
            w("Photo", "акс", None),
            w("Damage", "зарар", None),
            w("Bumper", "бампер", None),
            w("Fault", "гуноҳ", None),
        ]),
        ("Шумо хубед?", [
            t("Oh no! Are you okay?", "Вой! Шумо хубед?", "Бигӯ: ҳа, ман хубам. Шумо?", "Yes, I'm okay. You?",
              "Ҳа, ман хубам. Шумо?", ["I'm fine. And you?", "Yes. Are you okay?"]),
            t("I'm fine. I'm so sorry!", "Ман хубам. Хеле бубахшед!", "Бигӯ: ҳеҷ гап не. Касе захмӣ нест",
              "It's okay. No one is hurt.", "Ҳеҷ гап не. Касе захмӣ нест.", ["It's okay.", "No one is hurt."]),
            t("Look at your bumper.", "Бамперро бинед.", "Бигӯ: зарари хурд", "Small damage.", "Зарари хурд.",
              ["Just small damage.", "It's small."]),
        ]),
        ("Гуноҳи кӣ?", [
            s("Small damage", "Зарари хурд", None),
            s("My fault", "Гуноҳи ман", None),
            s("Your fault", "Гуноҳи шумо", None),
            s("Take photos", "Акс гиред", None),
            s("Insurance card", "Корти суғурта", None),
            s("Stay here", "Ин ҷо монед", None),
        ]),
        ("Чароғ сурх буд", [
            t("It's your fault!", "Гуноҳи шумо!", "Бигӯ: не, гуноҳи ман нест", "No, it's not my fault.",
              "Не, гуноҳи ман нест.", ["Not my fault.", "No. It's not my fault."]),
            t("You stopped too fast!", "Шумо хеле тез истодед!", "Бигӯ: чароғ сурх буд", "The light was red.",
              "Чароғ сурх буд.", ["It was a red light.", "Red light!"]),
            t("Okay, okay. Let's call the police.", "Хуб, хуб. Ба полис занг занем.", "Бигӯ: хуб", "Okay.",
              "Хуб.", ["Okay, let's call.", "Yes, let's call."]),
        ]),
        ("Акс мегирам", [
            s("Take photos?", "Акс гирам?", None),
            s("No one is hurt.", "Касе захмӣ нест.", None),
            s("Call the police.", "Ба полис занг занед.", None),
            s("Here is my insurance.", "Ана суғуртаи ман.", None),
            s("Your phone number?", "Рақами телефонатон?", None),
            s("Please wait here.", "Лутфан, ин ҷо истед.", None),
        ]),
        ("Суғурта доред?", [
            t("Do you have insurance?", "Суғурта доред?", "Бигӯ: ҳа, ана суғуртаи ман",
              "Yes, here is my insurance.", "Ҳа, ана суғуртаи ман.", ["Yes. Here it is.", "Yes, here."]),
            t("Thanks. Here is mine.", "Ташаккур. Ана аз ман.", "Бипурс: рақами телефонатон?",
              "Your phone number?", "Рақами телефонатон?", ["What's your phone number?", "Phone number, please?"]),
            t("It's on the card.", "Дар корт ҳаст.", "Бигӯ: хуб. Ман акс мегирам", "Okay. I can take photos.",
              "Хуб. Акс гирифта метавонам.", ["I'll take photos.", "Okay, thanks."]),
        ]),
        ("Занг ба полис", [
            s("It's an accident.", "Садама шуд.", None),
            s("I'm on Main Street.", "Ман дар кӯчаи Мейн ҳастам.", None),
            s("We need the police.", "Ба мо полис лозим.", None),
            s("I have a passenger.", "Ман мусофир дорам.", None),
            s("My back hurts.", "Пуштам дард мекунад.", None),
            s("Please come quickly.", "Лутфан, зуд биёед.", None),
        ]),
        ("Полис, чӣ шуд?", [
            t("Police. What happened?", "Полис. Чӣ шуд?", "Бигӯ: садама шуд", "It's an accident.",
              "Садама шуд.", ["A car hit my car.", "An accident. A car hit me."]),
            t("Where are you?", "Шумо куҷоед?", "Бигӯ: ман дар кӯчаи Мейн", "I'm on Main Street.",
              "Ман дар кӯчаи Мейн ҳастам.", ["Main Street.", "On Main Street."]),
            t("Is anyone hurt?", "Касе захмӣ аст?", "Бигӯ: не, касе захмӣ нест", "No, no one is hurt.",
              "Не, касе захмӣ нест.", ["No one is hurt.", "No, we're okay."]),
        ]),
        ("Миссия: садама", [
            t("Are you okay?", "Шумо хубед?", "Бигӯ: ҳа, ман хубам. Шумо?", "Yes, I'm okay. You?",
              "Ҳа, ман хубам. Шумо?", ["I'm fine. And you?", "Yes. Are you okay?"]),
            t("I'm fine. Sorry, it's my fault.", "Ман хубам. Бубахшед, гуноҳи ман.",
              "Бигӯ: хуб. Суғурта доред?", "Okay. Do you have insurance?", "Хуб. Суғурта доред?",
              ["Your insurance, please.", "Do you have insurance?"]),
            t("Yes. Here is my card.", "Ҳа. Ана корти ман.", "Бигӯ: ташаккур. Ман акс мегирам",
              "Thanks. I can take photos.", "Ташаккур. Акс гирифта метавонам.", ["I'll take photos.", "Thank you. Photos, okay?"]),
            t("Sure. Should we call the police?", "Албатта. Ба полис занг занем?", "Бигӯ: ҳа, ба мо полис лозим",
              "Yes, we need the police.", "Ҳа, ба мо полис лозим.", ["Yes, let's call.", "Yes. We need a report."]),
        ]),
    ]))

# ═════════════════════ 20. Навбати корӣ ва даромад ═════════════════════
made.append(pack("shift_en_tg", "Shift and earnings", "Навбати корӣ ва даромад", "💰", 20, D,
    "Бо диспетчер ва сардори ширкат дар бораи кор гап мезанед: кай сар мекунед ва кай "
    "тамом, рӯзи истироҳат, музди ҳафта, барнома ва баҳои мусофирон.",
    [
        ("Навбат", [
            w("Shift", "навбати корӣ", "Вақти кор: рӯз ё шаб."),
            w("App", "барнома", "Барномаи телефон, ки фармоишҳо меоранд."),
            w("Rating", "баҳо", "Баҳои мусофирон — аз 1 то 5 ситора."),
            w("Week", "ҳафта", None),
            w("Day off", "рӯзи истироҳат", None),
            w("Night", "шаб", None),
        ]),
        ("Навбати шаб", [
            t("Can you work the night shift?", "Навбати шаб кор карда метавонед?", "Бигӯ: ҳа, метавонам",
              "Yes, I can.", "Ҳа, метавонам.", ["Yes.", "Sure, I can."]),
            t("It starts at eight.", "Соати ҳашт сар мешавад.", "Бипурс: кай тамом мешавад?", "When does it end?",
              "Кай тамом мешавад?", ["And the end?", "When does it finish?"]),
            t("At four in the morning.", "Соати чори субҳ.", "Бигӯ: хуб", "Okay.", "Хуб.",
              ["Okay, no problem.", "Okay, fine."]),
        ]),
        ("Панҷ ситора", [
            s("Night shift", "Навбати шаб", None),
            s("Day off", "Рӯзи истироҳат", None),
            s("Every week", "Ҳар ҳафта", None),
            s("Good rating", "Баҳои хуб", None),
            s("Five stars", "Панҷ ситора", None),
            s("Weekly pay", "Музди ҳафтаина", None),
        ]),
        ("Рӯзи истироҳат", [
            t("You work six days.", "Шумо шаш рӯз кор мекунед.", "Бипурс: рӯзи истироҳатам кай?",
              "When is my day off?", "Рӯзи истироҳатам кай?", ["My day off?", "Which day is off?"]),
            t("Sunday.", "Якшанбе.", "Бигӯ: хуб, ташаккур", "Okay, thank you.", "Хуб, ташаккур.",
              ["Okay.", "Good, thanks."]),
            t("And you get paid every week.", "Ва ҳар ҳафта музд мегиред.", "Бигӯ: олӣ", "Great!", "Олӣ!",
              ["Very good.", "Great, thanks!"]),
        ]),
        ("Соатҳои бештар", [
            s("When do I start?", "Кай сар кунам?", None),
            s("I want more hours.", "Ман соатҳои бештар мехоҳам.", None),
            s("I can't work Friday.", "Ҷумъа кор карда наметавонам.", None),
            s("I'm sick today.", "Имрӯз бемор ҳастам.", None),
            s("The app doesn't work.", "Барнома кор намекунад.", None),
            own("I work ___ hours.", "Ман ___ соат кор мекунам.", "Чанд соат кор мекунед — шумораро гӯед.",
                "How many hours do you work?", "Чанд соат кор мекунед?", "Шумораи соатҳоро гӯед"),
        ]),
        ("Барнома кор намекунад", [
            t("Dispatch. How can I help?", "Диспетчер. Чӣ ёрӣ диҳам?", "Бигӯ: барнома кор намекунад",
              "The app doesn't work.", "Барнома кор намекунад.", ["My app is not working.", "The app is broken."]),
            t("Close it and open it again.", "Бандед ва боз кушоед.", "Бигӯ: хуб, як дақиқа", "Okay, one minute.",
              "Хуб, як дақиқа.", ["Okay.", "One minute, please."]),
            t("Does it work now?", "Ҳоло кор мекунад?", "Бигӯ: ҳа, ҳоло кор мекунад", "Yes, it works now.",
              "Ҳа, ҳоло кор мекунад.", ["Yes, thank you!", "It works now. Thanks!"]),
        ]),
        ("Музди ҳафта", [
            s("How much this week?", "Ин ҳафта чанд?", None),
            s("My rating is good.", "Баҳои ман хуб аст.", None),
            s("Is my rating good?", "Баҳои ман хуб аст?", None),
            s("Can I see it?", "Дида метавонам?", None),
            s("Pay on Friday?", "Музд ҷумъа?", None),
            s("Thank you very much.", "Ташаккури зиёд.", None),
        ]),
        ("Баҳои хуб", [
            t("Here is your pay for this week.", "Ана музди ин ҳафтаатон.", "Бипурс: чанд?", "How much?",
              "Чанд?", ["How much this week?", "How much is it?"]),
            t("Six hundred dollars.", "Шашсад доллар.", "Бигӯ: олӣ! Баҳои ман хуб аст?",
              "Great! Is my rating good?", "Олӣ! Баҳои ман хуб аст?", ["Great! My rating?", "Thanks! And my rating?"]),
            t("Yes, five stars. Good job!", "Ҳа, панҷ ситора. Офарин!", "Бигӯ: ташаккур, сардор",
              "Thank you very much.", "Ташаккури зиёд.", ["Thanks, boss!", "Thank you!"]),
        ]),
        ("Миссия: ҳафтаи нав", [
            t("Hi! Can you work next week?", "Салом! Ҳафтаи оянда кор карда метавонед?",
              "Бигӯ: ҳа. Ман соатҳои бештар мехоҳам", "Yes. I want more hours.", "Ҳа. Ман соатҳои бештар мехоҳам.",
              ["Yes, more hours, please.", "Yes, I can."]),
            t("Okay. Night shift, Monday to Saturday.", "Хуб. Навбати шаб, аз душанбе то шанбе.",
              "Бипурс: рӯзи истироҳатам якшанбе?", "Is Sunday my day off?", "Рӯзи истироҳатам якшанбе?",
              ["My day off is Sunday?", "Sunday off?"]),
            t("Yes. Any questions?", "Ҳа. Саволе ҳаст?", "Бипурс: музд ҷумъа?", "Pay on Friday?",
              "Рӯзи музд кай?", ["When do I get paid?", "Payday is when?"]),
            t("Every Friday.", "Ҳар ҷумъа.", "Бигӯ: олӣ, ташаккур", "Great, thank you!", "Олӣ, ташаккур!",
              ["Great!", "Okay, thanks."]),
        ]),
    ]))

if MISSING:
    raise SystemExit('⛔ транскрипсия нест: ' + ', '.join(sorted(MISSING)))
print(' '.join(made))
