"""АНГЛИСӢ → тоҷикӣ, «Гуфтор» A1 — нишаи «Ошхона ва савдо» (`service`), 01.10.2026.

14 вазъият аз нигоҳи КОРГАР (тарабхона, қаҳвахона, мағоза): рӯзи аввал дар
ошхона, пешвози меҳмон, қабули фармоиш, овардани хӯрок, ҳисоб, шикояти меҳмон,
касса, мол дар рафҳо, ёрӣ ба харидор, фармоиш бо телефон, тозакунӣ ва бастан,
хӯрок ва аллергия, рӯзи серкор, ҷадвали кор.

Роҳи `service` = 5 вазъияти умумӣ (1 салом, 6 духтур, 10 бозор, 14 иҷора,
16 ҳуҷҷат) + «Кор ёфтан» (2, умумӣ барои build/service/drive/life) + ин 14 →
20 вазъият. `order`-ҳо ҳамон ҷойҳои холии роҳи сохтмонанд: 3–5, 7–9, 11–13,
15, 17–20.

Ҳамон қоидаҳо (`_en_packs_lib.py`): транскрипсия ҳатмӣ, зина ≤2/≤2/≤4/≤8 калима.
Аз ҷузвдони backend: PYTHONPATH=prisma python3 prisma/_en-service-a1-packs.py
"""
from _en_packs_lib import *  # noqa: F401,F403

EXTRA.update({
    # ошхона
    'kitchen': 'кичэн', 'chef': 'шеф', 'knife': 'найф', 'plate': 'плейт', 'plates': 'плейтс',
    'wash': 'вош', 'cut': 'кат', 'onions': 'анйэнз', 'oil': 'ойл', 'pot': 'пот', 'clean': 'клин',
    'new': 'ню', 'ready': 'редӣ', 'trash': 'трэш', 'washed': 'вошт', 'rest': 'рест',
    'away': 'эвей', 'right': 'райт',
    # меҳмон
    'table': 'тейбэл', 'guest': 'гест', 'menu': 'меню', 'inside': 'инсайд', 'outside': 'аутсайд',
    'welcome': 'велкам', 'evening': 'ивнинг', 'people': 'пипэл', 'moment': 'моумэнт',
    'restaurant': 'рестрон', 'reservation': 'резэрвейшэн', 'follow': 'фолоу', 'waiter': 'вейтэр',
    'anywhere': 'енӣвэр', 'kids': 'кидз', 'enjoy': 'инҷой', 'meal': 'мил', 'waiting': 'вейтинг',
    'full': 'фул', 'sit': 'сит', 'our': 'ауэр', 'way': 'вей', 'window': 'виндоу',
    # фармоиш
    'drink': 'дринк', 'soup': 'суп', 'salad': 'сэлэд', 'dessert': 'дизёрт', 'order': 'ордэр',
    'chicken': 'чикин', 'green': 'грин', 'just': 'ҷаст', 'ice': 'айс', 'would': 'вуд',
    'something': 'самҫинг', 'repeat': 'рипит', 'pizzas': 'питсэз', 'pizza': 'питсэ', 'cola': 'коулэ',
    'fish': 'фиш', 'fresh': 'фреш', 'popular': 'попюлэр', 'spicy': 'спайсӣ', 'cake': 'кейк',
    'coming': 'каминг', 'soon': 'сун', 'let': 'лет', 'anything': 'енӣҫинг', 'else': 'елс',
    'all': 'ол', "that's": 'ҙэтс', 'want': 'вонт',
    # овардан
    'fork': 'форк', 'spoon': 'спун', 'napkin': 'нэпкин', 'glass': 'глэс', 'bread': 'бред',
    'careful': 'кеэрфул', 'hot': 'ҳот', 'who': 'ҳу', 'finished': 'финишт', 'was': 'воз',
    'bring': 'бринг', 'coffee': 'кофӣ', 'tea': 'тӣ', 'back': 'бэк', "i'll": 'айл', 'take': 'тейк',
    # ҳисоб
    'bill': 'бил', 'total': 'тоутэл', 'cash': 'кэш', 'card': 'кард', 'pay': 'пей', 'tip': 'тип',
    'thirty': 'ҫёртӣ', 'separate': 'сепэрэт', 'together': 'тугеҙэр', 'front': 'франт',
    'change': 'чейнҷ', 'tap': 'тэп', 'service': 'сёрвис', 'included': 'инклудид', 'receipt': 'рисит',
    'night': 'найт', 'like': 'лайк', 'did': 'дид', 'come': 'кам', 'again': 'эген',
    # шикоят
    'cold': 'коулд', 'wrong': 'ронг', 'manager': 'мэниҷэр', 'mistake': 'мистейк', 'charge': 'чарҷ',
    'free': 'фрӣ', 'almost': 'олмоуст', 'better': 'бетэр', 'call': 'кол', 'understand': 'андэрстэнд',
    "we'll": 'вил', 'fix': 'фикс', 'telling': 'телинг', 'very': 'верӣ', 'ask': 'аск',
    # касса
    'cashier': 'кэшир', 'price': 'прайс', 'coupon': 'купон', 'next': 'некст', 'paper': 'пейпэр',
    'sale': 'сейл', 'need': 'нид', 'insert': 'инсёрт', 'sign': 'сайн', 'machine': 'мэшин',
    "here's": 'ҳирз', 'try': 'трай', 'fifteen': 'фифтин', 'twenty': 'твентӣ', 'ten': 'тен',
    'register': 'реҷистэр',
    # рафҳо
    'shelf': 'шелф', 'box': 'бокс', 'boxes': 'боксиз', 'price tag': 'прайс тэг', 'tags': 'тэгз',
    'aisle': 'айл', 'room': 'рум', 'empty': 'емптӣ', 'top': 'топ', 'bottom': 'ботэм', 'heavy': 'ҳевӣ',
    'dates': 'дейтс', 'check': 'чек', 'milk': 'милк', 'throw': 'ҫроу', 'truck': 'трак', "there's": 'ҙэрз',
    'done': 'дан', 'tag': 'тэг', 'price': 'прайс',
    # харидор
    'size': 'сайз', 'color': 'калэр', 'small': 'смол', 'medium': 'мидиэм', 'large': 'лардж',
    'fitting': 'фитинг', 'looking': 'лукинг', 'blue': 'блу', 'cheaper': 'чипэр', 'sold': 'соулд',
    'comes': 'камз', 'monday': 'мандей', 'over': 'оувэр', 'there': 'ҙэр', 'it': 'ит',
    # телефон
    'pickup': 'пикап', 'delivery': 'диливэрӣ', 'address': 'эдрес', 'number': 'намбэр',
    'house': 'ҳаус', 'spell': 'спел', 'say': 'сей', 'closed': 'клоузд', 'open': 'оупэн',
    'minutes': 'минитс', 'hello': 'ҳелоу',
    # тозакунӣ
    'mop': 'моп', 'broom': 'брум', 'floor': 'флор', 'wipe': 'вайп', 'lock': 'лок', 'wet': 'вет',
    'bags': 'бэгз', 'up': 'ап', 'tables': 'тейбэлз', 'locked': 'локт', 'lights': 'лайтс', 'off': 'оф',
    'everything': 'еврӣҫинг', 'going': 'гоуинг', 'home': 'ҳоум', 'tomorrow': 'туморроу', 'out': 'аут',
    # аллергия
    'nuts': 'натс', 'pork': 'порк', 'beef': 'биф', 'halal': 'ҳэлэл', 'vegetarian': 'веҷэтэриэн',
    'allergy': 'элэрҷӣ', 'has': 'ҳэз', 'food': 'фуд', 'vegetable': 'веҷтэбэл', 'made': 'мейд',
    'rice': 'райс', 'sugar': 'шугэр', 'meat': 'мит', 'only': 'оунлӣ', 'with': 'виҙ', 'sure': 'шуэр',
    'said': 'сед', 'so': 'соу', 'asked': 'аскт',
    # серкор
    'busy': 'бизӣ', 'line': 'лайн', 'coworker': 'коувёркэр', 'quick': 'квик', 'customer': 'кастэмэр',
    'patient': 'пейшэнт', 'correct': 'кэрект', "you're": 'юр', "we're": 'вир', 'day': 'дей',
    'help': 'ҳелп', 'more': 'мор',
    'bills': 'билз', 'black': 'блэк', 'close': 'клоуз', "doesn't": 'дазнт', 'minute': 'минит',
    # ҷадвал
    'schedule': 'скеҷул', 'swap': 'своп', 'shifts': 'шифтс', 'shift': 'шифт', 'morning': 'морнинг',
    "o'clock": 'эклок', 'week': 'вик', 'sick': 'сик', 'friday': 'фрайдей', 'sunday': 'сандей',
    'saturday': 'сэтэрдей', 'late': 'лейт', 'worked': 'вёркт', 'forty': 'фортӣ', 'hours': 'ауэрз',
    'payday': 'пейдей', 'boss': 'бос', 'family': 'фэмилӣ', 'him': 'ҳим', 'maybe': 'мейбӣ',
    'think': 'ҫинк', 'time': 'тайм', 'start': 'старт', 'days': 'дейз', 'paid': 'пейд', 'get': 'гет',
})

made = []
SV = ["service"]

# ═════════════════════ 3. Рӯзи аввал дар ошхона ═════════════════════
made.append(pack("kitchen_en_tg", "First day in the kitchen", "Рӯзи аввал дар ошхона", "👨‍🍳", 3, SV,
    "Шумо дар ошхонаи тарабхона кор сар мекунед. Ошпаз кӯтоҳ фармон медиҳад: шӯед, буред, "
    "биёред. Шумо мефаҳмед, мепурсед ва мегӯед, ки кор тайёр аст.",
    [
        ("Ошхона", [
            w("Kitchen", "ошхона", None),
            w("Chef", "ошпаз", "Ба сардори ошхона «chef» мегӯянд."),
            w("Knife", "корд", None),
            w("Plate", "табақ", None),
            w("Wash", "шустан", None),
            w("Cut", "буридан", None),
        ]),
        ("Ошпаз", [
            t("Hi! You're the new guy?", "Салом! Шумо навед?", "Бигӯ: ҳа, ман навам", "Yes, I'm new.",
              "Ҳа, ман навам.", ["Yes.", "Yes, I'm new here."]),
            t("Okay. Wash these plates first.", "Хуб. Аввал ин табақҳоро шӯед.", "Бигӯ: хуб", "Okay.", "Хуб.",
              ["Okay, sure.", "Sure."]),
            t("Then cut the onions.", "Баъд пиёзро буред.", "Бигӯ: фаҳмидам", "Got it.", "Фаҳмидам.",
              ["Okay.", "Okay, got it."]),
        ]),
        ("Табақ ва корд", [
            s("Wash plates", "Табақ шӯед", None),
            s("Cut onions", "Пиёз буред", None),
            s("Clean knife", "Корди тоза", None),
            s("Hot oil", "Равғани гарм", None),
            s("Big pot", "Деги калон", None),
            s("Right away", "Ҳозир", "Яъне «ҳамин ҳозир мекунам»."),
        ]),
        ("Пиёз", [
            t("Cut the onions, please.", "Пиёзро буред, лутфан.", "Бипурс: чандто?", "How many?", "Чандто?",
              ["How many onions?", "How many, chef?"]),
            t("Ten onions. Small pieces.", "Даҳ пиёз. Майда.", "Бигӯ: хуб, ҳозир", "Okay, right away.",
              "Хуб, ҳозир.", ["Right away.", "Okay."]),
            t("Be careful. The knife is sharp.", "Эҳтиёт шавед. Корд тез аст.", "Бигӯ: хуб, ташаккур",
              "Okay, thank you.", "Хуб, ташаккур.", ["Thanks.", "Okay, I'll be careful."]),
        ]),
        ("Баъд чӣ?", [
            s("Where are the plates?", "Табақҳо куҷоянд?", None),
            s("Is this okay?", "Ҳамин хел хуб?", None),
            s("The onions are ready.", "Пиёз тайёр аст.", None),
            s("What's next, chef?", "Баъд чӣ, ошпаз?", None),
            s("I need a knife.", "Ба ман корд лозим.", None),
            s("Where does it go?", "Инро куҷо гузорам?", None),
        ]),
        ("Тайёр", [
            t("Are the onions ready?", "Пиёз тайёр аст?", "Бигӯ: ҳа, пиёз тайёр аст", "Yes, the onions are ready.",
              "Ҳа, пиёз тайёр аст.", ["Yes, ready.", "Yes, they're ready."]),
            t("Good. Put them in the big pot.", "Хуб. Ба деги калон андозед.", "Бигӯ: хуб. Баъд чӣ?",
              "Okay. What's next?", "Хуб. Баъд чӣ?", ["What's next, chef?", "Okay. Next?"]),
            t("Now wash the knives.", "Акнун кордҳоро шӯед.", "Бигӯ: хуб, ҳозир", "Okay, right away.",
              "Хуб, ҳозир.", ["Right away.", "Sure."]),
        ]),
        ("Тамом кардам", [
            s("I washed the plates.", "Ман табақҳоро шустам.", None),
            s("I'm done.", "Ман тамом кардам.", None),
            s("Can I rest?", "Дам гирам?", None),
            s("It's very hot here.", "Ин ҷо хеле гарм аст.", None),
            s("Where is the trash?", "Партовдон куҷост?", None),
            s("I don't understand.", "Ман намефаҳмам.", None),
        ]),
        ("Партов", [
            t("Finished with the plates?", "Табақҳо тамом шуд?", "Бигӯ: ҳа, тамом кардам", "Yes, I'm done.",
              "Ҳа, тамом кардам.", ["Yes, done.", "Yes, all done."]),
            t("Great. Take out the trash.", "Олӣ. Партовро бароред.", "Бипурс: партовдон куҷост?",
              "Where is the trash?", "Партовдон куҷост?", ["Where's the trash?", "The trash? Where?"]),
            t("Next to the door. Then rest ten minutes.", "Назди дар. Баъд даҳ дақиқа дам гиред.",
              "Ташаккур гӯй", "Thank you, chef.", "Ташаккур, ошпаз.", ["Thanks!", "Thank you."]),
        ]),
        ("Миссия: ошхона", [
            t("Hi! You're new, right?", "Салом! Шумо навед, ҳа?", "Бигӯ: ҳа, ман навам", "Yes, I'm new.",
              "Ҳа, ман навам.", ["Yes.", "Yes, I'm new here."]),
            t("Wash the plates, then cut ten onions.", "Табақҳоро шӯед, баъд даҳ пиёз буред.",
              "Бигӯ: фаҳмидам. Корд куҷост?", "Got it. Where is the knife?", "Фаҳмидам. Корд куҷост?",
              ["Okay. The knife?", "Where is the knife?"]),
            t("Here. Be careful, it's sharp.", "Ана. Эҳтиёт шавед, тез аст.", "Бигӯ: хуб, ташаккур",
              "Okay, thank you.", "Хуб, ташаккур.", ["Thanks.", "Okay, I'll be careful."]),
            t("Are the onions ready?", "Пиёз тайёр аст?", "Бигӯ: ҳа. Баъд чӣ?", "Yes. What's next?",
              "Ҳа. Баъд чӣ?", ["Yes, ready. Next?", "Yes. What's next, chef?"]),
        ]),
    ]))

# ═════════════════════ 4. Пешвоз гирифтани меҳмон ═════════════════════
made.append(pack("host_en_tg", "Greeting guests", "Пешвоз гирифтани меҳмон", "🙋", 4, SV,
    "Шумо дар дари тарабхона меҳмононро пешвоз мегиред: салом медиҳед, мепурсед чанд "
    "нафаранд, ҷой банд кардаанд ё не, ба миз мебаред ва менюро медиҳед.",
    [
        ("Меҳмон", [
            w("Table", "миз", None),
            w("Guest", "меҳмон", None),
            w("Menu", "меню", None),
            w("Inside", "дарун", None),
            w("Outside", "берун", None),
            w("Welcome", "хуш омадед", None),
        ]),
        ("Чанд нафар?", [
            t("Hi! A table, please.", "Салом! Миз, лутфан.", "Бипурс: барои чанд нафар?", "For how many?",
              "Барои чанд нафар?", ["How many people?", "How many?"]),
            t("Two people.", "Ду нафар.", "Бигӯ: хуш омадед. Аз ин ҷо, лутфан", "Welcome. This way, please.",
              "Хуш омадед. Аз ин ҷо, лутфан.", ["This way, please.", "Welcome! Come in."]),
            t("Thank you.", "Ташаккур.", "Бигӯ: ана меню", "Here is the menu.", "Ана меню.",
              ["Your menu.", "Here's the menu."]),
        ]),
        ("Аз ин ҷо", [
            s("Good evening", "Шоми хуш", None),
            s("Two people", "Ду нафар", None),
            s("This way", "Аз ин ҷо", None),
            s("Window table", "Мизи назди тиреза", None),
            s("One moment", "Як лаҳза", None),
            s("Your menu", "Менюи шумо", None),
        ]),
        ("Назди тиреза", [
            t("Good evening! Table for four?", "Шоми хуш! Мизи чор нафара?", "Бигӯ: як лаҳза, лутфан",
              "One moment, please.", "Як лаҳза, лутфан.", ["Just a moment.", "One moment."]),
            t("Can we sit by the window?", "Назди тиреза шинем?", "Бигӯ: ҳа, албатта", "Yes, of course.",
              "Ҳа, албатта.", ["Sure.", "Yes, this way."]),
            t("Great. Thank you!", "Олӣ. Ташаккур!", "Бигӯ: менюи шумо", "Your menu.", "Менюи шумо.",
              ["Here's the menu.", "Here is your menu."]),
        ]),
        ("Хуш омадед", [
            s("Welcome to our restaurant!", "Ба тарабхонаи мо хуш омадед!", None),
            s("A reservation?", "Ҷой банд кардаед?", "Reservation — ҷои пешакӣ бандшуда."),
            s("Please follow me.", "Лутфан, аз пайи ман биёед.", None),
            s("Please wait here.", "Лутфан, ин ҷо интизор шавед.", None),
            s("Sit anywhere.", "Дилхоҳ ҷо шинед.", None),
            s("Your waiter is coming.", "Пешхизмат ҳозир меояд.", None),
        ]),
        ("Ҷой банд аст?", [
            t("Hello! We are five.", "Салом! Мо панҷ нафарем.", "Бипурс: ҷой банд кардаед?", "A reservation?",
              "Ҷой банд кардаед?", ["Do you have a reservation?", "Reservation?"]),
            t("No, sorry.", "Не, бубахшед.", "Бигӯ: лутфан, ин ҷо интизор шавед", "Please wait here.",
              "Лутфан, ин ҷо интизор шавед.", ["Wait here, please.", "One moment, please."]),
            t("How long?", "Чанд вақт?", "Бигӯ: панҷ дақиқа", "Five minutes.", "Панҷ дақиқа.",
              ["About five minutes.", "Five minutes, please."]),
        ]),
        ("Миз тайёр", [
            s("Inside or outside?", "Дарун ё берун?", None),
            s("It's full now.", "Ҳозир пур аст.", None),
            s("A table is ready.", "Миз тайёр шуд.", None),
            s("Kids menu?", "Менюи кӯдакона?", None),
            s("Enjoy your meal!", "Иштиҳои соф!", None),
            s("Thank you for waiting.", "Ташаккур барои интизорӣ.", None),
        ]),
        ("Дарун ё берун?", [
            t("Is our table ready?", "Мизи мо тайёр аст?", "Бигӯ: ҳа, миз тайёр шуд", "Yes, a table is ready.",
              "Ҳа, миз тайёр шуд.", ["Yes, it's ready.", "Yes. This way, please."]),
            t("Great!", "Олӣ!", "Бипурс: дарун ё берун?", "Inside or outside?", "Дарун ё берун?",
              ["Inside or outside, please?", "Outside or inside?"]),
            t("Inside, please. It's cold.", "Дарун, лутфан. Хунук аст.", "Бигӯ: ташаккур барои интизорӣ",
              "Thank you for waiting.", "Ташаккур барои интизорӣ.", ["Thanks for waiting.", "Thank you. This way."]),
        ]),
        ("Миссия: меҳмонон", [
            t("Hi! Do you have a table?", "Салом! Миз доред?", "Бипурс: барои чанд нафар?", "For how many?",
              "Барои чанд нафар?", ["How many people?", "How many?"]),
            t("Three people.", "Се нафар.", "Бипурс: ҷой банд кардаед?", "A reservation?", "Ҷой банд кардаед?",
              ["Do you have a reservation?", "Reservation?"]),
            t("No. Is that a problem?", "Не. Мушкил аст?", "Бигӯ: не. Аз ин ҷо, лутфан", "No. This way, please.",
              "Не. Аз ин ҷо, лутфан.", ["No problem. This way.", "No. Follow me, please."]),
            t("Thank you! Nice place.", "Ташаккур! Ҷои хуб.", "Бигӯ: ана меню", "Here is the menu.", "Ана меню.",
              ["Your menu.", "Here's the menu."]),
        ]),
    ]))

# ═════════════════════ 5. Қабули фармоиш ═════════════════════
made.append(pack("take_order_en_tg", "Taking an order", "Қабули фармоиш", "📝", 5, SV,
    "Шумо пешхизмат ҳастед: мепурсед, ки меҳмон чӣ мехоҳад, хӯрок ва нӯшокиро менависед, "
    "фармоишро такрор мекунед ва мепурсед, ки боз чизе лозим аст ё не.",
    [
        ("Хӯрок ва нӯшокӣ", [
            w("Drink", "нӯшокӣ", None),
            w("Water", "об", None),
            w("Soup", "шӯрбо", None),
            w("Salad", "салат", None),
            w("Dessert", "ширинӣ", None),
            w("Order", "фармоиш", None),
        ]),
        ("Чӣ мехоҳед?", [
            t("Hi! We're ready.", "Салом! Мо тайёрем.", "Бипурс: чӣ мехоҳед?", "What would you like?",
              "Чӣ мехоҳед?", ["What do you want?", "Ready to order?"]),
            t("The chicken soup, please.", "Шӯрбои мурғ, лутфан.", "Бигӯ: хуб. Ва нӯшокӣ?", "Okay. And to drink?",
              "Хуб. Ва нӯшокӣ?", ["Any drinks?", "And a drink?"]),
            t("Just water.", "Танҳо об.", "Бигӯ: хуб, як дақиқа", "Okay, one minute.", "Хуб, як дақиқа.",
              ["Sure.", "Okay."]),
        ]),
        ("Шӯрбои мурғ", [
            s("Chicken soup", "Шӯрбои мурғ", None),
            s("Green salad", "Салати сабз", None),
            s("Just water", "Танҳо об", None),
            s("Anything else?", "Боз чизе?", None),
            s("No ice", "Бе ях", None),
            s("Coming soon", "Ҳозир меояд", None),
        ]),
        ("Боз чизе?", [
            t("And a green salad.", "Ва салати сабз.", "Бипурс: боз чизе?", "Anything else?", "Боз чизе?",
              ["Something else?", "Is that all?"]),
            t("No, that's all.", "Не, ҳамин.", "Бигӯ: хуб. Ҳозир меояд", "Okay. Coming soon.", "Хуб. Ҳозир меояд.",
              ["Okay.", "Okay, thank you."]),
            t("Water with no ice, please.", "Об бе ях, лутфан.", "Бигӯ: бе ях, хуб", "No ice. Okay.",
              "Бе ях. Хуб.", ["Okay, no ice.", "Sure."]),
        ]),
        ("Такрор мекунам", [
            s("Are you ready?", "Тайёред?", None),
            s("What would you like?", "Чӣ мехоҳед?", None),
            s("Something to drink?", "Ягон нӯшокӣ?", None),
            s("Is that all?", "Ҳамин?", None),
            s("The soup is good.", "Шӯрбо хуб аст.", None),
            s("Let me repeat.", "Такрор мекунам.", None),
        ]),
        ("Ду пицца", [
            t("Two pizzas and a cola.", "Ду пицца ва як кола.", "Бигӯ: такрор мекунам: ду пицца, як кола",
              "Let me repeat. Two pizzas, one cola.", "Такрор мекунам. Ду пицца, як кола.",
              ["Two pizzas, one cola?", "Two pizzas and a cola. Right?"]),
            t("Yes, that's right.", "Ҳа, дуруст.", "Бипурс: ҳамин?", "Is that all?", "Ҳамин?",
              ["Anything else?", "That's all?"]),
            t("Yes, thank you.", "Ҳа, ташаккур.", "Бигӯ: ҳозир меояд", "Coming soon.", "Ҳозир меояд.",
              ["It's coming soon.", "Okay, thank you."]),
        ]),
        ("Чӣ тавсия медиҳед?", [
            s("The fish is fresh.", "Моҳӣ тоза аст.", None),
            s("This is very popular.", "Инро бисёр мегиранд.", None),
            s("It's spicy.", "Тунд аст.", None),
            s("Dessert for you?", "Ширинӣ мехоҳед?", None),
            s("We have cake.", "Мо торт дорем.", None),
            s("Sorry, no more fish.", "Бубахшед, моҳӣ тамом шуд.", None),
        ]),
        ("Тунд аст?", [
            t("What do you recommend?", "Чӣ тавсия медиҳед?", "Бигӯ: инро бисёр мегиранд", "This is very popular.",
              "Инро бисёр мегиранд.", ["This one is popular.", "The fish is very good."]),
            t("Is it spicy?", "Тунд аст?", "Бигӯ: каме тунд", "A little spicy.", "Каме тунд.",
              ["Yes, a little.", "It's a little spicy."]),
            t("Okay, I'll take it.", "Хуб, мегирам.", "Бипурс: ширинӣ ҳам?", "Dessert too?", "Ширинӣ ҳам?",
              ["Dessert for you?", "And dessert?"]),
        ]),
        ("Миссия: фармоиш", [
            t("Hi! We're ready to order.", "Салом! Фармоиш медиҳем.", "Бигӯ: хуб. Чӣ мехоҳед?",
              "Okay. What would you like?", "Хуб. Чӣ мехоҳед?", ["What would you like?", "Sure. What do you want?"]),
            t("One chicken soup and a salad.", "Як шӯрбои мурғ ва салат.", "Бипурс: ва нӯшокӣ?", "And to drink?",
              "Ва нӯшокӣ?", ["Something to drink?", "Any drinks?"]),
            t("Water, no ice.", "Об, бе ях.", "Бигӯ: такрор мекунам: шӯрбо, салат, об",
              "Let me repeat. Soup, salad, water.", "Такрор мекунам. Шӯрбо, салат, об.",
              ["Soup, salad and water?", "Soup, salad, water. Right?"]),
            t("Yes, that's right.", "Ҳа, дуруст.", "Бигӯ: хуб. Ҳозир меояд", "Okay. Coming soon.",
              "Хуб. Ҳозир меояд.", ["Coming soon.", "Thank you!"]),
        ]),
    ]))

# ═════════════════════ 7. Овардани хӯрок ═════════════════════
made.append(pack("serving_en_tg", "Serving food", "Овардани хӯрок", "🍽️", 7, SV,
    "Шумо хӯрокро ба миз меоред: мегӯед, ки чӣ овардед, огоҳ мекунед, ки табақ гарм аст, "
    "мепурсед, ки ҳама хуб аст ва дар охир табақҳоро мебардоред.",
    [
        ("Дар сари миз", [
            w("Fork", "чангча", None),
            w("Spoon", "қошуқ", None),
            w("Napkin", "дастмолча", None),
            w("Glass", "стакан", None),
            w("Bread", "нон", None),
            w("Hot", "гарм", None),
        ]),
        ("Хӯроки шумо", [
            t("Is this our food?", "Ин хӯроки мост?", "Бигӯ: ҳа, шӯрбои мурғ", "Yes, the chicken soup.",
              "Ҳа, шӯрбои мурғ.", ["Yes. Chicken soup.", "Yes, here you go."]),
            t("It smells good!", "Бӯи хуб дорад!", "Бигӯ: эҳтиёт шавед, табақ гарм аст", "Careful, the plate is hot.",
              "Эҳтиёт, табақ гарм аст.", ["Careful, it's hot.", "The plate is hot."]),
            t("Thanks. Can I have a spoon?", "Ташаккур. Қошуқ медиҳед?", "Бигӯ: албатта. Марҳамат",
              "Of course. Here you go.", "Албатта. Марҳамат.", ["Sure, here.", "Here you go."]),
        ]),
        ("Боз нон?", [
            s("Very hot", "Хеле гарм", None),
            s("More bread?", "Боз нон?", None),
            s("Clean glass", "Стакани тоза", None),
            s("Your soup", "Шӯрбои шумо", None),
            s("Right here", "Ҳамин ҷо", None),
            s("All good?", "Ҳама хуб?", None),
        ]),
        ("Стакани тоза", [
            t("Can we have more bread?", "Боз нон медиҳед?", "Бигӯ: албатта", "Of course.", "Албатта.",
              ["Sure.", "Yes, one moment."]),
            t("And a clean glass, please.", "Ва стакани тоза, лутфан.", "Бигӯ: бубахшед. Ҳозир",
              "Sorry. Right away.", "Бубахшед. Ҳозир.", ["Right away.", "Sorry, one moment."]),
            t("Thank you!", "Ташаккур!", "Бигӯ: иштиҳои соф", "Enjoy your meal!", "Иштиҳои соф!",
              ["Enjoy!", "Have a nice meal!"]),
        ]),
        ("Ана хӯрок", [
            s("Here is your soup.", "Ана шӯрбоятон.", None),
            s("Careful, it's hot.", "Эҳтиёт, гарм аст.", None),
            s("Is everything okay?", "Ҳама хуб?", None),
            s("More water?", "Боз об?", None),
            s("Who has the fish?", "Моҳӣ барои кист?", None),
            s("Enjoy your meal!", "Иштиҳои соф!", None),
        ]),
        ("Моҳӣ барои кист?", [
            t("Oh, the food is here!", "О, хӯрок омад!", "Бипурс: моҳӣ барои кист?", "Who has the fish?",
              "Моҳӣ барои кист?", ["The fish is for who?", "Who ordered the fish?"]),
            t("The fish is for me.", "Моҳӣ барои ман.", "Бигӯ: марҳамат. Эҳтиёт, гарм аст",
              "Here you go. Careful, it's hot.", "Марҳамат. Эҳтиёт, гарм аст.", ["Careful, it's hot.", "Here. It's hot."]),
            t("Thank you.", "Ташаккур.", "Бигӯ: иштиҳои соф", "Enjoy your meal!", "Иштиҳои соф!",
              ["Enjoy!", "Have a nice meal!"]),
        ]),
        ("Табақҳоро мебардорам", [
            s("Can I take this?", "Инро бардорам?", None),
            s("Are you finished?", "Тамом кардед?", None),
            s("Was it good?", "Хуб буд?", None),
            s("Coffee or tea?", "Қаҳва ё чой?", None),
            s("I'll bring dessert.", "Ширинӣ меорам.", None),
            s("I'll be right back.", "Ҳозир бармегардам.", None),
        ]),
        ("Тамом кардед?", [
            t("That was delicious!", "Хеле болаззат буд!", "Бипурс: тамом кардед?", "Are you finished?",
              "Тамом кардед?", ["Finished?", "All done?"]),
            t("Yes, thanks.", "Ҳа, ташаккур.", "Бипурс: инро бардорам?", "Can I take this?", "Инро бардорам?",
              ["Can I take the plates?", "May I take this?"]),
            t("Sure. And two coffees, please.", "Албатта. Ва ду қаҳва, лутфан.", "Бигӯ: хуб. Ҳозир бармегардам",
              "Okay. I'll be right back.", "Хуб. Ҳозир бармегардам.", ["Right away.", "Sure. Be right back."]),
        ]),
        ("Миссия: сари миз", [
            t("Is this our food?", "Ин хӯроки мост?", "Бигӯ: ҳа. Шӯрбо ва моҳӣ", "Yes. Soup and fish.",
              "Ҳа. Шӯрбо ва моҳӣ.", ["Yes, here you go.", "Yes. Chicken soup and fish."]),
            t("Great. The fish is for me.", "Олӣ. Моҳӣ барои ман.", "Бигӯ: эҳтиёт, гарм аст", "Careful, it's hot.",
              "Эҳтиёт, гарм аст.", ["Careful. The plate is hot.", "It's hot, careful."]),
            t("Thanks. Can we have more bread?", "Ташаккур. Боз нон медиҳед?", "Бигӯ: албатта. Ҳозир",
              "Of course. Right away.", "Албатта. Ҳозир.", ["Sure.", "Yes, one moment."]),
            t("Thank you so much!", "Ташаккури зиёд!", "Бигӯ: иштиҳои соф", "Enjoy your meal!", "Иштиҳои соф!",
              ["Enjoy!", "Have a nice meal!"]),
        ]),
    ]))

# ═════════════════════ 8. Ҳисоб дар тарабхона ═════════════════════
made.append(pack("bill_en_tg", "The bill", "Ҳисоб дар тарабхона", "🧾", 8, SV,
    "Меҳмонон ҳисобро мепурсанд. Шумо ҳисобро меоред, нархро мегӯед, мепурсед якҷоя ё "
    "ҷудо, кортро қабул мекунед ва меҳмононро бо хушрӯӣ гусел мекунед.",
    [
        ("Ҳисоб", [
            w("Bill", "ҳисоб", None),
            w("Total", "ҳамагӣ", None),
            w("Cash", "пули нақд", None),
            w("Card", "корт", None),
            w("Pay", "пардохт кардан", None),
            w("Tip", "чойпулӣ", None),
        ]),
        ("Ҳисоб, лутфан", [
            t("Can we have the bill, please?", "Ҳисобро медиҳед, лутфан?", "Бигӯ: албатта. Як лаҳза",
              "Of course. One moment.", "Албатта. Як лаҳза.", ["Sure, one moment.", "Yes, right away."]),
            t("How much is it?", "Чанд пул аст?", "Бигӯ: сӣ доллар", "Thirty dollars.", "Сӣ доллар.",
              ["It's thirty dollars.", "The total is thirty."]),
            t("Can I pay by card?", "Бо корт пардохт карда метавонам?", "Бигӯ: ҳа, албатта", "Yes, of course.",
              "Ҳа, албатта.", ["Sure.", "Yes."]),
        ]),
        ("Якҷоя ё ҷудо", [
            s("Your bill", "Ҳисоби шумо", None),
            s("Thirty dollars", "Сӣ доллар", None),
            s("By card", "Бо корт", None),
            s("Pay here", "Ин ҷо пардохт кунед", None),
            s("Separate bills", "Ҳисобҳои ҷудо", None),
            s("One moment", "Як лаҳза", None),
        ]),
        ("Ҳисобҳои ҷудо", [
            t("The bill, please.", "Ҳисоб, лутфан.", "Бипурс: якҷоя ё ҷудо?", "Together or separate?",
              "Якҷоя ё ҷудо?", ["One bill?", "Together?"]),
            t("Separate, please.", "Ҷудо, лутфан.", "Бигӯ: хуб, мушкил нест", "Okay, no problem.",
              "Хуб, мушкил нест.", ["No problem.", "Sure."]),
            t("I had the soup.", "Ман шӯрбо хӯрдам.", "Бигӯ: шӯрбо — даҳ доллар", "The soup is ten dollars.",
              "Шӯрбо даҳ доллар.", ["Ten dollars.", "That's ten dollars."]),
        ]),
        ("Кортро расонед", [
            s("Here is your bill.", "Ана ҳисобатон.", None),
            s("Pay at the front.", "Дар пеш пардохт кунед.", None),
            s("Cash or card?", "Нақд ё корт?", None),
            s("Here is your change.", "Ана бақияатон.", None),
            s("Tap your card here.", "Кортро ин ҷо расонед.", None),
            s("Service is included.", "Хизмат дохил аст.", None),
        ]),
        ("Чойпулӣ дохил аст?", [
            t("Is the tip included?", "Чойпулӣ дохил аст?", "Бигӯ: не, дохил нест", "No, it's not included.",
              "Не, дохил нест.", ["No, it's not.", "No."]),
            t("Okay. Here is my card.", "Хуб. Ана корти ман.", "Бигӯ: кортро ин ҷо расонед", "Tap your card here.",
              "Кортро ин ҷо расонед.", ["Tap here, please.", "Please tap here."]),
            t("Done?", "Тайёр?", "Бигӯ: ҳа. Ташаккур!", "Yes. Thank you!", "Ҳа. Ташаккур!",
              ["Yes, thank you.", "All done. Thanks!"]),
        ]),
        ("Боз биёед", [
            s("Thank you very much!", "Ташаккури зиёд!", None),
            s("Please come again!", "Боз биёед!", None),
            s("Have a good night!", "Шаби хуш!", None),
            s("Did you like it?", "Писанд омад?", None),
            s("Here is your receipt.", "Ана чекатон.", None),
            s("See you soon!", "То боздид!", None),
        ]),
        ("Шаби хуш", [
            t("Here, this is for you.", "Ана, ин барои шумо.", "Бигӯ: ташаккури зиёд!", "Thank you very much!",
              "Ташаккури зиёд!", ["Thank you so much!", "Thanks a lot!"]),
            t("The food was great.", "Хӯрок олӣ буд.", "Бигӯ: ташаккур! Боз биёед", "Thank you! Please come again!",
              "Ташаккур! Боз биёед!", ["Please come again!", "Thanks! Come again!"]),
            t("We will. Good night!", "Албатта. Шаб ба хайр!", "Бигӯ: шаби хуш", "Have a good night!", "Шаби хуш!",
              ["Good night!", "Have a nice night!"]),
        ]),
        ("Миссия: ҳисоб", [
            t("The bill, please.", "Ҳисоб, лутфан.", "Бигӯ: ана ҳисобатон", "Here is your bill.", "Ана ҳисобатон.",
              ["Here's your bill.", "Here you go."]),
            t("How much is it?", "Чанд пул аст?", "Бигӯ: сӣ доллар", "Thirty dollars.", "Сӣ доллар.",
              ["It's thirty dollars.", "Thirty."]),
            t("Card, please. Is the tip included?", "Корт, лутфан. Чойпулӣ дохил аст?", "Бигӯ: не, дохил нест",
              "No, it's not included.", "Не, дохил нест.", ["No, it's not.", "No."]),
            t("Okay. Thank you, it was great!", "Хуб. Ташаккур, олӣ буд!", "Бигӯ: ташаккур! Боз биёед",
              "Thank you! Please come again!", "Ташаккур! Боз биёед!", ["Please come again!", "Thanks! Come again!"]),
        ]),
    ]))

# ═════════════════════ 9. Шикояти меҳмон ═════════════════════
made.append(pack("complaint_en_tg", "Unhappy guest", "Шикояти меҳмон", "😟", 9, SV,
    "Меҳмон норозӣ аст: хӯрок хунук аст, фармоиш нодуруст омад ё дер шуд. Шумо бахшиш "
    "мепурсед, мушкилро ислоҳ мекунед ва агар лозим бошад, менеҷерро даъват мекунед.",
    [
        ("Мушкил", [
            w("Cold", "хунук", None),
            w("Wrong", "нодуруст", None),
            w("Late", "дер", None),
            w("Manager", "менеҷер", None),
            w("Sorry", "бубахшед", None),
            w("Change", "иваз кардан", None),
        ]),
        ("Шӯрбо хунук", [
            t("Excuse me, my soup is cold.", "Бубахшед, шӯрбоям хунук аст.", "Бигӯ: бубахшед. Иваз мекунам",
              "I'm sorry. I'll change it.", "Бубахшед. Иваз мекунам.", ["Sorry! I'll change it.", "Sorry, I'll bring a new one."]),
            t("Thank you.", "Ташаккур.", "Бигӯ: як дақиқа, лутфан", "One minute, please.", "Як дақиқа, лутфан.",
              ["One moment.", "Just a minute."]),
            t("This one is hot. Perfect!", "Ин гарм. Олӣ!", "Бигӯ: боз бубахшед", "Sorry again.", "Боз бубахшед.",
              ["Sorry about that.", "Sorry again!"]),
        ]),
        ("Хатои ман", [
            s("Very sorry", "Хеле бубахшед", None),
            s("Wrong order", "Фармоиши нодуруст", None),
            s("My mistake", "Хатои ман", None),
            s("Right away", "Ҳозир", None),
            s("No charge", "Ройгон", "Яъне пул намегирем."),
            s("The manager", "Менеҷер", None),
        ]),
        ("Фармоиши нодуруст", [
            t("This is not my order.", "Ин фармоиши ман нест.", "Бигӯ: хеле бубахшед. Хатои ман",
              "Very sorry. My mistake.", "Хеле бубахшед. Хатои ман.", ["Sorry, my mistake.", "I'm very sorry."]),
            t("I ordered the chicken.", "Ман мурғ фармоиш додам.", "Бигӯ: мурғ. Ҳозир", "Chicken. Right away.",
              "Мурғ. Ҳозир.", ["Right away.", "Okay, the chicken."]),
            t("Okay, thank you.", "Хуб, ташаккур.", "Бигӯ: нӯшокӣ ройгон", "The drink is free.",
              "Нӯшокӣ ройгон.", ["Your drink is free.", "A free drink for you."]),
        ]),
        ("Иваз мекунам", [
            s("I'll change it.", "Иваз мекунам.", None),
            s("I'll ask the kitchen.", "Аз ошхона мепурсам.", None),
            s("It's almost ready.", "Қариб тайёр аст.", None),
            s("Sorry for the wait.", "Барои интизорӣ бубахшед.", None),
            s("Is it better now?", "Ҳоло беҳтар аст?", None),
            s("I'll call the manager.", "Менеҷерро даъват мекунам.", None),
        ]),
        ("Дер шуд", [
            t("We are waiting forty minutes!", "Мо чил дақиқа интизорем!", "Бигӯ: бубахшед. Аз ошхона мепурсам",
              "Sorry. I'll ask the kitchen.", "Бубахшед. Аз ошхона мепурсам.", ["I'm sorry. I'll ask.", "Sorry! I'll check."]),
            t("Please hurry.", "Лутфан, тезтар.", "Бигӯ: қариб тайёр аст", "It's almost ready.", "Қариб тайёр аст.",
              ["Almost ready.", "Two more minutes."]),
            t("Finally! Thank you.", "Ниҳоят! Ташаккур.", "Бигӯ: барои интизорӣ бубахшед", "Sorry for the wait.",
              "Барои интизорӣ бубахшед.", ["Sorry about the wait.", "Sorry it was late."]),
        ]),
        ("Мо ислоҳ мекунем", [
            s("One moment, please.", "Як лаҳза, лутфан.", None),
            s("How can I help?", "Чӣ ёрӣ диҳам?", None),
            s("I understand.", "Ман мефаҳмам.", None),
            s("We'll fix it.", "Мо ислоҳ мекунем.", None),
            s("This is on us.", "Ин аз ҳисоби мо.", "Яъне меҳмон пул намедиҳад."),
            s("Thanks for telling me.", "Ташаккур, ки гуфтед.", None),
        ]),
        ("Менеҷер", [
            t("I want to talk to the manager!", "Мехоҳам бо менеҷер гап занам!", "Бигӯ: як лаҳза, лутфан",
              "One moment, please.", "Як лаҳза, лутфан.", ["Just a moment.", "Okay, one moment."]),
            t("The food is not good.", "Хӯрок хуб нест.", "Бигӯ: мефаҳмам. Мо ислоҳ мекунем",
              "I understand. We'll fix it.", "Мефаҳмам. Мо ислоҳ мекунем.", ["We'll fix it.", "I understand. Sorry."]),
            t("Okay. Thank you.", "Хуб. Ташаккур.", "Бигӯ: ин аз ҳисоби мо", "This is on us.", "Ин аз ҳисоби мо.",
              ["It's free.", "No charge today."]),
        ]),
        ("Миссия: меҳмони норозӣ", [
            t("Excuse me! This is the wrong order.", "Бубахшед! Ин фармоиши нодуруст.",
              "Бигӯ: хеле бубахшед. Хатои ман", "Very sorry. My mistake.", "Хеле бубахшед. Хатои ман.",
              ["Sorry, my mistake.", "I'm very sorry."]),
            t("And it's cold.", "Ва хунук ҳам.", "Бигӯ: иваз мекунам", "I'll change it.", "Иваз мекунам.",
              ["I'll bring a new one.", "I'll change it now."]),
            t("Please be quick. We are in a hurry.", "Лутфан, тез. Мо шитоб дорем.", "Бигӯ: қариб тайёр аст",
              "It's almost ready.", "Қариб тайёр аст.", ["Five minutes.", "Almost ready."]),
            t("Thank you. This one is good.", "Ташаккур. Ин хуб.", "Бигӯ: нӯшокӣ ройгон", "The drink is free.",
              "Нӯшокӣ ройгон.", ["Your drink is free.", "This is on us."]),
        ]),
    ]))

# ═════════════════════ 11. Дар касса ═════════════════════
made.append(pack("cashier_en_tg", "At the cash register", "Дар касса", "💳", 11, SV,
    "Шумо дар мағоза кассир ҳастед: салом медиҳед, мепурсед халта лозим аст ё не, нархро "
    "мегӯед, купон ва тахфифро месанҷед, пул мегиред ва чек медиҳед.",
    [
        ("Касса", [
            w("Cashier", "кассир", None),
            w("Bag", "халта", None),
            w("Price", "нарх", None),
            w("Total", "ҳамагӣ", None),
            w("Coupon", "купон", "Коғаз ё рамз барои тахфиф."),
            w("Receipt", "чек", None),
        ]),
        ("Халта лозим?", [
            t("Hi!", "Салом!", "Бигӯ: салом! Халта лозим?", "Hi! Need a bag?", "Салом! Халта лозим?",
              ["Hello! A bag?", "Hi! Do you need a bag?"]),
            t("Yes, one bag.", "Ҳа, як халта.", "Бигӯ: ҳамагӣ понздаҳ доллар", "Your total is fifteen.",
              "Ҳамагӣ понздаҳ.", ["Fifteen dollars.", "It's fifteen dollars."]),
            t("Here you go.", "Марҳамат.", "Бигӯ: ташаккур. Ана чекатон", "Thank you. Here's your receipt.",
              "Ташаккур. Ана чекатон.", ["Thanks. Your receipt.", "Here is your receipt."]),
        ]),
        ("Навбатӣ", [
            s("Next, please", "Навбатӣ, лутфан", None),
            s("Paper bag", "Халтаи коғазӣ", None),
            s("Fifteen dollars", "Понздаҳ доллар", None),
            s("Your receipt", "Чеки шумо", None),
            s("Card here", "Корт ин ҷо", None),
            s("On sale", "Бо тахфиф", None),
        ]),
        ("Купон", [
            t("I have a coupon.", "Ман купон дорам.", "Бигӯ: хуб. Нишон диҳед, лутфан", "Okay. Show me, please.",
              "Хуб. Нишон диҳед, лутфан.", ["Can I see it?", "Show me, please."]),
            t("Here.", "Ана.", "Бигӯ: бубахшед, ин кӯҳна аст", "Sorry, it's old.", "Бубахшед, ин кӯҳна аст.",
              ["Sorry, this is old.", "Sorry, it doesn't work."]),
            t("Oh, okay. No problem.", "О, хуб. Мушкил нест.", "Бигӯ: даҳ доллар, лутфан", "Ten dollars, please.",
              "Даҳ доллар, лутфан.", ["It's ten dollars.", "Your total is ten."]),
        ]),
        ("Ҳамагӣ бист", [
            s("Next, please!", "Навбатӣ, лутфан!", None),
            s("Need a bag?", "Халта лозим?", None),
            s("Your total is twenty.", "Ҳамагӣ бист.", None),
            s("Insert your card.", "Кортро дароред.", None),
            s("Sign here, please.", "Ин ҷо имзо кунед, лутфан.", None),
            s("This is on sale.", "Ин бо тахфиф аст.", None),
        ]),
        ("Нарх нодуруст", [
            t("This price is wrong.", "Ин нарх нодуруст аст.", "Бигӯ: бубахшед. Месанҷам", "Sorry. I'll check.",
              "Бубахшед. Месанҷам.", ["Let me check.", "Sorry, one moment."]),
            t("It says five dollars.", "Он ҷо панҷ доллар навишта.", "Бигӯ: ҳа, ин бо тахфиф аст",
              "Yes, this is on sale.", "Ҳа, ин бо тахфиф аст.", ["You're right. It's on sale.", "Yes, five dollars."]),
            t("Thank you.", "Ташаккур.", "Бигӯ: ҳамагӣ бист", "Your total is twenty.", "Ҳамагӣ бист.",
              ["Twenty dollars.", "It's twenty, please."]),
        ]),
        ("Дастгоҳ", [
            s("Here's your change.", "Ана бақияатон.", None),
            s("The machine doesn't work.", "Дастгоҳ кор намекунад.", None),
            s("Can you pay cash?", "Нақд дода метавонед?", None),
            s("Try again, please.", "Боз кӯшиш кунед, лутфан.", None),
            s("Your card, please.", "Корти шумо, лутфан.", None),
            s("Have a nice day!", "Рӯзи хуш!", None),
        ]),
        ("Корт кор намекунад", [
            t("My card doesn't work.", "Корти ман кор намекунад.", "Бигӯ: боз кӯшиш кунед, лутфан",
              "Try again, please.", "Боз кӯшиш кунед, лутфан.", ["Please try again.", "One more time, please."]),
            t("No, it doesn't work.", "Не, кор намекунад.", "Бигӯ: дастгоҳ кор намекунад. Нақд дода метавонед?",
              "The machine doesn't work. Can you pay cash?", "Дастгоҳ кор намекунад. Нақд дода метавонед?",
              ["Can you pay cash?", "Sorry. Cash, please?"]),
            t("Sure. Here's twenty.", "Албатта. Ана бист.", "Бигӯ: ана бақияатон. Рӯзи хуш",
              "Here's your change. Have a nice day!", "Ана бақияатон. Рӯзи хуш!",
              ["Here's your change.", "Your change. Have a nice day!"]),
        ]),
        ("Миссия: касса", [
            t("Hi!", "Салом!", "Бигӯ: салом! Халта лозим?", "Hi! Need a bag?", "Салом! Халта лозим?",
              ["Hello! A bag?", "Hi! Do you need a bag?"]),
            t("No, thanks. This is on sale, right?", "Не, ташаккур. Ин бо тахфиф, дуруст?",
              "Бигӯ: ҳа, ин бо тахфиф аст", "Yes, this is on sale.", "Ҳа, ин бо тахфиф аст.",
              ["Yes, it's on sale.", "Yes."]),
            t("Great. How much?", "Олӣ. Чанд?", "Бигӯ: ҳамагӣ бист", "Your total is twenty.", "Ҳамагӣ бист.",
              ["Twenty dollars.", "It's twenty dollars."]),
            t("Here's my card.", "Ана корти ман.", "Бигӯ: ташаккур. Ана чекатон", "Thank you. Here's your receipt.",
              "Ташаккур. Ана чекатон.", ["Your receipt.", "Thanks! Here is your receipt."]),
        ]),
    ]))

# ═════════════════════ 12. Мол дар рафҳо ═════════════════════
made.append(pack("shelves_en_tg", "Stocking shelves", "Мол дар рафҳо", "📦", 12, SV,
    "Шумо дар мағоза мол мечинед: қуттиҳоро мекушоед, молро ба раф мегузоред, санаҳоро "
    "месанҷед ва мепурсед, ки чиро куҷо гузоред.",
    [
        ("Раф", [
            w("Shelf", "раф", None),
            w("Box", "қуттӣ", None),
            w("Aisle", "қатор", "Роҳрави байни рафҳо дар мағоза."),
            w("Empty", "холӣ", None),
            w("Top", "боло", None),
            w("Bottom", "поён", None),
        ]),
        ("Кадом раф?", [
            t("Can you open these boxes?", "Ин қуттиҳоро мекушоед?", "Бигӯ: ҳа, албатта", "Yes, of course.",
              "Ҳа, албатта.", ["Sure.", "Yes."]),
            t("Put the milk on the shelf.", "Ширро ба раф гузоред.", "Бипурс: кадом раф?", "Which shelf?",
              "Кадом раф?", ["Which one?", "Which shelf, please?"]),
            t("The top shelf, in aisle five.", "Рафи боло, дар қатори панҷ.", "Бигӯ: хуб, фаҳмидам",
              "Okay, got it.", "Хуб, фаҳмидам.", ["Got it.", "Okay."]),
        ]),
        ("Рафи боло", [
            s("Top shelf", "Рафи боло", None),
            s("Bottom shelf", "Рафи поён", None),
            s("Aisle five", "Қатори панҷ", None),
            s("Price tags", "Нархномаҳо", None),
            s("Back room", "Анбор", "Ҳуҷраи қафои мағоза, ки мол он ҷост."),
            s("All empty", "Ҳама холӣ", None),
        ]),
        ("Раф холӣ", [
            t("The shelf is empty.", "Раф холӣ аст.", "Бигӯ: дар анбор боз ҳаст", "There's more in the back room.",
              "Дар анбор боз ҳаст.", ["More in the back room.", "I'll bring more."]),
            t("Great. Bring it, please.", "Олӣ. Биёред, лутфан.", "Бигӯ: хуб, ҳозир", "Okay, right away.",
              "Хуб, ҳозир.", ["Right away.", "Sure."]),
            t("And put price tags on.", "Ва нархнома часпонед.", "Бипурс: нарх чанд?", "What's the price?",
              "Нарх чанд?", ["How much is it?", "Which price?"]),
        ]),
        ("Ин куҷо меравад?", [
            s("Where does this go?", "Ин куҷо меравад?", None),
            s("This box is heavy.", "Ин қуттӣ вазнин аст.", None),
            s("The shelf is full.", "Раф пур аст.", None),
            s("I need more tags.", "Нархномаи бештар лозим.", None),
            s("This aisle?", "Ҳамин қатор?", None),
            s("All done here.", "Ин ҷо тамом.", None),
        ]),
        ("Қатори се", [
            t("Hi! How is it going?", "Салом! Корҳо чӣ хел?", "Бигӯ: хуб. Ин куҷо меравад?",
              "Good. Where does this go?", "Хуб. Ин куҷо меравад?", ["Where does this go?", "Fine. Where does it go?"]),
            t("Rice goes in aisle three.", "Биринҷ дар қатори се.", "Бипурс: ҳамин қатор?", "This aisle?",
              "Ҳамин қатор?", ["Aisle three? Here?", "This one?"]),
            t("Yes, bottom shelf.", "Ҳа, рафи поён.", "Бигӯ: хуб. Раф пур аст", "Okay. The shelf is full.",
              "Хуб. Раф пур аст.", ["Sorry, it's full.", "The shelf is full."]),
        ]),
        ("Санаҳо", [
            s("I finished aisle five.", "Қатори панҷро тамом кардам.", None),
            s("Check the dates.", "Санаҳоро санҷед.", None),
            s("This milk is old.", "Ин шир кӯҳна аст.", None),
            s("Throw it away?", "Партоям?", None),
            s("The truck is here.", "Мошини бор омад.", None),
            s("What's next?", "Баъд чӣ?", None),
        ]),
        ("Шири кӯҳна", [
            t("Did you check the dates?", "Санаҳоро санҷидед?", "Бигӯ: ҳа. Ин шир кӯҳна аст",
              "Yes. This milk is old.", "Ҳа. Ин шир кӯҳна аст.", ["Yes, this milk is old.", "Yes. Old milk here."]),
            t("Oh no. Take it off the shelf.", "Вой. Аз раф гиред.", "Бипурс: партоям?", "Throw it away?",
              "Партоям?", ["In the trash?", "Should I throw it away?"]),
            t("Yes, please. Then help with the truck.", "Ҳа, лутфан. Баъд бо мошини бор ёрӣ диҳед.",
              "Бигӯ: хуб, фаҳмидам", "Okay, got it.", "Хуб, фаҳмидам.", ["Okay.", "Sure."]),
        ]),
        ("Миссия: рафҳо", [
            t("Hi! The milk shelf is empty.", "Салом! Рафи шир холӣ аст.", "Бигӯ: дар анбор боз ҳаст",
              "There's more in the back room.", "Дар анбор боз ҳаст.", ["More in the back room.", "I'll bring more."]),
            t("Good. Bring two boxes.", "Хуб. Ду қуттӣ биёред.", "Бигӯ: хуб, ҳозир", "Okay, right away.",
              "Хуб, ҳозир.", ["Right away.", "Sure."]),
            t("Put them on the top shelf, aisle five.", "Ба рафи боло, қатори панҷ гузоред.",
              "Бигӯ: рафи боло, қатори панҷ. Хуб", "Top shelf, aisle five. Okay.", "Рафи боло, қатори панҷ. Хуб.",
              ["Aisle five. Okay.", "Okay, got it."]),
            t("And check the dates!", "Ва санаҳоро санҷед!", "Бигӯ: хуб. Ин шир кӯҳна аст", "Okay. This milk is old.",
              "Хуб. Ин шир кӯҳна аст.", ["This milk is old.", "Okay. One is old."]),
        ]),
    ]))

# ═════════════════════ 13. Ёрӣ ба харидор ═════════════════════
made.append(pack("shop_help_en_tg", "Helping a customer", "Ёрӣ ба харидор", "🛒", 13, SV,
    "Харидор чизе меҷӯяд. Шумо мепурсед, ки чӣ лозим, нишон медиҳед, ки куҷост, андоза ва "
    "рангро мепурсед, ва агар набошад, мегӯед, ки кай меояд.",
    [
        ("Андоза ва ранг", [
            w("Size", "андоза", None),
            w("Color", "ранг", None),
            w("Small", "хурд", None),
            w("Medium", "миёна", None),
            w("Large", "калон", None),
            w("Fitting room", "ҳуҷраи пӯшидан", "Ҷое, ки либосро пӯшида мебинанд."),
        ]),
        ("Нон куҷост?", [
            t("Excuse me, where is the bread?", "Бубахшед, нон куҷост?", "Бигӯ: қатори ду. Биёед",
              "Aisle two. Come with me.", "Қатори ду. Биёед.", ["In aisle two.", "This way, please."]),
            t("Thank you!", "Ташаккур!", "Бипурс: боз чизе лозим?", "Anything else?", "Боз чизе лозим?",
              ["Do you need anything else?", "Something else?"]),
            t("No, that's all.", "Не, ҳамин.", "Бигӯ: хуб. Рӯзи хуш", "Okay. Have a nice day!", "Хуб. Рӯзи хуш!",
              ["Have a nice day!", "Have a good day!"]),
        ]),
        ("Кадом андоза?", [
            s("Aisle two", "Қатори ду", None),
            s("Which size?", "Кадом андоза?", None),
            s("Which color?", "Кадом ранг?", None),
            s("Medium size", "Андозаи миёна", None),
            s("Try it", "Пӯшида бинед", None),
            s("Over there", "Он ҷо", None),
        ]),
        ("Пӯшида бинед", [
            t("I like this shirt.", "Ин курта ба ман писанд.", "Бипурс: кадом андоза?", "Which size?",
              "Кадом андоза?", ["What size?", "Which size, please?"]),
            t("Medium, please.", "Миёна, лутфан.", "Бигӯ: ана. Пӯшида бинед", "Here. Try it.", "Ана. Пӯшида бинед.",
              ["Here you go.", "Try it, please."]),
            t("Where is the fitting room?", "Ҳуҷраи пӯшидан куҷост?", "Бигӯ: он ҷо", "Over there.", "Он ҷо.",
              ["It's over there.", "There, on the left."]),
        ]),
        ("Ёрӣ диҳам?", [
            s("Can I help you?", "Ёрӣ диҳам?", None),
            s("Looking for something?", "Чизе меҷӯед?", None),
            s("Follow me, please.", "Аз пайи ман биёед.", None),
            s("It's in aisle two.", "Дар қатори ду.", None),
            s("We have blue.", "Кабуд дорем.", None),
            s("This one is cheaper.", "Ин арзонтар аст.", None),
        ]),
        ("Ранги дигар", [
            t("Do you have this in red?", "Инро сурх доред?", "Бигӯ: не. Кабуд дорем", "No. We have blue.",
              "Не. Кабуд дорем.", ["Sorry, only blue.", "We have blue."]),
            t("Hmm. It's expensive.", "Ҳмм. Қимат аст.", "Бигӯ: ин арзонтар аст", "This one is cheaper.",
              "Ин арзонтар аст.", ["This is cheaper.", "Look, this one is cheaper."]),
            t("Oh, nice! I'll take it.", "О, хуб! Мегирам.", "Бигӯ: олӣ. Касса он ҷо", "Great. The register is there.",
              "Олӣ. Касса он ҷо.", ["Great. Pay over there.", "Great!"]),
        ]),
        ("Тамом шуд", [
            s("Sorry, it's sold out.", "Бубахшед, тамом шуд.", None),
            s("It comes on Monday.", "Душанбе меояд.", None),
            s("Let me check.", "Ҳозир месанҷам.", None),
            s("It's in the back.", "Дар анбор аст.", None),
            s("I'll ask my manager.", "Аз менеҷер мепурсам.", None),
            s("Over here, please.", "Ин ҷо, лутфан.", None),
        ]),
        ("Кай меояд?", [
            t("Do you have more of these?", "Боз аз инҳо доред?", "Бигӯ: ҳозир месанҷам", "Let me check.",
              "Ҳозир месанҷам.", ["One moment.", "I'll check."]),
            t("Thanks.", "Ташаккур.", "Бигӯ: бубахшед, тамом шуд", "Sorry, it's sold out.", "Бубахшед, тамом шуд.",
              ["Sorry, none left.", "Sorry, we don't have it."]),
            t("When will you have more?", "Кай боз меояд?", "Бигӯ: душанбе меояд", "It comes on Monday.",
              "Душанбе меояд.", ["On Monday.", "Monday."]),
        ]),
        ("Миссия: харидор", [
            t("Excuse me, can you help me?", "Бубахшед, ёрӣ медиҳед?", "Бигӯ: ҳа, албатта. Чизе меҷӯед?",
              "Yes, of course. Looking for something?", "Ҳа, албатта. Чизе меҷӯед?",
              ["Sure. Can I help you?", "Yes. What do you need?"]),
            t("Yes, this jacket. Size large.", "Ҳа, ин куртка. Андозаи калон.", "Бигӯ: ҳозир месанҷам",
              "Let me check.", "Ҳозир месанҷам.", ["One moment.", "I'll check."]),
            t("Do you have it?", "Доред?", "Бигӯ: бубахшед, тамом шуд. Душанбе меояд",
              "Sorry, it's sold out. It comes on Monday.", "Бубахшед, тамом шуд. Душанбе меояд.",
              ["Sorry, it's sold out.", "Monday, sorry."]),
            t("Okay, I'll come on Monday.", "Хуб, душанбе меоям.", "Бигӯ: ташаккур. Рӯзи хуш",
              "Thank you. Have a nice day!", "Ташаккур. Рӯзи хуш!", ["Thanks! See you Monday.", "Have a nice day!"]),
        ]),
    ]))

# ═════════════════════ 15. Фармоиш бо телефон ═════════════════════
made.append(pack("phone_order_en_tg", "Phone orders", "Фармоиш бо телефон", "📞", 15, SV,
    "Мизоҷ ба тарабхона занг мезанад ва хӯрок фармоиш медиҳад. Шумо фармоишро менависед, "
    "мепурсед, ки худаш мегирад ё расонем, суроға ва телефонро мепурсед ва вақтро мегӯед.",
    [
        ("Занг", [
            w("Pizza", "пицца", None),
            w("Pickup", "худатон гирифтан", "Мизоҷ худаш омада мегирад."),
            w("Delivery", "расонидан", None),
            w("Address", "суроға", None),
            w("Number", "рақам", None),
            w("Minutes", "дақиқаҳо", None),
        ]),
        ("Пиццаи калон", [
            t("Hi! Can I order food?", "Салом! Хӯрок фармоиш дода метавонам?", "Бигӯ: ҳа, албатта. Чӣ мехоҳед?",
              "Yes, of course. What would you like?", "Ҳа, албатта. Чӣ мехоҳед?",
              ["Sure. What would you like?", "Yes. What do you want?"]),
            t("One large pizza.", "Як пиццаи калон.", "Бипурс: худатон мегиред ё расонем?", "Pickup or delivery?",
              "Худатон мегиред ё расонем?", ["Delivery or pickup?", "Pickup?"]),
            t("Pickup, please.", "Худам мегирам.", "Бигӯ: бист дақиқа тайёр мешавад", "Ready in twenty minutes.",
              "Пас аз бист дақиқа тайёр.", ["Twenty minutes.", "It's ready in twenty minutes."]),
        ]),
        ("Суроғаатон?", [
            s("Large pizza", "Пиццаи калон", None),
            s("For pickup", "Барои гирифтан", None),
            s("For delivery", "Барои расонидан", None),
            s("Your address?", "Суроғаатон?", None),
            s("Your number?", "Рақаматон?", None),
            s("Twenty minutes", "Бист дақиқа", None),
        ]),
        ("Расонидан", [
            t("Delivery, please.", "Расонидан, лутфан.", "Бипурс: суроғаатон?", "Your address?", "Суроғаатон?",
              ["What's your address?", "Address, please?"]),
            t("Twelve Park Street.", "Кӯчаи Парк, хонаи дувоздаҳ.", "Бипурс: рақаматон?", "Your number?",
              "Рақаматон?", ["Your phone number?", "Phone number, please?"]),
            t("Five five five, one two three four.", "Панҷ панҷ панҷ, як ду се чор.", "Бигӯ: ташаккур. Сӣ дақиқа",
              "Thank you. Thirty minutes.", "Ташаккур. Сӣ дақиқа.", ["Thanks. About thirty minutes.", "Thirty minutes."]),
        ]),
        ("Ҳарф ба ҳарф", [
            s("Hello, Pizza House.", "Алло, «Пицца Ҳаус».", None),
            s("Can you spell it?", "Ҳарф ба ҳарф мегӯед?", None),
            s("Please say again.", "Лутфан, боз гӯед.", None),
            s("Pay at pickup.", "Ҳангоми гирифтан пардохт кунед.", None),
            s("It's twenty dollars.", "Бист доллар мешавад.", None),
            s("Anything to drink?", "Ягон нӯшокӣ?", None),
        ]),
        ("Номатон?", [
            t("My name is Smith.", "Номи ман Смит.", "Бипурс: ҳарф ба ҳарф мегӯед?", "Can you spell it?",
              "Ҳарф ба ҳарф мегӯед?", ["Spell it, please?", "How do you spell it?"]),
            t("S-M-I-T-H.", "С-М-И-Т-Ҳ.", "Бигӯ: ташаккур. Ягон нӯшокӣ?", "Thank you. Anything to drink?",
              "Ташаккур. Ягон нӯшокӣ?", ["Anything to drink?", "Thanks. A drink?"]),
            t("Two colas.", "Ду кола.", "Бигӯ: бист доллар. Ҳангоми гирифтан пардохт кунед",
              "It's twenty dollars. Pay at pickup.", "Бист доллар. Ҳангоми гирифтан пардохт кунед.",
              ["Twenty dollars. Pay at pickup.", "It's twenty dollars."]),
        ]),
        ("Баста ҳастем", [
            s("Sorry, we are closed.", "Бубахшед, мо баста ҳастем.", None),
            s("We open at ten.", "Соати даҳ мекушоем.", None),
            s("Your order is ready.", "Фармоишатон тайёр.", None),
            s("Please call back.", "Лутфан, боз занг занед.", None),
            s("One large pizza?", "Як пиццаи калон?", None),
            s("See you soon!", "То дидор!", None),
        ]),
        ("Кай мекушоед?", [
            t("Hello? Can I order now?", "Алло? Ҳозир фармоиш дода метавонам?", "Бигӯ: бубахшед, мо баста ҳастем",
              "Sorry, we are closed.", "Бубахшед, мо баста ҳастем.", ["Sorry, we're closed.", "Sorry, closed now."]),
            t("Oh. When do you open?", "О. Кай мекушоед?", "Бигӯ: соати даҳ мекушоем", "We open at ten.",
              "Соати даҳ мекушоем.", ["At ten.", "Ten o'clock."]),
            t("Okay, I'll call tomorrow.", "Хуб, фардо занг мезанам.", "Бигӯ: ташаккур. Хайр", "Thank you. Bye!",
              "Ташаккур. Хайр!", ["Thanks! Goodbye.", "Okay, bye!"]),
        ]),
        ("Миссия: фармоиш бо телефон", [
            t("Hello? Is this Pizza House?", "Алло? Ин «Пицца Ҳаус» аст?", "Бигӯ: ҳа. Чӣ ёрӣ диҳам?",
              "Yes. How can I help?", "Ҳа. Чӣ ёрӣ диҳам?", ["Yes. Can I help you?", "Yes, hello!"]),
            t("One large pizza, delivery.", "Як пиццаи калон, бо расонидан.", "Бипурс: суроғаатон?", "Your address?",
              "Суроғаатон?", ["What's your address?", "Address, please?"]),
            t("Twelve Park Street.", "Кӯчаи Парк, хонаи дувоздаҳ.", "Бипурс: ягон нӯшокӣ?", "Anything to drink?",
              "Ягон нӯшокӣ?", ["Something to drink?", "Any drinks?"]),
            t("No, thanks. How long?", "Не, ташаккур. Чанд вақт?", "Бигӯ: сӣ дақиқа", "Thirty minutes.",
              "Сӣ дақиқа.", ["About thirty minutes.", "Thirty minutes, please."]),
        ]),
    ], mission_mode="call"))

# ═════════════════════ 17. Тозакунӣ ва бастан ═════════════════════
made.append(pack("closing_en_tg", "Cleaning and closing", "Тозакунӣ ва бастан", "🧹", 17, SV,
    "Охири рӯз: мизҳоро пок мекунед, фаршро мешӯед, партовро мебароред ва ҷойро мебандед. "
    "Шумо мепурсед, ки чӣ кор кунед, ва мегӯед, ки ҳама тайёр аст.",
    [
        ("Тозакунӣ", [
            w("Mop", "швабра", None),
            w("Broom", "ҷорӯб", None),
            w("Trash", "партов", None),
            w("Floor", "фарш", None),
            w("Wipe", "пок кардан", None),
            w("Lock", "қулф кардан", None),
        ]),
        ("Чӣ кор кунам?", [
            t("We close in ten minutes.", "Пас аз даҳ дақиқа мебандем.", "Бипурс: чӣ кор кунам?", "What do I do?",
              "Чӣ кор кунам?", ["What can I do?", "What should I do?"]),
            t("Wipe the tables, please.", "Мизҳоро пок кунед, лутфан.", "Бигӯ: хуб", "Okay.", "Хуб.",
              ["Okay, sure.", "Sure."]),
            t("Then mop the floor.", "Баъд фаршро шӯед.", "Бигӯ: фаҳмидам", "Got it.", "Фаҳмидам.",
              ["Okay.", "Okay, got it."]),
        ]),
        ("Фарши тар", [
            s("Wipe tables", "Мизҳоро пок кунед", None),
            s("Wet floor", "Фарши тар", None),
            s("Trash bags", "Халтаҳои партов", None),
            s("Lock up", "Қулф кунед", None),
            s("All clean", "Ҳама тоза", None),
            s("Ten minutes", "Даҳ дақиқа", None),
        ]),
        ("Эҳтиёт, тар аст", [
            t("Can I walk here?", "Аз ин ҷо гузарам?", "Бигӯ: эҳтиёт шавед, фарш тар аст", "Careful, the floor is wet.",
              "Эҳтиёт, фарш тар аст.", ["Careful, it's wet.", "The floor is wet."]),
            t("Oh, thanks!", "О, ташаккур!", "Бигӯ: мо пас аз даҳ дақиқа мебандем", "We close in ten minutes.",
              "Пас аз даҳ дақиқа мебандем.", ["Ten minutes to close.", "We close soon."]),
            t("Okay, I'm leaving.", "Хуб, меравам.", "Бигӯ: ташаккур. Шаби хуш", "Thank you. Good night!",
              "Ташаккур. Шаби хуш!", ["Good night!", "Thanks, bye!"]),
        ]),
        ("Швабра куҷост?", [
            s("The tables are clean.", "Мизҳо тоза ҳастанд.", None),
            s("Where is the mop?", "Швабра куҷост?", None),
            s("The trash is out.", "Партов берун шуд.", None),
            s("The floor is wet.", "Фарш тар аст.", None),
            s("Is the door locked?", "Дар қулф аст?", None),
            s("Lights off?", "Чароғҳоро хомӯш кунам?", None),
        ]),
        ("Мизҳо тоза", [
            t("Did you wipe the tables?", "Мизҳоро пок кардед?", "Бигӯ: ҳа, мизҳо тоза ҳастанд",
              "Yes, the tables are clean.", "Ҳа, мизҳо тоза ҳастанд.", ["Yes, all clean.", "Yes, done."]),
            t("Good. Now the floor.", "Хуб. Акнун фарш.", "Бипурс: швабра куҷост?", "Where is the mop?",
              "Швабра куҷост?", ["The mop?", "Where's the mop?"]),
            t("In the back, by the sink.", "Дар қафо, назди раковина.", "Бигӯ: хуб, ташаккур", "Okay, thanks.",
              "Хуб, ташаккур.", ["Thanks.", "Okay."]),
        ]),
        ("То фардо", [
            s("Everything is clean.", "Ҳама тоза аст.", None),
            s("I'm going home.", "Ман ба хона меравам.", None),
            s("See you tomorrow!", "То фардо!", None),
            s("The door is locked.", "Дар қулф аст.", None),
            s("The lights are off.", "Чароғҳо хомӯш.", None),
            s("Can I go now?", "Ҳозир равам?", None),
        ]),
        ("Ҳама тоза", [
            t("Is everything clean?", "Ҳама тоза аст?", "Бигӯ: ҳа, ҳама тоза аст", "Yes, everything is clean.",
              "Ҳа, ҳама тоза аст.", ["Yes, all clean.", "Yes, everything."]),
            t("And the door?", "Ва дар?", "Бигӯ: дар қулф аст", "The door is locked.", "Дар қулф аст.",
              ["It's locked.", "Yes, locked."]),
            t("Great job. You can go.", "Офарин. Рафта метавонед.", "Бигӯ: ташаккур. То фардо",
              "Thanks. See you tomorrow!", "Ташаккур. То фардо!", ["See you tomorrow!", "Thank you, bye!"]),
        ]),
        ("Миссия: бастан", [
            t("We close in ten minutes.", "Пас аз даҳ дақиқа мебандем.", "Бипурс: чӣ кор кунам?", "What do I do?",
              "Чӣ кор кунам?", ["What can I do?", "What should I do?"]),
            t("Wipe the tables and mop the floor.", "Мизҳоро пок кунед ва фаршро шӯед.",
              "Бигӯ: фаҳмидам. Швабра куҷост?", "Got it. Where is the mop?", "Фаҳмидам. Швабра куҷост?",
              ["Okay. The mop?", "Where's the mop?"]),
            t("In the back. Then take out the trash.", "Дар қафо. Баъд партовро бароред.", "Бигӯ: хуб", "Okay.",
              "Хуб.", ["Okay, sure.", "Sure."]),
            t("All done? Is the door locked?", "Тамом? Дар қулф аст?", "Бигӯ: ҳа, дар қулф аст. То фардо",
              "Yes, the door is locked. See you tomorrow!", "Ҳа, дар қулф аст. То фардо!",
              ["Yes, it's locked.", "Yes. See you tomorrow!"]),
        ]),
    ]))

# ═════════════════════ 18. Хӯрок ва аллергия ═════════════════════
made.append(pack("allergy_en_tg", "Food and allergies", "Хӯрок ва аллергия", "🥜", 18, SV,
    "Меҳмон мепурсад, ки дар хӯрок чӣ ҳаст: гӯшти хук, чормағз, шир. Шумо ҷавоб медиҳед, "
    "аз ошпаз мепурсед ва хӯроки дигар пешниҳод мекунед.",
    [
        ("Дар хӯрок чӣ ҳаст?", [
            w("Nuts", "чормағз", None),
            w("Pork", "гӯшти хук", None),
            w("Beef", "гӯшти гов", None),
            w("Halal", "ҳалол", None),
            w("Vegetarian", "бе гӯшт", "Хӯрок барои касе, ки гӯшт намехӯрад."),
            w("Allergy", "аллергия", None),
        ]),
        ("Гӯшти хук ҳаст?", [
            t("Is there pork in this?", "Дар ин гӯшти хук ҳаст?", "Бигӯ: не, ин гӯшти гов", "No, it's beef.",
              "Не, ин гӯшти гов.", ["No pork. Beef.", "No. It's beef."]),
            t("Is it halal?", "Ҳалол аст?", "Бигӯ: ҳа, ҳалол", "Yes, it's halal.", "Ҳа, ҳалол.",
              ["Yes.", "Yes, halal."]),
            t("Great, I'll take it.", "Олӣ, мегирам.", "Бигӯ: хуб", "Okay.", "Хуб.", ["Okay, great.", "Sure."]),
        ]),
        ("Бе чормағз", [
            s("No pork", "Бе гӯшти хук", None),
            s("No nuts", "Бе чормағз", None),
            s("Halal meat", "Гӯшти ҳалол", None),
            s("With milk", "Бо шир", None),
            s("I'll ask", "Мепурсам", None),
            s("Fish only", "Танҳо моҳӣ", None),
        ]),
        ("Аллергия", [
            t("I have a nut allergy.", "Ман ба чормағз аллергия дорам.", "Бигӯ: мефаҳмам. Аз ошпаз мепурсам",
              "I understand. I'll ask the chef.", "Мефаҳмам. Аз ошпаз мепурсам.", ["I'll ask the chef.", "Okay. I'll ask."]),
            t("Thank you.", "Ташаккур.", "Бигӯ: дар ин чормағз нест", "This has no nuts.", "Дар ин чормағз нест.",
              ["No nuts in this.", "It has no nuts."]),
            t("Are you sure?", "Боварӣ доред?", "Бигӯ: ҳа, аз ошпаз пурсидам", "Yes, I asked the chef.",
              "Ҳа, аз ошпаз пурсидам.", ["Yes, I'm sure.", "Yes, the chef said so."]),
        ]),
        ("Аз ошпаз мепурсам", [
            s("It has milk.", "Дар он шир ҳаст.", None),
            s("This has no nuts.", "Дар ин чормағз нест.", None),
            s("I'll ask the chef.", "Аз ошпаз мепурсам.", None),
            s("The chicken is halal.", "Мурғ ҳалол аст.", None),
            s("We have vegetarian food.", "Мо хӯроки бе гӯшт дорем.", None),
            s("Try the fish.", "Моҳиро бичашед.", None),
        ]),
        ("Бе гӯшт", [
            t("I don't eat meat.", "Ман гӯшт намехӯрам.", "Бигӯ: мо хӯроки бе гӯшт дорем", "We have vegetarian food.",
              "Мо хӯроки бе гӯшт дорем.", ["We have food with no meat.", "We have vegetarian dishes."]),
            t("What do you have?", "Чӣ доред?", "Бигӯ: шӯрбои сабзавот ва салат", "Vegetable soup and salad.",
              "Шӯрбои сабзавот ва салат.", ["Salad and vegetable soup.", "Vegetable soup."]),
            t("Is there milk in the soup?", "Дар шӯрбо шир ҳаст?", "Бигӯ: ҳа, дар он шир ҳаст", "Yes, it has milk.",
              "Ҳа, дар он шир ҳаст.", ["Yes, a little milk.", "Yes."]),
        ]),
        ("Бо биринҷ", [
            s("It's not spicy.", "Тунд нест.", None),
            s("This has no sugar.", "Дар ин шакар нест.", None),
            s("It's made fresh.", "Тоза тайёр шудааст.", None),
            s("Small or large?", "Хурд ё калон?", None),
            s("It comes with rice.", "Бо биринҷ меояд.", None),
            s("Do you want bread?", "Нон мехоҳед?", None),
        ]),
        ("Тунд нест", [
            t("What comes with the chicken?", "Мурғ бо чӣ меояд?", "Бигӯ: бо биринҷ меояд", "It comes with rice.",
              "Бо биринҷ меояд.", ["Rice.", "With rice."]),
            t("Is it spicy?", "Тунд аст?", "Бигӯ: не, тунд нест", "No, it's not spicy.", "Не, тунд нест.",
              ["Not spicy.", "No, not at all."]),
            t("Perfect. One chicken, please.", "Олӣ. Як мурғ, лутфан.", "Бипурс: нон мехоҳед?", "Do you want bread?",
              "Нон мехоҳед?", ["Bread too?", "Any bread?"]),
        ]),
        ("Миссия: хӯроки бехатар", [
            t("Hi! Is there pork in the soup?", "Салом! Дар шӯрбо гӯшти хук ҳаст?", "Бигӯ: не, ин гӯшти гов",
              "No, it's beef.", "Не, ин гӯшти гов.", ["No pork. Beef.", "No. It's beef."]),
            t("Good. And I have a nut allergy.", "Хуб. Ва ман ба чормағз аллергия дорам.",
              "Бигӯ: мефаҳмам. Аз ошпаз мепурсам", "I understand. I'll ask the chef.", "Мефаҳмам. Аз ошпаз мепурсам.",
              ["I'll ask the chef.", "Okay. I'll ask."]),
            t("Thank you. Is it safe?", "Ташаккур. Бехатар аст?", "Бигӯ: ҳа, дар ин чормағз нест",
              "Yes, this has no nuts.", "Ҳа, дар ин чормағз нест.", ["Yes, no nuts.", "Yes, it's safe."]),
            t("Great! One soup, please.", "Олӣ! Як шӯрбо, лутфан.", "Бипурс: нон мехоҳед?", "Do you want bread?",
              "Нон мехоҳед?", ["Bread too?", "Any bread?"]),
        ]),
    ]))

# ═════════════════════ 19. Рӯзи серкор ═════════════════════
made.append(pack("rush_en_tg", "A busy day", "Рӯзи серкор", "⏱️", 19, SV,
    "Мизоҷон бисёранд ва ҳама шитоб доранд. Шумо мегӯед «як дақиқа», аз ҳамкор ёрӣ "
    "мепурсед, мегӯед, ки чизе тамом шуд ва навбатро ором идора мекунед.",
    [
        ("Серкор", [
            w("Busy", "серкор", None),
            w("Line", "навбат", "Одамоне, ки пай дар пай меистанд."),
            w("Coworker", "ҳамкор", None),
            w("Wait", "интизор шудан", None),
            w("Quick", "зуд", None),
            w("Customer", "мизоҷ", None),
        ]),
        ("Шумо навбатӣ", [
            t("Excuse me! I'm waiting!", "Бубахшед! Ман интизорам!", "Бигӯ: як дақиқа, лутфан", "One minute, please.",
              "Як дақиқа, лутфан.", ["Just a minute.", "One moment, please."]),
            t("How long?", "Чанд вақт?", "Бигӯ: шумо навбатӣ", "You're next.", "Шумо навбатӣ.",
              ["You are next.", "You're next, sorry."]),
            t("Okay, thanks.", "Хуб, ташаккур.", "Бигӯ: ташаккур барои интизорӣ", "Thanks for waiting.",
              "Ташаккур барои интизорӣ.", ["Thank you for waiting.", "Sorry for the wait."]),
        ]),
        ("Навбати дароз", [
            s("Very busy", "Хеле серкор", None),
            s("Long line", "Навбати дароз", None),
            s("You're next", "Шумо навбатӣ", None),
            s("Help me", "Ёрӣ диҳед", None),
            s("Two minutes", "Ду дақиқа", None),
            s("Sold out", "Тамом шуд", None),
        ]),
        ("Ҳамкор", [
            t("Hey, are you okay?", "Эй, хубӣ?", "Бигӯ: хеле серкор. Ёрӣ диҳед, лутфан", "Very busy. Help me, please.",
              "Хеле серкор. Ёрӣ диҳед, лутфан.", ["Help me, please.", "It's busy. Can you help?"]),
            t("Sure. What can I do?", "Албатта. Чӣ кор кунам?", "Бигӯ: мизоҷи навбатиро гиред",
              "Take the next customer.", "Мизоҷи навбатиро гиред.", ["Help the next customer.", "Take the next one."]),
            t("Okay, no problem.", "Хуб, мушкил нест.", "Бигӯ: ташаккур!", "Thank you!", "Ташаккур!",
              ["Thanks a lot!", "Thank you so much!"]),
        ]),
        ("Тез мекунам", [
            s("Next customer, please!", "Мизоҷи навбатӣ, лутфан!", None),
            s("No more milk.", "Шир тамом шуд.", None),
            s("Today is busy.", "Имрӯз серкор аст.", None),
            s("I'll be quick.", "Зуд мекунам.", None),
            s("Please wait a minute.", "Лутфан, як дақиқа сабр кунед.", None),
            s("I'm coming.", "Ҳозир меоям.", None),
        ]),
        ("Шир тамом", [
            t("A latte, please.", "Як латте, лутфан.", "Бигӯ: бубахшед, шир тамом шуд", "Sorry, no more milk.",
              "Бубахшед, шир тамом шуд.", ["Sorry, we're out of milk.", "No milk, sorry."]),
            t("Oh no. What do you have?", "Вой. Чӣ доред?", "Бигӯ: чой ё қаҳваи сиёҳ", "Tea or black coffee.",
              "Чой ё қаҳваи сиёҳ.", ["Black coffee or tea.", "We have tea."]),
            t("Black coffee, then.", "Пас қаҳваи сиёҳ.", "Бигӯ: хуб, зуд мекунам", "Okay, I'll be quick.",
              "Хуб, зуд мекунам.", ["Okay, one minute.", "Coming right up."]),
        ]),
        ("Сабр кунед", [
            s("Sorry, my mistake.", "Бубахшед, хатои ман.", None),
            s("This is correct.", "Ин дуруст аст.", None),
            s("I'm new here.", "Ман ин ҷо навам.", None),
            s("Please be patient.", "Лутфан, сабр кунед.", None),
            s("Almost done!", "Қариб тамом!", None),
            s("We're very busy.", "Мо хеле серкорем.", None),
        ]),
        ("Хатои ман", [
            t("This is taking so long!", "Ин хеле дароз шуд!", "Бигӯ: бубахшед, мо хеле серкорем",
              "Sorry, we're very busy.", "Бубахшед, мо хеле серкорем.", ["Sorry, it's busy today.", "We're very busy, sorry."]),
            t("I have a meeting!", "Ман ҷаласа дорам!", "Бигӯ: лутфан, сабр кунед. Қариб тамом",
              "Please be patient. Almost done!", "Лутфан, сабр кунед. Қариб тамом!", ["Almost done!", "Please wait. Almost ready."]),
            t("Hmm, this is not mine.", "Ҳмм, ин аз ман нест.", "Бигӯ: бубахшед, хатои ман", "Sorry, my mistake.",
              "Бубахшед, хатои ман.", ["Sorry! My mistake.", "Oh, sorry."]),
        ]),
        ("Миссия: рӯзи серкор", [
            t("Excuse me! We are waiting!", "Бубахшед! Мо интизорем!", "Бигӯ: як дақиқа. Шумо навбатӣ",
              "One minute. You're next.", "Як дақиқа. Шумо навбатӣ.", ["You're next.", "One minute, please."]),
            t("Two lattes, please.", "Ду латте, лутфан.", "Бигӯ: бубахшед, шир тамом шуд", "Sorry, no more milk.",
              "Бубахшед, шир тамом шуд.", ["Sorry, we're out of milk.", "No milk, sorry."]),
            t("Then two black coffees.", "Пас ду қаҳваи сиёҳ.", "Бигӯ: хуб, зуд мекунам", "Okay, I'll be quick.",
              "Хуб, зуд мекунам.", ["Okay, one minute.", "Coming right up."]),
            t("Thank you. Busy day, huh?", "Ташаккур. Рӯзи серкор, ҳа?", "Бигӯ: ҳа. Ташаккур барои интизорӣ",
              "Yes. Thanks for waiting.", "Ҳа. Ташаккур барои интизорӣ.", ["Thanks for waiting.", "Yes! Thank you for waiting."]),
        ]),
    ]))

# ═════════════════════ 20. Ҷадвали кор ═════════════════════
made.append(pack("schedule_en_tg", "Work schedule", "Ҷадвали кор", "🗓️", 20, SV,
    "Бо менеҷер дар бораи ҷадвал гап мезанед: кадом рӯзҳо ва соатҳо кор мекунед, навбатро "
    "иваз мекунед, бемор шудед ё рӯзи истироҳат мехоҳед, ва музд дуруст аст ё не.",
    [
        ("Ҷадвал", [
            w("Schedule", "ҷадвал", None),
            w("Manager", "менеҷер", None),
            w("Morning", "субҳ", None),
            w("Evening", "бегоҳ", None),
            w("Day off", "рӯзи истироҳат", None),
            w("Swap", "иваз кардан", None),
        ]),
        ("Кай кор мекунам?", [
            t("Here is your schedule.", "Ана ҷадвали шумо.", "Бипурс: ман кай кор мекунам?", "When do I work?",
              "Ман кай кор мекунам?", ["Which days do I work?", "What days?"]),
            t("Monday to Friday, mornings.", "Аз душанбе то ҷумъа, субҳ.", "Бипурс: соати чанд?", "What time?",
              "Соати чанд?", ["What time do I start?", "Start time?"]),
            t("Seven to three.", "Аз ҳафт то се.", "Бигӯ: хуб, ташаккур", "Okay, thank you.", "Хуб, ташаккур.",
              ["Okay.", "Great, thanks."]),
        ]),
        ("Навбати субҳ", [
            s("Morning shift", "Навбати субҳ", None),
            s("Evening shift", "Навбати бегоҳ", None),
            s("Day off", "Рӯзи истироҳат", None),
            s("Next week", "Ҳафтаи оянда", None),
            s("Swap shifts", "Навбат иваз кардан", None),
            s("Seven o'clock", "Соати ҳафт", None),
        ]),
        ("Шанбе", [
            t("Can you work Saturday?", "Шанбе кор карда метавонед?", "Бигӯ: бубахшед, наметавонам",
              "Sorry, I can't.", "Бубахшед, наметавонам.", ["Sorry, not Saturday.", "No, sorry."]),
            t("Why not?", "Чаро не?", "Бигӯ: ман бо оилаам ҳастам", "I'm with my family.", "Ман бо оилаам ҳастам.",
              ["Family day.", "I'm with my family that day."]),
            t("Okay. Can you swap with Ali?", "Хуб. Бо Алӣ иваз мекунед?", "Бигӯ: ҳа, аз ӯ мепурсам",
              "Yes, I'll ask him.", "Ҳа, аз ӯ мепурсам.", ["Okay, I'll ask.", "Sure."]),
        ]),
        ("Бемор ҳастам", [
            s("I'm sick today.", "Имрӯз беморам.", None),
            s("I can't come today.", "Имрӯз омада наметавонам.", None),
            s("Friday off, please?", "Ҷумъа истироҳат, лутфан?", None),
            s("I can work Sunday.", "Якшанбе кор карда метавонам.", None),
            s("I'll be late.", "Дер мемонам.", None),
            s("Can we swap?", "Иваз кунем?", None),
        ]),
        ("Занг ба менеҷер", [
            t("Hello? Where are you?", "Алло? Шумо куҷоед?", "Бигӯ: ман имрӯз беморам", "I'm sick today.",
              "Ман имрӯз беморам.", ["Sorry, I'm sick.", "I'm sick. I can't come."]),
            t("Oh no. Can you come tomorrow?", "Вой. Фардо омада метавонед?", "Бигӯ: ҳа, шояд", "Yes, maybe.",
              "Ҳа, шояд.", ["I think so.", "Maybe, yes."]),
            t("Okay. Feel better!", "Хуб. Шифо ёбед!", "Ташаккур гӯй", "Thank you.", "Ташаккур.",
              ["Thanks.", "Thank you very much."]),
        ]),
        ("Музд", [
            s("Is my pay ready?", "Музди ман тайёр аст?", None),
            s("When is payday?", "Рӯзи музд кай?", None),
            s("This is not right.", "Ин дуруст нест.", None),
            s("I worked forty hours.", "Ман чил соат кор кардам.", None),
            s("Can you check, please?", "Месанҷед, лутфан?", None),
            s("Thank you, boss.", "Ташаккур, сардор.", None),
        ]),
        ("Музд дуруст нест", [
            t("Here is your pay.", "Ана музди шумо.", "Бигӯ: ин дуруст нест", "This is not right.", "Ин дуруст нест.",
              ["Sorry, this is wrong.", "I think this is wrong."]),
            t("Why? What's wrong?", "Чаро? Чӣ нодуруст?", "Бигӯ: ман чил соат кор кардам", "I worked forty hours.",
              "Ман чил соат кор кардам.", ["Forty hours.", "I worked forty hours this week."]),
            t("Oh, you're right. I'll fix it.", "О, дуруст мегӯед. Ислоҳ мекунам.", "Ташаккур гӯй", "Thank you.",
              "Ташаккур.", ["Thanks.", "Thank you, boss."]),
        ]),
        ("Миссия: ҷадвали нав", [
            t("Hi! Can you work Saturday?", "Салом! Шанбе кор карда метавонед?",
              "Бигӯ: бубахшед, наметавонам. Якшанбе метавонам", "Sorry, I can't. I can work Sunday.",
              "Бубахшед, наметавонам. Якшанбе метавонам.", ["I can work Sunday.", "Not Saturday. Sunday is okay."]),
            t("Okay, Sunday then. Morning or evening?", "Хуб, пас якшанбе. Субҳ ё бегоҳ?", "Бигӯ: субҳ, лутфан",
              "Morning, please.", "Субҳ, лутфан.", ["The morning shift.", "Morning."]),
            t("Done. Anything else?", "Тайёр. Боз чизе?", "Бипурс: ҷумъа истироҳат, лутфан?", "Friday off, please?",
              "Ҷумъа истироҳат, лутфан?", ["Can I have Friday off?", "Friday off?"]),
            t("Sure, Friday is off. See you Sunday!", "Хуб, ҷумъа истироҳат. То якшанбе!", "Бигӯ: олӣ, ташаккур",
              "Great, thank you!", "Олӣ, ташаккур!", ["Great!", "Thanks! See you Sunday."]),
        ]),
    ]))

if MISSING:
    raise SystemExit('⛔ транскрипсия нест: ' + ', '.join(sorted(MISSING)))
print(' '.join(made))
