"""АНГЛИСӢ → тоҷикӣ, «Гуфтор» A1 — нишаи «Сафар ва ҳаёт» (`life`), 01.10.2026.

14 вазъияти ҳаёти ҳаррӯза ва сафар дар кишвари англисзабон: фурудгоҳ,
меҳмонхона, автобус ва метро, қаҳвахона, супермаркет, телефон ва интернет,
пул ва фиристодан ба хона, дорухона, почта, ҳамсояҳо, гум шудан дар шаҳр,
вақти холӣ, занги фаврӣ (911), сартарошхона.

Роҳи `life` = 5 вазъияти умумӣ (1 салом, 6 духтур, 10 бозор, 14 иҷора,
16 ҳуҷҷат) + «Кор ёфтан» (2, умумӣ барои build/service/drive/life) + ин 14 →
20 вазъият. `order`-ҳо ҳамон ҷойҳои холии роҳи сохтмонанд: 3–5, 7–9, 11–13,
15, 17–20.

Ҳамон қоидаҳо (`_en_packs_lib.py`): транскрипсия ҳатмӣ, зина ≤2/≤2/≤4/≤8 калима.
Аз ҷузвдони backend: PYTHONPATH=prisma python3 prisma/_en-life-a1-packs.py

02.10.2026: аз шохаи `claude/nifty-albattani-6uijek` (42e16a3) гирифта шуд ва бо
`prisma/_en-a1-path-audit.mjs life` ба A1-и қатъӣ расонида шуд. Унвони coffee_shop —
«Қаҳвахонаи шаҳр»: «Дар қаҳвахона» аллакай вазъияти «Хизматрасонӣ» аст, ва seed
категорияро аз рӯи унвон нест мекунад.

02.10.2026: аз шохаи `claude/nifty-albattani-6uijek` (42e16a3) гирифта шуд ва бо
`prisma/_en-a1-path-audit.mjs life` ба A1-и қатъӣ расонида шуд (`prisma/_en-life-a1-fix.py`).
Унвони coffee_shop — «Қаҳвахонаи шаҳр»: «Дар қаҳвахона» аллакай вазъияти «Хизматрасонӣ» аст,
ва seed категорияро аз рӯи унвон нест мекунад.
"""
from _en_packs_lib import *  # noqa: F401,F403

EXTRA.update({
    'books': 'букс', "he's": 'ҳиз', 'rooms': 'румз',
    # фурудгоҳ
    'flight': 'флайт', 'ticket': 'тикит', 'gate': 'гейт', 'seat': 'сит', 'bag': 'бэг', 'bags': 'бэгз',
    'window': 'виндоу', 'aisle': 'айл', 'boarding': 'бординг', 'pass': 'пэс', 'time': 'тайм',
    'flying': 'флайинг', 'lost': 'лост', 'black': 'блэк', 'big': 'биг', 'delayed': 'дилейд',
    'number': 'намбэр', 'heavy': 'ҳевӣ', 'dushanbe': 'душанбе',
    # меҳмонхона
    'hotel': 'ҳоутел', 'room': 'рум', 'key': 'кӣ', 'night': 'найт', 'nights': 'найтс',
    'breakfast': 'брекфэст', 'towel': 'тауэл', 'towels': 'тауэлз', 'reservation': 'резэрвейшэн',
    'wi': 'вай', 'fi': 'фай', 'password': 'пэсвёрд', 'free': 'фрӣ', 'checkout': 'чекаут',
    'leave': 'лив', 'elevator': 'елэвейтэр', 'shower': 'шауэр', 'noisy': 'нойзӣ', 'cold': 'коулд',
    "doesn't": 'дазнт', 'clean': 'клин',
    # роҳ
    'bus': 'бас', 'metro': 'метроу', 'stop': 'стоп', 'stops': 'стопс', 'line': 'лайн', 'map': 'мэп',
    'city': 'ситӣ', 'center': 'сентэр', 'red': 'ред', 'single': 'сингэл', 'downtown': 'даунтаун',
    'missed': 'мист', 'tell': 'тел', 'off': 'оф', 'card': 'кард',
    # қаҳвахона
    'coffee': 'кофӣ', 'tea': 'тӣ', 'cake': 'кейк', 'sugar': 'шугэр', 'cup': 'кап', 'sandwich': 'сэндвич',
    'large': 'лардж', 'small': 'смол', 'green': 'грин', 'milk': 'милк', 'restroom': 'реструм',
    'sweet': 'свит', 'receipt': 'рисит', 'another': 'эназэр', 'little': 'литэл',
    # супермаркет
    'rice': 'райс', 'eggs': 'егз', 'meat': 'мит', 'fruit': 'фрут', 'cart': 'карт', 'price': 'прайс',
    'halal': 'ҳэлэл', 'fresh': 'фреш', 'twelve': 'твелв', 'expensive': 'икспенсив', 'kilo': 'килоу',
    'kilos': 'килоуз', 'sale': 'сейл', 'forgot': 'фэргот', 'exit': 'егзит',
    # телефон
    'phone': 'фоун', 'internet': 'интэрнет', 'plan': 'плэн', 'data': 'дейтэ', 'charger': 'чарҷэр',
    'battery': 'бэтэрӣ', 'sim': 'сим', 'monthly': 'манҫлӣ', 'signal': 'сигнэл', 'slow': 'слоу',
    'charge': 'чарҷ', 'top': 'топ', 'up': 'ап', 'add': 'эд', 'message': 'месиҷ', 'send': 'сенд',
    "there's": 'ҙэрз', 'works': 'вёркс', 'twenty': 'твентӣ',
    # пул
    'money': 'манӣ', 'exchange': 'иксчейнҷ', 'atm': 'эй ти эм', 'rate': 'рейт', 'fee': 'фӣ',
    'somoni': 'сомонӣ', 'family': 'фэмилӣ', 'cash': 'кэш', 'only': 'оунлӣ', 'arrive': 'эрайв',
    'stuck': 'стак', 'count': 'каунт', 'safe': 'сейф', 'hundred': 'ҳандрэд', 'main': 'мейн',
    # дорухона
    'pharmacy': 'фармэсӣ', 'medicine': 'медсин', 'pills': 'пилз', 'headache': 'ҳедейк',
    'prescription': 'прискрипшэн', 'cream': 'крим', 'cough': 'коф', 'sore': 'сор', 'throat': 'ҫроут',
    'times': 'таймз', 'after': 'эфтэр', 'food': 'фуд', 'kids': 'кидз', 'fever': 'фивэр',
    'stomach': 'стамэк', 'hurts': 'ҳёртс', 'child': 'чайлд', 'she': 'шӣ', 'strong': 'стронг',
    'feel': 'фил', 'better': 'бетэр', 'before': 'бифор', 'old': 'оулд', 'years': 'йирз',
    'often': 'офэн',
    # почта
    'package': 'пэкиҷ', 'letter': 'летэр', 'stamp': 'стэмп', 'address': 'эдрес', 'form': 'форм',
    'box': 'бокс', 'air': 'еэр', 'mail': 'мейл', 'gifts': 'гифтс', 'clothes': 'клоуз', 'fast': 'фэст',
    'faster': 'фестэр', 'days': 'дейз', 'track': 'трэк', 'fragile': 'фрэҷайл', 'careful': 'кеэрфул',
    'sixty': 'сикстӣ', 'which': 'вич',
    # ҳамсояҳо
    'neighbor': 'нейбэр', 'door': 'дор', 'noise': 'нойз', 'party': 'парти', 'apartment': 'эпартмэнт',
    'loud': 'лауд', 'late': 'лейт', 'upstairs': 'апстеэрз', 'borrow': 'бороу', 'building': 'билдинг',
    'sleeping': 'слипинг', 'quiet': 'квайэт', 'music': 'мюзик', 'kind': 'кайнд', "you're": 'юр',
    'mine': 'майн', 'tomorrow': 'туморроу', 'return': 'ритёрн', 'live': 'лив',
    # гум шудан
    'station': 'стейшэн', 'park': 'парк', 'train': 'трейн', 'walk': 'вок', 'foot': 'фут',
    'looking': 'лукинг', 'show': 'шоу', 'am': 'эм', 'dead': 'дед', 'write': 'райт', 'taxi': 'тэксӣ',
    'straight': 'стрейт', 'far': 'фар', 'near': 'нир', 'way': 'вей', 'sir': 'сёр', 'excuse': 'икскюз',
    # вақти холӣ
    'weekend': 'викенд', 'movie': 'мувӣ', 'football': 'футбол', 'friends': 'френдз', 'watch': 'воч',
    'movies': 'мувиз', 'idea': 'айдиэ', 'maybe': 'мейбӣ', 'later': 'лейтэр', 'meet': 'мит',
    'together': 'тугеҙэр', 'fun': 'фан', 'stayed': 'стейд', 'tired': 'тайэрд', 'about': 'эбаут',
    'again': 'эген', 'play': 'плей', 'sunday': 'сандей', 'saturday': 'сэтэрдей', 'next': 'некст',
    'week': 'вик', 'perfect': 'пёрфект', 'sounds': 'саундз',
    # фаврӣ
    'fire': 'файэр', 'thief': 'ҫиф', 'emergency': 'имёрджэнсӣ', 'ambulance': 'эмбюлэнс',
    'fell': 'фел', 'breathing': 'бриҙинг', 'quickly': 'квиклӣ', 'someone': 'самван', 'took': 'тук',
    'hurt': 'ҳёрт', 'english': 'инглиш', 'translator': 'трэнслейтэр', 'hospital': 'ҳоспитэл',
    'son': 'сан', 'six': 'сикс', 'everyone': 'еврӣван', 'tall': 'тол', 'jacket': 'ҷэкит', 'wears': 'веэрз',
    'quick': 'квик', 'outside': 'аутсайд', 'down': 'даун', 'missing': 'мисинг', 'hurry': 'ҳарӣ',
    # сартарошхона
    'haircut': 'ҳеркат', 'short': 'шорт', 'beard': 'бирд', 'mirror': 'мирэр', 'sides': 'сайдз',
    'shorter': 'шортэр', 'bit': 'бит', 'tip': 'тип', 'month': 'манҫ', 'looks': 'лукс', 'cards': 'кардз',
    'wait': 'вейт', 'photo': 'фоутоу', 'only': 'оунлӣ',
    'but': 'бат', 'has': 'ҳэз', 'low': 'лоу', 'minute': 'минит', 'moment': 'моумэнт', 'sit': 'сит', 'so': 'соу',
})

made = []
L = ["life"]

# ═════════════════════ 3. Дар фурудгоҳ ═════════════════════
made.append(pack("airport_en_tg", "At the airport", "Дар фурудгоҳ", "🛫", 3, L,
    "Шумо ба хона ё ба сафар парвоз мекунед: шиносномаро нишон медиҳед, бағоҷро месупоред, "
    "ҷои назди тирезаро мепурсед, дарвозаро меёбед ва агар сумка гум шавад — хабар медиҳед.",
    [
        ("Парвоз", [
            w("Flight", "парвоз", None),
            w("Ticket", "чипта", None),
            w("Gate", "дарвоза", "Дарвозае, ки аз он ба ҳавопаймо мебароед."),
            w("Passport", "шиноснома", None),
            w("Seat", "ҷой", None),
            w("Bag", "сумка", None),
        ]),
        ("Бақайдгирӣ", [
            t("Hello! Where are you flying?", "Салом! Ба куҷо парвоз мекунед?", "Бигӯ: ба Душанбе", "To Dushanbe.",
              "Ба Душанбе.", ["Dushanbe.", "I'm flying to Dushanbe."]),
            t("Passport, please.", "Шиноснома, лутфан.", "Бигӯ: марҳамат", "Here you go.", "Марҳамат.",
              ["Here it is.", "Here is my passport."]),
            t("Any bags?", "Бағоҷ доред?", "Бигӯ: ҳа, як сумка", "Yes, one bag.", "Ҳа, як сумка.",
              ["One bag.", "Yes, just one."]),
        ]),
        ("Ҷои назди тиреза", [
            s("Window seat", "Ҷои назди тиреза", None),
            s("Aisle seat", "Ҷои назди роҳрав", None),
            s("Gate ten", "Дарвозаи даҳ", None),
            s("One bag", "Як сумка", None),
            s("Boarding pass", "Талони нишаст", "Коғазе, ки бо он ба ҳавопаймо медароед."),
            s("On time", "Сари вақт", None),
        ]),
        ("Кадом дарвоза?", [
            t("Window or aisle?", "Назди тиреза ё роҳрав?", "Бигӯ: тиреза, лутфан", "Window, please.",
              "Тиреза, лутфан.", ["A window seat, please.", "Window."]),
            t("Okay. Here is your boarding pass.", "Хуб. Ана талони нишастатон.", "Бипурс: кадом дарвоза?",
              "Which gate?", "Кадом дарвоза?", ["What gate?", "Which gate, please?"]),
            t("Gate ten.", "Дарвозаи даҳ.", "Ташаккур гӯй", "Thank you.", "Ташаккур.",
              ["Thanks.", "Thank you very much."]),
        ]),
        ("Сари вақт аст?", [
            s("Where is gate ten?", "Дарвозаи даҳ куҷост?", None),
            s("Is the flight late?", "Парвоз дер мешавад?", None),
            s("My bag is heavy.", "Сумкаам вазнин аст.", None),
            s("I have one bag.", "Ман як сумка дорам.", None),
            s("When is boarding?", "Нишаст кай?", None),
            s("Is it on time?", "Сари вақт аст?", None),
        ]),
        ("Дарвозаи даҳ", [
            t("Can I help you?", "Ёрӣ диҳам?", "Бипурс: дарвозаи даҳ куҷост?", "Where is gate ten?",
              "Дарвозаи даҳ куҷост?", ["Gate ten, please?", "Where's gate ten?"]),
            t("Go straight, then left.", "Рост равед, баъд ба чап.", "Бипурс: сари вақт аст?", "Is it on time?",
              "Сари вақт аст?", ["Is the flight on time?", "On time?"]),
            t("Yes, boarding is at five.", "Ҳа, нишаст соати панҷ.", "Бигӯ: олӣ, ташаккур", "Great, thank you.",
              "Олӣ, ташаккур.", ["Thanks!", "Okay, thank you."]),
        ]),
        ("Сумка гум шуд", [
            s("Where is my bag?", "Халтаи ман куҷост?", None),
            s("This is my bag.", "Ин сумкаи ман аст.", None),
            s("It's black and big.", "Сиёҳ ва калон аст.", None),
            s("Here is my ticket.", "Ана чиптаи ман.", None),
            s("My flight is late.", "Парвози ман дер мекунад.", None),
            s("Where are the bags?", "Сумкаҳо куҷоянд?", None),
        ]),
        ("Чӣ ранг?", [
            t("Next, please. What's the problem?", "Навбатӣ. Мушкил чист?", "Бигӯ: халтаи ман куҷост",
              "Where is my bag?", "Халтаи ман куҷост?", ["My bag is lost.", "I can't find my bag."]),
            t("What color is it?", "Чӣ ранг аст?", "Бигӯ: сиёҳ ва калон", "It's black and big.",
              "Сиёҳ ва калон аст.", ["Black and big.", "A big black bag."]),
            t("Okay. We'll call you.", "Хуб. Ба шумо занг мезанем.", "Бигӯ: ташаккур. Ана рақами ман",
              "Thank you. Here is my number.", "Ташаккур. Ана рақами ман.", ["Thanks.", "Thank you. My number is here."]),
        ]),
        ("Миссия: фурудгоҳ", [
            t("Hello! Where are you flying?", "Салом! Ба куҷо парвоз мекунед?", "Бигӯ: ба Душанбе", "To Dushanbe.",
              "Ба Душанбе.", ["Dushanbe.", "I'm flying to Dushanbe."]),
            t("Passport, please. Any bags?", "Шиноснома, лутфан. Бағоҷ доред?", "Бигӯ: марҳамат. Як сумка",
              "Here you go. One bag.", "Марҳамат. Як сумка.", ["Here. One bag.", "Yes, one bag."]),
            t("Window or aisle?", "Назди тиреза ё роҳрав?", "Бигӯ: тиреза, лутфан", "Window, please.",
              "Тиреза, лутфан.", ["A window seat, please.", "Window."]),
            t("Here is your boarding pass.", "Ана талони нишастатон.", "Бипурс: кадом дарвоза?", "Which gate?",
              "Кадом дарвоза?", ["What gate?", "Which gate, please?"]),
        ]),
    ]))

# ═════════════════════ 4. Қабул дар меҳмонхона ═════════════════════
made.append(pack("hotel_stay_en_tg", "Hotel check-in", "Қабул дар меҳмонхона", "🏨", 4, L,
    "Шумо ба меҳмонхона омадед: мегӯед, ки ҳуҷра банд кардаед, калид мегиред, дар бораи "
    "субҳона ва Wi-Fi мепурсед ва агар чизе кор накунад, хабар медиҳед.",
    [
        ("Ҳуҷра", [
            w("Hotel", "меҳмонхона", None),
            w("Room", "ҳуҷра", None),
            w("Key", "калид", None),
            w("Reservation", "шаб", None),
            w("Breakfast", "субҳона", None),
            w("Towel", "дастмол", None),
        ]),
        ("Ҳуҷра банд аст", [
            t("Good evening! Do you have a reservation?", "Шоми хуш! Ҳуҷра банд кардаед?", "Бигӯ: ҳа, дорам",
              "Yes, I do.", "Ҳа, дорам.", ["Yes.", "Yes, I have a reservation."]),
            t("For how many nights?", "Барои чанд шаб?", "Бигӯ: ду шаб", "Two nights.", "Ду шаб.",
              ["For two nights.", "Two."]),
            t("Here is your key. Room five.", "Ана калидатон. Ҳуҷраи панҷ.", "Ташаккур гӯй", "Thank you.",
              "Ташаккур.", ["Thanks.", "Thank you very much."]),
        ]),
        ("Калиди ҳуҷра", [
            s("Two nights", "Ду шаб", None),
            s("Checkout time", "Вақти баромадан", None),
            s("The elevator", "Лифт", None),
            s("Free breakfast", "Субҳонаи ройгон", None),
            s("Clean towels", "Дастмолҳои тоза", None),
            s("Wi-Fi password", "Рамзи Wi-Fi", None),
        ]),
        ("Субҳона кай?", [
            t("Anything else?", "Боз чизе?", "Бипурс: субҳона кай?", "When is breakfast?", "Субҳона кай?",
              ["What time is breakfast?", "Breakfast?"]),
            t("From seven to ten.", "Аз ҳафт то даҳ.", "Бипурс: рамзи Wi-Fi?", "The Wi-Fi password?",
              "Рамзи Wi-Fi?", ["What's the Wi-Fi password?", "Wi-Fi, please?"]),
            t("It's on your key card.", "Дар корти калидатон.", "Бигӯ: олӣ, ташаккур", "Great, thank you.",
              "Олӣ, ташаккур.", ["Thanks.", "Okay, thanks."]),
        ]),
        ("Ман ҷой банд кардам", [
            s("I have a reservation.", "Ман ҳуҷра банд кардаам.", None),
            own("My name is ___.", "Номи ман ___.", "Номи худро гӯед.",
                "Your name, please?", "Номатон, лутфан?", "Номи худро гӯед"),
            s("Is breakfast free?", "Субҳона ройгон аст?", None),
            s("What time is checkout?", "Соати чанд ҳуҷраро холӣ кунам?", "Checkout — баромадан аз меҳмонхона."),
            s("Leave my bag here?", "Сумкаамро ин ҷо гузорам?", None),
            s("Where is the elevator?", "Лифт куҷост?", None),
        ]),
        ("Лифт куҷост?", [
            t("Welcome! Your room is ready.", "Хуш омадед! Ҳуҷраатон тайёр.", "Бипурс: соати чанд холӣ кунам?",
              "What time is checkout?", "Соати чанд ҳуҷраро холӣ кунам?", ["When is checkout?", "Checkout time?"]),
            t("At twelve.", "Соати дувоздаҳ.", "Бипурс: лифт куҷост?", "Where is the elevator?", "Лифт куҷост?",
              ["The elevator?", "Where's the elevator?"]),
            t("On the left.", "Дар тарафи чап.", "Ташаккур гӯй", "Thank you.", "Ташаккур.",
              ["Thanks!", "Okay, thanks."]),
        ]),
        ("Душ кор намекунад", [
            s("The shower doesn't work.", "Душ кор намекунад.", None),
            s("The room is cold.", "Ҳуҷра хунук аст.", None),
            s("I need more towels.", "Дастмоли бештар лозим.", None),
            s("Can you help me?", "Ба ман ёрӣ медиҳед?", None),
            s("The key doesn't work.", "Калид кор намекунад.", None),
            s("Can I change rooms?", "Ҳуҷраро иваз карда метавонам?", None),
        ]),
        ("Қабулгоҳ", [
            t("Front desk. How can I help?", "Қабулгоҳ. Чӣ ёрӣ диҳам?", "Бигӯ: душ кор намекунад",
              "The shower doesn't work.", "Душ кор намекунад.", ["My shower is broken.", "The shower is broken."]),
            t("Sorry! What room?", "Бубахшед! Кадом ҳуҷра?", "Бигӯ: ҳуҷраи панҷ", "Room five.", "Ҳуҷраи панҷ.",
              ["Five.", "It's room five."]),
            t("We'll send someone now.", "Ҳозир касеро мефиристем.", "Бигӯ: ташаккур. Дастмоли бештар ҳам лозим",
              "Thanks. I need more towels too.", "Ташаккур. Дастмоли бештар ҳам лозим.",
              ["Thanks. More towels, please.", "Thank you."]),
        ]),
        ("Миссия: меҳмонхона", [
            t("Good evening! Do you have a reservation?", "Шоми хуш! Ҳуҷра банд кардаед?", "Бигӯ: ҳа, дорам",
              "Yes, I do.", "Ҳа, дорам.", ["Yes.", "Yes, I have a reservation."]),
            t("How many nights?", "Чанд шаб?", "Бигӯ: ду шаб", "Two nights.", "Ду шаб.",
              ["For two nights.", "Two."]),
            t("Room five. Here is your key.", "Ҳуҷраи панҷ. Ана калидатон.", "Бипурс: субҳона ройгон аст?",
              "Is breakfast free?", "Субҳона ройгон аст?", ["Free breakfast?", "Is breakfast included?"]),
            t("Yes, from seven to ten.", "Ҳа, аз ҳафт то даҳ.", "Бигӯ: олӣ, ташаккур", "Great, thank you.",
              "Олӣ, ташаккур.", ["Thanks!", "Great!"]),
        ]),
    ]))

# ═════════════════════ 5. Автобус ва метро ═════════════════════
made.append(pack("transit_en_tg", "Bus and metro", "Автобус ва метро", "🚇", 5, L,
    "Шумо дар шаҳр бо автобус ва метро мегардед: чипта мехаред, мепурсед кадом автобус ба "
    "марказ меравад, чанд истгоҳ аст ва аз мусофирон хоҳиш мекунед, ки истгоҳро гӯянд.",
    [
        ("Нақлиёт", [
            w("Bus", "автобус", None),
            w("Metro", "метро", None),
            w("Stop", "истгоҳ", None),
            w("Ticket", "чипта", None),
            w("Line", "хат", "Хати метро ё автобус."),
            w("Map", "харита", None),
        ]),
        ("Ба марказ", [
            t("Hi! Where to?", "Салом! Ба куҷо?", "Бигӯ: ба маркази шаҳр", "To the city center.",
              "Ба маркази шаҳр.", ["City center, please.", "The center."]),
            t("Take bus five.", "Автобуси панҷро савор шавед.", "Бипурс: истгоҳ куҷост?", "Where is the stop?",
              "Истгоҳ куҷост?", ["Where's the bus stop?", "The stop?"]),
            t("Across the street.", "Он тарафи кӯча.", "Ташаккур гӯй", "Thank you.", "Ташаккур.",
              ["Thanks.", "Thank you very much."]),
        ]),
        ("Истгоҳи навбатӣ", [
            s("Bus five", "Автобуси панҷ", None),
            s("Next stop", "Истгоҳи навбатӣ", None),
            s("One ticket", "Як чипта", None),
            s("Red line", "Хати сурх", None),
            s("City center", "Маркази шаҳр", None),
            s("Get off", "Фуромадан", None),
        ]),
        ("Чипта", [
            t("Next!", "Навбатӣ!", "Бигӯ: як чипта, лутфан", "One ticket, please.", "Як чипта, лутфан.",
              ["A ticket, please.", "One, please."]),
            t("Single or return?", "Як тараф ё рафту баргашт?", "Бигӯ: як тараф", "Single.", "Як тараф.",
              ["One way.", "Single, please."]),
            t("Two dollars fifty.", "Ду доллару панҷоҳ сент.", "Бигӯ: марҳамат", "Here you go.", "Марҳамат.",
              ["Here.", "Here it is."]),
        ]),
        ("Чанд истгоҳ?", [
            s("Does it go there?", "Ба он ҷо меравад?", None),
            s("Is this my stop?", "Истгоҳи ман ҳамин аст?", None),
            s("Which line?", "Кадом хат?", None),
            s("How many stops?", "Чанд истгоҳ?", None),
            s("Not my stop!", "Истгоҳи ман нест!", None),
            s("Where is the metro?", "Метро куҷост?", None),
        ]),
        ("Ба марказ меравад?", [
            t("Hello! Can I help you?", "Салом! Ёрӣ диҳам?", "Бипурс: ба он ҷо меравад", "Does it go there?",
              "Ба он ҷо меравад?", ["Downtown?", "Does this bus go downtown?"]),
            t("Yes, it does.", "Ҳа, меравад.", "Бипурс: чанд истгоҳ?", "How many stops?", "Чанд истгоҳ?",
              ["How many?", "How many stops, please?"]),
            t("Four stops.", "Чор истгоҳ.", "Бигӯ: хуб, ташаккур", "Okay, thank you.", "Хуб, ташаккур.",
              ["Thanks.", "Four. Okay."]),
        ]),
        ("Дар автобус", [
            s("Excuse me, my stop!", "Бубахшед, истгоҳи ман!", None),
            s("Can I sit here?", "Ин ҷо шинам?", None),
            s("Is this seat free?", "Ин ҷой холӣ аст?", None),
            s("The bus is late.", "Автобус дер монд.", None),
            s("Here is my card.", "Ана корти ман.", None),
            s("Please tell me.", "Лутфан, ба ман гӯед.", None),
        ]),
        ("Истгоҳи ман?", [
            t("This is Park Street.", "Ин кӯчаи Парк.", "Бипурс: истгоҳи ман ҳамин аст?", "Is this my stop?",
              "Истгоҳи ман ҳамин аст?", ["My stop?", "Is it my stop?"]),
            t("Where are you going?", "Ба куҷо меравед?", "Бигӯ: ба маркази шаҳр", "To the city center.",
              "Ба маркази шаҳр.", ["City center.", "Downtown."]),
            t("Two more stops.", "Боз ду истгоҳ.", "Бигӯ: лутфан, ба ман гӯед", "Please tell me.",
              "Лутфан, ба ман гӯед.", ["Can you tell me?", "Okay. Please tell me."]),
        ]),
        ("Миссия: метро", [
            t("Hi! Where to?", "Салом! Ба куҷо?", "Бигӯ: ба маркази шаҳр", "To the city center.",
              "Ба маркази шаҳр.", ["City center, please.", "Downtown."]),
            t("Take the red line.", "Хати сурхро гиред.", "Бигӯ: хуб. Як чипта, лутфан", "Okay. One ticket, please.",
              "Хуб. Як чипта, лутфан.", ["One ticket, please.", "Okay. A ticket, please."]),
            t("Here. Two dollars fifty.", "Марҳамат. Ду доллару панҷоҳ сент.", "Бипурс: чанд истгоҳ?",
              "How many stops?", "Чанд истгоҳ?", ["How many?", "How many stops, please?"]),
            t("Five stops.", "Панҷ истгоҳ.", "Ташаккур гӯй", "Thank you.", "Ташаккур.",
              ["Thanks!", "Five. Okay, thanks."]),
        ]),
    ]))

# ═════════════════════ 7. Дар қаҳвахона ═════════════════════
made.append(pack("coffee_shop_en_tg", "At a café", "Қаҳвахонаи шаҳр", "☕", 7, L,
    "Шумо дар қаҳвахона қаҳва ва газак фармоиш медиҳед: андоза мегӯед, шир ва шакарро "
    "интихоб мекунед, мегӯед ки ин ҷо мехӯред ё бо худ мебаред, ва пардохт мекунед.",
    [
        ("Қаҳва ва чой", [
            w("Coffee", "қаҳва", None),
            w("Tea", "чой", None),
            w("Cake", "торт", None),
            w("Sugar", "шакар", None),
            w("Cup", "пиёла", None),
            w("Sandwich", "сандвич", None),
        ]),
        ("Як қаҳва", [
            t("Hi! What can I get you?", "Салом! Чӣ биёрам?", "Бигӯ: як қаҳва, лутфан", "A coffee, please.",
              "Як қаҳва, лутфан.", ["One coffee, please.", "Coffee, please."]),
            t("Small or large?", "Хурд ё калон?", "Бигӯ: калон", "Large.", "Калон.",
              ["Large, please.", "A large one."]),
            t("For here or to go?", "Ин ҷо ё бо худ?", "Бигӯ: бо худ", "To go.", "Бо худ.",
              ["To go, please.", "Take away."]),
        ]),
        ("Бе шакар", [
            s("Large coffee", "Қаҳваи калон", None),
            s("No sugar", "Бе шакар", None),
            s("To go", "Бо худ", None),
            s("For here", "Ин ҷо", None),
            s("With milk", "Бо шир", None),
            s("Green tea", "Чойи сабз", None),
        ]),
        ("Бо шир?", [
            t("Milk and sugar?", "Шир ва шакар?", "Бигӯ: бо шир, бе шакар", "With milk, no sugar.",
              "Бо шир, бе шакар.", ["Milk, no sugar.", "Just milk, please."]),
            t("Anything to eat?", "Чизе барои хӯрдан?", "Бигӯ: як сандвич, лутфан", "A sandwich, please.",
              "Як сандвич, лутфан.", ["One sandwich.", "Yes, a sandwich."]),
            t("That's eight dollars.", "Ҳашт доллар мешавад.", "Бигӯ: бо корт, лутфан", "By card, please.",
              "Бо корт, лутфан.", ["Card, please.", "Can I pay by card?"]),
        ]),
        ("Wi-Fi доред?", [
            s("A green tea, please.", "Як чойи сабз, лутфан.", None),
            s("Is this seat free?", "Ин ҷой холӣ аст?", None),
            s("Where is the toilet?", "Ҳоҷатхона куҷост?", None),
            s("Do you have Wi-Fi?", "Wi-Fi доред?", None),
            s("This is very good.", "Ин хеле хуб аст.", None),
            s("Can I sit here?", "Ин ҷо шинам?", None),
        ]),
        ("Рамз дар девор", [
            t("Here is your tea.", "Ана чойи шумо.", "Бипурс: Wi-Fi доред?", "Do you have Wi-Fi?", "Wi-Fi доред?",
              ["Wi-Fi?", "Is there Wi-Fi?"]),
            t("Yes, the password is on the wall.", "Ҳа, рамз дар девор.", "Бипурс: ҳоҷатхона куҷост",
              "Where is the toilet?", "Ҳоҷатхона куҷост?", ["The restroom?", "Where's the restroom?"]),
            t("Over there, on the right.", "Он ҷо, дар тарафи рост.", "Ташаккур гӯй", "Thank you.", "Ташаккур.",
              ["Thanks!", "Okay, thanks."]),
        ]),
        ("Қаҳва хунук", [
            s("This coffee is cold.", "Ин қаҳва хунук аст.", None),
            s("Can I have water?", "Об медиҳед?", None),
            s("A little more milk.", "Каме шири бештар.", None),
            s("It's very sweet.", "Хеле ширин аст.", None),
            s("Another one, please.", "Боз як, лутфан.", None),
            s("Receipt, please.", "Чек, лутфан.", None),
        ]),
        ("Навашро меорам", [
            t("How is your coffee?", "Қаҳваатон чӣ хел?", "Бигӯ: ин қаҳва хунук аст", "This coffee is cold.",
              "Ин қаҳва хунук аст.", ["It's cold.", "Sorry, it's cold."]),
            t("Oh, sorry! I'll make a new one.", "О, бубахшед! Навашро тайёр мекунам.", "Ташаккур гӯй",
              "Thank you.", "Ташаккур.", ["Thanks.", "Thank you so much."]),
            t("Here you go. Better?", "Марҳамат. Беҳтар?", "Бигӯ: ҳа, хеле хуб", "Yes, very good.",
              "Ҳа, хеле хуб.", ["Yes, it's good.", "Much better, thanks."]),
        ]),
        ("Миссия: қаҳвахона", [
            t("Hi! What can I get you?", "Салом! Чӣ биёрам?", "Бигӯ: як қаҳва бо шир, лутфан",
              "A coffee with milk, please.", "Як қаҳва бо шир, лутфан.", ["Coffee with milk.", "One coffee with milk."]),
            t("Small or large?", "Хурд ё калон?", "Бигӯ: калон", "Large.", "Калон.",
              ["Large, please.", "A large one."]),
            t("For here or to go?", "Ин ҷо ё бо худ?", "Бигӯ: ин ҷо", "For here.", "Ин ҷо.",
              ["Here, please.", "For here, please."]),
            t("Four dollars, please.", "Чор доллар, лутфан.", "Бигӯ: бо корт, лутфан", "By card, please.",
              "Бо корт, лутфан.", ["Card, please.", "Here's my card."]),
        ]),
    ]))

# ═════════════════════ 8. Дар супермаркет ═════════════════════
made.append(pack("supermarket_en_tg", "At the supermarket", "Дар супермаркет", "🛒", 8, L,
    "Шумо дар супермаркет харид мекунед: мепурсед, ки чиз дар куҷост, гӯшти ҳалол меҷӯед, "
    "нархро мефаҳмед ва дар касса пардохт мекунед.",
    [
        ("Харид", [
            w("Rice", "биринҷ", None),
            w("Eggs", "тухм", None),
            w("Meat", "гӯшт", None),
            w("Fruit", "мева", None),
            w("Cart", "аробача", None),
            w("Price", "нарх", None),
        ]),
        ("Биринҷ куҷост?", [
            t("Hi! Can I help you?", "Салом! Ёрӣ диҳам?", "Бипурс: биринҷ куҷост?", "Where is the rice?",
              "Биринҷ куҷост?", ["Rice?", "Where's the rice?"]),
            t("Aisle four.", "Қатори чор.", "Бипурс: ва тухм?", "And eggs?", "Ва тухм?",
              ["Where are the eggs?", "And the eggs?"]),
            t("Next to the milk.", "Назди шир.", "Ташаккур гӯй", "Thank you.", "Ташаккур.",
              ["Thanks.", "Thank you very much."]),
        ]),
        ("Гӯшти ҳалол", [
            s("Halal meat", "Гӯшти ҳалол", None),
            s("Fresh fruit", "Меваи тоза", None),
            s("Twelve eggs", "Дувоздаҳ тухм", None),
            s("Aisle four", "Қатори чор", None),
            s("Too expensive", "Хеле қимат", None),
            s("Small bag", "Халтаи хурд", None),
        ]),
        ("Як кило чанд?", [
            t("Can I help you find something?", "Ёрӣ диҳам, ки ёбед?", "Бипурс: гӯшти ҳалол доред?",
              "Do you have halal meat?", "Гӯшти ҳалол доред?", ["Halal meat?", "Is there halal meat?"]),
            t("Yes, in the back.", "Ҳа, дар қафо.", "Бипурс: як кило чанд?", "How much is one kilo?",
              "Як кило чанд?", ["How much per kilo?", "How much?"]),
            t("Twelve dollars.", "Дувоздаҳ доллар.", "Бигӯ: хеле қимат", "Too expensive.", "Хеле қимат.",
              ["It's expensive.", "That's too much."]),
        ]),
        ("Тоза аст?", [
            s("Where are the eggs?", "Тухм куҷост?", None),
            s("Is this fresh?", "Ин тоза аст?", None),
            s("How much is this?", "Ин чанд пул?", None),
            s("I need a cart.", "Ба ман аробача лозим.", None),
            s("Is it on sale?", "Бо тахфиф аст?", None),
            s("Where do I pay?", "Куҷо пардохт кунам?", None),
        ]),
        ("Ду кило", [
            t("Good morning!", "Субҳ ба хайр!", "Бипурс: ин тоза аст?", "Is this fresh?", "Ин тоза аст?",
              ["Is it fresh?", "Fresh?"]),
            t("Yes, from today.", "Ҳа, аз имрӯз.", "Бипурс: ин чанд пул?", "How much is this?", "Ин чанд пул?",
              ["How much?", "What's the price?"]),
            t("Three dollars a kilo.", "Се доллар як кило.", "Бигӯ: ду кило, лутфан", "Two kilos, please.",
              "Ду кило, лутфан.", ["Two kilos.", "I'll take two kilos."]),
        ]),
        ("Дар касса", [
            s("I have a bag.", "Ман халта дорам.", None),
            s("Card is okay?", "Корт мешавад?", None),
            s("I need milk.", "Ба ман шир лозим.", None),
            s("Wait, please.", "Лутфан, сабр кунед.", None),
            s("Is this halal?", "Ин ҳалол аст?", None),
            s("Where is the exit?", "Баромадгоҳ куҷост?", None),
        ]),
        ("Ширро фаромӯш кардам", [
            t("Hi! Do you need a bag?", "Салом! Халта лозим?", "Бигӯ: не, ман халта дорам", "No, I have a bag.",
              "Не, ман халта дорам.", ["No, thanks. I have one.", "No, thank you."]),
            t("Okay. Twenty-five dollars.", "Хуб. Бисту панҷ доллар.", "Бигӯ: лутфан, сабр кунед. Ба ман шир лозим",
              "Wait, please. I need milk.", "Лутфан, сабр кунед. Ба ман шир лозим.",
              ["Sorry, I forgot milk.", "Wait, I forgot milk."]),
            t("No problem. I'll wait.", "Мушкил нест. Интизор мешавам.", "Ташаккур гӯй", "Thank you.", "Ташаккур.",
              ["Thanks!", "Thank you so much."]),
        ]),
        ("Миссия: супермаркет", [
            t("Hi! Can I help you?", "Салом! Ёрӣ диҳам?", "Бипурс: гӯшти ҳалол доред?", "Do you have halal meat?",
              "Гӯшти ҳалол доред?", ["Halal meat?", "Is there halal meat?"]),
            t("Yes, in aisle seven.", "Ҳа, дар қатори ҳафт.", "Бипурс: як кило чанд?", "How much is one kilo?",
              "Як кило чанд?", ["How much per kilo?", "How much?"]),
            t("Ten dollars. It's on sale.", "Даҳ доллар. Бо тахфиф.", "Бигӯ: олӣ. Ду кило, лутфан",
              "Great. Two kilos, please.", "Олӣ. Ду кило, лутфан.", ["Two kilos, please.", "Great!"]),
            t("Anything else?", "Боз чизе?", "Бипурс: куҷо пардохт кунам?", "Where do I pay?",
              "Куҷо пардохт кунам?", ["Where is the cashier?", "Where can I pay?"]),
        ]),
    ]))

# ═════════════════════ 9. Телефон ва интернет ═════════════════════
made.append(pack("phone_plan_en_tg", "Phone and internet", "Телефон ва интернет", "📶", 9, L,
    "Шумо SIM-корт мехаред, тарифро интихоб мекунед, ба ҳисоб пул меандозед ва агар "
    "телефон ё интернет кор накунад, ёрӣ мепурсед.",
    [
        ("Телефон", [
            w("Phone", "телефон", None),
            w("Internet", "интернет", None),
            w("Plan", "тариф", None),
            w("Data", "интернети мобилӣ", None),
            w("Charger", "заряднок", None),
            w("SIM", "батарея", None),
        ]),
        ("SIM-корт", [
            t("Hi! How can I help?", "Салом! Чӣ ёрӣ диҳам?", "Бигӯ: ба ман SIM-корт лозим", "I need a SIM card.",
              "Ба ман SIM-корт лозим.", ["A SIM card, please.", "SIM card, please."]),
            t("Okay. Monthly plan?", "Хуб. Тарифи моҳона?", "Бигӯ: ҳа. Чанд пул?", "Yes. How much?",
              "Ҳа. Чанд пул?", ["How much is it?", "Yes, how much?"]),
            t("Twenty dollars a month.", "Моҳе бист доллар.", "Бигӯ: хуб, инро мехоҳам", "Okay, I want it.",
              "Хуб, инро мехоҳам.", ["I'll take it.", "Okay."]),
        ]),
        ("Тарифи моҳона", [
            s("SIM card", "SIM-корт", None),
            s("Monthly plan", "Тарифи моҳона", None),
            s("More data", "Интернети бештар", None),
            s("No signal", "Алоқа нест", None),
            s("Phone charger", "Заряднок", None),
            s("Low battery", "Заряд кам", None),
        ]),
        ("Интернети бештар", [
            t("This plan has ten gigs.", "Ин тариф даҳ гигабайт дорад.", "Бипурс: интернети бештар доред?",
              "More data?", "Интернети бештар?", ["Do you have more data?", "Is there more data?"]),
            t("Yes, unlimited for thirty.", "Ҳа, беҳадд барои сӣ доллар.", "Бигӯ: хуб, онро мехоҳам",
              "Okay, I want that.", "Хуб, онро мехоҳам.", ["I'll take it.", "Okay, that one."]),
            t("Your passport, please.", "Шиносномаатон, лутфан.", "Бигӯ: марҳамат", "Here you go.", "Марҳамат.",
              ["Here it is.", "Here."]),
        ]),
        ("Алоқа нест", [
            s("My phone doesn't work.", "Телефонам кор намекунад.", None),
            s("There's no signal.", "Алоқа нест.", None),
            s("The internet is slow.", "Интернет суст аст.", None),
            s("I can't call.", "Занг зада наметавонам.", None),
            s("My battery is low.", "Заряди телефонам кам.", None),
            s("A charger, please?", "Пуркунак, лутфан?", None),
        ]),
        ("Ҳоло кор мекунад", [
            t("What's the problem?", "Мушкил чист?", "Бигӯ: алоқа нест", "There's no signal.", "Алоқа нест.",
              ["No signal.", "My phone has no signal."]),
            t("Restart your phone, please.", "Телефонро хомӯш карда, боз фаъол кунед.", "Бигӯ: хуб, як дақиқа",
              "Okay, one minute.", "Хуб, як дақиқа.", ["Okay.", "One moment."]),
            t("Is it okay now?", "Ҳоло хуб?", "Бигӯ: ҳа, ҳоло кор мекунад", "Yes, it works now.",
              "Ҳа, ҳоло кор мекунад.", ["Yes, thank you!", "It works now."]),
        ]),
        ("Пул андохтан", [
            s("More data, please.", "Интернети бештар, лутфан.", "Top up — ба ҳисоби телефон пул андохтан."),
            s("Ten dollars, please.", "Даҳ доллар, лутфан.", None),
            s("What's my number?", "Рақами ман чанд?", None),
            s("Call me, please.", "Ба ман занг занед, лутфан.", None),
            s("Send me a message.", "Ба ман паём фиристед.", None),
            s("I need a charger.", "Ба ман заряднок лозим.", None),
        ]),
        ("Даҳ доллар", [
            t("Hi! Can I help?", "Салом! Ёрӣ диҳам?", "Бипурс: интернети бештар, лутфан", "More data, please.",
              "Интернети бештар, лутфан.", ["Top up, please.", "I want to top up."]),
            t("Sure. How much?", "Албатта. Чанд?", "Бигӯ: даҳ доллар, лутфан", "Ten dollars, please.",
              "Даҳ доллар, лутфан.", ["Ten dollars, please.", "Ten dollars."]),
            t("Done! Anything else?", "Тайёр! Боз чизе?", "Бигӯ: ба ман заряднок лозим", "I need a charger.",
              "Ба ман заряднок лозим.", ["A charger, please.", "Do you have a charger?"]),
        ]),
        ("Миссия: SIM-корт", [
            t("Hi! How can I help?", "Салом! Чӣ ёрӣ диҳам?", "Бигӯ: ба ман SIM-корт лозим", "I need a SIM card.",
              "Ба ман SIM-корт лозим.", ["A SIM card, please.", "SIM card, please."]),
            t("Which plan? Ten gigs or unlimited?", "Кадом тариф? Даҳ гигабайт ё беҳадд?", "Бипурс: чанд пул?",
              "How much?", "Чанд пул?", ["How much is it?", "What's the price?"]),
            t("Twenty or thirty dollars.", "Бист ё сӣ доллар.", "Бигӯ: бист, лутфан", "Twenty, please.",
              "Бист, лутфан.", ["The twenty dollar plan.", "Twenty."]),
            t("Okay. Your passport, please.", "Хуб. Шиносномаатон, лутфан.", "Бигӯ: марҳамат", "Here you go.",
              "Марҳамат.", ["Here it is.", "Here."]),
        ]),
    ]))

# ═════════════════════ 11. Пул ва мубодила ═════════════════════
made.append(pack("money_en_tg", "Money and exchange", "Пул ва мубодила", "💱", 11, L,
    "Шумо пул иваз мекунед, ба оила пул мефиристед ва агар банкомат кортро нигоҳ дорад, "
    "ба бонк занг мезанед. Қурбро мепурсед, маблағро мегӯед ва шиносномаро нишон медиҳед.",
    [
        ("Пул", [
            w("Money", "пул", None),
            w("Exchange", "иваз кардан", None),
            w("ATM", "банкомат", None),
            w("Rate", "қурб", "Нархи асъор: як доллар чанд сомонӣ."),
            w("Send", "фиристодан", None),
            w("Fee", "комиссия", "Пули иловагӣ барои хизмат."),
        ]),
        ("Иваз кардани пул", [
            t("Hello! How can I help?", "Салом! Чӣ ёрӣ диҳам?", "Бигӯ: пул иваз кардан мехоҳам",
              "I want to exchange money.", "Пул иваз кардан мехоҳам.", ["Exchange money, please.", "I need to change money."]),
            t("Dollars to rubles?", "Доллар ба рубл?", "Бигӯ: не, доллар ба сомонӣ", "No, dollars to somoni.",
              "Не, доллар ба сомонӣ.", ["Dollars to somoni.", "No. Somoni, please."]),
            t("How much?", "Чанд?", "Бигӯ: сад доллар", "One hundred dollars.", "Сад доллар.",
              ["A hundred dollars.", "One hundred."]),
        ]),
        ("Қурби асъор", [
            s("Hundred dollars", "Сад доллар", None),
            s("Exchange rate", "Қурби асъор", None),
            s("Send money", "Пул фиристодан", None),
            s("No fee", "Бе комиссия", None),
            s("My family", "Оилаам", None),
            s("Cash only", "Танҳо нақд", None),
        ]),
        ("Қурб чанд?", [
            t("Good morning!", "Субҳ ба хайр!", "Бипурс: қурб чанд?", "What's the rate?", "Қурб чанд?",
              ["The exchange rate?", "What's the rate today?"]),
            t("Ten somoni for one dollar.", "Даҳ сомонӣ барои як доллар.", "Бипурс: комиссия ҳаст?",
              "Is there a fee?", "Комиссия ҳаст?", ["Any fee?", "What's the fee?"]),
            t("No fee today.", "Имрӯз комиссия нест.", "Бигӯ: олӣ", "Great!", "Олӣ!",
              ["Good.", "Great, thanks!"]),
        ]),
        ("Пул ба хона", [
            s("Send money home.", "Ба хона пул фиристам.", None),
            s("To Tajikistan, please.", "Ба Тоҷикистон, лутфан.", None),
            s("When does it arrive?", "Кай мерасад?", None),
            s("Here is my passport.", "Ана шиносномаи ман.", None),
            s("What's the fee?", "Комиссия чанд?", None),
            s("Where is an ATM?", "Банкомат куҷост?", None),
        ]),
        ("Ба Тоҷикистон", [
            t("Next, please.", "Навбатӣ, лутфан.", "Бигӯ: ба хона пул фиристодан мехоҳам",
              "I want to send money home.", "Ба хона пул фиристодан мехоҳам.", ["Send money, please.", "I want to send money."]),
            t("Where to?", "Ба куҷо?", "Бигӯ: ба Тоҷикистон, лутфан", "To Tajikistan, please.",
              "Ба Тоҷикистон, лутфан.", ["Tajikistan.", "To Tajikistan."]),
            t("Okay. Your passport, please.", "Хуб. Шиносномаатон, лутфан.", "Бигӯ: ана шиносномаи ман",
              "Here is my passport.", "Ана шиносномаи ман.", ["Here you go.", "Here it is."]),
        ]),
        ("Банкомат", [
            s("The ATM doesn't work.", "Банкомат кор намекунад.", None),
            s("I need cash.", "Ба ман пули нақд лозим.", None),
            s("Is it all here?", "Ҳамааш ҳаст?", None),
            s("Is it safe?", "Бехатар аст?", None),
            s("Receipt, please.", "Чек, лутфан.", None),
            s("Thank you for help.", "Барои ёрӣ ташаккур.", None),
        ]),
        ("Кортам монд", [
            t("Bank, hello. How can I help?", "Бонк, салом. Чӣ ёрӣ диҳам?", "Бигӯ: банкомат кор намекунад",
              "The ATM doesn't work.", "Банкомат кор намекунад.", ["The ATM has my card.", "My card is in the ATM."]),
            t("Which ATM?", "Кадом банкомат?", "Бигӯ: дар кӯчаи Мейн", "On Main Street.", "Дар кӯчаи Мейн.",
              ["Main Street.", "The one on Main Street."]),
            t("Okay. Come tomorrow with your passport.", "Хуб. Фардо бо шиноснома биёед.", "Бигӯ: хуб, ташаккур",
              "Okay, thank you.", "Хуб, ташаккур.", ["Thanks.", "Okay. Tomorrow."]),
        ]),
        ("Миссия: пул ба хона", [
            t("Hello! How can I help?", "Салом! Чӣ ёрӣ диҳам?", "Бигӯ: ба хона пул фиристодан мехоҳам",
              "I want to send money home.", "Ба хона пул фиристодан мехоҳам.",
              ["Send money home, please.", "I want to send money."]),
            t("How much?", "Чанд?", "Бигӯ: дусад доллар", "Two hundred dollars.", "Дусад доллар.",
              ["Two hundred.", "Two hundred, please."]),
            t("The fee is five dollars.", "Комиссия панҷ доллар.", "Бипурс: кай мерасад?", "When does it arrive?",
              "Кай мерасад?", ["When does it get there?", "How long?"]),
            t("In one hour.", "Пас аз як соат.", "Бигӯ: олӣ. Ана шиносномаи ман", "Great. Here is my passport.",
              "Олӣ. Ана шиносномаи ман.", ["Great!", "Here is my passport."]),
        ]),
    ]))

# ═════════════════════ 12. Дар дорухона ═════════════════════
made.append(pack("pharmacy_en_tg", "At the pharmacy", "Дар дорухона", "💊", 12, L,
    "Шумо ба дорухона меравед: мегӯед, ки чӣ дард мекунад, дору мепурсед, мефаҳмед, ки "
    "чанд маротиба нӯшед, ва рецептро нишон медиҳед.",
    [
        ("Дорухона", [
            w("Pharmacy", "дорухона", None),
            w("Medicine", "дору", None),
            w("Pills", "ҳаб", None),
            w("Headache", "сардард", None),
            w("Prescription", "рецепт", "Коғази духтур барои дору."),
            w("Cream", "крем", None),
        ]),
        ("Сарам дард мекунад", [
            t("Hi! Can I help you?", "Салом! Ёрӣ диҳам?", "Бигӯ: сарам дард мекунад", "I have a headache.",
              "Сарам дард мекунад.", ["My head hurts.", "Headache."]),
            t("Take these pills.", "Ин ҳабҳоро нӯшед.", "Бипурс: чанд маротиба?", "How often?", "Чанд маротиба?",
              ["How many times?", "How often, please?"]),
            t("Two times a day.", "Рӯзе ду маротиба.", "Бигӯ: хуб, ташаккур", "Okay, thank you.",
              "Хуб, ташаккур.", ["Thanks.", "Two times. Okay."]),
        ]),
        ("Сулфа", [
            s("Bad cough", "Сулфаи сахт", None),
            s("Sore throat", "Гулӯдард", None),
            s("Two times", "Ду маротиба", None),
            s("After food", "Баъди хӯрок", None),
            s("For kids", "Барои кӯдакон", None),
            s("My prescription", "Рецепти ман", None),
        ]),
        ("Баъди хӯрок", [
            t("What's wrong?", "Чӣ шуд?", "Бигӯ: сулфа ва гулӯдард", "A cough and a sore throat.",
              "Сулфа ва гулӯдард.", ["I have a bad cough.", "My throat hurts."]),
            t("Take this syrup.", "Ин шарбатро нӯшед.", "Бипурс: пеш ё баъди хӯрок?", "Before or after food?",
              "Пеш ё баъди хӯрок?", ["After food?", "With food?"]),
            t("After food. One spoon.", "Баъди хӯрок. Як қошуқ.", "Бигӯ: фаҳмидам", "Got it.", "Фаҳмидам.",
              ["Okay.", "One spoon. Okay."]),
        ]),
        ("Таб дорам", [
            s("I have a fever.", "Ман таб дорам.", None),
            s("I have a cough.", "Ман сулфа дорам.", None),
            s("My stomach hurts.", "Шикамам дард мекунад.", None),
            s("Is it for kids?", "Барои кӯдакон аст?", None),
            s("Need a prescription?", "Рецепт лозим?", None),
            s("Here is my prescription.", "Ана рецепти ман.", None),
        ]),
        ("Рецепт", [
            t("Hello! What do you need?", "Салом! Чӣ лозим?", "Бигӯ: ана рецепти ман", "Here is my prescription.",
              "Ана рецепти ман.", ["My prescription.", "This prescription, please."]),
            t("Okay. Ten minutes, please.", "Хуб. Даҳ дақиқа, лутфан.", "Бипурс: чанд пул?", "How much is it?",
              "Чанд пул?", ["How much?", "What's the price?"]),
            t("Fifteen dollars.", "Понздаҳ доллар.", "Бигӯ: бо корт, лутфан", "By card, please.",
              "Бо корт, лутфан.", ["Card, please.", "Here's my card."]),
        ]),
        ("Кӯдак бемор", [
            s("My child is sick.", "Кӯдакам бемор аст.", None),
            s("She has a fever.", "Ӯ таб дорад.", None),
            s("Is it strong?", "Сахт аст?", None),
            s("How many pills?", "Чандто ҳаб?", None),
            s("I feel better.", "Худро беҳтар ҳис мекунам.", None),
            s("Thanks for your help.", "Барои ёриатон ташаккур.", None),
        ]),
        ("Чандсола?", [
            t("Hi! How can I help?", "Салом! Чӣ ёрӣ диҳам?", "Бигӯ: кӯдакам бемор аст", "My child is sick.",
              "Кӯдакам бемор аст.", ["My kid is sick.", "My child has a fever."]),
            t("How old is the child?", "Кӯдак чандсола аст?", "Бигӯ: панҷсола", "Five years old.", "Панҷсола.",
              ["Five.", "She is five."]),
            t("Give this, two times a day.", "Инро рӯзе ду маротиба диҳед.", "Бигӯ: барои ёриатон ташаккур",
              "Thanks for your help.", "Барои ёриатон ташаккур.", ["Thank you!", "Thank you very much."]),
        ]),
        ("Миссия: дорухона", [
            t("Hi! What's wrong?", "Салом! Чӣ шуд?", "Бигӯ: ман таб ва сулфа дорам", "I have a fever and a cough.",
              "Ман таб ва сулфа дорам.", ["I have a fever.", "Fever and cough."]),
            t("Take these pills.", "Ин ҳабҳоро нӯшед.", "Бипурс: чанд маротиба?", "How often?", "Чанд маротиба?",
              ["How many times?", "How often, please?"]),
            t("Three times a day, after food.", "Рӯзе се маротиба, баъди хӯрок.", "Бипурс: чанд пул?",
              "How much is it?", "Чанд пул?", ["How much?", "What's the price?"]),
            t("Eight dollars. Feel better!", "Ҳашт доллар. Шифо ёбед!", "Ташаккур гӯй", "Thank you.", "Ташаккур.",
              ["Thanks!", "Thank you so much."]),
        ]),
    ]))

# ═════════════════════ 13. Дар почта ═════════════════════
made.append(pack("post_en_tg", "At the post office", "Дар почта", "📮", 13, L,
    "Шумо ба оила баста мефиристед: мегӯед ба кадом кишвар, нарх ва вақтро мепурсед, "
    "варақаро пур мекунед ва мегӯед, ки дарунаш чист.",
    [
        ("Почта", [
            w("Package", "баста", None),
            w("Letter", "мактуб", None),
            w("Stamp", "марка", None),
            w("Address", "суроға", None),
            w("Form", "варақа", None),
            w("Box", "қуттӣ", None),
        ]),
        ("Баста ба хона", [
            t("Hi! What are you sending?", "Салом! Чӣ мефиристед?", "Бигӯ: баста ба Тоҷикистон",
              "A package to Tajikistan.", "Баста ба Тоҷикистон.", ["To Tajikistan.", "This package, to Tajikistan."]),
            t("Put it here, please.", "Ин ҷо гузоред, лутфан.", "Бипурс: чанд пул?", "How much?", "Чанд пул?",
              ["How much is it?", "How much to send it?"]),
            t("Forty dollars.", "Чил доллар.", "Бипурс: кай мерасад?", "When does it arrive?", "Кай мерасад?",
              ["How long?", "When will it arrive?"]),
        ]),
        ("Бо ҳавопаймо", [
            s("Two kilos", "Ду кило", None),
            s("This form", "Ин варақа", None),
            s("By air", "Бо ҳавопаймо", None),
            s("Fast mail", "Почтаи тез", None),
            s("One stamp", "Як марка", None),
            s("Big box", "Қуттии калон", None),
        ]),
        ("Варақа", [
            t("Please fill in this form.", "Лутфан, ин варақаро пур кунед.", "Бипурс: ин ҷо?", "Here?", "Ин ҷо?",
              ["Write here?", "On this line?"]),
            t("Yes. Name and address.", "Ҳа. Ном ва суроға.", "Бигӯ: хуб", "Okay.", "Хуб.",
              ["Okay, sure.", "Sure."]),
            t("What's in the box?", "Дар қуттӣ чӣ ҳаст?", "Бигӯ: либос ва китоб", "Clothes and books.",
              "Либос ва китоб.", ["Clothes.", "Gifts for my family."]),
        ]),
        ("Барои оилаам", [
            s("Send this, please.", "Инро фиристед, лутфан.", None),
            s("It's for my family.", "Барои оилаам аст.", None),
            s("How many days?", "Чанд рӯз?", None),
            s("Is it fast?", "Тез аст?", None),
            s("I need a box.", "Ба ман қуттӣ лозим.", None),
            s("One stamp, please.", "Як марка, лутфан.", None),
        ]),
        ("Кадомаш тез?", [
            t("Air or ground?", "Бо ҳавопаймо ё бо замин?", "Бипурс: кадомаш тез аст?", "Which is fast?",
              "Кадомаш тез аст?", ["Which is faster?", "Which one is fast?"]),
            t("Air. Ten days.", "Бо ҳавопаймо. Даҳ рӯз.", "Бигӯ: бо ҳавопаймо, лутфан", "Air, please.",
              "Бо ҳавопаймо, лутфан.", ["By air.", "By air, please."]),
            t("Okay. Sixty dollars.", "Хуб. Шаст доллар.", "Бигӯ: марҳамат", "Here you go.", "Марҳамат.",
              ["Here.", "Here, sixty dollars."]),
        ]),
        ("Шикастанӣ", [
            s("I have a package.", "Ман баста дорам.", None),
            s("When does it arrive?", "Кай мерасад?", "Яъне дар интернет бинам, ки баста куҷост."),
            s("What's the number?", "Рақам чанд?", None),
            s("It's very heavy.", "Хеле вазнин аст.", None),
            s("Please be careful.", "Лутфан, эҳтиёт кунед.", None),
            s("It's glass.", "Шиша аст.", None),
        ]),
        ("Пайгирӣ", [
            t("What's inside?", "Дарунаш чист?", "Бигӯ: шиша аст. Лутфан, эҳтиёт кунед",
              "It's glass. Please be careful.", "Шиша аст. Лутфан, эҳтиёт кунед.",
              ["Please be careful.", "Fragile, please."]),
            t("Okay. Here is your receipt.", "Хуб. Ана чекатон.", "Бипурс: кай мерасад",
              "When does it arrive?", "Кай мерасад?", ["Can I check it online?", "Tracking?"]),
            t("Yes, the number is on top.", "Ҳа, рақам дар боло.", "Ташаккур гӯй", "Thank you.", "Ташаккур.",
              ["Thanks.", "Okay, thank you."]),
        ]),
        ("Миссия: почта", [
            t("Next! What are you sending?", "Навбатӣ! Чӣ мефиристед?", "Бигӯ: баста ба Тоҷикистон",
              "A package to Tajikistan.", "Баста ба Тоҷикистон.", ["To Tajikistan.", "This package to Tajikistan."]),
            t("Air or ground?", "Бо ҳавопаймо ё бо замин?", "Бипурс: кадомаш тез аст?", "Which is fast?",
              "Кадомаш тез аст?", ["Which is faster?", "Which one is fast?"]),
            t("Air. Ten days, sixty dollars.", "Бо ҳавопаймо. Даҳ рӯз, шаст доллар.", "Бигӯ: бо ҳавопаймо, лутфан",
              "Air, please.", "Бо ҳавопаймо, лутфан.", ["By air.", "By air, please."]),
            t("Please fill in this form.", "Лутфан, ин варақаро пур кунед.", "Бигӯ: хуб. Шиша аст",
              "Okay. It's glass.", "Хуб. Шиша аст.", ["Okay.", "Sure. It's fragile."]),
        ]),
    ]))

# ═════════════════════ 15. Ҳамсояҳо ═════════════════════
made.append(pack("neighbors_en_tg", "Neighbors", "Ҳамсояҳо", "🏠", 15, L,
    "Шумо бо ҳамсояҳо шинос мешавед, бастаро мегиред, чизе қарз мегиред ва агар шаб садо "
    "баланд бошад, бо хушмуомилагӣ хоҳиш мекунед, ки оромтар бошанд.",
    [
        ("Ҳамсоя", [
            w("Neighbor", "ҳамсоя", None),
            w("Door", "дар", None),
            w("Noise", "садо", None),
            w("Party", "зиёфат", None),
            w("Package", "баста", None),
            w("Upstairs", "дар боло", None),
        ]),
        ("Ҳамсояи нав", [
            t("Hi! Are you new here?", "Салом! Шумо навед?", "Бигӯ: ҳа, ман дар хонаи панҷ зиндагӣ мекунам",
              "Yes, I live in apartment five.", "Ҳа, ман дар хонаи панҷ зиндагӣ мекунам.",
              ["Yes, I'm new.", "Yes. Apartment five."]),
            t("Welcome! I'm Sarah.", "Хуш омадед! Ман Сара.", "Бигӯ: аз шиносоӣ хурсандам", "Nice to meet you.",
              "Аз шиносоӣ хурсандам.", ["Nice to meet you too.", "Hi Sarah! Nice to meet you."]),
            t("If you need help, ask me.", "Агар ёрӣ лозим бошад, аз ман пурсед.", "Ташаккур гӯй",
              "Thank you very much.", "Ташаккури зиёд.", ["Thanks!", "Thank you."]),
        ]),
        ("Хонаи панҷ", [
            s("New neighbor", "Ҳамсояи нав", None),
            s("Apartment five", "Хонаи панҷ", None),
            s("Too loud", "Хеле баланд", None),
            s("Late night", "Шаби дер", None),
            s("Your package", "Бастаи шумо", None),
            s("Come in", "Дароед", None),
        ]),
        ("Бастаи шумо", [
            t("Hi! Is this your package?", "Салом! Ин бастаи шумост?", "Бигӯ: ҳа! Ташаккур", "Yes! Thank you.",
              "Ҳа! Ташаккур.", ["Oh, yes. Thanks!", "Yes, it's mine."]),
            t("It was at my door.", "Назди дари ман буд.", "Бигӯ: шумо хеле меҳрубонед", "You're very kind.",
              "Шумо хеле меҳрубонед.", ["That's very kind.", "Thank you so much."]),
            t("No problem!", "Ҳеҷ гап не!", "Бигӯ: дароед, чой нӯшед", "Come in for tea?", "Дароед, чой нӯшед?",
              ["Would you like tea?", "Come in, please."]),
        ]),
        ("Ёрӣ медиҳед?", [
            s("I live upstairs.", "Ман дар боло зиндагӣ мекунам.", None),
            s("Nice to meet you.", "Аз шиносоӣ хурсандам.", None),
            s("Can you help me?", "Ба ман ёрӣ медиҳед?", None),
            s("Can I take this?", "Инро гирифта метавонам?", "Borrow — чизеро муваққатан гирифтан."),
            s("Welcome to the building!", "Ба бино хуш омадед!", None),
            s("Back tomorrow, okay?", "Фардо бармегардонам, хуб?", None),
        ]),
        ("Нардбон", [
            t("Hi! Can I help you?", "Салом! Ёрӣ диҳам?", "Бигӯ: ҳа. Инро гирифта метавонам", "Yes. Can I take this?",
              "Ҳа. Инро гирифта метавонам?", ["Can I borrow it?", "Yes, please. Can I borrow this?"]),
            t("The ladder? Sure.", "Нардбон? Албатта.", "Бигӯ: фардо бармегардонам, хуб", "Back tomorrow, okay?",
              "Фардо бармегардонам, хуб?", ["Back tomorrow.", "I'll bring it back tomorrow."]),
            t("No rush.", "Шитоб накунед.", "Ташаккур гӯй", "Thank you so much.", "Ташаккури зиёд.",
              ["Thanks!", "Thank you."]),
        ]),
        ("Садо", [
            s("It's very late.", "Хеле дер аст.", None),
            s("My kids are sleeping.", "Кӯдаконам хобанд.", None),
            s("Please be quiet.", "Лутфан, оромтар.", None),
            s("The music is loud.", "Мусиқӣ баланд аст.", None),
            s("Sorry about the noise.", "Барои садо бубахшед.", None),
            s("No problem at all.", "Ҳеҷ гап не.", None),
        ]),
        ("Шаби дер", [
            t("Hi! Is everything okay?", "Салом! Ҳама хуб?", "Бигӯ: мусиқӣ баланд аст. Кӯдаконам хобанд",
              "The music is loud. My kids are sleeping.", "Мусиқӣ баланд аст. Кӯдаконам хобанд.",
              ["The music is loud.", "Please, my kids are sleeping."]),
            t("Oh, I'm sorry! We have a party.", "О, бубахшед! Мо зиёфат дорем.", "Бигӯ: лутфан, оромтар",
              "Please be quiet.", "Лутфан, оромтар.", ["A little quieter, please.", "Please, it's late."]),
            t("Of course. Sorry about the noise.", "Албатта. Барои садо бубахшед.", "Бигӯ: ҳеҷ гап не. Ташаккур",
              "No problem at all. Thanks.", "Ҳеҷ гап не. Ташаккур.", ["No problem.", "Thank you."]),
        ]),
        ("Миссия: ҳамсоя", [
            t("Hi! Are you new here?", "Салом! Шумо навед?", "Бигӯ: ҳа, ман дар боло зиндагӣ мекунам",
              "Yes, I live upstairs.", "Ҳа, ман дар боло зиндагӣ мекунам.", ["Yes, I'm new.", "Yes. I live upstairs."]),
            t("Welcome! I'm Sarah, from apartment two.", "Хуш омадед! Ман Сара, аз хонаи ду.",
              "Бигӯ: аз шиносоӣ хурсандам", "Nice to meet you.", "Аз шиносоӣ хурсандам.",
              ["Nice to meet you too.", "Hi! Nice to meet you."]),
            t("This package was at my door.", "Ин баста назди дари ман буд.", "Бигӯ: ташаккур! Шумо хеле меҳрубонед",
              "Thank you! You're very kind.", "Ташаккур! Шумо хеле меҳрубонед.",
              ["Thanks! That's very kind.", "Thank you so much!"]),
            t("No problem. See you around!", "Ҳеҷ гап не. То дидор!", "Бигӯ: то дидор", "See you!", "То дидор!",
              ["Bye!", "See you later!"]),
        ]),
    ]))

# ═════════════════════ 17. Гум шудам ═════════════════════
made.append(pack("lost_en_tg", "Lost in the city", "Гум шудам", "🧭", 17, L,
    "Шумо дар шаҳри нав роҳро гум кардед ва телефонатон хомӯш шуд. Бо хушмуомилагӣ аз "
    "одамон мепурсед, ки куҷо ҳастед, роҳро мефаҳмед ва хоҳиш мекунед, ки нависанд.",
    [
        ("Шаҳр", [
            w("Map", "харита", None),
            w("Lost", "гум", None),
            w("Station", "истгоҳ, вокзал", None),
            w("Park", "боғ", None),
            w("Near", "наздик", None),
            w("Far", "дур", None),
        ]),
        ("Ман гум шудам", [
            t("Are you okay?", "Шумо хубед?", "Бигӯ: ман гум шудам", "I'm lost.", "Ман гум шудам.",
              ["I'm lost, sorry.", "Sorry, I'm lost."]),
            t("Where are you going?", "Ба куҷо меравед?", "Бигӯ: ба вокзал", "To the station.", "Ба вокзал.",
              ["The station.", "To the train station."]),
            t("It's near. Go straight.", "Наздик аст. Рост равед.", "Ташаккур гӯй", "Thank you.", "Ташаккур.",
              ["Thanks.", "Thank you so much."]),
        ]),
        ("Кадом тараф?", [
            s("Train station", "Вокзал", None),
            s("Very near", "Хеле наздик", None),
            s("Too far", "Хеле дур", None),
            s("This map", "Ин харита", None),
            s("Which way?", "Кадом тараф?", None),
            s("On foot", "Пиёда", None),
        ]),
        ("Пиёда?", [
            t("Hi! Can I help?", "Салом! Ёрӣ диҳам?", "Бипурс: вокзал кадом тараф аст?",
              "Which way is the station?", "Вокзал кадом тараф аст?", ["Which way?", "Where is the station?"]),
            t("That way. Ten minutes.", "Он тараф. Даҳ дақиқа.", "Бипурс: пиёда?", "On foot?", "Пиёда?",
              ["Walking?", "Can I walk?"]),
            t("Yes, it's not far.", "Ҳа, дур нест.", "Бигӯ: олӣ, ташаккур", "Great, thank you.",
              "Олӣ, ташаккур.", ["Thanks!", "Okay, thank you."]),
        ]),
        ("Ман куҷо ҳастам?", [
            s("Excuse me, please.", "Бубахшед, лутфан.", None),
            s("I'm looking for this.", "Инро меҷӯям.", None),
            s("Is it far?", "Дур аст?", None),
            s("Can you show me?", "Нишон медиҳед?", None),
            s("Where am I?", "Ман куҷо ҳастам?", None),
            s("I'm new here.", "Ман ин ҷо навам.", None),
        ]),
        ("Кӯчаи Парк", [
            t("Yes? Can I help you?", "Ҳа? Ёрӣ диҳам?", "Бигӯ: бубахшед. Ман куҷо ҳастам?", "Sorry. Where am I?",
              "Бубахшед. Ман куҷо ҳастам?", ["Where am I, please?", "Excuse me, where am I?"]),
            t("This is Park Street.", "Ин кӯчаи Парк.", "Бигӯ: инро меҷӯям", "I'm looking for this.",
              "Инро меҷӯям.", ["I need this address.", "I'm looking for this place."]),
            t("Oh, that's near. Next street.", "О, наздик. Кӯчаи навбатӣ.", "Бипурс: нишон медиҳед?",
              "Can you show me?", "Нишон медиҳед?", ["Show me, please?", "Can you show me, please?"]),
        ]),
        ("Телефонам хомӯш", [
            s("My phone doesn't work.", "Телефонам кор намекунад.", "Яъне заряд тамом шуд."),
            s("Can I call?", "Занг занам?", None),
            s("I need a taxi.", "Ба ман такси лозим.", None),
            s("Is it safe here?", "Ин ҷо бехатар аст?", None),
            s("Which bus goes there?", "Кадом автобус он ҷо меравад?", None),
            s("Write it, please.", "Нависед, лутфан.", None),
        ]),
        ("Автобуси даҳ", [
            t("You look lost.", "Гӯё гум шудаед.", "Бигӯ: ҳа. Телефонам кор намекунад", "Yes. My phone doesn't work.",
              "Ҳа. Телефонам кор намекунад.", ["Yes, my phone is dead.", "Yes. No battery."]),
            t("Where do you need to go?", "Ба куҷо рафтан лозим?", "Бигӯ: ба кӯчаи Мейн", "Main Street.",
              "Ба кӯчаи Мейн.", ["To Main Street.", "Main Street, please."]),
            t("Take bus ten. The stop is there.", "Автобуси даҳро гиред. Истгоҳ он ҷост.", "Бигӯ: нависед, лутфан",
              "Write it, please.", "Нависед, лутфан.", ["Can you write it?", "Please write it."]),
        ]),
        ("Миссия: роҳ ба вокзал", [
            t("Excuse me, are you okay?", "Бубахшед, шумо хубед?", "Бигӯ: роҳро гум кардам. Телефонам кор намекунад",
              "I'm lost. My phone doesn't work.", "Роҳро гум кардам. Телефонам кор намекунад.", ["Sorry, I'm lost.", "I'm lost."]),
            t("Where are you going?", "Ба куҷо меравед?", "Бигӯ: ба вокзал", "To the station.", "Ба вокзал.",
              ["The train station.", "The station."]),
            t("Go straight, then right.", "Рост равед, баъд ба рост.", "Бипурс: дур аст?", "Is it far?",
              "Дур аст?", ["Far?", "Is it near?"]),
            t("No, five minutes.", "Не, панҷ дақиқа.", "Бигӯ: олӣ, ташаккури зиёд", "Great, thank you so much.",
              "Олӣ, ташаккури зиёд.", ["Thank you!", "Thanks a lot!"]),
        ]),
    ]))

# ═════════════════════ 18. Вақти холӣ ═════════════════════
made.append(pack("free_time_en_tg", "Free time", "Вақти холӣ", "🎉", 18, L,
    "Рӯзҳои истироҳат: бо дӯстон вохӯрӣ мегузоред, ба футбол ё кино меравед, вақт ва ҷойро "
    "мепурсед, даъватро қабул ё рад мекунед ва мегӯед, ки истироҳат чӣ хел гузашт.",
    [
        ("Истироҳат", [
            w("Weekend", "рӯзҳои истироҳат", None),
            w("Movie", "филм", None),
            w("Park", "боғ", None),
            w("Football", "футбол", None),
            w("Friends", "дӯстон", None),
            w("Free", "холӣ", None),
        ]),
        ("Якшанбе холӣ ҳастед?", [
            t("Are you free on Sunday?", "Якшанбе холӣ ҳастед?", "Бигӯ: ҳа, холӣ ҳастам", "Yes, I'm free.",
              "Ҳа, холӣ ҳастам.", ["Yes.", "Yes, why?"]),
            t("Let's play football!", "Биёед футбол бозӣ кунем!", "Бигӯ: олӣ! Соати чанд?", "Great! What time?",
              "Олӣ! Соати чанд?", ["Sounds good! When?", "Great! When?"]),
            t("At ten, in the park.", "Соати даҳ, дар боғ.", "Бигӯ: хуб, то якшанбе", "Okay, see you Sunday.",
              "Хуб, то якшанбе.", ["See you Sunday!", "Okay, see you."]),
        ]),
        ("Фикри хуб", [
            s("This weekend", "Ин рӯзҳои истироҳат", None),
            s("Play football", "Футбол бозӣ кардан", None),
            s("Watch movies", "Филм тамошо кардан", None),
            s("Good idea", "Фикри хуб", None),
            s("Maybe later", "Шояд баъдтар", None),
            s("See you", "То дидор", None),
        ]),
        ("Филм", [
            t("Do you want to see a movie?", "Мехоҳед филм бинед?", "Бигӯ: фикри хуб! Кай?", "Good idea! When?",
              "Фикри хуб! Кай?", ["Sure! When?", "Yes! What time?"]),
            t("Saturday evening.", "Шанбе бегоҳ.", "Бигӯ: бубахшед, кор мекунам. Шояд якшанбе?",
              "Sorry, I work. Maybe Sunday?", "Бубахшед, кор мекунам. Шояд якшанбе?",
              ["Sorry, I'm busy Saturday.", "I can't. Sunday?"]),
            t("Sunday is okay!", "Якшанбе мешавад!", "Бигӯ: олӣ", "Great!", "Олӣ!",
              ["Perfect!", "Great, see you!"]),
        ]),
        ("Куҷо вомехӯрем?", [
            s("I like football.", "Ман футболро дӯст медорам.", None),
            s("I'm free on Sunday.", "Якшанбе холӣ ҳастам.", None),
            s("Where do we meet?", "Куҷо вомехӯрем?", None),
            s("Let's go together.", "Якҷоя равем.", None),
            s("I can't today.", "Имрӯз наметавонам.", None),
            s("Maybe next time.", "Шояд дафъаи дигар.", None),
        ]),
        ("Дар истгоҳ", [
            t("Let's go to the park!", "Биёед ба боғ равем!", "Бигӯ: хуб. Куҷо вомехӯрем?", "Okay. Where do we meet?",
              "Хуб. Куҷо вомехӯрем?", ["Where do we meet?", "Sure! Where?"]),
            t("At the bus stop.", "Дар истгоҳи автобус.", "Бипурс: соати чанд?", "What time?", "Соати чанд?",
              ["When?", "What time, please?"]),
            t("At two o'clock.", "Соати ду.", "Бигӯ: хуб. То дидор!", "Okay. See you!", "Хуб. То дидор!",
              ["See you at two!", "Okay, see you."]),
        ]),
        ("Истироҳат чӣ хел гузашт?", [
            s("Good weekend?", "Истироҳат хуб гузашт?", None),
            s("It was fun.", "Ҷолиб буд.", None),
            s("I was at home.", "Дар хона будам.", None),
            s("I was tired.", "Монда будам.", None),
            s("What about you?", "Шумо чӣ?", None),
            s("Let's do it again!", "Боз мекунем!", None),
        ]),
        ("Ҳафтаи оянда", [
            t("Hi! How was your weekend?", "Салом! Истироҳат чӣ хел гузашт?", "Бигӯ: ҷолиб буд. Шумо чӣ?",
              "It was fun. What about you?", "Ҷолиб буд. Шумо чӣ?", ["Good! And you?", "It was fun."]),
            t("I stayed home. I was tired.", "Дар хона мондам. Монда будам.",
              "Бигӯ: ҳафтаи оянда футбол бозӣ кунем", "Let's play football next week.",
              "Ҳафтаи оянда футбол бозӣ кунем.", ["Football next week?", "Next week, football?"]),
            t("Sure, good idea!", "Албатта, фикри хуб!", "Бигӯ: олӣ", "Great!", "Олӣ!",
              ["Perfect!", "Great, see you!"]),
        ]),
        ("Миссия: истироҳат", [
            t("Hi! Are you free this weekend?", "Салом! Рӯзҳои истироҳат холӣ ҳастед?",
              "Бигӯ: ҳа, якшанбе холӣ ҳастам", "Yes, I'm free on Sunday.", "Ҳа, якшанбе холӣ ҳастам.",
              ["Yes, on Sunday.", "Sunday, yes."]),
            t("Let's watch a movie!", "Биёед филм бинем!", "Бигӯ: фикри хуб! Соати чанд?", "Good idea! What time?",
              "Фикри хуб! Соати чанд?", ["Great! When?", "Sure! What time?"]),
            t("At six. Where do we meet?", "Соати шаш. Куҷо вомехӯрем?", "Бигӯ: дар истгоҳи автобус",
              "At the bus stop.", "Дар истгоҳи автобус.", ["The bus stop.", "At the bus stop, okay?"]),
            t("Perfect. See you Sunday!", "Олӣ. То якшанбе!", "Бигӯ: то якшанбе", "See you Sunday!",
              "То якшанбе!", ["See you!", "Bye! See you Sunday."]),
        ]),
    ]))

# ═════════════════════ 19. Занги фаврӣ ═════════════════════
made.append(pack("emergency_en_tg", "Emergency call", "Занги фаврӣ", "🚨", 19, L,
    "Ҳолати фаврӣ: оташ, касе афтод ё сумкаро дузд бурд. Шумо ба 911 занг мезанед, кӯтоҳ "
    "мегӯед чӣ шуд ва дар куҷо ҳастед, ва ба саволҳо ором ҷавоб медиҳед.",
    [
        ("Ёрӣ!", [
            w("Help", "ёрӣ", None),
            w("Fire", "оташ", None),
            w("Police", "полис", None),
            w("Ambulance", "ёрии таъҷилӣ", None),
            w("Thief", "дузд", None),
            w("Emergency", "ҳолати фаврӣ", "Дар ИМА рақами фаврӣ 911 аст."),
        ]),
        ("Оташ!", [
            t("Nine one one. What's your emergency?", "Нӯҳ як як. Чӣ шуд?", "Бигӯ: ёрӣ диҳед! Оташ!",
              "Help! There's a fire!", "Ёрӣ диҳед! Оташ!", ["Fire! Help!", "There's a fire!"]),
            t("Where are you?", "Шумо куҷоед?", "Бигӯ: кӯчаи Мейн, хонаи даҳ", "Ten Main Street.",
              "Кӯчаи Мейн, хонаи даҳ.", ["Main Street, number ten.", "I'm on Main Street."]),
            t("Is anyone inside?", "Касе дарун ҳаст?", "Бигӯ: не, ҳама берунанд", "No, everyone is outside.",
              "Не, ҳама берунанд.", ["No. We are all outside.", "No one."]),
        ]),
        ("Зуд биёед", [
            s("Help, please!", "Ёрӣ диҳед!", None),
            s("A fire", "Оташ", None),
            s("He's hurt", "Ӯ захмӣ шуд", None),
            s("Not breathing", "Нафас намекашад", None),
            s("Come quickly", "Зуд биёед", None),
            s("Right now", "Ҳозир", None),
        ]),
        ("Як мард афтод", [
            t("Nine one one. What happened?", "Нӯҳ як як. Чӣ шуд?", "Бигӯ: одаме захмӣ шуд", "A man is hurt.",
              "Одаме захмӣ шуд.", ["A man fell down.", "Someone fell."]),
            t("Is he breathing?", "Нафас мекашад?", "Бигӯ: ҳа, нафас мекашад", "Yes, he is breathing.",
              "Ҳа, нафас мекашад.", ["Yes.", "Yes, he's breathing."]),
            t("The ambulance is coming.", "Ёрии таъҷилӣ меояд.", "Бигӯ: лутфан, зуд биёед", "Please come fast.",
              "Лутфан, зуд биёед.", ["Please hurry.", "Come quickly, please."]),
        ]),
        ("Дузд", [
            s("Please send help.", "Лутфан, ёрӣ фиристед.", None),
            s("A thief! My bag!", "Дузд! Халтаи ман!", None),
            s("He is hurt.", "Ӯ захмӣ аст.", None),
            s("Please come fast.", "Лутфан, зуд биёед.", None),
            s("Everyone is outside.", "Ҳама берунанд.", None),
            s("Call an ambulance!", "Ёрии таъҷилиро ҷеғ занед!", None),
        ]),
        ("Ӯ чӣ хел буд?", [
            t("Police. What happened?", "Полис. Чӣ шуд?", "Бигӯ: дузд! Халтаи ман", "A thief! My bag!",
              "Дузд! Халтаи ман!", ["My bag! A thief!", "A man took my bag."]),
            t("What did he look like?", "Ӯ чӣ хел буд?", "Бигӯ: қадбаланд, куртаи сиёҳ", "Tall, black jacket.",
              "Қадбаланд, куртаи сиёҳ.", ["Tall. A black jacket.", "He was tall."]),
            t("Okay. Where are you now?", "Хуб. Ҳозир куҷоед?", "Бигӯ: ман дар кӯчаи Мейн", "I'm on Main Street.",
              "Ман дар кӯчаи Мейн ҳастам.", ["Main Street.", "On Main Street."]),
        ]),
        ("Писарам гум шуд", [
            s("Please speak slowly.", "Лутфан, оҳиста гап занед.", None),
            s("My English is bad.", "Англисиям бад аст.", None),
            s("I need a translator.", "Ба ман тарҷумон лозим.", None),
            s("Where is the hospital?", "Беморхона куҷост?", None),
            s("My son is lost.", "Писарам гум шуд.", None),
            s("He is six.", "Ӯ шашсола аст.", None),
        ]),
        ("Чӣ пӯшидааст?", [
            t("Police. How can I help?", "Полис. Чӣ ёрӣ диҳам?", "Бигӯ: писарам гум шуд", "My son is lost.",
              "Писарам гум шуд.", ["I can't find my son.", "My son is missing."]),
            t("How old is he?", "Ӯ чандсола аст?", "Бигӯ: шашсола", "He is six.", "Ӯ шашсола аст.",
              ["Six.", "Six years old."]),
            t("What is he wearing?", "Чӣ пӯшидааст?", "Бигӯ: куртаи сурх", "A red jacket.", "Куртаи сурх.",
              ["Red jacket.", "He wears red."]),
        ]),
        ("Миссия: 911", [
            t("Nine one one. What's your emergency?", "Нӯҳ як як. Чӣ шуд?", "Бигӯ: ёрӣ диҳед! Одаме захмӣ шуд",
              "Help! A man is hurt.", "Ёрӣ диҳед! Одаме захмӣ шуд.", ["A man fell. Help!", "Help, please! A man fell."]),
            t("Where are you?", "Шумо куҷоед?", "Бигӯ: ман дар кӯчаи Мейн", "I'm on Main Street.",
              "Ман дар кӯчаи Мейн ҳастам.", ["Main Street.", "On Main Street."]),
            t("Is he breathing?", "Нафас мекашад?", "Бигӯ: ҳа, вале захмӣ аст", "Yes, but he is hurt.",
              "Ҳа, вале захмӣ аст.", ["Yes. He is hurt.", "Yes, he's breathing."]),
            t("Stay with him. The ambulance is coming.", "Бо ӯ монед. Ёрии таъҷилӣ меояд.",
              "Бигӯ: хуб. Лутфан, зуд биёед", "Okay. Please come fast.", "Хуб. Лутфан, зуд биёед.",
              ["Okay. Please hurry.", "Okay, thank you."]),
        ]),
    ], mission_mode="call"))

# ═════════════════════ 20. Дар сартарошхона ═════════════════════
made.append(pack("barber_en_tg", "At the barber", "Дар сартарошхона", "💈", 20, L,
    "Шумо ба сартарошхона меравед: навбат мегиред, мегӯед мӯйро чӣ хел гиранд — кӯтоҳ ё "
    "каме, ришро ҳам, нархро мепурсед ва барои кори хуб ташаккур мегӯед.",
    [
        ("Мӯй", [
            w("Haircut", "мӯйгирӣ", None),
            w("Short", "кӯтоҳ", None),
            w("Long", "дароз", None),
            w("Beard", "риш", None),
            w("Mirror", "оина", None),
            w("Wait", "интизор шудан", None),
        ]),
        ("Навбат", [
            t("Hi! Haircut?", "Салом! Мӯй гиред?", "Бигӯ: ҳа, лутфан", "Yes, please.", "Ҳа, лутфан.",
              ["Yes.", "Yes, a haircut."]),
            t("Please wait ten minutes.", "Лутфан, даҳ дақиқа интизор шавед.", "Бигӯ: хуб, мушкил нест",
              "Okay, no problem.", "Хуб, мушкил нест.", ["Okay.", "No problem."]),
            t("Okay, sit here.", "Хуб, ин ҷо шинед.", "Ташаккур гӯй", "Thank you.", "Ташаккур.",
              ["Thanks.", "Okay, thanks."]),
        ]),
        ("Ҳамин хел", [
            s("Very short", "Хеле кӯтоҳ", None),
            s("A little", "Каме", None),
            s("The sides", "Паҳлӯҳо", None),
            s("The top", "Боло", None),
            s("My beard", "Риши ман", None),
            s("Like this", "Ҳамин хел", None),
        ]),
        ("Паҳлӯҳо кӯтоҳ", [
            t("How do you want it?", "Чӣ хел мехоҳед?", "Бигӯ: паҳлӯҳо кӯтоҳ", "Short on the sides.",
              "Паҳлӯҳо кӯтоҳ.", ["Short sides.", "The sides short, please."]),
            t("And the top?", "Ва боло?", "Бигӯ: каме", "Just a little.", "Каме.",
              ["A little.", "Only a little."]),
            t("Okay. Beard too?", "Хуб. Риш ҳам?", "Бигӯ: ҳа, лутфан", "Yes, please.", "Ҳа, лутфан.",
              ["Yes.", "Yes, the beard too."]),
        ]),
        ("На хеле кӯтоҳ", [
            s("Not too short.", "На хеле кӯтоҳ.", None),
            s("Like this, please.", "Ҳамин хел, лутфан.", "Метавонед аксро нишон диҳед."),
            s("How long to wait?", "Чанд вақт интизор шавам?", None),
            s("Short, please.", "Кӯтоҳ, лутфан.", None),
            s("Just a little.", "Каме.", None),
            s("My beard too.", "Риши ман ҳам.", None),
        ]),
        ("Ба оина нигоҳ кунед", [
            t("What style?", "Чӣ хел?", "Бигӯ: ҳамин хел, лутфан", "Like this, please.", "Ҳамин хел, лутфан.",
              ["This one, please.", "Like this photo."]),
            t("Okay. Short?", "Хуб. Кӯтоҳ?", "Бигӯ: на хеле кӯтоҳ", "Not too short.", "На хеле кӯтоҳ.",
              ["A little short.", "Not very short."]),
            t("Look in the mirror. Good?", "Ба оина нигоҳ кунед. Хуб?", "Бигӯ: кӯтоҳ, лутфан",
              "Short, please.", "Кӯтоҳ, лутфан.", ["A little shorter, please.", "A bit shorter."]),
        ]),
        ("Олӣ шуд", [
            s("It looks great!", "Олӣ шуд!", None),
            s("That's perfect.", "Айнан ҳамин.", None),
            s("Do you take cards?", "Корт қабул мекунед?", None),
            s("This is for you.", "Ин барои шумо.", None),
            s("See you next month.", "То моҳи оянда.", None),
            s("See you again.", "То боз дидор.", None),
        ]),
        ("Корт қабул мекунед?", [
            t("All done. Do you like it?", "Тамом. Писанд аст?", "Бигӯ: олӣ шуд!", "It looks great!", "Олӣ шуд!",
              ["Perfect!", "I like it. Great!"]),
            t("Twenty dollars, please.", "Бист доллар, лутфан.", "Бипурс: корт қабул мекунед?", "Do you take cards?",
              "Корт қабул мекунед?", ["Card okay?", "Can I pay by card?"]),
            t("Yes, of course.", "Ҳа, албатта.", "Бигӯ: ана. Ва ин барои шумо", "Here. And this is for you.",
              "Ана. Ва ин барои шумо.", ["Here is a tip.", "Thanks! This is for you."]),
        ]),
        ("Миссия: сартарошхона", [
            t("Hi! Haircut?", "Салом! Мӯй гиред?", "Бигӯ: ҳа. Чанд вақт интизор шавам?", "Yes. How long to wait?",
              "Ҳа. Чанд вақт интизор шавам?", ["Yes, please. How long?", "Yes. Is there a wait?"]),
            t("Okay, sit here. How short?", "Хуб, ин ҷо шинед. Чӣ қадар кӯтоҳ?", "Бигӯ: на хеле кӯтоҳ",
              "Not too short.", "На хеле кӯтоҳ.", ["A little short.", "Not very short."]),
            t("And the beard?", "Ва риш?", "Бигӯ: каме, лутфан", "Just a little, please.", "Каме, лутфан.",
              ["A little.", "Only a little."]),
            t("Done! Do you like it?", "Тамом! Писанд аст?", "Бигӯ: олӣ шуд! То моҳи оянда",
              "It looks great! See you next month.", "Олӣ шуд! То моҳи оянда.", ["It looks great!", "Perfect, thanks!"]),
        ]),
    ]))

if MISSING:
    raise SystemExit('⛔ транскрипсия нест: ' + ', '.join(sorted(MISSING)))
print(' '.join(made))
