"""ТУРКӢ → тоҷикӣ, «Гуфтор» A1 — нишаи «Ронандагӣ» (`drive`), 05.10.2026.

14 вазъият барои ронандаи тоҷик дар Туркия (такси, курйер, мошини ширкат) — ҳамон тартиби
русӣ/олмонӣ/арабӣ. Роҳи `drive` = 6 вазъияти умумӣ (1, 2, 6, 10, 14, 16) + ин 14 → 20.

Қоидаҳо — `_tr_packs_lib.py`. Бо мусофир — «siz», бо диспетчер/устои автосервис — «abi».
chunks ≤ 2 калима, sentences ≤ 4. Рақамҳо бо ҳарф. Касб бе `{job}`: «Ben şoförüm.»

Аз ҷузвдони backend: python prisma/_tr-drive-a1-packs.py
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _tr_packs_lib import *  # noqa: F401,F403

_s = s


def s(text, tr, note=None, cue=None, cue_tr=None, swaps=None):  # noqa: F811
    if not cue and not swaps and len(text.split()) == 1:
        return w(text.rstrip('.!'), tr.rstrip('.!'), note)
    return _s(text, tr, note, cue, cue_tr, swaps)


made = []
DR = ["drive"]

# ═════════════════════ 3. Мошин ва ҳуҷҷатҳо ═════════════════════
made.append(pack("car_tr_tg", "Araba ve belgeler", "Мошин ва ҳуҷҷатҳо", "🚗", 3, DR,
    "Рӯзи аввал дар ширкати такси ё расонидан. Мудир ба шумо мошин, калид ва ҳуҷҷатҳоро медиҳад. "
    "Шумо мошинро месанҷед ва мепурсед, ки чӣ кор кунед.",
    [
        ("Мошин", [
            w("Araba", "мошин", None),
            w("Anahtar", "калид", None),
            w("Ehliyet", "шаҳодатномаи ронандагӣ", None),
            w("Ruhsat", "ҳуҷҷати мошин", None),
            w("Benzin", "бензин", None),
            w("Lastik", "чарх (шина)", None),
        ]),
        ("Ҳуҷҷатҳо", [
            t("Merhaba! Yeni şoför müsün?", "Салом! Ронандаи навӣ?", "Бигӯ: ҳа, ман ронандаам", "Evet, ben şoförüm.",
              "Ҳа, ман ронандаам.", ["Evet."]),
            t("Ehliyetin var mı?", "Шаҳодатнома дорӣ?", "Бигӯ: ҳа, марҳамат", "Evet, buyurun.", "Ҳа, марҳамат.",
              ["Var, buyurun."]),
            t("Tamam. Anahtar burada.", "Хуб. Калид ин ҷо.", "Ташаккур гӯй", "Teşekkürler.", "Ташаккур.",
              ["Sağ olun abi."]),
        ]),
        ("Ибораҳо", [
            s("Ben şoförüm", "Ман ронандаам", None),
            s("Arabanın anahtarı", "Калиди мошин", None),
            w("Ruhsat", "ҳуҷҷати мошин", None),
            s("Depo dolu", "Бак пур", None),
            s("Lastik inik", "Чарх холӣ (бебод)", None),
            s("Nerede park?", "Дар куҷо истад?", None),
        ]),
        ("Мошин куҷост?", [
            t("Araban hazır.", "Мошинат тайёр.", "Бипурс: мошин куҷост?", "Araba nerede?", "Мошин куҷост?",
              ["Nerede abi?"]),
            t("Otoparkta, beyaz.", "Дар таваққуфгоҳ, сафед.", "Бипурс: ҳуҷҷати мошин куҷост?", "Ruhsat nerede?",
              "Ҳуҷҷати мошин куҷост?", ["Ya ruhsat?"]),
            t("Torpidoda.", "Дар қуттии пеши мошин.", "Бигӯ: фаҳмидам", "Anladım.", "Фаҳмидам.", ["Tamam abi."]),
        ]),
        ("Мошинро месанҷам", [
            s("Depo yarım.", "Бак ним аст.", None),
            s("Bu lastik inik.", "Ин чарх бебод.", None),
            s("Işıklar çalışıyor.", "Чароғҳо кор мекунанд.", None),
            s("Klima çalışmıyor.", "Кондитсионер кор намекунад.", None),
            s("Burada çizik var.", "Ин ҷо харош ҳаст.", None),
            s("Her şey tamam.", "Ҳама хуб.", None),
        ]),
        ("Санҷиш", [
            t("Arabaya baktın mı?", "Ба мошин нигоҳ кардӣ?", "Бигӯ: ин чарх бебод", "Bu lastik inik.",
              "Ин чарх бебод.", ["Lastik inik abi."]),
            t("Tamam, hava bas.", "Хуб, бод деҳ.", "Бигӯ: ин ҷо харош ҳаст", "Burada çizik var.", "Ин ҷо харош ҳаст.",
              ["Bir de çizik var."]),
            t("Biliyorum, eski.", "Медонам, кӯҳна аст.", "Бигӯ: хуб", "Tamam.", "Хуб.", ["Peki abi."]),
        ]),
        ("Қоидаҳои ширкат", [
            s("Arabada sigara yok.", "Дар мошин сигор не.", None),
            s("Her akşam rapor.", "Ҳар шом ҳисобот.", None),
            s("Benzin kartı burada.", "Корти бензин ин ҷо.", None),
            s("Arabayı temiz tut.", "Мошинро тоза нигоҳ дор.", None),
            s("Sorun olursa ara.", "Агар мушкил бошад, занг зан.", None),
            s("Anladım, teşekkürler.", "Фаҳмидам, ташаккур.", None),
        ]),
        ("Корти бензин", [
            t("Bu benzin kartı.", "Ин корти бензин.", "Бипурс: дар кадом колонка?", "Hangi benzinlikte?",
              "Дар кадом колонка?", ["Nerede kullanayım?"]),
            t("Her yerde olur.", "Ҳама ҷо мешавад.", "Бигӯ: фаҳмидам, ташаккур", "Anladım, teşekkürler.",
              "Фаҳмидам, ташаккур.", ["Tamam, sağ olun."]),
            t("Sorun olursa ara.", "Агар мушкил бошад, занг зан.", "Бигӯ: хуб, ака", "Tamam abi.", "Хуб, ака.",
              ["Peki abi."]),
        ]),
        ("Миссия: мошини нав", [
            t("Merhaba! Yeni şoför müsün?", "Салом! Ронандаи навӣ?", "Бигӯ: ҳа, ман ронандаам", "Evet, ben şoförüm.",
              "Ҳа, ман ронандаам.", ["Evet."]),
            t("Bu senin araban. Anahtar burada.", "Ин мошини ту. Калид ин ҷо.", "Бипурс: ҳуҷҷати мошин куҷост?",
              "Ruhsat nerede?", "Ҳуҷҷати мошин куҷост?", ["Ya ruhsat?"]),
            t("Torpidoda. Arabaya bak.", "Дар қуттӣ. Ба мошин нигоҳ кун.", "Бигӯ: ин чарх бебод", "Bu lastik inik.",
              "Ин чарх бебод.", ["Lastik inik abi."]),
            t("Tamam, hava bas.", "Хуб, бод деҳ.", "Бигӯ: хуб, ака", "Tamam abi.", "Хуб, ака.", ["Peki abi."]),
        ]),
    ]))

# ═════════════════════ 4. Гирифтани мусофир ═════════════════════
made.append(pack("pickup_tr_tg", "Yolcu almak", "Гирифтани мусофир", "🙋", 4, DR,
    "Шумо мусофирро аз ҷои фармоиш мегиред: занг мезанед, ки омадед, номро месанҷед, мепурсед, "
    "ки куҷо меравад ва камарбандро ёдрас мекунед.",
    [
        ("Такси", [
            w("Yolcu", "мусофир", None),
            w("Taksi", "такси", None),
            w("Kapı", "дар", None),
            w("Bagaj", "бағоҷ (бағоҷдон)", None),
            w("Kemer", "камарбанд", None),
            w("Adres", "суроға", None),
        ]),
        ("Ман омадам", [
            t("Alo?", "Ало?", "Бигӯ: салом, ман таксиам, омадам", "Merhaba, taksi geldi.", "Салом, такси омад.",
              ["Ben buradayım."]),
            t("Tamam, geliyorum.", "Хуб, меоям.", "Бигӯ: мошини сафед", "Beyaz araba.", "Мошини сафед.",
              ["Beyaz taksi."]),
            t("Görüyorum!", "Мебинам!", "Бигӯ: хуб", "Tamam.", "Хуб.", ["Bekliyorum."]),
        ]),
        ("Ибораҳо", [
            s("Taksi geldi", "Такси омад", None),
            s("Beyaz araba", "Мошини сафед", None),
            s("Nereye gidiyoruz?", "Ба куҷо меравем?", None),
            s("Kemerinizi takın", "Камарбандро банд кунед", None),
            s("Buyurun, binin", "Марҳамат, савор шавед", None),
            w("Bagaj", "бағоҷдон", None),
        ]),
        ("Ному суроға", [
            t("Merhaba!", "Салом!", "Бипурс: номатон Айше?", "Adınız Ayşe mi?", "Номатон Айше?", ["Ayşe Hanım mı?"]),
            t("Evet, benim.", "Ҳа, манам.", "Бипурс: ба куҷо меравем?", "Nereye gidiyoruz?", "Ба куҷо меравем?",
              ["Nereye?"]),
            t("Havalimanına.", "Ба фурудгоҳ.", "Бигӯ: хуб, марҳамат", "Tamam, buyurun.", "Хуб, марҳамат.",
              ["Buyurun, binin."]),
        ]),
        ("Савор шудан", [
            s("Bagajınız var mı?", "Бағоҷ доред?", None),
            s("Bagajı açıyorum.", "Бағоҷдонро мекушоям.", None),
            s("Kemerinizi takın lütfen.", "Камарбандро банд кунед, лутфан.", None),
            s("Klima açık mı?", "Кондитсионер кушода бошад?", None),
            s("Yolculuk yirmi dakika.", "Роҳ бист дақиқа.", None),
            s("Hazır mısınız?", "Тайёред?", None),
        ]),
        ("Бағоҷ", [
            t("Bir valizim var.", "Як ҷомадон дорам.", "Бигӯ: бағоҷдонро мекушоям", "Bagajı açıyorum.",
              "Бағоҷдонро мекушоям.", ["Bagaja koyalım."]),
            t("Teşekkürler.", "Ташаккур.", "Бигӯ: камарбандро банд кунед, лутфан", "Kemerinizi takın lütfen.",
              "Камарбандро банд кунед, лутфан.", ["Kemer lütfen."]),
            t("Tabii. Ne kadar sürer?", "Албатта. Чӣ қадар мегирад?", "Бигӯ: бист дақиқа", "Yirmi dakika.",
              "Бист дақиқа.", ["Yolculuk yirmi dakika."]),
        ]),
        ("Мусофир нест", [
            s("Neredesiniz?", "Шумо куҷоед?", None),
            s("Kapının önündeyim.", "Дар назди дарам.", None),
            s("Beş dakika bekliyorum.", "Панҷ дақиқа интизорам.", None),
            s("Sizi göremiyorum.", "Шуморо намебинам.", None),
            s("Hangi kapı?", "Кадом дар?", None),
            s("Hemen geliyorum.", "Ҳозир меоям.", None),
        ]),
        ("Мусофирро намебинам", [
            t("Alo? Neredesiniz?", "Ало? Шумо куҷоед?", "Бигӯ: дар назди дарам", "Kapının önündeyim.",
              "Дар назди дарам.", ["Ben buradayım."]),
            t("Ben de kapıdayım!", "Ман ҳам дар назди дарам!", "Бигӯ: шуморо намебинам", "Sizi göremiyorum.",
              "Шуморо намебинам.", ["Göremiyorum."]),
            t("Arka kapıdayım.", "Дар дари қафо.", "Бигӯ: ҳозир меоям", "Hemen geliyorum.", "Ҳозир меоям.",
              ["Tamam, geliyorum."]),
        ]),
        ("Миссия: мусофири аввал", [
            t("Alo? Neredesiniz?", "Ало? Куҷоед?", "Бигӯ: дар назди дарам, мошини сафед", "Kapıdayım, beyaz araba.",
              "Дар назди дарам, мошини сафед.", ["Beyaz araba."]),
            t("Tamam, geliyorum. Valizim var.", "Хуб, меоям. Ҷомадон дорам.", "Бигӯ: бағоҷдонро мекушоям",
              "Bagajı açıyorum.", "Бағоҷдонро мекушоям.", ["Bagaja koyalım."]),
            t("Teşekkürler.", "Ташаккур.", "Бипурс: ба куҷо меравем?", "Nereye gidiyoruz?", "Ба куҷо меравем?",
              ["Nereye?"]),
            t("Havalimanına.", "Ба фурудгоҳ.", "Бигӯ: камарбандро банд кунед, лутфан", "Kemerinizi takın lütfen.",
              "Камарбандро банд кунед, лутфан.", ["Kemer lütfen."]),
        ]),
    ]))

# ═════════════════════ 5. Роҳ ва самт ═════════════════════
made.append(pack("route_tr_tg", "Yol tarifi", "Роҳ ва самт", "🧭", 5, DR,
    "Мусофир роҳ нишон медиҳад ё шумо мепурсед: рост, чап, рост равед, дар чароғак гардед. "
    "Шумо самтро мефаҳмед ва такрор мекунед.",
    [
        ("Самт", [
            w("Sağ", "рост (тараф)", None),
            w("Sol", "чап", None),
            w("Düz", "рост (пеш)", None),
            w("Işık", "чароғак (светофор)", None),
            w("Köprü", "пул (кӯпрук)", None),
            w("Cadde", "хиёбон", None),
        ]),
        ("Ба куҷо?", [
            t("Taksim'e lütfen.", "Ба Таксим, лутфан.", "Бигӯ: хуб", "Tamam.", "Хуб.", ["Peki."]),
            t("Köprüden git.", "Аз пул рав.", "Бигӯ: хуб, аз пул", "Tamam, köprüden.", "Хуб, аз пул.",
              ["Köprüden, tamam."]),
            t("Şimdi sağa dön.", "Ҳоло ба рост гард.", "Бигӯ: ба рост, хуб", "Sağa, tamam.", "Ба рост, хуб.",
              ["Tamam."]),
        ]),
        ("Ибораҳо", [
            s("Sağa dönün", "Ба рост гардед", None),
            s("Sola dönün", "Ба чап гардед", None),
            s("Düz gidin", "Рост равед", None),
            s("Işıkta dur", "Дар чароғак ист", None),
            s("Burası mı?", "Ҳамин ҷо?", None),
            s("Biraz ileride", "Каме пештар", None),
        ]),
        ("Ҳамин ҷо?", [
            t("Işıktan sonra sola.", "Баъди чароғак ба чап.", "Такрор кун: баъди чароғак ба чап",
              "Işıktan sonra sola.", "Баъди чароғак ба чап.", ["Sola, tamam."]),
            t("Evet. Sonra düz.", "Ҳа. Баъд рост.", "Бипурс: ҳамин ҷо?", "Burası mı?", "Ҳамин ҷо?", ["Burada mı?"]),
            t("Hayır, biraz ileride.", "Не, каме пештар.", "Бигӯ: хуб", "Tamam.", "Хуб.", ["Peki."]),
        ]),
        ("Ман роҳро мепурсам", [
            s("Hangi yoldan gidelim?", "Аз кадом роҳ равем?", None),
            s("Navigasyon böyle diyor.", "Навигатор ҳамин тавр мегӯяд.", None),
            s("Bu yol kapalı.", "Ин роҳ баста аст.", None),
            s("Başka yoldan gidelim.", "Аз роҳи дигар равем.", None),
            s("Tam adres ne?", "Суроғаи дақиқ чист?", None),
            s("Burada durayım mı?", "Ин ҷо истам?", None),
        ]),
        ("Роҳ баста", [
            t("Neden durduk?", "Чаро истодем?", "Бигӯ: ин роҳ баста аст", "Bu yol kapalı.", "Ин роҳ баста аст.",
              ["Yol kapalı."]),
            t("Ne yapacağız?", "Чӣ мекунем?", "Бигӯ: аз роҳи дигар равем", "Başka yoldan gidelim.",
              "Аз роҳи дигар равем.", ["Başka yol var."]),
            t("Tamam, olur.", "Хуб, мешавад.", "Бигӯ: навигатор ҳамин тавр мегӯяд", "Navigasyon böyle diyor.",
              "Навигатор ҳамин тавр мегӯяд.", ["Navigasyon gösteriyor."]),
        ]),
        ("Ҷои истодан", [
            s("Burada duramam.", "Ин ҷо истода наметавонам.", None),
            s("Durak ileride.", "Истгоҳ пештар аст.", None),
            s("Köşede durayım.", "Дар гӯша истам.", None),
            s("Bina hangisi?", "Бино кадомаш?", None),
            s("Sağdaki bina.", "Бинои тарафи рост.", None),
            s("Geldik!", "Расидем!", None),
        ]),
        ("Расидем", [
            t("Burada dur lütfen.", "Ин ҷо ист, лутфан.", "Бигӯ: ин ҷо истода наметавонам", "Burada duramam.",
              "Ин ҷо истода наметавонам.", ["Burası yasak."]),
            t("Neden?", "Чаро?", "Бигӯ: дар гӯша истам", "Köşede durayım.", "Дар гӯша истам.",
              ["Köşede durabilirim."]),
            t("Tamam.", "Хуб.", "Бигӯ: расидем!", "Geldik!", "Расидем!", ["İşte geldik!"]),
        ]),
        ("Миссия: роҳи душвор", [
            t("Kadıköy'e lütfen.", "Ба Кадикёй, лутфан.", "Бипурс: суроғаи дақиқ чист?", "Tam adres ne?",
              "Суроғаи дақиқ чист?", ["Adres ne?"]),
            t("Moda Caddesi.", "Хиёбони Мода.", "Бигӯ: хуб", "Tamam.", "Хуб.", ["Peki."]),
            t("Bu yol neden kapalı?", "Ин роҳ чаро баста?", "Бигӯ: аз роҳи дигар равем", "Başka yoldan gidelim.",
              "Аз роҳи дигар равем.", ["Başka yol var."]),
            t("Burada dur lütfen.", "Ин ҷо ист, лутфан.", "Бигӯ: дар гӯша истам", "Köşede durayım.",
              "Дар гӯша истам.", ["Köşede durabilirim."]),
        ]),
    ]))

# ═════════════════════ 7. Бағоҷ ═════════════════════
made.append(pack("luggage_tr_tg", "Bagaj", "Бағоҷ", "🧳", 7, DR,
    "Мусофир бағоҷи зиёд дорад: шумо ёрӣ медиҳед, мепурсед, ки чизи шикастанӣ ҳаст ва дар охир "
    "ёдрас мекунед, ки чизе фаромӯш накунад.",
    [
        ("Бағоҷ", [
            w("Valiz", "ҷомадон", None),
            w("Çanta", "сумка", None),
            w("Kutu", "қуттӣ", None),
            w("Ağır", "вазнин", None),
            w("Hafif", "сабук", None),
            w("Kırılır", "шикастанӣ", None),
        ]),
        ("Ёрӣ бо ҷомадон", [
            t("Çok valizim var.", "Ҷомадонам бисёр аст.", "Бигӯ: ёрӣ медиҳам", "Yardım ederim.", "Ёрӣ медиҳам.",
              ["Ben alırım."]),
            t("Teşekkürler! Bu çok ağır.", "Ташаккур! Ин хеле вазнин.", "Бигӯ: мушкил нест", "Sorun değil.",
              "Мушкил нест.", ["Tamam."]),
            t("Ya bu çanta?", "Ва ин сумка?", "Бигӯ: дар пеш, бо шумо", "Önde, sizinle.", "Дар пеш, бо шумо.",
              ["Yanınızda."]),
        ]),
        ("Ибораҳо", [
            s("Yardım ederim", "Ёрӣ медиҳам", None),
            s("Çok ağır", "Хеле вазнин", None),
            s("Kırılır mı?", "Мешиканад?", None),
            s("Bagaja koyalım", "Ба бағоҷдон гузорем", None),
            s("Yer yok", "Ҷой нест", None),
            s("Arka koltuğa", "Ба курсии қафо", None),
        ]),
        ("Шикастанӣ?", [
            t("Bu kutu çok önemli.", "Ин қуттӣ хеле муҳим.", "Бипурс: мешиканад?", "Kırılır mı?", "Мешиканад?",
              ["İçinde cam var mı?"]),
            t("Evet, dikkat!", "Ҳа, эҳтиёт!", "Бигӯ: ба курсии қафо", "Arka koltuğa.", "Ба курсии қафо.",
              ["Arkaya koyalım."]),
            t("Süper, teşekkürler.", "Олӣ, ташаккур.", "Бигӯ: арзише надорад", "Rica ederim.", "Арзише надорад.",
              ["Ne demek."]),
        ]),
        ("Бағоҷ мегузорам", [
            s("Bagaj dolu.", "Бағоҷдон пур.", None),
            s("Valizi yatırıyorum.", "Ҷомадонро мехобонам.", None),
            s("Bu sığmıyor.", "Ин ҷо намешавад.", None),
            s("Dikkatli koyuyorum.", "Эҳтиёткорона мегузорам.", None),
            s("Bagaj ücreti yok.", "Пули бағоҷ нест.", None),
            s("Her şey içeride.", "Ҳама дарун.", None),
        ]),
        ("Ҷо намешавад", [
            t("Dört valiz var.", "Чор ҷомадон ҳаст.", "Бигӯ: бағоҷдон пур", "Bagaj dolu.", "Бағоҷдон пур.",
              ["Yer yok."]),
            t("Ne yapalım?", "Чӣ кунем?", "Бигӯ: ба курсии қафо", "Arka koltuğa.", "Ба курсии қафо.",
              ["Birini arkaya koyalım."]),
            t("Ekstra para var mı?", "Пули иловагӣ ҳаст?", "Бигӯ: пули бағоҷ нест", "Bagaj ücreti yok.",
              "Пули бағоҷ нест.", ["Hayır, yok."]),
        ]),
        ("Дар охир", [
            s("Bir şey unutmayın.", "Чизе фаромӯш накунед.", None),
            s("Telefonunuz burada.", "Телефонатон ин ҷо.", None),
            s("Bagajı açıyorum.", "Бағоҷдонро мекушоям.", None),
            s("Hepsi bu mu?", "Ҳамааш ҳамин?", None),
            s("İyi yolculuklar!", "Сафари хуш!", None),
            s("Bir çanta kaldı.", "Як сумка монд.", None),
        ]),
        ("Чизе монд?", [
            t("Geldik, teşekkürler.", "Расидем, ташаккур.", "Бипурс: ҳамааш ҳамин?", "Hepsi bu mu?",
              "Ҳамааш ҳамин?", ["Hepsi tamam mı?"]),
            t("Evet, galiba.", "Ҳа, гумон кунам.", "Бигӯ: як сумка монд", "Bir çanta kaldı.", "Як сумка монд.",
              ["Burada bir çanta var."]),
            t("Aa, teşekkürler!", "О, ташаккур!", "Бигӯ: сафари хуш!", "İyi yolculuklar!", "Сафари хуш!",
              ["İyi günler!"]),
        ]),
        ("Миссия: бағоҷи бисёр", [
            t("Üç valiz, bir kutu.", "Се ҷомадон, як қуттӣ.", "Бигӯ: ёрӣ медиҳам", "Yardım ederim.", "Ёрӣ медиҳам.",
              ["Ben alırım."]),
            t("Kutuya dikkat! Kırılır.", "Эҳтиёт ба қуттӣ! Мешиканад.", "Бигӯ: ба курсии қафо", "Arka koltuğa.",
              "Ба курсии қафо.", ["Arkaya koyalım."]),
            t("Geldik mi? Teşekkürler!", "Расидем? Ташаккур!", "Бипурс: ҳамааш ҳамин?", "Hepsi bu mu?",
              "Ҳамааш ҳамин?", ["Hepsi tamam mı?"]),
            t("Evet, hepsi.", "Ҳа, ҳамааш.", "Бигӯ: сафари хуш!", "İyi yolculuklar!", "Сафари хуш!", ["İyi günler!"]),
        ]),
    ]))

# ═════════════════════ 8. Пули роҳ ═════════════════════
made.append(pack("fare_tr_tg", "Ücret", "Пули роҳ", "💵", 8, DR,
    "Сафар тамом шуд: шумо нархро аз таксиметр мегӯед, пулро мегиред, бақия медиҳед ё бо корт "
    "пардохт мекунед ва чек пешниҳод мекунед.",
    [
        ("Пул", [
            w("Taksimetre", "таксиметр", None),
            w("Ücret", "нарх (пули роҳ)", None),
            w("Lira", "лира", None),
            w("Nakit", "нақд", None),
            w("Kart", "корт", None),
            w("Bozuk", "майда", None),
        ]),
        ("Чанд?", [
            t("Ne kadar?", "Чанд?", "Бигӯ: саду бист лира", "Yüz yirmi lira.", "Саду бист лира.",
              ["Taksimetre yüz yirmi."]),
            t("Kartla olur mu?", "Бо корт мешавад?", "Бигӯ: ҳа, мешавад", "Evet, olur.", "Ҳа, мешавад.", ["Tabii."]),
            t("Buyurun.", "Марҳамат.", "Ташаккур гӯй", "Teşekkürler.", "Ташаккур.", ["Sağ olun."]),
        ]),
        ("Ибораҳо", [
            s("Taksimetre gösteriyor", "Таксиметр нишон медиҳад", None),
            s("Yüz lira", "Сад лира", None),
            s("Bozuk yok", "Майда нест", None),
            s("Fiş lazım?", "Чек лозим?", None),
            s("Üstü kalsın", "Бақия лозим нест", "Мусофир мегӯяд."),
            w("Buyurun", "марҳамат", None),
        ]),
        ("Майда нест", [
            t("İki yüz lira, buyurun.", "Дусад лира, марҳамат.", "Бигӯ: майда нест", "Bozuk yok.", "Майда нест.",
              ["Maalesef bozuk yok."]),
            t("Kartla ödeyeyim.", "Бо корт медиҳам.", "Бигӯ: хуб, марҳамат", "Tamam, buyurun.", "Хуб, марҳамат.",
              ["Tabii."]),
            t("Fiş lütfen.", "Чек, лутфан.", "Бигӯ: марҳамат, чек", "Buyurun, fiş.", "Марҳамат, чек.",
              ["Fişiniz burada."]),
        ]),
        ("Нарх", [
            s("Taksimetre yüz lira.", "Таксиметр сад лира.", None),
            s("Köprü ücreti ekstra.", "Пули пул алоҳида.", None),
            s("Gece tarifesi var.", "Нархи шабона ҳаст.", None),
            s("Fiyat sabit.", "Нарх собит аст.", None),
            s("Para üstünüz.", "Бақияатон.", None),
            s("İyi günler!", "Рӯзи хуш!", None),
        ]),
        ("Чаро ин қадар?", [
            t("Neden yüz elli?", "Чаро саду панҷоҳ?", "Бигӯ: пули пул алоҳида", "Köprü ücreti ekstra.",
              "Пули пул алоҳида.", ["Köprü ücreti var."]),
            t("Aa, anladım.", "О, фаҳмидам.", "Бигӯ: таксиметр нишон медиҳад", "Taksimetre gösteriyor.",
              "Таксиметр нишон медиҳад.", ["Bakın, taksimetre."]),
            t("Tamam, buyurun.", "Хуб, марҳамат.", "Ташаккур гӯй", "Teşekkürler!", "Ташаккур!", ["Sağ olun!"]),
        ]),
        ("Мушкили пардохт", [
            s("Kart geçmedi.", "Корт нагузашт.", None),
            s("Bir daha deneyin.", "Боз як бор санҷед.", None),
            s("Nakit var mı?", "Нақд ҳаст?", None),
            s("Havale olur mu?", "Интиқол мешавад?", None),
            s("Bankamatik orada.", "Банкомат он ҷо.", None),
            s("Sizi bekliyorum.", "Шуморо интизорам.", None),
        ]),
        ("Корт нагузашт", [
            t("Kartla lütfen.", "Бо корт, лутфан.", "Бигӯ: корт нагузашт", "Kart geçmedi.", "Корт нагузашт.",
              ["Maalesef geçmedi."]),
            t("Nakit yok.", "Нақд нест.", "Бигӯ: банкомат он ҷо", "Bankamatik orada.", "Банкомат он ҷо.",
              ["Orada bankamatik var."]),
            t("Tamam, hemen gelirim.", "Хуб, ҳозир меоям.", "Бигӯ: шуморо интизорам", "Sizi bekliyorum.",
              "Шуморо интизорам.", ["Bekliyorum."]),
        ]),
        ("Миссия: охири сафар", [
            t("Geldik mi? Ne kadar?", "Расидем? Чанд?", "Бигӯ: саду панҷоҳ лира", "Yüz elli lira.",
              "Саду панҷоҳ лира.", ["Taksimetre yüz elli."]),
            t("Neden bu kadar?", "Чаро ин қадар?", "Бигӯ: пули пул алоҳида", "Köprü ücreti ekstra.",
              "Пули пул алоҳида.", ["Köprü ücreti var."]),
            t("Tamam. İki yüz, buyurun.", "Хуб. Дусад, марҳамат.", "Бигӯ: бақияатон", "Para üstünüz.", "Бақияатон.",
              ["Buyurun para üstü."]),
            t("Teşekkürler!", "Ташаккур!", "Бигӯ: рӯзи хуш!", "İyi günler!", "Рӯзи хуш!", ["Güle güle!"]),
        ]),
    ]))

# ═════════════════════ 9. Гап бо мусофир ═════════════════════
made.append(pack("smalltalk_tr_tg", "Yolcuyla sohbet", "Гап бо мусофир", "💬", 9, DR,
    "Дар роҳ мусофир гап мезанад: аз куҷо ҳастед, чанд сол дар Туркия ҳастед, оила доред? Шумо "
    "кӯтоҳ ва хушмуомила ҷавоб медиҳед.",
    [
        ("Гап", [
            w("Memleket", "ватан", None),
            w("Aile", "оила", None),
            w("Çocuk", "кӯдак", None),
            w("Yıl", "сол", None),
            w("Hava", "обу ҳаво", None),
            w("Trafik", "роҳбандӣ", None),
        ]),
        ("Аз куҷоӣ?", [
            t("Nerelisiniz?", "Аз куҷоед?", "Бигӯ: аз Тоҷикистон", "Tacikistanlıyım.", "Аз Тоҷикистонам.",
              ["Tacikistan'dan."]),
            t("Aa, Tacikistan! Güzel.", "О, Тоҷикистон! Хуб.", "Ташаккур гӯй", "Teşekkürler.", "Ташаккур.",
              ["Sağ olun."]),
            t("Türkçeniz iyi.", "Туркии шумо хуб.", "Бигӯ: каме", "Biraz.", "Каме.", ["Biraz biliyorum."]),
        ]),
        ("Ибораҳо", [
            w("Tacikistanlıyım", "аз Тоҷикистонам", None),
            s("İki yıldır", "Ду сол боз", None),
            s("Biraz Türkçe", "Каме туркӣ", None),
            s("Ailem orada", "Оилаам он ҷо", None),
            s("Hava güzel", "Ҳаво хуб", None),
            s("Çok trafik", "Роҳбандӣ зиёд", None),
        ]),
        ("Чанд сол?", [
            t("Kaç yıldır Türkiye'desiniz?", "Чанд сол боз дар Туркияед?", "Бигӯ: ду сол боз", "İki yıldır.",
              "Ду сол боз.", ["İki yıl."]),
            t("Aileniz burada mı?", "Оилаатон ин ҷост?", "Бигӯ: не, оилаам он ҷо", "Hayır, ailem orada.",
              "Не, оилаам он ҷо.", ["Hayır, memlekette."]),
            t("Zor olmalı.", "Душвор бошад.", "Бигӯ: ҳа, каме", "Evet, biraz.", "Ҳа, каме.", ["Evet."]),
        ]),
        ("Дар бораи худам", [
            s("Ben taksi şoförüyüm.", "Ман ронандаи таксиам.", None),
            s("İki çocuğum var.", "Ду фарзанд дорам.", None),
            s("Türkçe öğreniyorum.", "Туркӣ меомӯзам.", None),
            s("İstanbul'u seviyorum.", "Истанбулро дӯст медорам.", None),
            s("Memleketim çok güzel.", "Ватанам хеле зебо.", None),
            s("Dağlar çok yüksek.", "Кӯҳҳо хеле баланд.", None),
        ]),
        ("Тоҷикистон чӣ гуна?", [
            t("Tacikistan nasıl bir yer?", "Тоҷикистон чӣ гуна ҷой аст?", "Бигӯ: ватанам хеле зебо",
              "Memleketim çok güzel.", "Ватанам хеле зебо.", ["Çok güzel."]),
            t("Dağlar var mı?", "Кӯҳ ҳаст?", "Бигӯ: ҳа, кӯҳҳо хеле баланд", "Evet, dağlar çok yüksek.",
              "Ҳа, кӯҳҳо хеле баланд.", ["Evet, çok dağ var."]),
            t("Çocuğunuz var mı?", "Фарзанд доред?", "Бигӯ: ду фарзанд дорам", "İki çocuğum var.",
              "Ду фарзанд дорам.", ["Evet, iki."]),
        ]),
        ("Ҳаво ва роҳ", [
            s("Bugün çok sıcak.", "Имрӯз хеле гарм.", None),
            s("Yağmur yağıyor.", "Борон меборад.", None),
            s("Akşam trafik çok.", "Шом роҳбандӣ зиёд.", None),
            s("Klimayı açayım mı?", "Кондитсионерро кушоям?", None),
            s("Müzik açayım mı?", "Мусиқӣ монам?", None),
            s("Sessiz olsun.", "Ором бошад.", None),
        ]),
        ("Кондитсионер?", [
            t("Bugün çok sıcak!", "Имрӯз хеле гарм!", "Бипурс: кондитсионерро кушоям?", "Klimayı açayım mı?",
              "Кондитсионерро кушоям?", ["Klima açayım mı?"]),
            t("Evet, lütfen.", "Ҳа, лутфан.", "Бипурс: мусиқӣ монам?", "Müzik açayım mı?", "Мусиқӣ монам?",
              ["Müzik ister misiniz?"]),
            t("Hayır, sessiz olsun.", "Не, ором бошад.", "Бигӯ: хуб", "Tamam.", "Хуб.", ["Peki."]),
        ]),
        ("Миссия: мусофири пургап", [
            t("Nerelisiniz?", "Аз куҷоед?", "Бигӯ: аз Тоҷикистон", "Tacikistanlıyım.", "Аз Тоҷикистонам.",
              ["Tacikistan'dan."]),
            t("Kaç yıldır buradasınız?", "Чанд сол боз ин ҷоед?", "Бигӯ: ду сол боз", "İki yıldır.", "Ду сол боз.",
              ["İki yıl."]),
            t("Türkçeniz iyi!", "Туркии шумо хуб!", "Бигӯ: туркӣ меомӯзам", "Türkçe öğreniyorum.", "Туркӣ меомӯзам.",
              ["Biraz biliyorum."]),
            t("Bugün çok sıcak!", "Имрӯз хеле гарм!", "Бипурс: кондитсионерро кушоям?", "Klimayı açayım mı?",
              "Кондитсионерро кушоям?", ["Klima açayım mı?"]),
        ]),
    ]))

# ═════════════════════ 11. Дар колонка ═════════════════════
made.append(pack("fuel_tr_tg", "Benzinlikte", "Дар колонка", "⛽", 11, DR,
    "Шумо ба колонкаи бензин меравед: мегӯед, ки кадом сӯзишворӣ ва чӣ қадар, мепурсед, ки бод "
    "ва шустани мошин ҳаст ва пардохт мекунед.",
    [
        ("Колонка", [
            w("Benzinlik", "колонка (АЗС)", None),
            w("Benzin", "бензин", None),
            w("Mazot", "солярка (дизел)", None),
            w("Litre", "литр", None),
            w("Hava", "бод (ҳаво)", None),
            w("Yıkama", "шустан", None),
        ]),
        ("Пур кунед", [
            t("Merhaba! Ne alırsınız?", "Салом! Чӣ мегиред?", "Бигӯ: бензин, лутфан", "Benzin lütfen.",
              "Бензин, лутфан.", ["Benzin."]),
            t("Ne kadar?", "Чӣ қадар?", "Бигӯ: пур кунед", "Full lütfen.", "Пур кунед.", ["Depoyu doldurun."]),
            t("Tamam.", "Хуб.", "Ташаккур гӯй", "Teşekkürler.", "Ташаккур.", ["Sağ olun."]),
        ]),
        ("Ибораҳо", [
            s("Full lütfen", "Пур кунед", None),
            s("Yüz liralık", "Ба сад лира", None),
            w("Mazot", "дизел", None),
            s("Hava basmak", "Бод додан", None),
            s("Kartla ödeyeceğim", "Бо корт медиҳам", None),
            s("Fiş lütfen", "Чек, лутфан", None),
        ]),
        ("Ба панҷсад лира", [
            t("Benzin mi, mazot mu?", "Бензин ё дизел?", "Бигӯ: дизел", "Mazot.", "Дизел.", ["Mazot lütfen."]),
            t("Ne kadar?", "Чӣ қадар?", "Бигӯ: ба панҷсад лира", "Beş yüz liralık.", "Ба панҷсад лира.",
              ["Beş yüz lira."]),
            t("Tamam, hemen.", "Хуб, ҳозир.", "Бигӯ: ташаккур", "Teşekkürler.", "Ташаккур.", ["Sağ olun."]),
        ]),
        ("Хизматҳо", [
            s("Hava nerede?", "Бод куҷост?", None),
            s("Yıkama var mı?", "Шустан ҳаст?", None),
            s("Yağa bakar mısınız?", "Ба равған нигоҳ мекунед?", None),
            s("Tuvalet nerede?", "Ҳоҷатхона куҷост?", None),
            s("Su alabilir miyim?", "Об гирам?", None),
            s("Kartla ödeyeceğim.", "Бо корт медиҳам.", None),
        ]),
        ("Бод ва равған", [
            t("Başka bir şey?", "Боз чизе?", "Бипурс: ба равған нигоҳ мекунед?", "Yağa bakar mısınız?",
              "Ба равған нигоҳ мекунед?", ["Yağı kontrol eder misiniz?"]),
            t("Yağ tamam.", "Равған хуб.", "Бипурс: бод куҷост?", "Hava nerede?", "Бод куҷост?",
              ["Hava basabilir miyim?"]),
            t("Arkada, solda.", "Дар қафо, тарафи чап.", "Ташаккур гӯй", "Teşekkürler.", "Ташаккур.", ["Sağ olun."]),
        ]),
        ("Пардохт", [
            s("Pompa üç.", "Колонкаи се.", None),
            s("Benzin kartı geçer mi?", "Корти бензин мегузарад?", None),
            s("Şirket faturası lazım.", "Фактураи ширкат лозим.", None),
            s("Vergi numarası burada.", "Рақами андоз ин ҷо.", None),
            s("Fiş lütfen.", "Чек, лутфан.", None),
            s("Kolay gelsin!", "Кор осон шавад!", None),
        ]),
        ("Фактура", [
            t("Hangi pompa?", "Кадом колонка?", "Бигӯ: колонкаи се", "Pompa üç.", "Колонкаи се.", ["Üç numara."]),
            t("Beş yüz lira.", "Панҷсад лира.", "Бигӯ: фактураи ширкат лозим", "Şirket faturası lazım.",
              "Фактураи ширкат лозим.", ["Fatura lütfen."]),
            t("Vergi numarası?", "Рақами андоз?", "Бигӯ: рақами андоз ин ҷо", "Vergi numarası burada.",
              "Рақами андоз ин ҷо.", ["Buyurun."]),
        ]),
        ("Миссия: бак холӣ", [
            t("Merhaba! Benzin mi, mazot mu?", "Салом! Бензин ё дизел?", "Бигӯ: дизел, пур кунед",
              "Mazot, full lütfen.", "Дизел, пур кунед.", ["Mazot, full."]),
            t("Tamam. Başka bir şey?", "Хуб. Боз чизе?", "Бипурс: бод куҷост?", "Hava nerede?", "Бод куҷост?",
              ["Hava basabilir miyim?"]),
            t("Arkada. Nasıl ödersiniz?", "Дар қафо. Чӣ тавр медиҳед?", "Бигӯ: бо корт медиҳам",
              "Kartla ödeyeceğim.", "Бо корт медиҳам.", ["Kartla."]),
            t("Tamam. Fiş ister misiniz?", "Хуб. Чек мехоҳед?", "Бигӯ: ҳа, чек, лутфан", "Evet, fiş lütfen.",
              "Ҳа, чек, лутфан.", ["Evet."]),
        ]),
    ]))

# ═════════════════════ 12. Роҳбандӣ ═════════════════════
made.append(pack("traffic_tr_tg", "Trafikte", "Роҳбандӣ", "🚦", 12, DR,
    "Истанбул ва роҳбандӣ: шумо ба мусофир ё диспетчер мегӯед, ки дер мемонед, роҳи дигар "
    "пешниҳод мекунед ва вақти расиданро мегӯед.",
    [
        ("Роҳ", [
            w("Trafik", "роҳбандӣ (пробка)", None),
            w("Kaza", "садама", None),
            w("Otoyol", "шоҳроҳ", None),
            w("Geç", "дер", None),
            w("Erken", "барвақт", None),
            w("Polis", "полис", None),
        ]),
        ("Дер мемонем", [
            t("Neden durduk?", "Чаро истодем?", "Бигӯ: роҳбандӣ зиёд", "Çok trafik var.", "Роҳбандӣ зиёд.",
              ["Trafik var."]),
            t("Ne kadar sürer?", "Чӣ қадар мегирад?", "Бигӯ: даҳ дақиқа", "On dakika.", "Даҳ дақиқа.",
              ["Belki on dakika."]),
            t("Tamam.", "Хуб.", "Бигӯ: бубахшед", "Kusura bakmayın.", "Маъзур доред.", ["Özür dilerim."]),
        ]),
        ("Ибораҳо", [
            s("Çok trafik", "Роҳбандӣ зиёд", None),
            s("İleride kaza", "Пештар садама", None),
            s("Geç kalıyoruz", "Дер мемонем", None),
            s("Başka yol", "Роҳи дигар", None),
            s("Otoyoldan gidelim", "Аз шоҳроҳ равем", None),
            s("Yarım saat", "Ним соат", None),
        ]),
        ("Роҳи дигар", [
            t("Uçağım var, geç kalıyorum!", "Ҳавопаймо дорам, дер мемонам!", "Бигӯ: аз шоҳроҳ равем",
              "Otoyoldan gidelim.", "Аз шоҳроҳ равем.", ["Başka yoldan gidelim."]),
            t("Daha hızlı mı?", "Тезтар аст?", "Бигӯ: ҳа, вале пулакӣ", "Evet, ama ücretli.", "Ҳа, вале пулакӣ.",
              ["Evet."]),
            t("Olur, gidelim.", "Мешавад, равем.", "Бигӯ: хуб", "Tamam.", "Хуб.", ["Peki."]),
        ]),
        ("Ба мусофир хабар медиҳам", [
            s("İleride kaza var.", "Пештар садама ҳаст.", None),
            s("Yol kapalı.", "Роҳ баста.", None),
            s("Biraz geç kalacağız.", "Каме дер мемонем.", None),
            s("Yaklaşık yarım saat.", "Тақрибан ним соат.", None),
            s("Navigasyon gösteriyor.", "Навигатор нишон медиҳад.", None),
            s("Elimden geleni yapıyorum.", "Аз дастам омадаро мекунам.", None),
        ]),
        ("Садама", [
            t("Ne oldu?", "Чӣ шуд?", "Бигӯ: пештар садама ҳаст", "İleride kaza var.", "Пештар садама ҳаст.",
              ["Kaza var."]),
            t("Ne kadar geç kalırız?", "Чӣ қадар дер мемонем?", "Бигӯ: тақрибан ним соат", "Yaklaşık yarım saat.",
              "Тақрибан ним соат.", ["Yarım saat."]),
            t("Hay aksi!", "Ох, бад шуд!", "Бигӯ: аз дастам омадаро мекунам", "Elimden geleni yapıyorum.",
              "Аз дастам омадаро мекунам.", ["Hızlı gidiyorum."]),
        ]),
        ("Ба диспетчер", [
            s("Trafikteyim abi.", "Дар роҳбандӣам, ака.", None),
            s("Yarım saat geç kalırım.", "Ним соат дер мемонам.", None),
            s("Müşteriye haber verin.", "Ба мизоҷ хабар диҳед.", None),
            s("Şimdi köprüdeyim.", "Ҳоло дар пулам.", None),
            s("Yolcu bekliyor mu?", "Мусофир интизор аст?", None),
            s("Tamam, anladım.", "Хуб, фаҳмидам.", None),
        ]),
        ("Занги диспетчер", [
            t("Alo, neredesin?", "Ало, куҷоӣ?", "Бигӯ: дар роҳбандӣам, ака", "Trafikteyim abi.",
              "Дар роҳбандӣам, ака.", ["Trafikte."]),
            t("Ne zaman varırsın?", "Кай мерасӣ?", "Бигӯ: ним соат дер мемонам", "Yarım saat geç kalırım.",
              "Ним соат дер мемонам.", ["Yarım saat sonra."]),
            t("Tamam, müşteriye söylerim.", "Хуб, ба мизоҷ мегӯям.", "Бигӯ: ташаккур, ака", "Sağ ol abi.",
              "Ташаккур, ака.", ["Teşekkürler."]),
        ]),
        ("Миссия: роҳбандии шом", [
            t("Neden bu kadar yavaş?", "Чаро ин қадар оҳиста?", "Бигӯ: пештар садама ҳаст", "İleride kaza var.",
              "Пештар садама ҳаст.", ["Kaza var."]),
            t("Toplantım var, geç kalıyorum!", "Ҷаласа дорам, дер мемонам!", "Бигӯ: аз шоҳроҳ равем",
              "Otoyoldan gidelim.", "Аз шоҳроҳ равем.", ["Başka yoldan gidelim."]),
            t("Ne kadar sürer?", "Чӣ қадар мегирад?", "Бигӯ: тақрибан ним соат", "Yaklaşık yarım saat.",
              "Тақрибан ним соат.", ["Yarım saat."]),
            t("Tamam, hızlı lütfen.", "Хуб, тезтар, лутфан.", "Бигӯ: аз дастам омадаро мекунам",
              "Elimden geleni yapıyorum.", "Аз дастам омадаро мекунам.", ["Tamam."]),
        ]),
    ]))

# ═════════════════════ 13. Расонидани бор ═════════════════════
made.append(pack("delivery_tr_tg", "Kurye teslimatı", "Расонидани бор", "📦", 13, DR,
    "Шумо курйер ҳастед: бастаро мебаред, ба мизоҷ занг мезанед, дар даромадгоҳ ё домофон гап "
    "мезанед ва имзо мегиред.",
    [
        ("Курйер", [
            w("Kurye", "курйер", None),
            w("Paket", "баста", None),
            w("Kat", "қабат", None),
            w("Daire", "хонадон (квартира)", None),
            w("Zil", "занг (дари хона)", None),
            w("İmza", "имзо", None),
        ]),
        ("Домофон", [
            t("Kim o?", "Кист?", "Бигӯ: курйер, баста дорам", "Kurye, paketiniz var.", "Курйер, бастаатон ҳаст.",
              ["Kurye geldi."]),
            t("Tamam, açıyorum.", "Хуб, мекушоям.", "Бипурс: кадом қабат?", "Hangi kat?", "Кадом қабат?",
              ["Kaçıncı kat?"]),
            t("Beşinci kat.", "Қабати панҷум.", "Бигӯ: хуб, меоям", "Tamam, geliyorum.", "Хуб, меоям.",
              ["Geliyorum."]),
        ]),
        ("Ибораҳо", [
            s("Paketiniz var", "Бастаатон ҳаст", None),
            s("Hangi kat?", "Кадом қабат?", None),
            s("Daire numarası?", "Рақами хонадон?", None),
            s("Buraya imza", "Ин ҷо имзо", None),
            s("Kapıya bırakayım?", "Назди дар монам?", None),
            s("İyi günler", "Рӯзи хуш", None),
        ]),
        ("Имзо", [
            t("Merhaba! Benim paketim mi?", "Салом! Бастаи ман?", "Бипурс: номатон Али Йылмаз?",
              "Adınız Ali Yılmaz mı?", "Номатон Али Йылмаз?", ["Ali Bey mi?"]),
            t("Evet, benim.", "Ҳа, манам.", "Бигӯ: ин ҷо имзо, лутфан", "Buraya imza lütfen.", "Ин ҷо имзо, лутфан.",
              ["İmza lütfen."]),
            t("Tamam. Teşekkürler!", "Хуб. Ташаккур!", "Бигӯ: рӯзи хуш", "İyi günler!", "Рӯзи хуш!", ["Kolay gelsin."]),
        ]),
        ("Ба мизоҷ занг мезанам", [
            s("Ben kuryeyim.", "Ман курйерам.", None),
            s("Kapının önündeyim.", "Дар назди дарам.", None),
            s("Zil çalışmıyor.", "Занг кор намекунад.", None),
            s("Evde misiniz?", "Дар хонаед?", None),
            s("Komşuya bırakayım mı?", "Ба ҳамсоя диҳам?", None),
            s("Yarın tekrar gelirim.", "Фардо боз меоям.", None),
        ]),
        ("Занг кор намекунад", [
            t("Alo?", "Ало?", "Бигӯ: ман курйерам, дар назди дарам", "Kuryeyim, kapının önündeyim.",
              "Курйерам, дар назди дарам.", ["Kapıdayım."]),
            t("Zili çalın.", "Зангро занед.", "Бигӯ: занг кор намекунад", "Zil çalışmıyor.", "Занг кор намекунад.",
              ["Zil bozuk."]),
            t("Tamam, iniyorum.", "Хуб, мефароям.", "Бигӯ: хуб, интизорам", "Tamam, bekliyorum.", "Хуб, интизорам.",
              ["Bekliyorum."]),
        ]),
        ("Мизоҷ дар хона нест", [
            s("Evde değilim.", "Дар хона нестам.", None),
            s("Kapıya bırakın.", "Назди дар монед.", None),
            s("Bırakamam, imza lazım.", "Монда наметавонам, имзо лозим.", None),
            s("Ne zaman evdesiniz?", "Кай дар хонаед?", None),
            s("Akşam altıda.", "Шом соати шаш.", None),
            s("Altıda gelirim.", "Соати шаш меоям.", None),
        ]),
        ("Кай дар хонаед?", [
            t("Evde değilim!", "Дар хона нестам!", "Бипурс: кай дар хонаед?", "Ne zaman evdesiniz?",
              "Кай дар хонаед?", ["Ne zaman gelirsiniz?"]),
            t("Kapıya bırakın.", "Назди дар монед.", "Бигӯ: монда наметавонам, имзо лозим", "Bırakamam, imza lazım.",
              "Монда наметавонам, имзо лозим.", ["İmza lazım."]),
            t("Akşam altıda evdeyim.", "Шом соати шаш дар хонаам.", "Бигӯ: соати шаш меоям", "Altıda gelirim.",
              "Соати шаш меоям.", ["Tamam, altıda."]),
        ]),
        ("Миссия: бастаи охирин", [
            t("Kim o?", "Кист?", "Бигӯ: курйер, баста дорам", "Kurye, paketiniz var.", "Курйер, бастаатон ҳаст.",
              ["Kurye geldi."]),
            t("Tamam, açıyorum.", "Хуб, мекушоям.", "Бипурс: кадом қабат?", "Hangi kat?", "Кадом қабат?",
              ["Kaçıncı kat?"]),
            t("Üçüncü kat, daire yedi.", "Қабати сеюм, хонадони ҳафт.", "Бигӯ: хуб, меоям", "Tamam, geliyorum.",
              "Хуб, меоям.", ["Geliyorum."]),
            t("Merhaba! Teşekkürler.", "Салом! Ташаккур.", "Бигӯ: ин ҷо имзо, лутфан", "Buraya imza lütfen.",
              "Ин ҷо имзо, лутфан.", ["İmza lütfen."]),
        ]),
    ]))

# ═════════════════════ 15. Занг ба мизоҷ ═════════════════════
made.append(pack("customer_call_tr_tg", "Müşteriyi aramak", "Занг ба мизоҷ", "📞", 15, DR,
    "Шумо ба мизоҷ занг мезанед: мегӯед, ки кай мерасед, суроғаро дақиқ мекунед, ҷои вохӯриро "
    "мепурсед ва дар бораи таъхир узр мепурсед.",
    [
        ("Занг", [
            w("Arama", "занг", None),
            w("Numara", "рақам", None),
            w("Mesaj", "паём", None),
            w("Konum", "ҷойгиршавӣ (локатсия)", None),
            w("Giriş", "даромадгоҳ", None),
            w("Bina", "бино", None),
        ]),
        ("Ман дар роҳам", [
            t("Alo?", "Ало?", "Бигӯ: салом, ман ронанда", "Merhaba, ben şoförünüz.", "Салом, ман ронандаи шумо.",
              ["Merhaba, taksi."]),
            t("Ne zaman gelirsiniz?", "Кай меоед?", "Бигӯ: панҷ дақиқа", "Beş dakika.", "Панҷ дақиқа.",
              ["Beş dakika sonra."]),
            t("Tamam, bekliyorum.", "Хуб, интизорам.", "Бигӯ: хуб, то дидан", "Tamam, görüşürüz.", "Хуб, то дидан.",
              ["Görüşürüz."]),
        ]),
        ("Ибораҳо", [
            s("Yoldayım", "Дар роҳам", None),
            s("Beş dakika", "Панҷ дақиқа", None),
            s("Konum atın", "Локатсия фиристед", None),
            s("Hangi giriş?", "Кадом даромадгоҳ?", None),
            s("Ben geldim", "Ман омадам", None),
            s("Görüşürüz", "То дидан", None),
        ]),
        ("Локатсия", [
            t("Adresi bulamıyor musunuz?", "Суроғаро ёфта наметавонед?", "Бигӯ: локатсия фиристед, лутфан",
              "Konum atın lütfen.", "Локатсия фиристед, лутфан.", ["Konum lütfen."]),
            t("Tamam, atıyorum.", "Хуб, мефиристам.", "Бипурс: кадом даромадгоҳ?", "Hangi giriş?",
              "Кадом даромадгоҳ?", ["Hangi kapı?"]),
            t("B girişi.", "Даромадгоҳи B.", "Бигӯ: хуб, фаҳмидам", "Tamam, anladım.", "Хуб, фаҳмидам.",
              ["Anladım."]),
        ]),
        ("Дақиқ мекунам", [
            s("Adresi doğruluyorum.", "Суроғаро месанҷам.", None),
            s("Bina numarası ne?", "Рақами бино чист?", None),
            s("Mavi binanın önündeyim.", "Дар назди бинои кабудам.", None),
            s("Sizi göremiyorum.", "Шуморо намебинам.", None),
            s("Ne giyiyorsunuz?", "Чӣ пӯшидаед?", None),
            s("Sizi gördüm!", "Шуморо дидам!", None),
        ]),
        ("Шуморо намебинам", [
            t("Ben dışarıdayım.", "Ман берунам.", "Бигӯ: шуморо намебинам", "Sizi göremiyorum.", "Шуморо намебинам.",
              ["Göremiyorum."]),
            t("Kırmızı mont giyiyorum.", "Куртаи сурх пӯшидаам.", "Бигӯ: дар назди бинои кабудам",
              "Mavi binanın önündeyim.", "Дар назди бинои кабудам.", ["Mavi binadayım."]),
            t("Aa, sizi gördüm!", "О, шуморо дидам!", "Бигӯ: ман ҳам шуморо дидам", "Ben de sizi gördüm!",
              "Ман ҳам шуморо дидам!", ["Sizi gördüm!"]),
        ]),
        ("Таъхир", [
            s("Kusura bakmayın, gecikiyorum.", "Бубахшед, дер мекунам.", None),
            s("Trafik çok yoğun.", "Роҳбандӣ хеле сахт.", None),
            s("On dakika gecikirim.", "Даҳ дақиқа дер мекунам.", None),
            s("Bekleyebilir misiniz?", "Интизор шуда метавонед?", None),
            s("Çok teşekkür ederim.", "Хеле ташаккур.", None),
            s("Hemen geliyorum.", "Ҳозир меоям.", None),
        ]),
        ("Дер мекунам", [
            t("Alo? Neredesiniz?", "Ало? Куҷоед?", "Бигӯ: бубахшед, дер мекунам", "Kusura bakmayın, gecikiyorum.",
              "Бубахшед, дер мекунам.", ["Gecikiyorum."]),
            t("Ne kadar?", "Чӣ қадар?", "Бигӯ: даҳ дақиқа дер мекунам", "On dakika gecikirim.",
              "Даҳ дақиқа дер мекунам.", ["On dakika."]),
            t("Tamam, beklerim.", "Хуб, интизор мешавам.", "Бигӯ: хеле ташаккур", "Çok teşekkür ederim.",
              "Хеле ташаккур.", ["Teşekkürler."]),
        ]),
        ("Миссия: мизоҷро ёфтан", [
            t("Alo? Taksi nerede?", "Ало? Такси куҷост?", "Бигӯ: бубахшед, дер мекунам",
              "Kusura bakmayın, gecikiyorum.", "Бубахшед, дер мекунам.", ["Gecikiyorum."]),
            t("Ne kadar?", "Чӣ қадар?", "Бигӯ: панҷ дақиқа. Локатсия фиристед", "Beş dakika. Konum atın.",
              "Панҷ дақиқа. Локатсия фиристед.", ["Beş dakika."]),
            t("Tamam, attım.", "Хуб, фиристодам.", "Бипурс: кадом даромадгоҳ?", "Hangi giriş?", "Кадом даромадгоҳ?",
              ["Hangi kapı?"]),
            t("A girişi.", "Даромадгоҳи A.", "Бигӯ: хуб, то дидан", "Tamam, görüşürüz.", "Хуб, то дидан.",
              ["Görüşürüz."]),
        ]),
    ], mission_mode="call"))

# ═════════════════════ 17. Полиси роҳ ═════════════════════
made.append(pack("traffic_stop_tr_tg", "Trafik polisi", "Полиси роҳ", "👮", 17, DR,
    "Полиси роҳ шуморо нигоҳ медорад: шумо ором ҳуҷҷатҳоро медиҳед, ба саволҳо ҷавоб медиҳед ва "
    "агар чизе нафаҳмед, хоҳиш мекунед, ки оҳиста гӯянд.",
    [
        ("Полис", [
            w("Polis", "полис", None),
            w("Ehliyet", "шаҳодатномаи ронандагӣ", None),
            w("Kimlik", "шаҳодатнома (ID)", None),
            w("Ceza", "ҷарима", None),
            w("Hız", "суръат", None),
            w("Sigorta", "суғурта", None),
        ]),
        ("Ҳуҷҷатҳо", [
            t("İyi günler. Ehliyet ve ruhsat.", "Рӯз ба хайр. Шаҳодатнома ва ҳуҷҷат.", "Бигӯ: марҳамат", "Buyurun.",
              "Марҳамат.", ["Buyurun memur bey."]),
            t("Kimliğiniz?", "Шаҳодатномаатон?", "Бигӯ: иҷозати иқомат, марҳамат", "İkamet izni, buyurun.",
              "Иҷозати иқомат, марҳамат.", ["Buyurun."]),
            t("Tamam, bekleyin.", "Хуб, интизор шавед.", "Бигӯ: хуб", "Tamam.", "Хуб.", ["Peki."]),
        ]),
        ("Ибораҳо", [
            s("Memur bey", "Ҷаноби полис", None),
            s("İkamet izni", "Иҷозати иқомат", None),
            s("Yavaş lütfen", "Оҳиста, лутфан", None),
            s("Anlamadım", "Нафаҳмидам", None),
            s("Özür dilerim", "Бубахшед", None),
            s("Sigorta burada", "Суғурта ин ҷо", None),
        ]),
        ("Нафаҳмидам", [
            t("Bagajı açın.", "Бағоҷдонро кушоед.", "Бигӯ: бубахшед, нафаҳмидам", "Özür dilerim, anlamadım.",
              "Бубахшед, нафаҳмидам.", ["Anlamadım."]),
            t("Bagaj. Açın lütfen.", "Бағоҷдон. Кушоед, лутфан.", "Бигӯ: хуб, мекушоям", "Tamam, açıyorum.",
              "Хуб, мекушоям.", ["Açıyorum."]),
            t("Teşekkürler.", "Ташаккур.", "Бигӯ: арзише надорад", "Rica ederim.", "Арзише надорад.",
              ["Buyurun."]),
        ]),
        ("Саволҳои полис", [
            s("Hızınız yüksekti.", "Суръататон баланд буд.", None),
            s("Kemer takılı değil.", "Камарбанд баста нест.", None),
            s("Nereye gidiyorsunuz?", "Ба куҷо меравед?", None),
            s("İşe gidiyorum.", "Ба кор меравам.", None),
            s("Ben taksi şoförüyüm.", "Ман ронандаи таксиам.", None),
            s("Bir daha olmaz.", "Дигар намешавад.", None),
        ]),
        ("Суръат", [
            t("Hızınız yüksekti.", "Суръататон баланд буд.", "Бигӯ: бубахшед, дигар намешавад",
              "Özür dilerim, bir daha olmaz.", "Бубахшед, дигар намешавад.", ["Bir daha olmaz."]),
            t("Nereye gidiyorsunuz?", "Ба куҷо меравед?", "Бигӯ: ба кор меравам", "İşe gidiyorum.", "Ба кор меравам.",
              ["İşe."]),
            t("Ne iş yapıyorsunuz?", "Чӣ кор мекунед?", "Бигӯ: ман ронандаи таксиам", "Ben taksi şoförüyüm.",
              "Ман ронандаи таксиам.", ["Şoförüm."]),
        ]),
        ("Ҷарима", [
            s("Ceza yazıyorum.", "Ҷарима менависам.", None),
            s("Ceza ne kadar?", "Ҷарима чанд аст?", None),
            s("Nerede ödenir?", "Дар куҷо пардохт мешавад?", None),
            s("Bankada veya internetten.", "Дар бонк ё интернет.", None),
            s("Bu sefer uyarı.", "Ин дафъа огоҳӣ.", None),
            s("Çok teşekkürler.", "Ташаккури зиёд.", None),
        ]),
        ("Огоҳӣ", [
            t("Kemer takılı değil.", "Камарбанд баста нест.", "Бигӯ: бубахшед", "Özür dilerim.", "Бубахшед.",
              ["Kusura bakmayın."]),
            t("Bu sefer uyarı.", "Ин дафъа огоҳӣ.", "Бигӯ: ташаккури зиёд", "Çok teşekkürler.", "Ташаккури зиёд.",
              ["Teşekkürler memur bey."]),
            t("Bir daha olmasın.", "Дигар набошад.", "Бигӯ: дигар намешавад", "Bir daha olmaz.", "Дигар намешавад.",
              ["Olmaz."]),
        ]),
        ("Миссия: нуқтаи назорат", [
            t("İyi günler. Ehliyet lütfen.", "Рӯз ба хайр. Шаҳодатнома, лутфан.", "Бигӯ: марҳамат", "Buyurun.",
              "Марҳамат.", ["Buyurun memur bey."]),
            t("Hızınız yüksekti.", "Суръататон баланд буд.", "Бигӯ: бубахшед, дигар намешавад",
              "Özür dilerim, bir daha olmaz.", "Бубахшед, дигар намешавад.", ["Bir daha olmaz."]),
            t("Ceza yazıyorum.", "Ҷарима менависам.", "Бипурс: ҷарима чанд аст?", "Ceza ne kadar?",
              "Ҷарима чанд аст?", ["Ne kadar?"]),
            t("Bin lira. İyi günler.", "Ҳазор лира. Рӯзи хуш.", "Бигӯ: рӯзи хуш", "İyi günler.", "Рӯзи хуш.",
              ["Teşekkürler."]),
        ]),
    ]))

# ═════════════════════ 18. Таъмири мошин ═════════════════════
made.append(pack("repair_tr_tg", "Oto tamirde", "Таъмири мошин", "🔧", 18, DR,
    "Мошин вайрон шуд: шумо ба устои автосервис занг мезанед, мегӯед, ки чӣ шуд, мепурсед, ки "
    "кай тайёр мешавад ва чанд пул.",
    [
        ("Автосервис", [
            w("Tamirci", "устои мошин", None),
            w("Motor", "мотор", None),
            w("Fren", "тормоз", None),
            w("Akü", "аккумулятор", None),
            w("Ses", "овоз", None),
            w("Parça", "қисм (запчаст)", None),
        ]),
        ("Мошин вайрон", [
            t("Alo, oto tamir.", "Ало, автосервис.", "Бигӯ: мошинам вайрон шуд", "Arabam bozuldu.",
              "Мошинам вайрон шуд.", ["Araba bozuk."]),
            t("Ne oldu?", "Чӣ шуд?", "Бигӯ: мотор оташ намегирад", "Motor çalışmıyor.", "Мотор кор намекунад.",
              ["Çalışmıyor."]),
            t("Getirin, bakalım.", "Биёред, мебинем.", "Бигӯ: хуб, ташаккур", "Tamam, teşekkürler.",
              "Хуб, ташаккур.", ["Tamam abi."]),
        ]),
        ("Ибораҳо", [
            s("Arabam bozuldu", "Мошинам вайрон шуд", None),
            s("Garip ses", "Овози аҷиб", None),
            s("Fren tutmuyor", "Тормоз намегирад", None),
            s("Akü bitti", "Аккумулятор нишаст", None),
            s("Hazır mı?", "Тайёр аст?", None),
            s("Fiyat ne?", "Нарх чанд?", None),
        ]),
        ("Овози аҷиб", [
            t("Sorun ne?", "Мушкил чист?", "Бигӯ: овози аҷиб ҳаст", "Garip bir ses var.", "Овози аҷиб ҳаст.",
              ["Garip ses."]),
            t("Nereden?", "Аз куҷо?", "Бигӯ: аз пеш", "Önden.", "Аз пеш.", ["Ön taraftan."]),
            t("Fren olabilir.", "Тормоз шояд.", "Бипурс: кай тайёр?", "Ne zaman hazır?", "Кай тайёр?",
              ["Ne zaman biter?"]),
        ]),
        ("Мушкилро мегӯям", [
            s("Fren tutmuyor.", "Тормоз намегирад.", None),
            s("Motor ısınıyor.", "Мотор гарм мешавад.", None),
            s("Akü bitti galiba.", "Аккумулятор нишаст, гумон кунам.", None),
            s("Işık yanıyor.", "Чароғ месӯзад.", None),
            s("Sabah çalışmadı.", "Субҳ оташ нагирифт.", None),
            s("Acil lazım.", "Фаврӣ лозим.", None),
        ]),
        ("Чароғ месӯзад", [
            t("Ne oldu?", "Чӣ шуд?", "Бигӯ: субҳ оташ нагирифт", "Sabah çalışmadı.", "Субҳ оташ нагирифт.",
              ["Çalışmadı."]),
            t("Işık yanıyor mu?", "Чароғ месӯзад?", "Бигӯ: ҳа, чароғ месӯзад", "Evet, ışık yanıyor.",
              "Ҳа, чароғ месӯзад.", ["Evet, kırmızı."]),
            t("Akü olabilir.", "Аккумулятор шояд.", "Бигӯ: фаврӣ лозим", "Acil lazım.", "Фаврӣ лозим.",
              ["İşim var, acil."]),
        ]),
        ("Нарх ва вақт", [
            s("Yarın hazır.", "Фардо тайёр.", None),
            s("Parça lazım.", "Қисм лозим.", None),
            s("Bin beş yüz lira.", "Ҳазору панҷсад лира.", None),
            s("Biraz pahalı.", "Каме қимат.", None),
            s("İndirim olur mu?", "Тахфиф мешавад?", None),
            s("Tamam, yapın.", "Хуб, кунед.", None),
        ]),
        ("Чанд пул?", [
            t("Fren balatası lazım.", "Колодкаи тормоз лозим.", "Бипурс: чанд пул мешавад?", "Ne kadar tutar?",
              "Чанд пул мешавад?", ["Ne kadar?"]),
            t("Bin beş yüz lira.", "Ҳазору панҷсад лира.", "Бипурс: тахфиф мешавад?", "İndirim olur mu?",
              "Тахфиф мешавад?", ["Biraz pahalı."]),
            t("Bin dört yüz olur.", "Ҳазору чорсад мешавад.", "Бигӯ: хуб, кунед", "Tamam, yapın.", "Хуб, кунед.",
              ["Tamam abi."]),
        ]),
        ("Миссия: тормози вайрон", [
            t("Alo, oto tamir.", "Ало, автосервис.", "Бигӯ: мошинам вайрон шуд", "Arabam bozuldu.",
              "Мошинам вайрон шуд.", ["Araba bozuk."]),
            t("Ne oldu?", "Чӣ шуд?", "Бигӯ: тормоз намегирад", "Fren tutmuyor.", "Тормоз намегирад.",
              ["Fren kötü."]),
            t("Getirin. Yarın hazır.", "Биёред. Фардо тайёр.", "Бипурс: чанд пул мешавад?", "Ne kadar tutar?",
              "Чанд пул мешавад?", ["Ne kadar?"]),
            t("Bin lira civarı.", "Тақрибан ҳазор лира.", "Бигӯ: хуб, меоям", "Tamam, geliyorum.", "Хуб, меоям.",
              ["Tamam abi."]),
        ]),
    ], mission_mode="call"))

# ═════════════════════ 19. Садама ═════════════════════
made.append(pack("accident_tr_tg", "Kaza", "Садама", "💥", 19, DR,
    "Садамаи хурд рӯй дод: шумо мепурсед, ки касе захмӣ нашуд, ҳуҷҷат ва суғуртаро иваз мекунед, "
    "аксбардорӣ мекунед ва ба полис ё ширкат занг мезанед.",
    [
        ("Садама", [
            w("Kaza", "садама", None),
            w("Yaralı", "захмӣ", None),
            w("Hasar", "зарар", None),
            w("Tutanak", "протокол", None),
            w("Fotoğraf", "акс", None),
            w("Ambulans", "ёрии таъҷилӣ", None),
        ]),
        ("Ҳама сиҳат?", [
            t("Ah! Ne oldu?", "Оҳ! Чӣ шуд?", "Бипурс: шумо хубед?", "İyi misiniz?", "Шумо хубед?",
              ["Bir şey var mı?"]),
            t("Evet, iyiyim.", "Ҳа, хубам.", "Бипурс: захмӣ ҳаст?", "Yaralı var mı?", "Захмӣ ҳаст?",
              ["Herkes iyi mi?"]),
            t("Hayır, yok.", "Не, нест.", "Бигӯ: худоро шукр", "Allah'a şükür.", "Худоро шукр.", ["Çok şükür."]),
        ]),
        ("Ибораҳо", [
            s("İyi misiniz?", "Хубед?", None),
            s("Yaralı yok", "Захмӣ нест", None),
            s("Polisi arayalım", "Ба полис занг занем", None),
            s("Fotoğraf çekiyorum", "Акс мегирам", None),
            s("Sigorta var?", "Суғурта ҳаст?", None),
            w("Tutanak", "протокол", None),
        ]),
        ("Суғурта", [
            t("Sigortanız var mı?", "Суғурта доред?", "Бигӯ: ҳа, ин ҷо", "Evet, burada.", "Ҳа, ин ҷо.",
              ["Var, buyurun."]),
            t("Tutanak yazalım.", "Протокол нависем.", "Бигӯ: хуб, акс мегирам", "Tamam, fotoğraf çekiyorum.",
              "Хуб, акс мегирам.", ["Önce fotoğraf."]),
            t("Tamam.", "Хуб.", "Бигӯ: ба полис занг занем", "Polisi arayalım.", "Ба полис занг занем.",
              ["Polis çağıralım."]),
        ]),
        ("Чӣ шуд?", [
            s("Arkadan çarptı.", "Аз қафо зад.", None),
            s("Ben duruyordum.", "Ман истода будам.", None),
            s("Işık kırmızıydı.", "Чароғак сурх буд.", None),
            s("Tampon kırıldı.", "Бампер шикаст.", None),
            s("Hasar küçük.", "Зарар хурд аст.", None),
            s("Benim hatam değil.", "Хатои ман нест.", None),
        ]),
        ("Ба полис", [
            t("Ne oldu?", "Чӣ шуд?", "Бигӯ: аз қафо зад", "Arkadan çarptı.", "Аз қафо зад.",
              ["Arkadan çarptı memur bey."]),
            t("Siz ne yapıyordunuz?", "Шумо чӣ мекардед?", "Бигӯ: ман истода будам, чароғак сурх буд",
              "Duruyordum, ışık kırmızıydı.", "Истода будам, чароғак сурх буд.", ["Ben duruyordum."]),
            t("Yaralı var mı?", "Захмӣ ҳаст?", "Бигӯ: не, зарар хурд аст", "Hayır, hasar küçük.",
              "Не, зарар хурд аст.", ["Yaralı yok."]),
        ]),
        ("Ба ширкат", [
            s("Abi, kaza oldu.", "Ака, садама шуд.", None),
            s("Herkes iyi.", "Ҳама хуб.", None),
            s("Polis burada.", "Полис ин ҷо.", None),
            s("Araba çalışıyor.", "Мошин кор мекунад.", None),
            s("Fotoğrafları atıyorum.", "Аксҳоро мефиристам.", None),
            s("Ne yapayım?", "Чӣ кор кунам?", None),
        ]),
        ("Занг ба мудир", [
            t("Alo, ne oldu?", "Ало, чӣ шуд?", "Бигӯ: ака, садама шуд", "Abi, kaza oldu.", "Ака, садама шуд.",
              ["Kaza oldu."]),
            t("Herkes iyi mi?", "Ҳама хубанд?", "Бигӯ: ҳа, ҳама хуб. Полис ин ҷо", "Evet, herkes iyi. Polis burada.",
              "Ҳа, ҳама хуб. Полис ин ҷо.", ["Herkes iyi."]),
            t("Tamam. Fotoğraf çek.", "Хуб. Акс гир.", "Бигӯ: аксҳоро мефиристам", "Fotoğrafları atıyorum.",
              "Аксҳоро мефиристам.", ["Atıyorum."]),
        ]),
        ("Миссия: садамаи хурд", [
            t("Pardon! İyi misiniz?", "Бубахшед! Хубед?", "Бигӯ: ҳа, хубам. Захмӣ ҳаст?",
              "Evet, iyiyim. Yaralı var mı?", "Ҳа, хубам. Захмӣ ҳаст?", ["İyiyim."]),
            t("Hayır, yok. Benim hatam.", "Не, нест. Хатои ман.", "Бипурс: суғурта доред?", "Sigortanız var mı?",
              "Суғурта доред?", ["Sigorta var mı?"]),
            t("Evet, burada.", "Ҳа, ин ҷо.", "Бигӯ: акс мегирам", "Fotoğraf çekiyorum.", "Акс мегирам.",
              ["Önce fotoğraf."]),
            t("Tamam. Tutanak yazalım.", "Хуб. Протокол нависем.", "Бигӯ: хуб", "Tamam.", "Хуб.", ["Olur."]),
        ]),
    ]))

# ═════════════════════ 20. Навбати корӣ ═════════════════════
made.append(pack("shift_tr_tg", "Vardiya", "Навбати корӣ", "🕒", 20, DR,
    "Шумо бо диспетчер навбат ва ҳисоботро муҳокима мекунед: кай сар мекунед, чанд фармоиш доштед, "
    "пули нақдро месупоред ва рӯзи истироҳат мепурсед.",
    [
        ("Навбат", [
            w("Vardiya", "навбат (смена)", None),
            w("Sipariş", "фармоиш", None),
            w("Kasa", "касса (пули ҷамъшуда)", None),
            w("Mola", "танаффус", None),
            w("Gece", "шаб", None),
            w("İzin", "рӯзи истироҳат", None),
        ]),
        ("Оғози навбат", [
            t("Günaydın! Hazır mısın?", "Субҳ ба хайр! Тайёрӣ?", "Бигӯ: ҳа, тайёрам", "Evet, hazırım.",
              "Ҳа, тайёрам.", ["Hazırım abi."]),
            t("Bugün çok sipariş var.", "Имрӯз фармоиш бисёр.", "Бипурс: кай танаффус?", "Mola ne zaman?",
              "Танаффус кай?", ["Mola var mı?"]),
            t("Saat birde.", "Соати як.", "Бигӯ: хуб", "Tamam.", "Хуб.", ["Peki abi."]),
        ]),
        ("Ибораҳо", [
            s("Vardiya başladı", "Навбат сар шуд", None),
            s("Mola saati", "Вақти танаффус", None),
            s("Gece vardiyası", "Навбати шаб", None),
            s("On sipariş", "Даҳ фармоиш", None),
            s("Kasayı teslim", "Супоридани касса", None),
            s("Yarın izinliyim", "Фардо истироҳатам", None),
        ]),
        ("Ҳисобот", [
            t("Bugün kaç sipariş?", "Имрӯз чанд фармоиш?", "Бигӯ: дувоздаҳ фармоиш", "On iki sipariş.",
              "Дувоздаҳ фармоиш.", ["On iki."]),
            t("Aferin! Nakit ne kadar?", "Офарин! Нақд чанд?", "Бигӯ: ҳаштсад лира", "Sekiz yüz lira.",
              "Ҳаштсад лира.", ["Sekiz yüz."]),
            t("Tamam, kasaya koy.", "Хуб, ба касса гузор.", "Бигӯ: хуб, ака", "Tamam abi.", "Хуб, ака.", ["Peki."]),
        ]),
        ("Ҷадвали ман", [
            s("Gece çalışabilirim.", "Шаб кор карда метавонам.", None),
            s("Pazar izinliyim.", "Якшанбе истироҳатам.", None),
            s("Bu hafta yorgunum.", "Ин ҳафта хастаам.", None),
            s("Ekstra vardiya istiyorum.", "Навбати иловагӣ мехоҳам.", None),
            s("Maaş ne zaman?", "Маош кай?", None),
            s("Ayın birinde.", "Якуми моҳ.", None),
        ]),
        ("Маош", [
            t("Bir sorun var mı?", "Мушкиле ҳаст?", "Бипурс: маош кай?", "Maaş ne zaman?", "Маош кай?",
              ["Maaş ne zaman yatar?"]),
            t("Ayın birinde.", "Якуми моҳ.", "Бигӯ: навбати иловагӣ мехоҳам", "Ekstra vardiya istiyorum.",
              "Навбати иловагӣ мехоҳам.", ["Daha çok çalışmak istiyorum."]),
            t("Tamam, gece olur mu?", "Хуб, шаб мешавад?", "Бигӯ: шаб кор карда метавонам", "Gece çalışabilirim.",
              "Шаб кор карда метавонам.", ["Olur."]),
        ]),
        ("Рӯзи истироҳат", [
            s("Yarın izin alabilir miyim?", "Фардо рухсат гирам?", None),
            s("Doktora gideceğim.", "Ба духтур меравам.", None),
            s("Kim yerime çalışır?", "Кӣ ба ҷоям кор мекунад?", None),
            s("Ahmet çalışabilir.", "Аҳмет кор карда метавонад.", None),
            s("Teşekkürler abi.", "Ташаккур, ака.", None),
            s("İyi akşamlar!", "Шоми хуш!", None),
        ]),
        ("Рухсат", [
            t("Ne istiyorsun?", "Чӣ мехоҳӣ?", "Бипурс: фардо рухсат гирам?", "Yarın izin alabilir miyim?",
              "Фардо рухсат гирам?", ["Yarın izin var mı?"]),
            t("Neden?", "Чаро?", "Бигӯ: ба духтур меравам", "Doktora gideceğim.", "Ба духтур меравам.",
              ["Doktora."]),
            t("Tamam, Ahmet çalışır.", "Хуб, Аҳмет кор мекунад.", "Бигӯ: ташаккур, ака", "Teşekkürler abi.",
              "Ташаккур, ака.", ["Sağ ol abi."]),
        ]),
        ("Миссия: охири навбат", [
            t("Vardiya bitti mi?", "Навбат тамом шуд?", "Бигӯ: ҳа, дувоздаҳ фармоиш", "Evet, on iki sipariş.",
              "Ҳа, дувоздаҳ фармоиш.", ["Bitti abi."]),
            t("Aferin! Nakit ne kadar?", "Офарин! Нақд чанд?", "Бигӯ: ҳаштсад лира", "Sekiz yüz lira.",
              "Ҳаштсад лира.", ["Sekiz yüz."]),
            t("Tamam. Yarın geliyor musun?", "Хуб. Фардо меоӣ?", "Бигӯ: не, ба духтур меравам",
              "Hayır, doktora gideceğim.", "Не, ба духтур меравам.", ["Yarın izin istiyorum."]),
            t("Tamam, geçmiş olsun.", "Хуб, шифо ёбӣ.", "Бигӯ: ташаккур, ака", "Teşekkürler abi.", "Ташаккур, ака.",
              ["Sağ ol abi."]),
        ]),
    ]))

finish(made)
