"""ТУРКӢ → тоҷикӣ, «Гуфтор» A1 — нишаи «Ҳаёти рӯзмарра» (`life`), 05.10.2026.

14 вазъият барои муҳоҷири тоҷик дар Туркия: фурудгоҳ, меҳмонхона, İstanbulkart, қаҳвахона,
бозор, Turkcell, пул фиристодан, дорухона, PTT, ҳамсояҳо, гум шудан, вақти холӣ, 112, сартарош.
Ҳамон slug/order/унвонҳои тоҷикии русӣ/олмонӣ/арабӣ. Роҳи `life` = 6 умумӣ + ин 14 → 20.

Қоидаҳо — `_tr_packs_lib.py`. chunks ≤ 2 калима, sentences ≤ 4. Рақамҳо бо ҳарф.

Аз ҷузвдони backend: python prisma/_tr-life-a1-packs.py
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _tr_packs_lib import *  # noqa: F401,F403

_s = s


def s(text, tr, note=None, cue=None, cue_tr=None, swaps=None):  # noqa: F811
    if not cue and not swaps and len(text.split()) == 1:
        return w(text.rstrip('.!'), tr.rstrip('.!'), note)
    return _s(text, tr, note, cue, cue_tr, swaps)


made = []
LF = ["life"]

# ═════════════════════ 3. Дар фурудгоҳ ═════════════════════
made.append(pack("airport_tr_tg", "Havalimanında", "Дар фурудгоҳ", "🛫", 3, LF,
    "Шумо ба Туркия парвоз мекунед ё ба Душанбе бармегардед: дар қайди парвоз бағоҷро медиҳед, "
    "гейтро мепурсед ва агар ҷомадон наояд, хабар медиҳед.",
    [
        ("Фурудгоҳ", [
            w("Uçak", "ҳавопаймо", None),
            w("Bilet", "чипта", None),
            w("Pasaport", "шиноснома", None),
            w("Kapı", "гейт (дар)", None),
            w("Valiz", "ҷомадон", None),
            w("Uçuş", "парвоз", None),
        ]),
        ("Қайди парвоз", [
            t("Pasaportunuz lütfen.", "Шиносномаатон, лутфан.", "Бигӯ: марҳамат", "Buyurun.", "Марҳамат.",
              ["Buyurun, pasaport."]),
            t("Nereye uçuyorsunuz?", "Ба куҷо парвоз мекунед?", "Бигӯ: ба Душанбе", "Duşanbe'ye.", "Ба Душанбе.",
              ["Duşanbe."]),
            t("Valiz var mı?", "Ҷомадон ҳаст?", "Бигӯ: ҳа, як ҷомадон", "Evet, bir valiz.", "Ҳа, як ҷомадон.",
              ["Bir valiz var."]),
        ]),
        ("Ибораҳо", [
            s("Bir valiz", "Як ҷомадон", None),
            s("Hangi kapı?", "Кадом гейт?", None),
            s("Uçuş saati", "Вақти парвоз", None),
            s("Pencere kenarı", "Назди тиреза", None),
            s("Koridor tarafı", "Тарафи гузаргоҳ", None),
            s("İyi uçuşlar!", "Парвози хуш!", None),
        ]),
        ("Ҷой ва гейт", [
            t("Pencere mi, koridor mu?", "Назди тиреза ё гузаргоҳ?", "Бигӯ: назди тиреза, лутфан",
              "Pencere lütfen.", "Назди тиреза, лутфан.", ["Pencere kenarı."]),
            t("Tamam. Kartınız burada.", "Хуб. Корти шумо ин ҷо.", "Бипурс: кадом гейт?", "Hangi kapı?",
              "Кадом гейт?", ["Kapı kaç?"]),
            t("Kapı on iki.", "Гейти дувоздаҳ.", "Ташаккур гӯй", "Teşekkürler.", "Ташаккур.", ["Sağ olun."]),
        ]),
        ("Саволҳо дар фурудгоҳ", [
            s("Uçuş ne zaman?", "Парвоз кай?", None),
            s("Uçuş gecikmeli mi?", "Парвоз дер мешавад?", None),
            s("Kapı nerede?", "Гейт куҷост?", None),
            s("Valiz çok ağır.", "Ҷомадон хеле вазнин.", None),
            s("Fazla kilo var.", "Вазни зиёдатӣ ҳаст.", None),
            s("Ne kadar ödeyeyim?", "Чӣ қадар пардохт кунам?", None),
        ]),
        ("Вазни зиёдатӣ", [
            t("Valiz otuz kilo.", "Ҷомадон сӣ кило.", "Бипурс: вазни зиёдатӣ ҳаст?", "Fazla kilo var mı?",
              "Вазни зиёдатӣ ҳаст?", ["Çok mu ağır?"]),
            t("Evet, beş kilo fazla.", "Ҳа, панҷ кило зиёд.", "Бипурс: чӣ қадар пардохт кунам?",
              "Ne kadar ödeyeyim?", "Чӣ қадар пардохт кунам?", ["Ne kadar?"]),
            t("Elli dolar.", "Панҷоҳ доллар.", "Бигӯ: хуб, бо корт", "Tamam, kartla.", "Хуб, бо корт.",
              ["Kartla ödüyorum."]),
        ]),
        ("Ҷомадон наомад", [
            s("Valizim gelmedi.", "Ҷомадонам наомад.", None),
            s("Bu benim biletim.", "Ин чиптаи ман.", None),
            s("Valiz siyah, büyük.", "Ҷомадон сиёҳ, калон.", None),
            s("Telefon numaram bu.", "Рақами телефонам ин.", None),
            s("Ne zaman gelir?", "Кай меояд?", None),
            s("Eve getirir misiniz?", "Ба хона меоред?", None),
        ]),
        ("Хабар додан", [
            t("Buyurun, sorun ne?", "Марҳамат, мушкил чист?", "Бигӯ: ҷомадонам наомад", "Valizim gelmedi.",
              "Ҷомадонам наомад.", ["Valiz yok."]),
            t("Valiz nasıl?", "Ҷомадон чӣ гуна?", "Бигӯ: сиёҳ, калон", "Siyah, büyük.", "Сиёҳ, калон.",
              ["Büyük, siyah valiz."]),
            t("Yarın gelir.", "Фардо меояд.", "Бипурс: ба хона меоред?", "Eve getirir misiniz?", "Ба хона меоред?",
              ["Eve gelir mi?"]),
        ]),
        ("Миссия: парвоз ба хона", [
            t("Pasaportunuz lütfen. Nereye?", "Шиносномаатон, лутфан. Ба куҷо?", "Бигӯ: ба Душанбе, марҳамат",
              "Duşanbe'ye, buyurun.", "Ба Душанбе, марҳамат.", ["Duşanbe."]),
            t("Valiz var mı?", "Ҷомадон ҳаст?", "Бигӯ: ҳа, як ҷомадон", "Evet, bir valiz.", "Ҳа, як ҷомадон.",
              ["Bir valiz var."]),
            t("Pencere mi, koridor mu?", "Тиреза ё гузаргоҳ?", "Бигӯ: назди тиреза, лутфан", "Pencere lütfen.",
              "Назди тиреза, лутфан.", ["Pencere kenarı."]),
            t("Kapı on iki. İyi uçuşlar!", "Гейти дувоздаҳ. Парвози хуш!", "Ташаккур гӯй", "Teşekkürler!",
              "Ташаккур!", ["Sağ olun!"]),
        ]),
    ]))

# ═════════════════════ 4. Қабул дар меҳмонхона ═════════════════════
made.append(pack("hotel_stay_tr_tg", "Otelde", "Қабул дар меҳмонхона", "🏨", 4, LF,
    "Шумо дар меҳмонхона (otel) ҳуҷра мегиред: номатонро мегӯед, мепурсед, ки наҳорӣ кай аст, "
    "Wi-Fi ҳаст ва агар чизе дар ҳуҷра кор накунад, хабар медиҳед.",
    [
        ("Меҳмонхона", [
            w("Otel", "меҳмонхона", None),
            w("Oda", "ҳуҷра", None),
            w("Anahtar", "калид", None),
            w("Kahvaltı", "наҳорӣ", None),
            w("Gece", "шаб", None),
            w("Resepsiyon", "қабулгоҳ", None),
        ]),
        ("Ҳуҷра", [
            t("Hoş geldiniz!", "Хуш омадед!", "Бигӯ: салом, фармоиш дорам", "Merhaba, rezervasyonum var.",
              "Салом, фармоиш дорам.", ["Rezervasyonum var."]),
            t("Adınız ne?", "Номатон чист?", "Бигӯ: Фаридун Раҳимов", "Feridun Rahimov.", "Фаридун Раҳимов.",
              ["Adım Feridun Rahimov."]),
            t("İki gece, değil mi?", "Ду шаб, дуруст?", "Бигӯ: ҳа, ду шаб", "Evet, iki gece.", "Ҳа, ду шаб.",
              ["Evet, doğru."]),
        ]),
        ("Ибораҳо", [
            s("Rezervasyonum var", "Фармоиш дорам", None),
            s("İki gece", "Ду шаб", None),
            s("Kahvaltı dahil?", "Наҳорӣ дохил?", None),
            s("İnternet şifresi", "Рамзи интернет", None),
            s("Oda numarası", "Рақами ҳуҷра", None),
            s("Kaçta çıkış?", "Баромадан соати чанд?", None),
        ]),
        ("Наҳорӣ", [
            t("Oda üç yüz beş.", "Ҳуҷраи сесаду панҷ.", "Бипурс: наҳорӣ дохил?", "Kahvaltı dahil mi?",
              "Наҳорӣ дохил?", ["Kahvaltı var mı?"]),
            t("Evet, yedi ile on arası.", "Ҳа, аз ҳафт то даҳ.", "Бипурс: рамзи интернет?", "İnternet şifresi ne?",
              "Рамзи интернет чист?", ["İnternet var mı?"]),
            t("Kartta yazıyor.", "Дар корт навишта.", "Ташаккур гӯй", "Teşekkürler.", "Ташаккур.", ["Sağ olun."]),
        ]),
        ("Саволҳо", [
            s("Asansör nerede?", "Лифт куҷост?", None),
            s("Çıkış saat kaçta?", "Баромадан соати чанд?", None),
            s("Valizimi bırakabilir miyim?", "Ҷомадонамро монам?", None),
            s("Bir havlu daha.", "Боз як сачоқ.", None),
            s("Odam çok sıcak.", "Ҳуҷраам хеле гарм.", None),
            s("Taksi çağırır mısınız?", "Такси даъват мекунед?", None),
        ]),
        ("Баромадан", [
            t("Başka bir sorunuz?", "Боз савол доред?", "Бипурс: баромадан соати чанд?", "Çıkış saat kaçta?",
              "Баромадан соати чанд?", ["Çıkış ne zaman?"]),
            t("Saat on ikide.", "Соати дувоздаҳ.", "Бипурс: ҷомадонамро монам?", "Valizimi bırakabilir miyim?",
              "Ҷомадонамро монам?", ["Valiz bırakabilir miyim?"]),
            t("Tabii, sorun değil.", "Албатта, мушкил нест.", "Бигӯ: хеле ташаккур", "Çok teşekkürler.",
              "Хеле ташаккур.", ["Sağ olun."]),
        ]),
        ("Дар ҳуҷра мушкил", [
            s("Klima çalışmıyor.", "Кондитсионер кор намекунад.", None),
            s("Sıcak su yok.", "Оби гарм нест.", None),
            s("Oda temiz değil.", "Ҳуҷра тоза нест.", None),
            s("Başka oda var mı?", "Ҳуҷраи дигар ҳаст?", None),
            s("Birini gönderir misiniz?", "Касеро мефиристед?", None),
            s("Teşekkürler, şimdi iyi.", "Ташаккур, ҳоло хуб.", None),
        ]),
        ("Оби гарм нест", [
            t("Resepsiyon, buyurun.", "Қабулгоҳ, марҳамат.", "Бигӯ: оби гарм нест", "Sıcak su yok.",
              "Оби гарм нест.", ["Odada sıcak su yok."]),
            t("Kusura bakmayın! Hangi oda?", "Маъзур доред! Кадом ҳуҷра?", "Бигӯ: сесаду панҷ", "Üç yüz beş.",
              "Сесаду панҷ.", ["Oda üç yüz beş."]),
            t("Hemen birini gönderiyorum.", "Ҳозир касеро мефиристам.", "Ташаккур гӯй", "Teşekkürler.", "Ташаккур.",
              ["Sağ olun."]),
        ]),
        ("Миссия: шаб дар Истанбул", [
            t("Hoş geldiniz! Rezervasyon var mı?", "Хуш омадед! Фармоиш ҳаст?", "Бигӯ: ҳа, ду шаб",
              "Evet, iki gece.", "Ҳа, ду шаб.", ["Rezervasyonum var."]),
            t("Adınız lütfen?", "Номатон, лутфан?", "Бигӯ: Фаридун Раҳимов", "Feridun Rahimov.", "Фаридун Раҳимов.",
              ["Adım Feridun Rahimov."]),
            t("Tamam. Oda üç yüz beş.", "Хуб. Ҳуҷраи сесаду панҷ.", "Бипурс: наҳорӣ дохил?", "Kahvaltı dahil mi?",
              "Наҳорӣ дохил?", ["Kahvaltı var mı?"]),
            t("Evet, yediden ona.", "Ҳа, аз ҳафт то даҳ.", "Ташаккур гӯй", "Teşekkürler!", "Ташаккур!",
              ["Sağ olun!"]),
        ]),
    ]))

# ═════════════════════ 5. Автобус ва метро ═════════════════════
made.append(pack("transit_tr_tg", "Otobüs ve metro", "Автобус ва метро", "🚇", 5, LF,
    "Шумо дар Истанбул бо автобус, метро ва паром мегардед: İstanbulkart мехаред ва пур мекунед, "
    "мепурсед, ки кадом автобус меравад ва дар куҷо фуроед.",
    [
        ("Нақлиёт", [
            w("Otobüs", "автобус", None),
            w("Metro", "метро", None),
            w("Durak", "истгоҳ", None),
            w("Vapur", "паром (киштӣ)", None),
            w("İstanbulkart", "корти нақлиёти Истанбул", None),
            w("Hat", "хат (маршрут)", None),
        ]),
        ("Корти нақлиёт", [
            t("Buyurun?", "Марҳамат?", "Бигӯ: як İstanbulkart, лутфан", "Bir İstanbulkart lütfen.",
              "Як İstanbulkart, лутфан.", ["İstanbulkart istiyorum."]),
            t("Ne kadar yükleyeyim?", "Чӣ қадар пур кунам?", "Бигӯ: сад лира", "Yüz lira.", "Сад лира.",
              ["Yüz lira lütfen."]),
            t("Tamam, buyurun.", "Хуб, марҳамат.", "Ташаккур гӯй", "Teşekkürler.", "Ташаккур.", ["Sağ olun."]),
        ]),
        ("Ибораҳо", [
            s("Kartı yükle", "Кортро пур кун", None),
            s("Hangi otobüs?", "Кадом автобус?", None),
            s("Nerede ineyim?", "Куҷо фуроям?", None),
            s("Sonraki durak", "Истгоҳи навбатӣ", None),
            s("Aktarma var", "Ивазкунӣ ҳаст", None),
            s("Taksim'e gider", "Ба Таксим меравад", None),
        ]),
        ("Кадом автобус?", [
            t("Buyurun?", "Марҳамат?", "Бипурс: кадом автобус ба Таксим?", "Hangi otobüs Taksim'e?",
              "Кадом автобус ба Таксим?", ["Taksim'e hangi otobüs?"]),
            t("Otuz sekiz numara.", "Рақами сиву ҳашт.", "Бипурс: истгоҳ куҷост?", "Durak nerede?",
              "Истгоҳ куҷост?", ["Nerede durak?"]),
            t("Karşıda.", "Дар рӯ ба рӯ.", "Ташаккур гӯй", "Teşekkürler.", "Ташаккур.", ["Sağ olun."]),
        ]),
        ("Дар роҳ", [
            s("Taksim'e gider mi?", "Ба Таксим меравад?", None),
            s("Kaç durak var?", "Чанд истгоҳ ҳаст?", None),
            s("Nerede ineyim?", "Дар куҷо фуроям?", None),
            s("Burada iniyorum.", "Ин ҷо мефуроям.", None),
            s("Kartım çalışmıyor.", "Кортам кор намекунад.", None),
            s("Bakiye yok.", "Маблағ нест.", None),
        ]),
        ("Куҷо фуроям?", [
            t("Bu otobüs Taksim'e gider.", "Ин автобус ба Таксим меравад.", "Бипурс: чанд истгоҳ ҳаст?",
              "Kaç durak var?", "Чанд истгоҳ ҳаст?", ["Kaç durak?"]),
            t("Beş durak.", "Панҷ истгоҳ.", "Бипурс: дар куҷо фуроям?", "Nerede ineyim?", "Дар куҷо фуроям?",
              ["Nerede inerim?"]),
            t("Son durakta.", "Дар истгоҳи охир.", "Бигӯ: хуб, ташаккур", "Tamam, teşekkürler.", "Хуб, ташаккур.",
              ["Sağ olun."]),
        ]),
        ("Метро ва паром", [
            s("Metro nerede?", "Метро куҷост?", None),
            s("Hangi yön?", "Кадом самт?", None),
            s("Vapur kaçta kalkıyor?", "Паром соати чанд меравад?", None),
            s("Üsküdar'a gidiyorum.", "Ба Ускудар меравам.", None),
            s("Aktarma nerede?", "Ивазкунӣ дар куҷо?", None),
            s("Yanlış yöndeyim.", "Ман самти нодурустам.", None),
        ]),
        ("Самти нодуруст", [
            t("Nereye gidiyorsunuz?", "Ба куҷо меравед?", "Бигӯ: ба Ускудар меравам", "Üsküdar'a gidiyorum.",
              "Ба Ускудар меравам.", ["Üsküdar."]),
            t("Bu yanlış yön!", "Ин самти нодуруст!", "Бипурс: ивазкунӣ дар куҷо?", "Aktarma nerede?",
              "Ивазкунӣ дар куҷо?", ["Ne yapayım?"]),
            t("Sonraki durakta inin.", "Дар истгоҳи навбатӣ фуроед.", "Бигӯ: хуб, ташаккур", "Tamam, teşekkürler.",
              "Хуб, ташаккур.", ["Sağ olun."]),
        ]),
        ("Миссия: ба Ускудар", [
            t("Buyurun?", "Марҳамат?", "Бигӯ: кортро пур кунед, сад лира", "Kartı yükleyin, yüz lira.",
              "Кортро пур кунед, сад лира.", ["Yüz lira yükleyin."]),
            t("Tamam. Nereye gidiyorsunuz?", "Хуб. Ба куҷо меравед?", "Бигӯ: ба Ускудар меравам",
              "Üsküdar'a gidiyorum.", "Ба Ускудар меравам.", ["Üsküdar."]),
            t("Metro, sonra vapur.", "Метро, баъд паром.", "Бипурс: паром соати чанд меравад?",
              "Vapur kaçta kalkıyor?", "Паром соати чанд меравад?", ["Vapur ne zaman?"]),
            t("Her yarım saatte.", "Ҳар ним соат.", "Ташаккур гӯй", "Teşekkürler!", "Ташаккур!", ["Sağ olun!"]),
        ]),
    ]))

# ═════════════════════ 7. Қаҳвахонаи шаҳр ═════════════════════
made.append(pack("coffee_shop_tr_tg", "Kafede", "Қаҳвахонаи шаҳр", "☕", 7, LF,
    "Шумо дар қаҳвахона чой ё қаҳва фармоиш медиҳед: андоза ва шакарро мегӯед, мепурсед, ки "
    "ширинӣ чӣ ҳаст ва ҳисоб мекунед.",
    [
        ("Қаҳвахона", [
            w("Kahve", "қаҳва", None),
            w("Çay", "чой", None),
            w("Şeker", "қанд", None),
            w("Süt", "шир", None),
            w("Pasta", "торт", None),
            w("Simit", "симит (нони ҳалқадор)", None),
        ]),
        ("Фармоиш", [
            t("Merhaba, ne alırsınız?", "Салом, чӣ мегиред?", "Бигӯ: як чой, лутфан", "Bir çay lütfen.",
              "Як чой, лутфан.", ["Çay lütfen."]),
            t("Şekerli mi?", "Бо қанд?", "Бигӯ: не, бе қанд", "Hayır, şekersiz.", "Не, бе қанд.", ["Şekersiz."]),
            t("Başka bir şey?", "Боз чизе?", "Бигӯ: як симит", "Bir simit.", "Як симит.", ["Bir simit lütfen."]),
        ]),
        ("Ибораҳо", [
            s("Bir çay", "Як чой", None),
            w("Şekersiz", "бе қанд", None),
            s("Sütlü kahve", "Қаҳва бо шир", None),
            s("Türk kahvesi", "Қаҳваи туркӣ", None),
            s("Paket lütfen", "Барои бурдан", None),
            s("Burada içeceğim", "Ин ҷо менӯшам", None),
        ]),
        ("Қаҳваи туркӣ", [
            t("Ne içersiniz?", "Чӣ менӯшед?", "Бигӯ: қаҳваи туркӣ", "Türk kahvesi.", "Қаҳваи туркӣ.",
              ["Bir Türk kahvesi."]),
            t("Şekerli mi, sade mi?", "Бо қанд ё соф?", "Бигӯ: каме қанд", "Az şekerli.", "Каме қанд.",
              ["Orta şekerli."]),
            t("Burada mı?", "Ин ҷо?", "Бигӯ: ҳа, ин ҷо менӯшам", "Evet, burada içeceğim.", "Ҳа, ин ҷо менӯшам.",
              ["Burada."]),
        ]),
        ("Ман фармоиш медиҳам", [
            s("Bir sütlü kahve lütfen.", "Як қаҳва бо шир, лутфан.", None),
            s("Büyük olsun.", "Калон бошад.", None),
            s("Ne tatlı var?", "Чӣ ширинӣ ҳаст?", None),
            s("Bu pasta ne?", "Ин торт чист?", None),
            s("İnternet şifresi ne?", "Рамзи интернет чист?", None),
            s("Hesap lütfen.", "Ҳисоб, лутфан.", None),
        ]),
        ("Ширинӣ", [
            t("Başka bir şey?", "Боз чизе?", "Бипурс: чӣ ширинӣ ҳаст?", "Ne tatlı var?", "Чӣ ширинӣ ҳаст?",
              ["Tatlı var mı?"]),
            t("Baklava ve pasta.", "Бақлава ва торт.", "Бигӯ: як бақлава, лутфан", "Bir baklava lütfen.",
              "Як бақлава, лутфан.", ["Baklava."]),
            t("Tamam, hemen.", "Хуб, ҳозир.", "Бипурс: рамзи интернет чист?", "İnternet şifresi ne?", "Рамзи интернет чист?",
              ["İnternet var mı?"]),
        ]),
        ("Ҳисоб ва ҷой", [
            s("Bu masa boş mu?", "Ин миз холӣ аст?", None),
            s("Oturabilir miyim?", "Шинам?", None),
            s("Prizi var mı?", "Розетка ҳаст?", None),
            s("Ne kadar?", "Чанд?", None),
            s("Kartla ödüyorum.", "Бо корт медиҳам.", None),
            s("Çok lezzetliydi.", "Хеле бомаза буд.", None),
        ]),
        ("Ҷои холӣ", [
            t("Buyurun?", "Марҳамат?", "Бипурс: ин миз холӣ аст?", "Bu masa boş mu?", "Ин миз холӣ аст?",
              ["Boş mu?"]),
            t("Evet, oturun.", "Ҳа, шинед.", "Бипурс: розетка ҳаст?", "Prizi var mı?", "Розетка ҳаст?",
              ["Priz var mı?"]),
            t("Orada, duvarda.", "Он ҷо, дар девор.", "Ташаккур гӯй", "Teşekkürler.", "Ташаккур.", ["Sağ olun."]),
        ]),
        ("Миссия: субҳ дар қаҳвахона", [
            t("Günaydın! Ne alırsınız?", "Субҳ ба хайр! Чӣ мегиред?", "Бигӯ: як қаҳва бо шир, лутфан",
              "Bir sütlü kahve lütfen.", "Як қаҳва бо шир, лутфан.", ["Sütlü kahve."]),
            t("Büyük mü, küçük mü?", "Калон ё хурд?", "Бигӯ: калон бошад", "Büyük olsun.", "Калон бошад.",
              ["Büyük."]),
            t("Başka bir şey?", "Боз чизе?", "Бигӯ: як симит", "Bir simit.", "Як симит.", ["Bir simit lütfen."]),
            t("Toplam yüz lira.", "Ҳамагӣ сад лира.", "Бигӯ: бо корт медиҳам", "Kartla ödüyorum.",
              "Бо корт медиҳам.", ["Kartla."]),
        ]),
    ]))

# ═════════════════════ 8. Дар супермаркет ═════════════════════
made.append(pack("supermarket_tr_tg", "Markette", "Дар супермаркет", "🛒", 8, LF,
    "Шумо дар маркет ва бозор харид мекунед: маҳсулот меҷӯед, нарх мепурсед, «як кило» мегӯед ва "
    "дар касса пардохт мекунед.",
    [
        ("Маҳсулот", [
            w("Ekmek", "нон", None),
            w("Süt", "шир", None),
            w("Et", "гӯшт", None),
            w("Pirinç", "биринҷ", None),
            w("Domates", "помидор", None),
            w("Kilo", "кило", None),
        ]),
        ("Дар бозор", [
            t("Buyurun abi!", "Марҳамат, ака!", "Бипурс: помидор чанд?", "Domates kaç lira?", "Помидор чанд лира?",
              ["Domates ne kadar?"]),
            t("Kilosu otuz lira.", "Килояш сӣ лира.", "Бигӯ: ду кило, лутфан", "İki kilo lütfen.",
              "Ду кило, лутфан.", ["İki kilo."]),
            t("Başka?", "Дигар?", "Бигӯ: ҳамин, ташаккур", "Bu kadar, teşekkürler.", "Ҳамин, ташаккур.",
              ["Bu kadar."]),
        ]),
        ("Ибораҳо", [
            s("Bir kilo", "Як кило", None),
            s("Kaç lira?", "Чанд лира?", None),
            s("Taze mi?", "Тоза (тару тоза) аст?", None),
            s("Helal et", "Гӯшти ҳалол", None),
            s("Bu kadar", "Ҳамин", None),
            w("Poşet", "халта", None),
        ]),
        ("Гӯшти ҳалол", [
            t("Ne istersiniz?", "Чӣ мехоҳед?", "Бигӯ: як кило гӯшт", "Bir kilo et.", "Як кило гӯшт.",
              ["Et lütfen."]),
            t("Dana mı, kuzu mu?", "Гов ё барра?", "Бигӯ: барра", "Kuzu.", "Барра.", ["Kuzu lütfen."]),
            t("Buyurun.", "Марҳамат.", "Бипурс: чанд лира?", "Kaç lira?", "Чанд лира?", ["Ne kadar?"]),
        ]),
        ("Ҷустуҷӯ", [
            s("Pirinç nerede?", "Биринҷ куҷост?", None),
            s("Süt bitmiş mi?", "Шир тамом шудааст?", None),
            s("Bu taze mi?", "Ин тоза аст?", None),
            s("Daha ucuz var mı?", "Арзонтар ҳаст?", None),
            s("Bu indirimde mi?", "Ин бо тахфиф аст?", None),
            s("Poşet lazım değil.", "Халта лозим нест.", None),
        ]),
        ("Арзонтар", [
            t("Yardım edeyim mi?", "Ёрӣ диҳам?", "Бипурс: биринҷ куҷост?", "Pirinç nerede?", "Биринҷ куҷост?",
              ["Pirinç var mı?"]),
            t("Üçüncü rafta.", "Дар рафи сеюм.", "Бипурс: арзонтар ҳаст?", "Daha ucuz var mı?", "Арзонтар ҳаст?",
              ["Ucuz var mı?"]),
            t("Bu indirimde.", "Ин бо тахфиф аст.", "Ташаккур гӯй", "Teşekkürler.", "Ташаккур.", ["Sağ olun."]),
        ]),
        ("Дар касса", [
            s("Poşet ister misiniz?", "Халта мехоҳед?", None),
            s("Evet, bir tane.", "Ҳа, яктоӣ.", None),
            s("Kartla ödeyeceğim.", "Бо корт медиҳам.", None),
            s("Fiş lazım değil.", "Чек лозим нест.", None),
            s("Fiyat yanlış galiba.", "Нарх нодуруст, гумон кунам.", None),
            s("Bu yirmi liraydı.", "Ин бист лира буд.", None),
        ]),
        ("Нархи нодуруст", [
            t("Toplam iki yüz lira.", "Ҳамагӣ дусад лира.", "Бигӯ: нарх нодуруст, гумон кунам",
              "Fiyat yanlış galiba.", "Нарх нодуруст, гумон кунам.", ["Bu yanlış."]),
            t("Hangisi?", "Кадомаш?", "Бигӯ: ин бист лира нест?", "Bu yirmi liraydı.", "Ин бист лира буд.",
              ["Bu indirimde."]),
            t("Haklısınız, pardon.", "Ҳақ бо шумост, бубахшед.", "Бигӯ: мушкил нест", "Sorun değil.",
              "Мушкил нест.", ["Tamam."]),
        ]),
        ("Миссия: харид барои ҳафта", [
            t("Buyurun abi!", "Марҳамат, ака!", "Бипурс: помидор чанд лира?", "Domates kaç lira?",
              "Помидор чанд лира?", ["Domates ne kadar?"]),
            t("Kilosu otuz.", "Килояш сӣ.", "Бигӯ: ду кило, лутфан", "İki kilo lütfen.", "Ду кило, лутфан.",
              ["İki kilo."]),
            t("Başka?", "Дигар?", "Бигӯ: як кило гӯшти барра", "Bir kilo kuzu.", "Як кило гӯшти барра.",
              ["Kuzu eti."]),
            t("Toplam beş yüz lira.", "Ҳамагӣ панҷсад лира.", "Бигӯ: бо корт медиҳам", "Kartla ödeyeceğim.",
              "Бо корт медиҳам.", ["Kartla."]),
        ]),
    ]))

# ═════════════════════ 9. Телефон ва интернет ═════════════════════
made.append(pack("phone_plan_tr_tg", "Hat ve internet", "Телефон ва интернет", "📶", 9, LF,
    "Шумо SIM-корт ва тарифи интернет мехаред: шиносномаро медиҳед, мепурсед, ки чанд гигабайт ва "
    "чанд пул аст ва чӣ тавр ба Тоҷикистон занг занед.",
    [
        ("Алоқа", [
            w("Hat", "SIM (рақам)", None),
            w("Paket", "тариф (баста)", None),
            w("İnternet", "интернет", None),
            w("Dakika", "дақиқа", None),
            w("Fatura", "ҳисоб (фактура)", None),
            w("Kayıt", "қайд", None),
        ]),
        ("Рақами нав", [
            t("Merhaba, buyurun.", "Салом, марҳамат.", "Бигӯ: SIM-корт мехоҳам", "Hat almak istiyorum.",
              "SIM-корт мехоҳам.", ["Yeni hat lütfen."]),
            t("Pasaportunuz var mı?", "Шиноснома доред?", "Бигӯ: ҳа, марҳамат", "Evet, buyurun.", "Ҳа, марҳамат.",
              ["Buyurun."]),
            t("Hangi paket?", "Кадом тариф?", "Бигӯ: интернети бисёр", "Çok internet.", "Интернети бисёр.",
              ["İnternet paketi."]),
        ]),
        ("Ибораҳо", [
            s("Yeni hat", "Рақами нав", None),
            s("Kaç gigabayt?", "Чанд гигабайт?", None),
            s("Aylık paket", "Тарифи моҳона", None),
            s("Yurt dışı", "Хориҷа", None),
            s("Faturasız hat", "Рақами пешпардохт", None),
            s("Kontör yükle", "Ҳисобро пур кун", None),
        ]),
        ("Тариф", [
            t("Bu paket yirmi gigabayt.", "Ин тариф бист гигабайт.", "Бипурс: моҳе чанд?", "Ayda ne kadar?",
              "Моҳе чанд?", ["Fiyat ne?"]),
            t("Ayda dört yüz lira.", "Моҳе чорсад лира.", "Бигӯ: каме қимат", "Biraz pahalı.", "Каме қимат.",
              ["Pahalı."]),
            t("Bu da var, daha ucuz.", "Инаш ҳам ҳаст, арзонтар.", "Бигӯ: хуб, инро мегирам", "Tamam, bunu alıyorum.",
              "Хуб, инро мегирам.", ["Bunu alayım."]),
        ]),
        ("Саволҳо", [
            s("Tacikistan'ı arayabilir miyim?", "Ба Тоҷикистон занг зада метавонам?", None),
            s("Dakikası ne kadar?", "Дақиқааш чанд?", None),
            s("İnternetim bitti.", "Интернетам тамом шуд.", None),
            s("Telefonum kayıtsız.", "Телефонам қайд нашудааст.", None),
            s("Kayıt ücreti ne kadar?", "Пули қайд чанд?", None),
            s("Hat ne zaman açılır?", "Рақам кай фаъол мешавад?", None),
        ]),
        ("Занг ба ватан", [
            t("Başka sorunuz var mı?", "Боз савол доред?", "Бипурс: ба Тоҷикистон занг зада метавонам?",
              "Tacikistan'ı arayabilir miyim?", "Ба Тоҷикистон занг зада метавонам?", ["Tacikistan olur mu?"]),
            t("Evet, ama pahalı.", "Ҳа, вале қимат.", "Бипурс: дақиқааш чанд?", "Dakikası ne kadar?",
              "Дақиқааш чанд?", ["Ne kadar?"]),
            t("WhatsApp daha ucuz.", "WhatsApp арзонтар.", "Бигӯ: ҳа, дуруст", "Evet, doğru.", "Ҳа, дуруст.",
              ["Haklısınız."]),
        ]),
        ("Мушкил", [
            s("İnternet çalışmıyor.", "Интернет кор намекунад.", None),
            s("Telefonu kapatıp açın.", "Телефонро хомӯш-фаъол кунед.", None),
            s("Paketi yenileyin.", "Тарифро нав кунед.", None),
            s("Yüz lira yükleyin.", "Сад лира пур кунед.", None),
            s("Şimdi çalışıyor.", "Ҳоло кор мекунад.", None),
            s("Yardımınız için teşekkürler.", "Барои ёриатон ташаккур.", None),
        ]),
        ("Интернет нест", [
            t("Buyurun?", "Марҳамат?", "Бигӯ: интернет кор намекунад", "İnternet çalışmıyor.",
              "Интернет кор намекунад.", ["İnternetim yok."]),
            t("Paketiniz bitmiş.", "Тарифатон тамом шудааст.", "Бигӯ: сад лира пур кунед", "Yüz lira yükleyin.",
              "Сад лира пур кунед.", ["Yükleyin lütfen."]),
            t("Tamam. Şimdi çalışıyor mu?", "Хуб. Ҳоло кор мекунад?", "Бигӯ: ҳа, ташаккур", "Evet, teşekkürler.",
              "Ҳа, ташаккур.", ["Çalışıyor."]),
        ]),
        ("Миссия: SIM-и нав", [
            t("Merhaba, buyurun.", "Салом, марҳамат.", "Бигӯ: SIM-корт мехоҳам", "Hat almak istiyorum.",
              "SIM-корт мехоҳам.", ["Yeni hat lütfen."]),
            t("Pasaport lütfen.", "Шиноснома, лутфан.", "Бигӯ: марҳамат", "Buyurun.", "Марҳамат.",
              ["Buyurun pasaport."]),
            t("Bu paket yirmi gigabayt.", "Ин тариф бист гигабайт.", "Бипурс: моҳе чанд?", "Ayda ne kadar?", "Моҳе чанд?",
              ["Fiyat ne?"]),
            t("Üç yüz lira.", "Сесад лира.", "Бигӯ: хуб, инро мегирам", "Tamam, bunu alıyorum.",
              "Хуб, инро мегирам.", ["Bunu alayım."]),
        ]),
    ]))

# ═════════════════════ 11. Пул ва фиристодан ба хона ═════════════════════
made.append(pack("money_tr_tg", "Para ve havale", "Пул ва фиристодан ба хона", "💱", 11, LF,
    "Шумо пул иваз мекунед ва ба оила дар Тоҷикистон мефиристед: қурбро мепурсед, маблағ ва номи "
    "гирандаро мегӯед ва рамзи интиқолро мегиред.",
    [
        ("Пул", [
            w("Döviz", "асъор", None),
            w("Dolar", "доллар", None),
            w("Kur", "қурб", None),
            w("Havale", "интиқоли пул", None),
            w("Alıcı", "гиранда", None),
            w("Komisyon", "комиссия", None),
        ]),
        ("Иваз кардан", [
            t("Buyurun?", "Марҳамат?", "Бигӯ: доллар иваз мекунам", "Dolar bozdurmak istiyorum.",
              "Доллар иваз кардан мехоҳам.", ["Dolar bozduracağım."]),
            t("Ne kadar?", "Чӣ қадар?", "Бигӯ: сад доллар", "Yüz dolar.", "Сад доллар.", ["Yüz."]),
            t("Tamam, buyurun.", "Хуб, марҳамат.", "Ташаккур гӯй", "Teşekkürler.", "Ташаккур.", ["Sağ olun."]),
        ]),
        ("Ибораҳо", [
            s("Kur ne?", "Қурб чанд?", None),
            s("Yüz dolar", "Сад доллар", None),
            s("Para göndermek", "Пул фиристодан", None),
            s("Tacikistan'a havale", "Интиқол ба Тоҷикистон", None),
            s("Komisyon ne?", "Комиссия чанд?", None),
            w("Pasaport", "шиноснома", None),
        ]),
        ("Қурб", [
            t("Merhaba!", "Салом!", "Бипурс: қурби доллар чанд?", "Dolar kuru ne?", "Қурби доллар чанд?",
              ["Kur ne?"]),
            t("Bugün kırk bir lira.", "Имрӯз чилу як лира.", "Бигӯ: сад доллар иваз кунед", "Yüz dolar bozun.",
              "Сад доллар иваз кунед.", ["Yüz dolar lütfen."]),
            t("Dört bin yüz lira.", "Чор ҳазору сад лира.", "Ташаккур гӯй", "Teşekkürler.", "Ташаккур.",
              ["Sağ olun."]),
        ]),
        ("Фиристодани пул", [
            s("Tacikistan'a para göndereceğim.", "Ба Тоҷикистон пул мефиристам.", None),
            s("Alıcının adı Zarina.", "Номи гиранда Зарина.", None),
            s("Duşanbe'de alacak.", "Дар Душанбе мегирад.", None),
            s("Komisyon ne kadar?", "Комиссия чанд?", None),
            s("Ne zaman ulaşır?", "Кай мерасад?", None),
            s("Kodu yazar mısınız?", "Рамзро менависед?", None),
        ]),
        ("Ба модар", [
            t("Buyurun, kime?", "Марҳамат, ба кӣ?", "Бигӯ: номи гиранда Зарина", "Alıcının adı Zarina.",
              "Номи гиранда Зарина.", ["Zarina Rahimova."]),
            t("Hangi şehir?", "Кадом шаҳр?", "Бигӯ: дар Душанбе мегирад", "Duşanbe'de alacak.",
              "Дар Душанбе мегирад.", ["Duşanbe."]),
            t("Tamam. Ne kadar?", "Хуб. Чӣ қадар?", "Бигӯ: дусад доллар", "İki yüz dolar.", "Дусад доллар.",
              ["İki yüz."]),
        ]),
        ("Рамз ва комиссия", [
            s("Komisyon beş dolar.", "Комиссия панҷ доллар.", None),
            s("Para bugün ulaşır.", "Пул имрӯз мерасад.", None),
            s("Bu sizin kodunuz.", "Ин рамзи шумо.", None),
            s("Kodu annene gönder.", "Рамзро ба модарат фирист.", None),
            s("İmza burada.", "Имзо ин ҷо.", None),
            s("Fişi saklayın.", "Чекро нигоҳ доред.", None),
        ]),
        ("Кай мерасад?", [
            t("Komisyon beş dolar.", "Комиссия панҷ доллар.", "Бипурс: кай мерасад?", "Ne zaman ulaşır?",
              "Кай мерасад?", ["Ne zaman gelir?"]),
            t("Bugün ulaşır.", "Имрӯз мерасад.", "Бипурс: рамзро менависед?", "Kodu yazar mısınız?",
              "Рамзро менависед?", ["Kod ne?"]),
            t("Bu sizin kodunuz.", "Ин рамзи шумо.", "Ташаккури зиёд гӯй", "Çok teşekkürler.", "Ташаккури зиёд.",
              ["Sağ olun."]),
        ]),
        ("Миссия: маош ба хона", [
            t("Merhaba, buyurun.", "Салом, марҳамат.", "Бигӯ: ба Тоҷикистон пул мефиристам",
              "Tacikistan'a para göndereceğim.", "Ба Тоҷикистон пул мефиристам.", ["Havale yapacağım."]),
            t("Kime?", "Ба кӣ?", "Бигӯ: номи гиранда Зарина", "Alıcının adı Zarina.", "Номи гиранда Зарина.",
              ["Zarina Rahimova."]),
            t("Ne kadar?", "Чӣ қадар?", "Бигӯ: сесад доллар", "Üç yüz dolar.", "Сесад доллар.", ["Üç yüz."]),
            t("Tamam. Bu sizin kodunuz.", "Хуб. Ин рамзи шумо.", "Бипурс: кай мерасад?", "Ne zaman ulaşır?",
              "Кай мерасад?", ["Ne zaman gelir?"]),
        ]),
    ]))

# ═════════════════════ 12. Дар дорухона ═════════════════════
made.append(pack("pharmacy_tr_tg", "Eczanede", "Дар дорухона", "💊", 12, LF,
    "Шумо бемор шудед: дар дорухона (eczane) мегӯед, ки чӣ дард мекунад, дору мепурсед, мефаҳмед, "
    "ки рӯзе чанд бор нӯшед ва оё рецепт лозим аст.",
    [
        ("Беморӣ", [
            w("Eczane", "дорухона", None),
            w("İlaç", "дору", None),
            w("Ağrı", "дард", None),
            w("Ateş", "таб", None),
            w("Öksürük", "сулфа", None),
            w("Reçete", "рецепт", None),
        ]),
        ("Сарам дард мекунад", [
            t("Geçmiş olsun. Ne oldu?", "Шифо ёбед. Чӣ шуд?", "Бигӯ: сарам дард мекунад", "Başım ağrıyor.",
              "Сарам дард мекунад.", ["Başım çok ağrıyor."]),
            t("Ateş var mı?", "Таб ҳаст?", "Бигӯ: не, таб нест", "Hayır, ateş yok.", "Не, таб нест.", ["Yok."]),
            t("Bu ilacı alın.", "Ин доруро гиред.", "Бипурс: рӯзе чанд бор?", "Günde kaç kere?", "Рӯзе чанд бор?",
              ["Kaç kere?"]),
        ]),
        ("Ибораҳо", [
            s("Başım ağrıyor", "Сарам дард мекунад", None),
            s("Boğazım ağrıyor", "Гулӯям дард мекунад", None),
            s("Ateşim var", "Таб дорам", None),
            s("Günde iki", "Рӯзе ду бор", None),
            s("Yemekten sonra", "Баъди хӯрок", None),
            s("Reçete lazım?", "Рецепт лозим?", None),
        ]),
        ("Сулфа", [
            t("Buyurun?", "Марҳамат?", "Бигӯ: сулфа ва таб дорам", "Öksürüğüm ve ateşim var.",
              "Сулфа ва таб дорам.", ["Öksürük var."]),
            t("Bu şurup iyi.", "Ин шарбат хуб аст.", "Бипурс: рецепт лозим?", "Reçete lazım mı?", "Рецепт лозим?",
              ["Reçete gerekir mi?"]),
            t("Hayır, gerekmez.", "Не, лозим нест.", "Бигӯ: хуб, инро мегирам", "Tamam, bunu alıyorum.",
              "Хуб, инро мегирам.", ["Bunu alayım."]),
        ]),
        ("Тавзеҳи дору", [
            s("Günde üç kere.", "Рӯзе се бор.", None),
            s("Yemekten sonra için.", "Баъди хӯрок нӯшед.", None),
            s("Beş gün kullanın.", "Панҷ рӯз истифода баред.", None),
            s("Çocuk için mi?", "Барои кӯдак?", None),
            s("Bol su için.", "Об бисёр нӯшед.", None),
            s("Doktora gidin.", "Ба духтур равед.", None),
        ]),
        ("Чӣ тавр нӯшам?", [
            t("Bu ilaç ateş için.", "Ин дору барои таб.", "Бипурс: рӯзе чанд бор?", "Günde kaç kere?",
              "Рӯзе чанд бор?", ["Nasıl içeyim?"]),
            t("Günde üç kere.", "Рӯзе се бор.", "Бипурс: пеш аз хӯрок ё баъд?", "Yemekten önce mi, sonra mı?",
              "Пеш аз хӯрок ё баъд?", ["Yemekten sonra mı?"]),
            t("Yemekten sonra.", "Баъди хӯрок.", "Бигӯ: фаҳмидам, ташаккур", "Anladım, teşekkürler.",
              "Фаҳмидам, ташаккур.", ["Teşekkürler."]),
        ]),
        ("Агар бад шавад", [
            s("Üç gün geçmezse doktora.", "Агар се рӯз нагузарад, ба духтур.", None),
            s("Nöbetçi eczane nerede?", "Дорухонаи навбатдор куҷост?", None),
            s("Hastane yakın mı?", "Беморхона наздик аст?", None),
            s("Fiyatı ne kadar?", "Нархаш чанд?", None),
            s("Daha ucuzu var mı?", "Арзонтараш ҳаст?", None),
            s("Geçmiş olsun!", "Шифо ёбед!", None),
        ]),
        ("Нарх", [
            t("Bu ilaç çok iyi.", "Ин дору хеле хуб.", "Бипурс: нархаш чанд?", "Fiyatı ne kadar?", "Нархаш чанд?",
              ["Ne kadar?"]),
            t("Yüz elli lira.", "Саду панҷоҳ лира.", "Бипурс: арзонтараш ҳаст?", "Daha ucuzu var mı?",
              "Арзонтараш ҳаст?", ["Ucuz var mı?"]),
            t("Bu, seksen lira.", "Ин, ҳаштод лира.", "Бигӯ: хуб, инро мегирам", "Tamam, bunu alıyorum.",
              "Хуб, инро мегирам.", ["Bunu alayım."]),
        ]),
        ("Миссия: шамолхӯрӣ", [
            t("Merhaba, ne oldu?", "Салом, чӣ шуд?", "Бигӯ: гулӯям дард мекунад", "Boğazım ağrıyor.",
              "Гулӯям дард мекунад.", ["Boğazım çok ağrıyor."]),
            t("Ateş var mı?", "Таб ҳаст?", "Бигӯ: ҳа, каме", "Evet, biraz.", "Ҳа, каме.", ["Biraz ateşim var."]),
            t("Bu ilacı alın.", "Ин доруро гиред.", "Бипурс: рӯзе чанд бор?", "Günde kaç kere?", "Рӯзе чанд бор?",
              ["Nasıl içeyim?"]),
            t("Günde iki kere. Geçmiş olsun!", "Рӯзе ду бор. Шифо ёбед!", "Ташаккур гӯй", "Teşekkürler.",
              "Ташаккур.", ["Sağ olun."]),
        ]),
    ]))

# ═════════════════════ 13. Дар почта ═════════════════════
made.append(pack("post_tr_tg", "PTT'de", "Дар почта", "📮", 13, LF,
    "Шумо дар почтаи PTT баста ба Тоҷикистон мефиристед ё бастаи худро мегиред: вазн ва нархро "
    "мепурсед, суроғаро менависед ва рақами пайгириро мегиред.",
    [
        ("Почта", [
            w("Kargo", "баста (посылка)", None),
            w("Mektup", "мактуб", None),
            w("Adres", "суроға", None),
            w("Kutu", "қуттӣ", None),
            w("Takip", "пайгирӣ", None),
            w("Pul", "марка", None),
        ]),
        ("Баста ба ватан", [
            t("Buyurun?", "Марҳамат?", "Бигӯ: ба Тоҷикистон баста мефиристам", "Tacikistan'a kargo göndereceğim.",
              "Ба Тоҷикистон баста мефиристам.", ["Kargo göndereceğim."]),
            t("İçinde ne var?", "Дарунаш чист?", "Бигӯ: либос", "Kıyafet.", "Либос.", ["Kıyafet var."]),
            t("Üç kilo. Bin lira.", "Се кило. Ҳазор лира.", "Бигӯ: хуб", "Tamam.", "Хуб.", ["Peki."]),
        ]),
        ("Ибораҳо", [
            s("Kargo göndermek", "Баста фиристодан", None),
            s("Kaç kilo?", "Чанд кило?", None),
            s("Kaç gün?", "Чанд рӯз?", None),
            s("Takip numarası", "Рақами пайгирӣ", None),
            s("Kargom geldi", "Бастаам омад", None),
            w("Kimlik", "шаҳодатнома", None),
        ]),
        ("Чӣ қадар мегирад?", [
            t("Adresi yazın lütfen.", "Суроғаро нависед, лутфан.", "Бигӯ: хуб", "Tamam.", "Хуб.", ["Peki."]),
            t("Teşekkürler.", "Ташаккур.", "Бипурс: чӣ қадар мегирад?", "Ne kadar sürer?", "Чӣ қадар мегирад?",
              ["Ne zaman ulaşır?"]),
            t("İki hafta.", "Ду ҳафта.", "Бигӯ: хуб, ташаккур", "Tamam, teşekkürler.", "Хуб, ташаккур.",
              ["Sağ olun."]),
        ]),
        ("Гирифтани баста", [
            s("Kargom gelmiş.", "Бастаам омадааст.", None),
            s("Mesaj geldi.", "Паём омад.", None),
            s("Takip numarası bu.", "Рақами пайгирӣ ин.", None),
            s("Kimliğiniz lütfen.", "Шаҳодатномаатон, лутфан.", None),
            s("Buraya imza atın.", "Ин ҷо имзо кунед.", None),
            s("Kargo hasarlı.", "Баста осеб дидааст.", None),
        ]),
        ("Бастаам омад", [
            t("Buyurun?", "Марҳамат?", "Бигӯ: бастаам омадааст", "Kargom gelmiş.", "Бастаам омадааст.",
              ["Kargo almaya geldim."]),
            t("Takip numarası?", "Рақами пайгирӣ?", "Бигӯ: рақами пайгирӣ ин", "Takip numarası bu.",
              "Рақами пайгирӣ ин.", ["Buyurun."]),
            t("Kimliğiniz lütfen.", "Шаҳодатномаатон, лутфан.", "Бигӯ: марҳамат", "Buyurun.", "Марҳамат.",
              ["İkamet izni, buyurun."]),
        ]),
        ("Қуттӣ ва вазн", [
            s("Kutu var mı?", "Қуттӣ ҳаст?", None),
            s("Büyük kutu lütfen.", "Қуттии калон, лутфан.", None),
            s("Çok ağır mı?", "Хеле вазнин аст?", None),
            s("Maksimum yirmi kilo.", "Ҳадди аксар бист кило.", None),
            s("Kırılacak eşya var.", "Чизи шикастанӣ ҳаст.", None),
            s("Sigortalı olsun.", "Бо суғурта бошад.", None),
        ]),
        ("Шикастанӣ", [
            t("İçinde ne var?", "Дарунаш чист?", "Бигӯ: чизи шикастанӣ ҳаст", "Kırılacak eşya var.",
              "Чизи шикастанӣ ҳаст.", ["Cam var."]),
            t("Sigorta ister misiniz?", "Суғурта мехоҳед?", "Бигӯ: ҳа, бо суғурта бошад", "Evet, sigortalı olsun.",
              "Ҳа, бо суғурта бошад.", ["Evet."]),
            t("Tamam, elli lira ekstra.", "Хуб, панҷоҳ лира иловагӣ.", "Бигӯ: хуб", "Tamam.", "Хуб.", ["Olur."]),
        ]),
        ("Миссия: тӯҳфа ба оила", [
            t("Buyurun?", "Марҳамат?", "Бигӯ: ба Тоҷикистон баста мефиристам", "Tacikistan'a kargo göndereceğim.",
              "Ба Тоҷикистон баста мефиристам.", ["Kargo göndereceğim."]),
            t("İçinde ne var?", "Дарунаш чист?", "Бигӯ: чизи шикастанӣ ҳаст", "Kırılacak eşya var.",
              "Чизи шикастанӣ ҳаст.", ["Hediye var."]),
            t("Dört kilo. Bin iki yüz lira.", "Чор кило. Ҳазору дусад лира.", "Бипурс: чӣ қадар мегирад?",
              "Ne kadar sürer?", "Чӣ қадар мегирад?", ["Ne zaman ulaşır?"]),
            t("İki hafta. Takip numarası bu.", "Ду ҳафта. Рақами пайгирӣ ин.", "Ташаккур гӯй", "Teşekkürler!",
              "Ташаккур!", ["Sağ olun!"]),
        ]),
    ]))

# ═════════════════════ 15. Ҳамсояҳо ═════════════════════
made.append(pack("neighbors_tr_tg", "Komşular", "Ҳамсояҳо", "🏠", 15, LF,
    "Шумо бо ҳамсояҳо шинос мешавед: худро муаррифӣ мекунед, ёрӣ мепурсед, дар бораи садо ё "
    "партов гап мезанед ва ба чой даъват мекунед.",
    [
        ("Хона", [
            w("Komşu", "ҳамсоя", None),
            w("Apartman", "бино (хонаи бисёрқабата)", None),
            w("Kapıcı", "дарбон", None),
            w("Gürültü", "садо (ғавғо)", None),
            w("Çöp", "партов", None),
            w("Misafir", "меҳмон", None),
        ]),
        ("Шиносоӣ", [
            t("Merhaba! Yeni misiniz?", "Салом! Навед?", "Бигӯ: ҳа, ҳамсояи нав", "Evet, yeni komşuyum.",
              "Ҳа, ҳамсояи навам.", ["Evet, yeniyim."]),
            t("Hoş geldiniz! Ben Ayşe.", "Хуш омадед! Ман Айше.", "Бигӯ: ман Фаридун, шодам",
              "Ben Feridun, memnun oldum.", "Ман Фаридун, шодам.", ["Memnun oldum."]),
            t("Hangi daire?", "Кадом хонадон?", "Бигӯ: хонадони ҳафт", "Daire yedi.", "Хонадони ҳафт.",
              ["Yedi numara."]),
        ]),
        ("Ибораҳо", [
            s("Yeni komşuyum", "Ҳамсояи навам", None),
            s("Daire yedi", "Хонадони ҳафт", None),
            s("Kolay gelsin", "Кор осон шавад", None),
            s("Çöp günü", "Рӯзи партов", None),
            s("Çaya buyurun", "Ба чой марҳамат", None),
            s("Çok teşekkürler", "Ташаккури зиёд", None),
        ]),
        ("Партов", [
            t("Merhaba komşu!", "Салом, ҳамсоя!", "Бипурс: партов кай бурда мешавад?", "Çöp ne zaman alınıyor?",
              "Партов кай бурда мешавад?", ["Çöp günü ne zaman?"]),
            t("Her akşam, saat sekizde.", "Ҳар шом, соати ҳашт.", "Бипурс: дар куҷо мегузорем?", "Nereye koyuyoruz?",
              "Дар куҷо мегузорем?", ["Nereye?"]),
            t("Kapının önüne.", "Назди дар.", "Бигӯ: фаҳмидам, ташаккур", "Anladım, teşekkürler.",
              "Фаҳмидам, ташаккур.", ["Sağ olun."]),
        ]),
        ("Хоҳиш", [
            s("Bir ricam var.", "Як хоҳиш дорам.", None),
            s("Matkabınız var mı?", "Пармаатон ҳаст?", None),
            s("Yarın geri veririm.", "Фардо бармегардонам.", None),
            s("Kapıcı nerede?", "Дарбон куҷост?", None),
            s("Su kesik mi?", "Об қатъ шудааст?", None),
            s("Tabii, buyurun.", "Албатта, марҳамат.", None),
        ]),
        ("Парма", [
            t("Buyurun?", "Марҳамат?", "Бигӯ: як хоҳиш дорам", "Bir ricam var.", "Як хоҳиш дорам.",
              ["Bir şey soracağım."]),
            t("Tabii, söyleyin.", "Албатта, гӯед.", "Бипурс: пармаатон ҳаст?", "Matkabınız var mı?",
              "Пармаатон ҳаст?", ["Matkap var mı?"]),
            t("Var, buyurun.", "Ҳаст, марҳамат.", "Бигӯ: фардо бармегардонам", "Yarın geri veririm.",
              "Фардо бармегардонам.", ["Teşekkürler, yarın veririm."]),
        ]),
        ("Садо", [
            s("Gece çok gürültü var.", "Шаб садо зиёд.", None),
            s("Özür dilerim.", "Бубахшед.", None),
            s("Misafirlerim vardı.", "Меҳмон доштам.", None),
            s("Bir daha olmaz.", "Дигар намешавад.", None),
            s("Bize çaya gelin.", "Ба мо ба чой биёед.", None),
            s("Seve seve!", "Бо камоли майл!", None),
        ]),
        ("Ғавғои шаб", [
            t("Dün gece çok gürültü vardı.", "Дишаб садо зиёд буд.", "Бигӯ: бубахшед, меҳмон доштам",
              "Özür dilerim, misafirlerim vardı.", "Бубахшед, меҳмон доштам.", ["Özür dilerim."]),
            t("Tamam, sorun değil.", "Хуб, мушкил нест.", "Бигӯ: дигар намешавад", "Bir daha olmaz.",
              "Дигар намешавад.", ["Olmaz."]),
            t("Teşekkürler komşu.", "Ташаккур, ҳамсоя.", "Бигӯ: ба мо ба чой биёед", "Bize çaya gelin.",
              "Ба мо ба чой биёед.", ["Çaya buyurun."]),
        ]),
        ("Миссия: ҳамсояи нав", [
            t("Merhaba! Yeni misiniz?", "Салом! Навед?", "Бигӯ: ҳа, ҳамсояи навам", "Evet, yeni komşuyum.",
              "Ҳа, ҳамсояи навам.", ["Evet, yeniyim."]),
            t("Hoş geldiniz! Hangi daire?", "Хуш омадед! Кадом хонадон?", "Бигӯ: хонадони ҳафт", "Daire yedi.",
              "Хонадони ҳафт.", ["Yedi numara."]),
            t("Bir şey lazım olursa söyleyin.", "Агар чизе лозим шавад, гӯед.", "Бипурс: партов кай бурда мешавад?",
              "Çöp ne zaman alınıyor?", "Партов кай бурда мешавад?", ["Çöp günü ne zaman?"]),
            t("Her akşam sekizde.", "Ҳар шом соати ҳашт.", "Бигӯ: ба мо ба чой биёед", "Bize çaya gelin.",
              "Ба мо ба чой биёед.", ["Çaya buyurun."]),
        ]),
    ]))

# ═════════════════════ 17. Гум шудам ═════════════════════
made.append(pack("lost_tr_tg", "Kayboldum", "Гум шудам", "🧭", 17, LF,
    "Шумо дар шаҳр гум шудед: аз роҳгузар мепурсед, ки истгоҳ ё кӯча куҷост, суроғаро нишон "
    "медиҳед ва роҳро мефаҳмед.",
    [
        ("Шаҳр", [
            w("Sokak", "кӯча", None),
            w("Meydan", "майдон", None),
            w("Cami", "масҷид", None),
            w("Köşe", "гӯша", None),
            w("Yakın", "наздик", None),
            w("Uzak", "дур", None),
        ]),
        ("Бубахшед!", [
            t("Buyurun?", "Марҳамат?", "Бигӯ: бубахшед, гум шудам", "Pardon, kayboldum.", "Бубахшед, гум шудам.",
              ["Kayboldum."]),
            t("Nereye gidiyorsunuz?", "Ба куҷо меравед?", "Бигӯ: ба метро", "Metroya.", "Ба метро.",
              ["Metro nerede?"]),
            t("Düz gidin, sonra sağa.", "Рост равед, баъд ба рост.", "Бигӯ: хеле ташаккур", "Çok teşekkürler.",
              "Хеле ташаккур.", ["Sağ olun."]),
        ]),
        ("Ибораҳо", [
            w("Kayboldum", "гум шудам", None),
            s("Burası neresi?", "Ин ҷо куҷост?", None),
            s("Yakın mı?", "Наздик аст?", None),
            s("Yürüyerek mi?", "Пиёда?", None),
            s("Haritada gösterin", "Дар харита нишон диҳед", None),
            s("Caminin yanında", "Дар назди масҷид", None),
        ]),
        ("Наздик аст?", [
            t("Bu adres nerede?", "Ин суроға куҷост?", "Бигӯ: инро дар телефон бинед", "Telefonda bakın.",
              "Дар телефон бинед.", ["Bakın, bu adres."]),
            t("Aa, Gül Sokak. Caminin yanında.", "О, кӯчаи Гул. Назди масҷид.", "Бипурс: наздик аст?", "Yakın mı?",
              "Наздик аст?", ["Uzak mı?"]),
            t("Evet, beş dakika.", "Ҳа, панҷ дақиқа.", "Бигӯ: олӣ, ташаккур", "Süper, teşekkürler.",
              "Олӣ, ташаккур.", ["Sağ olun."]),
        ]),
        ("Ман мепурсам", [
            s("Burası neresi?", "Ин ҷо куҷост?", None),
            s("Metro nerede?", "Метро куҷост?", None),
            s("Bu sokak hangisi?", "Ин кӯча кадом аст?", None),
            s("Yolu gösterir misiniz?", "Роҳро нишон медиҳед?", None),
            s("Yavaş söyler misiniz?", "Оҳиста мегӯед?", None),
            s("Telefonumun şarjı bitti.", "Заряди телефонам тамом шуд.", None),
        ]),
        ("Заряд тамом", [
            t("Ne oldu?", "Чӣ шуд?", "Бигӯ: заряди телефонам тамом шуд", "Telefonumun şarjı bitti.",
              "Заряди телефонам тамом шуд.", ["Şarjım bitti."]),
            t("Nereye gidiyorsunuz?", "Ба куҷо меравед?", "Бигӯ: ба майдони Таксим", "Taksim Meydanı'na.",
              "Ба майдони Таксим.", ["Taksim'e."]),
            t("Soldan, sonra düz.", "Аз чап, баъд рост.", "Бипурс: оҳиста мегӯед?", "Yavaş söyler misiniz?",
              "Оҳиста мегӯед?", ["Bir daha lütfen."]),
        ]),
        ("Роҳ", [
            s("Köşeden sola dönün.", "Аз гӯша ба чап гардед.", None),
            s("Köprüyü geçin.", "Аз пул гузаред.", None),
            s("Caminin karşısında.", "Рӯ ба рӯи масҷид.", None),
            s("On dakika yürüyün.", "Даҳ дақиқа пиёда равед.", None),
            s("Otobüs daha iyi.", "Автобус беҳтар.", None),
            s("Ben de oraya gidiyorum.", "Ман ҳам он ҷо меравам.", None),
        ]),
        ("Ҳамроҳ", [
            t("Uzak mı?", "Дур аст?", "Бигӯ: даҳ дақиқа пиёда", "On dakika yürüyün.", "Даҳ дақиқа пиёда равед.",
              ["Biraz uzak."]),
            t("Ben de oraya gidiyorum.", "Ман ҳам он ҷо меравам.", "Бигӯ: олӣ! ташаккур", "Süper! Teşekkürler.",
              "Олӣ! Ташаккур.", ["Çok iyi!"]),
            t("Gelin, beraber gidelim.", "Биёед, якҷоя равем.", "Бигӯ: хуб", "Tamam.", "Хуб.", ["Olur."]),
        ]),
        ("Миссия: шаби бе заряд", [
            t("Buyurun? Bir sorun mu var?", "Марҳамат? Мушкил ҳаст?", "Бигӯ: бубахшед, гум шудам",
              "Pardon, kayboldum.", "Бубахшед, гум шудам.", ["Kayboldum."]),
            t("Nereye gidiyorsunuz?", "Ба куҷо меравед?", "Бигӯ: ба метро", "Metroya.", "Ба метро.",
              ["Metro nerede?"]),
            t("Köşeden sola, sonra düz.", "Аз гӯша ба чап, баъд рост.", "Бипурс: наздик аст?", "Yakın mı?",
              "Наздик аст?", ["Uzak mı?"]),
            t("Evet, beş dakika.", "Ҳа, панҷ дақиқа.", "Бигӯ: хеле ташаккур", "Çok teşekkürler.", "Хеле ташаккур.",
              ["Sağ olun."]),
        ]),
    ]))

# ═════════════════════ 18. Вақти холӣ ═════════════════════
made.append(pack("free_time_tr_tg", "Boş zaman", "Вақти холӣ", "🎉", 18, LF,
    "Рӯзи истироҳат: шумо дӯстонро ба сайр, футбол ё ошхона даъват мекунед, вақт ва ҷои вохӯриро "
    "мувофиқа мекунед ва дар бораи шавқҳоятон гап мезанед.",
    [
        ("Истироҳат", [
            w("Hafta sonu", "охири ҳафта", None),
            w("Futbol", "футбол", None),
            w("Park", "боғ", None),
            w("Sahil", "соҳил", None),
            w("Film", "филм", None),
            w("Arkadaş", "дӯст", None),
        ]),
        ("Даъват", [
            t("Hafta sonu ne yapıyorsun?", "Охири ҳафта чӣ мекунӣ?", "Бигӯ: ҳеҷ чиз", "Hiçbir şey.", "Ҳеҷ чиз.",
              ["Bir planım yok."]),
            t("Futbol oynayalım mı?", "Футбол бозӣ кунем?", "Бигӯ: ҳа, бо камоли майл", "Evet, seve seve!",
              "Ҳа, бо камоли майл!", ["Olur!"]),
            t("Pazar, saat onda.", "Якшанбе, соати даҳ.", "Бипурс: дар куҷо?", "Nerede?", "Дар куҷо?",
              ["Nerede buluşuyoruz?"]),
        ]),
        ("Ибораҳо", [
            s("Hafta sonu", "Охири ҳафта", None),
            s("Seve seve!", "Бо камоли майл!", None),
            s("Nerede buluşalım?", "Дар куҷо вохӯрем?", None),
            s("Saat kaçta?", "Соати чанд?", None),
            s("Maalesef olmaz", "Афсӯс, намешавад", None),
            s("Başka zaman", "Вақти дигар", None),
        ]),
        ("Ҷои вохӯрӣ", [
            t("Sahile gidelim mi?", "Ба соҳил равем?", "Бигӯ: фикри хуб!", "İyi fikir!", "Фикри хуб!",
              ["Olur!"]),
            t("Cumartesi olur mu?", "Шанбе мешавад?", "Бипурс: соати чанд?", "Saat kaçta?", "Соати чанд?",
              ["Kaçta?"]),
            t("Öğlen, metroda buluşalım.", "Нисфирӯзӣ, дар метро вохӯрем.", "Бигӯ: хуб, то шанбе",
              "Tamam, cumartesi görüşürüz.", "Хуб, то шанбе.", ["Görüşürüz."]),
        ]),
        ("Шавқҳои ман", [
            s("Futbolu çok seviyorum.", "Футболро хеле дӯст медорам.", None),
            s("Türk dizileri izliyorum.", "Сериалҳои туркӣ мебинам.", None),
            s("Pazar günü dinleniyorum.", "Якшанбе истироҳат мекунам.", None),
            s("Yemek yapmayı seviyorum.", "Хӯрок пухтанро дӯст медорам.", None),
            s("Plov yaparım.", "Палав мепазам.", None),
            s("Sen ne seversin?", "Ту чиро дӯст медорӣ?", None),
        ]),
        ("Палав", [
            t("Boş zamanında ne yaparsın?", "Дар вақти холӣ чӣ мекунӣ?", "Бигӯ: хӯрок пухтанро дӯст медорам",
              "Yemek yapmayı seviyorum.", "Хӯрок пухтанро дӯст медорам.", ["Yemek yaparım."]),
            t("Ne yaparsın?", "Чӣ мепазӣ?", "Бигӯ: палав мепазам", "Plov yaparım.", "Палав мепазам.",
              ["Tacik plovu."]),
            t("Vay! Tatmak isterim.", "Вой! Чашидан мехоҳам.", "Бигӯ: ба мо биё", "Bize gel.", "Ба мо биё.",
              ["Pazar günü gel."]),
        ]),
        ("Рад кардан", [
            s("Maalesef çalışıyorum.", "Афсӯс, кор мекунам.", None),
            s("Bu hafta olmaz.", "Ин ҳафта намешавад.", None),
            s("Gelecek hafta olur mu?", "Ҳафтаи оянда мешавад?", None),
            s("Çok yorgunum.", "Хеле хастаам.", None),
            s("Belki akşam.", "Шояд шом.", None),
            s("Haber veririm.", "Хабар медиҳам.", None),
        ]),
        ("Ин ҳафта намешавад", [
            t("Pazar sinemaya gidelim mi?", "Якшанбе ба кино равем?", "Бигӯ: афсӯс, кор мекунам",
              "Maalesef çalışıyorum.", "Афсӯс, кор мекунам.", ["Bu hafta olmaz."]),
            t("Yazık! Ne zaman boşsun?", "Ҳайф! Кай холӣ ҳастӣ?", "Бипурс: ҳафтаи оянда мешавад?",
              "Gelecek hafta olur mu?", "Ҳафтаи оянда мешавад?", ["Gelecek hafta?"]),
            t("Olur!", "Мешавад!", "Бигӯ: хабар медиҳам", "Haber veririm.", "Хабар медиҳам.", ["Yazarım."]),
        ]),
        ("Миссия: нақшаи якшанбе", [
            t("Hafta sonu ne yapıyorsun?", "Охири ҳафта чӣ мекунӣ?", "Бигӯ: ҳеҷ чиз", "Hiçbir şey.", "Ҳеҷ чиз.",
              ["Bir planım yok."]),
            t("Sahile gidelim mi?", "Ба соҳил равем?", "Бигӯ: фикри хуб!", "İyi fikir!", "Фикри хуб!", ["Olur!"]),
            t("Pazar, saat on birde.", "Якшанбе, соати ёздаҳ.", "Бипурс: дар куҷо вохӯрем?", "Nerede buluşalım?",
              "Дар куҷо вохӯрем?", ["Nerede?"]),
            t("Metroda.", "Дар метро.", "Бигӯ: хуб, то якшанбе", "Tamam, pazar görüşürüz.", "Хуб, то якшанбе.",
              ["Görüşürüz."]),
        ]),
    ]))

# ═════════════════════ 19. Занги фаврӣ ═════════════════════
made.append(pack("emergency_tr_tg", "Acil arama", "Занги фаврӣ", "🚨", 19, LF,
    "Ҳолати фаврӣ: шумо ба 112 занг мезанед, мегӯед, ки чӣ шуд, суроғаро дақиқ мегӯед ва ба "
    "саволҳои оператор ором ҷавоб медиҳед.",
    [
        ("Фаврӣ", [
            w("Acil", "фаврӣ", None),
            w("Ambulans", "ёрии таъҷилӣ", None),
            w("Yangın", "сӯхтор", None),
            w("Polis", "полис", None),
            w("Yaralı", "захмӣ", None),
            w("Nefes", "нафас", None),
        ]),
        ("Ёрӣ лозим", [
            t("Yüz on iki, acil. Buyurun.", "112, фаврӣ. Марҳамат.", "Бигӯ: ёрии таъҷилӣ лозим",
              "Ambulans lazım.", "Ёрии таъҷилӣ лозим.", ["Yardım edin!"]),
            t("Ne oldu?", "Чӣ шуд?", "Бигӯ: дӯстам афтод", "Arkadaşım düştü.", "Дӯстам афтод.", ["Biri düştü."]),
            t("Adres ne?", "Суроға чист?", "Бигӯ: кӯчаи Гул, дувоздаҳ", "Gül Sokak, on iki.",
              "Кӯчаи Гул, дувоздаҳ.", ["Gül Sokak."]),
        ]),
        ("Ибораҳо", [
            s("Ambulans lazım", "Ёрии таъҷилӣ лозим", None),
            s("Yardım edin!", "Ёрӣ диҳед!", None),
            s("Nefes alıyor", "Нафас мегирад", None),
            s("Kan var", "Хун ҳаст", None),
            s("Bilinci açık", "Ба худ аст", None),
            s("Acele edin!", "Шитоб кунед!", None),
        ]),
        ("Саволҳои оператор", [
            t("Nefes alıyor mu?", "Нафас мегирад?", "Бигӯ: ҳа, нафас мегирад", "Evet, nefes alıyor.",
              "Ҳа, нафас мегирад.", ["Evet."]),
            t("Bilinci açık mı?", "Ба худ аст?", "Бигӯ: ҳа, гап мезанад", "Evet, konuşuyor.", "Ҳа, гап мезанад.",
              ["Evet, açık."]),
            t("Ambulans geliyor.", "Ёрии таъҷилӣ меояд.", "Бигӯ: шитоб кунед!", "Acele edin!", "Шитоб кунед!",
              ["Lütfen çabuk!"]),
        ]),
        ("Ман хабар медиҳам", [
            s("Arkadaşım çok hasta.", "Дӯстам хеле бемор.", None),
            s("İş yerinde kaza oldu.", "Дар ҷои кор садама шуд.", None),
            s("Bacağı kırıldı galiba.", "Пояш шикаст, гумон кунам.", None),
            s("Evde yangın var!", "Дар хона сӯхтор!", None),
            s("Türkçem az.", "Туркиам кам.", None),
            s("Yavaş konuşun lütfen.", "Оҳиста гап занед, лутфан.", None),
        ]),
        ("Садама дар кор", [
            t("Acil, buyurun.", "Фаврӣ, марҳамат.", "Бигӯ: дар ҷои кор садама шуд", "İş yerinde kaza oldu.",
              "Дар ҷои кор садама шуд.", ["Kaza oldu."]),
            t("Ne oldu? Anlatın.", "Чӣ шуд? Нақл кунед.", "Бигӯ: пояш шикаст, гумон кунам", "Bacağı kırıldı galiba.",
              "Пояш шикаст, гумон кунам.", ["Bacağı kırık."]),
            t("Adres? Hızlı söyleyin.", "Суроға? Тез гӯед.", "Бигӯ: туркиам кам, оҳиста гап занед",
              "Türkçem az, yavaş konuşun.", "Туркиам кам, оҳиста гап занед.", ["Yavaş lütfen."]),
        ]),
        ("Суроға", [
            s("Adres Gül Sokak.", "Суроға кӯчаи Гул.", None),
            s("Bina numarası on iki.", "Рақами бино дувоздаҳ.", None),
            s("Üçüncü kat.", "Қабати сеюм.", None),
            s("İnşaatın yanında.", "Дар назди сохтмон.", None),
            s("Kapıda bekliyorum.", "Дар назди дар интизорам.", None),
            s("Telefon numaram bu.", "Рақами телефонам ин.", None),
        ]),
        ("Дақиқ кардан", [
            t("Adres ne?", "Суроға чист?", "Бигӯ: суроға кӯчаи Гул", "Adres Gül Sokak.", "Суроға кӯчаи Гул.",
              ["Gül Sokak."]),
            t("Bina numarası?", "Рақами бино?", "Бигӯ: рақами бино дувоздаҳ", "Bina numarası on iki.",
              "Рақами бино дувоздаҳ.", ["On iki."]),
            t("Tamam, ambulans yolda.", "Хуб, ёрии таъҷилӣ дар роҳ.", "Бигӯ: дар назди дар интизорам",
              "Kapıda bekliyorum.", "Дар назди дар интизорам.", ["Bekliyorum."]),
        ]),
        ("Миссия: занг ба 112", [
            t("Yüz on iki, acil.", "112, фаврӣ.", "Бигӯ: ёрии таъҷилӣ лозим", "Ambulans lazım.",
              "Ёрии таъҷилӣ лозим.", ["Yardım edin!"]),
            t("Ne oldu?", "Чӣ шуд?", "Бигӯ: дар ҷои кор садама шуд", "İş yerinde kaza oldu.",
              "Дар ҷои кор садама шуд.", ["Kaza oldu."]),
            t("Nefes alıyor mu?", "Нафас мегирад?", "Бигӯ: ҳа, нафас мегирад", "Evet, nefes alıyor.",
              "Ҳа, нафас мегирад.", ["Evet."]),
            t("Adres?", "Суроға?", "Бигӯ: кӯчаи Гул, дувоздаҳ", "Gül Sokak, on iki.", "Кӯчаи Гул, дувоздаҳ.",
              ["Gül Sokak."]),
        ]),
    ], mission_mode="call"))

# ═════════════════════ 20. Дар сартарошхона ═════════════════════
made.append(pack("barber_tr_tg", "Berberde", "Дар сартарошхона", "💈", 20, LF,
    "Шумо ба сартарош (berber) меравед: мегӯед, ки мӯйро чӣ тавр кӯтоҳ кунад, ришро ҳам, нархро "
    "мепурсед ва ташаккур мегӯед.",
    [
        ("Сартарош", [
            w("Berber", "сартарош", None),
            w("Saç", "мӯй", None),
            w("Sakal", "риш", None),
            w("Kısa", "кӯтоҳ", None),
            w("Uzun", "дароз", None),
            w("Ayna", "оина", None),
        ]),
        ("Навбат", [
            t("Hoş geldin abi!", "Хуш омадӣ, ака!", "Бипурс: навбат ҳаст?", "Sıra var mı?", "Навбат ҳаст?",
              ["Beklemek var mı?"]),
            t("On dakika bekle.", "Даҳ дақиқа интизор шав.", "Бигӯ: хуб, интизор мешавам", "Tamam, beklerim.",
              "Хуб, интизор мешавам.", ["Tamam."]),
            t("Buyur, otur.", "Марҳамат, шин.", "Ташаккур гӯй", "Sağ ol abi.", "Ташаккур, ака.", ["Teşekkürler."]),
        ]),
        ("Ибораҳо", [
            s("Saç kesimi", "Кӯтоҳ кардани мӯй", None),
            s("Kısa lütfen", "Кӯтоҳ, лутфан", None),
            s("Yanlar kısa", "Паҳлӯҳо кӯтоҳ", None),
            s("Üstü uzun", "Болояш дароз", None),
            s("Sakal da", "Риш ҳам", None),
            w("Kolonya", "одеколон", None),
        ]),
        ("Чӣ тавр?", [
            t("Nasıl keselim?", "Чӣ тавр кӯтоҳ кунем?", "Бигӯ: паҳлӯҳо кӯтоҳ", "Yanlar kısa.", "Паҳлӯҳо кӯтоҳ.",
              ["Kısa lütfen."]),
            t("Üstü?", "Болояш?", "Бигӯ: болояш каме", "Üstü biraz.", "Болояш каме.", ["Üstü uzun kalsın."]),
            t("Sakal da mı?", "Риш ҳам?", "Бигӯ: ҳа, риш ҳам", "Evet, sakal da.", "Ҳа, риш ҳам.", ["Evet."]),
        ]),
        ("Ман мегӯям", [
            s("Çok kısa olmasın.", "Хеле кӯтоҳ набошад.", None),
            s("Sakalı düzelt lütfen.", "Ришро ислоҳ кун, лутфан.", None),
            s("Arkası biraz daha.", "Қафояш боз каме.", None),
            s("Böyle iyi.", "Ҳамин тавр хуб.", None),
            s("Ne kadar?", "Чанд?", None),
            s("Eline sağlık!", "Дастат дард накунад!", None),
        ]),
        ("Оина", [
            t("Bak, nasıl?", "Бин, чӣ хел?", "Бигӯ: қафояш боз каме", "Arkası biraz daha.", "Қафояш боз каме.",
              ["Biraz daha kısa."]),
            t("Tamam. Şimdi?", "Хуб. Ҳоло?", "Бигӯ: ҳамин тавр хуб", "Böyle iyi.", "Ҳамин тавр хуб.", ["Süper!"]),
            t("Kolonya?", "Одеколон?", "Бигӯ: ҳа, лутфан", "Evet, lütfen.", "Ҳа, лутфан.", ["Olur."]),
        ]),
        ("Пардохт", [
            s("Saç sakal ne kadar?", "Мӯй ва риш чанд?", None),
            s("İki yüz lira.", "Дусад лира.", None),
            s("Kartla olur mu?", "Бо корт мешавад?", None),
            s("Sadece nakit.", "Танҳо нақд.", None),
            s("Gelecek ay yine gelirim.", "Моҳи оянда боз меоям.", None),
            s("Sıhhatler olsun!", "Саломат бошед!", "Сартарош баъди кор мегӯяд."),
        ]),
        ("Танҳо нақд", [
            t("Sıhhatler olsun!", "Саломат бошед!", "Бигӯ: дастат дард накунад! Чанд?", "Eline sağlık! Ne kadar?",
              "Дастат дард накунад! Чанд?", ["Ne kadar abi?"]),
            t("İki yüz lira.", "Дусад лира.", "Бипурс: бо корт мешавад?", "Kartla olur mu?", "Бо корт мешавад?",
              ["Kart geçer mi?"]),
            t("Sadece nakit.", "Танҳо нақд.", "Бигӯ: хуб, марҳамат", "Tamam, buyurun.", "Хуб, марҳамат.",
              ["Buyurun."]),
        ]),
        ("Миссия: пеш аз тӯй", [
            t("Hoş geldin! Nasıl keselim?", "Хуш омадӣ! Чӣ тавр кӯтоҳ кунем?", "Бигӯ: паҳлӯҳо кӯтоҳ",
              "Yanlar kısa.", "Паҳлӯҳо кӯтоҳ.", ["Kısa lütfen."]),
            t("Sakal da mı?", "Риш ҳам?", "Бигӯ: ҳа, ришро ислоҳ кун", "Evet, sakalı düzelt.", "Ҳа, ришро ислоҳ кун.",
              ["Evet, sakal da."]),
            t("Bak, nasıl?", "Бин, чӣ хел?", "Бигӯ: ҳамин тавр хуб", "Böyle iyi.", "Ҳамин тавр хуб.", ["Süper!"]),
            t("İki yüz lira.", "Дусад лира.", "Бигӯ: марҳамат. Дастат дард накунад!", "Buyurun. Eline sağlık!",
              "Марҳамат. Дастат дард накунад!", ["Eline sağlık!"]),
        ]),
    ]))

finish(made)
