import { W } from './b1-api-build.mjs';

export const M = {
  order: 6, title: 'Module 6: Technology and Communication', titleTranslated: 'Модули 6: Технология ва Алоқа',
  emoji: '💻', color: '#3B82F6',
  vocab: [
    { title: 'Lesson 1: Devices', tt: 'Дарси 1: Дастгоҳҳо', emoji: '📱', words: [
      W('Gadget','/ˈɡædʒɪt/','гаҷит','Дастгоҳи хурд','🔌','He loves buying new gadgets.','Ӯ харидани дастгоҳҳои навро дӯст медорад.','noun'),
      W('Smartphone','/ˈsmɑːtfəʊn/','смартфон','Смартфон','📱','My smartphone battery lasts all day.','Батареяи смартфони ман тамоми рӯз кор мекунад.','noun'),
      W('Touchscreen','/ˈtʌtʃskriːn/','тачскриин','Экрани ламсӣ','👆','The touchscreen is easy to use.','Экрани ламсӣ барои истифода осон аст.','noun'),
      W('Router','/ˈruːtə/','рутер','Роутер','📡','Restart the router if the internet is slow.','Агар интернет суст бошад, роутерро аз нав фаъол кунед.','noun'),
      W('Headset','/ˈhedset/','ҳедсет','Гӯшмонак','🎧','I use a headset for online meetings.','Ман барои вохӯриҳои онлайн гӯшмонак истифода мебарам.','noun'),
      W('Microphone','/ˈmaɪkrəfəʊn/','майкрафон','Микрофон','🎙️','Please turn on your microphone.','Лутфан микрофонатонро фаъол кунед.','noun'),
      W('Hardware','/ˈhɑːdweə/','ҳардвер','Сахтафзор','🖥️','The computer hardware is very modern.','Сахтафзори компютер хеле муосир аст.','noun'),
      W('Software','/ˈsɒftweə/','софтвер','Нармафзор','💿','This software is free to download.','Ин нармафзор барои зеркашӣ ройгон аст.','noun'),
      W('Storage','/ˈstɔːrɪdʒ/','сториҷ','Ҳофиза / нигоҳдорӣ','🗄️','My phone is running out of storage.','Ҳофизаи телефонам тамом шуда истодааст.','noun'),
      W('Backup','/ˈbækʌp/','бекап','Нусхаи эҳтиётӣ','💾','Always keep a backup of your files.','Ҳамеша нусхаи эҳтиётии файлҳоятонро нигоҳ доред.','noun'),
    ]},
    { title: 'Lesson 2: The Internet', tt: 'Дарси 2: Интернет', emoji: '🌐', words: [
      W('Wi-Fi','/ˈwaɪfaɪ/','вайфай','Wi-Fi / интернети бесим','📶','Is there free Wi-Fi in the café?','Дар қаҳвахона Wi-Fi-и ройгон ҳаст?','noun'),
      W('Signal','/ˈsɪɡnəl/','сигнал','Сигнал','📡','The signal is weak in this area.','Дар ин минтақа сигнал заиф аст.','noun'),
      W('Data','/ˈdeɪtə/','дейта','Маълумот / трафик','📊','Streaming videos uses a lot of data.','Тамошои видео трафики зиёд сарф мекунад.','noun'),
      W('Connection','/kəˈnekʃn/','конекшн','Пайваст','🔗','I lost my internet connection.','Пайвасти интернетам қатъ шуд.','noun'),
      W('Offline','/ˌɒfˈlaɪn/','офлайн','Ғайрифаъол / офлайн','🚫','You can read the articles offline.','Шумо мақолаҳоро офлайн хонда метавонед.','adjective'),
      W('Search engine','/ˈsɜːtʃ ˌendʒɪn/','сёрч энҷин','Системаи ҷустуҷӯ','🔎','Google is a popular search engine.','Google системаи ҷустуҷӯи маъмул аст.','noun'),
      W('Attachment','/əˈtætʃmənt/','атачмент','Замима','📎','I sent the report as an attachment.','Ман ҳисоботро ҳамчун замима фиристодам.','noun'),
      W('Inbox','/ˈɪnbɒks/','инбокс','Қуттии вуруд','📥','My inbox is full of emails.','Қуттии вуруди ман пур аз мактубҳост.','noun'),
      W('Spam','/spæm/','спам','Спам / мактуби нохоста','🗑️','Delete the spam messages.','Паёмҳои спамро нест кунед.','noun'),
      W('Username','/ˈjuːzəneɪm/','юзернейм','Номи корбар','👤','Choose a username and a password.','Номи корбар ва рамзро интихоб кунед.','noun'),
    ]},
    { title: 'Lesson 3: Social Media', tt: 'Дарси 3: Шабакаҳои иҷтимоӣ', emoji: '📲', words: [
      W('Profile','/ˈprəʊfaɪl/','профайл','Профил','🪪','She updated her profile picture.','Вай сурати профилашро нав кард.','noun'),
      W('Subscriber','/səbˈskraɪbə/','сабскрайбер','Обуначӣ','🔔','His channel has a million subscribers.','Канали ӯ як миллион обуначӣ дорад.','noun'),
      W('Influencer','/ˈɪnfluənsə/','инфлуэнсер','Инфлюенсер / таъсиргузор','🌟','The influencer promoted a new brand.','Инфлюенсер брендҳои навро таблиғ кард.','noun'),
      W('Trend','/trend/','тренд','Тренд / майл','📈','This video started a new trend.','Ин видео тренди навро оғоз кард.','noun'),
      W('Viral','/ˈvaɪrəl/','вайрал','Вирусӣ / зудпаҳншаванда','🚀','The clip went viral overnight.','Клип дар як шаб вирусӣ шуд.','adjective'),
      W('Livestream','/ˈlaɪvstriːm/','лайвстриим','Пахши мустақим','🔴','They watched the concert on a livestream.','Онҳо консертро тавассути пахши мустақим тамошо карданд.','noun'),
      W('Swipe','/swaɪp/','свайп','Кашидан (бо ангушт)','👉','Swipe left to see more photos.','Барои дидани аксҳои бештар ба чап кашед.','verb'),
      W('Click','/klɪk/','клик','Пахш кардан / клик','🖱️','Click the link to open the page.','Барои кушодани саҳифа ба пайванд клик кунед.','verb'),
      W('Screenshot','/ˈskriːnʃɒt/','скриншот','Скриншот / акси экран','📸','She took a screenshot of the message.','Вай аз паём скриншот гирифт.','noun'),
      W('Privacy','/ˈprɪvəsi/','прайваси','Махфият','🔒','Check your privacy settings.','Танзимоти махфиятатонро тафтиш кунед.','noun'),
    ]},
    { title: 'Lesson 4: Security and AI', tt: 'Дарси 4: Амният ва зеҳни сунъӣ', emoji: '🤖', words: [
      W('Virus','/ˈvaɪrəs/','вайрус','Вирус (компютерӣ)','🦠','A virus infected his computer.','Вирус компютери ӯро сироят кард.','noun'),
      W('Hacker','/ˈhækə/','ҳакер','Ҳакер','🕵️','Hackers stole the company data.','Ҳакерҳо маълумоти ширкатро дуздиданд.','noun'),
      W('Cybersecurity','/ˌsaɪbəsɪˈkjʊərəti/','сайберсикюрити','Амнияти киберӣ','🛡️','Cybersecurity protects our information.','Амнияти киберӣ маълумоти моро ҳифз мекунад.','noun'),
      W('Firewall','/ˈfaɪəwɔːl/','файервол','Девори оташ (муҳофиз)','🧱','A firewall blocks dangerous websites.','Девори оташ вебсайтҳои хатарнокро баста мекунад.','noun'),
      W('Encryption','/ɪnˈkrɪpʃn/','инкрипшн','Рамзгузорӣ','🔐','Encryption keeps your messages private.','Рамзгузорӣ паёмҳои шуморо махфӣ нигоҳ медорад.','noun'),
      W('Algorithm','/ˈælɡərɪðəm/','алгоритм','Алгоритм','🧮','The app uses a smart algorithm.','Барнома алгоритми зирак истифода мебарад.','noun'),
      W('Artificial intelligence','/ˌɑːtɪˈfɪʃl ɪnˈtelɪdʒəns/','артифишл интелиҷенс','Зеҳни сунъӣ','🤖','Artificial intelligence is changing the world.','Зеҳни сунъӣ ҷаҳонро тағйир дода истодааст.','noun'),
      W('Robot','/ˈrəʊbɒt/','робот','Робот','🦾','Robots build cars in this factory.','Дар ин корхона роботҳо мошин месозанд.','noun'),
      W('Automation','/ˌɔːtəˈmeɪʃn/','отомейшн','Худкорсозӣ','⚙️','Automation has replaced many jobs.','Худкорсозӣ бисёр ҷойҳои корро иваз кардааст.','noun'),
      W('Bluetooth','/ˈbluːtuːθ/','блутут','Bluetooth','🔵','Connect the speaker with Bluetooth.','Баландгӯякро тавассути Bluetooth пайваст кунед.','noun'),
    ]},
  ],
  grammar: [
    {
      title: 'Future Forms', titleTranslated: 'Шаклҳои замони оянда',
      lessonTitle: 'Lesson 5: Future Forms', lessonTitleTg: 'Дарси 5: Шаклҳои оянда', emoji: '🔮',
      explanation: 'Дар англисӣ оянда бо чанд шакл ифода мешавад:\n\n1. **will + феъл** — қарори лаҳзаӣ, пешгӯӣ, ваъда: *I **will** call you later.*\n2. **be going to + феъл** — нақша ё нияти қаблӣ, ё пешбинӣ аз далел: *I **am going to** study tonight.*\n3. **Present Continuous** — вохӯрии муайяншуда (созишнома): *I **am meeting** him at five.*\n\n**will** = қарори ҳозира ё пешгӯӣ; **going to** = нақшаи қаблӣ.',
      rules: [
        { pattern: 'will + V', note: 'Қарори лаҳзаӣ, ваъда, пешгӯӣ.' },
        { pattern: 'be going to + V', note: 'Нақшаи қаблӣ ё далели аён.' },
        { pattern: 'Present Continuous (future)', note: 'Вохӯрии муайяншуда: “I am meeting…”.' },
      ],
      examples: [
        { sentence: 'Look at those clouds! It is going to rain.', translation: 'Ба он абрҳо нигаред! Борон меборад.', highlight: 'is going to rain' },
        { sentence: 'I think our team will win.', translation: 'Ба фикрам, дастаи мо ғолиб мешавад.', highlight: 'will win' },
        { sentence: 'We are flying to Dubai on Monday.', translation: 'Мо рӯзи душанбе ба Дубай парвоз мекунем.', highlight: 'are flying' },
      ],
      exercises: [
        { type:'choose', prompt:'The phone is ringing. I ___ answer it.', promptTranslated:'Телефон занг зада истодааст. Ман ҷавоб медиҳам.', options:['will','am going to','am answering','answer'], answer:'will', explanation:'Қарори лаҳзаӣ → will.' },
        { type:'choose', prompt:'Look out! You ___ drop that glass!', promptTranslated:'Эҳтиёт шав! Ту он стаканро меафтонӣ!', options:['are going to','will','are dropping','drop'], answer:'are going to', explanation:'Пешбинӣ аз далели аён → going to.' },
        { type:'choose', prompt:'I ___ my friends at the cinema tonight.', promptTranslated:'Ман имшаб бо дӯстонам дар кинотеатр вомехӯрам.', options:['am meeting','will meet','meet','meeted'], answer:'am meeting', explanation:'Вохӯрии муайяншуда → Present Continuous.' },
        { type:'fill_blank', prompt:'She is going ___ start a new job next week. (to)', promptTranslated:'Вай ҳафтаи оянда кори нав сар мекунад.', answer:'to', explanation:'be going + to + V.' },
        { type:'transform', prompt:'I / think / it / be / a great film', promptTranslated:'Бо “will” пешгӯӣ созед.', answer:'I think it will be a great film.', explanation:'Пешгӯӣ бо will.' },
        { type:'transform', prompt:'We / going to / paint / the house / this summer', promptTranslated:'Бо “be going to” созед.', answer:'We are going to paint the house this summer.', explanation:'Нақшаи қаблӣ → are going to.' },
      ],
    },
    {
      title: 'Modals of Deduction', titleTranslated: 'Феълҳои модалии тахмин',
      lessonTitle: 'Lesson 6: Modals of Deduction', lessonTitleTg: 'Дарси 6: Тахмин (must/might/can\'t)', emoji: '🧩',
      explanation: 'Барои тахмин дар бораи ҳозира феълҳои модалӣ истифода мешаванд:\n\n- **must** — боварии қавӣ (мусбат): *She **must** be tired.* — Вай бояд хаста бошад.\n- **might / could / may** — эҳтимол: *He **might** be at home.* — Шояд ӯ дар хона бошад.\n- **can\'t** — боварии қавӣ (манфӣ): *That **can\'t** be true.* — Ин наметавонад рост бошад.\n\nПас аз ин феълҳо **be** ё феъли асосӣ бе “to” меояд.',
      rules: [
        { pattern: 'must + be/V', note: 'Боварии қавӣ (100% мусбат).' },
        { pattern: 'might / could / may + be/V', note: 'Эҳтимол (тахмин).' },
        { pattern: "can't + be/V", note: 'Боварии қавӣ, ки чизе номумкин аст.' },
      ],
      examples: [
        { sentence: 'The lights are off. They must be asleep.', translation: 'Чароғҳо хомӯшанд. Онҳо бояд хоб бошанд.', highlight: 'must be' },
        { sentence: 'He might be stuck in traffic.', translation: 'Шояд ӯ дар роҳбандӣ монда бошад.', highlight: 'might be' },
        { sentence: 'She can\'t be forty; she looks so young!', translation: 'Вай наметавонад чилсола бошад; хеле ҷавон менамояд!', highlight: "can't be" },
      ],
      exercises: [
        { type:'choose', prompt:'The phone is off. He ___ be busy.', promptTranslated:'Телефон хомӯш аст. Ӯ бояд машғул бошад.', options:['must','can\'t','isn\'t','won\'t'], answer:'must', explanation:'Боварии қавӣ → must.' },
        { type:'choose', prompt:'I\'m not sure where she is. She ___ be at work.', promptTranslated:'Намедонам вай куҷост. Шояд дар кор бошад.', options:['might','must','can\'t','will'], answer:'might', explanation:'Эҳтимол → might.' },
        { type:'choose', prompt:'That ___ be John. John is much taller.', promptTranslated:'Ин наметавонад Ҷон бошад. Ҷон хеле баландтар аст.', options:['can\'t','must','might','should'], answer:'can\'t', explanation:'Номумкин → can\'t.' },
        { type:'fill_blank', prompt:'The ground is wet. It ___ have rained. (must)', promptTranslated:'Замин тар аст. Бояд борон борида бошад.', answer:'must', explanation:'Тахмини қавӣ → must.' },
        { type:'transform', prompt:'Maybe / she / be / at the library', promptTranslated:'Бо “might” созед.', answer:'She might be at the library.', explanation:'Эҳтимол → might be.' },
        { type:'transform', prompt:'It is impossible that / he / be / the thief', promptTranslated:'Бо “can\'t” созед.', answer:'He can\'t be the thief.', explanation:'Номумкин → can\'t be.' },
      ],
    },
  ],
  listening: {
    lessonTitle: 'Lesson 7: Listening — A New Phone', lessonTitleTg: 'Дарси 7: Шунавоӣ — Телефони нав',
    title: 'A New Phone', titleTranslated: 'Телефони нав', emoji: '🎧',
    passage: 'Dilnoza had been saving money for months to buy a new smartphone. Last weekend she finally went to the shop. The assistant showed her several models and explained the features of each one. One phone had a bigger touchscreen and much more storage, but it was very expensive. Dilnoza asked whether she could pay in instalments. The assistant said she could, so she decided to buy it. Before leaving the shop, she asked him to help her move her photos and contacts from the old phone. He connected both devices and made a backup, so nothing was lost. That evening, Dilnoza set up her new Wi-Fi connection and downloaded all her favourite apps. She was very happy with her purchase.',
    passageTranslated: 'Дилноза чанд моҳ боз барои харидани смартфони нав пул ҷамъ мекард. Ҳафтаи гузашта ниҳоят ба мағоза рафт. Фурӯшанда ба ӯ якчанд намуна нишон дод ва хусусиятҳои ҳар якро фаҳмонд. Як телефон экрани ламсии калонтар ва ҳофизаи хеле зиёдтар дошт, вале хеле гарон буд. Дилноза пурсид, ки оё метавонад қисм-қисм пардохт кунад. Фурӯшанда гуфт, ки метавонад, бинобар ин ӯ харидани онро қарор дод. Пеш аз баромадан аз мағоза, ӯ хоҳиш кард, ки суратҳо ва контактҳояшро аз телефони кӯҳна кӯчонад. Фурӯшанда ҳар ду дастгоҳро пайваст кард ва нусхаи эҳтиётӣ сохт, то чизе гум нашавад. Он бегоҳ Дилноза пайвасти нави Wi-Fi-ро танзим кард ва ҳамаи барномаҳои дӯстдоштаашро зеркашӣ кард. Ӯ аз хариди худ хеле хушнуд буд.',
    questions: [
      { question: 'How long had Dilnoza been saving money?', questionTranslated: 'Дилноза чанд вақт пул ҷамъ мекард?', options: ['For months','For years','For one day','For a week'], correctIndex: 0, explanation: '“saving money for months”.' },
      { question: 'Why was one phone expensive?', questionTranslated: 'Чаро як телефон гарон буд?', options: ['Bigger screen and more storage','It was very old','It had no battery','It was broken'], correctIndex: 0, explanation: 'bigger touchscreen and more storage.' },
      { question: 'How did she decide to pay?', questionTranslated: 'Вай чӣ гуна пардохтро қарор кард?', options: ['In instalments','All at once','With a gift card','She did not pay'], correctIndex: 0, explanation: '“pay in instalments”.' },
      { question: 'What did the assistant make so nothing was lost?', questionTranslated: 'Фурӯшанда чӣ сохт, то чизе гум нашавад?', options: ['A backup','A phone call','A website','A password'], correctIndex: 0, explanation: '“made a backup”.' },
      { question: 'What did she do that evening?', questionTranslated: 'Он бегоҳ вай чӣ кард?', options: ['Downloaded her favourite apps','Sold the old phone','Returned the phone','Went to work'], correctIndex: 0, explanation: '“downloaded all her favourite apps”.' },
    ],
  },
  dialogue: {
    lessonTitle: 'Lesson 8: Speaking — Tech Support', lessonTitleTg: 'Дарси 8: Гуфтугӯ — Дастгирии техникӣ',
    title: 'Tech Support', titleTranslated: 'Дастгирии техникӣ', scenario: 'A customer calls tech support because the internet is not working.', emoji: '🛠️',
    lines: [
      { speaker: 'Agent', text: 'Hello, tech support. How can I help you?', translation: 'Салом, дастгирии техникӣ. Чӣ гуна кӯмак карда метавонам?', isUser: false },
      { speaker: 'Customer', text: 'My internet connection keeps dropping.', translation: 'Пайвасти интернетам пай дар пай қатъ мешавад.', isUser: true },
      { speaker: 'Agent', text: 'Have you restarted your router?', translation: 'Роутератонро аз нав фаъол кардед?', isUser: false },
      { speaker: 'Customer', text: 'Yes, but the signal is still weak.', translation: 'Ҳа, вале сигнал ҳанӯз заиф аст.', isUser: true },
      { speaker: 'Agent', text: 'It might be a problem with your Wi-Fi settings.', translation: 'Шояд мушкилӣ дар танзимоти Wi-Fi бошад.', isUser: false },
      { speaker: 'Customer', text: 'Can you help me check them?', translation: 'Метавонед ба ман кӯмак кунед, ки онҳоро тафтиш кунам?', isUser: true },
      { speaker: 'Agent', text: 'Of course. Open your settings and tell me what you see.', translation: 'Албатта. Танзимотро кушоед ва бигӯед, ки чӣ мебинед.', isUser: false },
      { speaker: 'Customer', text: 'It says the network is connected now.', translation: 'Навишта шудааст, ки шабака ҳоло пайваст аст.', isUser: true },
      { speaker: 'Agent', text: 'Great. It should work fine now.', translation: 'Аъло. Ҳоло бояд хуб кор кунад.', isUser: false },
    ],
  },
  reading: {
    lessonTitle: 'Lesson 9: Reading — Life Online', lessonTitleTg: 'Дарси 9: Хониш — Ҳаёт дар интернет',
    title: 'Life Online', titleTranslated: 'Ҳаёт дар интернет', emoji: '📖',
    passage: 'Twenty years ago, few people could imagine how much technology would change daily life. Today, most of us carry a smartphone that is more powerful than the computers of the past. We use apps to chat with friends, pay for shopping, and find our way around new cities. Social media lets us share our lives instantly, and a single video can go viral and be seen by millions. However, this connected life also brings problems. Many people spend too much time online and worry about their privacy. Experts say that artificial intelligence will soon change the way we work even more. The challenge for the future will be to enjoy the benefits of technology while protecting our health and our personal information.',
    passageTranslated: 'Бист сол пеш кам одамон тасаввур карда метавонистанд, ки технология ҳаёти ҳаррӯзаро чӣ қадар тағйир медиҳад. Имрӯз аксари мо смартфоне дорем, ки аз компютерҳои гузашта пурқувваттар аст. Мо барномаҳоро барои сӯҳбат бо дӯстон, пардохти харид ва ёфтани роҳ дар шаҳрҳои нав истифода мебарем. Шабакаҳои иҷтимоӣ ба мо имкон медиҳанд, ки ҳаётамонро фавран мубодила кунем ва як видео метавонад вирусӣ шуда, аз ҷониби миллионҳо нафар дида шавад. Аммо ин ҳаёти пайваст мушкилот низ меорад. Бисёр одамон вақти аз ҳад зиёдро дар интернет мегузаронанд ва аз махфияти худ нигаронанд. Коршиносон мегӯянд, ки зеҳни сунъӣ ба зудӣ тарзи кори моро боз ҳам бештар тағйир медиҳад. Мушкилии оянда дар он хоҳад буд, ки аз манфиатҳои технология лаззат барем, дар айни замон саломатӣ ва маълумоти шахсии худро ҳифз кунем.',
    questions: [
      { question: 'What do we carry today that is very powerful?', questionTranslated: 'Имрӯз мо чӣ дорем, ки хеле пурқувват аст?', options: ['A smartphone','A typewriter','A radio','A camera'], correctIndex: 0, explanation: 'a smartphone more powerful than old computers.' },
      { question: 'What can a single video do?', questionTranslated: 'Як видео чӣ карда метавонад?', options: ['Go viral','Cook food','Repair a phone','Print money'], correctIndex: 0, explanation: '“go viral and be seen by millions”.' },
      { question: 'What problem does connected life bring?', questionTranslated: 'Ҳаёти пайваст кадом мушкилиро меорад?', options: ['Worries about privacy','Free electricity','Better sleep','More free time'], correctIndex: 0, explanation: '“worry about their privacy”.' },
      { question: 'What will change the way we work even more?', questionTranslated: 'Чӣ тарзи кори моро боз ҳам бештар тағйир медиҳад?', options: ['Artificial intelligence','The weather','Old computers','Paper letters'], correctIndex: 0, explanation: '“artificial intelligence will soon change…”.' },
      { question: 'What is the challenge for the future?', questionTranslated: 'Мушкилии оянда чист?', options: ['Enjoying tech while protecting health and information','Buying more phones','Deleting the internet','Working less'], correctIndex: 0, explanation: 'last sentence.' },
    ],
  },
  review: {
    passage: 'Technology connects us to the whole world. We can send an attachment, join a livestream, or ask an app for directions. But we should also protect our devices with strong passwords and think carefully before we post online.',
    passageTranslated: 'Технология моро ба тамоми ҷаҳон пайваст мекунад. Мо метавонем замима фиристем, ба пахши мустақим ҳамроҳ шавем ё аз барнома роҳро пурсем. Вале мо бояд дастгоҳҳоямонро бо рамзҳои қавӣ ҳифз кунем ва пеш аз он ки дар интернет чизе нашр кунем, бодиққат фикр кунем.',
    questions: [
      { question: 'Which word means “ҳофиза / нигоҳдорӣ”?', questionTranslated: 'Кадом калима маънои “ҳофиза”-ро дорад?', options: ['Storage','Trend','Signal','Profile'], correctIndex: 0, explanation: 'storage = ҳофиза.' },
      { question: 'Choose the correct future form: “Look at the clock! We ___ be late.”', questionTranslated: 'Шакли дурусти ояндаро интихоб кунед.', options: ['are going to','will','were','are'], correctIndex: 0, explanation: 'Далели аён → going to.' },
      { question: 'What is a “hacker”?', questionTranslated: '“Hacker” кист?', options: ['Someone who breaks into computer systems','A type of phone','A social media app','A kind of battery'], correctIndex: 0, explanation: 'hacker = ҳакер.' },
      { question: 'Complete: “She ___ be tired; she worked all night.”', questionTranslated: 'Пур кунед: Вай бояд хаста бошад; тамоми шаб кор кард.', options: ['must','can\'t','won\'t','isn\'t'], correctIndex: 0, explanation: 'Тахмини қавӣ → must.' },
      { question: 'Which keeps your messages private?', questionTranslated: 'Кадомаш паёмҳоятонро махфӣ нигоҳ медорад?', options: ['Encryption','Spam','A trend','A gadget'], correctIndex: 0, explanation: 'encryption = рамзгузорӣ.' },
    ],
  },
  exam: {
    passage: 'This exam reviews Module 6: technology and communication vocabulary, future forms (will, going to, present continuous), and modals of deduction (must, might, can\'t). Choose the best answer for each question.',
    passageTranslated: 'Ин имтиҳон Модули 6-ро такрор мекунад: луғати технология ва алоқа, шаклҳои оянда ва феълҳои модалии тахмин. Барои ҳар савол беҳтарин ҷавобро интихоб кунед.',
    questions: [
      { question: 'A: The doorbell is ringing. B: I ___ get it.', questionTranslated: 'Занги дар. Ман мекушоям.', options: ['\'ll','am going to','am getting','get'], correctIndex: 0, explanation: 'Қарори лаҳзаӣ → will (\'ll).' },
      { question: 'They ___ be away; their car is gone and the lights are off.', questionTranslated: 'Онҳо бояд дар сафар бошанд; мошинашон нест ва чароғҳо хомӯш.', options: ['must','can\'t','might not','won\'t'], correctIndex: 0, explanation: 'Боварии қавӣ → must.' },
      { question: 'Which word means “обуначӣ”?', questionTranslated: 'Кадом калима маънои “обуначӣ”-ро дорад?', options: ['Subscriber','Firewall','Router','Backup'], correctIndex: 0, explanation: 'subscriber = обуначӣ.' },
      { question: 'I have already made plans. I ___ visit my aunt on Sunday.', questionTranslated: 'Ман аллакай нақша дорам. Рӯзи якшанбе ба аммаам меравам.', options: ['am going to','will','must','can\'t'], correctIndex: 0, explanation: 'Нақшаи қаблӣ → going to.' },
      { question: 'Choose the correct sentence.', questionTranslated: 'Ҷумлаи дурустро интихоб кунед.', options: ['That can\'t be right.','That can\'t to be right.','That not can be right.','That can\'t being right.'], correctIndex: 0, explanation: "can't + be (бе to).", },
    ],
  },
};
