import { W } from './b1-api-build.mjs';

export const M = {
  order: 8, title: 'Module 8: Relationships and Feelings', titleTranslated: 'Модули 8: Муносибат ва Ҳиссиёт',
  emoji: '❤️', color: '#EC4899',
  vocab: [
    { title: 'Lesson 1: Relationships', tt: 'Дарси 1: Муносибатҳо', emoji: '👥', words: [
      W('Relationship','/rɪˈleɪʃnʃɪp/','рилейшншип','Муносибат','💑','They have a strong relationship.','Онҳо муносибати мустаҳкам доранд.','noun'),
      W('Friendship','/ˈfrendʃɪp/','френдшип','Дӯстӣ','🤗','Their friendship lasted many years.','Дӯстии онҳо солҳои зиёд давом кард.','noun'),
      W('Acquaintance','/əˈkweɪntəns/','аквейнтенс','Шинос','🙋','He is just an acquaintance, not a close friend.','Ӯ танҳо як шинос аст, на дӯсти наздик.','noun'),
      W('Partner','/ˈpɑːtnə/','партнер','Ҳамсар / шарик','👫','She travels everywhere with her partner.','Вай ба ҳама ҷо бо ҳамсараш сафар мекунад.','noun'),
      W('Fiancé','/fiˈɒnseɪ/','фионсей','Домод (номзад)','💍','Her fiancé proposed last summer.','Домодаш тобистони гузашта хостгорӣ кард.','noun'),
      W('Marriage','/ˈmærɪdʒ/','мариҷ','Издивоҷ / никоҳ','💒','Their marriage is very happy.','Издивоҷи онҳо хеле хушбахт аст.','noun'),
      W('Divorce','/dɪˈvɔːs/','диворс','Талоқ','💔','After the divorce, they stayed friends.','Баъди талоқ онҳо дӯст монданд.','noun'),
      W('Engagement','/ɪnˈɡeɪdʒmənt/','ингейҷмент','Номзадӣ / фотиҳа','💍','They announced their engagement.','Онҳо номзадии худро эълон карданд.','noun'),
      W('Companion','/kəmˈpæniən/','кампаниан','Ҳамроҳ / ҳамсуҳбат','🚶','A dog can be a loyal companion.','Саг метавонад ҳамроҳи содиқ бошад.','noun'),
      W('Sibling','/ˈsɪblɪŋ/','сиблинг','Бародар ё хоҳар','👧','I have three siblings.','Ман се бародару хоҳар дорам.','noun'),
    ]},
    { title: 'Lesson 2: Getting Along', tt: 'Дарси 2: Хуб муомила кардан', emoji: '🤝', words: [
      W('Trust','/trʌst/','траст','Эътимод','🤞','Trust is the basis of any friendship.','Эътимод асоси ҳар дӯстист.','noun'),
      W('Loyalty','/ˈlɔɪəlti/','лойалти','Садоқат','🎗️','Loyalty matters more than money.','Садоқат аз пул муҳимтар аст.','noun'),
      W('Respect','/rɪˈspekt/','риспект','Эҳтиром','🙏','Show respect to your elders.','Ба калонсолон эҳтиром зоҳир кунед.','noun'),
      W('Admire','/ədˈmaɪə/','адмайр','Ситоиш кардан','😍','I admire her patience.','Ман сабри ӯро меситоям.','verb'),
      W('Encourage','/ɪnˈkʌrɪdʒ/','инкариҷ','Ҳавасманд кардан','📣','My teacher encouraged me to try again.','Муаллимам маро ҳавасманд кард, ки боз кӯшиш кунам.','verb'),
      W('Comfort','/ˈkʌmfət/','камфорт','Тасаллӣ додан','🫂','She comforted her crying friend.','Вай ба дӯсти гирякунандааш тасаллӣ дод.','verb'),
      W('Compromise','/ˈkɒmprəmaɪz/','компрамайз','Созиш','⚖️','A good relationship needs compromise.','Муносибати хуб созишро талаб мекунад.','noun'),
      W('Reconcile','/ˈrekənsaɪl/','реконсайл','Оштӣ кардан','🤝','They reconciled after their argument.','Онҳо баъди баҳс оштӣ карданд.','verb'),
      W('Forgive','/fəˈɡɪv/','фогив','Бахшидан','🕊️','It is not easy to forgive a betrayal.','Бахшидани хиёнат осон нест.','verb'),
      W('Bond','/bɒnd/','бонд','Робита / пайванд','🔗','There is a strong bond between the sisters.','Байни хоҳарон робитаи мустаҳкам ҳаст.','noun'),
    ]},
    { title: 'Lesson 3: Conflict and Emotions', tt: 'Дарси 3: Низоъ ва ҳиссиёт', emoji: '😔', words: [
      W('Argument','/ˈɑːɡjumənt/','аргюмент','Баҳс','🗯️','They had an argument about money.','Онҳо сари пул баҳс карданд.','noun'),
      W('Quarrel','/ˈkwɒrəl/','кворел','Ҷанҷол','😠','The brothers quarrel over small things.','Бародарон сари чизҳои хурд ҷанҷол мекунанд.','verb'),
      W('Betray','/bɪˈtreɪ/','битрей','Хиёнат кардан','🗡️','He would never betray a friend.','Ӯ ҳеҷ гоҳ ба дӯст хиёнат намекунад.','verb'),
      W('Envy','/ˈenvi/','энви','Ҳасад','😒','She felt envy at his success.','Вай ба муваффақияти ӯ ҳасад бурд.','noun'),
      W('Gossip','/ˈɡɒsɪp/','госип','Ғайбат','🗣️','Try not to listen to gossip.','Кӯшиш кунед, ки ба ғайбат гӯш накунед.','noun'),
      W('Ashamed','/əˈʃeɪmd/','ашеймд','Шарманда','😳','He was ashamed of his mistake.','Ӯ аз хатои худ шарманда буд.','adjective'),
      W('Frustrated','/frʌˈstreɪtɪd/','фрастрейтид','Дилтанг / асабонӣ','😤','I get frustrated when the internet is slow.','Вақте интернет суст аст, ман дилтанг мешавам.','adjective'),
      W('Miserable','/ˈmɪzrəbl/','мизрабл','Бадбахт / ғамгин','😢','The rainy weather made her miserable.','Ҳавои боронӣ ӯро ғамгин кард.','adjective'),
      W('Anxious','/ˈæŋkʃəs/','ангкшес','Мушавваш / нигарон','😟','I feel anxious before a big test.','Ман пеш аз имтиҳони калон мушавваш мешавам.','adjective'),
      W('Sympathy','/ˈsɪmpəθi/','симпати','Ҳамдардӣ','💐','She showed great sympathy for the family.','Вай ба оила ҳамдардии калон зоҳир кард.','noun'),
    ]},
    { title: 'Lesson 4: Personality', tt: 'Дарси 4: Хислат', emoji: '🧑', words: [
      W('Empathy','/ˈempəθi/','эмпати','Ҳамдилӣ','🫶','A good nurse needs empathy.','Ҳамшираи хуб ба ҳамдилӣ ниёз дорад.','noun'),
      W('Affection','/əˈfekʃn/','афекшн','Меҳру муҳаббат','🥰','She showed affection for the child.','Вай ба кӯдак меҳру муҳаббат зоҳир кард.','noun'),
      W('Sincere','/sɪnˈsɪə/','синсиер','Самимӣ','🙂','His apology was sincere.','Узрхоҳии ӯ самимӣ буд.','adjective'),
      W('Stubborn','/ˈstʌbən/','стаберн','Якрав / саркаш','🐏','He is too stubborn to admit he is wrong.','Ӯ он қадар якрав аст, ки хаташро эътироф намекунад.','adjective'),
      W('Outgoing','/ˌaʊtˈɡəʊɪŋ/','аутгоуинг','Ҷамъиятпазир / хушмуомила','🎉','She is friendly and outgoing.','Вай меҳрубон ва ҷамъиятпазир аст.','adjective'),
      W('Reserved','/rɪˈzɜːvd/','ризёрвд','Худдор / камгап','🤫','He is quiet and reserved with strangers.','Ӯ бо бегонагон ором ва камгап аст.','adjective'),
      W('Relative','/ˈrelətɪv/','релатив','Хеш / хешованд','👪','All my relatives came to the wedding.','Ҳамаи хешовандонам ба тӯй омаданд.','noun'),
      W('Ancestor','/ˈænsestə/','ансестор','Аҷдод / гузашта','🌳','Our ancestors lived in the mountains.','Аҷдодони мо дар кӯҳҳо зиндагӣ мекарданд.','noun'),
      W('Generation','/ˌdʒenəˈreɪʃn/','ҷенерейшн','Насл','👵','Three generations live in one house.','Се насл дар як хона зиндагӣ мекунанд.','noun'),
      W('Upbringing','/ˈʌpbrɪŋɪŋ/','апбрингинг','Тарбия','🏡','She had a strict upbringing.','Вай тарбияи сахтгирона дошт.','noun'),
    ]},
  ],
  grammar: [
    {
      title: 'Reported Questions and Commands', titleTranslated: 'Саволу фармони нақлшуда',
      lessonTitle: 'Lesson 5: Reported Questions & Commands', lessonTitleTg: 'Дарси 5: Саволу фармони нақлшуда', emoji: '💬',
      explanation: 'Ҳангоми нақл кардани саволу фармонҳо шакл тағйир меёбад:\n\n**Саволҳо:**\n- Савол бо феъли ёвар → **if / whether**: *“Are you tired?” → He asked **if** I **was** tired.*\n- Савол бо калимаи саволӣ → ҳамон калима: *“Where do you live?” → She asked **where** I **lived**.*\n- Тартиби калима мисли ҷумлаи хабарӣ мешавад (бе do/does/did).\n\n**Фармонҳо:**\n- **tell / ask + (не) + to + феъл**: *“Sit down.” → He told me **to sit** down.* / *“Don\'t worry.” → She told me **not to worry**.*',
      rules: [
        { pattern: 'ask if/whether + subject + verb', note: 'Барои саволи ҳа/не.' },
        { pattern: 'ask + question word + subject + verb', note: 'Бе do/does/did, тартиби хабарӣ.' },
        { pattern: 'tell/ask + object + (not) to + verb', note: 'Барои фармон ва хоҳиш.' },
      ],
      examples: [
        { sentence: 'She asked me where I had been.', translation: 'Вай пурсид, ки ман куҷо будам.', highlight: 'where I had been' },
        { sentence: 'He asked if I could help him.', translation: 'Ӯ пурсид, ки оё ман ба ӯ ёрӣ карда метавонам.', highlight: 'if I could' },
        { sentence: 'The teacher told us to be quiet.', translation: 'Муаллим ба мо гуфт, ки ором бошем.', highlight: 'told us to be' },
      ],
      exercises: [
        { type:'choose', prompt:'“Where do you work?” → She asked me where I ___.', promptTranslated:'Вай пурсид, ки ман куҷо кор мекунам.', options:['worked','do work','work','did work'], answer:'worked', explanation:'Тартиби хабарӣ, бе do → worked.' },
        { type:'choose', prompt:'“Are you ready?” → He asked ___ I was ready.', promptTranslated:'Ӯ пурсид, ки оё ман тайёрам.', options:['if','that','what','to'], answer:'if', explanation:'Савол бе калимаи саволӣ → if/whether.' },
        { type:'choose', prompt:'“Close the door.” → She told me ___ the door.', promptTranslated:'Вай ба ман гуфт, ки дарро пӯшам.', options:['to close','close','closing','closed'], answer:'to close', explanation:'Фармон → tell + to + V.' },
        { type:'fill_blank', prompt:'“Don\'t be late.” → He told me ___ to be late. (not)', promptTranslated:'Ӯ ба ман гуфт, ки дер накунам.', answer:'not', explanation:'Фармони манфӣ → not to + V.' },
        { type:'transform', prompt:'“What time is it?” → He asked me …', promptTranslated:'Ба саволи нақлшуда табдил диҳед.', answer:'He asked me what time it was.', explanation:'what time it was (тартиби хабарӣ).' },
        { type:'transform', prompt:'“Please wait here.” → She asked me …', promptTranslated:'Ба фармони нақлшуда табдил диҳед.', answer:'She asked me to wait there.', explanation:'ask + me + to + wait.' },
      ],
    },
    {
      title: 'Question Tags', titleTranslated: 'Пурсишҳои изофӣ (question tags)',
      lessonTitle: 'Lesson 6: Question Tags', lessonTitleTg: 'Дарси 6: Question tags', emoji: '❓',
      explanation: '**Question tags** пурсиши кӯтоҳе дар охири ҷумла мебошанд, ки барои тасдиқ истифода мешаванд:\n\n- Ҷумлаи **мусбат** → tag-и **манфӣ**: *You are tired, **aren\'t you**?*\n- Ҷумлаи **манфӣ** → tag-и **мусбат**: *He doesn\'t smoke, **does he**?*\n\nTag ҳамон феъли ёвари ҷумларо истифода мебарад. Барои Present Simple → do/does, барои Past Simple → did.',
      rules: [
        { pattern: 'Мусбат, + negative tag?', note: '“She is here, isn\'t she?”' },
        { pattern: 'Манфӣ, + positive tag?', note: '“They aren\'t ready, are they?”' },
        { pattern: 'Present/Past Simple → do/does/did', note: '“You like tea, don\'t you?”' },
      ],
      examples: [
        { sentence: 'You live near here, don\'t you?', translation: 'Ту дар наздикӣ зиндагӣ мекунӣ, ҳамин тавр не?', highlight: "don't you" },
        { sentence: 'She isn\'t coming, is she?', translation: 'Вай намеояд, ҳамин тавр не?', highlight: 'is she' },
        { sentence: 'They finished the work, didn\'t they?', translation: 'Онҳо корро тамом карданд, ҳамин тавр не?', highlight: "didn't they" },
      ],
      exercises: [
        { type:'choose', prompt:'You are a student, ___?', promptTranslated:'Ту донишҷӯ ҳастӣ, ҳамин тавр не?', options:['aren\'t you','are you','don\'t you','isn\'t it'], answer:'aren\'t you', explanation:'Мусбат → tag-и манфӣ (aren\'t you).' },
        { type:'choose', prompt:'He doesn\'t like coffee, ___?', promptTranslated:'Ӯ қаҳваро дӯст намедорад, ҳамин тавр не?', options:['does he','doesn\'t he','is he','do he'], answer:'does he', explanation:'Манфӣ → tag-и мусбат (does he).' },
        { type:'choose', prompt:'They went home, ___?', promptTranslated:'Онҳо ба хона рафтанд, ҳамин тавр не?', options:['didn\'t they','did they','don\'t they','weren\'t they'], answer:'didn\'t they', explanation:'Past Simple → didn\'t they.' },
        { type:'fill_blank', prompt:'She can swim, ___ she? (can\'t)', promptTranslated:'Вай шино карда метавонад, ҳамин тавр не?', answer:'can\'t', explanation:'Мусбат can → can\'t she.' },
        { type:'transform', prompt:'It is cold today (+ tag)', promptTranslated:'Question tag илова кунед.', answer:'It is cold today, isn\'t it?', explanation:"isn't it.", },
        { type:'transform', prompt:'You didn\'t call her (+ tag)', promptTranslated:'Question tag илова кунед.', answer:'You didn\'t call her, did you?', explanation:'did you.' },
      ],
    },
  ],
  listening: {
    lessonTitle: 'Lesson 7: Listening — An Old Friend', lessonTitleTg: 'Дарси 7: Шунавоӣ — Дӯсти кӯҳна',
    title: 'An Old Friend', titleTranslated: 'Дӯсти кӯҳна', emoji: '🎧',
    passage: 'Two years ago, Sabina had a serious argument with her best friend, Malika. They had been very close since childhood, but after the quarrel they stopped talking to each other. Sabina often felt miserable about it and wished she had apologised sooner. Last week, she saw Malika at a wedding. At first, both of them felt nervous, but then Malika came over and asked how she was. Sabina told her that she was sorry for the argument. Malika smiled and said she had missed their friendship too. They talked for hours, just like the old days. Sabina realised that a strong bond is worth saving, and that it is never too late to forgive someone you care about.',
    passageTranslated: 'Ду сол пеш Сабина бо дӯсти беҳтаринаш Малика баҳси ҷиддӣ кард. Онҳо аз кӯдакӣ хеле наздик буданд, вале баъди ҷанҷол бо ҳамдигар гап заданро бас карданд. Сабина аксар аз ин бобат ғамгин мешуд ва афсӯс мехӯрд, ки барвақттар узр напурсид. Ҳафтаи гузашта ӯ Маликаро дар як тӯй дид. Аввал ҳарду асабонӣ буданд, вале баъд Малика наздик омада пурсид, ки вай чӣ хел аст. Сабина ба ӯ гуфт, ки барои баҳс пушаймон аст. Малика табассум кард ва гуфт, ки ӯ низ дӯстии онҳоро пазмон шудааст. Онҳо соатҳо, мисли рӯзҳои гузашта, сӯҳбат карданд. Сабина фаҳмид, ки робитаи мустаҳкам арзиши нигоҳ доштанро дорад ва ҳеҷ гоҳ барои бахшидани касе, ки дӯсташ медорӣ, дер нест.',
    questions: [
      { question: 'Why did Sabina and Malika stop talking?', questionTranslated: 'Чаро Сабина ва Малика гап заданро бас карданд?', options: ['They had a serious argument','They moved away','They got new friends','They were too busy'], correctIndex: 0, explanation: '“a serious argument”.' },
      { question: 'What did Sabina wish?', questionTranslated: 'Сабина чиро орзу мекард?', options: ['That she had apologised sooner','That she had moved abroad','That she had more money','That she had a new friend'], correctIndex: 0, explanation: '“wished she had apologised sooner”.' },
      { question: 'Where did they meet again?', questionTranslated: 'Онҳо дубора куҷо вохӯрданд?', options: ['At a wedding','At school','At a shop','At work'], correctIndex: 0, explanation: '“saw Malika at a wedding”.' },
      { question: 'What did Malika say?', questionTranslated: 'Малика чӣ гуфт?', options: ['She had missed their friendship','She was still angry','She had a new best friend','She wanted to leave'], correctIndex: 0, explanation: '“she had missed their friendship too”.' },
      { question: 'What did Sabina realise?', questionTranslated: 'Сабина чиро дарк кард?', options: ['It is never too late to forgive','Friendship is not important','She should move away','Arguments never end'], correctIndex: 0, explanation: 'last sentence.' },
    ],
  },
  dialogue: {
    lessonTitle: 'Lesson 8: Speaking — Making Up', lessonTitleTg: 'Дарси 8: Гуфтугӯ — Оштӣ кардан',
    title: 'Making Up After an Argument', titleTranslated: 'Оштӣ баъди баҳс', scenario: 'Two friends apologise and make up after a disagreement.', emoji: '🕊️',
    lines: [
      { speaker: 'Nodira', text: 'Hi Zarina. Can we talk for a minute?', translation: 'Салом Зарина. Метавонем як дақиқа гап занем?', isUser: false },
      { speaker: 'Zarina', text: 'Of course. I have wanted to talk too.', translation: 'Албатта. Ман ҳам мехостам гап занам.', isUser: true },
      { speaker: 'Nodira', text: 'I am sorry about what I said. I was frustrated.', translation: 'Барои он чи гуфтам, узр мехоҳам. Ман дилтанг будам.', isUser: false },
      { speaker: 'Zarina', text: 'It\'s okay. I said some unfair things too.', translation: 'Мушкил нест. Ман ҳам чизҳои ноодилона гуфтам.', isUser: true },
      { speaker: 'Nodira', text: 'Our friendship means a lot to me.', translation: 'Дӯстии мо барои ман хеле муҳим аст.', isUser: false },
      { speaker: 'Zarina', text: 'To me too. Let\'s forget the argument.', translation: 'Барои ман ҳам. Биёед баҳсро фаромӯш кунем.', isUser: true },
      { speaker: 'Nodira', text: 'Agreed. Shall we get a coffee?', translation: 'Розӣ. Биёед қаҳва нӯшем?', isUser: false },
      { speaker: 'Zarina', text: 'That sounds perfect. My treat!', translation: 'Ин аъло аст. Аз ман!', isUser: true },
      { speaker: 'Nodira', text: 'Thank you. I\'m glad we talked.', translation: 'Раҳмат. Хушҳолам, ки гап задем.', isUser: false },
    ],
  },
  reading: {
    lessonTitle: 'Lesson 9: Reading — What Makes a Good Friend', lessonTitleTg: 'Дарси 9: Хониш — Дӯсти хуб кист',
    title: 'What Makes a Good Friend', titleTranslated: 'Дӯсти хуб кист', emoji: '📖',
    passage: 'True friendship is one of the most valuable things in life, but not everyone knows how to be a good friend. Psychologists say that trust and loyalty are the most important qualities. A good friend keeps your secrets, supports you in difficult times, and is happy for your success instead of feeling envy. Being a good listener is just as important as giving advice. Good friends do not always agree, but they know how to compromise and forgive after an argument. They also respect each other\'s differences. Many people have hundreds of contacts on social media, yet feel lonely because those relationships are not deep. In the end, it is better to have a few sincere friends than a large number of acquaintances.',
    passageTranslated: 'Дӯстии ҳақиқӣ яке аз арзишмандтарин чизҳои ҳаёт аст, вале на ҳама медонанд, ки чӣ гуна дӯсти хуб бошанд. Равоншиносон мегӯянд, ки эътимод ва садоқат муҳимтарин хислатҳо мебошанд. Дӯсти хуб сирри шуморо нигоҳ медорад, дар вақтҳои душвор дастгирӣ мекунад ва ба ҷои ҳасад ба муваффақияти шумо шод мешавад. Гӯши хуб будан ҳамон қадар муҳим аст, чун маслиҳат додан. Дӯстони хуб ҳамеша розӣ намешаванд, вале медонанд, ки чӣ гуна баъди баҳс созиш ва бахшиш кунанд. Онҳо инчунин фарқиятҳои якдигарро эҳтиром мекунанд. Бисёр одамон дар шабакаҳои иҷтимоӣ садҳо контакт доранд, аммо худро танҳо ҳис мекунанд, зеро он муносибатҳо амиқ нестанд. Дар ниҳоят, доштани чанд дӯсти самимӣ аз шумораи зиёди шиносон беҳтар аст.',
    questions: [
      { question: 'What are the most important qualities of a friend?', questionTranslated: 'Муҳимтарин хислатҳои дӯст кадомҳоянд?', options: ['Trust and loyalty','Money and fame','Height and looks','Speed and strength'], correctIndex: 0, explanation: '“trust and loyalty”.' },
      { question: 'How does a good friend react to your success?', questionTranslated: 'Дӯсти хуб ба муваффақияти шумо чӣ гуна муносибат мекунад?', options: ['Is happy for you','Feels envy','Ignores it','Gets angry'], correctIndex: 0, explanation: '“happy for your success instead of feeling envy”.' },
      { question: 'What is as important as giving advice?', questionTranslated: 'Чӣ ҳамон қадар муҳим аст, чун маслиҳат додан?', options: ['Being a good listener','Being rich','Being tall','Being famous'], correctIndex: 0, explanation: '“Being a good listener”.' },
      { question: 'Why do some people feel lonely on social media?', questionTranslated: 'Чаро баъзе одамон дар шабакаҳои иҷтимоӣ худро танҳо ҳис мекунанд?', options: ['Their relationships are not deep','They have no phone','They post too much','They have no internet'], correctIndex: 0, explanation: '“those relationships are not deep”.' },
      { question: 'What is better in the end?', questionTranslated: 'Дар ниҳоят чӣ беҳтар аст?', options: ['A few sincere friends','Many acquaintances','No friends at all','Only online friends'], correctIndex: 0, explanation: 'last sentence.' },
    ],
  },
  review: {
    passage: 'Relationships need effort. We should trust and respect each other, forgive after an argument, and be sincere. A person asked me once what the secret of friendship was. I told her to always be honest and loyal.',
    passageTranslated: 'Муносибатҳо кӯшишро талаб мекунанд. Мо бояд ба ҳамдигар эътимод ва эҳтиром кунем, баъди баҳс бибахшем ва самимӣ бошем. Замоне касе аз ман пурсид, ки сирри дӯстӣ чист. Ман ба ӯ гуфтам, ки ҳамеша ростқавл ва содиқ бошад.',
    questions: [
      { question: 'Which word means “садоқат”?', questionTranslated: 'Кадом калима маънои “садоқат”-ро дорад?', options: ['Loyalty','Envy','Argument','Divorce'], correctIndex: 0, explanation: 'loyalty = садоқат.' },
      { question: '“Where do you live?” → He asked me where I ___.', questionTranslated: 'Ӯ пурсид, ки ман куҷо зиндагӣ мекунам.', options: ['lived','live','do live','living'], correctIndex: 0, explanation: 'Reported question → lived.' },
      { question: 'Add the correct tag: “You are happy, ___?”', questionTranslated: 'Tag-и дурустро илова кунед.', options: ['aren\'t you','are you','don\'t you','is it'], correctIndex: 0, explanation: 'Мусбат → aren\'t you.' },
      { question: 'What does “forgive” mean?', questionTranslated: '“Forgive” чӣ маъно дорад?', options: ['To stop being angry with someone','To betray someone','To ignore someone','To envy someone'], correctIndex: 0, explanation: 'forgive = бахшидан.' },
      { question: '“Sit down.” → The teacher told us ___ down.', questionTranslated: 'Муаллим ба мо гуфт, ки нишинем.', options: ['to sit','sit','sitting','sat'], correctIndex: 0, explanation: 'told us to sit.' },
    ],
  },
  exam: {
    passage: 'This exam reviews Module 8: relationships and feelings vocabulary, reported questions and commands, and question tags. Choose the best answer for each question.',
    passageTranslated: 'Ин имтиҳон Модули 8-ро такрор мекунад: луғати муносибат ва ҳиссиёт, саволу фармони нақлшуда ва question tags. Барои ҳар савол беҳтарин ҷавобро интихоб кунед.',
    questions: [
      { question: '“Are you tired?” → She asked me ___ I was tired.', questionTranslated: 'Вай пурсид, ки оё ман хастаам.', options: ['if','that','what','to'], correctIndex: 0, explanation: 'Reported yes/no question → if.' },
      { question: 'He is your brother, ___?', questionTranslated: 'Ӯ бародари туст, ҳамин тавр не?', options: ['isn\'t he','is he','doesn\'t he','won\'t he'], correctIndex: 0, explanation: 'Мусбат → isn\'t he.' },
      { question: 'Which word means “ҳамдилӣ”?', questionTranslated: 'Кадом калима маънои “ҳамдилӣ”-ро дорад?', options: ['Empathy','Gossip','Quarrel','Bond'], correctIndex: 0, explanation: 'empathy = ҳамдилӣ.' },
      { question: '“Don\'t touch it.” → He told me ___ touch it.', questionTranslated: 'Ӯ ба ман гуфт, ки ба он даст назанам.', options: ['not to','to not','don\'t','to'], correctIndex: 0, explanation: 'told me not to touch.' },
      { question: 'Choose the correct sentence.', questionTranslated: 'Ҷумлаи дурустро интихоб кунед.', options: ['They live here, don\'t they?','They live here, do they?','They live here, aren\'t they?','They live here, isn\'t it?'], correctIndex: 0, explanation: 'Present Simple мусбат → don\'t they.' },
    ],
  },
};
