import { W } from './b1-api-build.mjs';

export const M = {
  order: 11, title: 'Module 11: Society and Culture', titleTranslated: 'Модули 11: Ҷомеа ва Фарҳанг',
  emoji: '🌍', color: '#8B5CF6',
  vocab: [
    { title: 'Lesson 1: Customs', tt: 'Дарси 1: Расму оин', emoji: '🎎', words: [
      W('Ritual','/ˈrɪtʃuəl/','ричуал','Маросим / расм','🕯️','Tea drinking is a daily ritual here.','Чойнӯшӣ дар ин ҷо расми ҳаррӯза аст.','noun'),
      W('Celebration','/ˌselɪˈbreɪʃn/','селебрейшн','Ҷашн','🎉','The whole town joined the celebration.','Тамоми шаҳр ба ҷашн ҳамроҳ шуд.','noun'),
      W('Superstition','/ˌsuːpəˈstɪʃn/','суперстишн','Хурофот','🔮','Breaking a mirror is a common superstition.','Шикастани оина хурофоти маъмул аст.','noun'),
      W('Legend','/ˈledʒənd/','леҷенд','Ривоят / афсона','🐉','Every region has its own legends.','Ҳар минтақа афсонаҳои худро дорад.','noun'),
      W('Folk','/fəʊk/','фоук','Мардумӣ / халқӣ','🪕','I love traditional folk music.','Ман мусиқии анъанавии халқиро дӯст медорам.','adjective'),
      W('Costume','/ˈkɒstjuːm/','костюм','Либоси миллӣ / костюм','👘','The dancers wore colourful costumes.','Рақсандагон либосҳои рангоранг пӯшида буданд.','noun'),
      W('Anthem','/ˈænθəm/','антем','Суруди миллӣ','🎵','Everyone stood for the national anthem.','Ҳама барои суруди миллӣ хестанд.','noun'),
      W('Etiquette','/ˈetɪket/','этикет','Одоб / қоидаҳои рафтор','🤝','Table etiquette varies between cultures.','Одоби сари дастархон дар фарҳангҳо фарқ мекунад.','noun'),
      W('Manners','/ˈmænəz/','манерз','Одоб / хушрафторӣ','🙇','Children should learn good manners.','Кӯдакон бояд хушрафториро омӯзанд.','noun'),
      W('Pilgrimage','/ˈpɪlɡrɪmɪdʒ/','пилгримиҷ','Зиёрат / ҳаҷ','🕌','They went on a pilgrimage to Mecca.','Онҳо ба зиёрати Макка рафтанд.','noun'),
    ]},
    { title: 'Lesson 2: Society', tt: 'Дарси 2: Ҷомеа', emoji: '🏙️', words: [
      W('Household','/ˈhaʊshəʊld/','ҳаусҳоулд','Хона / аҳли хона','🏠','There are five people in our household.','Дар оилаи мо панҷ нафар ҳаст.','noun'),
      W('Neighbourhood','/ˈneɪbəhʊd/','нейборҳуд','Маҳалла','🏘️','This is a quiet neighbourhood.','Ин маҳаллаи ором аст.','noun'),
      W('Urban','/ˈɜːbən/','ёрбан','Шаҳрӣ','🌆','Urban life can be very fast.','Ҳаёти шаҳрӣ метавонад хеле тез бошад.','adjective'),
      W('Rural','/ˈrʊərəl/','рурал','Деҳотӣ','🌾','He grew up in a rural village.','Ӯ дар деҳаи деҳотӣ ба воя расид.','adjective'),
      W('Poverty','/ˈpɒvəti/','поверти','Камбизоатӣ / фақр','🪙','The charity fights against poverty.','Хайрия бар зидди камбизоатӣ мубориза мебарад.','noun'),
      W('Unemployment','/ˌʌnɪmˈplɔɪmənt/','анимплоймент','Бекорӣ','📉','Unemployment is high among young people.','Бекорӣ дар байни ҷавонон баланд аст.','noun'),
      W('Welfare','/ˈwelfeə/','велфеер','Некӯаҳволӣ / кӯмаки иҷтимоӣ','🤲','The state provides welfare for the poor.','Давлат ба камбағалон кӯмаки иҷтимоӣ медиҳад.','noun'),
      W('Refugee','/ˌrefjuˈdʒiː/','рефюҷи','Гуреза / паноҳанда','🧳','The refugees needed food and shelter.','Гурезаҳо ба хӯрок ва паноҳгоҳ ниёз доштанд.','noun'),
      W('Minority','/maɪˈnɒrəti/','майнорити','Ақаллият','👥','The law protects minority groups.','Қонун гурӯҳҳои ақаллиятро ҳифз мекунад.','noun'),
      W('Majority','/məˈdʒɒrəti/','маҷорити','Аксарият','👨‍👩‍👧‍👦','The majority voted for the new plan.','Аксарият ба нақшаи нав овоз доданд.','noun'),
    ]},
    { title: 'Lesson 3: Beliefs and Values', tt: 'Дарси 3: Эътиқод ва арзишҳо', emoji: '🕊️', words: [
      W('Religion','/rɪˈlɪdʒən/','рилиҷен','Дин','🛐','People of every religion live here in peace.','Одамони ҳар дин дар ин ҷо дар сулҳ зиндагӣ мекунанд.','noun'),
      W('Belief','/bɪˈliːf/','билиф','Эътиқод / бовар','💭','Respect other people\'s beliefs.','Эътиқоди дигаронро эҳтиром кунед.','noun'),
      W('Faith','/feɪθ/','фейс','Имон','🙏','She has great faith in her family.','Вай ба оилааш имони калон дорад.','noun'),
      W('Worship','/ˈwɜːʃɪp/','вёршип','Ибодат','⛪','People go to the mosque to worship.','Одамон барои ибодат ба масҷид мераванд.','verb'),
      W('Values','/ˈvæljuːz/','валюз','Арзишҳо / принсипҳо','⚖️','Honesty is one of our family values.','Ростқавлӣ яке аз арзишҳои оилаи мост.','noun'),
      W('Identity','/aɪˈdentəti/','айдентити','Ҳувият / шахсият','🪪','Language is part of our identity.','Забон қисми ҳувияти мост.','noun'),
      W('Diversity','/daɪˈvɜːsəti/','дайвёрсити','Гуногунрангӣ','🌈','The city is proud of its diversity.','Шаҳр ба гуногунрангии худ ифтихор мекунад.','noun'),
      W('Tolerance','/ˈtɒlərəns/','толеренс','Таҳаммул / бурдборӣ','🤝','Tolerance keeps a society peaceful.','Таҳаммул ҷомеаро осоишта нигоҳ медорад.','noun'),
      W('Prejudice','/ˈpredʒudɪs/','преҷудис','Таассуб / пешдоварӣ','🚫','We must fight prejudice with education.','Мо бояд бо таҳсил бо таассуб мубориза барем.','noun'),
      W('Discrimination','/dɪˌskrɪmɪˈneɪʃn/','дискриминейшн','Табъиз','⛔','Discrimination at work is illegal.','Табъиз дар ҷои кор ғайриқонунист.','noun'),
    ]},
    { title: 'Lesson 4: Rights and Politics', tt: 'Дарси 4: Ҳуқуқ ва сиёсат', emoji: '⚖️', words: [
      W('Rights','/raɪts/','райтс','Ҳуқуқҳо','✊','Everyone has the right to education.','Ҳар кас ба таҳсил ҳуқуқ дорад.','noun'),
      W('Equality','/ɪˈkwɒləti/','иквалити','Баробарӣ','⚖️','They are fighting for equality.','Онҳо барои баробарӣ мубориза мебаранд.','noun'),
      W('Democracy','/dɪˈmɒkrəsi/','димокраси','Демократия','🗳️','In a democracy, people choose their leaders.','Дар демократия мардум роҳбарони худро интихоб мекунанд.','noun'),
      W('Politician','/ˌpɒləˈtɪʃn/','политишн','Сиёсатмадор','🎙️','The politician gave a long speech.','Сиёсатмадор нутқи дароз кард.','noun'),
      W('Mayor','/meə/','меэр','Шаҳрдор','🏛️','The mayor opened the new park.','Шаҳрдор боғи навро кушод.','noun'),
      W('Landmark','/ˈlændmɑːk/','лендмарк','Ёдгорӣ / нишонаи шаҳр','🗽','The tower is a famous landmark.','Манора ёдгории машҳур аст.','noun'),
      W('Conflict','/ˈkɒnflɪkt/','конфликт','Низоъ / ихтилоф','⚔️','The two countries ended their conflict.','Ду кишвар ба низои худ хотима доданд.','noun'),
      W('Peace','/piːs/','пис','Сулҳ','🕊️','Everyone hopes for lasting peace.','Ҳама ба сулҳи пойдор умед доранд.','noun'),
      W('Donation','/dəʊˈneɪʃn/','донейшн','Хайрия / садақа','💝','They made a donation to the school.','Онҳо ба мактаб хайрия карданд.','noun'),
      W('Citizenship','/ˈsɪtɪzənʃɪp/','ситизеншип','Шаҳрвандӣ','🛂','She applied for citizenship last year.','Вай соли гузашта барои шаҳрвандӣ ариза дод.','noun'),
    ]},
  ],
  grammar: [
    {
      title: 'Non-defining Relative Clauses', titleTranslated: 'Ҷумлаҳои пайрави тавзеҳӣ',
      lessonTitle: 'Lesson 5: Non-defining Relative Clauses', lessonTitleTg: 'Дарси 5: Ҷумлаҳои пайрави тавзеҳӣ', emoji: '➕',
      explanation: '**Ҷумлаи пайрави тавзеҳӣ** маълумоти иловагӣ медиҳад, ки ҳатмӣ нест. Он бо **вергул** ҷудо мешавад:\n\n- Барои одамон → **who**, барои ашё → **which**, барои ҷой → **where**.\n- **that** дар ин навъ истифода НАМЕШАВАД.\n- Агар маълумотро гирем, ҷумла боз ҳам мазмуни пурра дорад: *My father, **who is 60**, still works.*\n\nМуқоиса: ҷумлаи муайянкунанда (defining) вергул надорад ва маълумоти зарурӣ медиҳад.',
      rules: [
        { pattern: '…, who/which/where …, …', note: 'Бо вергул, маълумоти иловагӣ.' },
        { pattern: 'that ✗', note: 'Дар навъи тавзеҳӣ “that” намеояд.' },
      ],
      examples: [
        { sentence: 'My uncle, who lives in Khujand, is a teacher.', translation: 'Тағоям, ки дар Хуҷанд зиндагӣ мекунад, муаллим аст.', highlight: 'who lives in Khujand' },
        { sentence: 'The museum, which opened in 2010, is very popular.', translation: 'Осорхона, ки соли 2010 кушода шуд, хеле маъмул аст.', highlight: 'which opened in 2010' },
        { sentence: 'Paris, where they met, is a beautiful city.', translation: 'Париж, ки дар он ҷо вохӯрданд, шаҳри зебост.', highlight: 'where they met' },
      ],
      exercises: [
        { type:'choose', prompt:'My sister, ___ is a doctor, lives abroad.', promptTranslated:'Хоҳарам, ки духтур аст, дар хориҷа зиндагӣ мекунад.', options:['who','which','that','where'], answer:'who', explanation:'Одам → who.' },
        { type:'choose', prompt:'This book, ___ I read last year, is excellent.', promptTranslated:'Ин китоб, ки соли гузашта хондам, аъло аст.', options:['which','who','where','what'], answer:'which', explanation:'Ашё → which.' },
        { type:'choose', prompt:'Our school, ___ has 500 students, is very old.', promptTranslated:'Мактаби мо, ки 500 донишҷӯ дорад, хеле кӯҳна аст.', options:['which','who','that','where'], answer:'which', explanation:'Ашё → which (na that).' },
        { type:'fill_blank', prompt:'Samarkand, ___ my grandparents live, is famous. (where)', promptTranslated:'Самарқанд, ки бобову бибиям дар он зиндагӣ мекунанд, машҳур аст.', answer:'where', explanation:'Ҷой → where.' },
        { type:'transform', prompt:'Mr Karimov / who / teach us English / is retiring', promptTranslated:'Ҷумлаи тавзеҳиро созед (вергул гузоред).', answer:'Mr Karimov, who teaches us English, is retiring.', explanation:'…, who teaches us English, ….' },
        { type:'transform', prompt:'The Eiffel Tower / which / be / in Paris / is very tall', promptTranslated:'Ҷумлаи тавзеҳиро созед.', answer:'The Eiffel Tower, which is in Paris, is very tall.', explanation:'…, which is in Paris, ….' },
      ],
    },
    {
      title: 'Modals in the Past', titleTranslated: 'Феълҳои модалӣ дар гузашта',
      lessonTitle: 'Lesson 6: Past Modals (should have, must have)', lessonTitleTg: 'Дарси 6: Феълҳои модалӣ дар гузашта', emoji: '⏪',
      explanation: 'Барои сухан дар бораи гузашта феълҳои модалӣ бо **have + феъли сеюм** истифода мешаванд:\n\n- **should have + V3** — интиқод/афсӯс: *You **should have called** me.* — Ту бояд ба ман занг мезадӣ.\n- **must have + V3** — тахмини қавии гузашта: *She **must have forgotten**.* — Вай бояд фаромӯш карда бошад.\n- **might/could have + V3** — эҳтимоли гузашта: *He **might have missed** the bus.*\n- **can\'t have + V3** — номумкинии гузашта: *They **can\'t have finished** so fast.*',
      rules: [
        { pattern: 'should have + V3', note: 'Интиқод ё афсӯс дар бораи гузашта.' },
        { pattern: 'must have + V3', note: 'Тахмини қавӣ дар бораи гузашта.' },
        { pattern: "might / can't have + V3", note: 'Эҳтимол ё номумкинии гузашта.' },
      ],
      examples: [
        { sentence: 'You should have studied for the test.', translation: 'Ту бояд барои санҷиш омода мешудӣ.', highlight: 'should have studied' },
        { sentence: 'The road is wet; it must have rained.', translation: 'Роҳ тар аст; бояд борон борида бошад.', highlight: 'must have rained' },
        { sentence: 'She can\'t have seen us; it was too dark.', translation: 'Вай наметавонист моро дида бошад; хеле торик буд.', highlight: "can't have seen" },
      ],
      exercises: [
        { type:'choose', prompt:'You look tired. You ___ have gone to bed earlier.', promptTranslated:'Ту хаста менамоӣ. Ту бояд барвақттар хоб мерафтӣ.', options:['should','must','can\'t','will'], answer:'should', explanation:'Интиқод/афсӯс → should have.' },
        { type:'choose', prompt:'The door is open. Someone ___ have forgotten to lock it.', promptTranslated:'Дар кушода аст. Касе бояд қулф карданро фаромӯш карда бошад.', options:['must','should','can\'t','would'], answer:'must', explanation:'Тахмини қавӣ → must have.' },
        { type:'choose', prompt:'He ___ have taken the money; he was not even here.', promptTranslated:'Ӯ наметавонист пулро гирифта бошад; ӯ ҳатто ин ҷо набуд.', options:['can\'t','must','should','might'], answer:'can\'t', explanation:'Номумкинии гузашта → can\'t have.' },
        { type:'fill_blank', prompt:'I\'m not sure, but she ___ have left already. (might)', promptTranslated:'Дақиқ намедонам, вале шояд вай аллакай рафта бошад.', answer:'might', explanation:'Эҳтимоли гузашта → might have.' },
        { type:'transform', prompt:'You / not tell / him the secret (афсӯс)', promptTranslated:'Бо “shouldn\'t have” созед.', answer:'You shouldn\'t have told him the secret.', explanation:'shouldn\'t have told.' },
        { type:'transform', prompt:'They / be / very tired (тахмини қавии гузашта)', promptTranslated:'Бо “must have been” созед.', answer:'They must have been very tired.', explanation:'must have been.' },
      ],
    },
  ],
  listening: {
    lessonTitle: 'Lesson 7: Listening — A Traditional Wedding', lessonTitleTg: 'Дарси 7: Шунавоӣ — Тӯи анъанавӣ',
    title: 'A Traditional Wedding', titleTranslated: 'Тӯи анъанавӣ', emoji: '🎧',
    passage: 'Last summer, Aziz attended a traditional wedding in his grandmother\'s village. The celebration, which lasted three days, was full of music, dancing, and delicious food. Guests wore colourful costumes, and the older women sang folk songs that had been passed down for generations. Aziz, who had grown up in the city, had never seen such customs before. His grandmother explained the meaning of each ritual to him. He realised that these traditions, which connect people to their ancestors, are an important part of their identity. He thought that he should have visited the village more often when he was younger. Now he plans to return every year, because he believes that such rich cultural heritage must be protected and passed on to the next generation.',
    passageTranslated: 'Тобистони гузашта Азиз дар тӯи анъанавӣ дар деҳаи бибиаш ширкат кард. Ҷашн, ки се рӯз давом кард, пур аз мусиқӣ, рақс ва хӯроки лазиз буд. Меҳмонон либосҳои рангоранг пӯшида буданд ва занони калонсол сурудҳои халқиеро мехонданд, ки наслҳо интиқол дода шуда буданд. Азиз, ки дар шаҳр ба воя расида буд, ҳеҷ гоҳ чунин расмҳоро надида буд. Бибиаш маънои ҳар маросимро ба ӯ фаҳмонд. Ӯ дарк кард, ки ин анъанаҳо, ки одамонро ба аҷдодонашон пайваст мекунанд, қисми муҳими ҳувияти онҳост. Ӯ фикр кард, ки вақте ҷавонтар буд, бояд ба деҳа бештар меомад. Ҳоло ӯ нақша дорад, ки ҳар сол баргардад, зеро боварӣ дорад, ки чунин мероси бойи фарҳангӣ бояд ҳифз ва ба насли оянда интиқол дода шавад.',
    questions: [
      { question: 'How long did the celebration last?', questionTranslated: 'Ҷашн чанд вақт давом кард?', options: ['Three days','One day','A week','A month'], correctIndex: 0, explanation: '“which lasted three days”.' },
      { question: 'What did the older women do?', questionTranslated: 'Занони калонсол чӣ карданд?', options: ['Sang folk songs','Cooked all day','Danced alone','Stayed at home'], correctIndex: 0, explanation: '“sang folk songs”.' },
      { question: 'Why had Aziz never seen such customs?', questionTranslated: 'Чаро Азиз ҳеҷ гоҳ чунин расмҳоро надида буд?', options: ['He had grown up in the city','He was too young','He was ill','He lived abroad'], correctIndex: 0, explanation: '“who had grown up in the city”.' },
      { question: 'What did Aziz think he should have done?', questionTranslated: 'Азиз фикр кард, ки чӣ бояд мекард?', options: ['Visited the village more often','Studied harder','Moved to the city','Stayed home'], correctIndex: 0, explanation: '“should have visited the village more often”.' },
      { question: 'What does Aziz believe about cultural heritage?', questionTranslated: 'Азиз дар бораи мероси фарҳангӣ чӣ бовар дорад?', options: ['It must be protected and passed on','It is not important','It should be forgotten','It belongs only to cities'], correctIndex: 0, explanation: 'last sentence.' },
    ],
  },
  dialogue: {
    lessonTitle: 'Lesson 8: Speaking — Talking About Festivals', lessonTitleTg: 'Дарси 8: Гуфтугӯ — Дар бораи ҷашнҳо',
    title: 'Talking About Festivals', titleTranslated: 'Сӯҳбат дар бораи ҷашнҳо', scenario: 'Two friends from different countries compare their festivals.', emoji: '🎊',
    lines: [
      { speaker: 'Anna', text: 'What is the most important festival in your country?', translation: 'Дар кишвари ту муҳимтарин ҷашн кадом аст?', isUser: false },
      { speaker: 'Jamshed', text: 'It\'s Navruz, which celebrates the new year in spring.', translation: 'Ин Наврӯз аст, ки соли навро дар баҳор ҷашн мегирад.', isUser: true },
      { speaker: 'Anna', text: 'That sounds lovely. How do people celebrate it?', translation: 'Ин зебо менамояд. Мардум онро чӣ гуна ҷашн мегиранд?', isUser: false },
      { speaker: 'Jamshed', text: 'We cook special food and visit our relatives.', translation: 'Мо хӯроки махсус мепазем ва хешовандонамонро зиёрат мекунем.', isUser: true },
      { speaker: 'Anna', text: 'We have a similar tradition at the new year too.', translation: 'Мо ҳам дар соли нав анъанаи монанд дорем.', isUser: false },
      { speaker: 'Jamshed', text: 'Really? What do you usually do?', translation: 'Дар ҳақиқат? Одатан чӣ мекунед?', isUser: true },
      { speaker: 'Anna', text: 'We give gifts and light candles for good luck.', translation: 'Мо тӯҳфа медиҳем ва барои барори кор шамъ мефурӯзем.', isUser: false },
      { speaker: 'Jamshed', text: 'It\'s interesting how cultures share such customs.', translation: 'Ҷолиб аст, ки чӣ гуна фарҳангҳо чунин расмҳоро мубодила мекунанд.', isUser: true },
      { speaker: 'Anna', text: 'Yes. I\'d love to see Navruz one day.', translation: 'Ҳа. Ман мехоҳам рӯзе Наврӯзро бинам.', isUser: false },
    ],
  },
  reading: {
    lessonTitle: 'Lesson 9: Reading — A Changing Society', lessonTitleTg: 'Дарси 9: Хониш — Ҷомеаи тағйирёбанда',
    title: 'A Changing Society', titleTranslated: 'Ҷомеаи тағйирёбанда', emoji: '📖',
    passage: 'Societies are always changing. A hundred years ago, most families were large and lived in rural areas, where they worked on the land. Today, many people move to cities to find work, and households have become much smaller. Education, which was once available only to the rich, is now open to almost everyone. Women, who had few rights in the past, now study and work in every profession. Technology has also changed the way people communicate and share ideas. However, some things stay the same: people still value their traditions, their family, and their sense of identity. Experts say that a healthy society is one that respects diversity and treats all its citizens with equality, no matter their religion, background, or beliefs.',
    passageTranslated: 'Ҷомеаҳо ҳамеша тағйир меёбанд. Сад сол пеш аксари оилаҳо калон буданд ва дар минтақаҳои деҳот зиндагӣ мекарданд, ки дар он ҷо дар замин кор мекарданд. Имрӯз бисёр одамон барои ёфтани кор ба шаҳрҳо мекӯчанд ва оилаҳо хеле хурдтар шудаанд. Таҳсил, ки замоне танҳо барои сарватмандон дастрас буд, ҳоло барои қариб ҳама кушода аст. Занон, ки дар гузашта ҳуқуқи кам доштанд, ҳоло дар ҳар касб таҳсил ва кор мекунанд. Технология низ тарзи муоширату мубодилаи ғояҳои мардумро тағйир додааст. Аммо баъзе чизҳо бетағйир мемонанд: одамон ҳанӯз анъанаҳо, оила ва ҳисси ҳувияти худро қадр мекунанд. Коршиносон мегӯянд, ки ҷомеаи солим он аст, ки гуногунрангиро эҳтиром мекунад ва бо ҳамаи шаҳрвандони худ, новобаста аз дин, замина ё эътиқодашон, баробар муомила мекунад.',
    questions: [
      { question: 'Where did most families live a hundred years ago?', questionTranslated: 'Сад сол пеш аксари оилаҳо куҷо зиндагӣ мекарданд?', options: ['In rural areas','In big cities','By the sea','Abroad'], correctIndex: 0, explanation: '“lived in rural areas”.' },
      { question: 'What has happened to households today?', questionTranslated: 'Имрӯз ба оилаҳо чӣ шудааст?', options: ['They have become smaller','They have become larger','They disappeared','They stayed the same'], correctIndex: 0, explanation: '“households have become much smaller”.' },
      { question: 'Who was education once available to?', questionTranslated: 'Таҳсил замоне ба кӣ дастрас буд?', options: ['Only the rich','Only children','Everyone','Only women'], correctIndex: 0, explanation: '“available only to the rich”.' },
      { question: 'What do people still value?', questionTranslated: 'Одамон ҳанӯз чиро қадр мекунанд?', options: ['Traditions, family, and identity','Only money','Only technology','Nothing'], correctIndex: 0, explanation: '“value their traditions, their family, and their sense of identity”.' },
      { question: 'What is a healthy society, according to experts?', questionTranslated: 'Ба гуфти коршиносон, ҷомеаи солим чист?', options: ['One that respects diversity and equality','One with only one religion','One without cities','One that never changes'], correctIndex: 0, explanation: 'last sentence.' },
    ],
  },
  review: {
    passage: 'Every culture has its own traditions, which give people a sense of identity. A good society respects diversity and treats everyone with equality. We should have learned long ago that tolerance and peace are better than conflict.',
    passageTranslated: 'Ҳар фарҳанг анъанаҳои худро дорад, ки ба одамон ҳисси ҳувият медиҳанд. Ҷомеаи хуб гуногунрангиро эҳтиром мекунад ва бо ҳама баробар муомила мекунад. Мо бояд кайҳо меомӯхтем, ки таҳаммулу сулҳ аз низоъ беҳтаранд.',
    questions: [
      { question: 'Which word means “таҳаммул”?', questionTranslated: 'Кадом калима маънои “таҳаммул”-ро дорад?', options: ['Tolerance','Prejudice','Conflict','Poverty'], correctIndex: 0, explanation: 'tolerance = таҳаммул.' },
      { question: 'Complete: “My father, ___ is a farmer, lives in a village.”', questionTranslated: 'Пур кунед: Падарам, ки деҳқон аст, дар деҳа зиндагӣ мекунад.', options: ['who','which','that','where'], correctIndex: 0, explanation: 'Одам, тавзеҳӣ → who.' },
      { question: 'Complete: “You ___ have told me earlier!”', questionTranslated: 'Пур кунед: Ту бояд ба ман барвақттар мегуфтӣ!', options: ['should','must','can\'t','will'], correctIndex: 0, explanation: 'Интиқод → should have.' },
      { question: 'What does “refugee” mean?', questionTranslated: '“Refugee” чӣ маъно дорад?', options: ['A person who flees to another country for safety','A rich person','A politician','A tourist'], correctIndex: 0, explanation: 'refugee = гуреза.' },
      { question: 'Choose the correct sentence.', questionTranslated: 'Ҷумлаи дурустро интихоб кунед.', options: ['London, which is in England, is huge.','London, that is in England, is huge.','London which is in England is huge.','London, who is in England, is huge.'], correctIndex: 0, explanation: 'Тавзеҳӣ: which + вергул, na that.' },
    ],
  },
  exam: {
    passage: 'This exam reviews Module 11: society and culture vocabulary, non-defining relative clauses, and modals in the past. Choose the best answer for each question.',
    passageTranslated: 'Ин имтиҳон Модули 11-ро такрор мекунад: луғати ҷомеа ва фарҳанг, ҷумлаҳои пайрави тавзеҳӣ ва феълҳои модалӣ дар гузашта. Барои ҳар савол беҳтарин ҷавобро интихоб кунед.',
    questions: [
      { question: 'The teacher, ___ helped me a lot, has retired.', questionTranslated: 'Муаллим, ки ба ман бисёр кӯмак кард, ба нафақа баромад.', options: ['who','which','that','where'], correctIndex: 0, explanation: 'Одам, тавзеҳӣ → who.' },
      { question: 'The ground is wet. It ___ have rained last night.', questionTranslated: 'Замин тар аст. Шаби гузашта бояд борон борида бошад.', options: ['must','should','can\'t','would'], correctIndex: 0, explanation: 'Тахмини қавии гузашта → must have.' },
      { question: 'Which word means “баробарӣ”?', questionTranslated: 'Кадом калима маънои “баробарӣ”-ро дорад?', options: ['Equality','Poverty','Legend','Anthem'], correctIndex: 0, explanation: 'equality = баробарӣ.' },
      { question: 'You failed the test. You ___ have studied more.', questionTranslated: 'Ту имтиҳонро супорида натавонистӣ. Ту бояд бештар меомӯхтӣ.', options: ['should','must','can\'t','will'], correctIndex: 0, explanation: 'Интиқод/афсӯс → should have.' },
      { question: 'Choose the correct sentence.', questionTranslated: 'Ҷумлаи дурустро интихоб кунед.', options: ['She can\'t have seen me; I was at home.','She can\'t saw me; I was at home.','She can\'t have saw me; I was at home.','She couldn\'t see me have; I was at home.'], correctIndex: 0, explanation: "can't have + seen (V3).", },
    ],
  },
};
