import { W } from './b1-api-build.mjs';

export const M = {
  order: 9, title: 'Module 9: Food and Cooking', titleTranslated: 'Модули 9: Хӯрок ва Ошпазӣ',
  emoji: '🍳', color: '#84CC16',
  vocab: [
    { title: 'Lesson 1: Cooking Methods', tt: 'Дарси 1: Усулҳои пухтупаз', emoji: '🍳', words: [
      W('Grill','/ɡrɪl/','грил','Дар оташ бирён кардан','🔥','We grilled the meat outside.','Мо гӯштро дар берун дар оташ бирён кардем.','verb'),
      W('Steam','/stiːm/','стиим','Дар буғ пухтан','♨️','Steamed vegetables are very healthy.','Сабзавоти дар буғ пухташуда хеле солиманд.','verb'),
      W('Simmer','/ˈsɪmə/','симер','Оҳиста ҷӯшондан','🍲','Let the soup simmer for an hour.','Бигзоред шӯрбо як соат оҳиста ҷӯшад.','verb'),
      W('Marinate','/ˈmærɪneɪt/','маринейт','Дар қаймоқоб хобондан','🥩','Marinate the chicken overnight.','Мурғро як шаб дар қаймоқоб хобонед.','verb'),
      W('Whisk','/wɪsk/','виск','Задан (тухм)','🥚','Whisk the eggs before frying.','Пеш аз бирён кардан тухмҳоро задед.','verb'),
      W('Blend','/blend/','бленд','Омехтан (то майда)','🥤','Blend the fruit to make a smoothie.','Меваро омехта смузи созед.','verb'),
      W('Knead','/niːd/','нид','Хамир кардан','🍞','Knead the dough for ten minutes.','Хамирро даҳ дақиқа кунед.','verb'),
      W('Grate','/ɡreɪt/','грейт','Ранда кардан','🧀','Grate some cheese on top.','Дар боло каме панир ранда кунед.','verb'),
      W('Mince','/mɪns/','минс','Реза кардан (гӯшт)','🔪','Mince the meat for the sauce.','Гӯштро барои қайла реза кунед.','verb'),
      W('Mix','/mɪks/','микс','Омехтан','🥣','Mix the flour and the sugar.','Орд ва шакарро омехта кунед.','verb'),
    ]},
    { title: 'Lesson 2: Ingredients', tt: 'Дарси 2: Компонентҳо', emoji: '🧂', words: [
      W('Ingredient','/ɪnˈɡriːdiənt/','ингридиент','Компонент / масолеҳ','🧺','This recipe has only five ingredients.','Ин дастур танҳо панҷ компонент дорад.','noun'),
      W('Flavour','/ˈfleɪvə/','флейвор','Таъм / маза','😋','I love the flavour of fresh basil.','Ман таъми райҳони тозаро дӯст медорам.','noun'),
      W('Gravy','/ˈɡreɪvi/','грейви','Қайлаи гӯштӣ','🍛','Pour some gravy over the potatoes.','Ба картошка каме қайла резед.','noun'),
      W('Seasoning','/ˈsiːzənɪŋ/','сизонинг','Хӯришавӣ / зира-намак','🧂','Add a little seasoning to the soup.','Ба шӯрбо каме хӯриш илова кунед.','noun'),
      W('Cuisine','/kwɪˈziːn/','квизиин','Ошхонаи миллӣ','🍜','Tajik cuisine is famous for its pilaf.','Ошхонаи тоҷикӣ бо оши палавaш машҳур аст.','noun'),
      W('Raw','/rɔː/','ро','Хом','🥩','Do not eat raw chicken.','Мурғи хомро нахӯред.','adjective'),
      W('Frozen','/ˈfrəʊzn/','фроузн','Яхкарда','🧊','I keep frozen peas in the freezer.','Ман нахуди яхкардаро дар яхдон нигоҳ медорам.','adjective'),
      W('Organic','/ɔːˈɡænɪk/','органик','Органикӣ / табиӣ','🌱','Organic vegetables have no chemicals.','Сабзавоти органикӣ кимиё надорад.','adjective'),
      W('Nutritious','/njuˈtrɪʃəs/','нютришес','Серғизо','🥗','Beans are cheap and nutritious.','Лӯбиё арзон ва серғизо аст.','adjective'),
      W('Bland','/blænd/','бленд','Бемаза','😐','The soup was bland without salt.','Шӯрбо бе намак бемаза буд.','adjective'),
    ]},
    { title: 'Lesson 3: Describing Food', tt: 'Дарси 3: Тавсифи хӯрок', emoji: '😋', words: [
      W('Crispy','/ˈkrɪspi/','криспи','Тарсаки / шақ-шақ','🍟','I like crispy fried potatoes.','Ман картошкаи бирёни тарсакиро дӯст медорам.','adjective'),
      W('Tender','/ˈtendə/','тендер','Нарм (гӯшт)','🍖','The meat was soft and tender.','Гӯшт мулоим ва нарм буд.','adjective'),
      W('Juicy','/ˈdʒuːsi/','ҷуси','Обдор / шираноки','🍑','This peach is very juicy.','Ин шафтолу хеле обдор аст.','adjective'),
      W('Greasy','/ˈɡriːsi/','гриси','Равғанин','🍔','Fast food is often too greasy.','Хӯроки зудтайёр аксар хеле равғанин аст.','adjective'),
      W('Stale','/steɪl/','стейл','Кӯҳна / хушкшуда','🥖','The bread is stale and hard.','Нон кӯҳна ва сахт аст.','adjective'),
      W('Rotten','/ˈrɒtn/','ротн','Пӯсида','🍎','Throw away the rotten apples.','Себҳои пӯсидаро партоед.','adjective'),
      W('Sweet','/swiːt/','свит','Ширин','🍬','This tea is too sweet for me.','Ин чой барои ман хеле ширин аст.','adjective'),
      W('Homemade','/ˌhəʊmˈmeɪd/','ҳоуммейд','Хонагӣ','🥧','Homemade bread smells wonderful.','Нони хонагӣ бӯи аҷоиб дорад.','adjective'),
      W('Leftovers','/ˈleftəʊvəz/','лефтоуверз','Боқимондаи хӯрок','🍱','We ate the leftovers for lunch.','Мо боқимондаи хӯрокро барои нисфирӯзӣ хӯрдем.','noun'),
      W('Appetiser','/ˈæpɪtaɪzə/','апитайзер','Газак / пешхӯрок','🥗','The salad was a light appetiser.','Салат газаки сабук буд.','noun'),
    ]},
    { title: 'Lesson 4: Eating Out', tt: 'Дарси 4: Хӯрок дар берун', emoji: '🍽️', words: [
      W('Menu','/ˈmenjuː/','меню','Меню / феҳристи хӯрок','📋','Can I see the menu, please?','Метавонам менюро бинам, лутфан?','noun'),
      W('Reservation','/ˌrezəˈveɪʃn/','резервейшн','Ҷойбандӣ / брон','📅','I made a reservation for two.','Ман барои ду нафар ҷой банд кардам.','noun'),
      W('Takeaway','/ˈteɪkəweɪ/','тейкавей','Хӯроки хонабар','🥡','Let\'s order a takeaway tonight.','Биёед имшаб хӯроки хонабар фармоем.','noun'),
      W('Vegetarian','/ˌvedʒəˈteəriən/','веҷитериан','Гиёҳхӯр','🥦','My sister is a vegetarian.','Хоҳарам гиёҳхӯр аст.','noun'),
      W('Vegan','/ˈviːɡən/','виган','Веган (пурра гиёҳхӯр)','🌱','Vegan food has no animal products.','Хӯроки веган маҳсулоти ҳайвонӣ надорад.','noun'),
      W('Cutlery','/ˈkʌtləri/','катлери','Асбоби хӯрокхӯрӣ','🍴','Please set the cutlery on the table.','Лутфан асбоби хӯрокхӯриро болои миз гузоред.','noun'),
      W('Crockery','/ˈkrɒkəri/','крокери','Зарфҳо','🍽️','The crockery is in the cupboard.','Зарфҳо дар ҷевон ҳастанд.','noun'),
      W('Blender','/ˈblendə/','блендер','Блендер','🌀','I made soup in the blender.','Ман дар блендер шӯрбо тайёр кардам.','noun'),
      W('Apron','/ˈeɪprən/','эйпрон','Пешдоман','🧑‍🍳','The chef wore a white apron.','Ошпаз пешдомани сафед пӯшида буд.','noun'),
      W('Beverage','/ˈbevərɪdʒ/','беверидж','Нӯшокӣ','🥤','They serve hot and cold beverages.','Онҳо нӯшокиҳои гарму хунук пешниҳод мекунанд.','noun'),
    ]},
  ],
  grammar: [
    {
      title: 'Gerunds and Infinitives', titleTranslated: 'Герундий ва масдар',
      lessonTitle: 'Lesson 5: Gerunds & Infinitives', lessonTitleTg: 'Дарси 5: Герундий ва масдар', emoji: '🔤',
      explanation: 'Баъзе феълҳо баъди худ **герундий (V-ing)** ва баъзеашон **масдар (to + V)** мегиранд:\n\n- **V-ing** баъд аз: *enjoy, avoid, finish, mind, suggest, keep*: *I **enjoy cooking**.*\n- **to + V** баъд аз: *want, decide, hope, promise, need, would like*: *I **want to eat**.*\n- Баъди пешоянд ҳамеша **V-ing**: *good **at cooking***.\n- *like / love / hate* ҳам V-ing ва ҳам to мегиранд: *I **like swimming** / **to swim**.*',
      rules: [
        { pattern: 'enjoy/avoid/finish/mind + V-ing', note: 'Ин феълҳо герундий мегиранд.' },
        { pattern: 'want/decide/hope/need + to + V', note: 'Ин феълҳо масдар мегиранд.' },
        { pattern: 'preposition + V-ing', note: 'Баъди пешоянд ҳамеша -ing.' },
      ],
      examples: [
        { sentence: 'She enjoys baking cakes at the weekend.', translation: 'Вай дар рӯзҳои истироҳат тортпазиро дӯст медорад.', highlight: 'enjoys baking' },
        { sentence: 'They decided to open a restaurant.', translation: 'Онҳо қарор доданд, ки тарабхона кушоянд.', highlight: 'decided to open' },
        { sentence: 'He is good at making bread.', translation: 'Ӯ дар нонпазӣ моҳир аст.', highlight: 'at making' },
      ],
      exercises: [
        { type:'choose', prompt:'I enjoy ___ new recipes.', promptTranslated:'Ман кӯшидани дастурҳои навро дӯст медорам.', options:['trying','to try','try','tried'], answer:'trying', explanation:'enjoy + V-ing.' },
        { type:'choose', prompt:'We decided ___ dinner at home.', promptTranslated:'Мо қарор додем, ки хӯроки шомро дар хона хӯрем.', options:['to have','having','have','had'], answer:'to have', explanation:'decide + to + V.' },
        { type:'choose', prompt:'She is interested in ___ Italian food.', promptTranslated:'Вай ба пухтани хӯроки итолиёӣ таваҷҷуҳ дорад.', options:['cooking','to cook','cook','cooks'], answer:'cooking', explanation:'preposition (in) + V-ing.' },
        { type:'fill_blank', prompt:'Would you like ___ dessert? (to have)', promptTranslated:'Шумо ширинӣ мехоҳед?', answer:'to have', explanation:'would like + to + V.' },
        { type:'transform', prompt:'He / avoid / eat / greasy food', promptTranslated:'Ҷумларо созед (avoid).', answer:'He avoids eating greasy food.', explanation:'avoid + eating.' },
        { type:'transform', prompt:'They / hope / open / a café', promptTranslated:'Ҷумларо созед (hope).', answer:'They hope to open a café.', explanation:'hope + to open.' },
      ],
    },
    {
      title: 'Causative (have/get something done)', titleTranslated: 'Сохтори каузативӣ (коре карда шудан)',
      lessonTitle: 'Lesson 6: Causative — have something done', lessonTitleTg: 'Дарси 6: have something done', emoji: '🛠️',
      explanation: 'Вақте касе кореро на худаш, балки бо ёрии дигарон мекунад, сохтори **каузативӣ** истифода мешавад:\n\n**have / get + объект + феъли сеюм (past participle)**\n\n- *I **had my hair cut** yesterday.* — Дирӯз мӯямро (дар сартарошхона) буридам.\n- *She **got her car repaired**.* — Вай мошинашро таъмир кунонд.\n\nМаъно: амалро шахси дигар барои ту иҷро мекунад.',
      rules: [
        { pattern: 'have + object + past participle', note: '“I had the kitchen painted.”' },
        { pattern: 'get + object + past participle', note: 'Ғайрирасмитар: “I got my phone fixed.”' },
      ],
      examples: [
        { sentence: 'We had our windows cleaned last week.', translation: 'Ҳафтаи гузашта мо тирезаҳоямонро тоза кунондем.', highlight: 'had our windows cleaned' },
        { sentence: 'He got his suit dry-cleaned for the wedding.', translation: 'Ӯ костюмашро барои тӯй хушкшӯӣ кунонд.', highlight: 'got his suit dry-cleaned' },
        { sentence: 'I need to have my tooth pulled out.', translation: 'Ба ман лозим аст, ки дандонамро кашонам.', highlight: 'have my tooth pulled out' },
      ],
      exercises: [
        { type:'choose', prompt:'I had my hair ___ yesterday.', promptTranslated:'Дирӯз мӯямро буридам (кунондам).', options:['cut','cutting','to cut','cuts'], answer:'cut', explanation:'have + object + past participle (cut).' },
        { type:'choose', prompt:'She got her car ___ at the garage.', promptTranslated:'Вай мошинашро дар устохона таъмир кунонд.', options:['repaired','repair','repairing','to repair'], answer:'repaired', explanation:'get + object + past participle.' },
        { type:'fill_blank', prompt:'We are having the kitchen ___ next month. (paint)', promptTranslated:'Моҳи оянда мо ошхонаро ранг кунонда истодаем.', answer:'painted', explanation:'have + it + painted.' },
        { type:'fill_blank', prompt:'He had his photo ___ for the passport. (take)', promptTranslated:'Ӯ барои шиноснома аксашро гирондан.', answer:'taken', explanation:'past participle of take = taken.' },
        { type:'transform', prompt:'They / have / the roof / fix', promptTranslated:'Сохтори каузативӣ созед.', answer:'They had the roof fixed.', explanation:'had the roof fixed.' },
        { type:'transform', prompt:'I / need / get / my eyes / test', promptTranslated:'Сохтори каузативӣ созед (get).', answer:'I need to get my eyes tested.', explanation:'get my eyes tested.' },
      ],
    },
  ],
  listening: {
    lessonTitle: 'Lesson 7: Listening — A Cooking Class', lessonTitleTg: 'Дарси 7: Шунавоӣ — Дарси ошпазӣ',
    title: 'A Cooking Class', titleTranslated: 'Дарси ошпазӣ', emoji: '🎧',
    passage: 'Farrukh had always wanted to learn how to cook, so last month he joined a cooking class in the city. On the first day, the teacher explained that good cooking starts with fresh ingredients and a little patience. She showed the students how to chop vegetables safely and how to add just the right amount of seasoning. Farrukh enjoyed learning to make soups and sauces, but he found baking bread the most difficult, because the dough needs to be kneaded for a long time. By the end of the course, he had learned to prepare several traditional dishes. Now he loves cooking for his family every weekend, and he says that homemade food always tastes better than a takeaway.',
    passageTranslated: 'Фаррух ҳамеша мехост омӯзад, ки чӣ гуна хӯрок пазад, бинобар ин моҳи гузашта ба як дарси ошпазӣ дар шаҳр ҳамроҳ шуд. Рӯзи аввал муаллима фаҳмонд, ки ошпазии хуб бо масолеҳи тоза ва каме сабр оғоз мешавад. Вай ба донишҷӯён нишон дод, ки чӣ гуна сабзавотро бехатар реза кунанд ва чӣ гуна маҳз миқдори дурусти хӯриш илова кунанд. Фаррух омӯхтани пухтани шӯрбову қайлаҳоро дӯст дошт, вале нонпазиро душвортарин ёфт, зеро хамирро муддати тӯлонӣ кардан лозим аст. То охири курс ӯ тайёр кардани якчанд хӯроки анъанавиро омӯхт. Ҳоло ӯ ҳар рӯзи истироҳат барои оилааш пухтанро дӯст медорад ва мегӯяд, ки хӯроки хонагӣ ҳамеша аз хӯроки хонабар лаззатноктар аст.',
    questions: [
      { question: 'What did Farrukh join last month?', questionTranslated: 'Фаррух моҳи гузашта ба чӣ ҳамроҳ шуд?', options: ['A cooking class','A gym','A language school','A football team'], correctIndex: 0, explanation: '“joined a cooking class”.' },
      { question: 'What does good cooking start with?', questionTranslated: 'Ошпазии хуб аз чӣ оғоз мешавад?', options: ['Fresh ingredients and patience','Expensive pans','A big kitchen','Lots of money'], correctIndex: 0, explanation: '“fresh ingredients and a little patience”.' },
      { question: 'What did he find the most difficult?', questionTranslated: 'Ӯ чиро душвортарин ёфт?', options: ['Baking bread','Making soup','Chopping vegetables','Washing dishes'], correctIndex: 0, explanation: '“found baking bread the most difficult”.' },
      { question: 'Why is baking bread difficult?', questionTranslated: 'Чаро нонпазӣ душвор аст?', options: ['The dough needs long kneading','There is no flour','The oven is small','Bread is expensive'], correctIndex: 0, explanation: '“dough needs to be kneaded for a long time”.' },
      { question: 'What does Farrukh say about homemade food?', questionTranslated: 'Фаррух дар бораи хӯроки хонагӣ чӣ мегӯяд?', options: ['It tastes better than a takeaway','It is too expensive','It takes no time','It is unhealthy'], correctIndex: 0, explanation: 'last sentence.' },
    ],
  },
  dialogue: {
    lessonTitle: 'Lesson 8: Speaking — Ordering at a Restaurant', lessonTitleTg: 'Дарси 8: Гуфтугӯ — Фармоиш дар тарабхона',
    title: 'Ordering at a Restaurant', titleTranslated: 'Фармоиш дар тарабхона', scenario: 'A customer orders a meal at a restaurant.', emoji: '🍽️',
    lines: [
      { speaker: 'Waiter', text: 'Good evening. Are you ready to order?', translation: 'Бегоҳ ба хайр. Барои фармоиш тайёред?', isUser: false },
      { speaker: 'Customer', text: 'Yes. Could I see the menu again, please?', translation: 'Ҳа. Метавонам менюро боз бинам, лутфан?', isUser: true },
      { speaker: 'Waiter', text: 'Of course. Our special today is grilled lamb.', translation: 'Албатта. Хӯроки махсуси имрӯзаи мо гӯшти барраи дар оташ бирёншуда аст.', isUser: false },
      { speaker: 'Customer', text: 'That sounds delicious. I\'ll have that, please.', translation: 'Ин лазиз менамояд. Ҳаминро мегирам, лутфан.', isUser: true },
      { speaker: 'Waiter', text: 'Would you like a starter or a drink?', translation: 'Пешхӯрок ё нӯшокӣ мехоҳед?', isUser: false },
      { speaker: 'Customer', text: 'A green salad and a glass of water, please.', translation: 'Салати сабз ва як стакан об, лутфан.', isUser: true },
      { speaker: 'Waiter', text: 'Is there anything you can\'t eat?', translation: 'Чизе ҳаст, ки хӯрда наметавонед?', isUser: false },
      { speaker: 'Customer', text: 'I\'m vegetarian, but I do eat fish.', translation: 'Ман гиёҳхӯрам, вале моҳӣ мехӯрам.', isUser: true },
      { speaker: 'Waiter', text: 'Understood. I\'ll bring your order shortly.', translation: 'Фаҳмидам. Фармоишатонро ба зудӣ меорам.', isUser: false },
    ],
  },
  reading: {
    lessonTitle: 'Lesson 9: Reading — Slow Food', lessonTitleTg: 'Дарси 9: Хониш — Хӯроки оҳиста',
    title: 'The Slow Food Movement', titleTranslated: 'Ҳаракати «Хӯроки оҳиста»', emoji: '📖',
    passage: 'In our busy world, many people rely on fast food and ready meals because they have no time to cook. However, a growing number of people are joining the "slow food" movement, which began in Italy. The idea is simple: instead of eating quickly and without thinking, we should take time to prepare fresh, local, and healthy meals. Supporters say that cooking at home is not only better for our health but also brings families together. When you make food yourself, you know exactly what is in it, and you can avoid too much salt, sugar, and grease. Cooking can also be a relaxing hobby. Of course, preparing a meal from fresh ingredients takes longer than heating a frozen dinner, but many people believe the taste and the health benefits are worth the extra effort.',
    passageTranslated: 'Дар ҷаҳони серташвиши мо бисёр одамон ба хӯроки зудтайёр ва хӯрокҳои тайёр такя мекунанд, зеро вақти пухтан надоранд. Аммо шумораи афзояндаи одамон ба ҳаракати «хӯроки оҳиста» ҳамроҳ мешаванд, ки дар Италия оғоз ёфт. Ғоя содда аст: ба ҷои зуд ва бефикр хӯрдан, мо бояд барои тайёр кардани хӯроки тоза, маҳаллӣ ва солим вақт ҷудо кунем. Ҷонибдорон мегӯянд, ки пухтани хӯрок дар хона на танҳо барои саломатии мо беҳтар аст, балки оиларо низ гирд меорад. Вақте ки шумо худ хӯрок мепазед, дақиқ медонед, ки дар он чӣ ҳаст ва метавонед аз намак, шакар ва равғани зиёд канорагирӣ кунед. Пухтан инчунин метавонад ҳаваси оромбахш бошад. Албатта, тайёр кардани хӯрок аз масолеҳи тоза нисбат ба гарм кардани хӯроки яхкарда бештар вақт мегирад, вале бисёр одамон боварӣ доранд, ки таъм ва фоидаҳои саломатӣ ба ин кӯшиши иловагӣ меарзанд.',
    questions: [
      { question: 'Why do many people rely on fast food?', questionTranslated: 'Чаро бисёр одамон ба хӯроки зудтайёр такя мекунанд?', options: ['They have no time to cook','It is healthier','It is cheaper only','They cannot buy vegetables'], correctIndex: 0, explanation: '“they have no time to cook”.' },
      { question: 'Where did the slow food movement begin?', questionTranslated: 'Ҳаракати «хӯроки оҳиста» дар куҷо оғоз ёфт?', options: ['In Italy','In France','In Tajikistan','In America'], correctIndex: 0, explanation: '“which began in Italy”.' },
      { question: 'What does cooking at home bring?', questionTranslated: 'Пухтан дар хона чӣ меорад?', options: ['Families together','More stress','Higher bills','Less flavour'], correctIndex: 0, explanation: '“brings families together”.' },
      { question: 'What can you avoid by cooking yourself?', questionTranslated: 'Бо худ пухтан аз чӣ канорагирӣ карда метавонед?', options: ['Too much salt, sugar and grease','All vegetables','Fresh food','Family meals'], correctIndex: 0, explanation: '“avoid too much salt, sugar, and grease”.' },
      { question: 'What is a disadvantage of slow food?', questionTranslated: 'Камбудии «хӯроки оҳиста» чист?', options: ['It takes longer to prepare','It tastes bad','It is unhealthy','It has no ingredients'], correctIndex: 0, explanation: '“takes longer than heating a frozen dinner”.' },
    ],
  },
  review: {
    passage: 'Cooking is a useful life skill. If you enjoy trying new recipes and you avoid eating too much greasy food, you can stay healthy. Some people prefer to have their meals delivered, but homemade food is usually fresher and cheaper.',
    passageTranslated: 'Ошпазӣ як маҳорати муфиди ҳаётист. Агар шумо кӯшидани дастурҳои навро дӯст доред ва аз хӯрдани хӯроки хеле равғанин худдорӣ кунед, метавонед солим монед. Баъзе одамон мехоҳанд хӯрокашонро расонанд, вале хӯроки хонагӣ одатан тозатар ва арзонтар аст.',
    questions: [
      { question: 'Which word means “серғизо”?', questionTranslated: 'Кадом калима маънои “серғизо”-ро дорад?', options: ['Nutritious','Stale','Bland','Raw'], correctIndex: 0, explanation: 'nutritious = серғизо.' },
      { question: 'Complete: “I enjoy ___ for my friends.”', questionTranslated: 'Пур кунед: Ман барои дӯстонам пухтанро дӯст медорам.', options: ['cooking','to cook','cook','cooked'], correctIndex: 0, explanation: 'enjoy + V-ing.' },
      { question: 'Complete: “She had her kitchen ___.”', questionTranslated: 'Пур кунед: Вай ошхонаашро ранг кунонд.', options: ['painted','paint','painting','to paint'], correctIndex: 0, explanation: 'have + object + past participle.' },
      { question: 'What does “tender” describe?', questionTranslated: '“Tender” чиро тавсиф мекунад?', options: ['Soft meat','Hard bread','Cold soup','Sour milk'], correctIndex: 0, explanation: 'tender = нарм (гӯшт).' },
      { question: 'Choose the correct sentence.', questionTranslated: 'Ҷумлаи дурустро интихоб кунед.', options: ['They decided to open a café.','They decided opening a café.','They decided open a café.','They decided to opening a café.'], correctIndex: 0, explanation: 'decide + to + V.' },
    ],
  },
  exam: {
    passage: 'This exam reviews Module 9: food and cooking vocabulary, gerunds and infinitives, and the causative structure (have/get something done). Choose the best answer for each question.',
    passageTranslated: 'Ин имтиҳон Модули 9-ро такрор мекунад: луғати хӯрок ва ошпазӣ, герундий ва масдар ва сохтори каузативӣ. Барои ҳар савол беҳтарин ҷавобро интихоб кунед.',
    questions: [
      { question: 'She avoids ___ fast food.', questionTranslated: 'Вай аз хӯрдани хӯроки зудтайёр худдорӣ мекунад.', options: ['eating','to eat','eat','ate'], correctIndex: 0, explanation: 'avoid + V-ing.' },
      { question: 'I want ___ a new recipe tonight.', questionTranslated: 'Ман имшаб кӯшидани дастури навро мехоҳам.', options: ['to try','trying','try','tried'], correctIndex: 0, explanation: 'want + to + V.' },
      { question: 'We had the house ___ before the party.', questionTranslated: 'Мо пеш аз базм хонаро тоза кунондем.', options: ['cleaned','clean','cleaning','to clean'], correctIndex: 0, explanation: 'have + object + past participle.' },
      { question: 'Which word means “масолеҳ”?', questionTranslated: 'Кадом калима маънои “масолеҳ”-ро дорад?', options: ['Ingredient','Beverage','Apron','Menu'], correctIndex: 0, explanation: 'ingredient = масолеҳ.' },
      { question: 'Choose the correct sentence.', questionTranslated: 'Ҷумлаи дурустро интихоб кунед.', options: ['I got my car repaired.','I got my car repair.','I got repaired my car.','I got my car to repair.'], correctIndex: 0, explanation: 'get + object + past participle.' },
    ],
  },
};
