import { W } from './b1-api-build.mjs';

export const M = {
  order: 10, title: 'Module 10: Science and the Future', titleTranslated: 'Модули 10: Илм ва Оянда',
  emoji: '🔬', color: '#06B6D4',
  vocab: [
    { title: 'Lesson 1: Scientific Method', tt: 'Дарси 1: Усули илмӣ', emoji: '🔬', words: [
      W('Science','/ˈsaɪəns/','сайенс','Илм','🧪','Science helps us understand the world.','Илм ба мо кӯмак мекунад, ки ҷаҳонро фаҳмем.','noun'),
      W('Experiment','/ɪkˈsperɪmənt/','иксперимент','Таҷриба / озмоиш','⚗️','They did an experiment in the lab.','Онҳо дар лаборатория озмоиш гузарониданд.','noun'),
      W('Research','/rɪˈsɜːtʃ/','рисёрч','Таҳқиқот','📚','Her research is about clean energy.','Таҳқиқоти вай дар бораи энергияи тоза аст.','noun'),
      W('Laboratory','/ləˈbɒrətri/','лабораторӣ','Лаборатория','🏫','The samples are kept in the laboratory.','Намунаҳо дар лаборатория нигоҳ дошта мешаванд.','noun'),
      W('Theory','/ˈθɪəri/','сиори','Назария','💭','Einstein developed the theory of relativity.','Эйнштейн назарияи нисбиятро таҳия кард.','noun'),
      W('Evidence','/ˈevɪdəns/','эвиденс','Далел / исбот','🔎','There is strong evidence for this idea.','Барои ин ғоя далели қавӣ ҳаст.','noun'),
      W('Hypothesis','/haɪˈpɒθəsɪs/','ҳайпотесис','Фарзия','❓','The scientists tested their hypothesis.','Олимон фарзияи худро санҷиданд.','noun'),
      W('Observe','/əbˈzɜːv/','абзёрв','Мушоҳида кардан','👁️','We observed the stars all night.','Мо тамоми шаб ситораҳоро мушоҳида кардем.','verb'),
      W('Measure','/ˈmeʒə/','межер','Чен кардан','📏','You must measure the temperature carefully.','Шумо бояд ҳароратро бодиққат чен кунед.','verb'),
      W('Conclusion','/kənˈkluːʒn/','конклужн','Хулоса','✅','The report ends with a clear conclusion.','Ҳисобот бо хулосаи равшан анҷом меёбад.','noun'),
    ]},
    { title: 'Lesson 2: Discoveries', tt: 'Дарси 2: Кашфиётҳо', emoji: '💡', words: [
      W('Discovery','/dɪˈskʌvəri/','дискавери','Кашфиёт','🌟','The discovery changed modern medicine.','Кашфиёт тибби муосирро тағйир дод.','noun'),
      W('Invention','/ɪnˈvenʃn/','инвеншн','Ихтироъ','⚙️','The wheel was a great invention.','Чарх ихтирооти бузург буд.','noun'),
      W('Breakthrough','/ˈbreɪkθruː/','брейксру','Пешрафти бузург','🚀','Scientists made a breakthrough in cancer research.','Олимон дар таҳқиқи саратон пешрафти бузург карданд.','noun'),
      W('Innovation','/ˌɪnəˈveɪʃn/','иновейшн','Навоварӣ','💡','This company is famous for innovation.','Ин ширкат бо навоварӣ машҳур аст.','noun'),
      W('Prove','/pruːv/','прув','Исбот кардан','☑️','The test proved that he was right.','Санҷиш исбот кард, ки ӯ ҳақ буд.','verb'),
      W('Predict','/prɪˈdɪkt/','придикт','Пешгӯӣ кардан','🔮','Scientists can predict earthquakes better now.','Олимон ҳоло заминҷунбиро беҳтар пешгӯӣ карда метавонанд.','verb'),
      W('Develop','/dɪˈveləp/','дивелоп','Таҳия / рушд кардан','📈','They developed a new vaccine quickly.','Онҳо ваксинаи навро зуд таҳия карданд.','verb'),
      W('Analysis','/əˈnæləsɪs/','анализис','Таҳлил','📊','The data needs careful analysis.','Маълумот таҳлили бодиққатро талаб мекунад.','noun'),
      W('Formula','/ˈfɔːmjələ/','формула','Формула','🧮','Water has the formula H2O.','Об формулаи H2O дорад.','noun'),
      W('Progress','/ˈprəʊɡres/','прогрес','Пешрафт','➡️','Medicine has made great progress.','Тиб пешрафти бузург кардааст.','noun'),
    ]},
    { title: 'Lesson 3: Physics and Chemistry', tt: 'Дарси 3: Физика ва химия', emoji: '⚛️', words: [
      W('Atom','/ˈætəm/','атом','Атом','⚛️','Everything is made of atoms.','Ҳама чиз аз атомҳо иборат аст.','noun'),
      W('Molecule','/ˈmɒlɪkjuːl/','моликюл','Молекула','🔵','A water molecule has three atoms.','Молекулаи об се атом дорад.','noun'),
      W('Element','/ˈelɪmənt/','элемент','Унсур','🧱','Gold is a chemical element.','Тилло унсури кимиёвӣ аст.','noun'),
      W('Chemical','/ˈkemɪkl/','кемикл','Кимиёвӣ / модда','🧪','Do not mix these chemicals.','Ин моддаҳои кимиёвиро омехта накунед.','noun'),
      W('Reaction','/riˈækʃn/','риекшн','Реаксия / вокуниш','💥','The reaction produced a lot of heat.','Реаксия гармии зиёд ба вуҷуд овард.','noun'),
      W('Gravity','/ˈɡrævəti/','гравити','Ҷозиба','🌍','Gravity pulls objects towards the Earth.','Ҷозиба ашёро ба Замин мекашад.','noun'),
      W('Particle','/ˈpɑːtɪkl/','партикл','Зарра','🔬','Light is made of tiny particles.','Нур аз заррачаҳои хурд иборат аст.','noun'),
      W('Substance','/ˈsʌbstəns/','сабстенс','Модда','🧴','Water is a natural substance.','Об моддаи табиист.','noun'),
      W('Compound','/ˈkɒmpaʊnd/','компаунд','Пайвастагӣ','🧬','Salt is a compound of sodium and chlorine.','Намак пайвастагии натрий ва хлор аст.','noun'),
      W('Radiation','/ˌreɪdiˈeɪʃn/','рейдиейшн','Радиатсия / шуоъ','☢️','The sun gives off radiation.','Офтоб радиатсия мебарорад.','noun'),
    ]},
    { title: 'Lesson 4: Space and Life', tt: 'Дарси 4: Кайҳон ва ҳаёт', emoji: '🚀', words: [
      W('Universe','/ˈjuːnɪvɜːs/','юниверс','Коинот','🌌','The universe is billions of years old.','Коинот миллиардҳо сол дорад.','noun'),
      W('Galaxy','/ˈɡæləksi/','галакси','Галактика','🌠','Our galaxy is called the Milky Way.','Галактикаи мо «Роҳи Каҳкашон» ном дорад.','noun'),
      W('Orbit','/ˈɔːbɪt/','орбит','Мадор','🛰️','The Moon travels in orbit around the Earth.','Моҳ дар мадори гирди Замин ҳаракат мекунад.','noun'),
      W('Satellite','/ˈsætəlaɪt/','сателлайт','Моҳвора','📡','A satellite sends TV signals.','Моҳвора сигналҳои телевизиониро мефиристад.','noun'),
      W('Astronaut','/ˈæstrənɔːt/','астронот','Кайҳоннавард','👨‍🚀','The astronaut spent six months in space.','Кайҳоннавард шаш моҳ дар кайҳон буд.','noun'),
      W('Spacecraft','/ˈspeɪskrɑːft/','спейскрафт','Киштии кайҳонӣ','🛸','The spacecraft landed on Mars.','Киштии кайҳонӣ ба Миррих фуруд омад.','noun'),
      W('Rocket','/ˈrɒkɪt/','рокет','Мушак / ракета','🚀','The rocket launched at dawn.','Ракета субҳидам парвоз кард.','noun'),
      W('Gene','/dʒiːn/','ҷин','Ген','🧬','Genes decide the colour of our eyes.','Генҳо ранги чашмони моро муайян мекунанд.','noun'),
      W('Cell','/sel/','сел','Ҳуҷайра','🦠','The body is made of millions of cells.','Ҷисм аз миллионҳо ҳуҷайра иборат аст.','noun'),
      W('Evolution','/ˌiːvəˈluːʃn/','эволюшн','Таҳаввул / эволютсия','🐒','Evolution explains how species change.','Эволютсия шарҳ медиҳад, ки чӣ гуна намудҳо тағйир меёбанд.','noun'),
    ]},
  ],
  grammar: [
    {
      title: 'Passive Voice (Other Tenses)', titleTranslated: 'Тарзи мафъул (замонҳои дигар)',
      lessonTitle: 'Lesson 5: Passive — Other Tenses', lessonTitleTg: 'Дарси 5: Тарзи мафъул (замонҳои дигар)', emoji: '🔄',
      explanation: 'Дар **тарзи мафъул (passive)** диққат ба амал аст, на иҷрокунанда. Шакли **be** мувофиқи замон тағйир меёбад + феъли сеюм:\n\n- Present Perfect: **has/have been + V3**: *The results **have been published**.*\n- Future: **will be + V3**: *The rocket **will be launched** tomorrow.*\n- Modal: **can/must be + V3**: *This **must be done** carefully.*\n\nБарои нишон додани иҷрокунанда **by** истифода мешавад: *…**was discovered by** a scientist.*',
      rules: [
        { pattern: 'has/have been + V3', note: 'Passive-и Present Perfect.' },
        { pattern: 'will be + V3', note: 'Passive-и оянда.' },
        { pattern: 'can/must be + V3', note: 'Passive бо феъли модалӣ.' },
      ],
      examples: [
        { sentence: 'A new planet has been discovered.', translation: 'Сайёраи нав кашф карда шудааст.', highlight: 'has been discovered' },
        { sentence: 'The experiment will be repeated next week.', translation: 'Озмоиш ҳафтаи оянда такрор карда мешавад.', highlight: 'will be repeated' },
        { sentence: 'The samples must be kept cold.', translation: 'Намунаҳо бояд хунук нигоҳ дошта шаванд.', highlight: 'must be kept' },
      ],
      exercises: [
        { type:'choose', prompt:'The medicine ___ already ___ tested.', promptTranslated:'Дору аллакай санҷида шудааст.', options:['has / been','have / been','is / being','was / been'], answer:'has / been', explanation:'Present Perfect passive → has been + V3.' },
        { type:'choose', prompt:'The bridge ___ built next year.', promptTranslated:'Пул соли оянда сохта мешавад.', options:['will be','will','is','has been'], answer:'will be', explanation:'Future passive → will be + V3.' },
        { type:'fill_blank', prompt:'These results must ___ checked again. (be)', promptTranslated:'Ин натиҷаҳо бояд боз тафтиш карда шаванд.', answer:'be', explanation:'must + be + V3.' },
        { type:'fill_blank', prompt:'The theory was proved ___ a famous scientist. (by)', promptTranslated:'Назария аз ҷониби олими машҳур исбот шуд.', answer:'by', explanation:'Иҷрокунанда → by.' },
        { type:'transform', prompt:'They / will / launch / the satellite', promptTranslated:'Ба тарзи мафъул табдил диҳед (future).', answer:'The satellite will be launched.', explanation:'will be launched.' },
        { type:'transform', prompt:'Scientists / have / discover / a new gene', promptTranslated:'Ба тарзи мафъул табдил диҳед (present perfect).', answer:'A new gene has been discovered.', explanation:'has been discovered.' },
      ],
    },
    {
      title: 'so / such / too / enough', titleTranslated: 'so / such / too / enough',
      lessonTitle: 'Lesson 6: so, such, too, enough', lessonTitleTg: 'Дарси 6: so / such / too / enough', emoji: '📐',
      explanation: 'Ин калимаҳо дараҷа ва натиҷаро нишон медиҳанд:\n\n- **so + сифат/зарф**: *It was **so cold**.* — Ин қадар хунук буд.\n- **such + (сифат) + исм**: *It was **such a cold day**.* — Чунин рӯзи хунук.\n- **too + сифат** = аз ҳад зиёд (натиҷаи манфӣ): *It is **too hot** to work.* — Барои кор кардан хеле гарм.\n- **сифат + enough** = ба қадри кофӣ: *He is **old enough** to drive.* — Ӯ барои ронандагӣ ба қадри кофӣ калон аст.',
      rules: [
        { pattern: 'so + adjective', note: '“so difficult”.' },
        { pattern: 'such + (a/an) + noun phrase', note: '“such a good idea”.' },
        { pattern: 'too + adjective (+ to)', note: 'Аз ҳад зиёд: “too small to see”.' },
        { pattern: 'adjective + enough (+ to)', note: 'Ба қадри кофӣ: “strong enough”.' },
      ],
      examples: [
        { sentence: 'The problem was so difficult that nobody solved it.', translation: 'Масъала он қадар душвор буд, ки ҳеҷ кас онро ҳал накард.', highlight: 'so difficult' },
        { sentence: 'It was such an interesting lecture.', translation: 'Ин чунин лексияи ҷолиб буд.', highlight: 'such an interesting' },
        { sentence: 'This box is too heavy to lift.', translation: 'Ин қуттӣ барои бардоштан хеле вазнин аст.', highlight: 'too heavy' },
      ],
      exercises: [
        { type:'choose', prompt:'The water was ___ cold that we couldn\'t swim.', promptTranslated:'Об он қадар хунук буд, ки мо шино карда натавонистем.', options:['so','such','too','enough'], answer:'so', explanation:'so + сифат.' },
        { type:'choose', prompt:'It was ___ a boring film.', promptTranslated:'Ин чунин филми дилгиркунанда буд.', options:['such','so','too','enough'], answer:'such', explanation:'such + a + исм.' },
        { type:'choose', prompt:'This tea is ___ hot to drink.', promptTranslated:'Ин чой барои нӯшидан хеле гарм аст.', options:['too','so','such','enough'], answer:'too', explanation:'too + сифат (аз ҳад).' },
        { type:'fill_blank', prompt:'She is not tall ___ to reach the shelf. (enough)', promptTranslated:'Вай барои расидан ба раф ба қадри кофӣ баланд нест.', answer:'enough', explanation:'tall + enough.' },
        { type:'transform', prompt:'It / be / such / a nice surprise', promptTranslated:'Ҷумларо бо “such” созед.', answer:'It was such a nice surprise.', explanation:'such a nice surprise.' },
        { type:'transform', prompt:'He / be / strong / enough / to carry it', promptTranslated:'Ҷумларо бо “enough” созед.', answer:'He is strong enough to carry it.', explanation:'strong enough to carry.' },
      ],
    },
  ],
  listening: {
    lessonTitle: 'Lesson 7: Listening — A Science Fair', lessonTitleTg: 'Дарси 7: Шунавоӣ — Намоишгоҳи илмӣ',
    title: 'The Science Fair', titleTranslated: 'Намоишгоҳи илмӣ', emoji: '🎧',
    passage: 'Last spring, a big science fair was held at Malika\'s school. Students had been preparing their projects for months. Malika and her team built a small model of a solar-powered car. Their idea was so clever that it won first prize. A local newspaper wrote an article about the fair, and their photo was printed on the front page. The judges said that the projects had been designed with great care and that the future of science looked bright. Malika was so proud that she decided to study engineering at university. She now believes that with enough effort, young people can help solve some of the world\'s biggest problems, such as pollution and climate change.',
    passageTranslated: 'Баҳори гузашта дар мактаби Малика намоишгоҳи калони илмӣ баргузор шуд. Донишҷӯён чанд моҳ лоиҳаҳояшонро тайёр мекарданд. Малика ва дастаи ӯ намунаи хурди мошини аз офтоб қувватгирандаро сохтанд. Ғояи онҳо он қадар зирак буд, ки ҷои якумро гирифт. Рӯзномаи маҳаллӣ дар бораи намоишгоҳ мақола навишт ва акси онҳо дар саҳифаи аввал чоп шуд. Довaрон гуфтанд, ки лоиҳаҳо бо диққати калон тарҳрезӣ шудаанд ва ояндаи илм дурахшон менамояд. Малика он қадар ифтихор кард, ки қарор дод дар донишгоҳ муҳандисиро омӯзад. Вай ҳоло боварӣ дорад, ки бо кӯшиши кофӣ ҷавонон метавонанд ба ҳалли баъзе аз бузургтарин мушкилоти ҷаҳон, ба монанди ифлосшавӣ ва тағйири иқлим, кӯмак кунанд.',
    questions: [
      { question: 'What did Malika\'s team build?', questionTranslated: 'Дастаи Малика чӣ сохт?', options: ['A model of a solar-powered car','A rocket','A robot dog','A telescope'], correctIndex: 0, explanation: '“a small model of a solar-powered car”.' },
      { question: 'Why did their project win?', questionTranslated: 'Чаро лоиҳаи онҳо ғолиб шуд?', options: ['The idea was so clever','It was very cheap','It was the biggest','They were lucky'], correctIndex: 0, explanation: '“so clever that it won first prize”.' },
      { question: 'Where was their photo printed?', questionTranslated: 'Акси онҳо куҷо чоп шуд?', options: ['On the front page of a newspaper','On a website','On a poster','In a book'], correctIndex: 0, explanation: '“printed on the front page”.' },
      { question: 'What did Malika decide to study?', questionTranslated: 'Малика чиро омӯхтан қарор дод?', options: ['Engineering','Music','History','Cooking'], correctIndex: 0, explanation: '“study engineering at university”.' },
      { question: 'What does she believe young people can help solve?', questionTranslated: 'Вай боварӣ дорад, ки ҷавонон ба ҳалли чӣ кӯмак карда метавонанд?', options: ['Pollution and climate change','Traffic only','Homework','Nothing'], correctIndex: 0, explanation: '“pollution and climate change”.' },
    ],
  },
  dialogue: {
    lessonTitle: 'Lesson 8: Speaking — A Museum Visit', lessonTitleTg: 'Дарси 8: Гуфтугӯ — Ташриф ба осорхона',
    title: 'At the Science Museum', titleTranslated: 'Дар осорхонаи илм', scenario: 'A visitor asks a guide about the exhibits at a science museum.', emoji: '🔭',
    lines: [
      { speaker: 'Guide', text: 'Welcome to the science museum. Any questions?', translation: 'Ба осорхонаи илм хуш омадед. Саволе ҳаст?', isUser: false },
      { speaker: 'Visitor', text: 'Yes. What is that large machine over there?', translation: 'Ҳа. Он мошини калони он ҷо чист?', isUser: true },
      { speaker: 'Guide', text: 'It is a model of a spacecraft that was sent to Mars.', translation: 'Ин намунаи киштии кайҳонист, ки ба Миррих фиристода шуд.', isUser: false },
      { speaker: 'Visitor', text: 'That\'s amazing! When was it launched?', translation: 'Ин аҷоиб аст! Кай он парвоз кард?', isUser: true },
      { speaker: 'Guide', text: 'It was launched in 2020 and is still in orbit.', translation: 'Он соли 2020 парвоз кард ва ҳоло ҳам дар мадор аст.', isUser: false },
      { speaker: 'Visitor', text: 'Can I take photos of the exhibits?', translation: 'Метавонам аз намоишҳо акс гирам?', isUser: true },
      { speaker: 'Guide', text: 'Of course, but flash is not allowed.', translation: 'Албатта, вале аккоси барқӣ манъ аст.', isUser: false },
      { speaker: 'Visitor', text: 'Understood. Is there a section about the human body?', translation: 'Фаҳмидам. Бахше дар бораи ҷисми инсон ҳаст?', isUser: true },
      { speaker: 'Guide', text: 'Yes, it is on the second floor.', translation: 'Ҳа, он дар ошёнаи дуюм аст.', isUser: false },
    ],
  },
  reading: {
    lessonTitle: 'Lesson 9: Reading — The Future of Energy', lessonTitleTg: 'Дарси 9: Хониш — Ояндаи энергия',
    title: 'The Future of Energy', titleTranslated: 'Ояндаи энергия', emoji: '📖',
    passage: 'For over a hundred years, most of the world\'s energy has been produced by burning coal, oil, and gas. However, these fuels cause pollution and will not last forever. Because of this, scientists have been developing cleaner sources of energy, such as solar panels and wind turbines. In many countries, large amounts of electricity are now generated by the sun and the wind. Experts believe that in the future, most homes will be powered by renewable energy. Electric cars, which are charged instead of filled with petrol, are already becoming common. The change will not be easy, and new technology must be developed, but the benefits are clear. A cleaner planet will be created for the next generation if we act quickly enough.',
    passageTranslated: 'Дар давоми зиёда аз сад сол, аксари энергияи ҷаҳон тавассути сӯзондани ангишт, нафт ва газ истеҳсол мешуд. Аммо ин сӯзишвориҳо ифлосшавӣ ба вуҷуд меоранд ва абадӣ намемонанд. Аз ин сабаб, олимон манбаъҳои тозатари энергияро, ба монанди панелҳои офтобӣ ва турбинаҳои шамолӣ, таҳия карда истодаанд. Дар бисёр кишварҳо ҳоло миқдори зиёди барқ аз офтобу шамол истеҳсол мешавад. Коршиносон боварӣ доранд, ки дар оянда аксари хонаҳо бо энергияи барқароршаванда таъмин мешаванд. Мошинҳои барқӣ, ки ба ҷои бензин пур кардан, заряд карда мешаванд, аллакай маъмул шуда истодаанд. Тағйирот осон намешавад ва технологияи нав бояд таҳия шавад, вале манфиатҳо равшананд. Агар мо ба қадри кофӣ зуд амал кунем, барои насли оянда сайёраи тозатар ба вуҷуд оварда мешавад.',
    questions: [
      { question: 'How has most energy been produced for over a century?', questionTranslated: 'Дар давоми зиёда аз як аср аксари энергия чӣ тавр истеҳсол шудааст?', options: ['By burning coal, oil, and gas','By the sun only','By nuclear power only','By water only'], correctIndex: 0, explanation: '“burning coal, oil, and gas”.' },
      { question: 'What have scientists been developing?', questionTranslated: 'Олимон чиро таҳия карда истодаанд?', options: ['Cleaner sources of energy','Bigger cars','New fuels from oil','Louder machines'], correctIndex: 0, explanation: '“cleaner sources of energy”.' },
      { question: 'What will power most homes in the future?', questionTranslated: 'Дар оянда аксари хонаҳоро чӣ таъмин мекунад?', options: ['Renewable energy','Only coal','Candles','Nothing'], correctIndex: 0, explanation: '“powered by renewable energy”.' },
      { question: 'How are electric cars different?', questionTranslated: 'Мошинҳои барқӣ чӣ фарқ доранд?', options: ['They are charged, not filled with petrol','They use more oil','They cannot move','They need coal'], correctIndex: 0, explanation: '“charged instead of filled with petrol”.' },
      { question: 'What is needed to make the change?', questionTranslated: 'Барои тағйирот чӣ лозим аст?', options: ['New technology must be developed','Nothing at all','More coal','Fewer scientists'], correctIndex: 0, explanation: '“new technology must be developed”.' },
    ],
  },
  review: {
    passage: 'Science changes our lives. New discoveries are made every year, and problems that were once impossible to solve can now be understood. The future will be shaped by young scientists, so education is so important for everyone.',
    passageTranslated: 'Илм ҳаёти моро тағйир медиҳад. Ҳар сол кашфиётҳои нав ба амал меоянд ва мушкилоте, ки замоне ҳалнашаванда буданд, ҳоло фаҳмида мешаванд. Ояндаро олимони ҷавон шакл медиҳанд, бинобар ин таҳсил барои ҳама хеле муҳим аст.',
    questions: [
      { question: 'Which word means “коинот”?', questionTranslated: 'Кадом калима маънои “коинот”-ро дорад?', options: ['Universe','Element','Formula','Reaction'], correctIndex: 0, explanation: 'universe = коинот.' },
      { question: 'Complete: “The results ___ been published.”', questionTranslated: 'Пур кунед: Натиҷаҳо нашр карда шудаанд.', options: ['have','has to','are','will'], correctIndex: 0, explanation: 'Present Perfect passive: have been.' },
      { question: 'Complete: “It was ___ a difficult exam!”', questionTranslated: 'Пур кунед: Ин чунин имтиҳони душвор буд!', options: ['such','so','too','enough'], correctIndex: 0, explanation: 'such + a + noun.' },
      { question: 'What does a “satellite” do?', questionTranslated: '“Satellite” чӣ кор мекунад?', options: ['Travels around a planet and sends signals','Grows plants','Cooks food','Cleans water'], correctIndex: 0, explanation: 'satellite = моҳвора.' },
      { question: 'Choose the correct sentence.', questionTranslated: 'Ҷумлаи дурустро интихоб кунед.', options: ['The rocket will be launched tomorrow.','The rocket will launched tomorrow.','The rocket will be launch tomorrow.','The rocket is be launched tomorrow.'], correctIndex: 0, explanation: 'will be + V3.' },
    ],
  },
  exam: {
    passage: 'This exam reviews Module 10: science and future vocabulary, the passive voice in different tenses, and so/such/too/enough. Choose the best answer for each question.',
    passageTranslated: 'Ин имтиҳон Модули 10-ро такрор мекунад: луғати илм ва оянда, тарзи мафъул дар замонҳои гуногун ва so/such/too/enough. Барои ҳар савол беҳтарин ҷавобро интихоб кунед.',
    questions: [
      { question: 'A new vaccine ___ been developed this year.', questionTranslated: 'Имсол ваксинаи нав таҳия карда шудааст.', options: ['has','have','is','will'], correctIndex: 0, explanation: 'has been developed.' },
      { question: 'The film was ___ long that I fell asleep.', questionTranslated: 'Филм он қадар дароз буд, ки ман хоб рафтам.', options: ['so','such','too','enough'], correctIndex: 0, explanation: 'so + adjective.' },
      { question: 'Which word means “ҷозиба”?', questionTranslated: 'Кадом калима маънои “ҷозиба”-ро дорад?', options: ['Gravity','Cell','Orbit','Theory'], correctIndex: 0, explanation: 'gravity = ҷозиба.' },
      { question: 'This coffee is ___ hot to drink right now.', questionTranslated: 'Ин қаҳва барои ҳозир нӯшидан хеле гарм аст.', options: ['too','so','such','enough'], correctIndex: 0, explanation: 'too + adjective.' },
      { question: 'Choose the correct sentence.', questionTranslated: 'Ҷумлаи дурустро интихоб кунед.', options: ['The bridge will be built next year.','The bridge will build next year.','The bridge is built by next year will.','The bridge will been built next year.'], correctIndex: 0, explanation: 'will be built.' },
    ],
  },
};
