import { W } from './b1-api-build.mjs';

export const M = {
  order: 12, title: 'Module 12: Personal Development', titleTranslated: 'Модули 12: Рушди шахсӣ',
  emoji: '🚀', color: '#F97316',
  vocab: [
    { title: 'Lesson 1: Goals and Ambition', tt: 'Дарси 1: Ҳадафҳо ва орзу', emoji: '🎯', words: [
      W('Aspiration','/ˌæspəˈreɪʃn/','аспирейшн','Орзу / ормон','🌟','Her aspiration is to become a surgeon.','Орзуи вай ҷарроҳ шудан аст.','noun'),
      W('Milestone','/ˈmaɪlstəʊn/','майлстоун','Марҳилаи муҳим','🏁','Graduating was an important milestone.','Хатми донишгоҳ марҳилаи муҳим буд.','noun'),
      W('Potential','/pəˈtenʃl/','потеншл','Иқтидор / имконият','📈','This student has great potential.','Ин донишҷӯ иқтидори калон дорад.','noun'),
      W('Talent','/ˈtælənt/','талант','Истеъдод','🎨','She has a real talent for music.','Вай ба мусиқӣ истеъдоди воқеӣ дорад.','noun'),
      W('Vision','/ˈvɪʒn/','вижн','Дурнамо / ормон','🔭','A good leader needs a clear vision.','Роҳбари хуб ба дурнамои равшан ниёз дорад.','noun'),
      W('Focus','/ˈfəʊkəs/','фоукус','Тамаркуз','🎯','Try to keep your focus on the goal.','Кӯшиш кунед, ки тамаркузро ба ҳадаф нигоҳ доред.','noun'),
      W('Determination','/dɪˌtɜːmɪˈneɪʃn/','дитёрминейшн','Азму қатъият','💪','With determination, anything is possible.','Бо азм ҳама чиз имконпазир аст.','noun'),
      W('Perseverance','/ˌpɜːsɪˈvɪərəns/','пёрсивиренс','Собитқадамӣ','🧗','Success comes through perseverance.','Муваффақият тавассути собитқадамӣ меояд.','noun'),
      W('Dedication','/ˌdedɪˈkeɪʃn/','дедикейшн','Фидокорӣ / садоқат','🔥','Her dedication to work is admirable.','Фидокории вай ба кор қобили таҳсин аст.','noun'),
      W('Commitment','/kəˈmɪtmənt/','комитмент','Ӯҳдадорӣ / садоқат','🤝','Learning a language needs commitment.','Омӯхтани забон ӯҳдадориро талаб мекунад.','noun'),
    ]},
    { title: 'Lesson 2: Strengths', tt: 'Дарси 2: Тавоноиҳо', emoji: '💪', words: [
      W('Discipline','/ˈdɪsəplɪn/','дисиплин','Интизом','⏰','Self-discipline helps you reach your goals.','Худинтизомӣ ба расидан ба ҳадафҳо кӯмак мекунад.','noun'),
      W('Confidence','/ˈkɒnfɪdəns/','конфиденс','Эътимоди худ','😎','Practice gives you confidence.','Машқ ба шумо эътимоди худ медиҳад.','noun'),
      W('Attitude','/ˈætɪtjuːd/','атитюд','Муносибат / рӯҳия','🙂','A positive attitude changes everything.','Муносибати мусбат ҳама чизро тағйир медиҳад.','noun'),
      W('Initiative','/ɪˈnɪʃətɪv/','инишатив','Ташаббус','🚀','She showed initiative at work.','Вай дар кор ташаббус нишон дод.','noun'),
      W('Creativity','/ˌkriːeɪˈtɪvəti/','криейтивити','Эҷодкорӣ','🎨','Creativity is important in every job.','Эҷодкорӣ дар ҳар кор муҳим аст.','noun'),
      W('Patience','/ˈpeɪʃns/','пейшнс','Сабр','🧘','Learning takes time and patience.','Омӯзиш вақт ва сабр мехоҳад.','noun'),
      W('Curiosity','/ˌkjʊəriˈɒsəti/','кюриосити','Кунҷковӣ','🔍','Curiosity helps children learn.','Кунҷковӣ ба омӯзиши кӯдакон кӯмак мекунад.','noun'),
      W('Adaptable','/əˈdæptəbl/','адаптабл','Мутобиқшаванда','🔄','A good worker is adaptable.','Коргари хуб мутобиқшаванда аст.','adjective'),
      W('Organised','/ˈɔːɡənaɪzd/','органайзд','Ботартиб','🗂️','She is very organised and punctual.','Вай хеле ботартиб ва саривақт аст.','adjective'),
      W('Productive','/prəˈdʌktɪv/','продактив','Пурмаҳсул / самаранок','✅','I feel productive in the morning.','Ман субҳ худро пурмаҳсул ҳис мекунам.','adjective'),
    ]},
    { title: 'Lesson 3: Challenges', tt: 'Дарси 3: Душвориҳо', emoji: '🧗', words: [
      W('Failure','/ˈfeɪljə/','фейлюр','Нокомӣ / шикаст','❌','Failure is a part of learning.','Нокомӣ қисми омӯзиш аст.','noun'),
      W('Weakness','/ˈwiːknəs/','виакнес','Заъф / нуқсон','📉','Everyone has strengths and weaknesses.','Ҳар кас тавоноӣ ва заъф дорад.','noun'),
      W('Challenge','/ˈtʃælɪndʒ/','челинҷ','Мушкилӣ / вазифаи душвор','🏔️','Starting a business is a big challenge.','Оғози тиҷорат мушкилии калон аст.','noun'),
      W('Obstacle','/ˈɒbstəkl/','обстакл','Монеа','🚧','He overcame every obstacle.','Ӯ ба ҳар монеа ғолиб омад.','noun'),
      W('Struggle','/ˈstrʌɡl/','страгл','Талош / мубориза','😤','At first, she struggled with English.','Аввал вай бо англисӣ мубориза мебурд.','verb'),
      W('Setback','/ˈsetbæk/','сетбек','Ақибнишинӣ / нокомии муваққатӣ','⬇️','Do not give up after a setback.','Баъди як нокомӣ даст накашед.','noun'),
      W('Overcome','/ˌəʊvəˈkʌm/','оуверкам','Бартараф кардан','🏆','She overcame her fear of speaking.','Вай тарси гап заданро бартараф кард.','verb'),
      W('Effort','/ˈefət/','эфорт','Кӯшиш','🏋️','Real progress requires effort.','Пешрафти воқеӣ кӯшишро талаб мекунад.','noun'),
      W('Improve','/ɪmˈpruːv/','импрув','Беҳтар кардан','📈','Reading helps you improve your English.','Хониш ба беҳтар кардани англисии шумо кӯмак мекунад.','verb'),
      W('Reflect','/rɪˈflekt/','рифлект','Мулоҳиза кардан','🤔','Take time to reflect on your day.','Барои мулоҳиза дар бораи рӯзатон вақт ҷудо кунед.','verb'),
    ]},
    { title: 'Lesson 4: Work and Career', tt: 'Дарси 4: Кор ва касб', emoji: '💼', words: [
      W('Leadership','/ˈliːdəʃɪp/','лидершип','Роҳбарӣ','👔','Good leadership inspires a team.','Роҳбарии хуб дастаро илҳом мебахшад.','noun'),
      W('Teamwork','/ˈtiːmwɜːk/','тимвёрк','Кори дастаҷамъӣ','🤝','Teamwork makes difficult tasks easier.','Кори дастаҷамъӣ вазифаҳои душворро осон мекунад.','noun'),
      W('Priority','/praɪˈɒrəti/','прайорити','Афзалият / аввалиндараҷа','1️⃣','Health should be your first priority.','Саломатӣ бояд афзалияти аввали шумо бошад.','noun'),
      W('Workload','/ˈwɜːkləʊd/','вёрклоуд','Ҳаҷми кор','📚','My workload is very heavy this week.','Ҳаҷми кори ман ин ҳафта хеле вазнин аст.','noun'),
      W('Mentor','/ˈmentɔː/','ментор','Устод / роҳнамо','🧑‍🏫','A good mentor can change your life.','Устоди хуб метавонад ҳаёти шуморо тағйир диҳад.','noun'),
      W('Networking','/ˈnetwɜːkɪŋ/','нетвёркинг','Робитасозӣ','🔗','Networking helps you find new jobs.','Робитасозӣ ба ёфтани корҳои нав кӯмак мекунад.','noun'),
      W('Freelance','/ˈfriːlɑːns/','фриланс','Озодкор / фриланс','💻','She works freelance from home.','Вай аз хона ба таври озодкор кор мекунад.','adjective'),
      W('Startup','/ˈstɑːtʌp/','стартап','Ширкати навтаъсис','🌱','He founded a tech startup.','Ӯ як ширкати навтаъсиси технологӣ таъсис дод.','noun'),
      W('Résumé','/ˈrezjumeɪ/','резюме','Резюме / тарҷумаи ҳол','📄','Send your résumé with the application.','Резюмеи худро бо ариза фиристед.','noun'),
      W('Growth','/ɡrəʊθ/','гроус','Рушд / нашъунамо','🌿','Personal growth never stops.','Рушди шахсӣ ҳеҷ гоҳ бас намешавад.','noun'),
    ]},
  ],
  grammar: [
    {
      title: 'Mixed Conditionals', titleTranslated: 'Ҷумлаҳои шартии омехта',
      lessonTitle: 'Lesson 5: Mixed Conditionals', lessonTitleTg: 'Дарси 5: Ҷумлаҳои шартии омехта', emoji: '🔀',
      explanation: '**Ҷумлаи шартии омехта** ду замонро мепайвандад:\n\n1. **Шарти гузашта → натиҷаи ҳозира**: *If + Past Perfect, … would + феъл.*\n   *If I **had studied** medicine, I **would be** a doctor now.* — Агар тибро мехондам, ҳоло духтур мебудам.\n2. **Шарти ҳозира → натиҷаи гузашта**: *If + Past Simple, … would have + V3.*\n   *If I **were** more careful, I **wouldn\'t have made** that mistake.*\n\nОмехта вақте истифода мешавад, ки замони шарт ва натиҷа фарқ кунанд.',
      rules: [
        { pattern: 'If + Past Perfect, would + V (ҳозира)', note: 'Шарти гузашта, натиҷаи ҳозира.' },
        { pattern: 'If + Past Simple, would have + V3 (гузашта)', note: 'Шарти ҳозира, натиҷаи гузашта.' },
      ],
      examples: [
        { sentence: 'If I had saved money, I would have a car now.', translation: 'Агар пул ҷамъ мекардам, ҳоло мошин медоштам.', highlight: 'had saved … would have' },
        { sentence: 'If she were more organised, she wouldn\'t have missed the deadline.', translation: 'Агар вай ботартибтар мебуд, мӯҳлатро аз даст намедод.', highlight: "were … wouldn't have missed" },
        { sentence: 'If he had taken the job, he would be in London today.', translation: 'Агар ӯ он корро мегирифт, имрӯз дар Лондон мебуд.', highlight: 'had taken … would be' },
      ],
      exercises: [
        { type:'choose', prompt:'If I had learned to drive, I ___ a car now.', promptTranslated:'Агар ронандагиро меомӯхтам, ҳоло мошин медоштам.', options:['would have','will have','had','would had'], answer:'would have', explanation:'Шарти гузашта → натиҷаи ҳозира (would have).' },
        { type:'choose', prompt:'If she were taller, she ___ the team last year.', promptTranslated:'Агар вай баландтар мебуд, соли гузашта ба даста медаромад.', options:['would have joined','would join','joined','will join'], answer:'would have joined', explanation:'Шарти ҳозира → натиҷаи гузашта (would have + V3).' },
        { type:'fill_blank', prompt:'If they had invested earlier, they ___ be rich today. (would)', promptTranslated:'Агар барвақттар сармоягузорӣ мекарданд, имрӯз сарватманд мебуданд.', answer:'would', explanation:'would + be (натиҷаи ҳозира).' },
        { type:'fill_blank', prompt:'If I ___ better at maths, I would have passed the exam. (be)', promptTranslated:'Агар ман дар риёзӣ беҳтар мебудам, имтиҳонро месупоридам.', answer:'were', explanation:'If + were (шарти ҳозира).' },
        { type:'transform', prompt:'I / not sleep well last night → I / be / tired now', promptTranslated:'Ҷумлаи шартии омехта созед.', answer:'If I had slept well last night, I would not be tired now.', explanation:'had slept … would not be.' },
        { type:'transform', prompt:'He / be / lazy → he / not finish / the project', promptTranslated:'Ҷумлаи шартии омехта созед.', answer:'If he were not lazy, he would have finished the project.', explanation:'were not … would have finished.' },
      ],
    },
    {
      title: 'Phrasal Verbs', titleTranslated: 'Феълҳои таркибӣ',
      lessonTitle: 'Lesson 6: Phrasal Verbs', lessonTitleTg: 'Дарси 6: Феълҳои таркибӣ', emoji: '🧩',
      explanation: '**Феълҳои таркибӣ** аз феъл + пешоянд/зарф иборатанд ва маънои нав доранд:\n\n- **give up** — даст кашидан: *Don\'t **give up**!*\n- **carry on** — идома додан: *She **carried on** working.*\n- **take up** — оғоз кардан (машғулият): *He **took up** running.*\n- **look forward to** — интизор будан: *I **look forward to** meeting you.*\n- **put off** — ба таъхир андохтан: *Don\'t **put off** the work.*\n- **come up with** — пешниҳод кардан: *She **came up with** a plan.*',
      rules: [
        { pattern: 'give up = даст кашидан', note: 'Феъл + up.' },
        { pattern: 'put off = ба таъхир андохтан', note: 'Феъл + off.' },
        { pattern: 'look forward to + V-ing', note: 'Баъди “to” → V-ing.' },
      ],
      examples: [
        { sentence: 'She never gives up on her dreams.', translation: 'Вай ҳеҷ гоҳ аз орзуҳояш даст намекашад.', highlight: 'gives up' },
        { sentence: 'He took up painting last year.', translation: 'Ӯ соли гузашта ба наққошӣ шурӯъ кард.', highlight: 'took up' },
        { sentence: 'I am looking forward to starting my new job.', translation: 'Ман интизори оғози кори навамро дорам.', highlight: 'looking forward to' },
      ],
      exercises: [
        { type:'choose', prompt:'Don\'t ___ up! You are almost there.', promptTranslated:'Даст накаш! Ту қариб расидӣ.', options:['give','take','put','look'], answer:'give', explanation:'give up = даст кашидан.' },
        { type:'choose', prompt:'She decided to ___ up yoga to reduce stress.', promptTranslated:'Вай қарор кард, ки барои кам кардани фишор йогаро сар кунад.', options:['take','give','put','carry'], answer:'take', explanation:'take up = машғулиятро оғоз кардан.' },
        { type:'choose', prompt:'We should not ___ off the decision any longer.', promptTranslated:'Мо набояд қарорро дигар ба таъхир андозем.', options:['put','give','take','look'], answer:'put', explanation:'put off = ба таъхир андохтан.' },
        { type:'fill_blank', prompt:'I look forward ___ hearing from you. (to)', promptTranslated:'Ман интизори хабар аз шумо ҳастам.', answer:'to', explanation:'look forward + to.' },
        { type:'transform', prompt:'She / come up with / a great idea', promptTranslated:'Ҷумларо созед.', answer:'She came up with a great idea.', explanation:'came up with = пешниҳод кард.' },
        { type:'transform', prompt:'They / carry on / despite the problems', promptTranslated:'Ҷумларо созед.', answer:'They carried on despite the problems.', explanation:'carry on = идома додан.' },
      ],
    },
  ],
  listening: {
    lessonTitle: 'Lesson 7: Listening — Never Give Up', lessonTitleTg: 'Дарси 7: Шунавоӣ — Ҳеҷ гоҳ даст накаш',
    title: 'Never Give Up', titleTranslated: 'Ҳеҷ гоҳ даст накаш', emoji: '🎧',
    passage: 'When Nilufar finished school, she dreamed of becoming a doctor, but she failed the university entrance exam. It was a huge setback, and for a while she lost all her confidence. Her mentor, who believed in her, told her not to give up. So Nilufar studied even harder, took up new study habits, and reflected on her weaknesses. The following year, she passed the exam with excellent results. Looking back, she says that if she had given up after her first failure, she would not be a medical student today. She learned that determination and patience matter more than natural talent. Now she tells younger students that every obstacle is a chance to grow, and that success usually comes to those who keep trying.',
    passageTranslated: 'Вақте Нилуфар мактабро тамом кард, орзуи духтур шуданро дошт, вале имтиҳони вурудии донишгоҳро супорида натавонист. Ин нокомии бузург буд ва муддате вай тамоми эътимоди худро гум кард. Устодаш, ки ба вай бовар дошт, ба ӯ гуфт, ки даст накашад. Пас Нилуфар боз ҳам сахттар таҳсил кард, одатҳои нави омӯзишро гирифт ва дар бораи заъфҳояш мулоҳиза кард. Соли оянда ӯ имтиҳонро бо натиҷаҳои аъло супорид. Ба гузашта нигариста, ӯ мегӯяд, ки агар баъди нокомии аввалаш даст мекашид, имрӯз донишҷӯи тиб намебуд. Ӯ омӯхт, ки азму сабр аз истеъдоди табиӣ муҳимтаранд. Ҳоло ӯ ба донишҷӯёни ҷавонтар мегӯяд, ки ҳар монеа имконияти рушд аст ва муваффақият одатан ба онҳое меояд, ки кӯшишро идома медиҳанд.',
    questions: [
      { question: 'What did Nilufar dream of becoming?', questionTranslated: 'Нилуфар орзуи чӣ шуданро дошт?', options: ['A doctor','A teacher','A singer','An engineer'], correctIndex: 0, explanation: '“dreamed of becoming a doctor”.' },
      { question: 'What happened at her first exam?', questionTranslated: 'Дар имтиҳони аввалаш чӣ шуд?', options: ['She failed it','She passed easily','She missed it','She was late'], correctIndex: 0, explanation: '“she failed the university entrance exam”.' },
      { question: 'What did her mentor tell her?', questionTranslated: 'Устодаш ба ӯ чӣ гуфт?', options: ['Not to give up','To change careers','To rest for a year','To move away'], correctIndex: 0, explanation: '“told her not to give up”.' },
      { question: 'What would have happened if she had given up?', questionTranslated: 'Агар вай даст мекашид, чӣ мешуд?', options: ['She would not be a medical student today','She would be richer','Nothing would change','She would be a teacher'], correctIndex: 0, explanation: 'mixed conditional in the text.' },
      { question: 'What matters more than natural talent?', questionTranslated: 'Чӣ аз истеъдоди табиӣ муҳимтар аст?', options: ['Determination and patience','Money','Luck','Height'], correctIndex: 0, explanation: '“determination and patience matter more”.' },
    ],
  },
  dialogue: {
    lessonTitle: 'Lesson 8: Speaking — A Job Interview', lessonTitleTg: 'Дарси 8: Гуфтугӯ — Мусоҳибаи корӣ',
    title: 'A Job Interview', titleTranslated: 'Мусоҳибаи корӣ', scenario: 'A candidate answers questions at a job interview.', emoji: '💼',
    lines: [
      { speaker: 'Interviewer', text: 'Thank you for coming. Tell me about yourself.', translation: 'Ташаккур барои омаданатон. Дар бораи худатон нақл кунед.', isUser: false },
      { speaker: 'Candidate', text: 'I am hard-working and I enjoy teamwork.', translation: 'Ман меҳнатдӯст ҳастам ва кори дастаҷамъиро дӯст медорам.', isUser: true },
      { speaker: 'Interviewer', text: 'What would you say is your greatest strength?', translation: 'Бузургтарин тавоноии шумо чист?', isUser: false },
      { speaker: 'Candidate', text: 'My determination. I never give up on a task.', translation: 'Азми ман. Ман ҳеҷ гоҳ аз вазифа даст намекашам.', isUser: true },
      { speaker: 'Interviewer', text: 'And what about a weakness?', translation: 'Ва дар бораи заъф чӣ?', isUser: false },
      { speaker: 'Candidate', text: 'Sometimes I focus too much on small details.', translation: 'Баъзан ман ба ҷузъиёти хурд аз ҳад тамаркуз мекунам.', isUser: true },
      { speaker: 'Interviewer', text: 'Why do you want to work here?', translation: 'Чаро мехоҳед дар ин ҷо кор кунед?', isUser: false },
      { speaker: 'Candidate', text: 'I am looking forward to growing with your company.', translation: 'Ман интизори рушд бо ширкати шумо ҳастам.', isUser: true },
      { speaker: 'Interviewer', text: 'Great. We will contact you soon.', translation: 'Аъло. Мо ба зудӣ бо шумо тамос мегирем.', isUser: false },
    ],
  },
  reading: {
    lessonTitle: 'Lesson 9: Reading — Lifelong Learning', lessonTitleTg: 'Дарси 9: Хониш — Омӯзиши якумрӣ',
    title: 'Lifelong Learning', titleTranslated: 'Омӯзиши якумрӣ', emoji: '📖',
    passage: 'In the past, people believed that learning stopped when you left school or university. Today, experts agree that education should continue throughout our whole lives. The world changes so quickly that the skills we learn today may be out of date in ten years. People who keep learning are more adaptable, more confident, and usually more successful in their careers. Lifelong learning does not always mean going back to university. It can be as simple as reading books, taking an online course, or learning a new language in your free time. The most important thing is to have curiosity and a positive attitude. If more people took up new skills throughout their lives, they would be better prepared for the challenges of the future. As one famous saying goes, "Live as if you were to die tomorrow; learn as if you were to live forever."',
    passageTranslated: 'Дар гузашта одамон бовар доштанд, ки омӯзиш вақте бас мешавад, ки шумо мактаб ё донишгоҳро тарк мекунед. Имрӯз коршиносон розӣ ҳастанд, ки таҳсил бояд дар тӯли тамоми ҳаёти мо давом кунад. Ҷаҳон он қадар зуд тағйир меёбад, ки маҳоратҳое, ки мо имрӯз меомӯзем, метавонанд баъди даҳ сол кӯҳна шаванд. Одамоне, ки омӯзишро идома медиҳанд, мутобиқшавандатар, боэътимодтар ва одатан дар касбашон муваффақтаранд. Омӯзиши якумрӣ ҳамеша маънои ба донишгоҳ баргаштанро надорад. Он метавонад ба монанди хондани китобҳо, гузаштани курси онлайн ё омӯхтани забони нав дар вақти холии шумо содда бошад. Муҳимтарин чиз доштани кунҷковӣ ва муносибати мусбат аст. Агар одамони бештар дар тӯли ҳаёташон маҳоратҳои нав меомӯхтанд, онҳо ба душвориҳои оянда беҳтар омода мебуданд. Тавре як мақоли машҳур мегӯяд: «Чунон зиндагӣ кун, ки гӯё фардо бимирӣ; чунон омӯз, ки гӯё ҷовидон зиндагӣ кунӣ».',
    questions: [
      { question: 'What did people believe in the past about learning?', questionTranslated: 'Дар гузашта одамон дар бораи омӯзиш чӣ бовар доштанд?', options: ['It stopped after school','It never begins','It is only for adults','It is useless'], correctIndex: 0, explanation: '“learning stopped when you left school”.' },
      { question: 'Why can today\'s skills become out of date?', questionTranslated: 'Чаро маҳоратҳои имрӯза метавонанд кӯҳна шаванд?', options: ['The world changes quickly','People forget them','Schools close','Books disappear'], correctIndex: 0, explanation: '“the world changes so quickly”.' },
      { question: 'What are people who keep learning usually like?', questionTranslated: 'Одамоне, ки омӯзишро идома медиҳанд, одатан чӣ гунаанд?', options: ['More adaptable and successful','Less confident','Always tired','Never busy'], correctIndex: 0, explanation: '“more adaptable, more confident, and usually more successful”.' },
      { question: 'What is a simple example of lifelong learning?', questionTranslated: 'Намунаи соддаи омӯзиши якумрӣ чист?', options: ['Reading books or taking an online course','Sleeping more','Buying a car','Watching TV all day'], correctIndex: 0, explanation: '“reading books, taking an online course, or learning a new language”.' },
      { question: 'What is the most important thing for lifelong learning?', questionTranslated: 'Муҳимтарин чиз барои омӯзиши якумрӣ чист?', options: ['Curiosity and a positive attitude','A lot of money','A university degree','Free time only'], correctIndex: 0, explanation: '“curiosity and a positive attitude”.' },
    ],
  },
  review: {
    passage: 'Personal growth needs effort, patience, and a positive attitude. We all face challenges, but if we never give up, we can overcome them. If you had started learning English earlier, you would already be fluent — but it is never too late to begin.',
    passageTranslated: 'Рушди шахсӣ кӯшиш, сабр ва муносибати мусбатро талаб мекунад. Ҳамаи мо бо душвориҳо рӯ ба рӯ мешавем, вале агар ҳеҷ гоҳ даст накашем, метавонем онҳоро бартараф кунем. Агар шумо англисиро барвақттар меомӯхтед, аллакай озод гап мезадед — вале барои оғоз ҳеҷ гоҳ дер нест.',
    questions: [
      { question: 'Which word means “собитқадамӣ”?', questionTranslated: 'Кадом калима маънои “собитқадамӣ”-ро дорад?', options: ['Perseverance','Failure','Weakness','Obstacle'], correctIndex: 0, explanation: 'perseverance = собитқадамӣ.' },
      { question: 'Complete: “If I had studied law, I ___ a lawyer now.”', questionTranslated: 'Пур кунед: Агар ҳуқуқро мехондам, ҳоло ҳуқуқшинос мебудам.', options: ['would be','would have','will be','had been'], correctIndex: 0, explanation: 'Mixed conditional: would be.' },
      { question: 'Complete the phrasal verb: “Don\'t ___ up your dreams.”', questionTranslated: 'Феъли таркибиро пур кунед: Аз орзуҳоят даст накаш.', options: ['give','take','put','look'], correctIndex: 0, explanation: 'give up = даст кашидан.' },
      { question: 'What does “mentor” mean?', questionTranslated: '“Mentor” чӣ маъно дорад?', options: ['An experienced person who guides you','A new student','A manager only','A classmate'], correctIndex: 0, explanation: 'mentor = устод/роҳнамо.' },
      { question: 'Choose the correct sentence.', questionTranslated: 'Ҷумлаи дурустро интихоб кунед.', options: ['I look forward to seeing you.','I look forward to see you.','I look forward seeing you.','I look forward for see you.'], correctIndex: 0, explanation: 'look forward to + V-ing.' },
    ],
  },
  exam: {
    passage: 'This final exam reviews Module 12: personal development vocabulary, mixed conditionals, and phrasal verbs. It also marks the end of the B1 course. Choose the best answer for each question.',
    passageTranslated: 'Ин имтиҳони ниҳоӣ Модули 12-ро такрор мекунад: луғати рушди шахсӣ, ҷумлаҳои шартии омехта ва феълҳои таркибӣ. Он инчунин анҷоми курси B1-ро нишон медиҳад. Барои ҳар савол беҳтарин ҷавобро интихоб кунед.',
    questions: [
      { question: 'If she had taken the job, she ___ in Dubai now.', questionTranslated: 'Агар вай он корро мегирифт, ҳоло дар Дубай мебуд.', options: ['would live','would have lived','will live','lived'], correctIndex: 0, explanation: 'Mixed conditional: would live (ҳозира).' },
      { question: 'He is very determined and never ___ up.', questionTranslated: 'Ӯ хеле боазм аст ва ҳеҷ гоҳ даст намекашад.', options: ['gives','takes','puts','looks'], correctIndex: 0, explanation: 'give up.' },
      { question: 'Which word means “иқтидор”?', questionTranslated: 'Кадом калима маънои “иқтидор”-ро дорад?', options: ['Potential','Setback','Workload','Failure'], correctIndex: 0, explanation: 'potential = иқтидор.' },
      { question: 'She decided to ___ up a new hobby this year.', questionTranslated: 'Вай қарор кард, ки имсол як машғулияти нав сар кунад.', options: ['take','give','put','come'], correctIndex: 0, explanation: 'take up = оғоз кардан.' },
      { question: 'Choose the correct sentence.', questionTranslated: 'Ҷумлаи дурустро интихоб кунед.', options: ['If I were richer, I would have bought that house last year.','If I were richer, I would buy that house last year.','If I am richer, I would have bought that house last year.','If I were richer, I will have bought that house last year.'], correctIndex: 0, explanation: 'Mixed: were (ҳозира) … would have bought (гузашта).' },
    ],
  },
};
