import { W } from './b1-api-build.mjs';

export const M = {
  order: 7, title: 'Module 7: Money and Shopping', titleTranslated: 'Модули 7: Пул ва Харид',
  emoji: '💰', color: '#F59E0B',
  vocab: [
    { title: 'Lesson 1: Banking', tt: 'Дарси 1: Бонкдорӣ', emoji: '🏦', words: [
      W('Expense','/ɪkˈspens/','икспенс','Хароҷот','🧾','Rent is my biggest monthly expense.','Иҷора хароҷоти калонтарини моҳонаи ман аст.','noun'),
      W('Balance','/ˈbæləns/','баланс','Бақия (дар ҳисоб)','💳','I checked my account balance online.','Ман бақияи ҳисобамро онлайн тафтиш кардам.','noun'),
      W('Statement','/ˈsteɪtmənt/','стейтмент','Ҳисоботи бонкӣ','📄','The bank sends a statement every month.','Бонк ҳар моҳ ҳисобот мефиристад.','noun'),
      W('Transaction','/trænˈzækʃn/','транзекшн','Амалиёт (молиявӣ)','🔁','Every transaction appears in the app.','Ҳар амалиёт дар барнома пайдо мешавад.','noun'),
      W('Overdraft','/ˈəʊvədrɑːft/','оувердрафт','Изофабардошт','📉','I went into overdraft last month.','Моҳи гузашта ман ба изофабардошт афтодам.','noun'),
      W('Interest','/ˈɪntrəst/','интрест','Фоиз (бонкӣ)','％','The loan has a high interest rate.','Қарз фоизи баланд дорад.','noun'),
      W('Mortgage','/ˈmɔːɡɪdʒ/','моргиҷ','Ипотека / қарзи манзил','🏠','They are still paying off their mortgage.','Онҳо ҳанӯз ипотекаашонро пардохт карда истодаанд.','noun'),
      W('Invest','/ɪnˈvest/','инвест','Сармоягузорӣ кардан','📈','She decided to invest in shares.','Вай қарор кард, ки ба саҳмияҳо сармоягузорӣ кунад.','verb'),
      W('Pension','/ˈpenʃn/','пеншн','Нафақа','👴','He receives a monthly pension.','Ӯ нафақаи моҳона мегирад.','noun'),
      W('Insurance','/ɪnˈʃʊərəns/','иншуранс','Суғурта','🛡️','Car insurance is required by law.','Суғуртаи мошин тибқи қонун ҳатмист.','noun'),
    ]},
    { title: 'Lesson 2: Shopping', tt: 'Дарси 2: Харид', emoji: '🛒', words: [
      W('Purchase','/ˈpɜːtʃəs/','пёрчес','Харид кардан','🛍️','I made a big purchase yesterday.','Ман дирӯз хариди калон кардам.','verb'),
      W('Checkout','/ˈtʃekaʊt/','чекаут','Хазина (баромадгоҳ)','🧾','There was a long queue at the checkout.','Дар назди хазина навбати дароз буд.','noun'),
      W('Aisle','/aɪl/','айл','Раста (дар мағоза)','🏬','The bread is in aisle three.','Нон дар растаи сеюм аст.','noun'),
      W('Coupon','/ˈkuːpɒn/','купон','Купон / чипта','🎟️','I used a coupon to get 20% off.','Ман бо купон 20% тахфиф гирифтам.','noun'),
      W('Warranty','/ˈwɒrənti/','воранти','Кафолат','📃','The phone has a two-year warranty.','Телефон кафолати дусола дорад.','noun'),
      W('Instalment','/ɪnˈstɔːlmənt/','инстолмент','Қисм (пардохт)','📆','I pay for the sofa in monthly instalments.','Ман дивонро қисм-қисм ҳар моҳ пардохт мекунам.','noun'),
      W('Retail','/ˈriːteɪl/','ритейл','Чакана (фурӯш)','🏪','She works in the retail sector.','Вай дар бахши чаканафурӯшӣ кор мекунад.','noun'),
      W('Shopper','/ˈʃɒpə/','шопер','Харидор','🛒','The shop was full of shoppers.','Мағоза пур аз харидорон буд.','noun'),
      W('Second-hand','/ˌsekəndˈhænd/','секонд ҳанд','Дастдуюм','♻️','I bought a second-hand bicycle.','Ман дучархаи дастдуюм харидам.','adjective'),
      W('Haggle','/ˈhæɡl/','ҳагл','Чакчак кардан (нарх)','🤝','You can haggle over prices at the bazaar.','Дар бозор шумо метавонед сари нарх чакчак кунед.','verb'),
    ]},
    { title: 'Lesson 3: The Economy', tt: 'Дарси 3: Иқтисодиёт', emoji: '📈', words: [
      W('Profit','/ˈprɒfɪt/','профит','Фоида','💹','The company made a large profit.','Ширкат фоидаи калон ба даст овард.','noun'),
      W('Loss','/lɒs/','лос','Зарар','📉','They sold the car at a loss.','Онҳо мошинро бо зарар фурӯхтанд.','noun'),
      W('Tax','/tæks/','такс','Андоз','🏛️','Everyone must pay income tax.','Ҳама бояд андози даромад супоранд.','noun'),
      W('Fine','/faɪn/','файн','Ҷарима','🚫','He paid a fine for parking illegally.','Ӯ барои таваққуфи ғайриқонунӣ ҷарима пардохт.','noun'),
      W('Inflation','/ɪnˈfleɪʃn/','инфлейшн','Таваррум','🎈','Inflation makes everything more expensive.','Таваррум ҳама чизро гаронтар мекунад.','noun'),
      W('Recession','/rɪˈseʃn/','рисешн','Таназзули иқтисодӣ','📊','Many people lost jobs during the recession.','Дар давраи таназзул бисёр одамон корашонро аз даст доданд.','noun'),
      W('Economy','/ɪˈkɒnəmi/','иконами','Иқтисодиёт','🌐','The country has a growing economy.','Кишвар иқтисодиёти рӯ ба афзоиш дорад.','noun'),
      W('Fortune','/ˈfɔːtʃuːn/','форчун','Сарват / бахт','💎','He made a fortune in business.','Ӯ дар тиҷорат сарват ба даст овард.','noun'),
      W('Wealth','/welθ/','велс','Дороӣ / сарват','🏰','Health is more important than wealth.','Саломатӣ аз сарват муҳимтар аст.','noun'),
      W('Millionaire','/ˌmɪljəˈneə/','милйонер','Миллионер','🤑','She became a millionaire at thirty.','Вай дар сӣсолагӣ миллионер шуд.','noun'),
    ]},
    { title: 'Lesson 4: Spending Habits', tt: 'Дарси 4: Одатҳои харҷ', emoji: '💳', words: [
      W('Spend','/spend/','спенд','Харҷ кардан','💸','Try not to spend too much money.','Кӯшиш кунед, ки пули аз ҳад зиёд харҷ накунед.','verb'),
      W('Fund','/fʌnd/','фанд','Маблағгузорӣ кардан / фонд','🏦','The government will fund the project.','Ҳукумат лоиҳаро маблағгузорӣ мекунад.','verb'),
      W('Value','/ˈvæljuː/','валю','Арзиш','⚖️','This ring has great sentimental value.','Ин ангуштарин арзиши эҳсосии калон дорад.','noun'),
      W('Reward','/rɪˈwɔːd/','ривод','Мукофот','🏅','Loyal customers get a reward.','Муштариёни содиқ мукофот мегиранд.','noun'),
      W('Cashback','/ˈkæʃbæk/','кешбек','Кешбек / баргашти пул','💵','This card gives you cashback on shopping.','Ин корт ба шумо аз харид кешбек медиҳад.','noun'),
      W('Subscription','/səbˈskrɪpʃn/','сабскрипшн','Обунапулӣ','📅','I cancelled my streaming subscription.','Ман обунаи хидмати видеоиро бекор кардам.','noun'),
      W('Membership','/ˈmembəʃɪp/','мембершип','Узвият','🎫','A gym membership costs 100 somoni a month.','Узвияти варзишгоҳ моҳе 100 сомонӣ аст.','noun'),
      W('Stingy','/ˈstɪndʒi/','стинҷи','Хасис','🪙','He is too stingy to buy gifts.','Ӯ он қадар хасис аст, ки тӯҳфа намехарад.','adjective'),
      W('Thrifty','/ˈθrɪfti/','срифти','Сарфакор','🐷','My grandmother is very thrifty.','Бибиям хеле сарфакор аст.','adjective'),
      W('Debit card','/ˈdebɪt kɑːd/','дебит кард','Корти дебетӣ','💳','I paid with my debit card.','Ман бо корти дебетӣ пардохт кардам.','noun'),
    ]},
  ],
  grammar: [
    {
      title: 'Third Conditional', titleTranslated: 'Ҷумлаи шартии сеюм',
      lessonTitle: 'Lesson 5: Third Conditional', lessonTitleTg: 'Дарси 5: Ҷумлаи шартии сеюм', emoji: '⏳',
      explanation: '**Ҷумлаи шартии сеюм** дар бораи гузаштаи ғайривоқеӣ аст — чизе ки нашуд, вале агар мешуд, натиҷа дигар мебуд:\n\n**If + Past Perfect, … would have + феъли сеюм**\n\n- *If I **had studied**, I **would have passed** the exam.* — Агар ман таҳсил мекардам, имтиҳонро месупоридам (вале накардам).\n- *If she **had saved** money, she **would have bought** a car.* — Агар вай пул ҷамъ мекард, мошин мехарид.\n\nБарои афсӯс ё интиқод дар бораи гузашта истифода мешавад.',
      rules: [
        { pattern: 'If + had + V3, would have + V3', note: 'Гузаштаи ғайривоқеӣ ва натиҷаи он.' },
        { pattern: 'could have / might have + V3', note: 'Ба ҷои “would have” низ мумкин аст.' },
      ],
      examples: [
        { sentence: 'If we had left earlier, we would have caught the train.', translation: 'Агар мо барвақттар мебаромадем, ба поезд мерасидем.', highlight: 'would have caught' },
        { sentence: 'If he had asked, I would have helped him.', translation: 'Агар ӯ мепурсид, ман ба ӯ ёрӣ медодам.', highlight: 'would have helped' },
        { sentence: 'She would have won if she had trained harder.', translation: 'Агар вай сахттар машқ мекард, ғолиб мешуд.', highlight: 'had trained' },
      ],
      exercises: [
        { type:'choose', prompt:'If I had known, I ___ you.', promptTranslated:'Агар медонистам, ба ту мегуфтам.', options:['would have told','will tell','told','would tell'], answer:'would have told', explanation:'If + had + V3 → would have + V3.' },
        { type:'choose', prompt:'If they ___ harder, they would have passed.', promptTranslated:'Агар онҳо сахттар кор мекарданд, мегузаштанд.', options:['had worked','worked','have worked','would work'], answer:'had worked', explanation:'Қисми “if” → Past Perfect.' },
        { type:'fill_blank', prompt:'If she had run faster, she would ___ won. (have)', promptTranslated:'Агар вай тезтар медавид, ғолиб мешуд.', answer:'have', explanation:'would + have + V3.' },
        { type:'fill_blank', prompt:'We would have come if you had ___ us. (invite)', promptTranslated:'Агар моро даъват мекардӣ, меомадем.', answer:'invited', explanation:'had + invited (V3).' },
        { type:'transform', prompt:'I / not miss / the bus / if / I / wake up / on time', promptTranslated:'Ҷумлаи шартии сеюм созед.', answer:'I would not have missed the bus if I had woken up on time.', explanation:'would not have missed … had woken up.' },
        { type:'transform', prompt:'If / you / save / money / you / can / buy it', promptTranslated:'Ҷумлаи шартии сеюм созед (could have).', answer:'If you had saved money, you could have bought it.', explanation:'had saved … could have bought.' },
      ],
    },
    {
      title: 'wish (Regrets)', titleTranslated: 'wish (афсӯс)',
      lessonTitle: 'Lesson 6: wish', lessonTitleTg: 'Дарси 6: wish (афсӯс)', emoji: '🌠',
      explanation: '**wish** барои афсӯс ва орзу истифода мешавад:\n\n1. **wish + Past Simple** — афсӯс дар бораи ҳозира: *I **wish** I **had** more money.* — Кош ман пули бештар медоштам.\n2. **wish + Past Perfect** — афсӯс дар бораи гузашта: *I **wish** I **had studied** harder.* — Кош ман сахттар таҳсил мекардам.\n\nБо “wish” ба ҷои “was” одатан **were** истифода мешавад: *I wish I **were** rich.*',
      rules: [
        { pattern: 'wish + Past Simple', note: 'Афсӯс дар бораи вазъи ҳозира.' },
        { pattern: 'wish + Past Perfect', note: 'Афсӯс дар бораи гузашта.' },
        { pattern: 'I wish I were …', note: '“were” барои ҳама шахсҳо.' },
      ],
      examples: [
        { sentence: 'I wish I knew the answer.', translation: 'Кош ман ҷавобро медонистам.', highlight: 'wish I knew' },
        { sentence: 'She wishes she had bought that dress.', translation: 'Вай афсӯс мехӯрад, ки он куртаро нахарид.', highlight: 'had bought' },
        { sentence: 'I wish it weren\'t so expensive.', translation: 'Кош ин қадар гарон намебуд.', highlight: "weren't" },
      ],
      exercises: [
        { type:'choose', prompt:'I wish I ___ more free time.', promptTranslated:'Кош ман вақти озоди бештар медоштам.', options:['had','have','will have','would have'], answer:'had', explanation:'wish + Past Simple (ҳозира).' },
        { type:'choose', prompt:'He wishes he ___ that expensive phone last year.', promptTranslated:'Ӯ афсӯс мехӯрад, ки соли гузашта он телефони гаронро харид.', options:['hadn\'t bought','didn\'t buy','doesn\'t buy','wouldn\'t buy'], answer:'hadn\'t bought', explanation:'Афсӯси гузашта → wish + Past Perfect.' },
        { type:'fill_blank', prompt:'I wish I ___ rich enough to travel. (be)', promptTranslated:'Кош ман он қадар сарватманд мебудам, ки сафар кунам.', answer:'were', explanation:'wish + were.' },
        { type:'fill_blank', prompt:'She wishes she had ___ the money. (save)', promptTranslated:'Вай афсӯс мехӯрад, ки пулро сарфа накард.', answer:'saved', explanation:'wish + had + saved.' },
        { type:'transform', prompt:'I / not have / a car (Кош доштам)', promptTranslated:'Бо “wish + Past Simple” афсӯси ҳозира созед.', answer:'I wish I had a car.', explanation:'wish I had a car.' },
        { type:'transform', prompt:'We / not book / the hotel earlier (афсӯси гузашта)', promptTranslated:'Бо “wish + Past Perfect” созед.', answer:'I wish we had booked the hotel earlier.', explanation:'wish we had booked.' },
      ],
    },
  ],
  listening: {
    lessonTitle: 'Lesson 7: Listening — A Shopping Mistake', lessonTitleTg: 'Дарси 7: Шунавоӣ — Хатои харид',
    title: 'A Shopping Mistake', titleTranslated: 'Хатои харид', emoji: '🎧',
    passage: 'Last month, Karim wanted to buy a new laptop for his studies. He saw one online at a very low price and bought it immediately, without reading the reviews. When the laptop arrived, it was much slower than he had expected, and the battery only lasted one hour. He tried to get a refund, but the seller said the warranty did not cover the problem. Karim was very disappointed. If he had read the reviews first, he would not have wasted his money. He also wished he had bought it from a well-known shop instead of an unknown website. In the end, he had to spend even more to repair it. Now he always checks reviews and compares prices before making a purchase.',
    passageTranslated: 'Моҳи гузашта Карим мехост барои таҳсилаш лаптопи нав харад. Ӯ якеро дар интернет бо нархи хеле паст дид ва фавран, бе хондани шарҳҳо, харид. Вақте лаптоп расид, он аз он чи ӯ интизор дошт хеле сусттар буд ва батарея танҳо як соат кор мекард. Ӯ кӯшиш кард пулро баргардонад, вале фурӯшанда гуфт, ки кафолат ин мушкилиро дар бар намегирад. Карим хеле ноумед шуд. Агар ӯ аввал шарҳҳоро мехонд, пулашро беҳуда сарф намекард. Ҳамчунин афсӯс мехӯрд, ки онро ба ҷои вебсайти номаълум аз мағозаи маъруф нахарид. Дар охир, ӯ маҷбур шуд боз ҳам бештар барои таъмираш харҷ кунад. Ҳоло ӯ ҳамеша пеш аз харид шарҳҳоро тафтиш ва нархҳоро муқоиса мекунад.',
    questions: [
      { question: 'Why did Karim buy the laptop immediately?', questionTranslated: 'Чаро Карим лаптопро фавран харид?', options: ['It had a very low price','It was a famous brand','A friend told him to','It was free'], correctIndex: 0, explanation: '“at a very low price and bought it immediately”.' },
      { question: 'What was wrong with the laptop?', questionTranslated: 'Лаптоп чӣ айб дошт?', options: ['It was slow and the battery was weak','It was too big','It had no screen','It was the wrong colour'], correctIndex: 0, explanation: 'slower than expected, battery one hour.' },
      { question: 'Why couldn\'t he get a refund?', questionTranslated: 'Чаро ӯ пулро баргардонида натавонист?', options: ['The warranty did not cover the problem','He lost the receipt','The shop closed','He waited too long'], correctIndex: 0, explanation: '“warranty did not cover the problem”.' },
      { question: 'What would have happened if he had read the reviews?', questionTranslated: 'Агар ӯ шарҳҳоро мехонд, чӣ мешуд?', options: ['He would not have wasted his money','He would have bought two','Nothing would change','He would have paid more'], correctIndex: 0, explanation: 'third conditional in the text.' },
      { question: 'What does Karim always do now?', questionTranslated: 'Карим ҳоло ҳамеша чӣ мекунад?', options: ['Checks reviews and compares prices','Buys the cheapest option','Avoids online shops','Never buys laptops'], correctIndex: 0, explanation: 'last sentence.' },
    ],
  },
  dialogue: {
    lessonTitle: 'Lesson 8: Speaking — Returning an Item', lessonTitleTg: 'Дарси 8: Гуфтугӯ — Баргардонидани мол',
    title: 'Returning an Item', titleTranslated: 'Баргардонидани мол', scenario: 'A customer returns a faulty jacket to a shop.', emoji: '🧥',
    lines: [
      { speaker: 'Assistant', text: 'Hello, how can I help you today?', translation: 'Салом, имрӯз чӣ гуна кӯмак карда метавонам?', isUser: false },
      { speaker: 'Customer', text: 'I would like to return this jacket. The zip is broken.', translation: 'Ман мехоҳам ин куртаро баргардонам. Занҷираш вайрон аст.', isUser: true },
      { speaker: 'Assistant', text: 'I see. Do you have the receipt?', translation: 'Фаҳмидам. Чек доред?', isUser: false },
      { speaker: 'Customer', text: 'Yes, here it is. I bought it last week.', translation: 'Ҳа, ана он. Ман онро ҳафтаи гузашта харидам.', isUser: true },
      { speaker: 'Assistant', text: 'Would you like a refund or an exchange?', translation: 'Пасгардонии пул мехоҳед ё иваз кардан?', isUser: false },
      { speaker: 'Customer', text: 'A refund, please. Can I get it on my card?', translation: 'Пасгардонии пул, лутфан. Ба кортам гирифта метавонам?', isUser: true },
      { speaker: 'Assistant', text: 'Of course. It will go back to your debit card.', translation: 'Албатта. Он ба корти дебетии шумо бармегардад.', isUser: false },
      { speaker: 'Customer', text: 'How long will the refund take?', translation: 'Пасгардонии пул чанд вақт мегирад?', isUser: true },
      { speaker: 'Assistant', text: 'Usually three to five working days.', translation: 'Одатан се то панҷ рӯзи корӣ.', isUser: false },
    ],
  },
  reading: {
    lessonTitle: 'Lesson 9: Reading — Saving Money', lessonTitleTg: 'Дарси 9: Хониш — Сарфаи пул',
    title: 'Smart Ways to Save Money', titleTranslated: 'Роҳҳои зиракона барои сарфаи пул', emoji: '📖',
    passage: 'Many people find it difficult to save money, but a few simple habits can make a big difference. The first step is to make a budget so that you know exactly how much you earn and how much you spend each month. Experts advise saving a small amount every month, even if it is only a little. It also helps to compare prices before you buy something expensive, and to avoid paying for subscriptions you never use. Buying second-hand items or waiting for a sale can save a lot over time. Finally, try to pay with cash instead of a card, because people usually spend more when they cannot see the money leaving their hands. With patience and good habits, almost anyone can build up their savings.',
    passageTranslated: 'Бисёр одамон сарфаи пулро душвор меёбанд, вале чанд одати содда метавонанд фарқияти калон эҷод кунанд. Қадами аввал сохтани буҷа аст, то шумо дақиқ донед, ки ҳар моҳ чӣ қадар даромад мекунед ва чӣ қадар харҷ мекунед. Коршиносон маслиҳат медиҳанд, ки ҳар моҳ маблағи ками пул сарфа кунед, ҳатто агар он кам бошад. Ҳамчунин пеш аз харидани чизи гарон муқоисаи нархҳо ва канорагирӣ аз пардохти обунаҳое, ки ҳеҷ гоҳ истифода намебаред, кӯмак мекунад. Харидани ашёи дастдуюм ё интизори тахфиф бо мурури замон бисёр пулро сарфа мекунад. Ниҳоят, кӯшиш кунед, ки бо нақд пардохт кунед, на бо корт, зеро одамон одатан вақте пулро аз даст рафтанашро намебинанд, бештар харҷ мекунанд. Бо сабр ва одатҳои хуб, қариб ҳар кас метавонад пасандозашро зиёд кунад.',
    questions: [
      { question: 'What is the first step to saving money?', questionTranslated: 'Қадами аввали сарфаи пул чист?', options: ['Making a budget','Buying a new phone','Getting a loan','Spending more'], correctIndex: 0, explanation: '“make a budget”.' },
      { question: 'How much should you save every month?', questionTranslated: 'Ҳар моҳ чӣ қадар сарфа кардан лозим аст?', options: ['A small amount, even a little','Nothing','All your salary','Half of everything'], correctIndex: 0, explanation: '“saving a small amount every month”.' },
      { question: 'What can save a lot over time?', questionTranslated: 'Чӣ бо мурури замон бисёр сарфа мекунад?', options: ['Buying second-hand or waiting for a sale','Paying full price','Using many subscriptions','Shopping every day'], correctIndex: 0, explanation: 'second-hand items or waiting for a sale.' },
      { question: 'Why is paying with cash suggested?', questionTranslated: 'Чаро пардохт бо нақд пешниҳод мешавад?', options: ['People spend more with a card','Cash is prettier','Cards are illegal','Cash gives cashback'], correctIndex: 0, explanation: 'people spend more when they can\'t see the money leaving.' },
      { question: 'What does saving money require?', questionTranslated: 'Сарфаи пул чӣ талаб мекунад?', options: ['Patience and good habits','A high salary','Good luck','A credit card'], correctIndex: 0, explanation: '“With patience and good habits”.' },
    ],
  },
  review: {
    passage: 'Being good with money is a skill. If you make a budget, compare prices, and avoid unnecessary expenses, you can save for the future. Many people wish they had started saving earlier, so it is best to begin today.',
    passageTranslated: 'Хуб идора кардани пул як маҳорат аст. Агар шумо буҷа созед, нархҳоро муқоиса кунед ва аз хароҷоти нолозим худдорӣ кунед, метавонед барои оянда сарфа кунед. Бисёр одамон афсӯс мехӯранд, ки барвақттар сарфаро сар накарданд, бинобар ин беҳтараш имрӯз оғоз кунед.',
    questions: [
      { question: 'Which word means “хароҷот”?', questionTranslated: 'Кадом калима маънои “хароҷот”-ро дорад?', options: ['Expense','Profit','Reward','Warranty'], correctIndex: 0, explanation: 'expense = хароҷот.' },
      { question: 'Complete: “If I had saved more, I ___ have bought a house.”', questionTranslated: 'Пур кунед: Агар бештар сарфа мекардам, хона мехаридам.', options: ['would','will','can','am'], correctIndex: 0, explanation: 'Third conditional: would have.' },
      { question: 'Choose the correct wish sentence.', questionTranslated: 'Ҷумлаи дурусти “wish”-ро интихоб кунед.', options: ['I wish I had more money.','I wish I have more money.','I wish I will have more money.','I wish I am having money.'], correctIndex: 0, explanation: 'wish + Past Simple.' },
      { question: 'What does “thrifty” mean?', questionTranslated: '“Thrifty” чӣ маъно дорад?', options: ['Careful with money','Very rich','Very lazy','Very generous'], correctIndex: 0, explanation: 'thrifty = сарфакор.' },
      { question: 'A tax is money you pay to…', questionTranslated: 'Андоз пулест, ки шумо ба … месупоред.', options: ['the government','a shop','a friend','a bank card'], correctIndex: 0, explanation: 'tax = андоз (ба давлат).' },
    ],
  },
  exam: {
    passage: 'This exam reviews Module 7: money and shopping vocabulary, the Third Conditional, and the structure “wish”. Read each question carefully and choose the best answer.',
    passageTranslated: 'Ин имтиҳон Модули 7-ро такрор мекунад: луғати пул ва харид, ҷумлаи шартии сеюм ва сохтори “wish”. Ҳар саволро бодиққат хонед ва беҳтарин ҷавобро интихоб кунед.',
    questions: [
      { question: 'If we had booked earlier, the tickets ___ cheaper.', questionTranslated: 'Агар барвақттар банд мекардем, чиптаҳо арзонтар мешуданд.', options: ['would have been','will be','were','are'], correctIndex: 0, explanation: 'Third conditional: would have been.' },
      { question: 'I wish I ___ how to invest money.', questionTranslated: 'Кош ман медонистам, ки чӣ гуна пулро сармоягузорӣ кунам.', options: ['knew','know','will know','have known'], correctIndex: 0, explanation: 'wish + Past Simple: knew.' },
      { question: 'Which word means “кафолат”?', questionTranslated: 'Кадом калима маънои “кафолат”-ро дорад?', options: ['Warranty','Aisle','Fortune','Recession'], correctIndex: 0, explanation: 'warranty = кафолат.' },
      { question: 'Money you pay back monthly for a house is a…', questionTranslated: 'Пуле, ки барои хона ҳар моҳ бармегардонед…', options: ['mortgage','coupon','profit','fine'], correctIndex: 0, explanation: 'mortgage = ипотека.' },
      { question: 'Choose the correct sentence.', questionTranslated: 'Ҷумлаи дурустро интихоб кунед.', options: ['If she had asked, I would have helped.','If she asked, I would have helped.','If she had asked, I would helped.','If she has asked, I would have helped.'], correctIndex: 0, explanation: 'had asked + would have helped.' },
    ],
  },
};
