import { W } from './b1-api-build.mjs';

export const M = {
  order: 5, title: 'Module 5: Health and Lifestyle', titleTranslated: 'Модули 5: Саломатӣ ва Тарзи ҳаёт',
  emoji: '🩺', color: '#EF4444',
  vocab: [
    { title: 'Lesson 1: Symptoms', tt: 'Дарси 1: Аломатҳои беморӣ', emoji: '🤒', words: [
      W('Symptom','/ˈsɪmptəm/','симптом','Аломати беморӣ','🤒','A high fever is a common symptom of flu.','Табларзаи баланд аломати маъмули зуком аст.','noun'),
      W('Rash','/ræʃ/','раш','Доғи пӯст','🔴','The rash on his arm was very itchy.','Доғи дасташ хеле хориш дошт.','noun'),
      W('Swollen','/ˈswəʊlən/','своулен','Варамкарда','🦶','His ankle was swollen after the fall.','Баъди афтидан пойаш варам карда буд.','adjective'),
      W('Infection','/ɪnˈfekʃn/','инфекшн','Сироят','🦠','The doctor said it was a minor infection.','Духтур гуфт, ки ин сирояти сабук аст.','noun'),
      W('Nausea','/ˈnɔːziə/','нозиа','Дилбеҳузурӣ','🤢','The medicine can cause nausea.','Дору метавонад дилбеҳузурӣ орад.','noun'),
      W('Dizziness','/ˈdɪzinəs/','дизинес','Сарчархзанӣ','💫','Dizziness is a common sign of low blood sugar.','Сарчархзанӣ аломати маъмули пастии қанди хун аст.','noun'),
      W('Faint','/feɪnt/','фейнт','Беҳуш шудан','😵','She felt so weak that she nearly fainted.','Вай он қадар заиф буд, ки қариб беҳуш шуд.','verb'),
      W('Fatigue','/fəˈtiːɡ/','фатииг','Хастагии шадид','😩','He felt constant fatigue after the illness.','Баъди беморӣ ӯ хастагии доимӣ ҳис мекард.','noun'),
      W('Swelling','/ˈswelɪŋ/','свелинг','Варам','🩹','Ice can reduce the swelling.','Ях метавонад варамро кам кунад.','noun'),
      W('Heal','/hiːl/','ҳиил','Шифо ёфтан','🌱','The cut will heal in a few days.','Захм дар чанд рӯз шифо меёбад.','verb'),
    ]},
    { title: 'Lesson 2: Treatment', tt: 'Дарси 2: Табобат', emoji: '💊', words: [
      W('Painkiller','/ˈpeɪnkɪlə/','пейнкилер','Дарддур','💊','I took a painkiller for my headache.','Ман барои дарди сар дарддур гирифтам.','noun'),
      W('Surgery','/ˈsɜːdʒəri/','сёрҷери','Ҷарроҳӣ','🔪','He needs surgery on his knee.','Ба зонуяш ҷарроҳӣ лозим аст.','noun'),
      W('Diagnosis','/ˌdaɪəɡˈnəʊsɪs/','дайагноусис','Ташхис','🔬','The doctor made a quick diagnosis.','Духтур зуд ташхис гузошт.','noun'),
      W('Therapy','/ˈθerəpi/','терапи','Терапия / муолиҷа','🧑‍⚕️','Physical therapy helped him walk again.','Терапияи ҷисмонӣ ба ӯ ёрӣ дод, ки боз роҳ равад.','noun'),
      W('Vaccine','/ˈvæksiːn/','ваксиин','Ваксина / эмгузаронӣ','💉','The vaccine protects against the virus.','Ваксина аз вирус ҳифз мекунад.','noun'),
      W('Antibiotic','/ˌæntibaɪˈɒtɪk/','антибиотик','Антибиотик','🧫','Antibiotics do not work against colds.','Антибиотикҳо бар зидди шамолхӯрӣ кор намекунанд.','noun'),
      W('Remedy','/ˈremədi/','ремеди','Табобат / чора','🍵','Honey is a natural remedy for a sore throat.','Асал табобати табиии дарди гулӯ аст.','noun'),
      W('Recovery','/rɪˈkʌvəri/','рикавери','Сиҳатшавӣ / барқароршавӣ','💪','Rest is important for a full recovery.','Истироҳат барои сиҳатшавии пурра муҳим аст.','noun'),
      W('Check-up','/ˈtʃek ʌp/','чек ап','Муоинаи тиббӣ','🩺','I go for a check-up once a year.','Ман соле як бор ба муоинаи тиббӣ меравам.','noun'),
      W('Immunity','/ɪˈmjuːnəti/','имюнити','Масуният','🛡️','Good sleep strengthens your immunity.','Хоби хуб масуниятро мустаҳкам мекунад.','noun'),
    ]},
    { title: 'Lesson 3: Healthy Living', tt: 'Дарси 3: Ҳаёти солим', emoji: '🥗', words: [
      W('Balanced diet','/ˈbælənst ˈdaɪət/','балансд дайет','Ғизои мутавозин','🍽️','A balanced diet includes fruit and vegetables.','Ғизои мутавозин меваю сабзавотро дар бар мегирад.','noun'),
      W('Workout','/ˈwɜːkaʊt/','вёркаут','Машқи варзишӣ','🏋️','I do a short workout every morning.','Ман ҳар субҳ машқи кӯтоҳи варзишӣ мекунам.','noun'),
      W('Calorie','/ˈkæləri/','калорӣ','Калория','🔥','This meal has too many calories.','Ин таом калорияи аз ҳад зиёд дорад.','noun'),
      W('Protein','/ˈprəʊtiːn/','протеин','Сафеда','🍗','Eggs are a great source of protein.','Тухм манбаи хуби сафеда аст.','noun'),
      W('Hydration','/haɪˈdreɪʃn/','ҳайдрейшн','Обнӯшӣ','💧','Hydration is important during exercise.','Обнӯшӣ ҳангоми варзиш муҳим аст.','noun'),
      W('Portion','/ˈpɔːʃn/','поршн','Ҳисса / порсия','🍛','Try to eat smaller portions.','Кӯшиш кунед, ки ҳиссаҳои хурдтар хӯред.','noun'),
      W('Fibre','/ˈfaɪbə/','файбер','Нахи ғизоӣ','🌾','Whole grains are high in fibre.','Ғаллаи пурра нахи зиёд дорад.','noun'),
      W('Nutrient','/ˈnjuːtriənt/','нютриент','Моддаи ғизоӣ','🥦','Vegetables are full of important nutrients.','Сабзавот пур аз моддаҳои муҳими ғизоист.','noun'),
      W('Stamina','/ˈstæmɪnə/','стамина','Тобоварӣ','🏃','Running builds your stamina.','Давидан тобовариро зиёд мекунад.','noun'),
      W('Endurance','/ɪnˈdjʊərəns/','индюренс','Устуворӣ / чидамнокӣ','⛰️','Cycling improves your endurance.','Дучархаронӣ чидамнокиро беҳтар мекунад.','noun'),
    ]},
    { title: 'Lesson 4: Wellbeing', tt: 'Дарси 4: Некӯаҳволӣ', emoji: '🧘', words: [
      W('Anxiety','/æŋˈzaɪəti/','ангзайети','Изтироб','😰','She feels a lot of anxiety before exams.','Вай пеш аз имтиҳонҳо изтироби зиёд ҳис мекунад.','noun'),
      W('Mood','/muːd/','муд','Кайфият','🙂','A good sleep improves my mood.','Хоби хуб кайфияти маро беҳтар мекунад.','noun'),
      W('Mindfulness','/ˈmaɪndfəlnəs/','майндфулнес','Ҳушёрии зеҳнӣ','🧠','Mindfulness helps her stay calm.','Ҳушёрии зеҳнӣ ба вай ёрӣ мекунад, ки ором монад.','noun'),
      W('Burnout','/ˈbɜːnaʊt/','бёрнаут','Хастагии шадид','🥵','He suffered burnout from overworking.','Вай аз кори аз ҳад хастагии шадид кашид.','noun'),
      W('Lifestyle','/ˈlaɪfstaɪl/','лайфстайл','Тарзи ҳаёт','🌿','They live a healthy lifestyle.','Онҳо тарзи ҳаёти солим доранд.','noun'),
      W('Wellness','/ˈwelnəs/','велнес','Саломатӣ / некӯаҳволӣ','🌸','The company has a wellness programme.','Ширкат барномаи саломатӣ дорад.','noun'),
      W('Mindset','/ˈmaɪndset/','майндсет','Тарзи тафаккур','💭','A positive mindset helps you succeed.','Тарзи тафаккури мусбат ба муваффақият ёрӣ мекунад.','noun'),
      W('Tension','/ˈtenʃn/','теншн','Шиддати асаб','😣','Deep breathing releases tension.','Нафаскашии амиқ шиддатро коҳиш медиҳад.','noun'),
      W('Unwind','/ˌʌnˈwaɪnd/','анвайнд','Ором гирифтан','🛀','I unwind by reading a book.','Ман бо хондани китоб ором мегирам.','verb'),
      W('Willpower','/ˈwɪlpaʊə/','вилпауер','Иродаи қавӣ','💪','Losing weight takes willpower.','Кам кардани вазн иродаи қавӣ мехоҳад.','noun'),
    ]},
  ],
  grammar: [
    {
      title: 'Present Perfect Continuous', titleTranslated: 'Замони ҳозираи мукаммали давомдор',
      lessonTitle: 'Lesson 5: Present Perfect Continuous', lessonTitleTg: 'Дарси 5: Present Perfect Continuous', emoji: '⏳',
      explanation: '**Present Perfect Continuous** амалеро нишон медиҳад, ки дар гузашта сар шуда, то ҳозир давом дорад (ё навакак тамом шуд ва натиҷааш дида мешавад):\n\n**have / has + been + феъл + -ing**\n\n- *I **have been studying** for three hours.* — Ман се соат боз таҳсил карда истодаам.\n- *She **has been working** here since 2020.* — Вай аз соли 2020 инҷо кор карда истодааст.\n\nБо **for** (муддат) ва **since** (нуқтаи оғоз) истифода мешавад. Диққат ба давомнокӣ ва раванд, на натиҷаи ниҳоӣ.',
      rules: [
        { pattern: 'have/has + been + V-ing', note: 'Амали давомдор аз гузашта то ҳозир.' },
        { pattern: 'for + муддат / since + нуқтаи оғоз', note: '“for two hours”, “since Monday”.' },
      ],
      examples: [
        { sentence: 'It has been raining all day.', translation: 'Тамоми рӯз борон борида истодааст.', highlight: 'has been raining' },
        { sentence: 'They have been living here for ten years.', translation: 'Онҳо даҳ сол боз инҷо зиндагӣ карда истодаанд.', highlight: 'have been living' },
        { sentence: 'Why are you tired? I have been running.', translation: 'Чаро монда шудаӣ? Ман давида истодаам.', highlight: 'have been running' },
      ],
      exercises: [
        { type:'choose', prompt:'I ___ for the exam since morning.', promptTranslated:'Ман аз субҳ барои имтиҳон омода шуда истодаам.', options:['have been studying','study','studied','am studying'], answer:'have been studying', explanation:'“since morning” → Present Perfect Continuous.' },
        { type:'choose', prompt:'She ___ tennis for two hours.', promptTranslated:'Вай ду соат боз теннис бозӣ карда истодааст.', options:['has been playing','plays','played','is playing'], answer:'has been playing', explanation:'“for two hours” + давомнокӣ.' },
        { type:'fill_blank', prompt:'We have ___ waiting for the bus for 20 minutes. (be)', promptTranslated:'Мо 20 дақиқа боз мунтазири автобус ҳастем.', answer:'been', explanation:'have + been + V-ing.' },
        { type:'fill_blank', prompt:'He has been ___ the guitar since he was ten. (play)', promptTranslated:'Вай аз даҳсолагӣ гитара навохта истодааст.', answer:'playing', explanation:'been + V-ing.' },
        { type:'transform', prompt:'It / rain / all morning', promptTranslated:'Ин ҷумларо бо Present Perfect Continuous созед.', answer:'It has been raining all morning.', explanation:'has + been + raining.' },
        { type:'transform', prompt:'They / work / here / since 2019', promptTranslated:'Ин ҷумларо бо Present Perfect Continuous созед.', answer:'They have been working here since 2019.', explanation:'have + been + working.' },
      ],
    },
    {
      title: 'Past Perfect', titleTranslated: 'Замони гузаштаи мукаммал',
      lessonTitle: 'Lesson 6: Past Perfect', lessonTitleTg: 'Дарси 6: Past Perfect', emoji: '⏮️',
      explanation: '**Past Perfect** амалеро нишон медиҳад, ки **пеш аз** амали дигари гузашта рӯй дод:\n\n**had + феъли сеюм (past participle)**\n\n- *When I arrived, the train **had** already **left**.* — Вақте ки ман расидам, поезд аллакай рафта буд.\n- *She **had finished** her work before dinner.* — Вай пеш аз хӯроки шом кораш­ро тамом карда буд.\n\nБаробари Past Simple истифода мешавад, то тартиби ду амали гузаштаро нишон диҳад: аввал Past Perfect, баъд Past Simple.',
      rules: [
        { pattern: 'had + past participle', note: 'Амали пеш аз амали дигари гузашта.' },
        { pattern: 'Past Perfect (аввал) + Past Simple (баъд)', note: '“had left” пеш аз “arrived”.' },
      ],
      examples: [
        { sentence: 'The film had already started when we arrived.', translation: 'Вақте ки мо расидем, филм аллакай сар шуда буд.', highlight: 'had already started' },
        { sentence: 'I had never seen snow before I moved here.', translation: 'То ба ин ҷо кӯчиданам ман ҳеҷ гоҳ барфро надида будам.', highlight: 'had never seen' },
        { sentence: 'They had eaten before the guests came.', translation: 'Онҳо пеш аз омадани меҳмонон хӯрок хӯрда буданд.', highlight: 'had eaten' },
      ],
      exercises: [
        { type:'choose', prompt:'When we got to the station, the train ___.', promptTranslated:'Вақте ба истгоҳ расидем, поезд рафта буд.', options:['had left','leaves','was leaving','has left'], answer:'had left', explanation:'Амали пештар → Past Perfect.' },
        { type:'choose', prompt:'She ___ her keys, so she could not open the door.', promptTranslated:'Вай калидҳояшро гум карда буд, барои ҳамин дарро кушода натавонист.', options:['had lost','lost','loses','has lost'], answer:'had lost', explanation:'Сабаб пеш аз натиҷаи гузашта.' },
        { type:'fill_blank', prompt:'By the time I called, he had already ___. (leave)', promptTranslated:'Вақте занг задам, вай аллакай рафта буд.', answer:'left', explanation:'had + past participle (left).' },
        { type:'fill_blank', prompt:'I could not pay because I had ___ my wallet at home. (forget)', promptTranslated:'Пардохт карда натавонистам, чун ҳамёнамро дар хона фаромӯш карда будам.', answer:'forgotten', explanation:'past participle of forget = forgotten.' },
        { type:'transform', prompt:'The rain / stop / before we / go out', promptTranslated:'Бо Past Perfect + Past Simple созед.', answer:'The rain had stopped before we went out.', explanation:'had stopped (аввал) + went (баъд).' },
        { type:'transform', prompt:'She / never / travel / abroad / before that trip', promptTranslated:'Бо Past Perfect созед.', answer:'She had never travelled abroad before that trip.', explanation:'had never travelled.' },
      ],
    },
  ],
  listening: {
    lessonTitle: 'Lesson 7: Listening — A Visit to the Doctor', lessonTitleTg: 'Дарси 7: Шунавоӣ — Ташриф ба духтур',
    title: 'A Visit to the Doctor', titleTranslated: 'Ташриф ба духтур', emoji: '🎧',
    passage: 'Last week Omar had been feeling tired for several days, so he made an appointment with his doctor. He explained that he had a sore throat, a bad cough, and a slight fever. The doctor examined him carefully and said it was a minor infection, not something serious. She wrote a prescription for some medicine and told him to rest, drink plenty of water, and stay warm. She also advised him to eat a balanced diet and to avoid stress at work. Omar felt relieved. He had been worried that it was something worse. After three days of rest, he had almost fully recovered and was able to return to work.',
    passageTranslated: 'Ҳафтаи гузашта Умар чанд рӯз боз худро хаста ҳис мекард, бинобар ин бо духтураш вохӯрӣ таъин кард. Ӯ фаҳмонд, ки дарди гулӯ, сулфаи сахт ва каме табларза дорад. Духтур ӯро бодиққат муоина кард ва гуфт, ки ин сирояти сабук аст, на чизи ҷиддӣ. Вай доруномае навишт ва ба ӯ гуфт, ки истироҳат кунад, оби зиёд нӯшад ва гарм монад. Ҳамчунин маслиҳат дод, ки ғизои мутавозин хӯрад ва аз фишори равонӣ дар кор канорагирӣ кунад. Умар осуда шуд. Ӯ нигарон буд, ки ин чизи бадтар аст. Баъди се рӯзи истироҳат ӯ қариб пурра сиҳат шуд ва тавонист ба кор баргардад.',
    questions: [
      { question: 'How long had Omar been feeling tired?', questionTranslated: 'Умар чанд вақт боз худро хаста ҳис мекард?', options: ['For several days','For a month','For one hour','For a year'], correctIndex: 0, explanation: '“had been feeling tired for several days”.' },
      { question: 'What did the doctor say the problem was?', questionTranslated: 'Духтур гуфт, ки мушкилӣ чист?', options: ['A minor infection','A broken leg','Nothing at all','A serious disease'], correctIndex: 0, explanation: '“it was a minor infection”.' },
      { question: 'What did the doctor tell him to drink?', questionTranslated: 'Духтур ба ӯ гуфт, ки чӣ нӯшад?', options: ['Plenty of water','Coffee','Juice only','Nothing'], correctIndex: 0, explanation: '“drink plenty of water”.' },
      { question: 'Why had Omar been worried?', questionTranslated: 'Чаро Умар нигарон буд?', options: ['He thought it was something worse','He had lost his job','He had no money','He had missed a flight'], correctIndex: 0, explanation: '“worried that it was something worse”.' },
      { question: 'How did he feel after three days?', questionTranslated: 'Баъди се рӯз ӯ чӣ гуна ҳис кард?', options: ['Almost fully recovered','Much worse','Still very ill','The same'], correctIndex: 0, explanation: '“had almost fully recovered”.' },
    ],
  },
  dialogue: {
    lessonTitle: 'Lesson 8: Speaking — At the Pharmacy', lessonTitleTg: 'Дарси 8: Гуфтугӯ — Дар дорухона',
    title: 'At the Pharmacy', titleTranslated: 'Дар дорухона', scenario: 'A customer asks the pharmacist for help with cold symptoms.', emoji: '💊',
    lines: [
      { speaker: 'Pharmacist', text: 'Good morning. How can I help you?', translation: 'Субҳ ба хайр. Чӣ гуна кӯмак карда метавонам?', isUser: false },
      { speaker: 'Customer', text: 'I have had a cough and a sore throat for three days.', translation: 'Ман се рӯз боз сулфа ва дарди гулӯ дорам.', isUser: true },
      { speaker: 'Pharmacist', text: 'Do you have a fever as well?', translation: 'Табларза ҳам доред?', isUser: false },
      { speaker: 'Customer', text: 'A slight one. What do you recommend?', translation: 'Каме. Шумо чиро тавсия медиҳед?', isUser: true },
      { speaker: 'Pharmacist', text: 'Take this syrup twice a day and drink warm water.', translation: 'Ин шарбатро рӯзе ду бор гиред ва оби гарм нӯшед.', isUser: false },
      { speaker: 'Customer', text: 'Do I need a prescription for it?', translation: 'Барои он ба ман дорунома лозим аст?', isUser: true },
      { speaker: 'Pharmacist', text: 'No, it is available without one.', translation: 'Не, он бе дорунома дастрас аст.', isUser: false },
      { speaker: 'Customer', text: 'Great. How much is it?', translation: 'Хуб. Он чанд пул аст?', isUser: true },
      { speaker: 'Pharmacist', text: 'It is twelve somoni. Get well soon!', translation: 'Дувоздаҳ сомонӣ. Зуд сиҳат шавед!', isUser: false },
    ],
  },
  reading: {
    lessonTitle: 'Lesson 9: Reading — Why Sleep Matters', lessonTitleTg: 'Дарси 9: Хониш — Чаро хоб муҳим аст',
    title: 'Why Sleep Matters', titleTranslated: 'Чаро хоб муҳим аст', emoji: '📖',
    passage: 'Many people do not realise how important sleep is for their health. Doctors recommend that adults get between seven and nine hours of sleep each night. When we sleep, the body repairs itself and the brain stores new information. People who have not been sleeping well often feel tired, find it hard to concentrate, and are in a bad mood. Over time, poor sleep can increase stress and even lead to serious health problems. Experts suggest simple habits: going to bed at the same time every night, avoiding screens before bed, and keeping the bedroom dark and quiet. By making these small changes, most people can improve both their sleep and their general wellbeing.',
    passageTranslated: 'Бисёр одамон намедонанд, ки хоб барои саломатии онҳо чӣ қадар муҳим аст. Духтурон тавсия медиҳанд, ки калонсолон ҳар шаб байни ҳафт то нӯҳ соат хоб кунанд. Вақте ки мо хоб мекунем, ҷисм худро таъмир мекунад ва мағзи сар маълумоти навро нигоҳ медорад. Одамоне, ки хуб хоб накарда истодаанд, аксар хаста ҳис мекунанд, тамаркуз кардан барояшон душвор аст ва кайфияти бад доранд. Бо мурури замон, хоби бад метавонад фишори равониро зиёд кунад ва ҳатто ба мушкилоти ҷиддии саломатӣ оварда расонад. Коршиносон одатҳои соддаро пешниҳод мекунанд: ҳар шаб дар як вақт хоб рафтан, пеш аз хоб аз экранҳо канорагирӣ кардан ва хонаи хобро торику ором нигоҳ доштан. Бо ин тағйироти хурд, аксари одамон метавонанд ҳам хоб ва ҳам некӯаҳволии умумии худро беҳтар кунанд.',
    questions: [
      { question: 'How many hours of sleep do doctors recommend for adults?', questionTranslated: 'Духтурон барои калонсолон чанд соат хоб тавсия медиҳанд?', options: ['Seven to nine hours','Three to four hours','Ten to twelve hours','Five hours'], correctIndex: 0, explanation: '“between seven and nine hours”.' },
      { question: 'What does the brain do during sleep?', questionTranslated: 'Мағзи сар ҳангоми хоб чӣ мекунад?', options: ['Stores new information','Stops completely','Grows bigger','Forgets everything'], correctIndex: 0, explanation: '“the brain stores new information”.' },
      { question: 'What is one effect of poor sleep?', questionTranslated: 'Як таъсири хоби бад чист?', options: ['A bad mood','Better memory','More energy','Stronger muscles'], correctIndex: 0, explanation: '“are in a bad mood”.' },
      { question: 'What do experts suggest avoiding before bed?', questionTranslated: 'Коршиносон пеш аз хоб аз чӣ канорагириро пешниҳод мекунанд?', options: ['Screens','Warm water','Dark rooms','Sleep'], correctIndex: 0, explanation: '“avoiding screens before bed”.' },
      { question: 'What can small changes improve?', questionTranslated: 'Тағйироти хурд чиро беҳтар карда метавонанд?', options: ['Sleep and wellbeing','Only weight','Only mood','Nothing'], correctIndex: 0, explanation: '“improve both their sleep and their general wellbeing”.' },
    ],
  },
  review: {
    passage: 'Health is not only about medicine and treatment. A balanced diet, regular exercise, good sleep, and low stress all work together. If you have been feeling tired or anxious, small changes to your daily habits can make a big difference to your wellbeing.',
    passageTranslated: 'Саломатӣ танҳо дар бораи дору ва табобат нест. Ғизои мутавозин, варзиши мунтазам, хоби хуб ва фишори кам ҳама якҷоя амал мекунанд. Агар шумо хаста ё мушавваш ҳис карда истода бошед, тағйироти хурд дар одатҳои ҳаррӯза метавонанд ба некӯаҳволии шумо таъсири калон расонанд.',
    questions: [
      { question: 'Which word means “сиҳат шудан”?', questionTranslated: 'Кадом калима маънои “сиҳат шудан”-ро дорад?', options: ['Recover','Sneeze','Portion','Habit'], correctIndex: 0, explanation: 'recover = сиҳат шудан.' },
      { question: 'Choose the correct sentence.', questionTranslated: 'Ҷумлаи дурустро интихоб кунед.', options: ['I have been feeling tired lately.','I have been feel tired lately.','I has been feeling tired lately.','I been feeling tired lately.'], correctIndex: 0, explanation: 'have + been + feeling.' },
      { question: 'What is a “prescription”?', questionTranslated: '“Prescription” чист?', options: ['A doctor’s written order for medicine','A type of food','A sport','A feeling'], correctIndex: 0, explanation: 'prescription = дорунома.' },
      { question: 'Complete: When I arrived, the doctor ___ already gone home.', questionTranslated: 'Пур кунед: Вақте расидам, духтур аллакай ба хона рафта буд.', options: ['had','has','have','was'], correctIndex: 0, explanation: 'Past Perfect: had gone.' },
      { question: 'Which is a healthy habit?', questionTranslated: 'Кадомаш одати солим аст?', options: ['Eating a balanced diet','Skipping sleep','Ignoring symptoms','High stress'], correctIndex: 0, explanation: 'balanced diet = одати солим.' },
    ],
  },
  exam: {
    passage: 'This exam reviews Module 5: vocabulary about health and lifestyle, the Present Perfect Continuous, and the Past Perfect. Read each question carefully and choose the best answer.',
    passageTranslated: 'Ин имтиҳон Модули 5-ро такрор мекунад: луғати саломатӣ ва тарзи ҳаёт, Present Perfect Continuous ва Past Perfect. Ҳар саволро бодиққат хонед ва беҳтарин ҷавобро интихоб кунед.',
    questions: [
      { question: 'She ___ here since 8 a.m.', questionTranslated: 'Вай аз соати 8-и субҳ инҷо кор карда истодааст.', options: ['has been working','works','worked','is work'], correctIndex: 0, explanation: 'since + Present Perfect Continuous.' },
      { question: 'By the time help arrived, he ___ the fire himself.', questionTranslated: 'То расидани кӯмак, ӯ оташро худаш хомӯш карда буд.', options: ['had put out','puts out','has put out','was putting out'], correctIndex: 0, explanation: 'Past Perfect: had put out.' },
      { question: 'Which word means “изтироб”?', questionTranslated: 'Кадом калима маънои “изтироб”-ро дорад?', options: ['Anxiety','Portion','Bandage','Fitness'], correctIndex: 0, explanation: 'anxiety = изтироб.' },
      { question: 'You take this when you have pain.', questionTranslated: 'Инро вақте мегиред, ки дард доред.', options: ['Painkiller','Calorie','Mood','Wound'], correctIndex: 0, explanation: 'painkiller = дарддур.' },
      { question: 'Choose the correct sentence.', questionTranslated: 'Ҷумлаи дурустро интихоб кунед.', options: ['I had never seen the sea before that day.','I have never see the sea before that day.','I had never saw the sea before that day.','I never seen the sea before that day.'], correctIndex: 0, explanation: 'had + never + seen (past participle).' },
    ],
  },
};
