// Step 1 — Listening content for A1 (en→tg). One listening comprehension per
// module that lacks one. A1 level: present simple, short sentences, module theme.
// Each: English passage (transcript) + Tajik translation + 4 MC questions.

export const LISTENINGS = [
  {
    moduleOrder: 0,
    lessonTitle: 'Listening: Meeting People',
    lessonTitleTg: 'Шунавоӣ: Шиносоӣ',
    compEmoji: '👋',
    passage: "Hello! My name is Anna. I am a teacher. Good morning, everyone. This is my friend Tom. He is a student. Nice to meet you. Goodbye and see you soon!",
    passageTg: "Салом! Номи ман Анна. Ман муаллим ҳастам. Субҳ ба хайр, ҳама. Ин дӯсти ман Том аст. Ӯ донишҷӯ аст. Аз шиносоӣ шодам. Хайр ва то дидор!",
    questions: [
      { q: "What is her name?", qTg: "Номи ӯ чист?", options: ["Anna", "Tom", "Sara"], correct: 0, exp: "My name is Anna." },
      { q: "What is Anna's job?", qTg: "Касби Анна чист?", options: ["Student", "Teacher", "Doctor"], correct: 1, exp: "I am a teacher." },
      { q: "Who is Tom?", qTg: "Том кист?", options: ["Her friend", "Her brother", "Her teacher"], correct: 0, exp: "This is my friend Tom." },
      { q: "What is Tom's job?", qTg: "Касби Том чист?", options: ["Teacher", "Doctor", "Student"], correct: 2, exp: "He is a student." },
    ],
  },
  {
    moduleOrder: 3,
    lessonTitle: 'Listening: Time and Numbers',
    lessonTitleTg: 'Шунавоӣ: Вақт ва рақамҳо',
    compEmoji: '🕘',
    passage: "Today is Monday. It is nine o'clock in the morning. I have English class at ten. My birthday is in May. I am twelve years old. School finishes at three.",
    passageTg: "Имрӯз душанбе аст. Соат нӯҳи субҳ аст. Ман дарси англисӣ соати даҳ дорам. Зодрӯзи ман дар моҳи май аст. Ман дувоздаҳсола ҳастам. Мактаб соати се тамом мешавад.",
    questions: [
      { q: "What day is it today?", qTg: "Имрӯз кадом рӯз аст?", options: ["Sunday", "Monday", "Friday"], correct: 1, exp: "Today is Monday." },
      { q: "What time is the English class?", qTg: "Дарси англисӣ соати чанд аст?", options: ["Nine", "Ten", "Three"], correct: 1, exp: "I have English class at ten." },
      { q: "When is the birthday?", qTg: "Зодрӯз кай аст?", options: ["In March", "In June", "In May"], correct: 2, exp: "My birthday is in May." },
      { q: "How old is the speaker?", qTg: "Гӯянда чандсола аст?", options: ["Ten", "Twelve", "Thirteen"], correct: 1, exp: "I am twelve years old." },
    ],
  },
  {
    moduleOrder: 4,
    lessonTitle: 'Listening: My Day',
    lessonTitleTg: 'Шунавоӣ: Рӯзи ман',
    compEmoji: '🌅',
    passage: "I get up at seven o'clock. I have breakfast and go to school. In the afternoon I do my homework. In the evening I watch TV with my family. I go to bed at ten o'clock.",
    passageTg: "Ман соати ҳафт бедор мешавам. Ноништа мекунам ва ба мактаб меравам. Баъдаззуҳр вазифаи хонагиро иҷро мекунам. Бегоҳӣ бо оилаам телевизор тамошо мекунам. Соати даҳ хоб меравам.",
    questions: [
      { q: "What time does he get up?", qTg: "Ӯ соати чанд бедор мешавад?", options: ["Six", "Seven", "Eight"], correct: 1, exp: "I get up at seven o'clock." },
      { q: "What does he do in the afternoon?", qTg: "Ӯ баъдаззуҳр чӣ кор мекунад?", options: ["Homework", "Breakfast", "Sleep"], correct: 0, exp: "In the afternoon I do my homework." },
      { q: "What does he do in the evening?", qTg: "Ӯ бегоҳӣ чӣ кор мекунад?", options: ["Read a book", "Watch TV", "Play football"], correct: 1, exp: "In the evening I watch TV." },
      { q: "What time does he go to bed?", qTg: "Ӯ соати чанд хоб меравад?", options: ["Nine", "Ten", "Eleven"], correct: 1, exp: "I go to bed at ten o'clock." },
    ],
  },
  {
    moduleOrder: 5,
    lessonTitle: 'Listening: Food I Like',
    lessonTitleTg: 'Шунавоӣ: Хӯроки дӯстдоштаам',
    compEmoji: '🍎',
    passage: "I like fruit very much. For breakfast I eat bread and eggs. I drink tea, but I don't like coffee. My favourite food is rice with meat. I always drink water after lunch.",
    passageTg: "Ман меваро хеле дӯст медорам. Барои ноништа нон ва тухм мехӯрам. Чой менӯшам, аммо қаҳваро дӯст намедорам. Хӯроки дӯстдоштаи ман биринҷ бо гӯшт аст. Баъди хӯроки нисфирӯзӣ ҳамеша об менӯшам.",
    questions: [
      { q: "What does she eat for breakfast?", qTg: "Ӯ барои ноништа чӣ мехӯрад?", options: ["Rice", "Bread and eggs", "Fruit"], correct: 1, exp: "For breakfast I eat bread and eggs." },
      { q: "What does she NOT like?", qTg: "Ӯ чиро дӯст намедорад?", options: ["Tea", "Water", "Coffee"], correct: 2, exp: "I don't like coffee." },
      { q: "What is her favourite food?", qTg: "Хӯроки дӯстдоштаи ӯ чист?", options: ["Rice with meat", "Bread", "Eggs"], correct: 0, exp: "My favourite food is rice with meat." },
      { q: "What does she drink after lunch?", qTg: "Ӯ баъди хӯроки нисфирӯзӣ чӣ менӯшад?", options: ["Tea", "Water", "Coffee"], correct: 1, exp: "I always drink water after lunch." },
    ],
  },
  {
    moduleOrder: 6,
    lessonTitle: 'Listening: My House',
    lessonTitleTg: 'Шунавоӣ: Хонаи ман',
    compEmoji: '🏠',
    passage: "This is my house. It has three rooms. There is a big table in the kitchen. My bed is in the bedroom. There is a television in the living room. My books are on the table.",
    passageTg: "Ин хонаи ман аст. Он се ҳуҷра дорад. Дар ошхона мизи калон ҳаст. Кати ман дар хобгоҳ аст. Дар меҳмонхона телевизор ҳаст. Китобҳои ман болои миз ҳастанд.",
    questions: [
      { q: "How many rooms are there?", qTg: "Чанд ҳуҷра ҳаст?", options: ["Two", "Three", "Four"], correct: 1, exp: "It has three rooms." },
      { q: "Where is the big table?", qTg: "Мизи калон дар куҷост?", options: ["In the kitchen", "In the bedroom", "In the living room"], correct: 0, exp: "There is a big table in the kitchen." },
      { q: "Where is the bed?", qTg: "Кат дар куҷост?", options: ["Kitchen", "Bedroom", "Living room"], correct: 1, exp: "My bed is in the bedroom." },
      { q: "Where are the books?", qTg: "Китобҳо дар куҷоянд?", options: ["On the table", "On the bed", "On the floor"], correct: 0, exp: "My books are on the table." },
    ],
  },
  {
    moduleOrder: 7,
    lessonTitle: 'Listening: At the Shop',
    lessonTitleTg: 'Шунавоӣ: Дар мағоза',
    compEmoji: '🛍️',
    passage: "I am at the shop. I want to buy a red shirt. Excuse me, how much is it? It is ten dollars. That is not expensive. I have money. Here you are. Thank you very much.",
    passageTg: "Ман дар мағоза ҳастам. Мехоҳам куртаи сурх харам. Бубахшед, чанд пул аст? Даҳ доллар аст. Ин гарон нест. Ман пул дорам. Мана гиред. Ташаккури зиёд.",
    questions: [
      { q: "What does he want to buy?", qTg: "Ӯ чӣ харидан мехоҳад?", options: ["A red shirt", "A blue hat", "Black shoes"], correct: 0, exp: "I want to buy a red shirt." },
      { q: "How much is it?", qTg: "Он чанд пул аст?", options: ["Five dollars", "Ten dollars", "Twenty dollars"], correct: 1, exp: "It is ten dollars." },
      { q: "Is it expensive?", qTg: "Он гарон аст?", options: ["Yes", "No", "Very"], correct: 1, exp: "That is not expensive." },
      { q: "Where is he?", qTg: "Ӯ дар куҷост?", options: ["At school", "At the shop", "At home"], correct: 1, exp: "I am at the shop." },
    ],
  },
  {
    moduleOrder: 8,
    lessonTitle: 'Listening: Finding the Way',
    lessonTitleTg: 'Шунавоӣ: Ёфтани роҳ',
    compEmoji: '🧭',
    passage: "Excuse me, where is the bank? Go straight on. Then turn left. The bank is next to the shop. It is near the park. It is not far. Thank you very much.",
    passageTg: "Бубахшед, бонк дар куҷост? Рост равед. Баъд ба чап гардед. Бонк паҳлӯи мағоза аст. Он наздики боғ аст. Дур нест. Ташаккури зиёд.",
    questions: [
      { q: "What place is he looking for?", qTg: "Ӯ кадом ҷойро меҷӯяд?", options: ["The shop", "The bank", "The park"], correct: 1, exp: "Where is the bank?" },
      { q: "Which way does he turn?", qTg: "Ӯ ба кадом тараф мегардад?", options: ["Left", "Right", "Back"], correct: 0, exp: "Then turn left." },
      { q: "What is the bank next to?", qTg: "Бонк паҳлӯи чист?", options: ["The park", "The shop", "The school"], correct: 1, exp: "The bank is next to the shop." },
      { q: "Is it far?", qTg: "Он дур аст?", options: ["Yes", "No", "Very far"], correct: 1, exp: "It is not far." },
    ],
  },
  {
    moduleOrder: 9,
    lessonTitle: 'Listening: What I Wear',
    lessonTitleTg: 'Шунавоӣ: Чӣ мепӯшам',
    compEmoji: '👕',
    passage: "Today I wear a blue shirt and black trousers. My shoes are white. My sister wears a red dress. Her hat is green. We like our new clothes very much.",
    passageTg: "Имрӯз ман куртаи кабуд ва шими сиёҳ мепӯшам. Пойафзоли ман сафед аст. Хоҳари ман либоси сурх мепӯшад. Кулоҳи ӯ сабз аст. Мо либосҳои нави худро хеле дӯст медорем.",
    questions: [
      { q: "What colour is his shirt?", qTg: "Куртаи ӯ кадом ранг аст?", options: ["Blue", "Black", "White"], correct: 0, exp: "I wear a blue shirt." },
      { q: "What colour are his shoes?", qTg: "Пойафзоли ӯ кадом ранг аст?", options: ["Black", "White", "Red"], correct: 1, exp: "My shoes are white." },
      { q: "What does his sister wear?", qTg: "Хоҳари ӯ чӣ мепӯшад?", options: ["A red dress", "A green hat", "Blue trousers"], correct: 0, exp: "My sister wears a red dress." },
      { q: "What colour is her hat?", qTg: "Кулоҳи ӯ кадом ранг аст?", options: ["Red", "Green", "White"], correct: 1, exp: "Her hat is green." },
    ],
  },
  {
    moduleOrder: 10,
    lessonTitle: 'Listening: At the Doctor',
    lessonTitleTg: 'Шунавоӣ: Назди духтур',
    compEmoji: '🩺',
    passage: "I don't feel well today. I have a headache and my throat hurts. I go to the doctor. The doctor gives me medicine. I must drink water and rest at home. Get well soon!",
    passageTg: "Ман имрӯз худро хуб ҳис намекунам. Сарам дард мекунад ва гулӯям дард мекунад. Ман ба назди духтур меравам. Духтур ба ман дору медиҳад. Ман бояд об нӯшам ва дар хона истироҳат кунам. Тезтар сиҳат шав!",
    questions: [
      { q: "How does she feel?", qTg: "Ӯ худро чӣ гуна ҳис мекунад?", options: ["Happy", "Not well", "Tired"], correct: 1, exp: "I don't feel well today." },
      { q: "What hurts?", qTg: "Чӣ дард мекунад?", options: ["Her leg", "Her head and throat", "Her hand"], correct: 1, exp: "I have a headache and my throat hurts." },
      { q: "Who does she go to?", qTg: "Ӯ ба назди кӣ меравад?", options: ["The teacher", "The doctor", "Her friend"], correct: 1, exp: "I go to the doctor." },
      { q: "What must she do?", qTg: "Ӯ бояд чӣ кор кунад?", options: ["Run", "Drink water and rest", "Go to school"], correct: 1, exp: "I must drink water and rest at home." },
    ],
  },
];
